/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a complete platform combining the speed of the edge with the power of serverless, designed for modern development workflows.": "Une plateforme complète combinant la vitesse de l'edge avec la puissance du serverless, conçue pour des flux de travail de développement modernes.",
    "bank-grade encryption at rest and in transit. soc2 type ii, hipaa, and gdpr compliant out of the box.": "Chiffrement de niveau bancaire, au repos comme en transit. Conforme SOC 2 type II, HIPAA et RGPD dès l'installation.",
    "build, deploy, and scale globally distributed applications in seconds. we handle the infrastructure complexity so you can focus on writing code.": "Construisez, déployez et évoluez des applications distribuées à l'échelle mondiale en quelques secondes. Nous gérons la complexité de l'infrastructure afin que vous puissiez vous concentrer sur l'écriture de code.",
    "built-in redis-compatible distributed cache": "Cache réparti compatible Redis, intégré",
    "can i deploy nexus on-premise or in my vpc?": "Puis-je déployer Nexus sur site ou dans mon VPC ?",
    "customers": "Clients",
    "deploy your application logic to 250+ edge locations worldwide. route users to the nearest node automatically.": "Déployez votre logique d'application sur plus de 250 emplacements en périphérie dans le monde entier. Dirigez les utilisateurs vers le nœud le plus proche automatiquement.",
    "everything you need to scale.": "Tout ce dont vous avez besoin pour évoluer.",
    "for production applications with growing traffic.": "Pour des applications de production avec un trafic croissant.",
    "from": "de",
    "granular metrics, distributed tracing, and structured logging integrated seamlessly without performance overhead.": "Des métriques granulaires, un traçage distribué et des journaux structurés intégrés de manière transparente sans surcharge de performance.",
    "how does billing work if i exceed my tier's limits?": "Comment fonctionne la facturation si je dépasse les limites de mon niveau ?",
    "how does nexus compare to traditional cloud providers?": "Comment Nexus se compare-t-il aux fournisseurs de cloud traditionnels ?",
    "identity-aware access controls for every microservice. assume breach mentality built into the core infrastructure.": "Contrôles d'accès sensibles à l'identité pour chaque microservice. Mentalité de violation intégrée dans l'infrastructure de base.",
    "join thousands of developers building the future on nexus. start for free, upgrade when you need to.": "Rejoignez des milliers de développeurs construisant l'avenir sur Nexus. Commencez gratuitement, passez à la version supérieure lorsque vous en avez besoin.",
    "leverage embedded machine learning models to forecast capacity needs and identify anomalies before they impact users.": "Tirez parti des modèles d'apprentissage automatique intégrés pour prévoir les besoins en capacité et identifier les anomalies avant qu'elles n'impactent les utilisateurs.",
    "loved by developers.": "Aimé par les développeurs.",
    "our edge functions support node.js, python, go, and rust natively via webassembly. you can also deploy custom docker containers for legacy application support.": "Nos fonctions en périphérie prennent en charge Node.js, Python, Go et Rust nativement via WebAssembly. Vous pouvez également déployer des conteneurs Docker personnalisés pour le support des applications héritées.",
    "perfect for side projects and evaluating nexus.": "Parfait pour des projets secondaires et pour évaluer Nexus.",
    "process millions of events per second with sub-millisecond latency. our distributed edge network ensures your data is exactly where it needs to be.": "Traitez des millions d'événements par seconde, sous la milliseconde. Notre réseau réparti place vos données exactement là où il faut.",
    "read documentation": "Lire la documentation",
    "ready to scale?": "Prêt à évoluer ?",
    "real-time processing": "Traitement en temps réel",
    "simple, transparent pricing.": "Tarification simple et transparente.",
    "start 14-day trial": "Essai de 14 jours",
    "start building free": "Commencer gratuitement",
    "the global edge platform for modern applications. build faster, scale infinitely, and sleep better at night.": "La plateforme répartie pour les applications d'aujourd'hui. Construisez plus vite, montez en charge sans limite, dormez mieux.",
    "trusted by innovative engineering teams worldwide": "Fiable par des équipes d'ingénierie innovantes dans le monde entier",
    "up to 10,000 monthly events": "Jusqu'à 10 000 événements mensuels",
    "up to 5m monthly events": "Jusqu'à 5 millions d'événements mensuels",
    "we process over 2 billion events daily. before nexus, we needed a team of 5 devops engineers just to keep the lights on. now, it just runs automatically.": "Nous traitons plus de 2 milliards d'événements par jour. Avant Nexus, nous avions besoin d'une équipe de 5 ingénieurs DevOps juste pour maintenir le service. Maintenant, cela fonctionne automatiquement.",
    "what programming languages are supported?": "Quelles langages de programmation sont pris en charge ?",
  },
  es: {
    "a complete platform combining the speed of the edge with the power of serverless, designed for modern development workflows.": "Una plataforma completa que combina la velocidad del edge con el poder del serverless, diseñada para flujos de trabajo de desarrollo modernos.",
    "bank-grade encryption at rest and in transit. soc2 type ii, hipaa, and gdpr compliant out of the box.": "Cifrado de nivel bancario, en reposo y en tránsito. Conforme a SOC 2 tipo II, HIPAA y RGPD desde el primer día.",
    "build, deploy, and scale globally distributed applications in seconds. we handle the infrastructure complexity so you can focus on writing code.": "Construya, despliegue y escale aplicaciones distribuidas globalmente en segundos. Nos encargamos de la complejidad de la infraestructura para que pueda centrarse en escribir código.",
    "built-in redis-compatible distributed cache": "Caché distribuida compatible con Redis, integrada",
    "can i deploy nexus on-premise or in my vpc?": "¿Puedo desplegar Nexus en las instalaciones o en mi VPC?",
    "customers": "Clientes",
    "deploy your application logic to 250+ edge locations worldwide. route users to the nearest node automatically.": "Despliega la lógica de tu aplicación en más de 250 ubicaciones en el borde en todo el mundo. Rutea a los usuarios al nodo más cercano automáticamente.",
    "everything you need to scale.": "Todo lo que necesita para escalar.",
    "for production applications with growing traffic.": "Para aplicaciones de producción con tráfico creciente.",
    "from": "de",
    "granular metrics, distributed tracing, and structured logging integrated seamlessly without performance overhead.": "Métricas granulares, trazado distribuido y registro estructurado integrados sin problemas y sin sobrecarga de rendimiento.",
    "how does billing work if i exceed my tier's limits?": "¿Cómo funciona la facturación si supero los límites de mi nivel?",
    "how does nexus compare to traditional cloud providers?": "¿Cómo se compara Nexus con los proveedores de nube tradicionales?",
    "identity-aware access controls for every microservice. assume breach mentality built into the core infrastructure.": "Controles de acceso conscientes de la identidad para cada microservicio. Mentalidad de asunción de brechas integrada en la infraestructura central.",
    "join thousands of developers building the future on nexus. start for free, upgrade when you need to.": "Únase a miles de desarrolladores que están construyendo el futuro en Nexus. Comience gratis, actualice cuando lo necesite.",
    "leverage embedded machine learning models to forecast capacity needs and identify anomalies before they impact users.": "Aprovecha los modelos de aprendizaje automático integrados para prever las necesidades de capacidad e identificar anomalías antes de que afecten a los usuarios.",
    "loved by developers.": "Amado por los desarrolladores.",
    "our edge functions support node.js, python, go, and rust natively via webassembly. you can also deploy custom docker containers for legacy application support.": "Nuestras funciones de borde admiten Node.js, Python, Go y Rust de forma nativa a través de WebAssembly. También puedes desplegar contenedores Docker personalizados para soporte de aplicaciones heredadas.",
    "perfect for side projects and evaluating nexus.": "Perfecto para proyectos secundarios y para evaluar Nexus.",
    "process millions of events per second with sub-millisecond latency. our distributed edge network ensures your data is exactly where it needs to be.": "Procese millones de eventos por segundo, por debajo del milisegundo. Nuestra red distribuida coloca sus datos exactamente donde deben estar.",
    "read documentation": "Leer la documentación",
    "ready to scale?": "¿Listo para escalar?",
    "real-time processing": "Procesamiento en tiempo real",
    "simple, transparent pricing.": "Precios simples y transparentes.",
    "start 14-day trial": "Prueba de 14 días",
    "start building free": "Empezar gratis",
    "the global edge platform for modern applications. build faster, scale infinitely, and sleep better at night.": "La plataforma distribuida para las aplicaciones de hoy. Construya más rápido, escale sin límite y duerma mejor.",
    "trusted by innovative engineering teams worldwide": "Confiado por equipos de ingeniería innovadores en todo el mundo",
    "up to 10,000 monthly events": "Hasta 10,000 eventos mensuales",
    "up to 5m monthly events": "Hasta 5 millones de eventos mensuales",
    "we process over 2 billion events daily. before nexus, we needed a team of 5 devops engineers just to keep the lights on. now, it just runs automatically.": "Procesamos más de 2 mil millones de eventos diariamente. Antes de Nexus, necesitábamos un equipo de 5 ingenieros DevOps solo para mantener el servicio. Ahora, simplemente funciona automáticamente.",
    "what programming languages are supported?": "¿Qué lenguajes de programación son compatibles?",
  },
  de: {
    "a complete platform combining the speed of the edge with the power of serverless, designed for modern development workflows.": "Eine vollständige Plattform, die die Geschwindigkeit des Edge mit der Leistung von Serverless kombiniert, entworfen für moderne Entwicklungs-Workflows.",
    "bank-grade encryption at rest and in transit. soc2 type ii, hipaa, and gdpr compliant out of the box.": "Verschlüsselung auf Bankniveau, im Ruhezustand wie bei der Übertragung. SOC 2 Typ II, HIPAA und DSGVO ab Werk.",
    "build, deploy, and scale globally distributed applications in seconds. we handle the infrastructure complexity so you can focus on writing code.": "Bauen, bereitstellen und global verteilte Anwendungen in Sekunden skalieren. Wir kümmern uns um die Infrastrukturkomplexität, damit Sie sich auf das Schreiben von Code konzentrieren können.",
    "built-in redis-compatible distributed cache": "Integrierter verteilter Cache, Redis-kompatibel",
    "can i deploy nexus on-premise or in my vpc?": "Kann ich Nexus vor Ort oder in meinem VPC bereitstellen?",
    "customers": "Kunden",
    "deploy your application logic to 250+ edge locations worldwide. route users to the nearest node automatically.": "Stellen Sie Ihre Anwendungslogik an über 250 Edge-Standorten weltweit bereit. Leiten Sie Benutzer automatisch zum nächstgelegenen Knoten.",
    "everything you need to scale.": "Alles, was Sie zum Skalieren benötigen.",
    "for production applications with growing traffic.": "Für Produktionsanwendungen mit wachsendem Verkehr.",
    "from": "von",
    "granular metrics, distributed tracing, and structured logging integrated seamlessly without performance overhead.": "Granulare Metriken, verteiltes Tracing und strukturierte Protokollierung nahtlos integriert, ohne Leistungsüberhang.",
    "how does billing work if i exceed my tier's limits?": "Wie funktioniert die Abrechnung, wenn ich die Grenzen meiner Stufe überschreite?",
    "how does nexus compare to traditional cloud providers?": "Wie schneidet Nexus im Vergleich zu traditionellen Cloud-Anbietern ab?",
    "identity-aware access controls for every microservice. assume breach mentality built into the core infrastructure.": "Identitätsbewusste Zugriffskontrollen für jeden Microservice. Annahme einer Verletzungsmentalität, die in die Kerninfrastruktur integriert ist.",
    "join thousands of developers building the future on nexus. start for free, upgrade when you need to.": "Schließen Sie sich Tausenden von Entwicklern an, die die Zukunft auf Nexus aufbauen. Starten Sie kostenlos, upgraden Sie, wenn Sie es benötigen.",
    "leverage embedded machine learning models to forecast capacity needs and identify anomalies before they impact users.": "Nutzen Sie eingebettete Machine-Learning-Modelle, um den Kapazitätsbedarf vorherzusagen und Anomalien zu identifizieren, bevor sie die Benutzer beeinträchtigen.",
    "loved by developers.": "Von Entwicklern geliebt.",
    "our edge functions support node.js, python, go, and rust natively via webassembly. you can also deploy custom docker containers for legacy application support.": "Unsere Edge-Funktionen unterstützen Node.js, Python, Go und Rust nativ über WebAssembly. Sie können auch benutzerdefinierte Docker-Container für die Unterstützung von Legacy-Anwendungen bereitstellen.",
    "perfect for side projects and evaluating nexus.": "Perfekt für Nebenprojekte und zur Bewertung von Nexus.",
    "process millions of events per second with sub-millisecond latency. our distributed edge network ensures your data is exactly where it needs to be.": "Verarbeiten Sie Millionen Ereignisse pro Sekunde, unter einer Millisekunde. Unser verteiltes Netz legt Ihre Daten genau dorthin, wo sie hingehören.",
    "read documentation": "Dokumentation lesen",
    "ready to scale?": "Bereit zum Skalieren?",
    "real-time processing": "Echtzeitverarbeitung",
    "simple, transparent pricing.": "Einfache, transparente Preisgestaltung.",
    "start 14-day trial": "14 Tage testen",
    "start building free": "Kostenlos loslegen",
    "the global edge platform for modern applications. build faster, scale infinitely, and sleep better at night.": "Die verteilte Plattform für moderne Anwendungen. Schneller bauen, unbegrenzt skalieren, ruhiger schlafen.",
    "trusted by innovative engineering teams worldwide": "Vertraut von innovativen Ingenieurteams weltweit",
    "up to 10,000 monthly events": "Bis zu 10.000 monatlichen Veranstaltungen",
    "up to 5m monthly events": "Bis zu 5 Millionen monatlichen Veranstaltungen",
    "we process over 2 billion events daily. before nexus, we needed a team of 5 devops engineers just to keep the lights on. now, it just runs automatically.": "Wir verarbeiten täglich über 2 Milliarden Ereignisse. Vor Nexus benötigten wir ein Team von 5 DevOps-Ingenieuren, nur um den Betrieb aufrechtzuerhalten. Jetzt läuft es einfach automatisch.",
    "what programming languages are supported?": "Welche Programmiersprachen werden unterstützt?",
  },
  pt: {
    "a complete platform combining the speed of the edge with the power of serverless, designed for modern development workflows.": "Uma plataforma completa que combina a velocidade da edge com o poder do serverless, projetada para fluxos de trabalho de desenvolvimento modernos.",
    "bank-grade encryption at rest and in transit. soc2 type ii, hipaa, and gdpr compliant out of the box.": "Cifragem de nível bancário, em repouso e em trânsito. Conforme SOC 2 tipo II, HIPAA e RGPD desde o início.",
    "build, deploy, and scale globally distributed applications in seconds. we handle the infrastructure complexity so you can focus on writing code.": "Construa, implemente e escale aplicações distribuídas globalmente em segundos. Nós cuidamos da complexidade da infraestrutura para que você possa se concentrar em escrever código.",
    "built-in redis-compatible distributed cache": "Cache distribuída compatível com Redis, integrada",
    "can i deploy nexus on-premise or in my vpc?": "Posso implantar o Nexus no local ou na minha VPC?",
    "customers": "Clientes",
    "deploy your application logic to 250+ edge locations worldwide. route users to the nearest node automatically.": "Implante a lógica da sua aplicação em mais de 250 locais de borda em todo o mundo. Roteie os utilizadores automaticamente para o nó mais próximo.",
    "everything you need to scale.": "Tudo o que você precisa para escalar.",
    "for production applications with growing traffic.": "Para aplicações de produção com tráfego crescente.",
    "from": "de",
    "granular metrics, distributed tracing, and structured logging integrated seamlessly without performance overhead.": "Métricas granulares, rastreamento distribuído e registos estruturados integrados de forma transparente, sem sobrecarga de desempenho.",
    "how does billing work if i exceed my tier's limits?": "Como funciona a faturação se eu exceder os limites do meu nível?",
    "how does nexus compare to traditional cloud providers?": "Como é que o Nexus se compara com os fornecedores de nuvem tradicionais?",
    "identity-aware access controls for every microservice. assume breach mentality built into the core infrastructure.": "Controles de acesso conscientes da identidade para cada microserviço. Mentalidade de assunção de violação integrada na infraestrutura central.",
    "join thousands of developers building the future on nexus. start for free, upgrade when you need to.": "Junte-se a milhares de desenvolvedores construindo o futuro no Nexus. Comece gratuitamente, faça upgrade quando precisar.",
    "leverage embedded machine learning models to forecast capacity needs and identify anomalies before they impact users.": "Aproveite os modelos de aprendizagem automática integrados para prever as necessidades de capacidade e identificar anomalias antes que afetem os utilizadores.",
    "loved by developers.": "Amado pelos desenvolvedores.",
    "our edge functions support node.js, python, go, and rust natively via webassembly. you can also deploy custom docker containers for legacy application support.": "As nossas funções de borda suportam Node.js, Python, Go e Rust nativamente via WebAssembly. Também pode implantar contentores Docker personalizados para suporte a aplicações legadas.",
    "perfect for side projects and evaluating nexus.": "Perfeito para projetos paralelos e para avaliar o Nexus.",
    "process millions of events per second with sub-millisecond latency. our distributed edge network ensures your data is exactly where it needs to be.": "Processe milhões de eventos por segundo, abaixo do milissegundo. A nossa rede distribuída coloca os seus dados exatamente onde devem estar.",
    "read documentation": "Ler a documentação",
    "ready to scale?": "Pronto para escalar?",
    "real-time processing": "Processamento em tempo real",
    "simple, transparent pricing.": "Preços simples e transparentes.",
    "start 14-day trial": "Teste de 14 dias",
    "start building free": "Começar gratuitamente",
    "the global edge platform for modern applications. build faster, scale infinitely, and sleep better at night.": "A plataforma distribuída para as aplicações de hoje. Construa mais depressa, escale sem limite e durma melhor.",
    "trusted by innovative engineering teams worldwide": "Confiável por equipes de engenharia inovadoras em todo o mundo",
    "up to 10,000 monthly events": "Até 10.000 eventos mensais",
    "up to 5m monthly events": "Até 5 milhões de eventos mensais",
    "we process over 2 billion events daily. before nexus, we needed a team of 5 devops engineers just to keep the lights on. now, it just runs automatically.": "Processamos mais de 2 mil milhões de eventos diariamente. Antes do Nexus, precisávamos de uma equipa de 5 engenheiros DevOps apenas para manter o serviço. Agora, funciona automaticamente.",
    "what programming languages are supported?": "Quais linguagens de programação são suportadas?",
  },
};
