/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "the journal of the palace": "Le Journal du Palais",
    "our chronicles of the art of living, travel and gastronomy, written to the rhythm of the seasons.": "Nos chroniques de l'art de vivre, du voyage et de la gastronomie, écrites au rythme des saisons.",
    "the french art of the table, a living heritage": "L'art de la table à la française, un patrimoine vivant",
    "from the fold of the cloth to the choice of crystal, the french table is a silent choreography. a look inside a craft the grand palais perpetuates every evening.": "Du pli de la nappe au choix du cristal, la table française est une chorégraphie silencieuse. Regard sur un savoir-faire que le Grand Palais perpétue chaque soir.",
    "an escape to the loire valley": "Une échappée dans le Val de Loire",
    "four exceptional categories, each a variation on the same art of welcoming. choose your refuge.": "Quatre catégories d'exception, chacune une variation du même art de recevoir. Choisissez votre refuge.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring and a private terrace overlooking the sculpted garden.": "Un refuge d'un calme soigné : lin cousu main, parquet de chêne ancien et terrasse privée sur le jardin sculpté.",
    "soaring ceilings, a double marble bathroom and floor-to-ceiling windows that frame the park like a living painting.": "Hauteur sous plafond, salle de bains double en marbre et baies vitrées qui cadrent le parc comme un tableau vivant.",
    "our most coveted address. a private dining room, a butler antechamber and a rooftop terrace over the skyline.": "Notre adresse la plus recherchée : salle à manger privée, antichambre de majordome et terrasse sur les toits.",
    "a palace of quiet distinction at the heart of": "Un palace d'une distinction discrète, au cœur de",
    "spa, gastronomy, concierge: every service at the grand palais is designed so that everything feels simple and natural.": "Spa, gastronomie, conciergerie : chaque service du Grand Palais est pensé pour que tout paraisse simple et naturel.",
    "seven treatment rooms, a roman hammam and a 25-metre heated pool. every ritual is bespoke, every moment restorative.": "Sept cabines de soin, un hammam romain et un bassin chauffé de 25 mètres. Chaque rituel est sur mesure, chaque moment répare.",
    "chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "La cheffe Margaux Vernet réinvente le répertoire français avec des produits cultivés à cinquante mètres des fourneaux. Le menu dégustation change avec la lune.",
    "rooms": "Chambres",
    "reserve": "Réserver",
    "palace — founded 1887": "Palace — depuis 1887",
    "rooms & suites": "Chambres et suites",
    "hectares of gardens": "Hectares de jardins",
    "accommodations": "Hébergements",
    "most requested": "La plus demandée",
    "courtyard garden": "Jardin intérieur",
    "prestige room": "Chambre Prestige",
    "/night": "/nuit",
    "guest favourite": "La préférée des clients",
    "panoramic park": "Vue panoramique sur le parc",
    "deluxe suite": "Suite Deluxe",
    "city skyline": "Vue sur les toits",
    "grand suite": "Grande Suite",
    "two michelin stars": "Deux étoiles au Michelin",
    "spa & thermal circuit": "Spa et parcours thermal",
    "rare spirits & cellar": "Spiritueux rares et cave",
    "gastronomy": "Gastronomie",
    "breakfast": "Petit-déjeuner",
    "guest voices": "Paroles de clients",
    "address": "Adresse",
    "telephone": "Téléphone",
    "available 24 hours": "Joignable 24 h/24",
    "eiffel tower": "Tour Eiffel",
    "cdg airport": "Aéroport Roissy-CDG",
    "arrival": "Arrivée",
    "departure": "Départ",
    "guests": "Voyageurs",
    "check availability": "Vérifier les disponibilités",
    "stay": "Le séjour",
    "presidential suite": "Suite présidentielle",
    "experiences": "Expériences",
    "private events": "Événements privés",
    "information": "Informations",
    "where time is measured not in hours, but in moments that endure.": "Où le temps ne se compte pas en heures, mais en moments qui restent.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring, and a private terrace overlooking the sculpted inner garden.": "Un refuge d'un calme soigné : lin cousu main, parquet de chêne ancien et terrasse privée sur le jardin intérieur.",
    "soaring ceilings, a double marble bathroom, and floor-to-ceiling windows that frame the park like a living painting.": "Hauteur sous plafond, salle de bains double en marbre et baies vitrées qui cadrent le parc comme un tableau vivant.",
    "our most coveted address. a private dining room, butler antechamber, and a rooftop terrace overlooking the golden skyline at dusk.": "Notre adresse la plus recherchée : salle à manger privée, antichambre de majordome et terrasse sur les toits, face au ciel doré du soir.",
    "view all rooms & suites": "Voir toutes les chambres et suites",
    "chef margaux vernet elevates classical french gastronomy with ingredients sourced from our estate gardens and trusted regional producers.": "La cheffe revisite la grande cuisine française avec les produits du potager de la maison et ceux de producteurs de la région.",
    "seven treatment rooms, a roman hammam, and a 25m heated pool. every ritual is bespoke, every moment restorative.": "Sept cabines de soin, un hammam romain et un bassin chauffé de 25 mètres. Chaque rituel est sur mesure ; chaque moment répare.",
    "an intimate bar presided over by our maître d'alcools. three thousand labels. one extraordinary conversation.": "Un bar intime tenu par notre maître des alcools. Trois mille références. Une conversation d'exception.",
    "an experience that redefined our expectations of hospitality. every detail, every gesture — flawless.": "Une expérience qui a redéfini ce que nous attendions de l'hôtellerie. Chaque détail, chaque geste — impeccable.",
    "\"luxury is the ease of a t-shirt in a very expensive dress.\"": "« Le luxe, c'est l'aisance d'un tee-shirt dans une robe très chère. »",
    "← all articles": "← Tous les articles",
    "← all rooms": "← Toutes les chambres",
    "at the heart of": "Au cœur de",
    "attended to": "Pris en charge",
    "data from the contact form is kept for the time necessary to process your request, then archived or deleted in accordance with applicable legal obligations.": "Les données du formulaire de contact sont conservées le temps nécessaire au traitement de votre demande, puis archivées ou supprimées conformément aux obligations légales applicables.",
    "discover →": "Découvrez →",
    "discover our suites": "Découvrir nos suites",
    "eight hundred metres from the opéra. a fifteen-minute walk to the louvre.": "À huit cents mètres de l'Opéra. Quinze minutes à pied du Louvre.",
    "every sense,": "Chaque sens,",
    "for private hire, events or long-stay enquiries, our concierge replies within 24 hours.": "Pour les locations privées, les événements ou les demandes de séjours prolongés, notre concierge répond dans les 24 heures.",
    "from": "De",
    "let us compose your stay together": "Composons votre séjour ensemble",
    "live the": "Vivez le",
    "our concierge is available at every hour to orchestrate a stay that is entirely yours.": "Notre concierge est disponible à toute heure pour orchestrer un séjour qui vous ressemble entièrement.",
    "our concierge team is available at every hour to craft a stay that is entirely, irreducibly yours.": "Notre conciergerie est joignable à toute heure pour composer un séjour qui n'appartienne qu'à vous.",
    "purpose and legal basis": "Objetif et base légale",
    "read the article →": "Lire l'article →",
    "request sent": "Demande envoyée",
    "send my request": "Envoyer ma demande",
    "thank you. our concierge will reply within 24 hours.": "Merci. Notre concierge répondra dans les 24 heures.",
    "the city of light": "la Ville Lumière",
    "the controller of personal data is": "Le responsable des données personnelles est",
    "the information published on this site is provided for guidance only. the visuals and rates shown are not contractual and may change without notice.": "Les informations publiées sur ce site sont fournies à titre indicatif seulement. Les visuels et les tarifs affichés ne sont pas contractuels et peuvent changer sans préavis.",
    "this site does not place advertising tracking cookies. only technical cookies strictly necessary for the operation of the site may be used.": "Ce site ne place pas de cookies de suivi publicitaire. Seuls les cookies techniques strictement nécessaires au fonctionnement du site peuvent être utilisés.",
    "two michelin stars. chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "Deux étoiles au Michelin. La cheffe Margaux Vernet réinvente le répertoire français avec des produits cultivés à cinquante mètres des fourneaux. Le menu dégustation change avec la lune.",
    "unfolds at your threshold.": "s'ouvre à votre porte.",
    "vat not applicable, art. 293 b of the french tax code (cgi).": "TVA non applicable, art. 293 B du Code général des impôts (CGI).",
    "view all rooms & suites": "Voir Toutes les Chambres & Suites",
    "virtual journey": "Voyage Virtuel",
    "your rights": "Vos droits",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "the journal of the palace": "El Diario del Palacio",
    "our chronicles of the art of living, travel and gastronomy, written to the rhythm of the seasons.": "Nuestras crónicas del arte de vivir, los viajes y la gastronomía, escritas al ritmo de las estaciones.",
    "the french art of the table, a living heritage": "El arte de la mesa a la francesa, un patrimonio vivo",
    "from the fold of the cloth to the choice of crystal, the french table is a silent choreography. a look inside a craft the grand palais perpetuates every evening.": "Del pliegue del mantel a la elección del cristal, la mesa francesa es una coreografía silenciosa. Una mirada a un oficio que el Grand Palais perpetúa cada noche.",
    "an escape to the loire valley": "Una escapada al Valle del Loira",
    "four exceptional categories, each a variation on the same art of welcoming. choose your refuge.": "Cuatro categorías excepcionales, cada una una variación del mismo arte de recibir. Elija su refugio.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring and a private terrace overlooking the sculpted garden.": "Un refugio de calma refinada: lino cosido a mano, parqué de roble antiguo y terraza privada sobre el jardín esculpido.",
    "soaring ceilings, a double marble bathroom and floor-to-ceiling windows that frame the park like a living painting.": "Techos altos, baño doble de mármol y ventanales que enmarcan el parque como un cuadro vivo.",
    "our most coveted address. a private dining room, a butler antechamber and a rooftop terrace over the skyline.": "Nuestra dirección más codiciada: comedor privado, antecámara de mayordomo y terraza en la azotea.",
    "a palace of quiet distinction at the heart of": "Un palacio de distinción discreta, en el corazón de",
    "spa, gastronomy, concierge: every service at the grand palais is designed so that everything feels simple and natural.": "Spa, gastronomía, conserjería: cada servicio del Grand Palais está pensado para que todo parezca simple y natural.",
    "seven treatment rooms, a roman hammam and a 25-metre heated pool. every ritual is bespoke, every moment restorative.": "Siete cabinas de tratamiento, un hammam romano y una piscina climatizada de 25 metros. Cada ritual es a medida, cada momento repara.",
    "chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "La chef Margaux Vernet reinventa el repertorio francés con productos cultivados a cincuenta metros de los fogones. El menú degustación cambia con la luna.",
    "rooms": "Habitaciones",
    "reserve": "Reservar",
    "palace — founded 1887": "Palace — desde 1887",
    "rooms & suites": "Habitaciones y suites",
    "hectares of gardens": "Hectáreas de jardines",
    "accommodations": "Alojamientos",
    "most requested": "La más solicitada",
    "courtyard garden": "Jardín interior",
    "prestige room": "Habitación Prestige",
    "/night": "/noche",
    "guest favourite": "La favorita de los clientes",
    "panoramic park": "Vista panorámica al parque",
    "deluxe suite": "Suite Deluxe",
    "city skyline": "Vista a los tejados",
    "grand suite": "Gran Suite",
    "two michelin stars": "Dos estrellas Michelin",
    "spa & thermal circuit": "Spa y circuito termal",
    "rare spirits & cellar": "Licores raros y bodega",
    "gastronomy": "Gastronomía",
    "breakfast": "Desayuno",
    "guest voices": "Voces de los clientes",
    "address": "Dirección",
    "telephone": "Teléfono",
    "available 24 hours": "Disponible 24 h",
    "eiffel tower": "Torre Eiffel",
    "cdg airport": "Aeropuerto Roissy-CDG",
    "arrival": "Llegada",
    "departure": "Salida",
    "guests": "Huéspedes",
    "check availability": "Ver disponibilidad",
    "stay": "La estancia",
    "presidential suite": "Suite presidencial",
    "experiences": "Experiencias",
    "private events": "Eventos privados",
    "information": "Información",
    "where time is measured not in hours, but in moments that endure.": "Donde el tiempo no se cuenta en horas, sino en momentos que quedan.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring, and a private terrace overlooking the sculpted inner garden.": "Un refugio de calma cuidada: lino cosido a mano, roble antiguo en el suelo y terraza privada sobre el jardín interior.",
    "soaring ceilings, a double marble bathroom, and floor-to-ceiling windows that frame the park like a living painting.": "Altura de techo, baño doble en mármol y ventanales que encuadran el parque como un cuadro vivo.",
    "our most coveted address. a private dining room, butler antechamber, and a rooftop terrace overlooking the golden skyline at dusk.": "Nuestra dirección más buscada: comedor privado, antecámara de mayordomo y terraza sobre los tejados, frente al cielo dorado del atardecer.",
    "view all rooms & suites": "Ver todas las habitaciones y suites",
    "chef margaux vernet elevates classical french gastronomy with ingredients sourced from our estate gardens and trusted regional producers.": "La chef reinterpreta la gran cocina francesa con los productos del huerto de la casa y de productores de la región.",
    "seven treatment rooms, a roman hammam, and a 25m heated pool. every ritual is bespoke, every moment restorative.": "Siete cabinas de tratamiento, un hamam romano y una piscina climatizada de 25 metros. Cada ritual es a medida; cada momento repara.",
    "an intimate bar presided over by our maître d'alcools. three thousand labels. one extraordinary conversation.": "Un bar íntimo dirigido por nuestro maestro de licores. Tres mil referencias. Una conversación excepcional.",
    "an experience that redefined our expectations of hospitality. every detail, every gesture — flawless.": "Una experiencia que redefinió lo que esperábamos de la hostelería. Cada detalle, cada gesto — impecable.",
    "\"luxury is the ease of a t-shirt in a very expensive dress.\"": "«El lujo es la comodidad de una camiseta en un vestido carísimo.»",
    "← all articles": "← Todos los artículos",
    "← all rooms": "← Todas las habitaciones",
    "at the heart of": "En el corazón de",
    "attended to": "Atendido",
    "data from the contact form is kept for the time necessary to process your request, then archived or deleted in accordance with applicable legal obligations.": "Los datos del formulario de contacto se conservan el tiempo necesario para procesar su solicitud, luego se archivan o eliminan de acuerdo con las obligaciones legales aplicables.",
    "discover →": "Descubre →",
    "discover our suites": "Descubrir nuestras suites",
    "eight hundred metres from the opéra. a fifteen-minute walk to the louvre.": "A ochocientos metros de la Ópera. A quince minutos a pie del Louvre.",
    "every sense,": "Cada sentido,",
    "for private hire, events or long-stay enquiries, our concierge replies within 24 hours.": "Para alquileres privados, eventos o consultas de estancias largas, nuestro conserje responde en un plazo de 24 horas.",
    "from": "Desde",
    "let us compose your stay together": "Compongamos su estancia juntos",
    "live the": "Viva el",
    "our concierge is available at every hour to orchestrate a stay that is entirely yours.": "Nuestro conserje está disponible a cualquier hora para orquestar una estancia que sea completamente suya.",
    "our concierge team is available at every hour to craft a stay that is entirely, irreducibly yours.": "Nuestra conserjería está disponible a cualquier hora para componer una estancia que sea solo suya.",
    "purpose and legal basis": "Propósito y base legal",
    "read the article →": "Leer el artículo →",
    "request sent": "Solicitud enviada",
    "send my request": "Enviar mi solicitud",
    "thank you. our concierge will reply within 24 hours.": "Gracias. Nuestro conserje responderá en un plazo de 24 horas.",
    "the city of light": "la Ciudad de la Luz",
    "the controller of personal data is": "El responsable de los datos personales es",
    "the information published on this site is provided for guidance only. the visuals and rates shown are not contractual and may change without notice.": "La información publicada en este sitio se proporciona solo como guía. Las imágenes y tarifas mostradas no son contractuales y pueden cambiar sin previo aviso.",
    "this site does not place advertising tracking cookies. only technical cookies strictly necessary for the operation of the site may be used.": "Este sitio no coloca cookies de seguimiento publicitario. Solo se pueden utilizar cookies técnicas estrictamente necesarias para el funcionamiento del sitio.",
    "two michelin stars. chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "Dos estrellas Michelin. La chef Margaux Vernet reinventa el repertorio francés con productos cultivados a cincuenta metros de los fogones. El menú degustación cambia con la luna.",
    "unfolds at your threshold.": "se abre a su puerta.",
    "vat not applicable, art. 293 b of the french tax code (cgi).": "IVA no aplicable, art. 293 B del Código General de Impuestos (CGI).",
    "view all rooms & suites": "Ver Todas las Habitaciones & Suites",
    "virtual journey": "Viaje Virtual",
    "your rights": "Tus derechos",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "the journal of the palace": "Das Journal des Palasts",
    "our chronicles of the art of living, travel and gastronomy, written to the rhythm of the seasons.": "Unsere Chroniken der Lebenskunst, des Reisens und der Gastronomie, im Rhythmus der Jahreszeiten geschrieben.",
    "the french art of the table, a living heritage": "Die französische Tischkultur, ein lebendiges Erbe",
    "from the fold of the cloth to the choice of crystal, the french table is a silent choreography. a look inside a craft the grand palais perpetuates every evening.": "Von der Faltung des Tischtuchs bis zur Wahl des Kristalls ist die französische Tafel eine stille Choreografie. Ein Blick auf ein Handwerk, das das Grand Palais jeden Abend fortführt.",
    "an escape to the loire valley": "Ein Ausflug ins Loiretal",
    "four exceptional categories, each a variation on the same art of welcoming. choose your refuge.": "Vier außergewöhnliche Kategorien, jede eine Variation derselben Kunst des Empfangens. Wählen Sie Ihr Refugium.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring and a private terrace overlooking the sculpted garden.": "Ein Refugium gepflegter Ruhe: handgenähtes Leinen, alter Eichenboden und eine private Terrasse zum Skulpturengarten.",
    "soaring ceilings, a double marble bathroom and floor-to-ceiling windows that frame the park like a living painting.": "Hohe Decken, ein doppeltes Marmorbad und raumhohe Fenster, die den Park wie ein lebendes Gemälde rahmen.",
    "our most coveted address. a private dining room, a butler antechamber and a rooftop terrace over the skyline.": "Unsere begehrteste Adresse: privates Esszimmer, Butler-Vorzimmer und Dachterrasse über der Stadt.",
    "a palace of quiet distinction at the heart of": "Ein Palasthotel leiser Vornehmheit, im Herzen von",
    "spa, gastronomy, concierge: every service at the grand palais is designed so that everything feels simple and natural.": "Spa, Gastronomie, Concierge: Jeder Service des Grand Palais ist so gedacht, dass alles einfach und selbstverständlich wirkt.",
    "seven treatment rooms, a roman hammam and a 25-metre heated pool. every ritual is bespoke, every moment restorative.": "Sieben Behandlungsräume, ein römisches Hamam und ein beheiztes 25-Meter-Becken. Jedes Ritual ist maßgeschneidert, jeder Moment heilsam.",
    "chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "Chefköchin Margaux Vernet erfindet den französischen Kanon neu, mit Erzeugnissen, die fünfzig Meter von der Küche wachsen. Das Degustationsmenü wechselt mit dem Mond.",
    "rooms": "Zimmer",
    "reserve": "Reservieren",
    "palace — founded 1887": "Palasthotel — seit 1887",
    "rooms & suites": "Zimmer und Suiten",
    "hectares of gardens": "Hektar Gärten",
    "accommodations": "Unterkünfte",
    "most requested": "Am häufigsten gefragt",
    "courtyard garden": "Innenhofgarten",
    "prestige room": "Prestige-Zimmer",
    "/night": "/Nacht",
    "guest favourite": "Gästeliebling",
    "panoramic park": "Panoramablick auf den Park",
    "deluxe suite": "Deluxe-Suite",
    "city skyline": "Blick über die Dächer",
    "grand suite": "Grand Suite",
    "two michelin stars": "Zwei Michelin-Sterne",
    "spa & thermal circuit": "Spa und Thermalparcours",
    "rare spirits & cellar": "Seltene Spirituosen und Weinkeller",
    "gastronomy": "Gastronomie",
    "breakfast": "Frühstück",
    "guest voices": "Gästestimmen",
    "address": "Adresse",
    "telephone": "Telefon",
    "available 24 hours": "Rund um die Uhr erreichbar",
    "eiffel tower": "Eiffelturm",
    "cdg airport": "Flughafen Roissy-CDG",
    "arrival": "Anreise",
    "departure": "Abreise",
    "guests": "Gäste",
    "check availability": "Verfügbarkeit prüfen",
    "stay": "Der Aufenthalt",
    "presidential suite": "Präsidentensuite",
    "experiences": "Erlebnisse",
    "private events": "Private Veranstaltungen",
    "information": "Informationen",
    "where time is measured not in hours, but in moments that endure.": "Wo die Zeit nicht in Stunden zählt, sondern in Momenten, die bleiben.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring, and a private terrace overlooking the sculpted inner garden.": "Ein Rückzugsort von gepflegter Ruhe: handvernähtes Leinen, alter Eichenboden und private Terrasse zum Innengarten.",
    "soaring ceilings, a double marble bathroom, and floor-to-ceiling windows that frame the park like a living painting.": "Hohe Decken, doppeltes Marmorbad und raumhohe Fenster, die den Park wie ein lebendes Bild rahmen.",
    "our most coveted address. a private dining room, butler antechamber, and a rooftop terrace overlooking the golden skyline at dusk.": "Unsere begehrteste Adresse: privates Esszimmer, Butler-Vorzimmer und Dachterrasse vor dem goldenen Abendhimmel.",
    "view all rooms & suites": "Alle Zimmer und Suiten ansehen",
    "chef margaux vernet elevates classical french gastronomy with ingredients sourced from our estate gardens and trusted regional producers.": "Die Küchenchefin interpretiert die große französische Küche mit Produkten aus dem hauseigenen Garten und von regionalen Erzeugern.",
    "seven treatment rooms, a roman hammam, and a 25m heated pool. every ritual is bespoke, every moment restorative.": "Sieben Behandlungsräume, ein römisches Hamam und ein 25-Meter-Becken. Jedes Ritual ist maßgeschneidert; jeder Moment heilt.",
    "an intimate bar presided over by our maître d'alcools. three thousand labels. one extraordinary conversation.": "Eine intime Bar, geführt von unserem Maître d'Alcools. Dreitausend Etiketten. Ein außergewöhnliches Gespräch.",
    "an experience that redefined our expectations of hospitality. every detail, every gesture — flawless.": "Ein Erlebnis, das unsere Erwartungen an Hotellerie neu definiert hat. Jedes Detail, jede Geste — makellos.",
    "\"luxury is the ease of a t-shirt in a very expensive dress.\"": "„Luxus ist die Leichtigkeit eines T-Shirts in einem sehr teuren Kleid.“",
    "← all articles": "← Alle Artikel",
    "← all rooms": "← Alle Zimmer",
    "at the heart of": "Im Herzen von",
    "attended to": "Bearbeitet",
    "data from the contact form is kept for the time necessary to process your request, then archived or deleted in accordance with applicable legal obligations.": "Die Daten aus dem Kontaktformular werden für die Zeit aufbewahrt, die zur Bearbeitung Ihrer Anfrage erforderlich ist, und dann gemäß den geltenden gesetzlichen Verpflichtungen archiviert oder gelöscht.",
    "discover →": "Entdecken →",
    "discover our suites": "Unsere Suiten entdecken",
    "eight hundred metres from the opéra. a fifteen-minute walk to the louvre.": "Achthundert Meter von der Oper. Fünfzehn Gehminuten zum Louvre.",
    "every sense,": "Jeder Sinn,",
    "for private hire, events or long-stay enquiries, our concierge replies within 24 hours.": "Für private Buchungen, Veranstaltungen oder Anfragen zu Langzeitaufenthalten antwortet unser Concierge innerhalb von 24 Stunden.",
    "from": "Von",
    "let us compose your stay together": "Lassen Sie uns Ihren Aufenthalt gemeinsam gestalten",
    "live the": "Erleben Sie das",
    "our concierge is available at every hour to orchestrate a stay that is entirely yours.": "Unser Concierge ist rund um die Uhr verfügbar, um einen Aufenthalt zu gestalten, der ganz Ihnen gehört.",
    "our concierge team is available at every hour to craft a stay that is entirely, irreducibly yours.": "Unser Concierge-Team ist rund um die Uhr da, um einen Aufenthalt zu gestalten, der ganz Ihnen gehört.",
    "purpose and legal basis": "Zweck und rechtliche Grundlage",
    "read the article →": "Den Artikel lesen →",
    "request sent": "Anfrage gesendet",
    "send my request": "Meine Anfrage senden",
    "thank you. our concierge will reply within 24 hours.": "Danke. Unser Concierge wird innerhalb von 24 Stunden antworten.",
    "the city of light": "der Stadt des Lichts",
    "the controller of personal data is": "Der Verantwortliche für personenbezogene Daten ist",
    "the information published on this site is provided for guidance only. the visuals and rates shown are not contractual and may change without notice.": "Die auf dieser Seite veröffentlichten Informationen dienen nur zur Orientierung. Die gezeigten Bilder und Preise sind nicht verbindlich und können ohne vorherige Ankündigung geändert werden.",
    "this site does not place advertising tracking cookies. only technical cookies strictly necessary for the operation of the site may be used.": "Diese Website platziert keine Werbe-Tracking-Cookies. Es dürfen nur technische Cookies verwendet werden, die für den Betrieb der Website unbedingt erforderlich sind.",
    "two michelin stars. chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "Zwei Michelin-Sterne. Köchin Margaux Vernet erfindet das französische Repertoire neu, mit Produkten von fünfzig Metern hinter der Küche. Das Degustationsmenü wechselt mit dem Mond.",
    "unfolds at your threshold.": "beginnt vor Ihrer Tür.",
    "vat not applicable, art. 293 b of the french tax code (cgi).": "USt nicht anwendbar, Art. 293 B des französischen Steuergesetzes (CGI).",
    "view all rooms & suites": "Alle Zimmer & Suiten Anzeigen",
    "virtual journey": "Virtuelle Reise",
    "your rights": "Ihre Rechte",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "the journal of the palace": "O Diário do Palácio",
    "our chronicles of the art of living, travel and gastronomy, written to the rhythm of the seasons.": "As nossas crónicas da arte de viver, das viagens e da gastronomia, escritas ao ritmo das estações.",
    "the french art of the table, a living heritage": "A arte da mesa à francesa, um património vivo",
    "from the fold of the cloth to the choice of crystal, the french table is a silent choreography. a look inside a craft the grand palais perpetuates every evening.": "Da dobra da toalha à escolha do cristal, a mesa francesa é uma coreografia silenciosa. Um olhar sobre um saber-fazer que o Grand Palais perpetua todas as noites.",
    "an escape to the loire valley": "Uma escapada ao Vale do Loire",
    "four exceptional categories, each a variation on the same art of welcoming. choose your refuge.": "Quatro categorias de exceção, cada uma uma variação da mesma arte de receber. Escolha o seu refúgio.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring and a private terrace overlooking the sculpted garden.": "Um refúgio de calma cuidada: linho cosido à mão, soalho de carvalho antigo e terraço privado sobre o jardim esculpido.",
    "soaring ceilings, a double marble bathroom and floor-to-ceiling windows that frame the park like a living painting.": "Pé-direito alto, casa de banho dupla em mármore e janelas que enquadram o parque como um quadro vivo.",
    "our most coveted address. a private dining room, a butler antechamber and a rooftop terrace over the skyline.": "A nossa morada mais procurada: sala de jantar privada, antecâmara de mordomo e terraço sobre os telhados.",
    "a palace of quiet distinction at the heart of": "Um palace de distinção discreta, no coração de",
    "spa, gastronomy, concierge: every service at the grand palais is designed so that everything feels simple and natural.": "Spa, gastronomia, concierge: cada serviço do Grand Palais é pensado para que tudo pareça simples e natural.",
    "seven treatment rooms, a roman hammam and a 25-metre heated pool. every ritual is bespoke, every moment restorative.": "Sete cabinas de tratamento, um hammam romano e uma piscina aquecida de 25 metros. Cada ritual é à medida, cada momento repara.",
    "chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "A chef Margaux Vernet reinventa o repertório francês com produtos cultivados a cinquenta metros dos fogões. O menu de degustação muda com a lua.",
    "rooms": "Quartos",
    "reserve": "Reservar",
    "palace — founded 1887": "Palace — desde 1887",
    "rooms & suites": "Quartos e suites",
    "hectares of gardens": "Hectares de jardins",
    "accommodations": "Alojamentos",
    "most requested": "A mais procurada",
    "courtyard garden": "Jardim interior",
    "prestige room": "Quarto Prestige",
    "/night": "/noite",
    "guest favourite": "A preferida dos hóspedes",
    "panoramic park": "Vista panorâmica sobre o parque",
    "deluxe suite": "Suite Deluxe",
    "city skyline": "Vista sobre os telhados",
    "grand suite": "Grande Suite",
    "two michelin stars": "Duas estrelas Michelin",
    "spa & thermal circuit": "Spa e circuito termal",
    "rare spirits & cellar": "Bebidas raras e adega",
    "gastronomy": "Gastronomia",
    "breakfast": "Pequeno-almoço",
    "guest voices": "Vozes dos hóspedes",
    "address": "Morada",
    "telephone": "Telefone",
    "available 24 hours": "Disponível 24 h",
    "eiffel tower": "Torre Eiffel",
    "cdg airport": "Aeroporto Roissy-CDG",
    "arrival": "Chegada",
    "departure": "Partida",
    "guests": "Hóspedes",
    "check availability": "Ver disponibilidade",
    "stay": "A estadia",
    "presidential suite": "Suite presidencial",
    "experiences": "Experiências",
    "private events": "Eventos privados",
    "information": "Informações",
    "where time is measured not in hours, but in moments that endure.": "Onde o tempo não se conta em horas, mas em momentos que ficam.",
    "a sanctuary of refined calm. hand-stitched linen, aged oak flooring, and a private terrace overlooking the sculpted inner garden.": "Um refúgio de calma cuidada: linho cosido à mão, soalho de carvalho antigo e terraço privado sobre o jardim interior.",
    "soaring ceilings, a double marble bathroom, and floor-to-ceiling windows that frame the park like a living painting.": "Pé-direito alto, casa de banho dupla em mármore e janelas do chão ao teto que enquadram o parque como um quadro vivo.",
    "our most coveted address. a private dining room, butler antechamber, and a rooftop terrace overlooking the golden skyline at dusk.": "O nosso endereço mais procurado: sala de jantar privada, antecâmara de mordomo e terraço sobre os telhados, diante do céu dourado do fim de tarde.",
    "view all rooms & suites": "Ver todos os quartos e suites",
    "chef margaux vernet elevates classical french gastronomy with ingredients sourced from our estate gardens and trusted regional producers.": "A chef reinterpreta a grande cozinha francesa com os produtos da horta da casa e de produtores da região.",
    "seven treatment rooms, a roman hammam, and a 25m heated pool. every ritual is bespoke, every moment restorative.": "Sete cabinas de tratamento, um hammam romano e uma piscina aquecida de 25 metros. Cada ritual é à medida; cada momento repara.",
    "an intimate bar presided over by our maître d'alcools. three thousand labels. one extraordinary conversation.": "Um bar íntimo dirigido pelo nosso mestre de licores. Três mil referências. Uma conversa de exceção.",
    "an experience that redefined our expectations of hospitality. every detail, every gesture — flawless.": "Uma experiência que redefiniu o que esperávamos da hotelaria. Cada detalhe, cada gesto — impecável.",
    "\"luxury is the ease of a t-shirt in a very expensive dress.\"": "«O luxo é a leveza de uma t-shirt num vestido caríssimo.»",
    "← all articles": "← Todos os artigos",
    "← all rooms": "← Todos os quartos",
    "at the heart of": "No coração de",
    "attended to": "Atendido",
    "data from the contact form is kept for the time necessary to process your request, then archived or deleted in accordance with applicable legal obligations.": "Os dados do formulário de contacto são mantidos pelo tempo necessário para processar o seu pedido, sendo depois arquivados ou eliminados de acordo com as obrigações legais aplicáveis.",
    "discover →": "Descubra →",
    "discover our suites": "Descobrir as nossas suítes",
    "eight hundred metres from the opéra. a fifteen-minute walk to the louvre.": "A oitocentos metros da Ópera. A quinze minutos a pé do Louvre.",
    "every sense,": "Cada sentido,",
    "for private hire, events or long-stay enquiries, our concierge replies within 24 hours.": "Para aluguer privado, eventos ou consultas de estadias prolongadas, o nosso concierge responde dentro de 24 horas.",
    "from": "De",
    "let us compose your stay together": "Vamos compor a sua estadia juntos",
    "live the": "Viva o",
    "our concierge is available at every hour to orchestrate a stay that is entirely yours.": "O nosso concierge está disponível a qualquer hora para orquestrar uma estadia que é inteiramente sua.",
    "our concierge team is available at every hour to craft a stay that is entirely, irreducibly yours.": "A nossa portaria está disponível a qualquer hora para compor uma estadia que seja só sua.",
    "purpose and legal basis": "Propósito e base legal",
    "read the article →": "Ler o artigo →",
    "request sent": "Pedido enviado",
    "send my request": "Enviar o meu pedido",
    "thank you. our concierge will reply within 24 hours.": "Obrigado. O nosso concierge responderá dentro de 24 horas.",
    "the city of light": "a Cidade Luz",
    "the controller of personal data is": "O responsável pelos dados pessoais é",
    "the information published on this site is provided for guidance only. the visuals and rates shown are not contractual and may change without notice.": "As informações publicadas neste site são fornecidas apenas para orientação. Os visuais e tarifas mostrados não são contratuais e podem mudar sem aviso prévio.",
    "this site does not place advertising tracking cookies. only technical cookies strictly necessary for the operation of the site may be used.": "Este site não coloca cookies de rastreamento publicitário. Apenas cookies técnicos estritamente necessários para o funcionamento do site podem ser utilizados.",
    "two michelin stars. chef margaux vernet reimagines the french canon with produce grown fifty metres from the kitchen. the tasting menu changes with the moon.": "Duas estrelas Michelin. A chef Margaux Vernet reinventa o repertório francês com produtos cultivados a cinquenta metros dos fogões. O menu de degustação muda com a lua.",
    "unfolds at your threshold.": "abre-se à sua porta.",
    "vat not applicable, art. 293 b of the french tax code (cgi).": "IVA não aplicável, art. 293 B do Código Geral Tributário (CGI).",
    "view all rooms & suites": "Ver Todas as Quartos & Suítes",
    "virtual journey": "Viagem Virtual",
    "your rights": "Seus direitos",
  },
};
