/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "all coffee rests 5–14 days after roasting before shipping — peak degassing for optimal extraction.": "Tout café repose de cinq à quatorze jours après torréfaction avant l'expédition — le temps du dégazage, pour une extraction juste.",
    "can i skip or pause my subscription?": "Puis-je sauter ou mettre en pause mon abonnement ?",
    "do you offer decaffeinated options?": "Proposez-vous des options décaféinées ?",
    "do you ship internationally?": "Expédiez-vous à l'international ?",
    "every bag includes qr-linked brew guides for that specific lot and roast level.": "Chaque sachet porte un code renvoyant aux méthodes d'extraction propres à ce lot et à ce degré de torréfaction.",
    "green coffee is cupped blind by our team. less than 8% of samples we receive make it to roasting.": "Le café vert est dégusté à l'aveugle par notre équipe. Moins de 8 % des échantillons reçus vont jusqu'à la torréfaction.",
    "how fresh is the coffee when it arrives?": "Quelle est la fraîcheur du café à son arrivée ?",
    "nitrogen-flushed valve bags preserve freshness. shipped within 48h of packing.": "Les sacs à valve sous azote préservent la fraîcheur. Expédié dans les 48h suivant l'emballage.",
    "small-batch roasting on our loring s35. every profile is developed over months and documented precisely.": "Torréfaction en petits lots sur notre Loring S35. Chaque profil se construit sur des mois et se consigne avec précision.",
    "the ethiopian yirgacheffe changed how i think about coffee. i've tried beans from every major subscription — origin roast is in another category.": "L'Ethiopian Yirgacheffe a changé ma façon de penser le café. J'ai essayé des grains de chaque abonnement majeur — Origin Roast est dans une autre catégorie.",
    "the monthly box is a coffee education. each arrival i learn something new — about the farm, the process, the roast. it's made me genuinely knowledgeable.": "La box mensuelle est une éducation au café. À chaque arrivée, j'apprends quelque chose de nouveau — sur la ferme, le processus, le torréfaction. Cela m'a rendu véritablement connaisseur.",
    "we ship to 22 countries across europe and north america. international orders include expedited shipping to ensure freshness. dhl tracked, typically 3–5 days.": "Nous expédions vers 22 pays en Europe et en Amérique du Nord. Les commandes internationales incluent une expédition accélérée pour garantir la fraîcheur. Suivi DHL, généralement 3 à 5 jours.",
    "we switched our cafe's house blend to origin roast six months ago. customer feedback on our espresso has improved measurably. the consistency is remarkable.": "Nous avons changé le mélange maison de notre café pour Origin Roast il y a six mois. Les retours des clients sur notre espresso se sont améliorés de manière significative. La constance est remarquable.",
    "we visit farms annually. every lot is traceable to the specific producer and harvest. no middlemen.": "Nous visitons les fermes chaque année. Chaque lot remonte à son producteur et à sa récolte. Aucun intermédiaire.",
    "what grind options are available?": "Quelles options de mouture sont disponibles ?",
    "what is your sourcing philosophy?": "Quelle est votre philosophie d'approvisionnement ?",
    "yes — skip up to 4 consecutive deliveries per year, or pause for up to 3 months. manage everything from your account dashboard or email us.": "Oui — sautez jusqu'à 4 livraisons consécutives par an, ou mettez en pause pendant jusqu'à 3 mois. Gérez tout depuis votre tableau de bord ou envoyez-nous un e-mail.",
    "yes. we carry a swiss water process decaf single origin, rotated seasonally. all subscription plans can include decaf as one of your selections.": "Oui. Nous proposons un décaféiné d'origine unique par Swiss Water Process, tourné saisonnièrement. Tous les plans d'abonnement peuvent inclure du décaféiné comme l'une de vos sélections.",
  },
  es: {
    "all coffee rests 5–14 days after roasting before shipping — peak degassing for optimal extraction.": "Todo el café reposa de cinco a catorce días tras el tueste antes del envío: el tiempo del desgasificado, para una extracción justa.",
    "can i skip or pause my subscription?": "¿Puedo saltar o pausar mi suscripción?",
    "do you offer decaffeinated options?": "¿Ofrecen opciones descafeinadas?",
    "do you ship internationally?": "¿Hacen envíos internacionales?",
    "every bag includes qr-linked brew guides for that specific lot and roast level.": "Cada bolsa lleva un código que remite a los métodos de extracción propios de ese lote y ese grado de tueste.",
    "green coffee is cupped blind by our team. less than 8% of samples we receive make it to roasting.": "El café verde lo cata a ciegas nuestro equipo. Menos del 8 % de las muestras recibidas llega al tueste.",
    "how fresh is the coffee when it arrives?": "¿Qué tan fresco está el café cuando llega?",
    "nitrogen-flushed valve bags preserve freshness. shipped within 48h of packing.": "Las bolsas de válvula envasadas al vacío preservan la frescura. Enviadas dentro de las 48 horas posteriores al empaquetado.",
    "small-batch roasting on our loring s35. every profile is developed over months and documented precisely.": "Tueste en pequeños lotes en nuestra Loring S35. Cada perfil se construye durante meses y se documenta con precisión.",
    "the ethiopian yirgacheffe changed how i think about coffee. i've tried beans from every major subscription — origin roast is in another category.": "El Yirgacheffe etíope cambió la forma en que pienso sobre el café. He probado granos de todas las suscripciones importantes — Origin Roast está en otra categoría.",
    "the monthly box is a coffee education. each arrival i learn something new — about the farm, the process, the roast. it's made me genuinely knowledgeable.": "La caja mensual es una educación sobre el café. Con cada llegada aprendo algo nuevo — sobre la granja, el proceso, el tueste. Me ha hecho realmente conocedor.",
    "we ship to 22 countries across europe and north america. international orders include expedited shipping to ensure freshness. dhl tracked, typically 3–5 days.": "Enviamos a 22 países en Europa y América del Norte. Los pedidos internacionales incluyen envío exprés para garantizar la frescura. Seguimiento de DHL, generalmente 3-5 días.",
    "we switched our cafe's house blend to origin roast six months ago. customer feedback on our espresso has improved measurably. the consistency is remarkable.": "Cambiamos la mezcla de la casa de nuestro café a Origin Roast hace seis meses. La retroalimentación de los clientes sobre nuestro espresso ha mejorado notablemente. La consistencia es notable.",
    "we visit farms annually. every lot is traceable to the specific producer and harvest. no middlemen.": "Visitamos las fincas cada año. Cada lote se remonta a su productor y a su cosecha. Sin intermediarios.",
    "what grind options are available?": "¿Qué opciones de molienda están disponibles?",
    "what is your sourcing philosophy?": "¿Cuál es su filosofía de abastecimiento?",
    "yes — skip up to 4 consecutive deliveries per year, or pause for up to 3 months. manage everything from your account dashboard or email us.": "Sí — salta hasta 4 entregas consecutivas al año, o pausa durante hasta 3 meses. Administra todo desde tu panel de cuenta o envíanos un correo electrónico.",
    "yes. we carry a swiss water process decaf single origin, rotated seasonally. all subscription plans can include decaf as one of your selections.": "Sí. Ofrecemos un descafeinado de origen único de Swiss Water Process, rotado estacionalmente. Todos los planes de suscripción pueden incluir descafeinado como una de tus selecciones.",
  },
  de: {
    "all coffee rests 5–14 days after roasting before shipping — peak degassing for optimal extraction.": "Jeder Kaffee ruht nach der Röstung fünf bis vierzehn Tage vor dem Versand — die Zeit des Entgasens, für eine saubere Extraktion.",
    "can i skip or pause my subscription?": "Kann ich mein Abonnement aussetzen oder pausieren?",
    "do you offer decaffeinated options?": "Bieten Sie entkoffeinierte Optionen an?",
    "do you ship internationally?": "Versenden Sie international?",
    "every bag includes qr-linked brew guides for that specific lot and roast level.": "Jede Tüte trägt einen Code zu den Zubereitungsanleitungen für genau diese Partie und Röstung.",
    "green coffee is cupped blind by our team. less than 8% of samples we receive make it to roasting.": "Der Rohkaffee wird von unserem Team blind verkostet. Weniger als 8 % der eingegangenen Muster gelangen zur Röstung.",
    "how fresh is the coffee when it arrives?": "Wie frisch ist der Kaffee, wenn er ankommt?",
    "nitrogen-flushed valve bags preserve freshness. shipped within 48h of packing.": "Die mit Stickstoff gefüllten Ventilsäcke bewahren die Frische. Innerhalb von 48 Stunden nach dem Verpacken versendet.",
    "small-batch roasting on our loring s35. every profile is developed over months and documented precisely.": "Röstung in kleinen Chargen auf unserer Loring S35. Jedes Profil entsteht über Monate und wird genau dokumentiert.",
    "the ethiopian yirgacheffe changed how i think about coffee. i've tried beans from every major subscription — origin roast is in another category.": "Der äthiopische Yirgacheffe hat meine Sicht auf Kaffee verändert. Ich habe Bohnen aus jedem großen Abonnement ausprobiert — Origin Roast ist eine andere Kategorie.",
    "the monthly box is a coffee education. each arrival i learn something new — about the farm, the process, the roast. it's made me genuinely knowledgeable.": "Die monatliche Box ist eine Kaffeeausbildung. Bei jeder Ankunft lerne ich etwas Neues — über die Farm, den Prozess, die Röstung. Es hat mich wirklich sachkundig gemacht.",
    "we ship to 22 countries across europe and north america. international orders include expedited shipping to ensure freshness. dhl tracked, typically 3–5 days.": "Wir versenden in 22 Länder in Europa und Nordamerika. Internationale Bestellungen beinhalten einen beschleunigten Versand, um die Frische zu gewährleisten. DHL-Tracking, typischerweise 3–5 Tage.",
    "we switched our cafe's house blend to origin roast six months ago. customer feedback on our espresso has improved measurably. the consistency is remarkable.": "Wir haben die Hausmischung unseres Cafés vor sechs Monaten auf Origin Roast umgestellt. Das Kundenfeedback zu unserem Espresso hat sich merklich verbessert. Die Konsistenz ist bemerkenswert.",
    "we visit farms annually. every lot is traceable to the specific producer and harvest. no middlemen.": "Wir besuchen die Farmen jedes Jahr. Jede Partie lässt sich auf Erzeuger und Ernte zurückführen. Keine Zwischenhändler.",
    "what grind options are available?": "Welche Mahlgradoptionen sind verfügbar?",
    "what is your sourcing philosophy?": "Was ist Ihre Beschaffungsphilosophie?",
    "yes — skip up to 4 consecutive deliveries per year, or pause for up to 3 months. manage everything from your account dashboard or email us.": "Ja — überspringen Sie bis zu 4 aufeinanderfolgende Lieferungen pro Jahr oder pausieren Sie bis zu 3 Monate. Verwalten Sie alles von Ihrem Kontodashboard oder senden Sie uns eine E-Mail.",
    "yes. we carry a swiss water process decaf single origin, rotated seasonally. all subscription plans can include decaf as one of your selections.": "Ja. Wir führen einen entkoffeinierten Single Origin nach dem Swiss Water Process, der saisonal gewechselt wird. Alle Abonnementpläne können entkoffeinierten Kaffee als eine Ihrer Auswahlmöglichkeiten enthalten.",
  },
  pt: {
    "all coffee rests 5–14 days after roasting before shipping — peak degassing for optimal extraction.": "Todo o café repousa de cinco a catorze dias após a torrefação antes do envio — o tempo da desgaseificação, para uma extração justa.",
    "can i skip or pause my subscription?": "Posso pular ou pausar a minha subscrição?",
    "do you offer decaffeinated options?": "Oferecem opções descafeinadas?",
    "do you ship internationally?": "Fazem envios internacionais?",
    "every bag includes qr-linked brew guides for that specific lot and roast level.": "Cada saco leva um código que remete para os métodos de extração próprios desse lote e desse grau de torra.",
    "green coffee is cupped blind by our team. less than 8% of samples we receive make it to roasting.": "O café verde é provado às cegas pela nossa equipa. Menos de 8 % das amostras recebidas chega à torrefação.",
    "how fresh is the coffee when it arrives?": "Quão fresco está o café quando chega?",
    "nitrogen-flushed valve bags preserve freshness. shipped within 48h of packing.": "Os sacos de válvula com gás nitrogênio preservam a frescura. Enviados dentro de 48h após a embalagem.",
    "small-batch roasting on our loring s35. every profile is developed over months and documented precisely.": "Torrefação em pequenos lotes na nossa Loring S35. Cada perfil constrói-se ao longo de meses e é documentado com rigor.",
    "the ethiopian yirgacheffe changed how i think about coffee. i've tried beans from every major subscription — origin roast is in another category.": "O Yirgacheffe etíope mudou a forma como penso sobre café. Já experimentei grãos de todas as principais subscrições — Origin Roast está em outra categoria.",
    "the monthly box is a coffee education. each arrival i learn something new — about the farm, the process, the roast. it's made me genuinely knowledgeable.": "A caixa mensal é uma educação sobre café. A cada chegada, aprendo algo novo — sobre a quinta, o processo, a torrefação. Isso me tornou genuinamente conhecedor.",
    "we ship to 22 countries across europe and north america. international orders include expedited shipping to ensure freshness. dhl tracked, typically 3–5 days.": "Enviamos para 22 países na Europa e na América do Norte. Os pedidos internacionais incluem envio expresso para garantir a frescura. Rastreio DHL, normalmente 3–5 dias.",
    "we switched our cafe's house blend to origin roast six months ago. customer feedback on our espresso has improved measurably. the consistency is remarkable.": "Mudámos a mistura da casa do nosso café para Origin Roast há seis meses. O feedback dos clientes sobre o nosso espresso melhorou significativamente. A consistência é notável.",
    "we visit farms annually. every lot is traceable to the specific producer and harvest. no middlemen.": "Visitamos as quintas todos os anos. Cada lote remonta ao seu produtor e à sua colheita. Sem intermediários.",
    "what grind options are available?": "Quais opções de moagem estão disponíveis?",
    "what is your sourcing philosophy?": "Qual é a sua filosofia de abastecimento?",
    "yes — skip up to 4 consecutive deliveries per year, or pause for up to 3 months. manage everything from your account dashboard or email us.": "Sim — pule até 4 entregas consecutivas por ano, ou pause por até 3 meses. Gerencie tudo a partir do seu painel de conta ou envie-nos um e-mail.",
    "yes. we carry a swiss water process decaf single origin, rotated seasonally. all subscription plans can include decaf as one of your selections.": "Sim. Temos um descafeinado de origem única pelo processo Swiss Water, rotacionado sazonalmente. Todos os planos de subscrição podem incluir descafeinado como uma das suas seleções.",
  },
};
