/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "· all rights reserved": "· Tous droits réservés",
    "best restaurants france": "Meilleurs Restaurants France",
    "born from a passion": "Né d'une passion",
    "can you accommodate dietary requirements?": "Pouvez-vous répondre aux exigences alimentaires ?",
    "choose your": "Choisissez votre",
    "complete the form below and we will confirm within 24 hours.": "Complétez le formulaire ci-dessous et nous confirmerons dans les 24 heures.",
    "creamy burrata, heirloom tomatoes from marmande, aged 12-year balsamic reduction, ligurian basil oil, fleur de sel": "Burrata crémeuse, tomates anciennes de Marmande, réduction de balsamique de 12 ans, huile de basilic ligurien, fleur de sel",
    "do you offer gift vouchers?": "Proposez-vous des bons cadeaux ?",
    "enquire about private dining": "Demander une privatisation",
    "full freedom to compose your evening from our seasonal menu.": "Liberté totale de composer votre soirée à partir de notre menu saisonnier.",
    "how far in advance should i book?": "Combien de temps à l'avance devrais-je réserver ?",
    "i travel to": "Je voyage à",
    "is a deposit required for reservations?": "Un acompte est-il requis pour les réservations ?",
    "is the wine list available to preview?": "La carte des vins est-elle disponible en aperçu ?",
    "is there a dress code?": "Y a-t-il un code vestimentaire ?",
    "journey": "Voyage",
    "make a reservation": "Réserver",
    "reserve your table": "Réserver votre table",
    "seven courses curated by chef beaumont around the season's finest ingredients.": "Sept plats élaborés par le Chef Beaumont autour des meilleurs ingrédients de la saison.",
    "story": "Histoire",
    "thank you.": "Merci.",
    "time": "Temps",
    "we recommend reserving at least three weeks in advance. for private events or large parties, our team is at your service.": "Nous conseillons de réserver au moins trois semaines à l'avance. Pour une privatisation ou un grand groupe, notre équipe est à votre disposition.",
    "what is the nearest parking?": "Quel est le parking le plus proche ?",
    "what our guests": "Ce que nos clients",
    "your message has been sent. we will get back to you shortly.": "Votre message a été envoyé. Nous vous répondrons sous peu.",
    "your reservation enquiry has been received. our team will contact you shortly to confirm.": "Votre demande de réservation a été reçue. Notre équipe vous contactera sous peu pour confirmer.",
    "your table": "Votre table",
  },
  es: {
    "· all rights reserved": "· Todos los derechos reservados",
    "best restaurants france": "Mejores Restaurantes Francia",
    "born from a passion": "Nacido de una pasión",
    "can you accommodate dietary requirements?": "¿Pueden acomodar requisitos dietéticos?",
    "choose your": "Elija su",
    "complete the form below and we will confirm within 24 hours.": "Complete el formulario a continuación y confirmaremos en 24 horas.",
    "creamy burrata, heirloom tomatoes from marmande, aged 12-year balsamic reduction, ligurian basil oil, fleur de sel": "Burrata cremosa, tomates heirloom de Marmande, reducción de balsámico de 12 años, aceite de albahaca ligur, fleur de sel",
    "do you offer gift vouchers?": "¿Ofrecen vales de regalo?",
    "enquire about private dining": "Consultar sobre privatización",
    "full freedom to compose your evening from our seasonal menu.": "Libertad total para componer su velada a partir de nuestro menú de temporada.",
    "how far in advance should i book?": "¿Con cuánta antelación debo reservar?",
    "i travel to": "Viajo a",
    "is a deposit required for reservations?": "¿Se requiere un depósito para las reservas?",
    "is the wine list available to preview?": "¿Está disponible la carta de vinos para previsualizar?",
    "is there a dress code?": "¿Hay un código de vestimenta?",
    "journey": "Viaje",
    "make a reservation": "Reservar",
    "reserve your table": "Reservar su mesa",
    "seven courses curated by chef beaumont around the season's finest ingredients.": "Siete platos seleccionados por el Chef Beaumont con los mejores ingredientes de la temporada.",
    "story": "Historia",
    "thank you.": "Gracias.",
    "time": "Tiempo",
    "we recommend reserving at least three weeks in advance. for private events or large parties, our team is at your service.": "Aconsejamos reservar con al menos tres semanas de antelación. Para privatizaciones o grupos grandes, nuestro equipo está a su disposición.",
    "what is the nearest parking?": "¿Cuál es el aparcamiento más cercano?",
    "what our guests": "Lo que nuestros clientes",
    "your message has been sent. we will get back to you shortly.": "Su mensaje ha sido enviado. Nos pondremos en contacto con usted en breve.",
    "your reservation enquiry has been received. our team will contact you shortly to confirm.": "Hemos recibido su consulta de reserva. Nuestro equipo se pondrá en contacto con usted en breve para confirmar.",
    "your table": "Su mesa",
  },
  de: {
    "· all rights reserved": "· Alle Rechte vorbehalten",
    "best restaurants france": "Beste Restaurants Frankreich",
    "born from a passion": "Aus einer Leidenschaft entstanden",
    "can you accommodate dietary requirements?": "Können Sie diätetische Anforderungen berücksichtigen?",
    "choose your": "Wählen Sie Ihr",
    "complete the form below and we will confirm within 24 hours.": "Füllen Sie das untenstehende Formular aus und wir bestätigen innerhalb von 24 Stunden.",
    "creamy burrata, heirloom tomatoes from marmande, aged 12-year balsamic reduction, ligurian basil oil, fleur de sel": "Cremige Burrata, Erbstücktomaten aus Marmande, 12 Jahre alte Balsamico-Reduktion, ligurisches Basilikumöl, Fleur de Sel",
    "do you offer gift vouchers?": "Bieten Sie Geschenkgutscheine an?",
    "enquire about private dining": "Private Veranstaltung anfragen",
    "full freedom to compose your evening from our seasonal menu.": "Vollständige Freiheit, Ihren Abend aus unserem saisonalen Menü zu gestalten.",
    "how far in advance should i book?": "Wie weit im Voraus sollte ich buchen?",
    "i travel to": "Ich reise nach",
    "is a deposit required for reservations?": "Ist eine Anzahlung für Reservierungen erforderlich?",
    "is the wine list available to preview?": "Ist die Weinkarte zur Vorschau verfügbar?",
    "is there a dress code?": "Gibt es einen Dresscode?",
    "journey": "Reise",
    "make a reservation": "Reservieren",
    "reserve your table": "Tisch reservieren",
    "seven courses curated by chef beaumont around the season's finest ingredients.": "Sieben Gänge, die von Chef Beaumont aus den besten Zutaten der Saison zusammengestellt wurden.",
    "story": "Geschichte",
    "thank you.": "Danke.",
    "time": "Zeit",
    "we recommend reserving at least three weeks in advance. for private events or large parties, our team is at your service.": "Wir empfehlen, mindestens drei Wochen im Voraus zu reservieren. Für private Veranstaltungen oder große Gruppen steht Ihnen unser Team zur Verfügung.",
    "what is the nearest parking?": "Was ist das nächstgelegene Parkhaus?",
    "what our guests": "Was unsere Gäste",
    "your message has been sent. we will get back to you shortly.": "Ihre Nachricht wurde gesendet. Wir werden uns in Kürze bei Ihnen melden.",
    "your reservation enquiry has been received. our team will contact you shortly to confirm.": "Ihre Reservierungsanfrage wurde erhalten. Unser Team wird Sie in Kürze kontaktieren, um zu bestätigen.",
    "your table": "Ihr Tisch",
  },
  pt: {
    "· all rights reserved": "· Todos os direitos reservados",
    "best restaurants france": "Melhores Restaurantes França",
    "born from a passion": "Nascido de uma paixão",
    "can you accommodate dietary requirements?": "Conseguem acomodar requisitos dietéticos?",
    "choose your": "Escolha o seu",
    "complete the form below and we will confirm within 24 hours.": "Preencha o formulário abaixo e confirmaremos dentro de 24 horas.",
    "creamy burrata, heirloom tomatoes from marmande, aged 12-year balsamic reduction, ligurian basil oil, fleur de sel": "Burrata cremosa, tomates heirloom de Marmande, redução de balsâmico de 12 anos, azeite de manjericão da Ligúria, fleur de sel",
    "do you offer gift vouchers?": "Oferecem vouchers de presente?",
    "enquire about private dining": "Pedir informações sobre privatização",
    "full freedom to compose your evening from our seasonal menu.": "Liberdade total para compor a sua noite a partir do nosso menu sazonal.",
    "how far in advance should i book?": "Com quanta antecedência devo reservar?",
    "i travel to": "Viajo para",
    "is a deposit required for reservations?": "É necessário um depósito para reservas?",
    "is the wine list available to preview?": "A lista de vinhos está disponível para pré-visualização?",
    "is there a dress code?": "Há um código de vestuário?",
    "journey": "Jornada",
    "make a reservation": "Reservar",
    "reserve your table": "Reservar a sua mesa",
    "seven courses curated by chef beaumont around the season's finest ingredients.": "Sete pratos elaborados pelo Chef Beaumont com os melhores ingredientes da estação.",
    "story": "História",
    "thank you.": "Obrigado.",
    "time": "Tempo",
    "we recommend reserving at least three weeks in advance. for private events or large parties, our team is at your service.": "Aconselhamos reservar com pelo menos três semanas de antecedência. Para privatizações ou grupos grandes, a nossa equipa está à sua disposição.",
    "what is the nearest parking?": "Qual é o estacionamento mais próximo?",
    "what our guests": "O que os nossos clientes",
    "your message has been sent. we will get back to you shortly.": "A sua mensagem foi enviada. Entraremos em contacto consigo em breve.",
    "your reservation enquiry has been received. our team will contact you shortly to confirm.": "A sua consulta de reserva foi recebida. A nossa equipa entrará em contacto consigo em breve para confirmar.",
    "your table": "A sua mesa",
  },
};
