/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    ", grasse, new york.": ", Grasse, New York.",
    "1-on-1 with master perfumer": "En tête-à-tête avec le maître parfumeur",
    "a singular fragrance crafted exclusively for you.": "Un parfum singulier, composé pour vous seul.",
    "a visceral descent into the midnight hour. dark, resinous, and unapologetic.": "Une descente viscérale dans l'heure de la nuit. Sombre, résineux et sans excuses.",
    "absolutely. we maintain direct relationships with our growers, paying premiums for sustainable farming and ethical harvesting practices.": "Absolument. Nous entretenons des relations directes avec nos producteurs, en payant des primes pour une agriculture durable et des pratiques de récolte éthiques.",
    "aged for three years in subterranean vaults.": "Vieilli pendant trois ans dans des voûtes souterraines.",
    "architectural scent structures crafted in grasse. where botanical rarity meets quantum precision.": "Structures olfactives architecturales conçues à Grasse. Là où la rareté botanique rencontre la précision quantique.",
    "are the ingredients ethically sourced?": "Les matières sont-elles sourcées de façon éthique ?",
    "between four and eleven revisions, typically over nine months. the formula moves by fractions of a percent. you are copied on every version.": "De quatre à onze retouches, sur neuf mois en général. La formule bouge par fractions de pour cent. Vous recevez chaque version.",
    "client": "Client",
    "commissions begin at €15,000, settled in three instalments across the work. should no direction satisfy you by the third trial, the engagement ends and the second instalment is not called.": "Les commandes débutent à 15 000 €, réglées en trois versements au fil du travail. Si aucune direction ne vous convient au troisième essai, l'engagement prend fin et le deuxième versement n'est pas appelé.",
    "do you offer refill services?": "Proposez-vous le réassort ?",
    "due to our 35% extrait de parfum concentration, you can expect a projection of 12-16 hours on skin, and up to 48 hours on textiles.": "En raison de notre concentration de 35 % d'Extrait de Parfum, vous pouvez vous attendre à une projection de 12 à 16 heures sur la peau et jusqu'à 48 heures sur les textiles.",
    "every full-size bottle comes with a complimentary 2ml sample. try the sample first. if it does not resonate, return the unopened full bottle for a full refund.": "Chaque flacon de taille normale est accompagné d'un échantillon de 2 ml gratuit. Essayez d'abord l'échantillon. S'il ne résonne pas, retournez le flacon plein non ouvert pour un remboursement complet.",
    "four hours in grasse, with no fragrance in the room. we talk about places, materials and memory — never about notes. most clients arrive expecting a questionnaire.": "Quatre heures à Grasse, sans un parfum dans la pièce. On parle de lieux, de matières et de mémoire — jamais de notes. La plupart des clients arrivent en s'attendant à un questionnaire.",
    "fractional distillation under vacuum ensures the delicate top notes are captured without thermal degradation.": "La distillation fractionnée sous vide garantit que les délicates notes de tête sont capturées sans dégradation thermique.",
    "hand-picked at dawn to preserve the volatile heart notes.": "Récolté à la main à l'aube pour préserver les notes de cœur volatiles.",
    "how long does the sillage last on the skin?": "Combien de temps le sillage tient-il sur la peau ?",
    "join the registry": "Rejoindre le registre",
    "limited editions, private commissions and bespoke inquiries begin here.": "Éditions limitées, commandes privées et demandes sur mesure commencent ici.",
    "liquid gold trapped in crystal. the blinding warmth of a mediterranean summer.": "De l'or liquide piégé dans du cristal. La chaleur éblouissante d'un été méditerranéen.",
    "order": "Commande",
    "our extracts rest in oak barrels for up to 18 months, allowing complex esters to form and sharp edges to smooth into velvet.": "Nos extraits reposent dans des fûts de chêne pendant jusqu'à 18 mois, permettant aux esters complexes de se former et aux bords tranchants de s'adoucir en velours.",
    "our master nose blends the rare absolutes with precision molecular captive molecules for unprecedented sillage.": "Notre maître parfumeur assemble les absolues rares et des molécules captives d'une grande précision, pour un sillage sans équivalent.",
    "six weeks later, three directions on blotters. you live with them for a month. nothing is decided in the atelier; it is decided on your skin, in your weather.": "Six semaines plus tard, trois directions sur mouillettes. Vous vivez un mois avec elles. Rien ne se décide à l'atelier : tout se décide sur votre peau, sous votre climat.",
    "store in a cool, dark environment. the custom vitrine box provided acts as a thermal and uv shield to prevent molecular degradation.": "Conservez dans un environnement frais et sombre. La boîte vitrine personnalisée fournie agit comme un bouclier thermique et UV pour prévenir la dégradation moléculaire.",
    "that exists once": "qui n'existe qu'une fois",
    "the essential introduction to the éclat universe.": "L'entrée en matière dans notre univers.",
    "the final formula is registered under your name and held for life. a refill can be produced at any point, at any volume, without repeating the work.": "La formule finale est déposée à votre nom et conservée à vie. Un réassort peut être produit à tout moment, dans n'importe quel volume, sans refaire le travail.",
    "the first three trials": "Les trois premiers essais",
    "the full manifestation of our olfactory art.": "L'expression entière de notre art olfactif.",
    "the interview": "L'entretien",
    "the longevity is simply supernatural. a single drop lasts well into the next sunrise.": "La longévité est tout simplement surnaturelle. Une seule goutte dure jusqu'au lever du soleil suivant.",
    "the noses": "Les nez",
    "the raw materials": "Les matières",
    "the vault": "Le coffre",
    "to wear nocturne is to wrap oneself in an invisible armor of pure, liquid luxury.": "Porter Nocturne, c'est s'envelopper dans une armure invisible de luxe pur et liquide.",
    "two commissions are accepted each year. the work takes between twelve and eighteen months, and we have declined more of them than we have taken.": "Deux commandes sont acceptées par an. Le travail demande douze à dix-huit mois, et nous en avons refusé plus que nous n'en avons pris.",
    "unveil your": "Révélez votre",
    "what is the return policy for a blind buy?": "Quelle est la politique de retour pour un achat à l'aveugle ?",
    "yes, our crystal flacons are designed for eternity. we offer a white-glove refill service at 40% of the original retail price.": "Oui, nos flacons en cristal sont conçus pour l'éternité. Nous proposons un service de recharge avec gants blancs à 40 % du prix de vente au détail d'origine.",
    "you're on the list": "Vous êtes sur la liste",
    "your cart is empty.": "Votre panier est vide.",
  },
  es: {
    ", grasse, new york.": ", Grasse, Nueva York.",
    "1-on-1 with master perfumer": "Cara a cara con el maestro perfumista",
    "a singular fragrance crafted exclusively for you.": "Un perfume singular, compuesto solo para usted.",
    "a visceral descent into the midnight hour. dark, resinous, and unapologetic.": "Una descenso visceral hacia la hora de la medianoche. Oscuro, resinoso y sin disculpas.",
    "absolutely. we maintain direct relationships with our growers, paying premiums for sustainable farming and ethical harvesting practices.": "Absolutamente. Mantenemos relaciones directas con nuestros cultivadores, pagando primas por la agricultura sostenible y prácticas de cosecha éticas.",
    "aged for three years in subterranean vaults.": "Envejecido durante tres años en bóvedas subterráneas.",
    "architectural scent structures crafted in grasse. where botanical rarity meets quantum precision.": "Estructuras de aroma arquitectónicas elaboradas en Grasse. Donde la rareza botánica se encuentra con la precisión cuántica.",
    "are the ingredients ethically sourced?": "¿Las materias tienen un origen ético?",
    "between four and eleven revisions, typically over nine months. the formula moves by fractions of a percent. you are copied on every version.": "De cuatro a once revisiones, normalmente a lo largo de nueve meses. La fórmula se mueve por fracciones de un uno por ciento. Recibe cada versión.",
    "client": "Cliente",
    "commissions begin at €15,000, settled in three instalments across the work. should no direction satisfy you by the third trial, the engagement ends and the second instalment is not called.": "Los encargos parten de 15 000 €, en tres pagos a lo largo del trabajo. Si ninguna dirección le convence en el tercer ensayo, el compromiso termina y no se reclama el segundo pago.",
    "do you offer refill services?": "¿Ofrecen recarga?",
    "due to our 35% extrait de parfum concentration, you can expect a projection of 12-16 hours on skin, and up to 48 hours on textiles.": "Debido a nuestra concentración del 35% de Extrait de Parfum, puede esperar una proyección de 12 a 16 horas en la piel y hasta 48 horas en los textiles.",
    "every full-size bottle comes with a complimentary 2ml sample. try the sample first. if it does not resonate, return the unopened full bottle for a full refund.": "Cada botella de tamaño completo viene con una muestra de 2 ml de cortesía. Prueba primero la muestra. Si no resuena, devuelve la botella llena sin abrir para un reembolso completo.",
    "four hours in grasse, with no fragrance in the room. we talk about places, materials and memory — never about notes. most clients arrive expecting a questionnaire.": "Cuatro horas en Grasse, sin un perfume en la sala. Hablamos de lugares, materias y memoria, nunca de notas. La mayoría de los clientes llega esperando un cuestionario.",
    "fractional distillation under vacuum ensures the delicate top notes are captured without thermal degradation.": "La destilación fraccionada al vacío asegura que las delicadas notas de salida se capturen sin degradación térmica.",
    "hand-picked at dawn to preserve the volatile heart notes.": "Cosechado a mano al amanecer para preservar las notas de corazón volátiles.",
    "how long does the sillage last on the skin?": "¿Cuánto dura la estela sobre la piel?",
    "join the registry": "Unirse al registro",
    "limited editions, private commissions and bespoke inquiries begin here.": "Ediciones limitadas, comisiones privadas y consultas personalizadas comienzan aquí.",
    "liquid gold trapped in crystal. the blinding warmth of a mediterranean summer.": "Oro líquido atrapado en cristal. El calor deslumbrante de un verano mediterráneo.",
    "order": "Orden",
    "our extracts rest in oak barrels for up to 18 months, allowing complex esters to form and sharp edges to smooth into velvet.": "Nuestros extractos reposan en barricas de roble durante hasta 18 meses, permitiendo que se formen ésteres complejos y que los bordes afilados se suavicen en terciopelo.",
    "our master nose blends the rare absolutes with precision molecular captive molecules for unprecedented sillage.": "Nuestro maestro perfumista combina absolutos raros con moléculas cautivas de gran precisión, para una estela sin igual.",
    "six weeks later, three directions on blotters. you live with them for a month. nothing is decided in the atelier; it is decided on your skin, in your weather.": "Seis semanas después, tres direcciones en tiras de papel. Convive un mes con ellas. Nada se decide en el taller: se decide sobre su piel, con su clima.",
    "store in a cool, dark environment. the custom vitrine box provided acts as a thermal and uv shield to prevent molecular degradation.": "Almacene en un entorno fresco y oscuro. La caja vitrina personalizada proporcionada actúa como un escudo térmico y UV para prevenir la degradación molecular.",
    "that exists once": "que existe una sola vez",
    "the essential introduction to the éclat universe.": "La introducción esencial a nuestro universo.",
    "the final formula is registered under your name and held for life. a refill can be produced at any point, at any volume, without repeating the work.": "La fórmula final se registra a su nombre y se conserva de por vida. Se puede producir una recarga en cualquier momento y volumen, sin repetir el trabajo.",
    "the first three trials": "Los tres primeros ensayos",
    "the full manifestation of our olfactory art.": "La expresión plena de nuestro arte olfativo.",
    "the interview": "La entrevista",
    "the longevity is simply supernatural. a single drop lasts well into the next sunrise.": "La longevidad es simplemente sobrenatural. Una sola gota dura hasta el siguiente amanecer.",
    "the noses": "Los narices",
    "the raw materials": "Las materias",
    "the vault": "La caja fuerte",
    "to wear nocturne is to wrap oneself in an invisible armor of pure, liquid luxury.": "Llevar Nocturne es envolverse en una armadura invisible de lujo puro y líquido.",
    "two commissions are accepted each year. the work takes between twelve and eighteen months, and we have declined more of them than we have taken.": "Se aceptan dos encargos al año. El trabajo lleva de doce a dieciocho meses, y hemos rechazado más de los que hemos aceptado.",
    "unveil your": "Revele su",
    "what is the return policy for a blind buy?": "¿Cuál es la política de devolución en una compra a ciegas?",
    "yes, our crystal flacons are designed for eternity. we offer a white-glove refill service at 40% of the original retail price.": "Sí, nuestros frascos de cristal están diseñados para la eternidad. Ofrecemos un servicio de recarga con guantes blancos al 40% del precio de venta original.",
    "you're on the list": "Estás en la lista",
    "your cart is empty.": "Tu carrito está vacío.",
  },
  de: {
    ", grasse, new york.": ", Grasse, New York.",
    "1-on-1 with master perfumer": "Vier Augen mit dem Meisterparfumeur",
    "a singular fragrance crafted exclusively for you.": "Ein einzigartiger Duft, allein für Sie komponiert.",
    "a visceral descent into the midnight hour. dark, resinous, and unapologetic.": "Ein viszeraler Abstieg in die Mitternachtsstunde. Dunkel, harzig und unversöhnlich.",
    "absolutely. we maintain direct relationships with our growers, paying premiums for sustainable farming and ethical harvesting practices.": "Absolut. Wir pflegen direkte Beziehungen zu unseren Erzeugern und zahlen Prämien für nachhaltige Landwirtschaft und ethische Erntepraktiken.",
    "aged for three years in subterranean vaults.": "Drei Jahre in unterirdischen Gewölben gereift.",
    "architectural scent structures crafted in grasse. where botanical rarity meets quantum precision.": "Architektonische Duftstrukturen, die in Grasse gefertigt werden. Wo botanische Raritäten auf quantenmäßige Präzision treffen.",
    "are the ingredients ethically sourced?": "Werden die Rohstoffe ethisch bezogen?",
    "between four and eleven revisions, typically over nine months. the formula moves by fractions of a percent. you are copied on every version.": "Vier bis elf Überarbeitungen, meist über neun Monate. Die Formel verschiebt sich um Bruchteile eines Prozents. Sie erhalten jede Fassung.",
    "client": "Kunde",
    "commissions begin at €15,000, settled in three instalments across the work. should no direction satisfy you by the third trial, the engagement ends and the second instalment is not called.": "Aufträge beginnen bei 15 000 €, zahlbar in drei Raten im Verlauf der Arbeit. Überzeugt Sie bis zum dritten Versuch keine Richtung, endet der Auftrag und die zweite Rate entfällt.",
    "do you offer refill services?": "Bieten Sie Nachfüllungen an?",
    "due to our 35% extrait de parfum concentration, you can expect a projection of 12-16 hours on skin, and up to 48 hours on textiles.": "Aufgrund unserer 35% Extrait de Parfum-Konzentration können Sie mit einer Projektion von 12-16 Stunden auf der Haut und bis zu 48 Stunden auf Textilien rechnen.",
    "every full-size bottle comes with a complimentary 2ml sample. try the sample first. if it does not resonate, return the unopened full bottle for a full refund.": "Jede Flasche in voller Größe kommt mit einer kostenlosen 2-ml-Probe. Probieren Sie zuerst die Probe. Wenn sie nicht anspricht, senden Sie die ungeöffnete volle Flasche für eine vollständige Rückerstattung zurück.",
    "four hours in grasse, with no fragrance in the room. we talk about places, materials and memory — never about notes. most clients arrive expecting a questionnaire.": "Vier Stunden in Grasse, ohne einen Duft im Raum. Wir sprechen über Orte, Materialien und Erinnerung — nie über Noten. Die meisten Kunden erwarten einen Fragebogen.",
    "fractional distillation under vacuum ensures the delicate top notes are captured without thermal degradation.": "Die fraktionierte Destillation unter Vakuum stellt sicher, dass die zarten Kopfnoten ohne thermische Degradation erfasst werden.",
    "hand-picked at dawn to preserve the volatile heart notes.": "Handverlesen bei Sonnenaufgang, um die flüchtigen Herznote zu bewahren.",
    "how long does the sillage last on the skin?": "Wie lange hält das Sillage auf der Haut?",
    "join the registry": "Dem Register beitreten",
    "limited editions, private commissions and bespoke inquiries begin here.": "Limitierte Auflagen, private Aufträge und maßgeschneiderte Anfragen beginnen hier.",
    "liquid gold trapped in crystal. the blinding warmth of a mediterranean summer.": "Flüssiges Gold, das in Kristall gefangen ist. Die blendende Wärme eines mediterranen Sommers.",
    "order": "Bestellung",
    "our extracts rest in oak barrels for up to 18 months, allowing complex esters to form and sharp edges to smooth into velvet.": "Unsere Extrakte ruhen bis zu 18 Monate in Eichenfässern, wodurch komplexe Ester entstehen und scharfe Kanten sich in Samt verwandeln.",
    "our master nose blends the rare absolutes with precision molecular captive molecules for unprecedented sillage.": "Unser Meisterparfumeur verbindet seltene Absolues mit hochpräzisen Captive-Molekülen zu einem Sillage ohnegleichen.",
    "six weeks later, three directions on blotters. you live with them for a month. nothing is decided in the atelier; it is decided on your skin, in your weather.": "Sechs Wochen später drei Richtungen auf Teststreifen. Sie leben einen Monat damit. Nichts wird im Atelier entschieden, sondern auf Ihrer Haut, in Ihrem Klima.",
    "store in a cool, dark environment. the custom vitrine box provided acts as a thermal and uv shield to prevent molecular degradation.": "Lagern Sie es in einer kühlen, dunklen Umgebung. Die bereitgestellte maßgeschneiderte Vitrinenbox fungiert als thermischer und UV-Schutz, um molekulare Degradation zu verhindern.",
    "that exists once": "das es nur einmal gibt",
    "the essential introduction to the éclat universe.": "Der Einstieg in unsere Welt.",
    "the final formula is registered under your name and held for life. a refill can be produced at any point, at any volume, without repeating the work.": "Die endgültige Formel wird auf Ihren Namen hinterlegt und lebenslang verwahrt. Eine Nachfüllung ist jederzeit und in jeder Menge möglich, ohne die Arbeit zu wiederholen.",
    "the first three trials": "Die ersten drei Versuche",
    "the full manifestation of our olfactory art.": "Der volle Ausdruck unserer Duftkunst.",
    "the interview": "Das Gespräch",
    "the longevity is simply supernatural. a single drop lasts well into the next sunrise.": "Die Langlebigkeit ist einfach übernatürlich. Ein einziger Tropfen hält bis zum nächsten Sonnenaufgang.",
    "the noses": "Die Nasen",
    "the raw materials": "Die Rohstoffe",
    "the vault": "Der Tresor",
    "to wear nocturne is to wrap oneself in an invisible armor of pure, liquid luxury.": "Nocturne zu tragen bedeutet, sich in eine unsichtbare Rüstung aus purem, flüssigem Luxus zu hüllen.",
    "two commissions are accepted each year. the work takes between twelve and eighteen months, and we have declined more of them than we have taken.": "Zwei Aufträge werden pro Jahr angenommen. Die Arbeit dauert zwölf bis achtzehn Monate, und wir haben mehr abgelehnt als angenommen.",
    "unveil your": "Enthüllen Sie Ihren",
    "what is the return policy for a blind buy?": "Wie ist die Rückgabe bei einem Blindkauf geregelt?",
    "yes, our crystal flacons are designed for eternity. we offer a white-glove refill service at 40% of the original retail price.": "Ja, unsere Kristallflakons sind für die Ewigkeit gemacht. Wir bieten einen Weißhandschuh-Nachfüllservice zu 40% des ursprünglichen Einzelhandelspreises an.",
    "you're on the list": "Sie stehen auf der Liste",
    "your cart is empty.": "Ihr Warenkorb ist leer.",
  },
  pt: {
    ", grasse, new york.": ", Grasse, Nova Iorque.",
    "1-on-1 with master perfumer": "A sós com o mestre perfumista",
    "a singular fragrance crafted exclusively for you.": "Um perfume singular, composto só para si.",
    "a visceral descent into the midnight hour. dark, resinous, and unapologetic.": "Uma descida visceral na hora da meia-noite. Escuro, resinoso e sem desculpas.",
    "absolutely. we maintain direct relationships with our growers, paying premiums for sustainable farming and ethical harvesting practices.": "Absolutamente. Mantemos relações diretas com os nossos agricultores, pagando prémios por práticas agrícolas sustentáveis e de colheita ética.",
    "aged for three years in subterranean vaults.": "Envelhecido durante três anos em vaults subterrâneas.",
    "architectural scent structures crafted in grasse. where botanical rarity meets quantum precision.": "Estruturas olfativas arquitetónicas criadas em Grasse. Onde a raridade botânica encontra a precisão quântica.",
    "are the ingredients ethically sourced?": "As matérias têm origem ética?",
    "between four and eleven revisions, typically over nine months. the formula moves by fractions of a percent. you are copied on every version.": "De quatro a onze revisões, normalmente ao longo de nove meses. A fórmula move-se por frações de um por cento. Recebe cada versão.",
    "client": "Cliente",
    "commissions begin at €15,000, settled in three instalments across the work. should no direction satisfy you by the third trial, the engagement ends and the second instalment is not called.": "As encomendas começam em 15 000 €, pagas em três prestações ao longo do trabalho. Se nenhuma direção o convencer ao terceiro ensaio, o compromisso termina e a segunda prestação não é cobrada.",
    "do you offer refill services?": "Oferecem recarga?",
    "due to our 35% extrait de parfum concentration, you can expect a projection of 12-16 hours on skin, and up to 48 hours on textiles.": "Devido à nossa concentração de 35% de Extrait de Parfum, pode esperar uma projeção de 12 a 16 horas na pele e até 48 horas em têxteis.",
    "every full-size bottle comes with a complimentary 2ml sample. try the sample first. if it does not resonate, return the unopened full bottle for a full refund.": "Cada frasco de tamanho normal vem com uma amostra de 2 ml gratuita. Experimente primeiro a amostra. Se não ressoar, devolva o frasco cheio não aberto para um reembolso total.",
    "four hours in grasse, with no fragrance in the room. we talk about places, materials and memory — never about notes. most clients arrive expecting a questionnaire.": "Quatro horas em Grasse, sem um perfume na sala. Falamos de lugares, matérias e memória — nunca de notas. A maioria dos clientes chega à espera de um questionário.",
    "fractional distillation under vacuum ensures the delicate top notes are captured without thermal degradation.": "A destilação fracionada a vácuo garante que as delicadas notas de topo sejam capturadas sem degradação térmica.",
    "hand-picked at dawn to preserve the volatile heart notes.": "Colhido à mão ao amanhecer para preservar as notas de coração voláteis.",
    "how long does the sillage last on the skin?": "Quanto tempo dura o rasto na pele?",
    "join the registry": "Juntar-se ao registo",
    "limited editions, private commissions and bespoke inquiries begin here.": "Edições limitadas, comissões privadas e consultas personalizadas começam aqui.",
    "liquid gold trapped in crystal. the blinding warmth of a mediterranean summer.": "Ouro líquido aprisionado em cristal. O calor ofuscante de um verão mediterrânico.",
    "order": "Pedido",
    "our extracts rest in oak barrels for up to 18 months, allowing complex esters to form and sharp edges to smooth into velvet.": "Os nossos extratos repousam em barricas de carvalho durante até 18 meses, permitindo que se formem ésteres complexos e que as bordas afiadas se suavizem em veludo.",
    "our master nose blends the rare absolutes with precision molecular captive molecules for unprecedented sillage.": "O nosso mestre perfumista combina absolutos raros com moléculas cativas de grande precisão, para um rasto sem igual.",
    "six weeks later, three directions on blotters. you live with them for a month. nothing is decided in the atelier; it is decided on your skin, in your weather.": "Seis semanas depois, três direções em tiras de papel. Convive um mês com elas. Nada se decide no atelier: decide-se na sua pele, com o seu clima.",
    "store in a cool, dark environment. the custom vitrine box provided acts as a thermal and uv shield to prevent molecular degradation.": "Armazene num ambiente fresco e escuro. A caixa vitrine personalizada fornecida atua como um escudo térmico e UV para prevenir a degradação molecular.",
    "that exists once": "que existe uma só vez",
    "the essential introduction to the éclat universe.": "A introdução essencial ao nosso universo.",
    "the final formula is registered under your name and held for life. a refill can be produced at any point, at any volume, without repeating the work.": "A fórmula final é registada em seu nome e conservada para toda a vida. Pode produzir-se uma recarga a qualquer momento e em qualquer volume, sem repetir o trabalho.",
    "the first three trials": "Os três primeiros ensaios",
    "the full manifestation of our olfactory art.": "A expressão plena da nossa arte olfativa.",
    "the interview": "A entrevista",
    "the longevity is simply supernatural. a single drop lasts well into the next sunrise.": "A longevidade é simplesmente sobrenatural. Uma única gota dura até o próximo nascer do sol.",
    "the noses": "Os narizes",
    "the raw materials": "As matérias",
    "the vault": "O cofre",
    "to wear nocturne is to wrap oneself in an invisible armor of pure, liquid luxury.": "Usar Nocturne é envolver-se em uma armadura invisível de puro luxo líquido.",
    "two commissions are accepted each year. the work takes between twelve and eighteen months, and we have declined more of them than we have taken.": "São aceites duas encomendas por ano. O trabalho leva doze a dezoito meses, e recusámos mais do que aceitámos.",
    "unveil your": "Revele o seu",
    "what is the return policy for a blind buy?": "Qual é a política de devolução numa compra às cegas?",
    "yes, our crystal flacons are designed for eternity. we offer a white-glove refill service at 40% of the original retail price.": "Sim, os nossos frascos de cristal são projetados para a eternidade. Oferecemos um serviço de recarga com luvas brancas a 40% do preço de venda original.",
    "you're on the list": "Você está na lista",
    "your cart is empty.": "O seu carrinho está vazio.",
  },
};
