/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "haven estates found our hampstead estate entirely off-market. their discretion and global network are simply unmatched.": "Ils ont trouvé notre propriété de Hampstead entièrement hors marché. Leur discrétion et leur réseau international n'ont pas d'équivalent.",
    "founded by former principals at sotheby's realty and christie's international,": "Fondée par d'anciens dirigeants de Sotheby's Realty et Christie's International,",
    "brings institutional expertise to private hands — with complete discretion.": "apporte une expertise institutionnelle à des mains privées — en toute discrétion.",
    "client voices": "Voix des clients",
    "curated trophy properties for discerning clients worldwide. off-market access. discretion guaranteed.": "Propriétés trophées sélectionnées pour des clients exigeants dans le monde entier. Accès hors marché. Discrétion garantie.",
    "discreet luxury real estate advisory for the world's most exceptional properties.": "Un conseil discret en immobilier de prestige, pour les biens les plus rares.",
    "end-to-end guidance from search to closing on residential and commercial assets.": "Accompagnement complet de la recherche à la conclusion sur des actifs résidentiels et commerciaux.",
    "exclusive pre-market listings and pocket deals from our global broker network.": "Des biens en avant-première et des affaires confidentielles, par notre réseau international de courtiers.",
    "find your": "Trouvez votre",
    "new listing": "Nouveau bien",
    "new york": "New York",
    "off-market": "Hors marché",
    "off-market access": "Accès hors marché",
    "our difference": "Ce qui nous distingue",
    "schedule private viewing": "Planifier une visite privée",
    "the belvedere penthouse": "Le penthouse Belvedere",
    "the haven": "Le Havre",
    "the team navigated our singapore acquisition with extraordinary professionalism. we closed in under three weeks.": "L'équipe a géré notre acquisition à Singapour avec un professionnalisme extraordinaire. Nous avons conclu en moins de trois semaines.",
    "three continents, one advisor. haven managed our entire portfolio consolidation seamlessly and discreetly.": "Trois continents, un conseiller. Haven a géré la consolidation de notre portefeuille de manière fluide et discrète.",
    "trusted by the": "La confiance des",
    "world's best.": "Meilleurs.",
    "world's best.": "Le meilleur du monde.",
  },
  es: {
    "haven estates found our hampstead estate entirely off-market. their discretion and global network are simply unmatched.": "Encontraron nuestra propiedad de Hampstead totalmente fuera de mercado. Su discreción y su red internacional no tienen igual.",
    "founded by former principals at sotheby's realty and christie's international,": "Fundada por antiguos directivos de Sotheby's Realty y Christie's International,",
    "brings institutional expertise to private hands — with complete discretion.": "aporta una experiencia institucional a manos privadas — con total discreción.",
    "client voices": "Voces de los clientes",
    "curated trophy properties for discerning clients worldwide. off-market access. discretion guaranteed.": "Propiedades trofeo seleccionadas para clientes exigentes en todo el mundo. Acceso fuera del mercado. Discreción garantizada.",
    "discreet luxury real estate advisory for the world's most exceptional properties.": "Asesoramiento discreto en inmobiliario de prestigio, para los bienes más excepcionales.",
    "end-to-end guidance from search to closing on residential and commercial assets.": "Orientación de principio a fin desde la búsqueda hasta el cierre de activos residenciales y comerciales.",
    "exclusive pre-market listings and pocket deals from our global broker network.": "Propiedades en primicia y operaciones confidenciales, a través de nuestra red internacional de agentes.",
    "find your": "Encuentre su",
    "new listing": "Nueva propiedad",
    "new york": "Nueva York",
    "off-market": "Fuera del mercado",
    "off-market access": "Acceso fuera del mercado",
    "our difference": "Lo que nos distingue",
    "schedule private viewing": "Programar visita privada",
    "the belvedere penthouse": "El ático Belvedere",
    "the haven": "El Refugio",
    "the team navigated our singapore acquisition with extraordinary professionalism. we closed in under three weeks.": "El equipo navegó nuestra adquisición en Singapur con una profesionalidad extraordinaria. Cerramos en menos de tres semanas.",
    "three continents, one advisor. haven managed our entire portfolio consolidation seamlessly and discreetly.": "Tres continentes, un asesor. Haven gestionó la consolidación de nuestra cartera de manera fluida y discreta.",
    "trusted by the": "La confianza de los",
    "world's best.": "Mejores.",
    "world's best.": "El mejor del mundo.",
  },
  de: {
    "haven estates found our hampstead estate entirely off-market. their discretion and global network are simply unmatched.": "Sie haben unser Anwesen in Hampstead vollständig off-market gefunden. Ihre Diskretion und ihr internationales Netz sind unerreicht.",
    "founded by former principals at sotheby's realty and christie's international,": "Gegründet von ehemaligen Führungskräften von Sotheby's Realty und Christie's International,",
    "brings institutional expertise to private hands — with complete discretion.": "bringt institutionelle Expertise in private Hände — mit vollständiger Diskretion.",
    "client voices": "Kundenstimmen",
    "curated trophy properties for discerning clients worldwide. off-market access. discretion guaranteed.": "Kuratierte Trophäenimmobilien für anspruchsvolle Kunden weltweit. Zugang zu Off-Market-Angeboten. Diskretion garantiert.",
    "discreet luxury real estate advisory for the world's most exceptional properties.": "Diskrete Beratung für Luxusimmobilien, für die außergewöhnlichsten Objekte.",
    "end-to-end guidance from search to closing on residential and commercial assets.": "Umfassende Beratung von der Suche bis zum Abschluss bei Wohn- und Gewerbeimmobilien.",
    "exclusive pre-market listings and pocket deals from our global broker network.": "Objekte vor Markteintritt und vertrauliche Geschäfte über unser internationales Maklernetz.",
    "find your": "Finden Sie Ihr",
    "new listing": "Neues Objekt",
    "new york": "New York",
    "off-market": "Außerhalb des Marktes",
    "off-market access": "Zugang zu Off-Market-Angeboten",
    "our difference": "Was uns unterscheidet",
    "schedule private viewing": "Private Besichtigung vereinbaren",
    "the belvedere penthouse": "Die Belvedere-Penthouse",
    "the haven": "Der Hafen",
    "the team navigated our singapore acquisition with extraordinary professionalism. we closed in under three weeks.": "Das Team hat unsere Akquisition in Singapur mit außergewöhnlicher Professionalität geleitet. Wir haben in weniger als drei Wochen abgeschlossen.",
    "three continents, one advisor. haven managed our entire portfolio consolidation seamlessly and discreetly.": "Drei Kontinente, ein Berater. Haven hat unsere gesamte Portfolio-Konsolidierung nahtlos und diskret verwaltet.",
    "trusted by the": "Das Vertrauen der",
    "world's best.": "Besten.",
    "world's best.": "Die Besten der Welt.",
  },
  pt: {
    "haven estates found our hampstead estate entirely off-market. their discretion and global network are simply unmatched.": "Encontraram a nossa propriedade em Hampstead totalmente fora de mercado. A discrição e a rede internacional não têm igual.",
    "founded by former principals at sotheby's realty and christie's international,": "Fundada por antigos dirigentes da Sotheby's Realty e da Christie's International,",
    "brings institutional expertise to private hands — with complete discretion.": "traz uma experiência institucional a mãos privadas — com total discrição.",
    "client voices": "Vozes dos clientes",
    "curated trophy properties for discerning clients worldwide. off-market access. discretion guaranteed.": "Propriedades troféu selecionadas para clientes exigentes em todo o mundo. Acesso fora do mercado. Discrição garantida.",
    "discreet luxury real estate advisory for the world's most exceptional properties.": "Aconselhamento discreto em imobiliário de prestígio, para os bens mais excecionais.",
    "end-to-end guidance from search to closing on residential and commercial assets.": "Orientação de ponta a ponta desde a pesquisa até o fechamento de ativos residenciais e comerciais.",
    "exclusive pre-market listings and pocket deals from our global broker network.": "Imóveis em primeira mão e negócios confidenciais, através da nossa rede internacional de corretores.",
    "find your": "Encontre o seu",
    "new listing": "Novo imóvel",
    "new york": "Nova Iorque",
    "off-market": "Fora do mercado",
    "off-market access": "Acesso fora do mercado",
    "our difference": "O que nos distingue",
    "schedule private viewing": "Agendar visita privada",
    "the belvedere penthouse": "O penthouse Belvedere",
    "the haven": "O Refúgio",
    "the team navigated our singapore acquisition with extraordinary professionalism. we closed in under three weeks.": "A equipe navegou a nossa aquisição em Singapura com uma profissionalismo extraordinário. Fechámos em menos de três semanas.",
    "three continents, one advisor. haven managed our entire portfolio consolidation seamlessly and discreetly.": "Três continentes, um consultor. A Haven geriu a consolidação do nosso portfólio de forma fluida e discreta.",
    "trusted by the": "A confiança dos",
    "world's best.": "Melhores.",
    "world's best.": "O melhor do mundo.",
  },
};
