/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Un document sur ma façon de travailler — les outils, la philosophie, l'installation. Parce que l'environnement façonne le résultat.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Une astuce brillante que trois ingénieurs ne sauront plus lire au trimestre suivant est un passif, pas un actif. J'optimise pour le prochain ingénieur sur le code.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "L'intuition sur la performance se trompe presque toujours. Profileurs, traces distribuées et télémétrie de production doivent guider les décisions d'optimisation.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Une PR de 50 lignes livrée aujourd'hui vaut mieux qu'une PR de 500 lignes qui traîne deux semaines en relecture. Je garde des diffs lisibles et des contrôles automatisés pour que ça avance.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit est volontairement petit. Quatre projets par trimestre — jamais plus. Chaque client a tous les seniors autour de la table. C'est le modèle.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Stratège de marque, venue de la sémiotique et de l'économie comportementale. Passée par Wolff Olins à Londres. Convaincue que toute grande identité part d'un point de vue tranché.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obsédée de typographie, esprit systémique, ancienne de Pentagram. Sana transforme la clarté stratégique en précision visuelle — rien d'arbitraire, tout se déploie.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Fait passer la marque du statique au vivant — identité en mouvement, web interactif, points de contact numériques. A travaillé avec Nike Digital et Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Des composants 3D haute performance conçus pour le web moderne. Nous marions le geste créatif à une optimisation rigoureuse au niveau du GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Un rendu 3D temps réel haute fidélité, directement dans le navigateur : maillages légers, textures PBR optimisées, éclairage physiquement exact.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Des campagnes de réalité augmentée sans application : d'un simple lien, le client pose le produit chez lui, avec un réalisme photographique.",
    "camera filters and custom overlays": "Filtres caméra et surimpressions sur mesure",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism se branche nativement à votre entrepôt de données, votre CRM, votre prestataire de paiement et vos canaux publicitaires. Aucune intégration sur mesure requise.",
    "sync raw events natively from databases and query engines.": "Synchronisez les événements bruts depuis vos bases et moteurs de requête.",
    "align transaction records with user behavior metrics.": "Rapprochez les transactions des mesures de comportement.",
    "enrich user profiles and trigger messaging based on user actions.": "Enrichissez les profils et déclenchez des messages selon les actions.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Une conception de bout en bout, de l'esquisse au coulage du béton. L'honnêteté structurelle est notre directive première, sans compromis visuel.",
    "scope of work:": "Périmètre :",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Des stratégies d'aménagement à grande échelle pour institutions publiques et campus. Nos plans directeurs ancrent les ensembles bâtis dans une densité logique.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Nous laissons l'acier, le béton et les gaines apparents : les systèmes intérieurs font partie de l'esthétique au lieu d'être cachés derrière des finitions.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sept jours dans un désert ancien. Pratique somatique à l'aube, marches silencieuses à midi, cérémonies du feu le soir. Sans agenda. Sans performance.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Des retraites immersives dans les paysages les plus transformateurs du monde. Neuf participants au plus. Le calme comme pratique.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Je passe des semaines sur chaque lieu avant de faire une image. Les montagnes se moquent de mon calendrier. La brume vient quand elle veut. Cette patience est toute la méthode.",
    "each print is made in partnership with atelier gaspard in": "Chaque tirage est réalisé avec l'Atelier Gaspard à",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Pour les licences éditoriales, les usages commerciaux ou les commandes privées, écrivez-moi directement. Pour les tirages, passez par la boutique.",
    "bring the wild": "Ramenez le sauvage",
    "that's the point.": "C'est justement le but.",
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Éditeur de code collaboratif en temps réel. WebSockets, Monaco Editor, CRDT Y.js.",
    "quick setup instructions": "Mise en route rapide",
    "launch shell simulator": "Lancer le simulateur de terminal",
    "languages": "Langages",
    "staff engineer": "Ingénieur principal",
    "senior frontend": "Développeur front-end senior",
    "founding engineer": "Premier ingénieur",
    "since 2014": "depuis 2014",
    "github stars": "étoiles GitHub",
    "across 6 repos": "sur six dépôts",
    "uptime sla": "disponibilité garantie",
    "last 24 months": "sur les 24 derniers mois",
    "latency cut": "de latence en moins",
    "p99.9 at stripe": "p99,9 chez Stripe",
    "faang companies": "entreprises de la tech mondiale",
    "payload reduction": "de charge utile en moins",
    "crdt compaction pipeline": "chaîne de compaction CRDT",
    "€1 200 / day": "1 200 € / jour",
    "€8 000 flat": "8 000 € au forfait",
    "€800 / day": "800 € / jour",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Je m'intègre comme ingénieur principal dans vos équipes produit : infrastructure critique, rédaction des RFC, déblocage des points durs au niveau système. J'ai mené des équipes chez Stripe et Vercel sur des sujets où l'échec se chiffre en dizaines de millions.",
    "performance audits": "Audits de performance",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Deux semaines resserrées : profilage, traçage distribué, identification des goulots et feuille de route de correction hiérarchisée. Livrables : un rapport écrit et des correctifs qui fonctionnent. Les clients précédents ont vu leur p99 baisser de 30 à 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Gouvernance du projet, accueil des contributeurs, audit des licences, séquencement de la feuille de route. J'aide les entreprises portées par l'ingénierie à tirer une valeur durable du logiciel libre sans épuiser leurs mainteneurs.",
    "technical due diligence": "Audit technique d'acquisition",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Examen approfondi avant rachat ou investissement : qualité du code, posture de sécurité, plafond de montée en charge, dépendance aux personnes clés, passifs cachés. Rapport écrit en cinq jours ouvrés, présentable en conseil d'administration.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Passation propre : décisions d'architecture documentées, procédures d'exploitation, et deux semaines de questions-réponses après la mission. Aucun code orphelin.",
    "recent builds": "Réalisations récentes",
    "full project catalogue": "Tout le catalogue de projets",
    "project impact summary": "Synthèse de l'impact des projets",
    "principal engineer, datadog": "Ingénieur principal, Datadog",
    "engineering lead, pennylane": "Responsable ingénierie, Pennylane",
    "vp engineering, alan": "Directeur de l'ingénierie, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Brief asynchrone de 30 minutes via Loom ou document écrit. J'ai lu votre stack technologique, compris l'espace de contraintes et signalé tout ce qui change la portée.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponible pour des missions d'ingénierie senior, du conseil technique et du logiciel libre. Basé à",
    "browse the work": "Parcourir les réalisations",
    "built the real-time sync engine from scratch (yjs + crdts).": "Moteur de synchronisation en temps réel écrit de zéro (Yjs et CRDT).",
    "cargo build — execution": "cargo build — Exécution",
    "core contributor to next.js app router and turbopack.": "Contributeur principal à Next.js App Router et Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Détaillé, précis, communique des compromis au lieu d'opinions. Il a livré un RFC d'architecture de 25 pages sur notre couche de données que nous avons expédié presque mot pour mot. Rare.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de traçage distribué qui reconstruit des graphes d'appels à partir de spans OTLP bruts à travers plusieurs services.",
    "engagement process": "Processus d'engagement",
    "featured open source": "Logiciel libre mis en avant",
    "find the milliseconds your users feel": "Trouver les millisecondes que vos utilisateurs ressentent",
    "hire me": "engagez-moi",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Son audit de performance a trouvé trois modèles de requêtes systémiques que nous avions manqués pendant deux ans. La correction a été déployée en un sprint. Vaut dix fois le tarif.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Je prends 1 à 2 engagements ciblés par trimestre. Si votre calendrier le permet, voyons si nous sommes compatibles.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Je travaille en courts cycles avec des résultats visibles. Chaque semaine se termine par une présentation Loom de ce qui a été expédié, de ce qui ne l'a pas été et pourquoi.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Couche de cache de construction incrémentale pour les espaces de travail Cargo. Réduit les temps CI de 40 à 70 % grâce à des artefacts adressés par contenu.",
    "know what you're acquiring": "Savoir ce que vous rachetez",
    "led infrastructure reliability for payment processing at scale.": "A dirigé la fiabilité de l'infrastructure pour le traitement des paiements à grande échelle.",
    "let's build something great.": "Bâtissons quelque chose de bien.",
    "open source advisory": "Conseil en logiciel libre",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Conseil en open source d'une personne qui a réellement expédié et maintenu de grands projets OSS. Pas seulement de la théorie. Je travaillerais à nouveau avec lui immédiatement.",
    "previous employers and clients": "anciens employeurs et clients",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël a réécrit notre service de rapprochement des transactions en quatre semaines. Le P99 est passé de 900 ms à 120 ms. Le code qu'il a laissé est le plus propre que nous ayons — et ce n'est pas peu dire.",
    "ready to ship something great?": "Prêt à expédier quelque chose de génial ?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Document partagé avec des objectifs, des critères de succès et une cadence hebdomadaire. Pas de pivots surprises. Si le problème change en cours d'engagement, nous redéfinissons la portée par écrit.",
    "sustainable oss strategy for your company": "Une stratégie de logiciel libre tenable pour votre entreprise",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Cadre de test API basé sur le terminal avec des différences de snapshot et une intégration CI/CD.",
    "the setup": "la configuration",
    "view full architecture impact": "Voir l'impact architectural complet",
    "view source": "Voir la source",
    "view work()": "voirRéalisations()",
    "what engineers say": "Ce qu'en disent les ingénieurs",
    "what i do": "ce que je fais",
    "work environment": "Environnement de travail",
  },
  es: {
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Un documento sobre mi forma de trabajar: las herramientas, la filosofía, la instalación. Porque el entorno moldea el resultado.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Un truco brillante que tres ingenieros no sabrán leer el próximo trimestre es un pasivo, no un activo. Optimizo para el siguiente ingeniero en el código.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "La intuición sobre el rendimiento casi siempre se equivoca. Perfiles, trazas distribuidas y telemetría de producción deben guiar las decisiones de optimización.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Una PR de 50 líneas entregada hoy vale más que una de 500 que pasa dos semanas en revisión. Mantengo diffs legibles y controles automatizados para que todo avance.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit es deliberadamente pequeño. Cuatro proyectos por trimestre, nunca más. Cada cliente tiene a todos los seniors en la sala. Ese es el modelo.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Estratega de marca, con formación en semiótica y economía conductual. Antes en Wolff Olins Londres. Convencida de que toda gran identidad parte de un punto de vista afilado.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obsesa de la tipografía, mente sistémica, ex-Pentagram. Sana convierte la claridad estratégica en precisión visual: nada es arbitrario, todo escala.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Lleva la marca de lo estático a lo vivo: identidad en movimiento, web interactiva, puntos de contacto digitales. Trabajó con Nike Digital y Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Componentes 3D de alto rendimiento para la web moderna. Unimos el gesto creativo a una optimización rigurosa a nivel de GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Renderizado 3D en tiempo real de alta fidelidad, directamente en el navegador: mallas ligeras, texturas PBR optimizadas, iluminación físicamente exacta.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Campañas de realidad aumentada sin aplicación: con un simple enlace, el cliente coloca el producto en su espacio con realismo fotográfico.",
    "camera filters and custom overlays": "Filtros de cámara y superposiciones a medida",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism se conecta de forma nativa a su almacén de datos, su CRM, su procesador de pagos y sus canales publicitarios. Sin integraciones a medida.",
    "sync raw events natively from databases and query engines.": "Sincronice eventos en bruto desde sus bases y motores de consulta.",
    "align transaction records with user behavior metrics.": "Alinee las transacciones con las métricas de comportamiento.",
    "enrich user profiles and trigger messaging based on user actions.": "Enriquezca los perfiles y active mensajes según las acciones.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Diseño de principio a fin, del boceto al vertido del hormigón. La honestidad estructural es nuestra directiva primera, sin compromiso visual.",
    "scope of work:": "Alcance:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Estrategias de ordenación a gran escala para instituciones públicas y campus. Nuestros planes maestros anclan los conjuntos con una densidad lógica.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Dejamos el acero, el hormigón y los conductos a la vista: los sistemas interiores forman parte de la estética en lugar de esconderse tras acabados.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Siete días en un desierto antiguo. Práctica somática al alba, caminatas silenciosas al mediodía, ceremonias de fuego al anochecer. Sin agenda. Sin rendimiento.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Retiros inmersivos en los paisajes más transformadores del mundo. Nueve participantes como máximo. La calma como práctica.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Paso semanas en cada lugar antes de hacer una imagen. A las montañas no les importa mi calendario. La niebla llega cuando quiere. Esa paciencia es todo el método.",
    "each print is made in partnership with atelier gaspard in": "Cada copia se realiza con el Atelier Gaspard en",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Para licencias editoriales, usos comerciales o encargos privados, escríbame directamente. Para las copias, pase por la tienda.",
    "bring the wild": "Traiga lo salvaje",
    "that's the point.": "Ese es justamente el punto.",
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Editor de código colaborativo en tiempo real. WebSockets, Monaco Editor, CRDT Y.js.",
    "quick setup instructions": "Puesta en marcha rápida",
    "launch shell simulator": "Lanzar el simulador de terminal",
    "languages": "Lenguajes",
    "staff engineer": "Ingeniero principal",
    "senior frontend": "Desarrollador front-end sénior",
    "founding engineer": "Primer ingeniero",
    "since 2014": "desde 2014",
    "github stars": "estrellas GitHub",
    "across 6 repos": "en seis repositorios",
    "uptime sla": "disponibilidad garantizada",
    "last 24 months": "en los últimos 24 meses",
    "latency cut": "menos de latencia",
    "p99.9 at stripe": "p99,9 en Stripe",
    "faang companies": "empresas de la gran tecnología",
    "payload reduction": "menos carga útil",
    "crdt compaction pipeline": "cadena de compactación CRDT",
    "€1 200 / day": "1 200 € / día",
    "€8 000 flat": "8 000 € a tanto alzado",
    "€800 / day": "800 € / día",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Me integro como ingeniero principal en sus equipos de producto: infraestructura crítica, redacción de RFC, desbloqueo de puntos duros a nivel de sistema. He dirigido equipos en Stripe y Vercel en problemas donde el fallo se mide en decenas de millones.",
    "performance audits": "Auditorías de rendimiento",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Dos semanas concentradas: perfilado, trazado distribuido, identificación de cuellos de botella y hoja de ruta de corrección priorizada. Entregables: un informe escrito y parches que funcionan. Clientes anteriores vieron bajar su p99 entre un 30 y un 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Gobernanza del proyecto, acogida de contribuidores, auditoría de licencias, secuenciación de la hoja de ruta. Ayudo a empresas dirigidas por la ingeniería a extraer valor duradero del software libre sin quemar a sus mantenedores.",
    "technical due diligence": "Diligencia técnica",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Examen a fondo antes de una compra o inversión: calidad del código, postura de seguridad, techo de escalabilidad, dependencia de personas clave, pasivos ocultos. Informe escrito en cinco días hábiles, presentable ante el consejo.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Traspaso limpio: decisiones de arquitectura documentadas, procedimientos de operación y dos semanas de preguntas tras la misión. Ningún código huérfano.",
    "recent builds": "Trabajos recientes",
    "full project catalogue": "Todo el catálogo de proyectos",
    "project impact summary": "Resumen del impacto de los proyectos",
    "principal engineer, datadog": "Ingeniero principal, Datadog",
    "engineering lead, pennylane": "Responsable de ingeniería, Pennylane",
    "vp engineering, alan": "Director de ingeniería, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Resumen asíncrono de 30 minutos a través de Loom o documento escrito. Leí su stack tecnológico, entendí el espacio de restricciones y señalé cualquier cosa que cambie el alcance.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponible para misiones de ingeniería sénior, consultoría técnica y código abierto. Con base en",
    "browse the work": "Ver los trabajos",
    "built the real-time sync engine from scratch (yjs + crdts).": "Motor de sincronización en tiempo real escrito desde cero (Yjs y CRDT).",
    "cargo build — execution": "cargo build — Ejecución",
    "core contributor to next.js app router and turbopack.": "Contribuyente principal a Next.js App Router y Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detallado, preciso, comunica compensaciones en lugar de opiniones. Entregó un RFC de arquitectura de 25 páginas sobre nuestra capa de datos que enviamos casi palabra por palabra. Raro.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de trazado distribuido que reconstruye gráficos de llamadas a partir de spans OTLP en bruto a través de múltiples servicios.",
    "engagement process": "Proceso de compromiso",
    "featured open source": "Código abierto destacado",
    "find the milliseconds your users feel": "Encontrar los milisegundos que sus usuarios notan",
    "hire me": "contrátame",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Su auditoría de rendimiento encontró tres patrones de consulta sistémicos que habíamos pasado por alto durante dos años. La solución se implementó en un sprint. Vale diez veces la tarifa.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Acepto 1 a 2 compromisos enfocados por trimestre. Si tu cronograma encaja, averigüemos si somos compatibles.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Trabajo en ciclos cortos con resultados visibles. Cada semana termina con un recorrido de Loom sobre lo que se envió, lo que no se envió y por qué.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Capa de caché de construcción incremental para espacios de trabajo Cargo. Reduce los tiempos de CI en un 40-70% a través de artefactos dirigidos por contenido.",
    "know what you're acquiring": "Saber lo que está adquiriendo",
    "led infrastructure reliability for payment processing at scale.": "Lideró la fiabilidad de la infraestructura para el procesamiento de pagos a gran escala.",
    "let's build something great.": "Construyamos algo bueno.",
    "open source advisory": "Asesoramiento en código abierto",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Asesoría de código abierto de alguien que realmente ha enviado y mantenido grandes proyectos de OSS. No solo teoría. Trabajaría con él de nuevo de inmediato.",
    "previous employers and clients": "empleadores y clientes anteriores",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël reescribió nuestro servicio de conciliación de transacciones en cuatro semanas. El P99 pasó de 900 ms a 120 ms. El código que dejó es el más limpio que tenemos, y no es poco decir.",
    "ready to ship something great?": "¿Listo para enviar algo grandioso?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Documento compartido con objetivos, criterios de éxito y cadencia semanal. Sin pivotes sorpresa. Si el problema cambia a mitad del compromiso, redefinimos el alcance por escrito.",
    "sustainable oss strategy for your company": "Una estrategia de código abierto sostenible para su empresa",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Marco de pruebas de API basado en terminal con diferencias de instantáneas e integración CI/CD.",
    "the setup": "la configuración",
    "view full architecture impact": "Ver el impacto arquitectónico completo",
    "view source": "Ver fuente",
    "view work()": "verTrabajos()",
    "what engineers say": "Lo que dicen los ingenieros",
    "what i do": "lo que hago",
    "work environment": "Entorno de trabajo",
  },
  de: {
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Ein Dokument über meine Arbeitsweise — Werkzeuge, Philosophie, Arbeitsplatz. Denn die Umgebung prägt das Ergebnis.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Ein brillanter Trick, den drei Ingenieure im nächsten Quartal nicht mehr lesen können, ist eine Last, kein Gewinn. Ich optimiere für den nächsten Menschen im Code.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "Intuition über Performance liegt meist daneben. Profiler, verteilte Traces und echte Produktionstelemetrie sollten Optimierungsentscheidungen leiten.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Ein 50-Zeilen-PR, der heute live geht, schlägt einen 500-Zeilen-PR, der zwei Wochen im Review hängt. Ich halte Diffs lesbar und Gates automatisiert, damit es vorangeht.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit ist bewusst klein. Vier Projekte pro Quartal — nie mehr. Jeder Kunde bekommt alle Senioren an den Tisch. Das ist das Modell.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Markenstrategin mit Hintergrund in Semiotik und Verhaltensökonomie. Zuvor bei Wolff Olins London. Überzeugt, dass jede große Identität mit einer klaren Haltung beginnt.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Typografie-Besessene, Systemdenkerin, früher bei Pentagram. Sana übersetzt strategische Klarheit in visuelle Präzision — nichts ist beliebig, alles skaliert.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Überführt statische Marken in lebende Systeme — Motion Identity, interaktives Web, digitale Touchpoints. Arbeitete mit Nike Digital und Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Hochperformante 3D-Komponenten für das moderne Web. Wir verbinden kreatives Können mit rigoroser Optimierung auf GPU-Ebene.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Hochauflösendes Echtzeit-3D direkt im Browser: leichte Meshes, optimierte PBR-Texturen, physikalisch korrektes Licht.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "AR-Kampagnen ohne App: Über einen Link platzieren Kunden Produkte fotorealistisch im eigenen Raum.",
    "camera filters and custom overlays": "Kamerafilter und individuelle Overlays",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism verbindet sich nativ mit Ihrem Data Warehouse, CRM, Zahlungsdienstleister und Ihren Werbekanälen. Keine individuellen API-Integrationen nötig.",
    "sync raw events natively from databases and query engines.": "Rohereignisse nativ aus Datenbanken und Query-Engines synchronisieren.",
    "align transaction records with user behavior metrics.": "Transaktionen mit Verhaltensmetriken abgleichen.",
    "enrich user profiles and trigger messaging based on user actions.": "Profile anreichern und Nachrichten aktionsbasiert auslösen.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Entwurf von A bis Z, von der Skizze bis zum Betonguss. Strukturelle Ehrlichkeit ist unsere oberste Direktive, ohne visuelle Kompromisse.",
    "scope of work:": "Leistungsumfang:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Großmaßstäbliche Planungsstrategien für öffentliche Einrichtungen und Campusse. Unsere Masterpläne verankern Baugruppen in logischer Dichte.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Wir lassen Stahl, Beton und Leitungen sichtbar: Die Haustechnik ist Teil der Ästhetik, statt hinter Verkleidungen zu verschwinden.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sieben Tage in einer uralten Wüstenlandschaft. Somatische Praxis im Morgengrauen, stille Mittagswanderungen, Feuerzeremonien am Abend. Ohne Agenda. Ohne Leistung.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Immersive Retreats in den verwandelndsten Landschaften der Welt. Höchstens neun Teilnehmende. Stille als Praxis.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Ich verbringe Wochen an jedem Ort, bevor ein Bild entsteht. Den Bergen ist mein Zeitplan gleich. Der Nebel kommt, wann er will. Diese Geduld ist die ganze Methode.",
    "each print is made in partnership with atelier gaspard in": "Jeder Abzug entsteht mit dem Atelier Gaspard in",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Für redaktionelle Lizenzen, kommerzielle Nutzung oder private Aufträge schreiben Sie mir direkt. Für Drucke besuchen Sie den Shop.",
    "bring the wild": "Holen Sie die Wildnis",
    "that's the point.": "Genau darum geht es.",
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Kollaborativer Code-Editor in Echtzeit. WebSockets, Monaco Editor, Y.js-CRDT.",
    "quick setup instructions": "Schnelleinstieg",
    "launch shell simulator": "Terminal-Simulator starten",
    "languages": "Sprachen",
    "staff engineer": "Staff Engineer",
    "senior frontend": "Senior-Frontend-Entwickler",
    "founding engineer": "Erster Ingenieur",
    "since 2014": "seit 2014",
    "github stars": "GitHub-Sterne",
    "across 6 repos": "über sechs Repositories",
    "uptime sla": "garantierte Verfügbarkeit",
    "last 24 months": "in den letzten 24 Monaten",
    "latency cut": "weniger Latenz",
    "p99.9 at stripe": "p99,9 bei Stripe",
    "faang companies": "Big-Tech-Unternehmen",
    "payload reduction": "weniger Nutzlast",
    "crdt compaction pipeline": "CRDT-Kompaktierungspipeline",
    "€1 200 / day": "1 200 € / Tag",
    "€8 000 flat": "8 000 € pauschal",
    "€800 / day": "800 € / Tag",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Ich arbeite als Principal Engineer in Ihren Produktteams: kritische Infrastruktur, RFCs, Auflösen systemischer Blockaden. Bei Stripe und Vercel habe ich Teams bei Problemen geführt, deren Scheitern zweistellige Millionenbeträge kostet.",
    "performance audits": "Performance-Audits",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Zwei fokussierte Wochen: Profiling, verteiltes Tracing, Identifikation von Engpässen und eine priorisierte Roadmap. Lieferung: ein schriftlicher Bericht und funktionierende Patches. Frühere Kunden senkten ihren p99 um 30 bis 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Projekt-Governance, Onboarding von Beitragenden, Lizenz-Audits, Roadmap-Sequenzierung. Ich helfe technikgetriebenen Unternehmen, nachhaltigen Wert aus Open Source zu ziehen, ohne ihre Maintainer auszubrennen.",
    "technical due diligence": "Technische Due Diligence",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Tiefenprüfung vor Übernahme oder Investition: Codequalität, Sicherheitslage, Skalierungsgrenze, Schlüsselpersonenrisiko, verborgene Verbindlichkeiten. Schriftlicher Bericht in fünf Werktagen, gremientauglich.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Saubere Übergabe: dokumentierte Architekturentscheidungen, Runbooks und zwei Wochen Rückfragezeit nach dem Einsatz. Kein verwaister Code.",
    "recent builds": "Aktuelle Arbeiten",
    "full project catalogue": "Der gesamte Projektkatalog",
    "project impact summary": "Zusammenfassung der Projektwirkung",
    "principal engineer, datadog": "Principal Engineer, Datadog",
    "engineering lead, pennylane": "Engineering-Leiterin, Pennylane",
    "vp engineering, alan": "Engineering-Direktor, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "30-minütiger asynchroner Briefing über Loom oder schriftliches Dokument. Ich habe Ihren Tech-Stack gelesen, den Einschränkungsbereich verstanden und alles markiert, was den Umfang ändert.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Verfügbar für Senior-Engineering-Mandate, technische Beratung und Open Source. Ansässig in",
    "browse the work": "Die Arbeiten durchsehen",
    "built the real-time sync engine from scratch (yjs + crdts).": "Echtzeit-Synchronisationsmotor von Grund auf geschrieben (Yjs und CRDTs).",
    "cargo build — execution": "cargo build — Ausführung",
    "core contributor to next.js app router and turbopack.": "Kernbeitrag zu Next.js App Router und Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detailliert, präzise, kommuniziert Kompromisse statt Meinungen. Er lieferte ein 25-seitiges Architektur-RFC zu unserer Datenebene, das wir fast wörtlich versendet haben. Selten.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "Verteilte Tracing-CLI, die Anrufgraphen aus rohen OTLP-Spans über mehrere Dienste hinweg rekonstruiert.",
    "engagement process": "Engagement-Prozess",
    "featured open source": "Ausgewähltes Open Source",
    "find the milliseconds your users feel": "Die Millisekunden finden, die Ihre Nutzer spüren",
    "hire me": "stelle mich ein",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Sein Performance-Audit fand drei systematische Abfrage-Muster, die wir zwei Jahre lang übersehen hatten. Der Fix wurde in einem Sprint bereitgestellt. Zehnmal so viel wert wie die Gebühr.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Ich nehme 1–2 fokussierte Engagements pro Quartal an. Wenn dein Zeitrahmen passt, lass uns herausfinden, ob wir zusammenpassen.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Ich arbeite in kurzen Zyklen mit sichtbaren Ergebnissen. Jede Woche endet mit einem Loom-Durchgang über das, was versendet wurde, was nicht und warum.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Inkrementelle Build-Cache-Schicht für Cargo-Arbeitsbereiche. Reduziert die CI-Zeiten um 40-70 % durch inhaltsadressierte Artefakte.",
    "know what you're acquiring": "Wissen, was Sie kaufen",
    "led infrastructure reliability for payment processing at scale.": "Leitete die Infrastrukturzuverlässigkeit für die Zahlungsabwicklung in großem Maßstab.",
    "let's build something great.": "Bauen wir etwas Gutes.",
    "open source advisory": "Open-Source-Beratung",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Open-Source-Beratung von jemandem, der tatsächlich große OSS-Projekte versendet und gewartet hat. Nicht nur Theorie. Würde sofort wieder mit ihm arbeiten.",
    "previous employers and clients": "frühere Arbeitgeber und Kunden",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël hat unseren Abgleichdienst in vier Wochen neu geschrieben. Das P99 fiel von 900 ms auf 120 ms. Der Code, den er hinterließ, ist der sauberste, den wir haben — und das will etwas heißen.",
    "ready to ship something great?": "Bereit, etwas Großartiges zu versenden?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Geteiltes Dokument mit Zielen, Erfolgskriterien und wöchentlichem Rhythmus. Keine Überraschungspivots. Wenn sich das Problem während des Engagements ändert, definieren wir den Umfang schriftlich neu.",
    "sustainable oss strategy for your company": "Eine tragfähige Open-Source-Strategie für Ihr Unternehmen",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Terminalbasiertes API-Testframework mit Snapshot-Diffs und CI/CD-Integration.",
    "the setup": "die Einrichtung",
    "view full architecture impact": "Vollständige architektonische Auswirkungen anzeigen",
    "view source": "Quelltext anzeigen",
    "view work()": "arbeitenAnsehen()",
    "what engineers say": "Was Entwickler sagen",
    "what i do": "was ich tue",
    "work environment": "Arbeitsumgebung",
  },
  pt: {
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Um documento sobre a minha forma de trabalhar — as ferramentas, a filosofia, a instalação. Porque o ambiente molda o resultado.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Um truque brilhante que três engenheiros já não saberão ler no próximo trimestre é um passivo, não um ativo. Otimizo para o próximo engenheiro no código.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "A intuição sobre desempenho quase sempre se engana. Perfis, rastreios distribuídos e telemetria de produção devem guiar as decisões de otimização.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Um PR de 50 linhas entregue hoje vale mais do que um de 500 que fica duas semanas em revisão. Mantenho diffs legíveis e controlos automatizados para que as coisas avancem.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "A Orbit é deliberadamente pequena. Quatro projetos por trimestre — nunca mais. Cada cliente tem todos os seniores à mesa. É o modelo.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Estratega de marca, vinda da semiótica e da economia comportamental. Antes na Wolff Olins em Londres. Convicta de que toda a grande identidade parte de um ponto de vista afiado.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obcecada por tipografia, mente sistémica, ex-Pentagram. A Sana converte clareza estratégica em precisão visual — nada é arbitrário, tudo escala.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Leva a marca do estático ao vivo — identidade em movimento, web interativa, pontos de contacto digitais. Trabalhou com a Nike Digital e o Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Componentes 3D de alto desempenho para a web moderna. Unimos o gesto criativo a uma otimização rigorosa ao nível do GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Renderização 3D em tempo real de alta fidelidade, diretamente no navegador: malhas leves, texturas PBR otimizadas, iluminação fisicamente exata.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Campanhas de realidade aumentada sem aplicação: com um simples link, o cliente coloca o produto no seu espaço com realismo fotográfico.",
    "camera filters and custom overlays": "Filtros de câmara e sobreposições à medida",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "O Prism liga-se nativamente ao seu armazém de dados, CRM, processador de pagamentos e canais publicitários. Sem integrações à medida.",
    "sync raw events natively from databases and query engines.": "Sincronize eventos em bruto das suas bases e motores de consulta.",
    "align transaction records with user behavior metrics.": "Alinhe as transações com as métricas de comportamento.",
    "enrich user profiles and trigger messaging based on user actions.": "Enriqueça os perfis e dispare mensagens conforme as ações.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Conceção de ponta a ponta, do esboço à betonagem. A honestidade estrutural é a nossa diretiva primeira, sem compromissos visuais.",
    "scope of work:": "Âmbito:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Estratégias de ordenamento em grande escala para instituições públicas e campi. Os nossos planos diretores ancoram os conjuntos numa densidade lógica.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Deixamos o aço, o betão e as condutas à vista: os sistemas interiores fazem parte da estética em vez de se esconderem atrás de acabamentos.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sete dias num deserto antigo. Prática somática de madrugada, caminhadas silenciosas ao meio-dia, cerimónias do fogo à noite. Sem agenda. Sem desempenho.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Retiros imersivos nas paisagens mais transformadoras do mundo. Nove participantes no máximo. A calma como prática.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Passo semanas em cada lugar antes de fazer uma imagem. As montanhas não querem saber do meu calendário. O nevoeiro chega quando quer. Essa paciência é todo o método.",
    "each print is made in partnership with atelier gaspard in": "Cada impressão é feita com o Atelier Gaspard em",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Para licenças editoriais, usos comerciais ou encomendas privadas, escreva-me diretamente. Para impressões, passe pela loja.",
    "bring the wild": "Traga o selvagem",
    "that's the point.": "É exatamente esse o ponto.",
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Editor de código colaborativo em tempo real. WebSockets, Monaco Editor, CRDT Y.js.",
    "quick setup instructions": "Arranque rápido",
    "launch shell simulator": "Lançar o simulador de terminal",
    "languages": "Linguagens",
    "staff engineer": "Engenheiro principal",
    "senior frontend": "Programador front-end sénior",
    "founding engineer": "Primeiro engenheiro",
    "since 2014": "desde 2014",
    "github stars": "estrelas GitHub",
    "across 6 repos": "em seis repositórios",
    "uptime sla": "disponibilidade garantida",
    "last 24 months": "nos últimos 24 meses",
    "latency cut": "menos de latência",
    "p99.9 at stripe": "p99,9 na Stripe",
    "faang companies": "empresas da grande tecnologia",
    "payload reduction": "menos carga útil",
    "crdt compaction pipeline": "cadeia de compactação CRDT",
    "€1 200 / day": "1 200 € / dia",
    "€8 000 flat": "8 000 € a preço fechado",
    "€800 / day": "800 € / dia",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Integro-me como engenheiro principal nas suas equipas de produto: infraestrutura crítica, redação de RFC, desbloqueio de pontos difíceis ao nível do sistema. Liderei equipas na Stripe e na Vercel em problemas onde a falha se mede em dezenas de milhões.",
    "performance audits": "Auditorias de desempenho",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Duas semanas concentradas: perfilagem, rastreio distribuído, identificação de estrangulamentos e um roteiro de correção priorizado. Entregáveis: um relatório escrito e correções que funcionam. Clientes anteriores viram o p99 descer entre 30 e 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Governação do projeto, acolhimento de contribuidores, auditoria de licenças, sequenciação do roteiro. Ajudo empresas lideradas pela engenharia a extrair valor duradouro do software livre sem esgotar os seus mantenedores.",
    "technical due diligence": "Auditoria técnica de aquisição",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Exame aprofundado antes de aquisição ou investimento: qualidade do código, postura de segurança, teto de escalabilidade, dependência de pessoas-chave, passivos ocultos. Relatório escrito em cinco dias úteis, apresentável em conselho.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Passagem limpa: decisões de arquitetura documentadas, procedimentos de operação e duas semanas de perguntas após a missão. Nenhum código órfão.",
    "recent builds": "Trabalhos recentes",
    "full project catalogue": "Todo o catálogo de projetos",
    "project impact summary": "Síntese do impacto dos projetos",
    "principal engineer, datadog": "Engenheiro principal, Datadog",
    "engineering lead, pennylane": "Responsável de engenharia, Pennylane",
    "vp engineering, alan": "Diretor de engenharia, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Resumo assíncrono de 30 minutos via Loom ou documento escrito. Li a sua pilha tecnológica, entendi o espaço de restrições e sinalizei qualquer coisa que mudasse o escopo.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponível para missões de engenharia sénior, consultoria técnica e código aberto. Sediado em",
    "browse the work": "Ver os trabalhos",
    "built the real-time sync engine from scratch (yjs + crdts).": "Motor de sincronização em tempo real escrito de raiz (Yjs e CRDTs).",
    "cargo build — execution": "cargo build — Execução",
    "core contributor to next.js app router and turbopack.": "Contribuidor principal para Next.js App Router e Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detalhado, preciso, comunica compromissos em vez de opiniões. Ele entregou um RFC de arquitetura de 25 páginas sobre nossa camada de dados que enviamos quase palavra por palavra. Raro.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de rastreamento distribuído que reconstrói gráficos de chamadas a partir de spans OTLP brutos em vários serviços.",
    "engagement process": "Processo de compromisso",
    "featured open source": "Código aberto em destaque",
    "find the milliseconds your users feel": "Encontrar os milissegundos que os seus utilizadores sentem",
    "hire me": "contrate-me",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "A sua auditoria de desempenho encontrou três padrões de consulta sistémicos que perdemos durante dois anos. A correção foi implementada em um sprint. Vale dez vezes a taxa.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Aceito 1 a 2 compromissos focados por trimestre. Se o seu cronograma se encaixar, vamos descobrir se somos compatíveis.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Trabalho em ciclos curtos com resultados visíveis. Cada semana termina com uma apresentação Loom sobre o que foi enviado, o que não foi e por quê.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Camada de cache de construção incremental para espaços de trabalho Cargo. Reduz os tempos de CI em 40-70% através de artefatos endereçados por conteúdo.",
    "know what you're acquiring": "Saber o que está a adquirir",
    "led infrastructure reliability for payment processing at scale.": "Liderou a fiabilidade da infraestrutura para o processamento de pagamentos em grande escala.",
    "let's build something great.": "Vamos construir algo bom.",
    "open source advisory": "Aconselhamento em código aberto",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Assessoria de código aberto de alguém que realmente enviou e manteve grandes projetos de OSS. Não apenas teoria. Trabalharia com ele novamente imediatamente.",
    "previous employers and clients": "empregadores e clientes anteriores",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "O Raphaël reescreveu o nosso serviço de reconciliação de transações em quatro semanas. O P99 passou de 900 ms para 120 ms. O código que deixou é o mais limpo que temos — e não é pouco dizer.",
    "ready to ship something great?": "Pronto para enviar algo incrível?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Documento partilhado com objetivos, critérios de sucesso e cadência semanal. Sem pivôs surpresa. Se o problema mudar durante o compromisso, redefinimos o escopo por escrito.",
    "sustainable oss strategy for your company": "Uma estratégia de código aberto sustentável para a sua empresa",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Estrutura de teste de API baseada em terminal com diferenças de instantâneas e integração CI/CD.",
    "the setup": "a configuração",
    "view full architecture impact": "Ver o impacto arquitetónico completo",
    "view source": "Ver fonte",
    "view work()": "verTrabalhos()",
    "what engineers say": "O que dizem os engenheiros",
    "what i do": "o que eu faço",
    "work environment": "Ambiente de trabalho",
  },
};
