/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Éditeur de code collaboratif en temps réel. WebSockets, Monaco Editor, CRDT Y.js.",
    "quick setup instructions": "Mise en route rapide",
    "launch shell simulator": "Lancer le simulateur de terminal",
    "languages": "Langages",
    "staff engineer": "Ingénieur principal",
    "senior frontend": "Développeur front-end senior",
    "founding engineer": "Premier ingénieur",
    "since 2014": "depuis 2014",
    "github stars": "étoiles GitHub",
    "across 6 repos": "sur six dépôts",
    "uptime sla": "disponibilité garantie",
    "last 24 months": "sur les 24 derniers mois",
    "latency cut": "de latence en moins",
    "p99.9 at stripe": "p99,9 chez Stripe",
    "faang companies": "entreprises de la tech mondiale",
    "payload reduction": "de charge utile en moins",
    "crdt compaction pipeline": "chaîne de compaction CRDT",
    "€1 200 / day": "1 200 € / jour",
    "€8 000 flat": "8 000 € au forfait",
    "€800 / day": "800 € / jour",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Je m'intègre comme ingénieur principal dans vos équipes produit : infrastructure critique, rédaction des RFC, déblocage des points durs au niveau système. J'ai mené des équipes chez Stripe et Vercel sur des sujets où l'échec se chiffre en dizaines de millions.",
    "performance audits": "Audits de performance",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Deux semaines resserrées : profilage, traçage distribué, identification des goulots et feuille de route de correction hiérarchisée. Livrables : un rapport écrit et des correctifs qui fonctionnent. Les clients précédents ont vu leur p99 baisser de 30 à 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Gouvernance du projet, accueil des contributeurs, audit des licences, séquencement de la feuille de route. J'aide les entreprises portées par l'ingénierie à tirer une valeur durable du logiciel libre sans épuiser leurs mainteneurs.",
    "technical due diligence": "Audit technique d'acquisition",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Examen approfondi avant rachat ou investissement : qualité du code, posture de sécurité, plafond de montée en charge, dépendance aux personnes clés, passifs cachés. Rapport écrit en cinq jours ouvrés, présentable en conseil d'administration.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Passation propre : décisions d'architecture documentées, procédures d'exploitation, et deux semaines de questions-réponses après la mission. Aucun code orphelin.",
    "recent builds": "Réalisations récentes",
    "full project catalogue": "Tout le catalogue de projets",
    "project impact summary": "Synthèse de l'impact des projets",
    "principal engineer, datadog": "Ingénieur principal, Datadog",
    "engineering lead, pennylane": "Responsable ingénierie, Pennylane",
    "vp engineering, alan": "Directeur de l'ingénierie, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Brief asynchrone de 30 minutes via Loom ou document écrit. J'ai lu votre stack technologique, compris l'espace de contraintes et signalé tout ce qui change la portée.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponible pour des missions d'ingénierie senior, du conseil technique et du logiciel libre. Basé à",
    "browse the work": "Parcourir les réalisations",
    "built the real-time sync engine from scratch (yjs + crdts).": "Moteur de synchronisation en temps réel écrit de zéro (Yjs et CRDT).",
    "cargo build — execution": "cargo build — Exécution",
    "core contributor to next.js app router and turbopack.": "Contributeur principal à Next.js App Router et Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Détaillé, précis, communique des compromis au lieu d'opinions. Il a livré un RFC d'architecture de 25 pages sur notre couche de données que nous avons expédié presque mot pour mot. Rare.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de traçage distribué qui reconstruit des graphes d'appels à partir de spans OTLP bruts à travers plusieurs services.",
    "engagement process": "Processus d'engagement",
    "featured open source": "Logiciel libre mis en avant",
    "find the milliseconds your users feel": "Trouver les millisecondes que vos utilisateurs ressentent",
    "hire me": "engagez-moi",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Son audit de performance a trouvé trois modèles de requêtes systémiques que nous avions manqués pendant deux ans. La correction a été déployée en un sprint. Vaut dix fois le tarif.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Je prends 1 à 2 engagements ciblés par trimestre. Si votre calendrier le permet, voyons si nous sommes compatibles.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Je travaille en courts cycles avec des résultats visibles. Chaque semaine se termine par une présentation Loom de ce qui a été expédié, de ce qui ne l'a pas été et pourquoi.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Couche de cache de construction incrémentale pour les espaces de travail Cargo. Réduit les temps CI de 40 à 70 % grâce à des artefacts adressés par contenu.",
    "know what you're acquiring": "Savoir ce que vous rachetez",
    "led infrastructure reliability for payment processing at scale.": "A dirigé la fiabilité de l'infrastructure pour le traitement des paiements à grande échelle.",
    "let's build something great.": "Bâtissons quelque chose de bien.",
    "open source advisory": "Conseil en logiciel libre",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Conseil en open source d'une personne qui a réellement expédié et maintenu de grands projets OSS. Pas seulement de la théorie. Je travaillerais à nouveau avec lui immédiatement.",
    "previous employers and clients": "anciens employeurs et clients",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël a réécrit notre service de rapprochement des transactions en quatre semaines. Le P99 est passé de 900 ms à 120 ms. Le code qu'il a laissé est le plus propre que nous ayons — et ce n'est pas peu dire.",
    "ready to ship something great?": "Prêt à expédier quelque chose de génial ?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Document partagé avec des objectifs, des critères de succès et une cadence hebdomadaire. Pas de pivots surprises. Si le problème change en cours d'engagement, nous redéfinissons la portée par écrit.",
    "sustainable oss strategy for your company": "Une stratégie de logiciel libre tenable pour votre entreprise",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Cadre de test API basé sur le terminal avec des différences de snapshot et une intégration CI/CD.",
    "the setup": "la configuration",
    "view full architecture impact": "Voir l'impact architectural complet",
    "view source": "Voir la source",
    "view work()": "voirRéalisations()",
    "what engineers say": "Ce qu'en disent les ingénieurs",
    "what i do": "ce que je fais",
    "work environment": "Environnement de travail",
  },
  es: {
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Editor de código colaborativo en tiempo real. WebSockets, Monaco Editor, CRDT Y.js.",
    "quick setup instructions": "Puesta en marcha rápida",
    "launch shell simulator": "Lanzar el simulador de terminal",
    "languages": "Lenguajes",
    "staff engineer": "Ingeniero principal",
    "senior frontend": "Desarrollador front-end sénior",
    "founding engineer": "Primer ingeniero",
    "since 2014": "desde 2014",
    "github stars": "estrellas GitHub",
    "across 6 repos": "en seis repositorios",
    "uptime sla": "disponibilidad garantizada",
    "last 24 months": "en los últimos 24 meses",
    "latency cut": "menos de latencia",
    "p99.9 at stripe": "p99,9 en Stripe",
    "faang companies": "empresas de la gran tecnología",
    "payload reduction": "menos carga útil",
    "crdt compaction pipeline": "cadena de compactación CRDT",
    "€1 200 / day": "1 200 € / día",
    "€8 000 flat": "8 000 € a tanto alzado",
    "€800 / day": "800 € / día",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Me integro como ingeniero principal en sus equipos de producto: infraestructura crítica, redacción de RFC, desbloqueo de puntos duros a nivel de sistema. He dirigido equipos en Stripe y Vercel en problemas donde el fallo se mide en decenas de millones.",
    "performance audits": "Auditorías de rendimiento",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Dos semanas concentradas: perfilado, trazado distribuido, identificación de cuellos de botella y hoja de ruta de corrección priorizada. Entregables: un informe escrito y parches que funcionan. Clientes anteriores vieron bajar su p99 entre un 30 y un 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Gobernanza del proyecto, acogida de contribuidores, auditoría de licencias, secuenciación de la hoja de ruta. Ayudo a empresas dirigidas por la ingeniería a extraer valor duradero del software libre sin quemar a sus mantenedores.",
    "technical due diligence": "Diligencia técnica",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Examen a fondo antes de una compra o inversión: calidad del código, postura de seguridad, techo de escalabilidad, dependencia de personas clave, pasivos ocultos. Informe escrito en cinco días hábiles, presentable ante el consejo.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Traspaso limpio: decisiones de arquitectura documentadas, procedimientos de operación y dos semanas de preguntas tras la misión. Ningún código huérfano.",
    "recent builds": "Trabajos recientes",
    "full project catalogue": "Todo el catálogo de proyectos",
    "project impact summary": "Resumen del impacto de los proyectos",
    "principal engineer, datadog": "Ingeniero principal, Datadog",
    "engineering lead, pennylane": "Responsable de ingeniería, Pennylane",
    "vp engineering, alan": "Director de ingeniería, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Resumen asíncrono de 30 minutos a través de Loom o documento escrito. Leí su stack tecnológico, entendí el espacio de restricciones y señalé cualquier cosa que cambie el alcance.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponible para misiones de ingeniería sénior, consultoría técnica y código abierto. Con base en",
    "browse the work": "Ver los trabajos",
    "built the real-time sync engine from scratch (yjs + crdts).": "Motor de sincronización en tiempo real escrito desde cero (Yjs y CRDT).",
    "cargo build — execution": "cargo build — Ejecución",
    "core contributor to next.js app router and turbopack.": "Contribuyente principal a Next.js App Router y Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detallado, preciso, comunica compensaciones en lugar de opiniones. Entregó un RFC de arquitectura de 25 páginas sobre nuestra capa de datos que enviamos casi palabra por palabra. Raro.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de trazado distribuido que reconstruye gráficos de llamadas a partir de spans OTLP en bruto a través de múltiples servicios.",
    "engagement process": "Proceso de compromiso",
    "featured open source": "Código abierto destacado",
    "find the milliseconds your users feel": "Encontrar los milisegundos que sus usuarios notan",
    "hire me": "contrátame",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Su auditoría de rendimiento encontró tres patrones de consulta sistémicos que habíamos pasado por alto durante dos años. La solución se implementó en un sprint. Vale diez veces la tarifa.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Acepto 1 a 2 compromisos enfocados por trimestre. Si tu cronograma encaja, averigüemos si somos compatibles.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Trabajo en ciclos cortos con resultados visibles. Cada semana termina con un recorrido de Loom sobre lo que se envió, lo que no se envió y por qué.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Capa de caché de construcción incremental para espacios de trabajo Cargo. Reduce los tiempos de CI en un 40-70% a través de artefactos dirigidos por contenido.",
    "know what you're acquiring": "Saber lo que está adquiriendo",
    "led infrastructure reliability for payment processing at scale.": "Lideró la fiabilidad de la infraestructura para el procesamiento de pagos a gran escala.",
    "let's build something great.": "Construyamos algo bueno.",
    "open source advisory": "Asesoramiento en código abierto",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Asesoría de código abierto de alguien que realmente ha enviado y mantenido grandes proyectos de OSS. No solo teoría. Trabajaría con él de nuevo de inmediato.",
    "previous employers and clients": "empleadores y clientes anteriores",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël reescribió nuestro servicio de conciliación de transacciones en cuatro semanas. El P99 pasó de 900 ms a 120 ms. El código que dejó es el más limpio que tenemos, y no es poco decir.",
    "ready to ship something great?": "¿Listo para enviar algo grandioso?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Documento compartido con objetivos, criterios de éxito y cadencia semanal. Sin pivotes sorpresa. Si el problema cambia a mitad del compromiso, redefinimos el alcance por escrito.",
    "sustainable oss strategy for your company": "Una estrategia de código abierto sostenible para su empresa",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Marco de pruebas de API basado en terminal con diferencias de instantáneas e integración CI/CD.",
    "the setup": "la configuración",
    "view full architecture impact": "Ver el impacto arquitectónico completo",
    "view source": "Ver fuente",
    "view work()": "verTrabajos()",
    "what engineers say": "Lo que dicen los ingenieros",
    "what i do": "lo que hago",
    "work environment": "Entorno de trabajo",
  },
  de: {
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Kollaborativer Code-Editor in Echtzeit. WebSockets, Monaco Editor, Y.js-CRDT.",
    "quick setup instructions": "Schnelleinstieg",
    "launch shell simulator": "Terminal-Simulator starten",
    "languages": "Sprachen",
    "staff engineer": "Staff Engineer",
    "senior frontend": "Senior-Frontend-Entwickler",
    "founding engineer": "Erster Ingenieur",
    "since 2014": "seit 2014",
    "github stars": "GitHub-Sterne",
    "across 6 repos": "über sechs Repositories",
    "uptime sla": "garantierte Verfügbarkeit",
    "last 24 months": "in den letzten 24 Monaten",
    "latency cut": "weniger Latenz",
    "p99.9 at stripe": "p99,9 bei Stripe",
    "faang companies": "Big-Tech-Unternehmen",
    "payload reduction": "weniger Nutzlast",
    "crdt compaction pipeline": "CRDT-Kompaktierungspipeline",
    "€1 200 / day": "1 200 € / Tag",
    "€8 000 flat": "8 000 € pauschal",
    "€800 / day": "800 € / Tag",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Ich arbeite als Principal Engineer in Ihren Produktteams: kritische Infrastruktur, RFCs, Auflösen systemischer Blockaden. Bei Stripe und Vercel habe ich Teams bei Problemen geführt, deren Scheitern zweistellige Millionenbeträge kostet.",
    "performance audits": "Performance-Audits",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Zwei fokussierte Wochen: Profiling, verteiltes Tracing, Identifikation von Engpässen und eine priorisierte Roadmap. Lieferung: ein schriftlicher Bericht und funktionierende Patches. Frühere Kunden senkten ihren p99 um 30 bis 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Projekt-Governance, Onboarding von Beitragenden, Lizenz-Audits, Roadmap-Sequenzierung. Ich helfe technikgetriebenen Unternehmen, nachhaltigen Wert aus Open Source zu ziehen, ohne ihre Maintainer auszubrennen.",
    "technical due diligence": "Technische Due Diligence",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Tiefenprüfung vor Übernahme oder Investition: Codequalität, Sicherheitslage, Skalierungsgrenze, Schlüsselpersonenrisiko, verborgene Verbindlichkeiten. Schriftlicher Bericht in fünf Werktagen, gremientauglich.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Saubere Übergabe: dokumentierte Architekturentscheidungen, Runbooks und zwei Wochen Rückfragezeit nach dem Einsatz. Kein verwaister Code.",
    "recent builds": "Aktuelle Arbeiten",
    "full project catalogue": "Der gesamte Projektkatalog",
    "project impact summary": "Zusammenfassung der Projektwirkung",
    "principal engineer, datadog": "Principal Engineer, Datadog",
    "engineering lead, pennylane": "Engineering-Leiterin, Pennylane",
    "vp engineering, alan": "Engineering-Direktor, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "30-minütiger asynchroner Briefing über Loom oder schriftliches Dokument. Ich habe Ihren Tech-Stack gelesen, den Einschränkungsbereich verstanden und alles markiert, was den Umfang ändert.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Verfügbar für Senior-Engineering-Mandate, technische Beratung und Open Source. Ansässig in",
    "browse the work": "Die Arbeiten durchsehen",
    "built the real-time sync engine from scratch (yjs + crdts).": "Echtzeit-Synchronisationsmotor von Grund auf geschrieben (Yjs und CRDTs).",
    "cargo build — execution": "cargo build — Ausführung",
    "core contributor to next.js app router and turbopack.": "Kernbeitrag zu Next.js App Router und Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detailliert, präzise, kommuniziert Kompromisse statt Meinungen. Er lieferte ein 25-seitiges Architektur-RFC zu unserer Datenebene, das wir fast wörtlich versendet haben. Selten.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "Verteilte Tracing-CLI, die Anrufgraphen aus rohen OTLP-Spans über mehrere Dienste hinweg rekonstruiert.",
    "engagement process": "Engagement-Prozess",
    "featured open source": "Ausgewähltes Open Source",
    "find the milliseconds your users feel": "Die Millisekunden finden, die Ihre Nutzer spüren",
    "hire me": "stelle mich ein",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Sein Performance-Audit fand drei systematische Abfrage-Muster, die wir zwei Jahre lang übersehen hatten. Der Fix wurde in einem Sprint bereitgestellt. Zehnmal so viel wert wie die Gebühr.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Ich nehme 1–2 fokussierte Engagements pro Quartal an. Wenn dein Zeitrahmen passt, lass uns herausfinden, ob wir zusammenpassen.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Ich arbeite in kurzen Zyklen mit sichtbaren Ergebnissen. Jede Woche endet mit einem Loom-Durchgang über das, was versendet wurde, was nicht und warum.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Inkrementelle Build-Cache-Schicht für Cargo-Arbeitsbereiche. Reduziert die CI-Zeiten um 40-70 % durch inhaltsadressierte Artefakte.",
    "know what you're acquiring": "Wissen, was Sie kaufen",
    "led infrastructure reliability for payment processing at scale.": "Leitete die Infrastrukturzuverlässigkeit für die Zahlungsabwicklung in großem Maßstab.",
    "let's build something great.": "Bauen wir etwas Gutes.",
    "open source advisory": "Open-Source-Beratung",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Open-Source-Beratung von jemandem, der tatsächlich große OSS-Projekte versendet und gewartet hat. Nicht nur Theorie. Würde sofort wieder mit ihm arbeiten.",
    "previous employers and clients": "frühere Arbeitgeber und Kunden",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël hat unseren Abgleichdienst in vier Wochen neu geschrieben. Das P99 fiel von 900 ms auf 120 ms. Der Code, den er hinterließ, ist der sauberste, den wir haben — und das will etwas heißen.",
    "ready to ship something great?": "Bereit, etwas Großartiges zu versenden?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Geteiltes Dokument mit Zielen, Erfolgskriterien und wöchentlichem Rhythmus. Keine Überraschungspivots. Wenn sich das Problem während des Engagements ändert, definieren wir den Umfang schriftlich neu.",
    "sustainable oss strategy for your company": "Eine tragfähige Open-Source-Strategie für Ihr Unternehmen",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Terminalbasiertes API-Testframework mit Snapshot-Diffs und CI/CD-Integration.",
    "the setup": "die Einrichtung",
    "view full architecture impact": "Vollständige architektonische Auswirkungen anzeigen",
    "view source": "Quelltext anzeigen",
    "view work()": "arbeitenAnsehen()",
    "what engineers say": "Was Entwickler sagen",
    "what i do": "was ich tue",
    "work environment": "Arbeitsumgebung",
  },
  pt: {
    "real-time collaborative code editor. websockets, monaco editor, y.js crdt.": "Editor de código colaborativo em tempo real. WebSockets, Monaco Editor, CRDT Y.js.",
    "quick setup instructions": "Arranque rápido",
    "launch shell simulator": "Lançar o simulador de terminal",
    "languages": "Linguagens",
    "staff engineer": "Engenheiro principal",
    "senior frontend": "Programador front-end sénior",
    "founding engineer": "Primeiro engenheiro",
    "since 2014": "desde 2014",
    "github stars": "estrelas GitHub",
    "across 6 repos": "em seis repositórios",
    "uptime sla": "disponibilidade garantida",
    "last 24 months": "nos últimos 24 meses",
    "latency cut": "menos de latência",
    "p99.9 at stripe": "p99,9 na Stripe",
    "faang companies": "empresas da grande tecnologia",
    "payload reduction": "menos carga útil",
    "crdt compaction pipeline": "cadeia de compactação CRDT",
    "€1 200 / day": "1 200 € / dia",
    "€8 000 flat": "8 000 € a preço fechado",
    "€800 / day": "800 € / dia",
    "i embed as a principal or staff engineer on product teams — owning critical infrastructure, driving rfcs, and unblocking roadblocks at the systems level. i've led teams at stripe and vercel on problems where the cost of failure is measured in eight figures.": "Integro-me como engenheiro principal nas suas equipas de produto: infraestrutura crítica, redação de RFC, desbloqueio de pontos difíceis ao nível do sistema. Liderei equipas na Stripe e na Vercel em problemas onde a falha se mede em dezenas de milhões.",
    "performance audits": "Auditorias de desempenho",
    "a focused 2-week engagement: profiling, distributed tracing, bottleneck identification, and a prioritized fix roadmap. deliverable is a written report + working patches. previous clients saw p99 reductions between 30 and 60 percent.": "Duas semanas concentradas: perfilagem, rastreio distribuído, identificação de estrangulamentos e um roteiro de correção priorizado. Entregáveis: um relatório escrito e correções que funcionam. Clientes anteriores viram o p99 descer entre 30 e 60 %.",
    "project governance, contributor onboarding pipelines, license audits, and roadmap sequencing. i help engineering-led companies extract compounding value from open source without burning their maintainers.": "Governação do projeto, acolhimento de contribuidores, auditoria de licenças, sequenciação do roteiro. Ajudo empresas lideradas pela engenharia a extrair valor duradouro do software livre sem esgotar os seus mantenedores.",
    "technical due diligence": "Auditoria técnica de aquisição",
    "pre-acquisition or pre-investment deep dives: codebase quality, security posture, scalability ceiling, key-person risk, and hidden liabilities. written report in 5 business days, suitable for board presentation.": "Exame aprofundado antes de aquisição ou investimento: qualidade do código, postura de segurança, teto de escalabilidade, dependência de pessoas-chave, passivos ocultos. Relatório escrito em cinco dias úteis, apresentável em conselho.",
    "clean handoff: documented architecture decisions, runbooks, and a post-engagement q&a window (2 weeks). no orphaned code.": "Passagem limpa: decisões de arquitetura documentadas, procedimentos de operação e duas semanas de perguntas após a missão. Nenhum código órfão.",
    "recent builds": "Trabalhos recentes",
    "full project catalogue": "Todo o catálogo de projetos",
    "project impact summary": "Síntese do impacto dos projetos",
    "principal engineer, datadog": "Engenheiro principal, Datadog",
    "engineering lead, pennylane": "Responsável de engenharia, Pennylane",
    "vp engineering, alan": "Diretor de engenharia, Alan",
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Resumo assíncrono de 30 minutos via Loom ou documento escrito. Li a sua pilha tecnológica, entendi o espaço de restrições e sinalizei qualquer coisa que mudasse o escopo.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponível para missões de engenharia sénior, consultoria técnica e código aberto. Sediado em",
    "browse the work": "Ver os trabalhos",
    "built the real-time sync engine from scratch (yjs + crdts).": "Motor de sincronização em tempo real escrito de raiz (Yjs e CRDTs).",
    "cargo build — execution": "cargo build — Execução",
    "core contributor to next.js app router and turbopack.": "Contribuidor principal para Next.js App Router e Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detalhado, preciso, comunica compromissos em vez de opiniões. Ele entregou um RFC de arquitetura de 25 páginas sobre nossa camada de dados que enviamos quase palavra por palavra. Raro.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de rastreamento distribuído que reconstrói gráficos de chamadas a partir de spans OTLP brutos em vários serviços.",
    "engagement process": "Processo de compromisso",
    "featured open source": "Código aberto em destaque",
    "find the milliseconds your users feel": "Encontrar os milissegundos que os seus utilizadores sentem",
    "hire me": "contrate-me",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "A sua auditoria de desempenho encontrou três padrões de consulta sistémicos que perdemos durante dois anos. A correção foi implementada em um sprint. Vale dez vezes a taxa.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Aceito 1 a 2 compromissos focados por trimestre. Se o seu cronograma se encaixar, vamos descobrir se somos compatíveis.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Trabalho em ciclos curtos com resultados visíveis. Cada semana termina com uma apresentação Loom sobre o que foi enviado, o que não foi e por quê.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Camada de cache de construção incremental para espaços de trabalho Cargo. Reduz os tempos de CI em 40-70% através de artefatos endereçados por conteúdo.",
    "know what you're acquiring": "Saber o que está a adquirir",
    "led infrastructure reliability for payment processing at scale.": "Liderou a fiabilidade da infraestrutura para o processamento de pagamentos em grande escala.",
    "let's build something great.": "Vamos construir algo bom.",
    "open source advisory": "Aconselhamento em código aberto",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Assessoria de código aberto de alguém que realmente enviou e manteve grandes projetos de OSS. Não apenas teoria. Trabalharia com ele novamente imediatamente.",
    "previous employers and clients": "empregadores e clientes anteriores",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "O Raphaël reescreveu o nosso serviço de reconciliação de transações em quatro semanas. O P99 passou de 900 ms para 120 ms. O código que deixou é o mais limpo que temos — e não é pouco dizer.",
    "ready to ship something great?": "Pronto para enviar algo incrível?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Documento partilhado com objetivos, critérios de sucesso e cadência semanal. Sem pivôs surpresa. Se o problema mudar durante o compromisso, redefinimos o escopo por escrito.",
    "sustainable oss strategy for your company": "Uma estratégia de código aberto sustentável para a sua empresa",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Estrutura de teste de API baseada em terminal com diferenças de instantâneas e integração CI/CD.",
    "the setup": "a configuração",
    "view full architecture impact": "Ver o impacto arquitetónico completo",
    "view source": "Ver fonte",
    "view work()": "verTrabalhos()",
    "what engineers say": "O que dizem os engenheiros",
    "what i do": "o que eu faço",
    "work environment": "Ambiente de trabalho",
  },
};
