/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Brief asynchrone de 30 minutes via Loom ou document écrit. J'ai lu votre stack technologique, compris l'espace de contraintes et signalé tout ce qui change la portée.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponible pour des missions d'ingénierie senior, du conseil technique et du logiciel libre. Basé à",
    "browse the work": "Parcourir les réalisations",
    "built the real-time sync engine from scratch (yjs + crdts).": "Moteur de synchronisation en temps réel écrit de zéro (Yjs et CRDT).",
    "cargo build — execution": "cargo build — Exécution",
    "core contributor to next.js app router and turbopack.": "Contributeur principal à Next.js App Router et Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Détaillé, précis, communique des compromis au lieu d'opinions. Il a livré un RFC d'architecture de 25 pages sur notre couche de données que nous avons expédié presque mot pour mot. Rare.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de traçage distribué qui reconstruit des graphes d'appels à partir de spans OTLP bruts à travers plusieurs services.",
    "engagement process": "Processus d'engagement",
    "featured open source": "Logiciel libre mis en avant",
    "find the milliseconds your users feel": "Trouver les millisecondes que vos utilisateurs ressentent",
    "hire me": "engagez-moi",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Son audit de performance a trouvé trois modèles de requêtes systémiques que nous avions manqués pendant deux ans. La correction a été déployée en un sprint. Vaut dix fois le tarif.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Je prends 1 à 2 engagements ciblés par trimestre. Si votre calendrier le permet, voyons si nous sommes compatibles.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Je travaille en courts cycles avec des résultats visibles. Chaque semaine se termine par une présentation Loom de ce qui a été expédié, de ce qui ne l'a pas été et pourquoi.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Couche de cache de construction incrémentale pour les espaces de travail Cargo. Réduit les temps CI de 40 à 70 % grâce à des artefacts adressés par contenu.",
    "know what you're acquiring": "Savoir ce que vous rachetez",
    "led infrastructure reliability for payment processing at scale.": "A dirigé la fiabilité de l'infrastructure pour le traitement des paiements à grande échelle.",
    "let's build something great.": "Bâtissons quelque chose de bien.",
    "open source advisory": "Conseil en logiciel libre",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Conseil en open source d'une personne qui a réellement expédié et maintenu de grands projets OSS. Pas seulement de la théorie. Je travaillerais à nouveau avec lui immédiatement.",
    "previous employers and clients": "anciens employeurs et clients",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël a réécrit notre service de rapprochement des transactions en quatre semaines. Le P99 est passé de 900 ms à 120 ms. Le code qu'il a laissé est le plus propre que nous ayons — et ce n'est pas peu dire.",
    "ready to ship something great?": "Prêt à expédier quelque chose de génial ?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Document partagé avec des objectifs, des critères de succès et une cadence hebdomadaire. Pas de pivots surprises. Si le problème change en cours d'engagement, nous redéfinissons la portée par écrit.",
    "sustainable oss strategy for your company": "Une stratégie de logiciel libre tenable pour votre entreprise",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Cadre de test API basé sur le terminal avec des différences de snapshot et une intégration CI/CD.",
    "the setup": "la configuration",
    "view full architecture impact": "Voir l'impact architectural complet",
    "view source": "Voir la source",
    "view work()": "voirRéalisations()",
    "what engineers say": "Ce qu'en disent les ingénieurs",
    "what i do": "ce que je fais",
    "work environment": "Environnement de travail",
  },
  es: {
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Resumen asíncrono de 30 minutos a través de Loom o documento escrito. Leí su stack tecnológico, entendí el espacio de restricciones y señalé cualquier cosa que cambie el alcance.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponible para misiones de ingeniería sénior, consultoría técnica y código abierto. Con base en",
    "browse the work": "Ver los trabajos",
    "built the real-time sync engine from scratch (yjs + crdts).": "Motor de sincronización en tiempo real escrito desde cero (Yjs y CRDT).",
    "cargo build — execution": "cargo build — Ejecución",
    "core contributor to next.js app router and turbopack.": "Contribuyente principal a Next.js App Router y Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detallado, preciso, comunica compensaciones en lugar de opiniones. Entregó un RFC de arquitectura de 25 páginas sobre nuestra capa de datos que enviamos casi palabra por palabra. Raro.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de trazado distribuido que reconstruye gráficos de llamadas a partir de spans OTLP en bruto a través de múltiples servicios.",
    "engagement process": "Proceso de compromiso",
    "featured open source": "Código abierto destacado",
    "find the milliseconds your users feel": "Encontrar los milisegundos que sus usuarios notan",
    "hire me": "contrátame",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Su auditoría de rendimiento encontró tres patrones de consulta sistémicos que habíamos pasado por alto durante dos años. La solución se implementó en un sprint. Vale diez veces la tarifa.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Acepto 1 a 2 compromisos enfocados por trimestre. Si tu cronograma encaja, averigüemos si somos compatibles.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Trabajo en ciclos cortos con resultados visibles. Cada semana termina con un recorrido de Loom sobre lo que se envió, lo que no se envió y por qué.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Capa de caché de construcción incremental para espacios de trabajo Cargo. Reduce los tiempos de CI en un 40-70% a través de artefactos dirigidos por contenido.",
    "know what you're acquiring": "Saber lo que está adquiriendo",
    "led infrastructure reliability for payment processing at scale.": "Lideró la fiabilidad de la infraestructura para el procesamiento de pagos a gran escala.",
    "let's build something great.": "Construyamos algo bueno.",
    "open source advisory": "Asesoramiento en código abierto",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Asesoría de código abierto de alguien que realmente ha enviado y mantenido grandes proyectos de OSS. No solo teoría. Trabajaría con él de nuevo de inmediato.",
    "previous employers and clients": "empleadores y clientes anteriores",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël reescribió nuestro servicio de conciliación de transacciones en cuatro semanas. El P99 pasó de 900 ms a 120 ms. El código que dejó es el más limpio que tenemos, y no es poco decir.",
    "ready to ship something great?": "¿Listo para enviar algo grandioso?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Documento compartido con objetivos, criterios de éxito y cadencia semanal. Sin pivotes sorpresa. Si el problema cambia a mitad del compromiso, redefinimos el alcance por escrito.",
    "sustainable oss strategy for your company": "Una estrategia de código abierto sostenible para su empresa",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Marco de pruebas de API basado en terminal con diferencias de instantáneas e integración CI/CD.",
    "the setup": "la configuración",
    "view full architecture impact": "Ver el impacto arquitectónico completo",
    "view source": "Ver fuente",
    "view work()": "verTrabajos()",
    "what engineers say": "Lo que dicen los ingenieros",
    "what i do": "lo que hago",
    "work environment": "Entorno de trabajo",
  },
  de: {
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "30-minütiger asynchroner Briefing über Loom oder schriftliches Dokument. Ich habe Ihren Tech-Stack gelesen, den Einschränkungsbereich verstanden und alles markiert, was den Umfang ändert.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Verfügbar für Senior-Engineering-Mandate, technische Beratung und Open Source. Ansässig in",
    "browse the work": "Die Arbeiten durchsehen",
    "built the real-time sync engine from scratch (yjs + crdts).": "Echtzeit-Synchronisationsmotor von Grund auf geschrieben (Yjs und CRDTs).",
    "cargo build — execution": "cargo build — Ausführung",
    "core contributor to next.js app router and turbopack.": "Kernbeitrag zu Next.js App Router und Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detailliert, präzise, kommuniziert Kompromisse statt Meinungen. Er lieferte ein 25-seitiges Architektur-RFC zu unserer Datenebene, das wir fast wörtlich versendet haben. Selten.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "Verteilte Tracing-CLI, die Anrufgraphen aus rohen OTLP-Spans über mehrere Dienste hinweg rekonstruiert.",
    "engagement process": "Engagement-Prozess",
    "featured open source": "Ausgewähltes Open Source",
    "find the milliseconds your users feel": "Die Millisekunden finden, die Ihre Nutzer spüren",
    "hire me": "stelle mich ein",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "Sein Performance-Audit fand drei systematische Abfrage-Muster, die wir zwei Jahre lang übersehen hatten. Der Fix wurde in einem Sprint bereitgestellt. Zehnmal so viel wert wie die Gebühr.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Ich nehme 1–2 fokussierte Engagements pro Quartal an. Wenn dein Zeitrahmen passt, lass uns herausfinden, ob wir zusammenpassen.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Ich arbeite in kurzen Zyklen mit sichtbaren Ergebnissen. Jede Woche endet mit einem Loom-Durchgang über das, was versendet wurde, was nicht und warum.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Inkrementelle Build-Cache-Schicht für Cargo-Arbeitsbereiche. Reduziert die CI-Zeiten um 40-70 % durch inhaltsadressierte Artefakte.",
    "know what you're acquiring": "Wissen, was Sie kaufen",
    "led infrastructure reliability for payment processing at scale.": "Leitete die Infrastrukturzuverlässigkeit für die Zahlungsabwicklung in großem Maßstab.",
    "let's build something great.": "Bauen wir etwas Gutes.",
    "open source advisory": "Open-Source-Beratung",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Open-Source-Beratung von jemandem, der tatsächlich große OSS-Projekte versendet und gewartet hat. Nicht nur Theorie. Würde sofort wieder mit ihm arbeiten.",
    "previous employers and clients": "frühere Arbeitgeber und Kunden",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "Raphaël hat unseren Abgleichdienst in vier Wochen neu geschrieben. Das P99 fiel von 900 ms auf 120 ms. Der Code, den er hinterließ, ist der sauberste, den wir haben — und das will etwas heißen.",
    "ready to ship something great?": "Bereit, etwas Großartiges zu versenden?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Geteiltes Dokument mit Zielen, Erfolgskriterien und wöchentlichem Rhythmus. Keine Überraschungspivots. Wenn sich das Problem während des Engagements ändert, definieren wir den Umfang schriftlich neu.",
    "sustainable oss strategy for your company": "Eine tragfähige Open-Source-Strategie für Ihr Unternehmen",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Terminalbasiertes API-Testframework mit Snapshot-Diffs und CI/CD-Integration.",
    "the setup": "die Einrichtung",
    "view full architecture impact": "Vollständige architektonische Auswirkungen anzeigen",
    "view source": "Quelltext anzeigen",
    "view work()": "arbeitenAnsehen()",
    "what engineers say": "Was Entwickler sagen",
    "what i do": "was ich tue",
    "work environment": "Arbeitsumgebung",
  },
  pt: {
    "30-minute async brief via loom or written document. i read your tech stack, understand the constraint space, and flag anything that changes scope.": "Resumo assíncrono de 30 minutos via Loom ou documento escrito. Li a sua pilha tecnológica, entendi o espaço de restrições e sinalizei qualquer coisa que mudasse o escopo.",
    "available for staff/principal engineering contracts, technical advisory, and open source. based in": "Disponível para missões de engenharia sénior, consultoria técnica e código aberto. Sediado em",
    "browse the work": "Ver os trabalhos",
    "built the real-time sync engine from scratch (yjs + crdts).": "Motor de sincronização em tempo real escrito de raiz (Yjs e CRDTs).",
    "cargo build — execution": "cargo build — Execução",
    "core contributor to next.js app router and turbopack.": "Contribuidor principal para Next.js App Router e Turbopack.",
    "detailed, precise, communicates tradeoffs instead of opinions. he delivered a 25-page architecture rfc on our data layer that we shipped almost verbatim. rare.": "Detalhado, preciso, comunica compromissos em vez de opiniões. Ele entregou um RFC de arquitetura de 25 páginas sobre nossa camada de dados que enviamos quase palavra por palavra. Raro.",
    "distributed tracing cli that reconstructs call graphs from raw otlp spans across multiple services.": "CLI de rastreamento distribuído que reconstrói gráficos de chamadas a partir de spans OTLP brutos em vários serviços.",
    "engagement process": "Processo de compromisso",
    "featured open source": "Código aberto em destaque",
    "find the milliseconds your users feel": "Encontrar os milissegundos que os seus utilizadores sentem",
    "hire me": "contrate-me",
    "his performance audit found three systemic query patterns we'd missed for two years. the fix was deployed in one sprint. worth ten times the fee.": "A sua auditoria de desempenho encontrou três padrões de consulta sistémicos que perdemos durante dois anos. A correção foi implementada em um sprint. Vale dez vezes a taxa.",
    "i take on 1–2 focused engagements per quarter. if your timeline fits, let's figure out if we're a match.": "Aceito 1 a 2 compromissos focados por trimestre. Se o seu cronograma se encaixar, vamos descobrir se somos compatíveis.",
    "i work in short cycles with visible output. each week ends with a loom walkthrough of what shipped, what didn't, and why.": "Trabalho em ciclos curtos com resultados visíveis. Cada semana termina com uma apresentação Loom sobre o que foi enviado, o que não foi e por quê.",
    "incremental build cache layer for cargo workspaces. cuts ci times by 40-70% via content-addressed artifacts.": "Camada de cache de construção incremental para espaços de trabalho Cargo. Reduz os tempos de CI em 40-70% através de artefatos endereçados por conteúdo.",
    "know what you're acquiring": "Saber o que está a adquirir",
    "led infrastructure reliability for payment processing at scale.": "Liderou a fiabilidade da infraestrutura para o processamento de pagamentos em grande escala.",
    "let's build something great.": "Vamos construir algo bom.",
    "open source advisory": "Aconselhamento em código aberto",
    "open source advisory from someone who's actually shipped and maintained large oss projects. not just theory. would work with him again immediately.": "Assessoria de código aberto de alguém que realmente enviou e manteve grandes projetos de OSS. Não apenas teoria. Trabalharia com ele novamente imediatamente.",
    "previous employers and clients": "empregadores e clientes anteriores",
    "raphaël rewrote our transaction reconciliation service in four weeks. p99 dropped from 900ms to 120ms. the codebase he left behind is the cleanest we have — and that's saying something.": "O Raphaël reescreveu o nosso serviço de reconciliação de transações em quatro semanas. O P99 passou de 900 ms para 120 ms. O código que deixou é o mais limpo que temos — e não é pouco dizer.",
    "ready to ship something great?": "Pronto para enviar algo incrível?",
    "shared document with goals, success criteria, and weekly cadence. no surprise pivots. if the problem shifts mid-engagement, we re-scope in writing.": "Documento partilhado com objetivos, critérios de sucesso e cadência semanal. Sem pivôs surpresa. Se o problema mudar durante o compromisso, redefinimos o escopo por escrito.",
    "sustainable oss strategy for your company": "Uma estratégia de código aberto sustentável para a sua empresa",
    "terminal-based api testing framework with snapshot diffs and ci/cd integration.": "Estrutura de teste de API baseada em terminal com diferenças de instantâneas e integração CI/CD.",
    "the setup": "a configuração",
    "view full architecture impact": "Ver o impacto arquitetónico completo",
    "view source": "Ver fonte",
    "view work()": "verTrabalhos()",
    "what engineers say": "O que dizem os engenheiros",
    "what i do": "o que eu faço",
    "work environment": "Ambiente de trabalho",
  },
};
