/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "primitive": "Raffinement",
    "refinement.": "primitif.",
    "where wood-fired alchemy meets contemporary culinary precision.": "Là où l'alchimie du feu de bois rencontre la précision de la cuisine contemporaine.",
    "wood species": "Essences de bois",
    "wine labels": "Références de vin",
    "dry-aged wagyu": "Wagyu maturé à sec",
    "appetizer": "Entrée",
    "smoked ember octopus": "Poulpe fumé aux braises",
    "pairing": "Accord",
    "45-day dry-aged a5 wagyu, seared over japanese white oak charcoal and finished with smoked sea salt.": "Wagyu A5 vieilli 45 jours, saisi sur charbon de bois de chêne blanc japonais et fini avec du sel de mer fumé.",
    "a curated flight of rare vintage reds, hand-selected to complement the intensity of wood-fired smoke.": "Un vol sélectionné de rouges vintage rares, soigneusement choisis pour compléter l'intensité de la fumée de bois.",
    "dry aging days": "Jours de vieillissement à sec",
    "explore the menu": "Découvrir la carte",
    "our cattle are raised on high-altitude pastures, following ethical farming lineages that span three generations.": "Notre bétail est élevé dans des pâturages en haute altitude, suivant des lignées agricoles éthiques qui s'étendent sur trois générations.",
    "precision temperature control meets raw elemental fire, guided by our executive chef's 20-year mastery.": "Le contrôle précis de la température rencontre le feu élémentaire brut, guidé par la maîtrise de 20 ans de notre Chef Exécutif.",
    "request private dining": "Demander une salle à manger privée",
    "the ember cellar selection": "La Sélection Ember Cellar",
    "the fire lab": "Le laboratoire du feu",
    "the maison": "La Maison",
    "the primal alchemy of wood, fire, and time. an uncompromising pursuit of culinary intensity.": "L'alchimie primitive du bois, du feu et du temps. Une quête intransigeante de l'intensité culinaire.",
    "view full wine list": "Voir la liste complète des vins",
    "view provenance": "Voir la provenance",
    "we utilize three distinct wood types—hickory, cherry, and oak—to create a complex smoke profile unique to every cut.": "Nous utilisons trois types de bois distincts—Hickory, Cerisier et Chêne—pour créer un profil de fumée complexe unique à chaque morceau.",
    "wood-fired octopus tentacle with chorizo emulsion, squid ink tuile, and pickled mustard seeds.": "Tentacule de poulpe cuit au feu de bois avec émulsion de chorizo, tuile d'encre de seiche et graines de moutarde marinées.",
  },
  es: {
    "primitive": "Refinamiento",
    "refinement.": "primitivo.",
    "where wood-fired alchemy meets contemporary culinary precision.": "Donde la alquimia del fuego de leña se encuentra con la precisión de la cocina contemporánea.",
    "wood species": "Especies de madera",
    "wine labels": "Referencias de vino",
    "dry-aged wagyu": "Wagyu madurado en seco",
    "appetizer": "Entrante",
    "smoked ember octopus": "Pulpo ahumado a las brasas",
    "pairing": "Maridaje",
    "45-day dry-aged a5 wagyu, seared over japanese white oak charcoal and finished with smoked sea salt.": "Wagyu A5 envejecido 45 días, sellado sobre carbón de roble blanco japonés y terminado con sal marina ahumada.",
    "a curated flight of rare vintage reds, hand-selected to complement the intensity of wood-fired smoke.": "Un vuelo curado de raros tintos vintage, seleccionados a mano para complementar la intensidad del humo de leña.",
    "dry aging days": "Días de envejecimiento en seco",
    "explore the menu": "Descubrir la carta",
    "our cattle are raised on high-altitude pastures, following ethical farming lineages that span three generations.": "Nuestro ganado se cría en pastos de gran altitud, siguiendo linajes agrícolas éticos que abarcan tres generaciones.",
    "precision temperature control meets raw elemental fire, guided by our executive chef's 20-year mastery.": "El control preciso de la temperatura se encuentra con el fuego elemental crudo, guiado por la maestría de 20 años de nuestro Chef Ejecutivo.",
    "request private dining": "Solicitar comedor privado",
    "the ember cellar selection": "La Selección Ember Cellar",
    "the fire lab": "El laboratorio del fuego",
    "the maison": "La Maison",
    "the primal alchemy of wood, fire, and time. an uncompromising pursuit of culinary intensity.": "La alquimia primal de la madera, el fuego y el tiempo. Una búsqueda intransigente de la intensidad culinaria.",
    "view full wine list": "Ver lista completa de vinos",
    "view provenance": "Ver procedencia",
    "we utilize three distinct wood types—hickory, cherry, and oak—to create a complex smoke profile unique to every cut.": "Utilizamos tres tipos de madera distintos—Hickory, Cereza y Roble—para crear un perfil de humo complejo único para cada corte.",
    "wood-fired octopus tentacle with chorizo emulsion, squid ink tuile, and pickled mustard seeds.": "Tentáculo de pulpo asado a la leña con emulsión de chorizo, tuile de tinta de calamar y semillas de mostaza en escabeche.",
  },
  de: {
    "primitive": "Ursprüngliche",
    "refinement.": "Verfeinerung.",
    "where wood-fired alchemy meets contemporary culinary precision.": "Wo die Alchemie des Holzfeuers auf zeitgenössische Küchenpräzision trifft.",
    "wood species": "Holzarten",
    "wine labels": "Weinreferenzen",
    "dry-aged wagyu": "Dry-Aged Wagyu",
    "appetizer": "Vorspeise",
    "smoked ember octopus": "Geräucherter Oktopus von der Glut",
    "pairing": "Begleitung",
    "45-day dry-aged a5 wagyu, seared over japanese white oak charcoal and finished with smoked sea salt.": "A5 Wagyu 45 Tage trocken gereift, über japanischem Weißeichen-Holzkohle angebraten und mit geräuchertem Meersalz vollendet.",
    "a curated flight of rare vintage reds, hand-selected to complement the intensity of wood-fired smoke.": "Eine kuratierte Auswahl seltener Jahrgangsrotweine, handverlesen, um die Intensität des Holzfeuersrauchs zu ergänzen.",
    "dry aging days": "Trockene Alterungstage",
    "explore the menu": "Zur Speisekarte",
    "our cattle are raised on high-altitude pastures, following ethical farming lineages that span three generations.": "Unser Vieh wird auf Hochlandweiden gehalten, die ethischen Landwirtschaftslinien folgen, die sich über drei Generationen erstrecken.",
    "precision temperature control meets raw elemental fire, guided by our executive chef's 20-year mastery.": "Präzise Temperaturkontrolle trifft auf rohes, elementares Feuer, geleitet von der 20-jährigen Meisterschaft unseres Executive Chefs.",
    "request private dining": "Private Dining anfragen",
    "the ember cellar selection": "Die Ember Cellar Auswahl",
    "the fire lab": "Das Feuerlabor",
    "the maison": "Das Maison",
    "the primal alchemy of wood, fire, and time. an uncompromising pursuit of culinary intensity.": "Die urtümliche Alchemie von Holz, Feuer und Zeit. Eine kompromisslose Verfolgung kulinarischer Intensität.",
    "view full wine list": "Die vollständige Weinkarte anzeigen",
    "view provenance": "Herkunft anzeigen",
    "we utilize three distinct wood types—hickory, cherry, and oak—to create a complex smoke profile unique to every cut.": "Wir verwenden drei verschiedene Holzarten—Hickory, Kirsche und Eiche—um ein komplexes Rauchprofil zu schaffen, das für jeden Schnitt einzigartig ist.",
    "wood-fired octopus tentacle with chorizo emulsion, squid ink tuile, and pickled mustard seeds.": "Holzkohle-gegrillter Oktopusarm mit Chorizo-Emulsion, Tintenfischtuiles und eingelegten Senfsamen.",
  },
  pt: {
    "primitive": "Refinamento",
    "refinement.": "primitivo.",
    "where wood-fired alchemy meets contemporary culinary precision.": "Onde a alquimia do fogo de lenha encontra a precisão da cozinha contemporânea.",
    "wood species": "Espécies de madeira",
    "wine labels": "Referências de vinho",
    "dry-aged wagyu": "Wagyu maturado a seco",
    "appetizer": "Entrada",
    "smoked ember octopus": "Polvo fumado nas brasas",
    "pairing": "Harmonização",
    "45-day dry-aged a5 wagyu, seared over japanese white oak charcoal and finished with smoked sea salt.": "Wagyu A5 curado a seco durante 45 días, sellado sobre carbón de roble blanco japonés y terminado con sal marina ahumada.",
    "a curated flight of rare vintage reds, hand-selected to complement the intensity of wood-fired smoke.": "Um voo selecionado de tintos vintage raros, escolhidos à mão para complementar a intensidade da fumaça de lenha.",
    "dry aging days": "Dias de cura a seco",
    "explore the menu": "Descobrir a carta",
    "our cattle are raised on high-altitude pastures, following ethical farming lineages that span three generations.": "O nosso gado é criado em pastagens de alta altitude, seguindo linhagens agrícolas éticas que se estendem por três gerações.",
    "precision temperature control meets raw elemental fire, guided by our executive chef's 20-year mastery.": "O controlo preciso da temperatura encontra o fogo elemental bruto, guiado pela maestria de 20 anos do nosso Chef Executivo.",
    "request private dining": "Solicitar sala de jantar privada",
    "the ember cellar selection": "A Seleção Ember Cellar",
    "the fire lab": "O laboratório do fogo",
    "the maison": "A Maison",
    "the primal alchemy of wood, fire, and time. an uncompromising pursuit of culinary intensity.": "A alquimia primal da madeira, do fogo e do tempo. Uma busca intransigente pela intensidade culinária.",
    "view full wine list": "Ver lista completa de vinhos",
    "view provenance": "Ver proveniência",
    "we utilize three distinct wood types—hickory, cherry, and oak—to create a complex smoke profile unique to every cut.": "Utilizamos três tipos distintos de madeira—Hickory, Cerejeira e Carvalho—para criar um perfil de fumaça complexo e único para cada corte.",
    "wood-fired octopus tentacle with chorizo emulsion, squid ink tuile, and pickled mustard seeds.": "Tentáculo de polvo assado em lenha com emulsão de chouriço, tuile de tinta de lula e sementes de mostarda em conserva.",
  },
};
