/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Un document sur ma façon de travailler — les outils, la philosophie, l'installation. Parce que l'environnement façonne le résultat.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Une astuce brillante que trois ingénieurs ne sauront plus lire au trimestre suivant est un passif, pas un actif. J'optimise pour le prochain ingénieur sur le code.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "L'intuition sur la performance se trompe presque toujours. Profileurs, traces distribuées et télémétrie de production doivent guider les décisions d'optimisation.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Une PR de 50 lignes livrée aujourd'hui vaut mieux qu'une PR de 500 lignes qui traîne deux semaines en relecture. Je garde des diffs lisibles et des contrôles automatisés pour que ça avance.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit est volontairement petit. Quatre projets par trimestre — jamais plus. Chaque client a tous les seniors autour de la table. C'est le modèle.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Stratège de marque, venue de la sémiotique et de l'économie comportementale. Passée par Wolff Olins à Londres. Convaincue que toute grande identité part d'un point de vue tranché.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obsédée de typographie, esprit systémique, ancienne de Pentagram. Sana transforme la clarté stratégique en précision visuelle — rien d'arbitraire, tout se déploie.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Fait passer la marque du statique au vivant — identité en mouvement, web interactif, points de contact numériques. A travaillé avec Nike Digital et Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Des composants 3D haute performance conçus pour le web moderne. Nous marions le geste créatif à une optimisation rigoureuse au niveau du GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Un rendu 3D temps réel haute fidélité, directement dans le navigateur : maillages légers, textures PBR optimisées, éclairage physiquement exact.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Des campagnes de réalité augmentée sans application : d'un simple lien, le client pose le produit chez lui, avec un réalisme photographique.",
    "camera filters and custom overlays": "Filtres caméra et surimpressions sur mesure",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism se branche nativement à votre entrepôt de données, votre CRM, votre prestataire de paiement et vos canaux publicitaires. Aucune intégration sur mesure requise.",
    "sync raw events natively from databases and query engines.": "Synchronisez les événements bruts depuis vos bases et moteurs de requête.",
    "align transaction records with user behavior metrics.": "Rapprochez les transactions des mesures de comportement.",
    "enrich user profiles and trigger messaging based on user actions.": "Enrichissez les profils et déclenchez des messages selon les actions.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Une conception de bout en bout, de l'esquisse au coulage du béton. L'honnêteté structurelle est notre directive première, sans compromis visuel.",
    "scope of work:": "Périmètre :",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Des stratégies d'aménagement à grande échelle pour institutions publiques et campus. Nos plans directeurs ancrent les ensembles bâtis dans une densité logique.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Nous laissons l'acier, le béton et les gaines apparents : les systèmes intérieurs font partie de l'esthétique au lieu d'être cachés derrière des finitions.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sept jours dans un désert ancien. Pratique somatique à l'aube, marches silencieuses à midi, cérémonies du feu le soir. Sans agenda. Sans performance.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Des retraites immersives dans les paysages les plus transformateurs du monde. Neuf participants au plus. Le calme comme pratique.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Je passe des semaines sur chaque lieu avant de faire une image. Les montagnes se moquent de mon calendrier. La brume vient quand elle veut. Cette patience est toute la méthode.",
    "each print is made in partnership with atelier gaspard in": "Chaque tirage est réalisé avec l'Atelier Gaspard à",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Pour les licences éditoriales, les usages commerciaux ou les commandes privées, écrivez-moi directement. Pour les tirages, passez par la boutique.",
    "bring the wild": "Ramenez le sauvage",
    "that's the point.": "C'est justement le but.",
    "> about": "> à propos",
    "> work": "> travail",
    "cve watch: true": "surveillance des CVE : vrai",
    "exploit design": "conception d'exploit",
    "on-chain identity vault": "coffre-fort d'identité en chaîne",
    "red team ops dashboard": "tableau de bord des opérations de l'équipe rouge",
    "zero day dev": "développement zero day",
    "zero day scanner.py": "scanner zero day.py",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Un documento sobre mi forma de trabajar: las herramientas, la filosofía, la instalación. Porque el entorno moldea el resultado.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Un truco brillante que tres ingenieros no sabrán leer el próximo trimestre es un pasivo, no un activo. Optimizo para el siguiente ingeniero en el código.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "La intuición sobre el rendimiento casi siempre se equivoca. Perfiles, trazas distribuidas y telemetría de producción deben guiar las decisiones de optimización.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Una PR de 50 líneas entregada hoy vale más que una de 500 que pasa dos semanas en revisión. Mantengo diffs legibles y controles automatizados para que todo avance.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit es deliberadamente pequeño. Cuatro proyectos por trimestre, nunca más. Cada cliente tiene a todos los seniors en la sala. Ese es el modelo.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Estratega de marca, con formación en semiótica y economía conductual. Antes en Wolff Olins Londres. Convencida de que toda gran identidad parte de un punto de vista afilado.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obsesa de la tipografía, mente sistémica, ex-Pentagram. Sana convierte la claridad estratégica en precisión visual: nada es arbitrario, todo escala.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Lleva la marca de lo estático a lo vivo: identidad en movimiento, web interactiva, puntos de contacto digitales. Trabajó con Nike Digital y Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Componentes 3D de alto rendimiento para la web moderna. Unimos el gesto creativo a una optimización rigurosa a nivel de GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Renderizado 3D en tiempo real de alta fidelidad, directamente en el navegador: mallas ligeras, texturas PBR optimizadas, iluminación físicamente exacta.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Campañas de realidad aumentada sin aplicación: con un simple enlace, el cliente coloca el producto en su espacio con realismo fotográfico.",
    "camera filters and custom overlays": "Filtros de cámara y superposiciones a medida",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism se conecta de forma nativa a su almacén de datos, su CRM, su procesador de pagos y sus canales publicitarios. Sin integraciones a medida.",
    "sync raw events natively from databases and query engines.": "Sincronice eventos en bruto desde sus bases y motores de consulta.",
    "align transaction records with user behavior metrics.": "Alinee las transacciones con las métricas de comportamiento.",
    "enrich user profiles and trigger messaging based on user actions.": "Enriquezca los perfiles y active mensajes según las acciones.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Diseño de principio a fin, del boceto al vertido del hormigón. La honestidad estructural es nuestra directiva primera, sin compromiso visual.",
    "scope of work:": "Alcance:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Estrategias de ordenación a gran escala para instituciones públicas y campus. Nuestros planes maestros anclan los conjuntos con una densidad lógica.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Dejamos el acero, el hormigón y los conductos a la vista: los sistemas interiores forman parte de la estética en lugar de esconderse tras acabados.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Siete días en un desierto antiguo. Práctica somática al alba, caminatas silenciosas al mediodía, ceremonias de fuego al anochecer. Sin agenda. Sin rendimiento.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Retiros inmersivos en los paisajes más transformadores del mundo. Nueve participantes como máximo. La calma como práctica.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Paso semanas en cada lugar antes de hacer una imagen. A las montañas no les importa mi calendario. La niebla llega cuando quiere. Esa paciencia es todo el método.",
    "each print is made in partnership with atelier gaspard in": "Cada copia se realiza con el Atelier Gaspard en",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Para licencias editoriales, usos comerciales o encargos privados, escríbame directamente. Para las copias, pase por la tienda.",
    "bring the wild": "Traiga lo salvaje",
    "that's the point.": "Ese es justamente el punto.",
    "> about": "> acerca de",
    "> work": "> trabajo",
    "cve watch: true": "vigilancia de CVE: verdadero",
    "exploit design": "diseño de exploit",
    "on-chain identity vault": "bóveda de identidad en cadena",
    "red team ops dashboard": "tablero de operaciones del equipo rojo",
    "zero day dev": "desarrollo de zero day",
    "zero day scanner.py": "escáner de zero day.py",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Ein Dokument über meine Arbeitsweise — Werkzeuge, Philosophie, Arbeitsplatz. Denn die Umgebung prägt das Ergebnis.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Ein brillanter Trick, den drei Ingenieure im nächsten Quartal nicht mehr lesen können, ist eine Last, kein Gewinn. Ich optimiere für den nächsten Menschen im Code.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "Intuition über Performance liegt meist daneben. Profiler, verteilte Traces und echte Produktionstelemetrie sollten Optimierungsentscheidungen leiten.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Ein 50-Zeilen-PR, der heute live geht, schlägt einen 500-Zeilen-PR, der zwei Wochen im Review hängt. Ich halte Diffs lesbar und Gates automatisiert, damit es vorangeht.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit ist bewusst klein. Vier Projekte pro Quartal — nie mehr. Jeder Kunde bekommt alle Senioren an den Tisch. Das ist das Modell.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Markenstrategin mit Hintergrund in Semiotik und Verhaltensökonomie. Zuvor bei Wolff Olins London. Überzeugt, dass jede große Identität mit einer klaren Haltung beginnt.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Typografie-Besessene, Systemdenkerin, früher bei Pentagram. Sana übersetzt strategische Klarheit in visuelle Präzision — nichts ist beliebig, alles skaliert.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Überführt statische Marken in lebende Systeme — Motion Identity, interaktives Web, digitale Touchpoints. Arbeitete mit Nike Digital und Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Hochperformante 3D-Komponenten für das moderne Web. Wir verbinden kreatives Können mit rigoroser Optimierung auf GPU-Ebene.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Hochauflösendes Echtzeit-3D direkt im Browser: leichte Meshes, optimierte PBR-Texturen, physikalisch korrektes Licht.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "AR-Kampagnen ohne App: Über einen Link platzieren Kunden Produkte fotorealistisch im eigenen Raum.",
    "camera filters and custom overlays": "Kamerafilter und individuelle Overlays",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism verbindet sich nativ mit Ihrem Data Warehouse, CRM, Zahlungsdienstleister und Ihren Werbekanälen. Keine individuellen API-Integrationen nötig.",
    "sync raw events natively from databases and query engines.": "Rohereignisse nativ aus Datenbanken und Query-Engines synchronisieren.",
    "align transaction records with user behavior metrics.": "Transaktionen mit Verhaltensmetriken abgleichen.",
    "enrich user profiles and trigger messaging based on user actions.": "Profile anreichern und Nachrichten aktionsbasiert auslösen.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Entwurf von A bis Z, von der Skizze bis zum Betonguss. Strukturelle Ehrlichkeit ist unsere oberste Direktive, ohne visuelle Kompromisse.",
    "scope of work:": "Leistungsumfang:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Großmaßstäbliche Planungsstrategien für öffentliche Einrichtungen und Campusse. Unsere Masterpläne verankern Baugruppen in logischer Dichte.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Wir lassen Stahl, Beton und Leitungen sichtbar: Die Haustechnik ist Teil der Ästhetik, statt hinter Verkleidungen zu verschwinden.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sieben Tage in einer uralten Wüstenlandschaft. Somatische Praxis im Morgengrauen, stille Mittagswanderungen, Feuerzeremonien am Abend. Ohne Agenda. Ohne Leistung.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Immersive Retreats in den verwandelndsten Landschaften der Welt. Höchstens neun Teilnehmende. Stille als Praxis.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Ich verbringe Wochen an jedem Ort, bevor ein Bild entsteht. Den Bergen ist mein Zeitplan gleich. Der Nebel kommt, wann er will. Diese Geduld ist die ganze Methode.",
    "each print is made in partnership with atelier gaspard in": "Jeder Abzug entsteht mit dem Atelier Gaspard in",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Für redaktionelle Lizenzen, kommerzielle Nutzung oder private Aufträge schreiben Sie mir direkt. Für Drucke besuchen Sie den Shop.",
    "bring the wild": "Holen Sie die Wildnis",
    "that's the point.": "Genau darum geht es.",
    "> about": "> über",
    "> work": "> Arbeit",
    "cve watch: true": "CVE-Überwachung: wahr",
    "exploit design": "Exploit-Design",
    "on-chain identity vault": "Identitätsvault on-chain",
    "red team ops dashboard": "Dashboard für die Operationen des roten Teams",
    "zero day dev": "Zero-Day-Entwicklung",
    "zero day scanner.py": "Zero-Day-Scanner.py",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Um documento sobre a minha forma de trabalhar — as ferramentas, a filosofia, a instalação. Porque o ambiente molda o resultado.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Um truque brilhante que três engenheiros já não saberão ler no próximo trimestre é um passivo, não um ativo. Otimizo para o próximo engenheiro no código.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "A intuição sobre desempenho quase sempre se engana. Perfis, rastreios distribuídos e telemetria de produção devem guiar as decisões de otimização.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Um PR de 50 linhas entregue hoje vale mais do que um de 500 que fica duas semanas em revisão. Mantenho diffs legíveis e controlos automatizados para que as coisas avancem.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "A Orbit é deliberadamente pequena. Quatro projetos por trimestre — nunca mais. Cada cliente tem todos os seniores à mesa. É o modelo.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Estratega de marca, vinda da semiótica e da economia comportamental. Antes na Wolff Olins em Londres. Convicta de que toda a grande identidade parte de um ponto de vista afiado.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obcecada por tipografia, mente sistémica, ex-Pentagram. A Sana converte clareza estratégica em precisão visual — nada é arbitrário, tudo escala.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Leva a marca do estático ao vivo — identidade em movimento, web interativa, pontos de contacto digitais. Trabalhou com a Nike Digital e o Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Componentes 3D de alto desempenho para a web moderna. Unimos o gesto criativo a uma otimização rigorosa ao nível do GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Renderização 3D em tempo real de alta fidelidade, diretamente no navegador: malhas leves, texturas PBR otimizadas, iluminação fisicamente exata.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Campanhas de realidade aumentada sem aplicação: com um simples link, o cliente coloca o produto no seu espaço com realismo fotográfico.",
    "camera filters and custom overlays": "Filtros de câmara e sobreposições à medida",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "O Prism liga-se nativamente ao seu armazém de dados, CRM, processador de pagamentos e canais publicitários. Sem integrações à medida.",
    "sync raw events natively from databases and query engines.": "Sincronize eventos em bruto das suas bases e motores de consulta.",
    "align transaction records with user behavior metrics.": "Alinhe as transações com as métricas de comportamento.",
    "enrich user profiles and trigger messaging based on user actions.": "Enriqueça os perfis e dispare mensagens conforme as ações.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Conceção de ponta a ponta, do esboço à betonagem. A honestidade estrutural é a nossa diretiva primeira, sem compromissos visuais.",
    "scope of work:": "Âmbito:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Estratégias de ordenamento em grande escala para instituições públicas e campi. Os nossos planos diretores ancoram os conjuntos numa densidade lógica.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Deixamos o aço, o betão e as condutas à vista: os sistemas interiores fazem parte da estética em vez de se esconderem atrás de acabamentos.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sete dias num deserto antigo. Prática somática de madrugada, caminhadas silenciosas ao meio-dia, cerimónias do fogo à noite. Sem agenda. Sem desempenho.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Retiros imersivos nas paisagens mais transformadoras do mundo. Nove participantes no máximo. A calma como prática.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Passo semanas em cada lugar antes de fazer uma imagem. As montanhas não querem saber do meu calendário. O nevoeiro chega quando quer. Essa paciência é todo o método.",
    "each print is made in partnership with atelier gaspard in": "Cada impressão é feita com o Atelier Gaspard em",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Para licenças editoriais, usos comerciais ou encomendas privadas, escreva-me diretamente. Para impressões, passe pela loja.",
    "bring the wild": "Traga o selvagem",
    "that's the point.": "É exatamente esse o ponto.",
    "> about": "> sobre",
    "> work": "> trabalho",
    "cve watch: true": "vigilância de CVE: verdadeiro",
    "exploit design": "design de exploit",
    "on-chain identity vault": "cofre de identidade em cadeia",
    "red team ops dashboard": "painel de operações da equipe vermelha",
    "zero day dev": "desenvolvimento zero day",
    "zero day scanner.py": "scanner zero day.py",
  },
};
