/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Un sanctuaire soigneusement sélectionné d'eaux thermales, de botanicals anciens et de silence. Soixante kilomètres de la ville. Un monde à part.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "La disponibilité est limitée à trente invités par jour. Nous recommandons de réserver au moins deux semaines à l'avance pour les visites du week-end.",
    "begin your retreat": "Commencer votre retraite",
    "choose your depth": "Choisissez votre profondeur",
    "compare all packages": "Comparer les formules",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Chaque traitement est conçu comme une cérémonie complète — pas simplement un service. Nous nous approvisionnons en botanicals auprès de fermes biologiques certifiées dans un rayon de 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Chaque plante de nos soins est certifiée biologique et récoltée à moins de deux cents kilomètres. Notre eau vient d'une source granitique à mille quatre cents mètres. Sur la matière, nous ne cédons rien.",
    "explore packages": "Explorer les forfaits",
    "for body and mind": "pour le corps et l'esprit",
    "guest stories": "Histoires de clients",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Les hôtes sont accueillis autour d'une tisane et invités à poser une intention pour leur séjour.",
    "hands you can trust": "Des mains de confiance",
    "himalayan sound journey": "Voyage sonore himalayen",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "J'ai visité six spas à travers l'Europe. Serene Retreat est catégoriquement différent. Le silence à lui seul vaut le voyage.",
    "included in all packages": "Compris dans toutes les formules",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "Le rituel de pierres d'Ingrid a traité des années de tension chronique en une seule séance. J'ai pleuré. Je le recommande sans réserve.",
    "meet all practitioners": "Voir tous les praticiens",
    "of immersion": "d'immersion",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "Notre parcours en six étapes suit le vieux principe du contraste — l'alternance voulue du chaud et du froid, qui met en marche les mécanismes de réparation les plus profonds.",
    "our treatments": "Nos soins",
    "private consultation with lead therapist": "Entretien privé avec la thérapeute principale",
    "read our philosophy →": "Lire notre philosophie →",
    "request reservation": "Demander une réservation",
    "reserve your stay": "Réserver votre séjour",
    "slow by design": "Lent par conception",
    "the art of": "L'art de",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "Le forfait Équinoxe a changé quelque chose de fondamental en moi. Je suis parti plus léger d'une manière que je ne peux pas expliquer aux personnes qui ne l'ont pas vécu.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "La chambre de flottaison était terrifiante pendant les cinq premières minutes et transcendante pendant les trente-cinq suivantes.",
    "the thermal circuit": "Le parcours thermal",
    "view all experiences →": "Voir toutes les expériences →",
    "view full circuit details": "Voir les détails du circuit complet",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Nous sommes venus en couple pour le forfait Équinoxe. C'est maintenant un rituel semestriel que nous protégeons comme rien d'autre.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Nous limitons les arrivées à trente personnes par jour. Ce n'est pas un métier de volume, mais de précision. Votre silence dépend de cette limite.",
    "what our guests say": "Ce que disent nos hôtes",
  },
  es: {
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Un santuario curado de aguas termales, botánicos antiguos y silencio. A sesenta kilómetros de la ciudad. Un mundo aparte.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "La disponibilidad está limitada a treinta huéspedes por día. Recomendamos reservar con al menos dos semanas de antelación para las visitas de fin de semana.",
    "begin your retreat": "Empezar su retiro",
    "choose your depth": "Elija su profundidad",
    "compare all packages": "Comparar las fórmulas",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Cada tratamiento está diseñado como una ceremonia completa — no simplemente un servicio. Obtenemos botánicos de granjas orgánicas certificadas a menos de 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Cada planta de nuestros tratamientos está certificada ecológica y recogida a menos de doscientos kilómetros. Nuestra agua viene de un manantial granítico a mil cuatrocientos metros. En la materia no cedemos.",
    "explore packages": "Explorar Paquetes",
    "for body and mind": "para el cuerpo y la mente",
    "guest stories": "Historias de Huéspedes",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Los huéspedes son recibidos con una infusión y se les invita a formular una intención para su estancia.",
    "hands you can trust": "Manos de confianza",
    "himalayan sound journey": "Viaje sonoro del Himalaya",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "He visitado seis spas en toda Europa. Serene Retreat es categóricamente diferente. El silencio por sí solo vale el viaje.",
    "included in all packages": "Incluido en todas las fórmulas",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "El ritual de piedras de Ingrid abordó años de tensión crónica en una sola sesión. Lloré. Lo recomiendo sin reservas.",
    "meet all practitioners": "Ver a todos los terapeutas",
    "of immersion": "de inmersión",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "Nuestro recorrido en seis etapas sigue el viejo principio del contraste: la alternancia deliberada de calor y frío, que pone en marcha los mecanismos de reparación más profundos.",
    "our treatments": "Nuestros tratamientos",
    "private consultation with lead therapist": "Consulta privada con la terapeuta principal",
    "read our philosophy →": "Leer nuestra filosofía →",
    "request reservation": "Solicitar Reserva",
    "reserve your stay": "Reservar su estancia",
    "slow by design": "Lento por diseño",
    "the art of": "El arte de",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "El paquete Equinox cambió algo fundamental en mí. Salí más ligero de una manera que no puedo explicar a las personas que no lo han experimentado.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "La cámara de flotación fue aterradora durante los primeros cinco minutos y trascendental durante los siguientes treinta y cinco.",
    "the thermal circuit": "El circuito termal",
    "view all experiences →": "Ver todas las experiencias →",
    "view full circuit details": "Ver Detalles del Circuito Completo",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Vinimos como pareja para el paquete Equinox. Ahora es un ritual semestral que protegemos como nada más.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Limitamos las llegadas a treinta personas al día. No es un negocio de volumen, sino de precisión. Su silencio depende de ese límite.",
    "what our guests say": "Lo que dicen nuestros huéspedes",
  },
  de: {
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Ein kuratiertes Heiligtum aus Thermalwasser, alten Botanicals und Stille. Sechzig Kilometer von der Stadt entfernt. Eine Welt für sich.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "Die Verfügbarkeit ist auf dreißig Gäste pro Tag begrenzt. Wir empfehlen, mindestens zwei Wochen im Voraus für Wochenendbesuche zu buchen.",
    "begin your retreat": "Ihren Rückzug beginnen",
    "choose your depth": "Wählen Sie Ihre Tiefe",
    "compare all packages": "Pakete vergleichen",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Jede Behandlung ist als vollständige Zeremonie konzipiert — nicht nur als Dienstleistung. Wir beziehen Botanicals von zertifizierten Bio-Bauernhöfen innerhalb von 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Jede Pflanze in unseren Behandlungen ist biozertifiziert und stammt aus höchstens zweihundert Kilometern Umkreis. Unser Wasser kommt aus einer Granitquelle auf vierzehnhundert Metern. Beim Material machen wir keine Abstriche.",
    "explore packages": "Pakete erkunden",
    "for body and mind": "für Körper und Geist",
    "guest stories": "Gästegeschichten",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Die Gäste werden mit einer Kräuterteezeremonie empfangen und eingeladen, eine Absicht für ihren Aufenthalt zu setzen.",
    "hands you can trust": "Hände, denen Sie vertrauen",
    "himalayan sound journey": "Himalayan Sound Journey",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "Ich habe sechs Spas in ganz Europa besucht. Serene Retreat ist kategorisch anders. Die Stille allein ist die Reise wert.",
    "included in all packages": "In allen Paketen enthalten",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "Ingrids Steinritual hat jahrelange chronische Spannungen in einer einzigen Sitzung angesprochen. Ich weinte. Ich empfehle es ohne Vorbehalte.",
    "meet all practitioners": "Alle Therapeuten ansehen",
    "of immersion": "der Immersion",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "Unser sechsstufiger Parcours folgt dem alten Prinzip des Wechselreizes — dem bewussten Wechsel von Hitze und Kälte, der die tiefsten Selbstheilungskräfte weckt.",
    "our treatments": "Unsere Behandlungen",
    "private consultation with lead therapist": "Privatgespräch mit der leitenden Therapeutin",
    "read our philosophy →": "Unsere Philosophie lesen →",
    "request reservation": "Reservierung anfragen",
    "reserve your stay": "Ihren Aufenthalt buchen",
    "slow by design": "Langsam durch Design",
    "the art of": "Die Kunst des",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "Das Equinox-Paket hat etwas Grundlegendes in mir verändert. Ich verließ es leichter auf eine Weise, die ich Menschen, die es nicht erlebt haben, nicht erklären kann.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "Die Floatationskammer war in den ersten fünf Minuten beängstigend und in den nächsten fünfunddreißig transzendent.",
    "the thermal circuit": "Der Thermalparcours",
    "view all experiences →": "Alle Erlebnisse ansehen →",
    "view full circuit details": "Vollständige Circuitdetails anzeigen",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Wir kamen als Paar für das Equinox-Paket. Es ist jetzt ein halbjährliches Ritual, das wir wie nichts anderes schützen.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Wir begrenzen die Ankünfte auf dreißig Gäste am Tag. Das ist kein Mengengeschäft, sondern ein Präzisionsgeschäft. Ihre Stille hängt an dieser Grenze.",
    "what our guests say": "Was unsere Gäste sagen",
  },
  pt: {
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Um santuário selecionado de águas termais, botânicos antigos e silêncio. A sessenta quilómetros da cidade. Um mundo à parte.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "A disponibilidade é limitada a trinta hóspedes por dia. Recomendamos reservar com pelo menos duas semanas de antecedência para visitas de fim de semana.",
    "begin your retreat": "Começar o seu retiro",
    "choose your depth": "Escolha a sua profundidade",
    "compare all packages": "Comparar as fórmulas",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Cada tratamento é concebido como uma cerimônia completa — não apenas um serviço. Obtemos botânicos de quintas orgânicas certificadas a menos de 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Cada planta dos nossos tratamentos é certificada biológica e colhida a menos de duzentos quilómetros. A nossa água vem de uma nascente granítica a mil e quatrocentos metros. Na matéria não cedemos.",
    "explore packages": "Explorar Pacotes",
    "for body and mind": "para o corpo e a mente",
    "guest stories": "Histórias de Clientes",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Os hóspedes são recebidos com uma tisana e convidados a formular uma intenção para a sua estadia.",
    "hands you can trust": "Mãos de confiança",
    "himalayan sound journey": "Jornada Sonora Himaláyica",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "Visitei seis spas por toda a Europa. O Serene Retreat é categoricamente diferente. O silêncio por si só vale a viagem.",
    "included in all packages": "Incluído em todas as fórmulas",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "O ritual de pedras da Ingrid abordou anos de tensão crónica em uma única sessão. Eu chorei. Recomendo-o sem reservas.",
    "meet all practitioners": "Ver todos os terapeutas",
    "of immersion": "de imersão",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "O nosso percurso em seis etapas segue o velho princípio do contraste — a alternância deliberada de calor e frio, que põe em marcha os mecanismos de reparação mais profundos.",
    "our treatments": "Os nossos tratamentos",
    "private consultation with lead therapist": "Consulta privada com a terapeuta principal",
    "read our philosophy →": "Ler a nossa filosofia →",
    "request reservation": "Solicitar Reserva",
    "reserve your stay": "Reservar a sua estadia",
    "slow by design": "Lento por design",
    "the art of": "A arte de",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "O pacote Equinox mudou algo fundamental em mim. Saí mais leve de uma maneira que não consigo explicar às pessoas que não o vivenciaram.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "A câmara de flutuação foi aterradora nos primeiros cinco minutos e transcendente nos trinta e cinco seguintes.",
    "the thermal circuit": "O circuito termal",
    "view all experiences →": "Ver todas as experiências →",
    "view full circuit details": "Ver Detalhes do Circuito Completo",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Viemos como casal para o pacote Equinox. Agora é um ritual semestral que protegemos como nada mais.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Limitamos as chegadas a trinta pessoas por dia. Não é um negócio de volume, mas de precisão. O seu silêncio depende desse limite.",
    "what our guests say": "O que dizem os nossos hóspedes",
  },
};
