/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "guidelines for the circuit": "Les règles du parcours",
    "hydrate between each step with our botanical infusions.": "Hydratez-vous entre chaque étape avec nos infusions de plantes.",
    "respect the silence of the chambers for all guests.": "Respectez le silence des salles, pour tous les hôtes.",
    "robes, slippers, and towels are provided in your locker.": "Peignoir, chaussons et serviettes vous attendent au vestiaire.",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest repair mechanisms.": "Notre parcours en six étapes suit le vieux principe du contraste : l'alternance voulue du chaud et du froid, qui met en marche les mécanismes de réparation les plus profonds.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining this limit.": "Nous limitons les arrivées à trente personnes par jour. Ce n'est pas un métier de volume, mais de précision. Votre silence dépend de cette limite.",
    "our therapists complete 800 hours of training before their first independent session. then they continue — weekly workshops, eastern medicine study, anatomy refreshers.": "Nos praticiens suivent 800 heures de formation avant leur première séance en autonomie. Puis ils continuent : ateliers hebdomadaires, médecines orientales, révisions d'anatomie.",
    "we change our treatment oils, botanical teas, and integration snacks according to the solar seasons. aligning physical recovery with natural rhythms.": "Nous changeons huiles de soin, tisanes et collations au fil des saisons solaires : la récupération physique s'accorde aux rythmes naturels.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m in the chartreuse massif.": "Chaque plante de nos soins est certifiée biologique et récoltée à moins de deux cents kilomètres. Notre eau vient d'une source granitique à 1 400 mètres, dans le massif de la Chartreuse.",
    "experiences": "Les soins",
    "packages": "Les formules",
    "philosophy": "Philosophie",
    "where stillness": "Là où le calme",
    "becomes medicine": "devient un soin",
    "alpine mineral waters": "Eaux minérales alpines",
    "certified organic botanicals": "Plantes certifiées biologiques",
    "biodynamic treatments": "Soins biodynamiques",
    "carbon neutral retreat": "Retraite neutre en carbone",
    "wild-harvested herbs": "Herbes cueillies à l'état sauvage",
    "ancient thermal traditions": "Traditions thermales anciennes",
    "zero fragrance synthetics": "Aucun parfum de synthèse",
    "forest-sourced cedar": "Cèdre issu de nos forêts",
    "alpine stone ritual": "Rituel aux pierres alpines",
    "forest immersion bath": "Bain d'immersion en forêt",
    "eastern": "Orient",
    "jade meridian massage": "Massage des méridiens au jade",
    "available daily, 7am – 9pm": "Ouvert tous les jours, 7 h – 21 h",
    "step": "Étape",
    "arrival & intention": "Accueil et intention",
    "cold plunge activation": "Bain froid d'activation",
    "infrared sauna": "Sauna infrarouge",
    "retreat packages": "Nos formules",
    "half day": "Demi-journée",
    "full day": "Journée entière",
    "2-night retreat": "Séjour de deux nuits",
    "full thermal circuit access (3 hours)": "Accès au parcours thermal complet (3 heures)",
    "one 60-minute signature treatment": "Un soin signature de 60 minutes",
    "botanical tea ceremony": "Cérémonie de tisanes",
    "use of robes & slippers": "Peignoir et chaussons fournis",
    "locker & amenity access": "Vestiaire et produits d'accueil",
    "two signature treatments (180 min total)": "Deux soins signature (180 minutes en tout)",
    "forest immersion lunch (plant-based)": "Déjeuner en forêt, entièrement végétal",
    "morning pranayama session": "Séance de pranayama le matin",
    "private meditation garden access": "Accès au jardin de méditation privé",
    "departure gift: botanical oil blend": "Cadeau de départ : huile de plantes",
    "two nights in a forest suite": "Deux nuits en suite Forêt",
    "unlimited thermal circuit": "Parcours thermal sans limite",
    "four curated treatments": "Quatre soins choisis pour vous",
    "daily guided forest bathing": "Bain de forêt guidé chaque jour",
    "doing nothing": "ne rien faire",
    "honest ingredients": "Des matières honnêtes",
    "lead holistic therapist": "Thérapeute holistique principale",
    "thermal therapist": "Thérapeute thermal",
    "sound & meditation guide": "Guide de méditation et de soin par le son",
    "somatic bodywork": "Travail corporel somatique",
    "botanical medicine": "Médecine des plantes",
    "hydrotherapy": "Hydrothérapie",
    "nordic bathing": "Bains nordiques",
    "sound healing": "Soin par le son",
    "tibetan bowls": "Bols tibétains",
    "meditation": "Méditation",
    "geneva": "Genève",
    "london": "Londres",
    "volcanic basalt stones, heated to 56°c, melt deep tension held in muscle and fascia. an ancient practice, refined.": "Des pierres de basalte volcanique, chauffées à 56 °C, font fondre les tensions profondes du muscle et du fascia. Une pratique ancienne, affinée.",
    "hinoki cypress and nordic moss botanicals transform warm water into a meditative forest clearing.": "Cyprès hinoki et mousse nordique transforment l'eau chaude en clairière méditative.",
    "a 3-minute immersion in 8°c mineral water awakens the circulatory system and activates cold-shock protein pathways.": "Trois minutes dans une eau minérale à 8 °C : la circulation se réveille et les protéines du choc thermique s'activent.",
    "far-infrared panels penetrate 4cm into tissue — twice the depth of conventional heat — releasing stored toxins at cellular level.": "Les panneaux à infrarouge lointain pénètrent de quatre centimètres — deux fois plus qu'une chaleur classique — et libèrent les toxines au niveau cellulaire.",
    "personalized herbal protocol to take home": "Protocole de plantes personnalisé, à emporter",
    "trained in norway, bali, and kerala. fifteen years of practice in somatic bodywork and botanical medicine.": "Formée en Norvège, à Bali et au Kerala. Quinze ans de pratique en travail corporel somatique et en médecine des plantes.",
    "former competitive swimmer turned hydrotherapy specialist. certified in watsu, aquatic craniosacral, and nordic bathing.": "Ancienne nageuse de compétition devenue spécialiste d'hydrothérapie. Certifiée en watsu, craniosacral aquatique et bains nordiques.",
    "studied under tibetan buddhist teachers for six years. integrates sound healing with somatic presence practices.": "Six années d'étude auprès de maîtres bouddhistes tibétains. Associe le soin par le son à des pratiques de présence somatique.",
    "serene retreat home": "Accueil",
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Un sanctuaire soigneusement sélectionné d'eaux thermales, de plantes anciennes et de silence. Soixante kilomètres de la ville. Un monde à part.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "La disponibilité est limitée à trente invités par jour. Nous recommandons de réserver au moins deux semaines à l'avance pour les visites du week-end.",
    "begin your retreat": "Commencer votre retraite",
    "choose your depth": "Choisissez votre profondeur",
    "compare all packages": "Comparer les formules",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Chaque traitement est conçu comme une cérémonie complète — pas simplement un service. Nous nous approvisionnons en plantes auprès de fermes biologiques certifiées dans un rayon de 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Chaque plante de nos soins est certifiée biologique et récoltée à moins de deux cents kilomètres. Notre eau vient d'une source granitique à mille quatre cents mètres. Sur la matière, nous ne cédons rien.",
    "explore packages": "Explorer les forfaits",
    "for body and mind": "pour le corps et l'esprit",
    "full thermal circuit access (all day)": "Accès complet au circuit thermal (toute la journée)",
    "guest stories": "Histoires de clients",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Les hôtes sont accueillis autour d'une tisane et invités à poser une intention pour leur séjour.",
    "hands you can trust": "Des mains de confiance",
    "himalayan sound journey": "Voyage sonore himalayen",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "J'ai visité six spas à travers l'Europe. Serene Retreat est catégoriquement différent. Le silence à lui seul vaut le voyage.",
    "included in all packages": "Compris dans toutes les formules",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "Le rituel de pierres d'Ingrid a traité des années de tension chronique en une seule séance. J'ai pleuré. Je le recommande sans réserve.",
    "meet all practitioners": "Voir tous les praticiens",
    "of immersion": "d'immersion",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "Notre parcours en six étapes suit le vieux principe du contraste — l'alternance voulue du chaud et du froid, qui met en marche les mécanismes de réparation les plus profonds.",
    "our treatments": "Nos soins",
    "private consultation with lead therapist": "Entretien privé avec la thérapeute principale",
    "read our philosophy →": "Lire notre philosophie →",
    "request reservation": "Demander une réservation",
    "reserve your stay": "Réserver votre séjour",
    "slow by design": "Lent par conception",
    "the art of": "L'art de",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "Le forfait Équinoxe a changé quelque chose de fondamental en moi. Je suis parti plus léger d'une manière que je ne peux pas expliquer aux personnes qui ne l'ont pas vécu.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "La chambre de flottaison était terrifiante pendant les cinq premières minutes et transcendante pendant les trente-cinq suivantes.",
    "the thermal circuit": "Le parcours thermal",
    "view all experiences →": "Voir toutes les expériences →",
    "view full circuit details": "Voir les détails du circuit complet",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Nous sommes venus en couple pour le forfait Équinoxe. C'est maintenant un rituel semestriel que nous protégeons comme rien d'autre.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Nous limitons les arrivées à trente personnes par jour. Ce n'est pas un métier de volume, mais de précision. Votre silence dépend de cette limite.",
    "what our guests say": "Ce que disent nos hôtes",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "guidelines for the circuit": "Las reglas del circuito",
    "hydrate between each step with our botanical infusions.": "Hidrátese entre cada etapa con nuestras infusiones de plantas.",
    "respect the silence of the chambers for all guests.": "Respete el silencio de las salas, por todos los huéspedes.",
    "robes, slippers, and towels are provided in your locker.": "Albornoz, zapatillas y toallas le esperan en el vestuario.",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest repair mechanisms.": "Nuestro recorrido en seis etapas sigue el viejo principio del contraste: la alternancia deliberada de calor y frío que activa los mecanismos de reparación más profundos.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining this limit.": "Limitamos las llegadas a treinta personas al día. No es un negocio de volumen, sino de precisión. Su silencio depende de este límite.",
    "our therapists complete 800 hours of training before their first independent session. then they continue — weekly workshops, eastern medicine study, anatomy refreshers.": "Nuestros terapeutas completan 800 horas de formación antes de su primera sesión autónoma. Y continúan: talleres semanales, medicinas orientales, repasos de anatomía.",
    "we change our treatment oils, botanical teas, and integration snacks according to the solar seasons. aligning physical recovery with natural rhythms.": "Cambiamos aceites, tisanas y colaciones al hilo de las estaciones solares: la recuperación física se acompasa a los ritmos naturales.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m in the chartreuse massif.": "Cada planta de nuestros tratamientos es ecológica certificada y recolectada a menos de doscientos kilómetros. Nuestra agua viene de un manantial granítico a 1 400 metros, en el macizo de la Chartreuse.",
    "experiences": "Los cuidados",
    "packages": "Las fórmulas",
    "philosophy": "Filosofía",
    "where stillness": "Donde la calma",
    "becomes medicine": "se vuelve cuidado",
    "alpine mineral waters": "Aguas minerales alpinas",
    "certified organic botanicals": "Plantas ecológicas certificadas",
    "biodynamic treatments": "Cuidados biodinámicos",
    "carbon neutral retreat": "Retiro neutro en carbono",
    "wild-harvested herbs": "Hierbas de recolección silvestre",
    "ancient thermal traditions": "Tradiciones termales antiguas",
    "zero fragrance synthetics": "Ningún perfume sintético",
    "forest-sourced cedar": "Cedro de nuestros bosques",
    "alpine stone ritual": "Ritual de piedras alpinas",
    "forest immersion bath": "Baño de inmersión en el bosque",
    "eastern": "Oriente",
    "jade meridian massage": "Masaje de meridianos con jade",
    "available daily, 7am – 9pm": "Abierto todos los días, 7 h – 21 h",
    "step": "Etapa",
    "arrival & intention": "Acogida e intención",
    "cold plunge activation": "Baño frío de activación",
    "infrared sauna": "Sauna de infrarrojos",
    "retreat packages": "Nuestras fórmulas",
    "half day": "Media jornada",
    "full day": "Jornada completa",
    "2-night retreat": "Estancia de dos noches",
    "full thermal circuit access (3 hours)": "Acceso al circuito termal completo (3 horas)",
    "one 60-minute signature treatment": "Un tratamiento signature de 60 minutos",
    "botanical tea ceremony": "Ceremonia de infusiones",
    "use of robes & slippers": "Albornoz y zapatillas incluidos",
    "locker & amenity access": "Vestuario y productos de acogida",
    "two signature treatments (180 min total)": "Dos tratamientos signature (180 minutos en total)",
    "forest immersion lunch (plant-based)": "Almuerzo en el bosque, totalmente vegetal",
    "morning pranayama session": "Sesión de pranayama por la mañana",
    "private meditation garden access": "Acceso al jardín de meditación privado",
    "departure gift: botanical oil blend": "Regalo de despedida: aceite de plantas",
    "two nights in a forest suite": "Dos noches en suite Bosque",
    "unlimited thermal circuit": "Circuito termal sin límite",
    "four curated treatments": "Cuatro tratamientos elegidos para usted",
    "daily guided forest bathing": "Baño de bosque guiado cada día",
    "doing nothing": "no hacer nada",
    "honest ingredients": "Materias honestas",
    "lead holistic therapist": "Terapeuta holística principal",
    "thermal therapist": "Terapeuta termal",
    "sound & meditation guide": "Guía de meditación y sonoterapia",
    "somatic bodywork": "Trabajo corporal somático",
    "botanical medicine": "Medicina de las plantas",
    "hydrotherapy": "Hidroterapia",
    "nordic bathing": "Baños nórdicos",
    "sound healing": "Sonoterapia",
    "tibetan bowls": "Cuencos tibetanos",
    "meditation": "Meditación",
    "geneva": "Ginebra",
    "london": "Londres",
    "volcanic basalt stones, heated to 56°c, melt deep tension held in muscle and fascia. an ancient practice, refined.": "Piedras de basalto volcánico, calentadas a 56 °C, funden las tensiones profundas del músculo y la fascia. Una práctica antigua, afinada.",
    "hinoki cypress and nordic moss botanicals transform warm water into a meditative forest clearing.": "Ciprés hinoki y musgo nórdico transforman el agua caliente en un claro meditativo.",
    "a 3-minute immersion in 8°c mineral water awakens the circulatory system and activates cold-shock protein pathways.": "Tres minutos en agua mineral a 8 °C: la circulación despierta y se activan las proteínas del choque térmico.",
    "far-infrared panels penetrate 4cm into tissue — twice the depth of conventional heat — releasing stored toxins at cellular level.": "Los paneles de infrarrojo lejano penetran cuatro centímetros — el doble que un calor clásico — y liberan las toxinas a nivel celular.",
    "personalized herbal protocol to take home": "Protocolo de plantas personalizado, para llevar",
    "trained in norway, bali, and kerala. fifteen years of practice in somatic bodywork and botanical medicine.": "Formada en Noruega, Bali y Kerala. Quince años de práctica en trabajo corporal somático y medicina de plantas.",
    "former competitive swimmer turned hydrotherapy specialist. certified in watsu, aquatic craniosacral, and nordic bathing.": "Antigua nadadora de competición hoy especialista en hidroterapia. Certificada en watsu, craneosacral acuático y baños nórdicos.",
    "studied under tibetan buddhist teachers for six years. integrates sound healing with somatic presence practices.": "Seis años de estudio junto a maestros budistas tibetanos. Combina el cuidado por el sonido con prácticas de presencia somática.",
    "serene retreat home": "Inicio",
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Un santuario curado de aguas termales, botánicos antiguos y silencio. A sesenta kilómetros de la ciudad. Un mundo aparte.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "La disponibilidad está limitada a treinta huéspedes por día. Recomendamos reservar con al menos dos semanas de antelación para las visitas de fin de semana.",
    "begin your retreat": "Empezar su retiro",
    "choose your depth": "Elija su profundidad",
    "compare all packages": "Comparar las fórmulas",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Cada tratamiento está diseñado como una ceremonia completa — no simplemente un servicio. Obtenemos botánicos de granjas orgánicas certificadas a menos de 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Cada planta de nuestros tratamientos está certificada ecológica y recogida a menos de doscientos kilómetros. Nuestra agua viene de un manantial granítico a mil cuatrocientos metros. En la materia no cedemos.",
    "explore packages": "Explorar Paquetes",
    "for body and mind": "para el cuerpo y la mente",
    "full thermal circuit access (all day)": "Acceso completo al circuito termal (todo el día)",
    "guest stories": "Historias de Huéspedes",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Los huéspedes son recibidos con una infusión y se les invita a formular una intención para su estancia.",
    "hands you can trust": "Manos de confianza",
    "himalayan sound journey": "Viaje sonoro del Himalaya",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "He visitado seis spas en toda Europa. Serene Retreat es categóricamente diferente. El silencio por sí solo vale el viaje.",
    "included in all packages": "Incluido en todas las fórmulas",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "El ritual de piedras de Ingrid abordó años de tensión crónica en una sola sesión. Lloré. Lo recomiendo sin reservas.",
    "meet all practitioners": "Ver a todos los terapeutas",
    "of immersion": "de inmersión",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "Nuestro recorrido en seis etapas sigue el viejo principio del contraste: la alternancia deliberada de calor y frío, que pone en marcha los mecanismos de reparación más profundos.",
    "our treatments": "Nuestros tratamientos",
    "private consultation with lead therapist": "Consulta privada con la terapeuta principal",
    "read our philosophy →": "Leer nuestra filosofía →",
    "request reservation": "Solicitar Reserva",
    "reserve your stay": "Reservar su estancia",
    "slow by design": "Lento por diseño",
    "the art of": "El arte de",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "El paquete Equinox cambió algo fundamental en mí. Salí más ligero de una manera que no puedo explicar a las personas que no lo han experimentado.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "La cámara de flotación fue aterradora durante los primeros cinco minutos y trascendental durante los siguientes treinta y cinco.",
    "the thermal circuit": "El circuito termal",
    "view all experiences →": "Ver todas las experiencias →",
    "view full circuit details": "Ver Detalles del Circuito Completo",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Vinimos como pareja para el paquete Equinox. Ahora es un ritual semestral que protegemos como nada más.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Limitamos las llegadas a treinta personas al día. No es un negocio de volumen, sino de precisión. Su silencio depende de ese límite.",
    "what our guests say": "Lo que dicen nuestros huéspedes",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "guidelines for the circuit": "Regeln für den Parcours",
    "hydrate between each step with our botanical infusions.": "Trinken Sie zwischen den Schritten unsere Kräuteraufgüsse.",
    "respect the silence of the chambers for all guests.": "Respektieren Sie die Stille der Räume, allen Gästen zuliebe.",
    "robes, slippers, and towels are provided in your locker.": "Bademantel, Slipper und Handtücher liegen in Ihrer Garderobe bereit.",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest repair mechanisms.": "Unser sechsstufiger Parcours folgt dem alten Prinzip des Kontrasts: der bewusste Wechsel von Wärme und Kälte, der die tiefsten Reparaturmechanismen des Körpers weckt.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining this limit.": "Wir begrenzen die Ankünfte auf dreißig Gäste pro Tag. Dies ist kein Mengengeschäft, sondern eines der Präzision. Ihre Stille hängt von dieser Grenze ab.",
    "our therapists complete 800 hours of training before their first independent session. then they continue — weekly workshops, eastern medicine study, anatomy refreshers.": "Unsere Therapeuten absolvieren 800 Ausbildungsstunden vor ihrer ersten eigenständigen Sitzung. Und sie lernen weiter: wöchentliche Workshops, östliche Medizin, Anatomieauffrischung.",
    "we change our treatment oils, botanical teas, and integration snacks according to the solar seasons. aligning physical recovery with natural rhythms.": "Wir wechseln Öle, Kräutertees und Snacks im Lauf der Sonnenjahreszeiten: körperliche Erholung im Einklang mit natürlichen Rhythmen.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m in the chartreuse massif.": "Jede Pflanze unserer Anwendungen ist bio-zertifiziert und stammt aus einem Umkreis von 200 km. Unser Wasser kommt aus einer Granitquelle auf 1 400 m im Chartreuse-Massiv.",
    "experiences": "Die Anwendungen",
    "packages": "Die Pakete",
    "philosophy": "Philosophie",
    "where stillness": "Wo Stille",
    "becomes medicine": "zur Medizin wird",
    "alpine mineral waters": "Alpine Mineralwasser",
    "certified organic botanicals": "Zertifizierte Bio-Pflanzen",
    "biodynamic treatments": "Biodynamische Anwendungen",
    "carbon neutral retreat": "Klimaneutrales Retreat",
    "wild-harvested herbs": "Wildgesammelte Kräuter",
    "ancient thermal traditions": "Alte Thermaltraditionen",
    "zero fragrance synthetics": "Keine synthetischen Duftstoffe",
    "forest-sourced cedar": "Zeder aus unseren Wäldern",
    "alpine stone ritual": "Ritual mit Alpensteinen",
    "forest immersion bath": "Waldimmersionsbad",
    "eastern": "Fernost",
    "jade meridian massage": "Jade-Meridian-Massage",
    "available daily, 7am – 9pm": "Täglich geöffnet, 7 – 21 Uhr",
    "step": "Schritt",
    "arrival & intention": "Ankunft und Absicht",
    "cold plunge activation": "Kaltbad zur Aktivierung",
    "infrared sauna": "Infrarotsauna",
    "retreat packages": "Unsere Pakete",
    "half day": "Halbtag",
    "full day": "Ganzer Tag",
    "2-night retreat": "Zwei-Nächte-Aufenthalt",
    "full thermal circuit access (3 hours)": "Zugang zum gesamten Thermalparcours (3 Stunden)",
    "one 60-minute signature treatment": "Eine Signature-Anwendung von 60 Minuten",
    "botanical tea ceremony": "Kräutertee-Zeremonie",
    "use of robes & slippers": "Bademantel und Slipper inklusive",
    "locker & amenity access": "Garderobe und Pflegeprodukte",
    "two signature treatments (180 min total)": "Zwei Signature-Anwendungen (insgesamt 180 Minuten)",
    "forest immersion lunch (plant-based)": "Mittagessen im Wald, rein pflanzlich",
    "morning pranayama session": "Pranayama-Sitzung am Morgen",
    "private meditation garden access": "Zugang zum privaten Meditationsgarten",
    "departure gift: botanical oil blend": "Abschiedsgeschenk: Pflanzenöl",
    "two nights in a forest suite": "Zwei Nächte in der Waldsuite",
    "unlimited thermal circuit": "Thermalparcours ohne Limit",
    "four curated treatments": "Vier für Sie ausgewählte Anwendungen",
    "daily guided forest bathing": "Täglich geführtes Waldbaden",
    "doing nothing": "des Nichtstuns",
    "honest ingredients": "Ehrliche Zutaten",
    "lead holistic therapist": "Leitende ganzheitliche Therapeutin",
    "thermal therapist": "Thermaltherapeut",
    "sound & meditation guide": "Leiter für Meditation und Klangarbeit",
    "somatic bodywork": "Somatische Körperarbeit",
    "botanical medicine": "Pflanzenheilkunde",
    "hydrotherapy": "Hydrotherapie",
    "nordic bathing": "Nordisches Baden",
    "sound healing": "Klangheilung",
    "tibetan bowls": "Tibetische Klangschalen",
    "meditation": "Meditation",
    "geneva": "Genf",
    "london": "London",
    "volcanic basalt stones, heated to 56°c, melt deep tension held in muscle and fascia. an ancient practice, refined.": "Vulkanische Basaltsteine, auf 56 °C erhitzt, lösen tiefe Spannungen in Muskel und Faszie. Eine alte Praxis, verfeinert.",
    "hinoki cypress and nordic moss botanicals transform warm water into a meditative forest clearing.": "Hinoki-Zypresse und nordisches Moos verwandeln warmes Wasser in eine meditative Lichtung.",
    "a 3-minute immersion in 8°c mineral water awakens the circulatory system and activates cold-shock protein pathways.": "Drei Minuten in 8 °C kaltem Mineralwasser: Der Kreislauf erwacht, die Kälteschockproteine werden aktiviert.",
    "far-infrared panels penetrate 4cm into tissue — twice the depth of conventional heat — releasing stored toxins at cellular level.": "Ferninfrarot-Paneele dringen vier Zentimeter ein — doppelt so tief wie herkömmliche Wärme — und lösen Giftstoffe auf Zellebene.",
    "personalized herbal protocol to take home": "Persönliches Kräuterprotokoll für zu Hause",
    "trained in norway, bali, and kerala. fifteen years of practice in somatic bodywork and botanical medicine.": "Ausgebildet in Norwegen, Bali und Kerala. Fünfzehn Jahre Praxis in somatischer Körperarbeit und Pflanzenheilkunde.",
    "former competitive swimmer turned hydrotherapy specialist. certified in watsu, aquatic craniosacral, and nordic bathing.": "Ehemalige Wettkampfschwimmerin, heute Hydrotherapie-Spezialistin. Zertifiziert in Watsu, aquatischer Craniosacraltherapie und nordischem Baden.",
    "studied under tibetan buddhist teachers for six years. integrates sound healing with somatic presence practices.": "Sechs Jahre Studium bei tibetisch-buddhistischen Lehrern. Verbindet Klangarbeit mit somatischen Präsenzpraktiken.",
    "serene retreat home": "Startseite",
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Ein kuratiertes Heiligtum aus Thermalwasser, alten Botanicals und Stille. Sechzig Kilometer von der Stadt entfernt. Eine Welt für sich.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "Die Verfügbarkeit ist auf dreißig Gäste pro Tag begrenzt. Wir empfehlen, mindestens zwei Wochen im Voraus für Wochenendbesuche zu buchen.",
    "begin your retreat": "Ihren Rückzug beginnen",
    "choose your depth": "Wählen Sie Ihre Tiefe",
    "compare all packages": "Pakete vergleichen",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Jede Behandlung ist als vollständige Zeremonie konzipiert — nicht nur als Dienstleistung. Wir beziehen Botanicals von zertifizierten Bio-Bauernhöfen innerhalb von 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Jede Pflanze in unseren Behandlungen ist biozertifiziert und stammt aus höchstens zweihundert Kilometern Umkreis. Unser Wasser kommt aus einer Granitquelle auf vierzehnhundert Metern. Beim Material machen wir keine Abstriche.",
    "explore packages": "Pakete erkunden",
    "for body and mind": "für Körper und Geist",
    "full thermal circuit access (all day)": "Vollständiger Zugang zum Thermalkreislauf (den ganzen Tag)",
    "guest stories": "Gästegeschichten",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Die Gäste werden mit einer Kräuterteezeremonie empfangen und eingeladen, eine Absicht für ihren Aufenthalt zu setzen.",
    "hands you can trust": "Hände, denen Sie vertrauen",
    "himalayan sound journey": "Himalayan Sound Journey",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "Ich habe sechs Spas in ganz Europa besucht. Serene Retreat ist kategorisch anders. Die Stille allein ist die Reise wert.",
    "included in all packages": "In allen Paketen enthalten",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "Ingrids Steinritual hat jahrelange chronische Spannungen in einer einzigen Sitzung angesprochen. Ich weinte. Ich empfehle es ohne Vorbehalte.",
    "meet all practitioners": "Alle Therapeuten ansehen",
    "of immersion": "der Immersion",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "Unser sechsstufiger Parcours folgt dem alten Prinzip des Wechselreizes — dem bewussten Wechsel von Hitze und Kälte, der die tiefsten Selbstheilungskräfte weckt.",
    "our treatments": "Unsere Behandlungen",
    "private consultation with lead therapist": "Privatgespräch mit der leitenden Therapeutin",
    "read our philosophy →": "Unsere Philosophie lesen →",
    "request reservation": "Reservierung anfragen",
    "reserve your stay": "Ihren Aufenthalt buchen",
    "slow by design": "Langsam durch Design",
    "the art of": "Die Kunst des",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "Das Equinox-Paket hat etwas Grundlegendes in mir verändert. Ich verließ es leichter auf eine Weise, die ich Menschen, die es nicht erlebt haben, nicht erklären kann.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "Die Floatationskammer war in den ersten fünf Minuten beängstigend und in den nächsten fünfunddreißig transzendent.",
    "the thermal circuit": "Der Thermalparcours",
    "view all experiences →": "Alle Erlebnisse ansehen →",
    "view full circuit details": "Vollständige Circuitdetails anzeigen",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Wir kamen als Paar für das Equinox-Paket. Es ist jetzt ein halbjährliches Ritual, das wir wie nichts anderes schützen.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Wir begrenzen die Ankünfte auf dreißig Gäste am Tag. Das ist kein Mengengeschäft, sondern ein Präzisionsgeschäft. Ihre Stille hängt an dieser Grenze.",
    "what our guests say": "Was unsere Gäste sagen",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "guidelines for the circuit": "As regras do circuito",
    "hydrate between each step with our botanical infusions.": "Hidrate-se entre cada etapa com as nossas infusões de plantas.",
    "respect the silence of the chambers for all guests.": "Respeite o silêncio das salas, por todos os hóspedes.",
    "robes, slippers, and towels are provided in your locker.": "Roupão, chinelos e toalhas esperam-no no vestiário.",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest repair mechanisms.": "O nosso percurso em seis etapas segue o velho princípio do contraste: a alternância deliberada de calor e frio que ativa os mecanismos de reparação mais profundos.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining this limit.": "Limitamos as chegadas a trinta pessoas por dia. Não é um negócio de volume, mas de precisão. O seu silêncio depende deste limite.",
    "our therapists complete 800 hours of training before their first independent session. then they continue — weekly workshops, eastern medicine study, anatomy refreshers.": "Os nossos terapeutas completam 800 horas de formação antes da primeira sessão autónoma. E continuam: ateliês semanais, medicinas orientais, revisões de anatomia.",
    "we change our treatment oils, botanical teas, and integration snacks according to the solar seasons. aligning physical recovery with natural rhythms.": "Mudamos óleos, tisanas e lanches ao longo das estações solares: a recuperação física acompanha os ritmos naturais.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m in the chartreuse massif.": "Cada planta dos nossos cuidados é biológica certificada e colhida a menos de duzentos quilómetros. A nossa água vem de uma nascente granítica a 1 400 metros, no maciço da Chartreuse.",
    "experiences": "Os cuidados",
    "packages": "As fórmulas",
    "philosophy": "Filosofia",
    "where stillness": "Onde a calma",
    "becomes medicine": "se torna cuidado",
    "alpine mineral waters": "Águas minerais alpinas",
    "certified organic botanicals": "Plantas com certificação biológica",
    "biodynamic treatments": "Cuidados biodinâmicos",
    "carbon neutral retreat": "Retiro neutro em carbono",
    "wild-harvested herbs": "Ervas de colheita silvestre",
    "ancient thermal traditions": "Tradições termais antigas",
    "zero fragrance synthetics": "Nenhum perfume sintético",
    "forest-sourced cedar": "Cedro das nossas florestas",
    "alpine stone ritual": "Ritual das pedras alpinas",
    "forest immersion bath": "Banho de imersão na floresta",
    "eastern": "Oriente",
    "jade meridian massage": "Massagem dos meridianos com jade",
    "available daily, 7am – 9pm": "Aberto todos os dias, 7 h – 21 h",
    "step": "Etapa",
    "arrival & intention": "Acolhimento e intenção",
    "cold plunge activation": "Banho frio de ativação",
    "infrared sauna": "Sauna de infravermelhos",
    "retreat packages": "As nossas fórmulas",
    "half day": "Meio-dia",
    "full day": "Dia inteiro",
    "2-night retreat": "Estadia de duas noites",
    "full thermal circuit access (3 hours)": "Acesso ao circuito termal completo (3 horas)",
    "one 60-minute signature treatment": "Um cuidado assinatura de 60 minutos",
    "botanical tea ceremony": "Cerimónia de infusões",
    "use of robes & slippers": "Roupão e chinelos incluídos",
    "locker & amenity access": "Vestiário e produtos de acolhimento",
    "two signature treatments (180 min total)": "Dois cuidados assinatura (180 minutos no total)",
    "forest immersion lunch (plant-based)": "Almoço na floresta, totalmente vegetal",
    "morning pranayama session": "Sessão de pranayama de manhã",
    "private meditation garden access": "Acesso ao jardim de meditação privado",
    "departure gift: botanical oil blend": "Presente de partida: óleo de plantas",
    "two nights in a forest suite": "Duas noites em suite Floresta",
    "unlimited thermal circuit": "Circuito termal sem limite",
    "four curated treatments": "Quatro cuidados escolhidos para si",
    "daily guided forest bathing": "Banho de floresta guiado todos os dias",
    "doing nothing": "não fazer nada",
    "honest ingredients": "Matérias honestas",
    "lead holistic therapist": "Terapeuta holística principal",
    "thermal therapist": "Terapeuta termal",
    "sound & meditation guide": "Guia de meditação e sonoterapia",
    "somatic bodywork": "Trabalho corporal somático",
    "botanical medicine": "Medicina das plantas",
    "hydrotherapy": "Hidroterapia",
    "nordic bathing": "Banhos nórdicos",
    "sound healing": "Sonoterapia",
    "tibetan bowls": "Taças tibetanas",
    "meditation": "Meditação",
    "geneva": "Genebra",
    "london": "Londres",
    "volcanic basalt stones, heated to 56°c, melt deep tension held in muscle and fascia. an ancient practice, refined.": "Pedras de basalto vulcânico, aquecidas a 56 °C, dissolvem as tensões profundas do músculo e da fáscia. Uma prática antiga, afinada.",
    "hinoki cypress and nordic moss botanicals transform warm water into a meditative forest clearing.": "Cipreste hinoki e musgo nórdico transformam a água quente numa clareira meditativa.",
    "a 3-minute immersion in 8°c mineral water awakens the circulatory system and activates cold-shock protein pathways.": "Três minutos em água mineral a 8 °C: a circulação desperta e ativam-se as proteínas do choque térmico.",
    "far-infrared panels penetrate 4cm into tissue — twice the depth of conventional heat — releasing stored toxins at cellular level.": "Os painéis de infravermelho longo penetram quatro centímetros — o dobro de um calor clássico — e libertam as toxinas ao nível celular.",
    "personalized herbal protocol to take home": "Protocolo de plantas personalizado, para levar",
    "trained in norway, bali, and kerala. fifteen years of practice in somatic bodywork and botanical medicine.": "Formada na Noruega, em Bali e no Kerala. Quinze anos de prática em trabalho corporal somático e medicina das plantas.",
    "former competitive swimmer turned hydrotherapy specialist. certified in watsu, aquatic craniosacral, and nordic bathing.": "Antiga nadadora de competição, hoje especialista em hidroterapia. Certificada em watsu, craniossacral aquático e banhos nórdicos.",
    "studied under tibetan buddhist teachers for six years. integrates sound healing with somatic presence practices.": "Seis anos de estudo junto de mestres budistas tibetanos. Junta o cuidado pelo som a práticas de presença somática.",
    "serene retreat home": "Início",
    "a curated sanctuary of thermal waters, ancient botanicals, and silence. sixty kilometres from the city. a world apart.": "Um santuário selecionado de águas termais, botânicos antigos e silêncio. A sessenta quilómetros da cidade. Um mundo à parte.",
    "availability is limited to thirty guests per day. we recommend booking at least two weeks in advance for weekend visits.": "A disponibilidade é limitada a trinta hóspedes por dia. Recomendamos reservar com pelo menos duas semanas de antecedência para visitas de fim de semana.",
    "begin your retreat": "Começar o seu retiro",
    "choose your depth": "Escolha a sua profundidade",
    "compare all packages": "Comparar as fórmulas",
    "each treatment is designed as a complete ceremony — not merely a service. we source botanicals from certified organic farms within 200km.": "Cada tratamento é concebido como uma cerimônia completa — não apenas um serviço. Obtemos botânicos de quintas orgânicas certificadas a menos de 200 km.",
    "every botanical in our treatments is certified organic and sourced within 200km. our water comes from a granite spring at 1,400m. we don't compromise on materials.": "Cada planta dos nossos tratamentos é certificada biológica e colhida a menos de duzentos quilómetros. A nossa água vem de uma nascente granítica a mil e quatrocentos metros. Na matéria não cedemos.",
    "explore packages": "Explorar Pacotes",
    "for body and mind": "para o corpo e a mente",
    "full thermal circuit access (all day)": "Acesso completo ao circuito termal (todo o dia)",
    "guest stories": "Histórias de Clientes",
    "guests are welcomed with a warm tisane ceremony and invited to set a personal intention for their time at the retreat.": "Os hóspedes são recebidos com uma tisana e convidados a formular uma intenção para a sua estadia.",
    "hands you can trust": "Mãos de confiança",
    "himalayan sound journey": "Jornada Sonora Himaláyica",
    "i have visited six spas across europe. serene retreat is categorically different. the silence alone is worth the journey.": "Visitei seis spas por toda a Europa. O Serene Retreat é categoricamente diferente. O silêncio por si só vale a viagem.",
    "included in all packages": "Incluído em todas as fórmulas",
    "ingrid's stone ritual addressed years of chronic tension in a single session. i wept. i recommend it without reservation.": "O ritual de pedras da Ingrid abordou anos de tensão crónica em uma única sessão. Eu chorei. Recomendo-o sem reservas.",
    "meet all practitioners": "Ver todos os terapeutas",
    "of immersion": "de imersão",
    "our six-step thermal journey follows the ancient principle of contrast therapy — the deliberate alternation of heat and cold that activates the body's deepest healing mechanisms.": "O nosso percurso em seis etapas segue o velho princípio do contraste — a alternância deliberada de calor e frio, que põe em marcha os mecanismos de reparação mais profundos.",
    "our treatments": "Os nossos tratamentos",
    "private consultation with lead therapist": "Consulta privada com a terapeuta principal",
    "read our philosophy →": "Ler a nossa filosofia →",
    "request reservation": "Solicitar Reserva",
    "reserve your stay": "Reservar a sua estadia",
    "slow by design": "Lento por design",
    "the art of": "A arte de",
    "the equinox package changed something fundamental in me. i left lighter in a way i cannot explain to people who haven't experienced it.": "O pacote Equinox mudou algo fundamental em mim. Saí mais leve de uma maneira que não consigo explicar às pessoas que não o vivenciaram.",
    "the floatation chamber was terrifying for the first five minutes and transcendent for the next thirty-five.": "A câmara de flutuação foi aterradora nos primeiros cinco minutos e transcendente nos trinta e cinco seguintes.",
    "the thermal circuit": "O circuito termal",
    "view all experiences →": "Ver todas as experiências →",
    "view full circuit details": "Ver Detalhes do Circuito Completo",
    "we came as a couple for the equinox package. it is now a twice-yearly ritual that we protect like nothing else.": "Viemos como casal para o pacote Equinox. Agora é um ritual semestral que protegemos como nada mais.",
    "we cap daily arrivals at thirty guests. this is not a volume business. it is a precision one. your experience of silence depends on us maintaining it.": "Limitamos as chegadas a trinta pessoas por dia. Não é um negócio de volume, mas de precisão. O seu silêncio depende desse limite.",
    "what our guests say": "O que dizem os nossos hóspedes",
  },
};
