/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"we architecturalize wealth through the acquisition of the world's most rare holdings.\"": "« Nous donnons une architecture au patrimoine, par l'acquisition des biens les plus rares au monde. »",
    "arcane doesn't just sell properties. they understand how your life should feel. we bought exactly the wrong house twice before them.": "Arcane ne se contente pas de vendre des propriétés. Ils comprennent comment votre vie devrait se sentir. Nous avons acheté exactement la mauvaise maison deux fois avant eux.",
    "arcane found our notting hill townhouse entirely off-market. their network is unlike anything we'd encountered at knight frank or savills.": "Arcane a trouvé notre maison de ville à Notting Hill entièrement hors marché. Leur réseau est sans pareil par rapport à ce que nous avions rencontré chez Knight Frank ou Savills.",
    "begin the": "Commencer Le",
    "built for the infinite.": "BÂTI POUR DURER.",
    "client voices": "Voix des clients",
    "exclusive first-access to off-market holdings before global public release.": "Accès prioritaire aux biens hors marché, avant toute mise en vente publique.",
    "explore collection": "Explorer la Collection",
    "in their": "Selon eux",
    "new york, ny": "New York",
    "non-disclosure agreements at the first point of contact. your privacy is our highest priority.": "Accord de confidentialité dès le premier échange. Votre discrétion passe avant tout.",
    "our advisors are ready to discuss your specific requirements. we don't find houses; we secure legacies.": "Nos conseillers sont prêts à discuter de vos besoins spécifiques. Nous ne trouvons pas des maisons ; nous sécurisons des héritages.",
    "our legacy": "Notre héritage",
    "request private audit": "Demander un Audit Privé",
    "request tour": "Demander une visite",
    "securing the world's most exclusive architectural masterpieces for the most discerning collectors.": "Sécuriser les chefs-d'œuvre architecturaux les plus exclusifs du monde pour les collectionneurs les plus exigeants.",
    "the level of discretion was absolute. three continents, one advisor — the whole transaction felt effortless.": "Le niveau de discrétion était absolu. Trois continents, un conseiller — toute la transaction semblait sans effort.",
    "the obsidian penthouse": "Le Penthouse Obsidien",
    "view portfolio": "Voir le Portfolio",
  },
  es: {
    "\"we architecturalize wealth through the acquisition of the world's most rare holdings.\"": "«Damos arquitectura al patrimonio mediante la adquisición de los bienes más raros del mundo.»",
    "arcane doesn't just sell properties. they understand how your life should feel. we bought exactly the wrong house twice before them.": "Arcane no solo vende propiedades. Entienden cómo debería sentirse tu vida. Compramos exactamente la casa equivocada dos veces antes de ellos.",
    "arcane found our notting hill townhouse entirely off-market. their network is unlike anything we'd encountered at knight frank or savills.": "Arcane encontró nuestra casa adosada en Notting Hill completamente fuera del mercado. Su red es diferente a cualquier cosa que hayamos encontrado en Knight Frank o Savills.",
    "begin the": "Comenzar El",
    "built for the infinite.": "CONSTRUIDO PARA DURAR.",
    "client voices": "Voces de los clientes",
    "exclusive first-access to off-market holdings before global public release.": "Acceso prioritario a bienes fuera de mercado, antes de cualquier salida pública.",
    "explore collection": "Explorar Colección",
    "in their": "Según ellos",
    "new york, ny": "Nueva York",
    "non-disclosure agreements at the first point of contact. your privacy is our highest priority.": "Acuerdo de confidencialidad desde el primer contacto. Su discreción es lo primero.",
    "our advisors are ready to discuss your specific requirements. we don't find houses; we secure legacies.": "Nuestros asesores están listos para discutir sus requisitos específicos. No encontramos casas; aseguramos legados.",
    "our legacy": "Nuestro legado",
    "request private audit": "Solicitar Auditoría Privada",
    "request tour": "Solicitar una visita",
    "securing the world's most exclusive architectural masterpieces for the most discerning collectors.": "Asegurando las obras maestras arquitectónicas más exclusivas del mundo para los coleccionistas más exigentes.",
    "the level of discretion was absolute. three continents, one advisor — the whole transaction felt effortless.": "El nivel de discreción fue absoluto. Tres continentes, un asesor: toda la transacción se sintió sin esfuerzo.",
    "the obsidian penthouse": "El Ático Obsidiana",
    "view portfolio": "Ver Portafolio",
  },
  de: {
    "\"we architecturalize wealth through the acquisition of the world's most rare holdings.\"": "„Wir geben Vermögen eine Architektur — durch den Erwerb der seltensten Objekte der Welt.“",
    "arcane doesn't just sell properties. they understand how your life should feel. we bought exactly the wrong house twice before them.": "Arcane verkauft nicht nur Immobilien. Sie verstehen, wie sich Ihr Leben anfühlen sollte. Wir haben genau das falsche Haus zweimal vor ihnen gekauft.",
    "arcane found our notting hill townhouse entirely off-market. their network is unlike anything we'd encountered at knight frank or savills.": "Arcane fand unser Stadthaus in Notting Hill vollständig off-market. Ihr Netzwerk ist einzigartig im Vergleich zu dem, was wir bei Knight Frank oder Savills erlebt haben.",
    "begin the": "Beginnen Sie Den",
    "built for the infinite.": "FÜR DIE EWIGKEIT GEBAUT.",
    "client voices": "Kundenstimmen",
    "exclusive first-access to off-market holdings before global public release.": "Vorrangiger Zugang zu Off-Market-Objekten, vor jeder öffentlichen Vermarktung.",
    "explore collection": "Kollektion Entdecken",
    "in their": "In ihren Worten",
    "new york, ny": "New York",
    "non-disclosure agreements at the first point of contact. your privacy is our highest priority.": "Vertraulichkeitsvereinbarung ab dem ersten Kontakt. Ihre Diskretion steht an erster Stelle.",
    "our advisors are ready to discuss your specific requirements. we don't find houses; we secure legacies.": "Unsere Berater sind bereit, Ihre spezifischen Anforderungen zu besprechen. Wir finden keine Häuser; wir sichern Vermächtnisse.",
    "our legacy": "Unser Erbe",
    "request private audit": "Private Prüfung Anfordern",
    "request tour": "Besichtigung anfragen",
    "securing the world's most exclusive architectural masterpieces for the most discerning collectors.": "Die exklusivsten architektonischen Meisterwerke der Welt für die anspruchsvollsten Sammler sichern.",
    "the level of discretion was absolute. three continents, one advisor — the whole transaction felt effortless.": "Das Maß an Diskretion war absolut. Drei Kontinente, ein Berater — die gesamte Transaktion fühlte sich mühelos an.",
    "the obsidian penthouse": "Das Obsidian-Penthouse",
    "view portfolio": "Portfolio Ansehen",
  },
  pt: {
    "\"we architecturalize wealth through the acquisition of the world's most rare holdings.\"": "«Damos arquitetura ao património, pela aquisição dos bens mais raros do mundo.»",
    "arcane doesn't just sell properties. they understand how your life should feel. we bought exactly the wrong house twice before them.": "A Arcane não vende apenas propriedades. Eles entendem como a sua vida deve ser. Comprámos exatamente a casa errada duas vezes antes deles.",
    "arcane found our notting hill townhouse entirely off-market. their network is unlike anything we'd encountered at knight frank or savills.": "A Arcane encontrou a nossa moradia em Notting Hill totalmente fora do mercado. A sua rede é diferente de tudo o que encontramos na Knight Frank ou na Savills.",
    "begin the": "Começar O",
    "built for the infinite.": "CONSTRUÍDO PARA DURAR.",
    "client voices": "Vozes dos clientes",
    "exclusive first-access to off-market holdings before global public release.": "Acesso prioritário a bens fora de mercado, antes de qualquer colocação pública.",
    "explore collection": "Explorar Coleção",
    "in their": "Segundo eles",
    "new york, ny": "Nova Iorque",
    "non-disclosure agreements at the first point of contact. your privacy is our highest priority.": "Acordo de confidencialidade desde o primeiro contacto. A sua discrição vem primeiro.",
    "our advisors are ready to discuss your specific requirements. we don't find houses; we secure legacies.": "Os nossos consultores estão prontos para discutir os seus requisitos específicos. Não encontramos casas; garantimos legados.",
    "our legacy": "O nosso legado",
    "request private audit": "Solicitar Auditoria Privada",
    "request tour": "Pedir uma visita",
    "securing the world's most exclusive architectural masterpieces for the most discerning collectors.": "Garantindo as obras-primas arquitetônicas mais exclusivas do mundo para os colecionadores mais exigentes.",
    "the level of discretion was absolute. three continents, one advisor — the whole transaction felt effortless.": "O nível de discrição foi absoluto. Três continentes, um consultor — toda a transação parecia sem esforço.",
    "the obsidian penthouse": "O Penthouse Obsidiana",
    "view portfolio": "Ver Portfólio",
  },
};
