/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "animated content that stops the scroll.": "Contenu animé qui arrête le défilement.",
    "campaign design": "Conception de campagne",
    "client": "Client",
    "creative agency for brands in motion.": "Agence créative pour les marques en mouvement.",
    "head of brand strategy": "Responsable de la stratégie de marque",
    "if it stands still, it's invisible. in a world of infinite scroll, we design for momentum, impact, and unforgettable digital interactions.": "Ce qui ne bouge pas est invisible. Dans un monde qui défile sans fin, nous concevons pour l'élan, la marque laissée et l'interaction dont on se souvient.",
    "immersive websites that convert attention into action.": "Des sites immersifs qui changent l'attention en action.",
    "kinetic doesn't just design — they ignite. our rebrand generated a 400% increase in social engagement within the first month.": "Kinetic ne se contente pas de concevoir — ils enflamment. Notre rebranding a généré une augmentation de 400 % de l'engagement social au cours du premier mois.",
    "let's build something unforgettable together.": "Bâtissons ensemble quelque chose dont on se souvienne.",
    "let's make": "Faisons",
    "motion design": "Design de mouvement",
    "multi-channel campaigns that amplify your message.": "Des campagnes multicanales qui portent votre message.",
    "name, logo, visual system, and tone of voice. a complete brand from scratch.": "Nom, logo, système visuel et ton de voix. Une marque complète depuis zéro.",
    "other": "Autre",
    "thank you": "Merci",
    "the website they built is an experience. our bounce rate dropped to 8% and conversions tripled.": "Le site web qu'ils ont construit est une expérience. Notre taux de rebond est tombé à 8 % et les conversions ont triplé.",
    "what we": "Ce que nous",
    "work.": "Travail.",
    "working with kinetic felt like having the best creative team in-house. except they're actually good.": "Travailler avec Kinetic, c'était comme avoir la meilleure équipe créative en interne. Sauf qu'ils sont vraiment bons.",
  },
  es: {
    "animated content that stops the scroll.": "Contenido animado que detiene el desplazamiento.",
    "campaign design": "Diseño de campaña",
    "client": "Cliente",
    "creative agency for brands in motion.": "Agencia creativa para marcas en movimiento.",
    "head of brand strategy": "Jefe de estrategia de marca",
    "if it stands still, it's invisible. in a world of infinite scroll, we design for momentum, impact, and unforgettable digital interactions.": "Lo que no se mueve es invisible. En un mundo de desplazamiento infinito, diseñamos para el impulso, la huella y la interacción memorable.",
    "immersive websites that convert attention into action.": "Sitios inmersivos que convierten la atención en acción.",
    "kinetic doesn't just design — they ignite. our rebrand generated a 400% increase in social engagement within the first month.": "Kinetic no solo diseña, sino que enciende. Nuestro rebranding generó un aumento del 400 % en el compromiso social durante el primer mes.",
    "let's build something unforgettable together.": "Construyamos juntos algo memorable.",
    "let's make": "Hagamos",
    "motion design": "Diseño en movimiento",
    "multi-channel campaigns that amplify your message.": "Campañas multicanal que amplifican su mensaje.",
    "name, logo, visual system, and tone of voice. a complete brand from scratch.": "Nombre, logo, sistema visual y tono de voz. Una marca completa desde cero.",
    "other": "Otro",
    "thank you": "Gracias",
    "the website they built is an experience. our bounce rate dropped to 8% and conversions tripled.": "El sitio web que construyeron es una experiencia. Nuestra tasa de rebote cayó al 8 % y las conversiones se triplicaron.",
    "what we": "Lo que nosotros",
    "work.": "Trabajo.",
    "working with kinetic felt like having the best creative team in-house. except they're actually good.": "Trabajar con Kinetic se sintió como tener el mejor equipo creativo interno. Excepto que realmente son buenos.",
  },
  de: {
    "animated content that stops the scroll.": "Animierter Inhalt, der das Scrollen stoppt.",
    "campaign design": "Kampagnendesign",
    "client": "Kunde",
    "creative agency for brands in motion.": "Kreativagentur für Marken in Bewegung.",
    "head of brand strategy": "Leiter der Markenstrategie",
    "if it stands still, it's invisible. in a world of infinite scroll, we design for momentum, impact, and unforgettable digital interactions.": "Was stillsteht, ist unsichtbar. In einer Welt des endlosen Scrollens gestalten wir für Schwung, Wirkung und unvergessliche Interaktion.",
    "immersive websites that convert attention into action.": "Immersive Websites, die Aufmerksamkeit in Handlung verwandeln.",
    "kinetic doesn't just design — they ignite. our rebrand generated a 400% increase in social engagement within the first month.": "Kinetic gestaltet nicht nur — sie entfachen. Unser Rebranding führte im ersten Monat zu einem Anstieg von 400 % beim sozialen Engagement.",
    "let's build something unforgettable together.": "Bauen wir gemeinsam etwas Unvergessliches.",
    "let's make": "Machen wir",
    "motion design": "Bewegungsdesign",
    "multi-channel campaigns that amplify your message.": "Mehrkanalkampagnen, die Ihre Botschaft tragen.",
    "name, logo, visual system, and tone of voice. a complete brand from scratch.": "Name, Logo, visuelles System und Tonfall. Eine komplette Marke von Grund auf.",
    "other": "Andere",
    "thank you": "Danke",
    "the website they built is an experience. our bounce rate dropped to 8% and conversions tripled.": "Die Website, die sie erstellt haben, ist ein Erlebnis. Unsere Absprungrate fiel auf 8 % und die Conversions verdreifachten sich.",
    "what we": "Was wir",
    "work.": "Arbeit.",
    "working with kinetic felt like having the best creative team in-house. except they're actually good.": "Die Zusammenarbeit mit Kinetic fühlte sich an, als hätte man das beste kreative Team intern. Außer, dass sie tatsächlich gut sind.",
  },
  pt: {
    "animated content that stops the scroll.": "Conteúdo animado que para o scroll.",
    "campaign design": "Design de campanha",
    "client": "Cliente",
    "creative agency for brands in motion.": "Agência criativa para marcas em movimento.",
    "head of brand strategy": "Chefe de estratégia de marca",
    "if it stands still, it's invisible. in a world of infinite scroll, we design for momentum, impact, and unforgettable digital interactions.": "O que não se move é invisível. Num mundo de deslocamento infinito, desenhamos para o impulso, a marca deixada e a interação memorável.",
    "immersive websites that convert attention into action.": "Sites imersivos que transformam a atenção em ação.",
    "kinetic doesn't just design — they ignite. our rebrand generated a 400% increase in social engagement within the first month.": "A Kinetic não apenas projeta — eles acendem. O nosso rebranding gerou um aumento de 400% no engajamento social no primeiro mês.",
    "let's build something unforgettable together.": "Vamos construir juntos algo memorável.",
    "let's make": "Vamos fazer",
    "motion design": "Design em movimento",
    "multi-channel campaigns that amplify your message.": "Campanhas multicanal que ampliam a sua mensagem.",
    "name, logo, visual system, and tone of voice. a complete brand from scratch.": "Nome, logótipo, sistema visual e tom de voz. Uma marca completa do zero.",
    "other": "Outro",
    "thank you": "Obrigado",
    "the website they built is an experience. our bounce rate dropped to 8% and conversions tripled.": "O site que eles construíram é uma experiência. A nossa taxa de rejeição caiu para 8% e as conversões triplicaram.",
    "what we": "O que nós",
    "work.": "Trabalho.",
    "working with kinetic felt like having the best creative team in-house. except they're actually good.": "Trabalhar com a Kinetic parecia ter a melhor equipe criativa interna. Exceto que eles são realmente bons.",
  },
};
