/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "✓ genesis compiled in 847ms — ready to render": "✓ Genesis compilé en 847ms — prêt à rendre",
    "about atelier": "À propos de l'atelier",
    "compare plans": "Comparer les plans",
    "consolidate your rendering stack onto a direct gpu cluster. build, mutation, and deployment layered in mathematical vector spaces.": "Consolidez votre pile de rendu sur un cluster GPU direct. Construction, mutation et déploiement superposés dans des espaces vectoriels mathématiques.",
    "deploy your first pipeline in under 5 minutes. no credit card required for the 14-day trial.": "Déployez votre première chaîne en moins de cinq minutes. Aucune carte bancaire pour l'essai de quatorze jours.",
    "end-to-end encryption baked into the data layer. zero-knowledge proofs by default.": "Chiffrement de bout en bout intégré dans la couche de données. Preuves à connaissance nulle par défaut.",
    "engineered for vector performance": "Conçu pour la performance vectorielle",
    "for independent artists and small creative teams.": "Pour les artistes indépendants et les petites équipes créatives.",
    "generative models trained on 10b creative samples. art that thinks for itself.": "Modèles génératifs entraînés sur 10 milliards d'échantillons créatifs. Un art qui pense par lui-même.",
    "graphql + rest with auto-generated typescript types. ship in hours, not days.": "GraphQL + REST avec des types TypeScript générés automatiquement. Expédiez en heures, pas en jours.",
    "graphql and rest engines with auto-generated typescript declarations. construct layered primitives with pure, structured javascript.": "Moteurs GraphQL et REST avec des déclarations TypeScript générées automatiquement. Construisez des primitives en couches avec du JavaScript pur et structuré.",
    "on-prem deployment and sla guarantees.": "Déploiement sur site et garanties SLA.",
    "on-prem or cloud": "Sur site ou dans le cloud",
    "on-premise deployment": "Déploiement sur site",
    "perfect for indie artists and small studios.": "Parfait pour les artistes indépendants et les petits studios.",
    "read the api docs": "Lire la documentation de l'API",
    "real-time observability with sub-second metric refresh. see everything, always.": "Observabilité en temps réel, mesures rafraîchies à la seconde. Tout voir, tout le temps.",
    "real-time telemetry": "Télémétrie en temps réel",
    "samples processed": "Échantillons traités",
    "scale your rendering pipeline.": "Montez en charge votre chaîne de rendu.",
    "stack visual primitives with mathematical precision. every layer is gpu-accelerated.": "Empilez les primitives visuelles avec une précision mathématique. Chaque couche passe par le processeur graphique.",
    "start rendering": "Commencer le rendu",
    "sub-millisecond computation pipeline with predictive cache warming. your users never wait.": "Une chaîne de calcul sous la milliseconde, avec préchauffage prédictif du cache. Vos utilisateurs n'attendent jamais.",
    "synthesize directly from your terminal": "Synthétisez directement depuis votre terminal",
    "team blog": "Blog de l'équipe",
    "the full pipeline for professional studios.": "Le pipeline complet pour les studios professionnels.",
    "the generative product engine for modern studios. infinite canvas synthesis on direct gpu networks.": "Le moteur de produit génératif pour les studios modernes. Synthèse de toile infinie sur des réseaux GPU directs.",
    "the gpu cluster is waiting.": "La grappe de calcul vous attend.",
    "view pricing": "Voir les prix",
    "white-label deployment on your infrastructure.": "Déploiement en marque blanche sur votre infrastructure.",
  },
  es: {
    "✓ genesis compiled in 847ms — ready to render": "✓ Genesis compilado en 847ms — listo para renderizar",
    "about atelier": "Sobre el taller",
    "compare plans": "Comparar planes",
    "consolidate your rendering stack onto a direct gpu cluster. build, mutation, and deployment layered in mathematical vector spaces.": "Consolide tu pila de renderizado en un clúster GPU directo. Construcción, mutación y despliegue en capas en espacios vectoriales matemáticos.",
    "deploy your first pipeline in under 5 minutes. no credit card required for the 14-day trial.": "Despliegue su primera cadena en menos de cinco minutos. Sin tarjeta para la prueba de catorce días.",
    "end-to-end encryption baked into the data layer. zero-knowledge proofs by default.": "Cifrado de extremo a extremo integrado en la capa de datos. Pruebas de conocimiento cero por defecto.",
    "engineered for vector performance": "Concebido para el rendimiento vectorial",
    "for independent artists and small creative teams.": "Para artistas independientes y pequeños equipos creativos.",
    "generative models trained on 10b creative samples. art that thinks for itself.": "Modelos generativos entrenados en 10 mil millones de muestras creativas. Arte que piensa por sí mismo.",
    "graphql + rest with auto-generated typescript types. ship in hours, not days.": "GraphQL + REST con tipos de TypeScript generados automáticamente. Envía en horas, no en días.",
    "graphql and rest engines with auto-generated typescript declarations. construct layered primitives with pure, structured javascript.": "Motores GraphQL y REST con declaraciones de TypeScript generadas automáticamente. Construye primitivas en capas con JavaScript puro y estructurado.",
    "on-prem deployment and sla guarantees.": "Despliegue en las instalaciones y garantías de SLA.",
    "on-prem or cloud": "Local o en la nube",
    "on-premise deployment": "Implementación local",
    "perfect for indie artists and small studios.": "Perfecto para artistas independientes y pequeños estudios.",
    "read the api docs": "Leer la documentación de la API",
    "real-time observability with sub-second metric refresh. see everything, always.": "Observabilidad en tiempo real, métricas actualizadas al segundo. Verlo todo, siempre.",
    "real-time telemetry": "Telemetría en tiempo real",
    "samples processed": "Muestras procesadas",
    "scale your rendering pipeline.": "Escale su cadena de renderizado.",
    "stack visual primitives with mathematical precision. every layer is gpu-accelerated.": "Apile las primitivas visuales con precisión matemática. Cada capa pasa por la tarjeta gráfica.",
    "start rendering": "Empezar a renderizar",
    "sub-millisecond computation pipeline with predictive cache warming. your users never wait.": "Una cadena de cálculo por debajo del milisegundo, con precalentamiento predictivo de la caché. Sus usuarios nunca esperan.",
    "synthesize directly from your terminal": "Sintetiza directamente desde tu terminal",
    "team blog": "Blog del equipo",
    "the full pipeline for professional studios.": "El pipeline completo para estudios profesionales.",
    "the generative product engine for modern studios. infinite canvas synthesis on direct gpu networks.": "El motor de producto generativo para estudios modernos. Síntesis de lienzo infinito en redes GPU directas.",
    "the gpu cluster is waiting.": "El clúster de cálculo le espera.",
    "view pricing": "Ver precios",
    "white-label deployment on your infrastructure.": "Despliegue de marca blanca en su infraestructura.",
  },
  de: {
    "✓ genesis compiled in 847ms — ready to render": "✓ Genesis in 847ms kompiliert — bereit zum Rendern",
    "about atelier": "Über das Atelier",
    "compare plans": "Pläne vergleichen",
    "consolidate your rendering stack onto a direct gpu cluster. build, mutation, and deployment layered in mathematical vector spaces.": "Konsolidieren Sie Ihren Rendering-Stack auf einem direkten GPU-Cluster. Aufbau, Mutation und Bereitstellung in mathematischen Vektorräumen geschichtet.",
    "deploy your first pipeline in under 5 minutes. no credit card required for the 14-day trial.": "Bringen Sie Ihre erste Pipeline in unter fünf Minuten live. Keine Kreditkarte für die vierzehntägige Testphase.",
    "end-to-end encryption baked into the data layer. zero-knowledge proofs by default.": "End-to-End-Verschlüsselung in die Datenschicht integriert. Standardmäßig Null-Wissen-Beweise.",
    "engineered for vector performance": "Für Vektorleistung gebaut",
    "for independent artists and small creative teams.": "Für unabhängige Künstler und kleine kreative Teams.",
    "generative models trained on 10b creative samples. art that thinks for itself.": "Generative Modelle, die auf 10 Milliarden kreativen Beispielen trainiert wurden. Kunst, die für sich selbst denkt.",
    "graphql + rest with auto-generated typescript types. ship in hours, not days.": "GraphQL + REST mit automatisch generierten TypeScript-Typen. In Stunden, nicht in Tagen versenden.",
    "graphql and rest engines with auto-generated typescript declarations. construct layered primitives with pure, structured javascript.": "GraphQL- und REST-Engines mit automatisch generierten TypeScript-Deklarationen. Schichten Sie primitive Elemente mit reinem, strukturiertem JavaScript.",
    "on-prem deployment and sla guarantees.": "On-Premise-Bereitstellung und SLA-Garantien.",
    "on-prem or cloud": "On-Premise oder Cloud",
    "on-premise deployment": "On-Premise-Bereitstellung",
    "perfect for indie artists and small studios.": "Perfekt für Indie-Künstler und kleine Studios.",
    "read the api docs": "API-Dokumentation lesen",
    "real-time observability with sub-second metric refresh. see everything, always.": "Beobachtbarkeit in Echtzeit, Messwerte im Sekundentakt. Alles sehen, jederzeit.",
    "real-time telemetry": "Echtzeit-Telemetrie",
    "samples processed": "Verarbeitete Proben",
    "scale your rendering pipeline.": "Skalieren Sie Ihre Render-Kette.",
    "stack visual primitives with mathematical precision. every layer is gpu-accelerated.": "Stapeln Sie visuelle Primitive mit mathematischer Präzision. Jede Ebene läuft über die GPU.",
    "start rendering": "Rendern starten",
    "sub-millisecond computation pipeline with predictive cache warming. your users never wait.": "Eine Rechenkette unter einer Millisekunde, mit vorausschauendem Cache-Aufwärmen. Ihre Nutzer warten nie.",
    "synthesize directly from your terminal": "Direkt von Ihrem Terminal aus synthetisieren",
    "team blog": "Team-Blog",
    "the full pipeline for professional studios.": "Die vollständige Pipeline für professionelle Studios.",
    "the generative product engine for modern studios. infinite canvas synthesis on direct gpu networks.": "Die generative Produktmaschine für moderne Studios. Unendliche Leinensynthese auf direkten GPU-Netzwerken.",
    "the gpu cluster is waiting.": "Der Rechencluster wartet.",
    "view pricing": "Preise anzeigen",
    "white-label deployment on your infrastructure.": "White-Label-Bereitstellung auf Ihrer Infrastruktur.",
  },
  pt: {
    "✓ genesis compiled in 847ms — ready to render": "✓ Genesis compilado em 847ms — pronto para renderizar",
    "about atelier": "Sobre o atelier",
    "compare plans": "Comparar planos",
    "consolidate your rendering stack onto a direct gpu cluster. build, mutation, and deployment layered in mathematical vector spaces.": "Consolide a sua pilha de renderização em um cluster GPU direto. Construção, mutação e implantação em camadas em espaços vetoriais matemáticos.",
    "deploy your first pipeline in under 5 minutes. no credit card required for the 14-day trial.": "Implante a sua primeira cadeia em menos de cinco minutos. Sem cartão para o teste de catorze dias.",
    "end-to-end encryption baked into the data layer. zero-knowledge proofs by default.": "Criptografia de ponta a ponta incorporada na camada de dados. Provas de conhecimento zero por padrão.",
    "engineered for vector performance": "Concebido para o desempenho vetorial",
    "for independent artists and small creative teams.": "Para artistas independentes e pequenas equipas criativas.",
    "generative models trained on 10b creative samples. art that thinks for itself.": "Modelos generativos treinados em 10 mil milhões de amostras criativas. Arte que pensa por si mesmo.",
    "graphql + rest with auto-generated typescript types. ship in hours, not days.": "GraphQL + REST com tipos TypeScript gerados automaticamente. Envie em horas, não em dias.",
    "graphql and rest engines with auto-generated typescript declarations. construct layered primitives with pure, structured javascript.": "Motores GraphQL e REST com declarações TypeScript geradas automaticamente. Construa primitivas em camadas com JavaScript puro e estruturado.",
    "on-prem deployment and sla guarantees.": "Implantação local e garantias de SLA.",
    "on-prem or cloud": "Local ou na nuvem",
    "on-premise deployment": "Implantação local",
    "perfect for indie artists and small studios.": "Perfeito para artistas independentes e pequenos estúdios.",
    "read the api docs": "Ler a documentação da API",
    "real-time observability with sub-second metric refresh. see everything, always.": "Observabilidade em tempo real, métricas atualizadas ao segundo. Ver tudo, sempre.",
    "real-time telemetry": "Telemetria em tempo real",
    "samples processed": "Amostras processadas",
    "scale your rendering pipeline.": "Escale a sua cadeia de renderização.",
    "stack visual primitives with mathematical precision. every layer is gpu-accelerated.": "Empilhe as primitivas visuais com precisão matemática. Cada camada passa pelo processador gráfico.",
    "start rendering": "Começar a renderizar",
    "sub-millisecond computation pipeline with predictive cache warming. your users never wait.": "Uma cadeia de cálculo abaixo do milissegundo, com pré-aquecimento preditivo da cache. Os seus utilizadores nunca esperam.",
    "synthesize directly from your terminal": "Sintetize diretamente do seu terminal",
    "team blog": "Blog da equipa",
    "the full pipeline for professional studios.": "O pipeline completo para estúdios profissionais.",
    "the generative product engine for modern studios. infinite canvas synthesis on direct gpu networks.": "O motor de produto generativo para estúdios modernos. Síntese de tela infinita em redes GPU diretas.",
    "the gpu cluster is waiting.": "O cluster de cálculo espera por si.",
    "view pricing": "Ver preços",
    "white-label deployment on your infrastructure.": "Implantação de marca branca na sua infraestrutura.",
  },
};
