/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "15% off all purchases": "15 % sur tous les achats",
    "are private events possible?": "Des événements privés sont-ils possibles ?",
    "can i purchase bottles to take home?": "Puis-je acheter des bouteilles à emporter ?",
    "do i need wine knowledge to visit or join?": "Ai-je besoin de connaissances en vin pour visiter ou rejoindre ?",
    "for the connoisseur": "Pour les connaisseurs",
    "for the curious": "Pour les curieux",
    "for the devoted": "Pour les fidèles",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champagnes de producteurs associés à de fins fromages et charcuterie par le Chef Dupont.",
    "how do i pause or cancel my membership?": "Comment puis-je mettre en pause ou annuler mon adhésion ?",
    "how does cellar storage work for sommelier and grand cru members?": "Comment fonctionne le stockage en cave pour les membres Sommelier et Grand Cru ?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Je me suis inscrit sans rien savoir sur le vin. Douze mois plus tard, je mets en cave des bouteilles avec confiance. L'éducation est intégrée dans chaque expérience ici.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Vins à faible intervention de petits producteurs en France, en Espagne et en Géorgie.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "Les adhésions peuvent être mises en pause une fois par an pendant jusqu'à 2 mois. L'annulation nécessite un préavis de 30 jours. Nous traitons tout de manière transparente — sans pénalités.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot noir et chardonnay de la Côte-d'Or — le cœur spirituel du vin français.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "La sélection mensuelle de bouteilles est extraordinaire. Ils ont trouvé un Barolo que je cherchais depuis trois ans — livré chez moi avec des notes de dégustation manuscrites.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Dégustation verticale de Gevrey-Chambertin sur trois millésimes avec Marie-Helene Fabre MW.",
    "what food is served?": "Quelle nourriture est servie ?",
  },
  es: {
    "15% off all purchases": "15 % en todas las compras",
    "are private events possible?": "¿Son posibles eventos privados?",
    "can i purchase bottles to take home?": "¿Puedo comprar botellas para llevar a casa?",
    "do i need wine knowledge to visit or join?": "¿Necesito conocimientos sobre vino para visitar o unirme?",
    "for the connoisseur": "Para los entendidos",
    "for the curious": "Para los curiosos",
    "for the devoted": "Para los fieles",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champagnes de productores combinados con finos quesos y charcutería por el Chef Dupont.",
    "how do i pause or cancel my membership?": "¿Cómo puedo pausar o cancelar mi membresía?",
    "how does cellar storage work for sommelier and grand cru members?": "¿Cómo funciona el almacenamiento en bodega para los miembros Sommelier y Grand Cru?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Me uní sin saber nada de vino. Doce meses después, estoy almacenando botellas con confianza. La educación está integrada en cada experiencia aquí.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Vinos de baja intervención de pequeños productores en Francia, España y Georgia.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "Las membresías se pueden pausar una vez al año por hasta 2 meses. La cancelación requiere un aviso de 30 días. Procesamos todo sin problemas — sin penalizaciones.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot noir y chardonnay de la Côte-d'Or, el corazón espiritual del vino francés.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "La curaduría mensual de botellas es extraordinaria. Encontraron un Barolo que había estado buscando durante tres años — entregado en mi casa con notas de cata escritas a mano.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Cata vertical de Gevrey-Chambertin a través de tres cosechas con Marie-Helene Fabre MW.",
    "what food is served?": "¿Qué comida se sirve?",
  },
  de: {
    "15% off all purchases": "15 % auf alle Einkäufe",
    "are private events possible?": "Sind private Veranstaltungen möglich?",
    "can i purchase bottles to take home?": "Kann ich Flaschen zum Mitnehmen kaufen?",
    "do i need wine knowledge to visit or join?": "Brauche ich Weinwissen, um zu besuchen oder beizutreten?",
    "for the connoisseur": "Für Kenner",
    "for the curious": "Für die Neugierigen",
    "for the devoted": "Für die Treuen",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champagner von Erzeugern kombiniert mit feinem Käse und Charcuterie von Chef Dupont.",
    "how do i pause or cancel my membership?": "Wie kann ich meine Mitgliedschaft pausieren oder kündigen?",
    "how does cellar storage work for sommelier and grand cru members?": "Wie funktioniert die Lagerung im Keller für Sommelier- und Grand Cru-Mitglieder?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Ich trat bei, ohne etwas über Wein zu wissen. Zwölf Monate später lagere ich mit Vertrauen Flaschen. Die Ausbildung ist in jeder Erfahrung hier eingebettet.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Niedrigintervention Weine von kleinen Produzenten in Frankreich, Spanien und Georgien.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "Mitgliedschaften können einmal im Jahr für bis zu 2 Monate pausiert werden. Die Kündigung erfordert eine Frist von 30 Tagen. Wir bearbeiten alles nahtlos — keine Strafen.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot Noir und Chardonnay von der Côte-d'Or — dem geistigen Herzen des französischen Weins.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "Die monatliche Flaschenkuration ist außergewöhnlich. Sie haben einen Barolo beschafft, nach dem ich drei Jahre lang gesucht habe — direkt zu mir nach Hause mit handgeschriebenen Verkostungsnotizen.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Vertikale Verkostung von Gevrey-Chambertin über drei Jahrgänge mit Marie-Helene Fabre MW.",
    "what food is served?": "Welche Speisen werden serviert?",
  },
  pt: {
    "15% off all purchases": "15 % em todas as compras",
    "are private events possible?": "São possíveis eventos privados?",
    "can i purchase bottles to take home?": "Posso comprar garrafas para levar para casa?",
    "do i need wine knowledge to visit or join?": "Preciso de conhecimentos sobre vinho para visitar ou aderir?",
    "for the connoisseur": "Para os entendidos",
    "for the curious": "Para os curiosos",
    "for the devoted": "Para os fiéis",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champanhes de produtores emparelhados com queijos finos e charcutaria pelo Chef Dupont.",
    "how do i pause or cancel my membership?": "Como posso pausar ou cancelar a minha adesão?",
    "how does cellar storage work for sommelier and grand cru members?": "Como funciona o armazenamento na adega para membros Sommelier e Grand Cru?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Entrei sem saber nada sobre vinho. Doze meses depois, estou a armazenar garrafas com confiança. A educação está incorporada em cada experiência aqui.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Vinhos de baixa intervenção de pequenos produtores em França, Espanha e Geórgia.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "As adesões podem ser pausadas uma vez por ano por até 2 meses. O cancelamento requer um aviso de 30 dias. Processamos tudo de forma fluida — sem penalizações.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot noir e chardonnay da Côte-d'Or — o coração espiritual do vinho francês.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "A curadoria mensal de garrafas é extraordinária. Eles encontraram um Barolo que eu procurava há três anos — entregue em minha casa com notas de prova escritas à mão.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Prova vertical de Gevrey-Chambertin em três colheitas com Marie-Helene Fabre MW.",
    "what food is served?": "Que comida é servida?",
  },
};
