/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "guided by claire vidal,": "Sous la conduite de Claire Vidal,",
    "each evening at": "Chaque soir au",
    "bordeaux grands crus evening": "Soirée grands crus de Bordeaux",
    "6 wines including two 2016 first growths, guided by maison bourgeois.": "Six vins dont deux premiers crus 2016, commentés par la Maison Bourgeois.",
    "natural wine discovery night": "Soirée découverte des vins nature",
    "champagne & food pairing": "Accords champagne et mets",
    "burgundy masterclass": "Masterclass Bourgogne",
    "grand cru member": "Membre Grand Cru",
    "cave member": "Membre Cave",
    "sommelier member": "Membre Sommelier",
    "2 complimentary glasses/month": "Deux verres offerts par mois",
    "monthly tasting notes newsletter": "Lettre mensuelle de notes de dégustation",
    "1 curated bottle/month to keep": "Une bouteille choisie par mois, à garder",
    "4 complimentary glasses/month": "Quatre verres offerts par mois",
    "priority event reservation": "Réservation prioritaire aux événements",
    "quarterly sommelier consultation": "Rendez-vous sommelier chaque trimestre",
    "cellar storage (12 bottles)": "Garde en cave (12 bouteilles)",
    "birthday bottle gift": "Bouteille offerte pour votre anniversaire",
    "3 curated prestige bottles/month": "Trois bouteilles de prestige choisies chaque mois",
    "unlimited complimentary pours": "Verres offerts sans limite",
    "annual en primeur allocation": "Allocation annuelle en primeur",
    "unlimited cellar storage": "Garde en cave sans limite",
    "airport lounge wine gift kit": "Coffret vin pour vos voyages",
    "natural selection": "Vins nature",
    "15 jun": "15 juin",
    "22 jun": "22 juin",
    "6 jul": "6 juillet",
    "20 jul": "20 juillet",
    "left bank cabernet-forward blends with profound structure and cellaring potential.": "Assemblages de la rive gauche menés par le cabernet : structure profonde, belle aptitude à la garde.",
    "sangiovese-based wines from chianti classico and brunello — earthy, bold, expressive.": "Vins de sangiovese du Chianti Classico et du Brunello — terriens, francs, expressifs.",
    "tempranillo from spain's rioja alongside our curated natural wine selection.": "Tempranillo de la Rioja, aux côtés de notre sélection de vins nature.",
    "claire spent a decade as a buyer for a michelin three-star in lyon before dedicating herself to a single vision: a wine bar where the story of every bottle is told with care.": "Elle a passé dix ans comme acheteuse pour un trois-étoiles lyonnais avant de se consacrer à une seule idée : un bar à vin où l'histoire de chaque bouteille se raconte avec soin.",
    ", she or one of her carefully trained team guides guests through the language of terroir, vintage, and winemaker intention — making every glass a conversation.": ", elle ou l'un de ses sommeliers guide les convives dans la langue du terroir, du millésime et de l'intention du vigneron — et chaque verre devient une conversation.",
    "clos du soir is where i celebrate everything that matters. the sommelier team's knowledge and warmth make every visit feel like coming home — only with better wine.": "C'est ici que je fête tout ce qui compte. Le savoir et la chaleur de l'équipe donnent, à chaque visite, l'impression de rentrer chez soi — avec de meilleurs vins.",
    "member welcome kit": "Coffret de bienvenue adhérent",
    "10% off all bottles & events": "10 % de réduction sur toutes les bouteilles et événements",
    "15% off all purchases": "15 % sur tous les achats",
    "are private events possible?": "Des événements privés sont-ils possibles ?",
    "can i purchase bottles to take home?": "Puis-je acheter des bouteilles à emporter ?",
    "curated from the world's finest regions": "Sélectionné parmi les meilleures régions du monde",
    "dedicated sommelier on-call": "Sommelier dédié à votre disposition",
    "do i need wine knowledge to visit or join?": "Ai-je besoin de connaissances en vin pour visiter ou rejoindre ?",
    "early access to events": "Accès anticipé aux événements",
    "exclusive members-only events": "Événements exclusifs réservés aux membres",
    "for the connoisseur": "Pour les connaisseurs",
    "for the curious": "Pour les curieux",
    "for the devoted": "Pour les fidèles",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champagnes de producteurs associés à de fins fromages et charcuterie par le Chef Dupont.",
    "how do i pause or cancel my membership?": "Comment puis-je mettre en pause ou annuler mon adhésion ?",
    "how does cellar storage work for sommelier and grand cru members?": "Comment fonctionne le stockage en cave pour les membres Sommelier et Grand Cru ?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Je me suis inscrit sans rien savoir sur le vin. Douze mois plus tard, je mets en cave des bouteilles avec confiance. L'éducation est intégrée dans chaque expérience ici.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Vins à faible intervention de petits producteurs en France, en Espagne et en Géorgie.",
    "master of wine": "Maître de Vin",
    "membership unlocks privileges, curated bottles, and a community of like-minded enthusiasts.": "L'adhésion débloque des privilèges, des bouteilles sélectionnées et une communauté d'enthousiastes partageant les mêmes idées.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "Les adhésions peuvent être mises en pause une fois par an pendant jusqu'à 2 mois. L'annulation nécessite un préavis de 30 jours. Nous traitons tout de manière transparente — sans pénalités.",
    "our 280-reference cellar is personally curated by head sommelier claire vidal mw. updated seasonally with small-production gems.": "Notre cave de 280 références est personnellement sélectionnée par la Chef Sommelier Claire Vidal MW. Mise à jour saisonnière avec des pépites de petites productions.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot noir et chardonnay de la Côte-d'Or — le cœur spirituel du vin français.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "La sélection mensuelle de bouteilles est extraordinaire. Ils ont trouvé un Barolo que je cherchais depuis trois ans — livré chez moi avec des notes de dégustation manuscrites.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Dégustation verticale de Gevrey-Chambertin sur trois millésimes avec Marie-Hélène Fabre MW.",
    "what food is served?": "Quelle nourriture est servie ?",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "guided by claire vidal,": "Bajo la dirección de Claire Vidal,",
    "each evening at": "Cada noche en",
    "bordeaux grands crus evening": "Velada de grandes crus de Burdeos",
    "6 wines including two 2016 first growths, guided by maison bourgeois.": "Seis vinos, dos de ellos primeros crus de 2016, comentados por la Maison Bourgeois.",
    "natural wine discovery night": "Velada de descubrimiento de vinos naturales",
    "champagne & food pairing": "Maridaje de champán y platos",
    "burgundy masterclass": "Clase magistral de Borgoña",
    "grand cru member": "Socio Grand Cru",
    "cave member": "Socio Cave",
    "sommelier member": "Socio Sommelier",
    "2 complimentary glasses/month": "Dos copas de cortesía al mes",
    "monthly tasting notes newsletter": "Boletín mensual de notas de cata",
    "1 curated bottle/month to keep": "Una botella seleccionada al mes, para quedársela",
    "4 complimentary glasses/month": "Cuatro copas de cortesía al mes",
    "priority event reservation": "Reserva prioritaria en los eventos",
    "quarterly sommelier consultation": "Consulta con el sumiller cada trimestre",
    "cellar storage (12 bottles)": "Guarda en bodega (12 botellas)",
    "birthday bottle gift": "Botella de regalo por su cumpleaños",
    "3 curated prestige bottles/month": "Tres botellas de prestigio seleccionadas cada mes",
    "unlimited complimentary pours": "Copas de cortesía sin límite",
    "annual en primeur allocation": "Asignación anual en primeur",
    "unlimited cellar storage": "Guarda en bodega sin límite",
    "airport lounge wine gift kit": "Estuche de vino para sus viajes",
    "natural selection": "Vinos naturales",
    "15 jun": "15 jun",
    "22 jun": "22 jun",
    "6 jul": "6 jul",
    "20 jul": "20 jul",
    "left bank cabernet-forward blends with profound structure and cellaring potential.": "Ensamblajes de la orilla izquierda liderados por el cabernet: estructura profunda y gran aptitud para la guarda.",
    "sangiovese-based wines from chianti classico and brunello — earthy, bold, expressive.": "Vinos de sangiovese del Chianti Classico y del Brunello — terrosos, francos, expresivos.",
    "tempranillo from spain's rioja alongside our curated natural wine selection.": "Tempranillo de La Rioja, junto a nuestra selección de vinos naturales.",
    "claire spent a decade as a buyer for a michelin three-star in lyon before dedicating herself to a single vision: a wine bar where the story of every bottle is told with care.": "Pasó diez años como compradora para un tres estrellas de Lyon antes de dedicarse a una sola idea: un bar de vinos donde la historia de cada botella se cuenta con cuidado.",
    ", she or one of her carefully trained team guides guests through the language of terroir, vintage, and winemaker intention — making every glass a conversation.": ", ella o uno de sus sumilleres guía a los comensales por el lenguaje del terruño, la añada y la intención del viticultor — y cada copa se vuelve una conversación.",
    "clos du soir is where i celebrate everything that matters. the sommelier team's knowledge and warmth make every visit feel like coming home — only with better wine.": "Es aquí donde celebro todo lo que importa. El saber y la calidez del equipo hacen que cada visita sea como volver a casa — con mejores vinos.",
    "member welcome kit": "Kit de bienvenida para socios",
    "10% off all bottles & events": "10 % de descuento en todas las botellas y eventos",
    "15% off all purchases": "15 % en todas las compras",
    "are private events possible?": "¿Son posibles eventos privados?",
    "can i purchase bottles to take home?": "¿Puedo comprar botellas para llevar a casa?",
    "curated from the world's finest regions": "Seleccionado de las mejores regiones del mundo",
    "dedicated sommelier on-call": "Sumiller dedicado a su disposición",
    "do i need wine knowledge to visit or join?": "¿Necesito conocimientos sobre vino para visitar o unirme?",
    "early access to events": "Acceso anticipado a eventos",
    "exclusive members-only events": "Eventos exclusivos solo para miembros",
    "for the connoisseur": "Para los entendidos",
    "for the curious": "Para los curiosos",
    "for the devoted": "Para los fieles",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champagnes de productores combinados con finos quesos y charcutería por el Chef Dupont.",
    "how do i pause or cancel my membership?": "¿Cómo puedo pausar o cancelar mi membresía?",
    "how does cellar storage work for sommelier and grand cru members?": "¿Cómo funciona el almacenamiento en bodega para los miembros Sommelier y Grand Cru?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Me uní sin saber nada de vino. Doce meses después, estoy almacenando botellas con confianza. La educación está integrada en cada experiencia aquí.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Vinos de baja intervención de pequeños productores en Francia, España y Georgia.",
    "master of wine": "Maestro de Vino",
    "membership unlocks privileges, curated bottles, and a community of like-minded enthusiasts.": "La membresía desbloquea privilegios, botellas seleccionadas y una comunidad de entusiastas afines.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "Las membresías se pueden pausar una vez al año por hasta 2 meses. La cancelación requiere un aviso de 30 días. Procesamos todo sin problemas — sin penalizaciones.",
    "our 280-reference cellar is personally curated by head sommelier claire vidal mw. updated seasonally with small-production gems.": "Nuestra bodega de 280 referencias es seleccionada personalmente por la Jefa de Sumilleres Claire Vidal MW. Actualizada estacionalmente con joyas de pequeñas producciones.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot noir y chardonnay de la Côte-d'Or, el corazón espiritual del vino francés.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "La curaduría mensual de botellas es extraordinaria. Encontraron un Barolo que había estado buscando durante tres años — entregado en mi casa con notas de cata escritas a mano.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Cata vertical de Gevrey-Chambertin a través de tres cosechas con Marie-Hélène Fabre MW.",
    "what food is served?": "¿Qué comida se sirve?",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "guided by claire vidal,": "Unter der Leitung von Claire Vidal,",
    "each evening at": "Jeden Abend im",
    "bordeaux grands crus evening": "Abend der Bordeaux-Grands-Crus",
    "6 wines including two 2016 first growths, guided by maison bourgeois.": "Sechs Weine, darunter zwei Premiers Crus von 2016, kommentiert von der Maison Bourgeois.",
    "natural wine discovery night": "Entdeckungsabend Naturweine",
    "champagne & food pairing": "Champagner und Speisen im Einklang",
    "burgundy masterclass": "Masterclass Burgund",
    "grand cru member": "Grand-Cru-Mitglied",
    "cave member": "Cave-Mitglied",
    "sommelier member": "Sommelier-Mitglied",
    "2 complimentary glasses/month": "Zwei Gläser gratis pro Monat",
    "monthly tasting notes newsletter": "Monatlicher Newsletter mit Verkostungsnotizen",
    "1 curated bottle/month to keep": "Eine ausgewählte Flasche pro Monat, zum Behalten",
    "4 complimentary glasses/month": "Vier Gläser gratis pro Monat",
    "priority event reservation": "Vorrangige Buchung von Veranstaltungen",
    "quarterly sommelier consultation": "Sommelier-Beratung jedes Quartal",
    "cellar storage (12 bottles)": "Kellerlagerung (12 Flaschen)",
    "birthday bottle gift": "Geburtstagsflasche geschenkt",
    "3 curated prestige bottles/month": "Drei ausgewählte Prestigeflaschen pro Monat",
    "unlimited complimentary pours": "Unbegrenzt Gläser gratis",
    "annual en primeur allocation": "Jährliche En-primeur-Zuteilung",
    "unlimited cellar storage": "Unbegrenzte Kellerlagerung",
    "airport lounge wine gift kit": "Wein-Geschenkset für Ihre Reisen",
    "natural selection": "Naturweine",
    "15 jun": "15. Juni",
    "22 jun": "22. Juni",
    "6 jul": "6. Juli",
    "20 jul": "20. Juli",
    "left bank cabernet-forward blends with profound structure and cellaring potential.": "Cabernet-geführte Cuvées vom linken Ufer: tiefe Struktur, großes Lagerpotenzial.",
    "sangiovese-based wines from chianti classico and brunello — earthy, bold, expressive.": "Sangiovese-Weine aus Chianti Classico und Brunello — erdig, kräftig, ausdrucksstark.",
    "tempranillo from spain's rioja alongside our curated natural wine selection.": "Tempranillo aus der Rioja, dazu unsere Auswahl an Naturweinen.",
    "claire spent a decade as a buyer for a michelin three-star in lyon before dedicating herself to a single vision: a wine bar where the story of every bottle is told with care.": "Sie war zehn Jahre Einkäuferin für ein Drei-Sterne-Haus in Lyon, bevor sie sich einer einzigen Idee widmete: einer Weinbar, in der die Geschichte jeder Flasche sorgfältig erzählt wird.",
    ", she or one of her carefully trained team guides guests through the language of terroir, vintage, and winemaker intention — making every glass a conversation.": ", führen sie oder einer ihrer Sommeliers die Gäste durch die Sprache von Terroir, Jahrgang und Winzerabsicht — und jedes Glas wird zum Gespräch.",
    "clos du soir is where i celebrate everything that matters. the sommelier team's knowledge and warmth make every visit feel like coming home — only with better wine.": "Hier feiere ich alles, was zählt. Wissen und Wärme des Teams lassen jeden Besuch wie ein Nachhausekommen wirken — nur mit besserem Wein.",
    "member welcome kit": "Willkommenspaket für Mitglieder",
    "10% off all bottles & events": "10 % Rabatt auf alle Flaschen und Veranstaltungen",
    "15% off all purchases": "15 % auf alle Einkäufe",
    "are private events possible?": "Sind private Veranstaltungen möglich?",
    "can i purchase bottles to take home?": "Kann ich Flaschen zum Mitnehmen kaufen?",
    "curated from the world's finest regions": "Aus den besten Regionen der Welt kuratiert",
    "dedicated sommelier on-call": "Dedizierter Sommelier auf Abruf",
    "do i need wine knowledge to visit or join?": "Brauche ich Weinwissen, um zu besuchen oder beizutreten?",
    "early access to events": "Früher Zugang zu Veranstaltungen",
    "exclusive members-only events": "Exklusive Veranstaltungen nur für Mitglieder",
    "for the connoisseur": "Für Kenner",
    "for the curious": "Für die Neugierigen",
    "for the devoted": "Für die Treuen",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champagner von Erzeugern kombiniert mit feinem Käse und Charcuterie von Chef Dupont.",
    "how do i pause or cancel my membership?": "Wie kann ich meine Mitgliedschaft pausieren oder kündigen?",
    "how does cellar storage work for sommelier and grand cru members?": "Wie funktioniert die Lagerung im Keller für Sommelier- und Grand Cru-Mitglieder?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Ich trat bei, ohne etwas über Wein zu wissen. Zwölf Monate später lagere ich mit Vertrauen Flaschen. Die Ausbildung ist in jeder Erfahrung hier eingebettet.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Niedrigintervention Weine von kleinen Produzenten in Frankreich, Spanien und Georgien.",
    "master of wine": "Master of Wine",
    "membership unlocks privileges, curated bottles, and a community of like-minded enthusiasts.": "Die Mitgliedschaft schaltet Privilegien, kuratierte Flaschen und eine Gemeinschaft gleichgesinnter Enthusiasten frei.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "Mitgliedschaften können einmal im Jahr für bis zu 2 Monate pausiert werden. Die Kündigung erfordert eine Frist von 30 Tagen. Wir bearbeiten alles nahtlos — keine Strafen.",
    "our 280-reference cellar is personally curated by head sommelier claire vidal mw. updated seasonally with small-production gems.": "Unser Weinkeller mit 280 Referenzen wird persönlich von der Chef-Sommelière Claire Vidal MW kuratiert. Saisonale Aktualisierung mit kleinen Produktionsjuwelen.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot Noir und Chardonnay von der Côte-d'Or — dem geistigen Herzen des französischen Weins.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "Die monatliche Flaschenkuration ist außergewöhnlich. Sie haben einen Barolo beschafft, nach dem ich drei Jahre lang gesucht habe — direkt zu mir nach Hause mit handgeschriebenen Verkostungsnotizen.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Vertikale Verkostung von Gevrey-Chambertin über drei Jahrgänge mit Marie-Hélène Fabre MW.",
    "what food is served?": "Welche Speisen werden serviert?",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "guided by claire vidal,": "Sob a direção de Claire Vidal,",
    "each evening at": "Todas as noites no",
    "bordeaux grands crus evening": "Noite de grandes crus de Bordéus",
    "6 wines including two 2016 first growths, guided by maison bourgeois.": "Seis vinhos, dois deles primeiros crus de 2016, comentados pela Maison Bourgeois.",
    "natural wine discovery night": "Noite de descoberta de vinhos naturais",
    "champagne & food pairing": "Harmonização champanhe e pratos",
    "burgundy masterclass": "Masterclass Borgonha",
    "grand cru member": "Sócio Grand Cru",
    "cave member": "Sócio Cave",
    "sommelier member": "Sócio Sommelier",
    "2 complimentary glasses/month": "Dois copos oferecidos por mês",
    "monthly tasting notes newsletter": "Boletim mensal de notas de prova",
    "1 curated bottle/month to keep": "Uma garrafa selecionada por mês, para guardar",
    "4 complimentary glasses/month": "Quatro copos oferecidos por mês",
    "priority event reservation": "Reserva prioritária nos eventos",
    "quarterly sommelier consultation": "Consulta com o escanção a cada trimestre",
    "cellar storage (12 bottles)": "Guarda em adega (12 garrafas)",
    "birthday bottle gift": "Garrafa oferecida no seu aniversário",
    "3 curated prestige bottles/month": "Três garrafas de prestígio selecionadas por mês",
    "unlimited complimentary pours": "Copos oferecidos sem limite",
    "annual en primeur allocation": "Alocação anual en primeur",
    "unlimited cellar storage": "Guarda em adega sem limite",
    "airport lounge wine gift kit": "Estojo de vinho para as suas viagens",
    "natural selection": "Vinhos naturais",
    "15 jun": "15 jun",
    "22 jun": "22 jun",
    "6 jul": "6 jul",
    "20 jul": "20 jul",
    "left bank cabernet-forward blends with profound structure and cellaring potential.": "Lotes da margem esquerda liderados pelo cabernet: estrutura profunda e boa aptidão para guarda.",
    "sangiovese-based wines from chianti classico and brunello — earthy, bold, expressive.": "Vinhos de sangiovese do Chianti Classico e do Brunello — terrosos, francos, expressivos.",
    "tempranillo from spain's rioja alongside our curated natural wine selection.": "Tempranillo da Rioja, ao lado da nossa seleção de vinhos naturais.",
    "claire spent a decade as a buyer for a michelin three-star in lyon before dedicating herself to a single vision: a wine bar where the story of every bottle is told with care.": "Passou dez anos como compradora para um três estrelas em Lyon antes de se dedicar a uma só ideia: um bar de vinhos onde a história de cada garrafa se conta com cuidado.",
    ", she or one of her carefully trained team guides guests through the language of terroir, vintage, and winemaker intention — making every glass a conversation.": ", ela ou um dos seus escanções guia os clientes pela linguagem do terroir, da colheita e da intenção do produtor — e cada copo torna-se uma conversa.",
    "clos du soir is where i celebrate everything that matters. the sommelier team's knowledge and warmth make every visit feel like coming home — only with better wine.": "É aqui que celebro tudo o que conta. O saber e o calor da equipa fazem de cada visita um regresso a casa — com melhores vinhos.",
    "member welcome kit": "Kit de boas-vindas para sócios",
    "10% off all bottles & events": "10 % de desconto em todas as garrafas e eventos",
    "15% off all purchases": "15 % em todas as compras",
    "are private events possible?": "São possíveis eventos privados?",
    "can i purchase bottles to take home?": "Posso comprar garrafas para levar para casa?",
    "curated from the world's finest regions": "Selecionado das melhores regiões do mundo",
    "dedicated sommelier on-call": "Sommelier dedicado à disposição",
    "do i need wine knowledge to visit or join?": "Preciso de conhecimentos sobre vinho para visitar ou aderir?",
    "early access to events": "Acesso antecipado a eventos",
    "exclusive members-only events": "Eventos exclusivos apenas para membros",
    "for the connoisseur": "Para os entendidos",
    "for the curious": "Para os curiosos",
    "for the devoted": "Para os fiéis",
    "grower champagnes paired with fine fromage and charcuterie by chef dupont.": "Champanhes de produtores emparelhados com queijos finos e charcutaria pelo Chef Dupont.",
    "how do i pause or cancel my membership?": "Como posso pausar ou cancelar a minha adesão?",
    "how does cellar storage work for sommelier and grand cru members?": "Como funciona o armazenamento na adega para membros Sommelier e Grand Cru?",
    "i joined knowing nothing about wine. twelve months later i'm cellaring bottles with confidence. the education is embedded in every experience here.": "Entrei sem saber nada sobre vinho. Doze meses depois, estou a armazenar garrafas com confiança. A educação está incorporada em cada experiência aqui.",
    "low-intervention wines from small producers in france, spain, and georgia.": "Vinhos de baixa intervenção de pequenos produtores em França, Espanha e Geórgia.",
    "master of wine": "Mestre de Vinho",
    "membership unlocks privileges, curated bottles, and a community of like-minded enthusiasts.": "A adesão desbloqueia privilégios, garrafas selecionadas e uma comunidade de entusiastas com ideias semelhantes.",
    "memberships can be paused once per year for up to 2 months. cancellation requires 30 days notice. we process everything seamlessly — no penalties.": "As adesões podem ser pausadas uma vez por ano por até 2 meses. O cancelamento requer um aviso de 30 dias. Processamos tudo de forma fluida — sem penalizações.",
    "our 280-reference cellar is personally curated by head sommelier claire vidal mw. updated seasonally with small-production gems.": "A nossa adega de 280 referências é pessoalmente selecionada pela Chefe Sommelier Claire Vidal MW. Atualizada sazonalmente com pequenas produções.",
    "pinot noir and chardonnay from the cote d'or — the spiritual heart of french wine.": "Pinot noir e chardonnay da Côte-d'Or — o coração espiritual do vinho francês.",
    "the monthly bottle curation is extraordinary. they sourced a barolo i'd been searching for three years — delivered to my home with handwritten tasting notes.": "A curadoria mensal de garrafas é extraordinária. Eles encontraram um Barolo que eu procurava há três anos — entregue em minha casa com notas de prova escritas à mão.",
    "vertical tasting of gevrey-chambertin across three vintages with marie-helene fabre mw.": "Prova vertical de Gevrey-Chambertin em três colheitas com Marie-Hélène Fabre MW.",
    "what food is served?": "Que comida é servida?",
  },
};
