/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "brands that": "Des marques qui",
    "shift": "déplacent",
    "perception.": "le regard.",
    "we build identity systems for ambitious companies — from seed-stage startups to century-old maisons. strategy, visual identity, and art direction that makes the right people stop scrolling.": "Nous construisons des systèmes d'identité pour des entreprises ambitieuses — de la jeune pousse à la maison centenaire. Stratégie, identité visuelle et direction artistique : de quoi arrêter le bon regard.",
    "12 countries": "12 pays",
    "orbit home": "Accueil",
    "about orbit": "À propos",
    "art direction for the launch of ovoid's clean beauty line. sensory, scientific, unmistakably feminine.": "Direction artistique pour le lancement de la ligne de beauté propre d'Ovoid. Sensoriel, scientifique, indéniablement féminin.",
    "average client growth yoy": "Croissance moyenne des clients d'une année sur l'autre",
    "brand story": "Histoire de la marque",
    "campaign concepting, editorial systems, and production oversight for brand moments that have to land perfectly.": "Conception de campagne, systèmes éditoriaux et suivi de production, pour les moments de marque qui ne peuvent pas rater.",
    "campaign concepts, visual worlds, and creative direction for shoots, launches, and brand campaigns that live long after the brief.": "Concepts de campagne, mondes visuels et direction créative pour des séances photo, des lancements et des campagnes de marque qui perdurent longtemps après le brief.",
    "can we own all files and assets after delivery?": "Pouvons-nous posséder tous les fichiers et actifs après la livraison ?",
    "client capital raised": "Capitaux levés par les clients",
    "complete identity overhaul for a luxury spirits house entering european markets. dark, confident, built to age.": "Refonte complète de l'identité pour une maison de spiritueux de luxe entrant sur les marchés européens. Sombre, confiante, conçue pour vieillir.",
    "comprehensive brand guidelines, all master files, asset libraries, and a handover session. everything you need to carry the brand forward.": "Directives de marque complètes, tous les fichiers maîtres, bibliothèques d'actifs et une session de passation. Tout ce dont vous avez besoin pour faire avancer la marque.",
    "digital experience for the brutalist architecture studio behind the prix d'architecture 2024 laureate.": "Expérience numérique pour le studio d'architecture brutaliste derrière le lauréat du Prix d'Architecture 2024.",
    "do you offer retainer arrangements after project delivery?": "Proposez-vous des arrangements de rétention après la livraison du projet ?",
    "do you work with early-stage startups or only established companies?": "Travaillez-vous avec des startups en phase de démarrage ou uniquement avec des entreprises établies ?",
    "full brand system and launch campaign for a dtc athletic brand hitting €1.2m gmv in month one.": "Système de marque complet et campagne de lancement pour une marque athlétique DTC atteignant 1,2 M€ de GMV au cours du premier mois.",
    "head of strategy": "Responsable de la stratégie",
    "how do you handle confidential work during the nda period?": "Comment gérez-vous le travail confidentiel pendant la période de NDA ?",
    "how long does a full brand identity project take?": "Combien de temps dure un projet d'identité de marque complet ?",
    "how we do it.": "comment nous procédons.",
    "let's make": "Faisons",
    "logo, type system, color, motion principles, and brand guidelines that hold up from a business card to a stadium banner.": "Logo, système typographique, couleur, principes de mouvement et directives de marque qui tiennent de la carte de visite à la bannière de stade.",
    "motion identity, web design systems, social template libraries, and digital touchpoints engineered for the screens your audience lives on.": "Identité de mouvement, systèmes de design web, bibliothèques de modèles sociaux et points de contact numériques conçus pour les écrans sur lesquels votre public vit.",
    "multi-brand and sub-brand hierarchies that scale without cannibalizing. built for acquirers and acquirees alike.": "Hiérarchies de marques multiples et de sous-marques qui se développent sans cannibaliser. Construit pour les acquéreurs et les cédants.",
    "new brief": "Nouveau projet",
    "one chosen direction, refined through two rounds of structured feedback. precision over iteration — we move forward, not in circles.": "Une direction choisie, affinée à travers deux tours de retours structurés. Précision plutôt qu'itération — nous avançons, pas en rond.",
    "orbit didn't just design a logo — they built us a world. every touchpoint now feels intentional. distributors stop us at every trade show to ask who did it.": "Orbit n'a pas seulement conçu un logo — ils nous ont construit un monde. Chaque point de contact semble maintenant intentionnel. Les distributeurs nous arrêtent à chaque salon pour demander qui l'a fait.",
    "packaging design": "Conception d'emballage",
    "positioning territory, naming (if needed), brand pillars, and the core narrative. everything downstream traces back to this document.": "Territoire de positionnement, nommage (si nécessaire), piliers de marque et narration centrale. Tout ce qui suit renvoie à ce document.",
    "positioning, naming, messaging architecture, and competitive landscaping. we build the logic before the aesthetics.": "Positionnement, nom, architecture du discours, cartographie concurrentielle. Nous posons la logique avant l'esthétique.",
    "positioning, naming, narrative, and competitive architecture. we find the single idea your brand should own — then build everything from it.": "Positionnement, nommage, narration et architecture concurrentielle. Nous trouvons l'idée unique que votre marque doit posséder — puis construisons tout à partir de cela.",
    "repositioning a 3rd-generation french maison as a modern luxury atelier without losing its heritage roots.": "Repositionnement d'une maison française de 3ème génération en tant qu'atelier de luxe moderne sans perdre ses racines patrimoniales.",
    "retail presence that earns shelf space. we design for attention at 2 meters and delight at 20 centimeters.": "Présence en magasin qui mérite de l'espace sur les étagères. Nous concevons pour attirer l'attention à 2 mètres et ravir à 20 centimètres.",
    "revenue multiple": "Multiple de revenus",
    "see all projects": "Voir tous les projets",
    "strategic rebrand for a cleantech startup pre-series b. built trust, signaled ambition, closed the round.": "Rebranding stratégique pour une startup cleantech avant la Série B. Confiance établie, ambition signalée, tour de table clôturée.",
    "the rebrand was the catalyst for our series b. investors told us directly — the identity signaled we were serious. that's the roi of great brand work.": "Le rebranding a été le catalyseur de notre Série B. Les investisseurs nous l'ont dit directement — l'identité a signalé que nous étions sérieux. C'est le retour sur investissement d'un excellent travail de marque.",
    "three creative directions, each fully resolved. no half-baked moodboards — real systems you can evaluate in context.": "Trois directions créatives, chacune entièrement résolue. Pas de moodboards à moitié cuits — de vrais systèmes que vous pouvez évaluer dans le contexte.",
    "view our work": "Voir nos réalisations",
    "we take on 6 projects per quarter. if your brief has ambition and your deadline has adrenaline, we want to hear it.": "Nous prenons 6 projets par trimestre. Si votre brief a de l'ambition et que votre délai a de l'adrénaline, nous voulons l'entendre.",
    "web design": "Conception Web",
    "websites and interactive platforms that convert intent. performance-first, scroll-driven, and designed to be remembered.": "Des sites et des plateformes qui transforment l'intention. Performance d'abord, conçus pour marquer.",
    "what makes orbit different from a freelancer or a large agency?": "Qu'est-ce qui rend Orbit différent d'un freelance ou d'une grande agence ?",
    "wordmarks, symbol systems, color architecture, and type hierarchies that telegraph exactly who you are before a single word is read.": "Logotypes, systèmes de symboles, architecture des couleurs et hiérarchies typographiques qui transmettent exactement qui vous êtes avant qu'un seul mot ne soit lu.",
  },
  es: {
    "brands that": "Marcas que",
    "shift": "cambian",
    "perception.": "la mirada.",
    "we build identity systems for ambitious companies — from seed-stage startups to century-old maisons. strategy, visual identity, and art direction that makes the right people stop scrolling.": "Construimos sistemas de identidad para empresas ambiciosas — desde la startup hasta la casa centenaria. Estrategia, identidad visual y dirección artística: lo justo para detener la mirada adecuada.",
    "12 countries": "12 países",
    "orbit home": "Inicio",
    "about orbit": "Sobre nosotros",
    "art direction for the launch of ovoid's clean beauty line. sensory, scientific, unmistakably feminine.": "Dirección de arte para el lanzamiento de la línea de belleza limpia de Ovoid. Sensorial, científica, inconfundiblemente femenina.",
    "average client growth yoy": "Crecimiento promedio de clientes año tras año",
    "brand story": "Historia de la marca",
    "campaign concepting, editorial systems, and production oversight for brand moments that have to land perfectly.": "Concepción de campaña, sistemas editoriales y seguimiento de producción, para los momentos de marca que no pueden fallar.",
    "campaign concepts, visual worlds, and creative direction for shoots, launches, and brand campaigns that live long after the brief.": "Conceptos de campaña, mundos visuales y dirección creativa para sesiones de fotos, lanzamientos y campañas de marca que perduran mucho después del brief.",
    "can we own all files and assets after delivery?": "¿Podemos poseer todos los archivos y activos después de la entrega?",
    "client capital raised": "Capital recaudado por clientes",
    "complete identity overhaul for a luxury spirits house entering european markets. dark, confident, built to age.": "Reforma completa de la identidad para una casa de licores de lujo que entra en los mercados europeos. Oscura, segura, diseñada para envejecer.",
    "comprehensive brand guidelines, all master files, asset libraries, and a handover session. everything you need to carry the brand forward.": "Guías de marca completas, todos los archivos maestros, bibliotecas de activos y una sesión de entrega. Todo lo que necesitas para llevar la marca hacia adelante.",
    "digital experience for the brutalist architecture studio behind the prix d'architecture 2024 laureate.": "Experiencia digital para el estudio de arquitectura brutalista detrás del laureado del Prix d'Architecture 2024.",
    "do you offer retainer arrangements after project delivery?": "¿Ofrecen acuerdos de retención después de la entrega del proyecto?",
    "do you work with early-stage startups or only established companies?": "¿Trabajan con startups en etapa temprana o solo con empresas establecidas?",
    "full brand system and launch campaign for a dtc athletic brand hitting €1.2m gmv in month one.": "Sistema de marca completo y campaña de lanzamiento para una marca atlética DTC que alcanza 1,2 M€ de GMV en el primer mes.",
    "head of strategy": "Jefe de Estrategia",
    "how do you handle confidential work during the nda period?": "¿Cómo manejan el trabajo confidencial durante el período de NDA?",
    "how long does a full brand identity project take?": "¿Cuánto tiempo lleva un proyecto de identidad de marca completo?",
    "how we do it.": "cómo lo hacemos.",
    "let's make": "Hagamos",
    "logo, type system, color, motion principles, and brand guidelines that hold up from a business card to a stadium banner.": "Logotipo, sistema tipográfico, color, principios de movimiento y directrices de marca que se mantienen desde una tarjeta de visita hasta una pancarta de estadio.",
    "motion identity, web design systems, social template libraries, and digital touchpoints engineered for the screens your audience lives on.": "Identidad en movimiento, sistemas de diseño web, bibliotecas de plantillas sociales y puntos de contacto digitales diseñados para las pantallas en las que vive tu audiencia.",
    "multi-brand and sub-brand hierarchies that scale without cannibalizing. built for acquirers and acquirees alike.": "Jerarquías de marcas múltiples y sub-marcas que escalan sin canibalizar. Construido para adquirentes y adquiridos por igual.",
    "new brief": "Nuevo proyecto",
    "one chosen direction, refined through two rounds of structured feedback. precision over iteration — we move forward, not in circles.": "Una dirección elegida, refinada a través de dos rondas de retroalimentación estructurada. Precisión sobre iteración: avanzamos, no damos vueltas.",
    "orbit didn't just design a logo — they built us a world. every touchpoint now feels intentional. distributors stop us at every trade show to ask who did it.": "Orbit no solo diseñó un logo: nos construyeron un mundo. Cada punto de contacto ahora se siente intencional. Los distribuidores nos detienen en cada feria comercial para preguntar quién lo hizo.",
    "packaging design": "Diseño de envases",
    "positioning territory, naming (if needed), brand pillars, and the core narrative. everything downstream traces back to this document.": "Territorio de posicionamiento, nombramiento (si es necesario), pilares de marca y narrativa central. Todo lo que sigue se remonta a este documento.",
    "positioning, naming, messaging architecture, and competitive landscaping. we build the logic before the aesthetics.": "Posicionamiento, nombre, arquitectura del discurso, mapa competitivo. Ponemos la lógica antes que la estética.",
    "positioning, naming, narrative, and competitive architecture. we find the single idea your brand should own — then build everything from it.": "Posicionamiento, nombramiento, narrativa y arquitectura competitiva. Encontramos la única idea que tu marca debería poseer — luego construimos todo a partir de ella.",
    "repositioning a 3rd-generation french maison as a modern luxury atelier without losing its heritage roots.": "Reubicación de una maison francesa de 3ª generación como un atelier de lujo moderno sin perder sus raíces patrimoniales.",
    "retail presence that earns shelf space. we design for attention at 2 meters and delight at 20 centimeters.": "Presencia en el retail que gana espacio en estanterías. Diseñamos para captar la atención a 2 metros y deleitar a 20 centímetros.",
    "revenue multiple": "Múltiplo de ingresos",
    "see all projects": "Ver todos los proyectos",
    "strategic rebrand for a cleantech startup pre-series b. built trust, signaled ambition, closed the round.": "Rebranding estratégico para una startup de cleantech antes de la Serie B. Confianza construida, ambición señalada, ronda cerrada.",
    "the rebrand was the catalyst for our series b. investors told us directly — the identity signaled we were serious. that's the roi of great brand work.": "El rebranding fue el catalizador de nuestra Serie B. Los inversores nos lo dijeron directamente: la identidad señalaba que éramos serios. Ese es el ROI de un gran trabajo de marca.",
    "three creative directions, each fully resolved. no half-baked moodboards — real systems you can evaluate in context.": "Tres direcciones creativas, cada una completamente resuelta. No moodboards a medio hacer: sistemas reales que puedes evaluar en contexto.",
    "view our work": "Ver nuestros trabajos",
    "we take on 6 projects per quarter. if your brief has ambition and your deadline has adrenaline, we want to hear it.": "Asumimos 6 proyectos por trimestre. Si tu propuesta tiene ambición y tu plazo tiene adrenalina, queremos escucharlo.",
    "web design": "Diseño Web",
    "websites and interactive platforms that convert intent. performance-first, scroll-driven, and designed to be remembered.": "Sitios y plataformas que convierten la intención. Rendimiento primero, pensados para dejar huella.",
    "what makes orbit different from a freelancer or a large agency?": "¿Qué hace que Orbit sea diferente de un freelancer o de una gran agencia?",
    "wordmarks, symbol systems, color architecture, and type hierarchies that telegraph exactly who you are before a single word is read.": "Logotipos, sistemas de símbolos, arquitectura del color y jerarquías tipográficas que transmiten exactamente quién eres antes de que se lea una sola palabra.",
  },
  de: {
    "brands that": "Marken, die",
    "shift": "verschieben",
    "perception.": "den Blick.",
    "we build identity systems for ambitious companies — from seed-stage startups to century-old maisons. strategy, visual identity, and art direction that makes the right people stop scrolling.": "Wir bauen Identitätssysteme für ambitionierte Unternehmen — vom jungen Start-up bis zum hundertjährigen Haus. Strategie, visuelle Identität und Art Direction, die den richtigen Blick anhalten.",
    "12 countries": "12 Länder",
    "orbit home": "Startseite",
    "about orbit": "Über uns",
    "art direction for the launch of ovoid's clean beauty line. sensory, scientific, unmistakably feminine.": "Kunstleitung für den Launch der Clean Beauty-Linie von Ovoid. Sensorisch, wissenschaftlich, unverkennbar feminin.",
    "average client growth yoy": "Durchschnittliches Kundenwachstum im Jahresvergleich",
    "brand story": "Markengeschichte",
    "campaign concepting, editorial systems, and production oversight for brand moments that have to land perfectly.": "Kampagnenkonzept, redaktionelle Systeme und Produktionsbegleitung für Markenmomente, die sitzen müssen.",
    "campaign concepts, visual worlds, and creative direction for shoots, launches, and brand campaigns that live long after the brief.": "Kampagnenkonzepte, visuelle Welten und kreative Leitung für Shootings, Launches und Marken-Kampagnen, die lange nach dem Brief bestehen bleiben.",
    "can we own all files and assets after delivery?": "Können wir nach der Lieferung alle Dateien und Vermögenswerte besitzen?",
    "client capital raised": "Von Kunden eingesammeltes Kapital",
    "complete identity overhaul for a luxury spirits house entering european markets. dark, confident, built to age.": "Vollständige Identitätsüberarbeitung für ein Luxus-Spirituosenhaus, das in die europäischen Märkte eintritt. Dunkel, selbstbewusst, zum Altern gebaut.",
    "comprehensive brand guidelines, all master files, asset libraries, and a handover session. everything you need to carry the brand forward.": "Umfassende Markenrichtlinien, alle Masterdateien, Asset-Bibliotheken und eine Übergabesitzung. Alles, was Sie brauchen, um die Marke voranzubringen.",
    "digital experience for the brutalist architecture studio behind the prix d'architecture 2024 laureate.": "Digitale Erfahrung für das brutalistische Architekturstudio hinter dem Preisträger des Prix d'Architecture 2024.",
    "do you offer retainer arrangements after project delivery?": "Bieten Sie nach der Projektlieferung Retainer-Vereinbarungen an?",
    "do you work with early-stage startups or only established companies?": "Arbeiten Sie mit Startups in der Frühphase oder nur mit etablierten Unternehmen?",
    "full brand system and launch campaign for a dtc athletic brand hitting €1.2m gmv in month one.": "Vollständiges Markensystem und Launch-Kampagne für eine DTC-Sportmarke, die im ersten Monat 1,2 Mio. € GMV erreicht.",
    "head of strategy": "Leiter der Strategie",
    "how do you handle confidential work during the nda period?": "Wie gehen Sie während der NDA-Phase mit vertraulicher Arbeit um?",
    "how long does a full brand identity project take?": "Wie lange dauert ein vollständiges Markenidentitätsprojekt?",
    "how we do it.": "wie wir vorgehen.",
    "let's make": "Lass uns machen",
    "logo, type system, color, motion principles, and brand guidelines that hold up from a business card to a stadium banner.": "Logo, Schriftsystem, Farbe, Bewegungsprinzipien und Markenrichtlinien, die von der Visitenkarte bis zum Stadionbanner bestehen.",
    "motion identity, web design systems, social template libraries, and digital touchpoints engineered for the screens your audience lives on.": "Bewegungsidentität, Webdesignsysteme, soziale Vorlagenbibliotheken und digitale Touchpoints, die für die Bildschirme entwickelt wurden, auf denen Ihr Publikum lebt.",
    "multi-brand and sub-brand hierarchies that scale without cannibalizing. built for acquirers and acquirees alike.": "Multi-Marken- und Submarkenhierarchien, die ohne Kannibalisierung skalieren. Entwickelt für Erwerber und Übertragene gleichermaßen.",
    "new brief": "Neues Briefing",
    "one chosen direction, refined through two rounds of structured feedback. precision over iteration — we move forward, not in circles.": "Eine gewählte Richtung, die durch zwei Runden strukturiertes Feedback verfeinert wurde. Präzision über Iteration — wir bewegen uns vorwärts, nicht im Kreis.",
    "orbit didn't just design a logo — they built us a world. every touchpoint now feels intentional. distributors stop us at every trade show to ask who did it.": "Orbit hat nicht nur ein Logo entworfen — sie haben uns eine Welt gebaut. Jeder Berührungspunkt fühlt sich jetzt absichtlich an. Distributoren halten uns auf jeder Messe an, um zu fragen, wer es gemacht hat.",
    "packaging design": "Verpackungsdesign",
    "positioning territory, naming (if needed), brand pillars, and the core narrative. everything downstream traces back to this document.": "Positionierungsgebiet, Benennung (falls erforderlich), Markenpfeiler und die zentrale Erzählung. Alles, was folgt, führt auf dieses Dokument zurück.",
    "positioning, naming, messaging architecture, and competitive landscaping. we build the logic before the aesthetics.": "Positionierung, Namensfindung, Botschaftsarchitektur, Wettbewerbsanalyse. Wir bauen die Logik vor der Ästhetik.",
    "positioning, naming, narrative, and competitive architecture. we find the single idea your brand should own — then build everything from it.": "Positionierung, Benennung, Erzählung und Wettbewerbsarchitektur. Wir finden die eine Idee, die Ihre Marke besitzen sollte – und bauen dann alles darauf auf.",
    "repositioning a 3rd-generation french maison as a modern luxury atelier without losing its heritage roots.": "Repositionierung eines französischen Hauses der 3. Generation als modernes Luxusatelier, ohne die Wurzeln des Erbes zu verlieren.",
    "retail presence that earns shelf space. we design for attention at 2 meters and delight at 20 centimeters.": "Einzelhandelspräsenz, die Regalplatz verdient. Wir gestalten für Aufmerksamkeit in 2 Metern und Freude in 20 Zentimetern.",
    "revenue multiple": "Umsatzmultiple",
    "see all projects": "Alle Projekte ansehen",
    "strategic rebrand for a cleantech startup pre-series b. built trust, signaled ambition, closed the round.": "Strategisches Rebranding für ein Cleantech-Startup vor der Serie B. Vertrauen aufgebaut, Ambitionen signalisiert, Runde abgeschlossen.",
    "the rebrand was the catalyst for our series b. investors told us directly — the identity signaled we were serious. that's the roi of great brand work.": "Das Rebranding war der Katalysator für unsere Series B. Investoren haben uns direkt gesagt — die Identität signalisierte, dass wir es ernst meinten. Das ist der ROI großartiger Markenarbeit.",
    "three creative directions, each fully resolved. no half-baked moodboards — real systems you can evaluate in context.": "Drei kreative Richtungen, jede vollständig gelöst. Keine halbherzigen Moodboards — echte Systeme, die Sie im Kontext bewerten können.",
    "view our work": "Unsere Arbeiten ansehen",
    "we take on 6 projects per quarter. if your brief has ambition and your deadline has adrenaline, we want to hear it.": "Wir übernehmen 6 Projekte pro Quartal. Wenn Ihr Brief Ambitionen hat und Ihre Frist Adrenalin hat, möchten wir davon hören.",
    "web design": "Webdesign",
    "websites and interactive platforms that convert intent. performance-first, scroll-driven, and designed to be remembered.": "Websites und Plattformen, die Absicht in Handlung verwandeln. Leistung zuerst, gebaut, um im Gedächtnis zu bleiben.",
    "what makes orbit different from a freelancer or a large agency?": "Was macht Orbit anders als einen Freelancer oder eine große Agentur?",
    "wordmarks, symbol systems, color architecture, and type hierarchies that telegraph exactly who you are before a single word is read.": "Wortmarken, Symbolsystheme, Farbarchitektur und Typografie-Hierarchien, die genau vermitteln, wer Sie sind, bevor ein einziges Wort gelesen wird.",
  },
  pt: {
    "brands that": "Marcas que",
    "shift": "deslocam",
    "perception.": "o olhar.",
    "we build identity systems for ambitious companies — from seed-stage startups to century-old maisons. strategy, visual identity, and art direction that makes the right people stop scrolling.": "Construímos sistemas de identidade para empresas ambiciosas — da jovem startup à casa centenária. Estratégia, identidade visual e direção artística: o suficiente para deter o olhar certo.",
    "12 countries": "12 países",
    "orbit home": "Início",
    "about orbit": "Sobre nós",
    "art direction for the launch of ovoid's clean beauty line. sensory, scientific, unmistakably feminine.": "Direção de arte para o lançamento da linha de beleza limpa da Ovoid. Sensorial, científica, inconfundivelmente feminina.",
    "average client growth yoy": "Crescimento médio de clientes ano a ano",
    "brand story": "História da marca",
    "campaign concepting, editorial systems, and production oversight for brand moments that have to land perfectly.": "Conceção de campanha, sistemas editoriais e acompanhamento de produção, para os momentos de marca que não podem falhar.",
    "campaign concepts, visual worlds, and creative direction for shoots, launches, and brand campaigns that live long after the brief.": "Conceitos de campanha, mundos visuais e direção criativa para sessões fotográficas, lançamentos e campanhas de marca que perduram muito depois do briefing.",
    "can we own all files and assets after delivery?": "Podemos possuir todos os arquivos e ativos após a entrega?",
    "client capital raised": "Capital levantado pelos clientes",
    "complete identity overhaul for a luxury spirits house entering european markets. dark, confident, built to age.": "Reformulação completa da identidade para uma casa de bebidas espirituosas de luxo que entra nos mercados europeus. Escura, confiante, feita para envelhecer.",
    "comprehensive brand guidelines, all master files, asset libraries, and a handover session. everything you need to carry the brand forward.": "Diretrizes de marca abrangentes, todos os arquivos mestres, bibliotecas de ativos e uma sessão de entrega. Tudo o que você precisa para levar a marca adiante.",
    "digital experience for the brutalist architecture studio behind the prix d'architecture 2024 laureate.": "Experiência digital para o estúdio de arquitetura brutalista por trás do laureado do Prix d'Architecture 2024.",
    "do you offer retainer arrangements after project delivery?": "Oferecem acordos de retenção após a entrega do projeto?",
    "do you work with early-stage startups or only established companies?": "Trabalham com startups em estágio inicial ou apenas com empresas estabelecidas?",
    "full brand system and launch campaign for a dtc athletic brand hitting €1.2m gmv in month one.": "Sistema de marca completo e campanha de lançamento para uma marca atlética DTC que atinge 1,2 M€ de GMV no primeiro mês.",
    "head of strategy": "Chefe de Estratégia",
    "how do you handle confidential work during the nda period?": "Como lidam com trabalho confidencial durante o período de NDA?",
    "how long does a full brand identity project take?": "Quanto tempo leva um projeto completo de identidade de marca?",
    "how we do it.": "como procedemos.",
    "let's make": "Vamos fazer",
    "logo, type system, color, motion principles, and brand guidelines that hold up from a business card to a stadium banner.": "Logotipo, sistema de tipografía, cor, princípios de movimento e diretrizes de marca que se mantêm desde um cartão de visita até um banner de estádio.",
    "motion identity, web design systems, social template libraries, and digital touchpoints engineered for the screens your audience lives on.": "Identidade em movimento, sistemas de design web, bibliotecas de modelos sociais e pontos de contato digitais projetados para as telas em que o seu público vive.",
    "multi-brand and sub-brand hierarchies that scale without cannibalizing. built for acquirers and acquirees alike.": "Hierarquias de múltiplas marcas e sub-marcas que escalam sem canibalizar. Construído para adquirentes e adquiridos.",
    "new brief": "Novo projeto",
    "one chosen direction, refined through two rounds of structured feedback. precision over iteration — we move forward, not in circles.": "Uma direção escolhida, refinada através de duas rodadas de feedback estruturado. Precisão em vez de iteração — avançamos, não andamos em círculos.",
    "orbit didn't just design a logo — they built us a world. every touchpoint now feels intentional. distributors stop us at every trade show to ask who did it.": "A Orbit não apenas desenhou um logotipo — eles nos construíram um mundo. Cada ponto de contato agora parece intencional. Os distribuidores nos param em cada feira para perguntar quem fez isso.",
    "packaging design": "Design de embalagem",
    "positioning territory, naming (if needed), brand pillars, and the core narrative. everything downstream traces back to this document.": "Território de posicionamento, nomeação (se necessário), pilares da marca e a narrativa central. Tudo o que vem a seguir remete a este documento.",
    "positioning, naming, messaging architecture, and competitive landscaping. we build the logic before the aesthetics.": "Posicionamento, nome, arquitetura do discurso, mapa competitivo. Pomos a lógica antes da estética.",
    "positioning, naming, narrative, and competitive architecture. we find the single idea your brand should own — then build everything from it.": "Posicionamento, nomeação, narrativa e arquitetura competitiva. Encontramos a única ideia que a sua marca deve possuir — depois construímos tudo a partir disso.",
    "repositioning a 3rd-generation french maison as a modern luxury atelier without losing its heritage roots.": "Reposicionamento de uma maison francesa de 3ª geração como um atelier de luxo moderno sem perder suas raízes patrimoniais.",
    "retail presence that earns shelf space. we design for attention at 2 meters and delight at 20 centimeters.": "Presença no retalho que conquista espaço nas prateleiras. Projetamos para chamar a atenção a 2 metros e encantar a 20 centímetros.",
    "revenue multiple": "Múltiplo de receita",
    "see all projects": "Ver todos os projetos",
    "strategic rebrand for a cleantech startup pre-series b. built trust, signaled ambition, closed the round.": "Rebranding estratégico para uma startup de cleantech antes da Série B. Confiança construída, ambição sinalizada, rodada fechada.",
    "the rebrand was the catalyst for our series b. investors told us directly — the identity signaled we were serious. that's the roi of great brand work.": "O rebranding foi o catalisador da nossa Série B. Os investidores nos disseram diretamente — a identidade sinalizou que éramos sérios. Esse é o ROI de um ótimo trabalho de marca.",
    "three creative directions, each fully resolved. no half-baked moodboards — real systems you can evaluate in context.": "Três direções criativas, cada uma totalmente resolvida. Sem moodboards mal feitos — sistemas reais que você pode avaliar no contexto.",
    "view our work": "Ver os nossos trabalhos",
    "we take on 6 projects per quarter. if your brief has ambition and your deadline has adrenaline, we want to hear it.": "Aceitamos 6 projetos por trimestre. Se o seu briefing tem ambição e o seu prazo tem adrenalina, queremos ouvi-lo.",
    "web design": "Design de Websites",
    "websites and interactive platforms that convert intent. performance-first, scroll-driven, and designed to be remembered.": "Sites e plataformas que convertem a intenção. Desempenho primeiro, pensados para deixar marca.",
    "what makes orbit different from a freelancer or a large agency?": "O que torna a Orbit diferente de um freelancer ou de uma grande agência?",
    "wordmarks, symbol systems, color architecture, and type hierarchies that telegraph exactly who you are before a single word is read.": "Logótipos, sistemas de símbolos, arquitetura de cores e hierarquias tipográficas que transmitem exatamente quem você é antes de se ler uma única palavra.",
  },
};
