/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "programs": "Programmes",
    "coaches": "Les coachs",
    "membership": "Abonnement",
    "types": "Types",
    "integrations": "Intégrations",
    "gdpr": "RGPD",
    "podcast": "Balado",
    "the art": "L'art",
    "finance": "Finance",
    "avis clients": "Avis clients",
    "des clients.": "des clients.",
    "of grooming.": "de Toilettage.",
    "the art of grooming": "L'art du soin",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "programs": "Programas",
    "coaches": "Los entrenadores",
    "membership": "Abono",
    "types": "Tipos",
    "integrations": "Integraciones",
    "gdpr": "RGPD",
    "podcast": "Pódcast",
    "the art": "El arte",
    "finance": "Finanzas",
    "avis clients": "Opiniones de clientes",
    "des clients.": "clientes.",
    "of grooming.": "de Aseo.",
    "the art of grooming": "El arte del cuidado",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "programs": "Programme",
    "coaches": "Die Coaches",
    "membership": "Mitgliedschaft",
    "types": "Typen",
    "integrations": "Integrationen",
    "gdpr": "DSGVO",
    "podcast": "Podcast",
    "the art": "Die Kunst",
    "finance": "Finanzen",
    "avis clients": "Kundenbewertungen",
    "des clients.": "Kunden.",
    "of grooming.": "von Grooming.",
    "the art of grooming": "Die Kunst der Pflege",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "programs": "Programas",
    "coaches": "Os treinadores",
    "membership": "Assinatura",
    "types": "Tipos",
    "integrations": "Integrações",
    "gdpr": "RGPD",
    "podcast": "Podcast",
    "the art": "A arte",
    "finance": "Finanças",
    "avis clients": "Avaliações de clientes",
    "des clients.": "clientes.",
    "of grooming.": "de Cuidado Pessoal.",
    "the art of grooming": "A arte do cuidado",
  },
};
