/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "retreats": "Les retraites",
    "lineage": "Filiation",
    "rest is": "Le repos est",
    "the work.": "le vrai travail.",
    "luminal designs profound retreat experiences in the world's most transformative landscapes. we create the conditions for genuine rest through carefully calibrated stillness.": "Luminal conçoit des retraites profondes dans les paysages les plus transformateurs du monde. Nous créons les conditions d'un repos véritable, par un calme soigneusement dosé.",
    "stillness": "Le calme",
    "sonoran silence": "Silence de Sonora",
    "arizona desert, usa": "Désert d'Arizona, États-Unis",
    "7 nights": "7 nuits",
    "5 nights": "5 nuits",
    "6 nights": "6 nuits",
    "oct–apr": "Oct.–avr.",
    "jun–aug": "Juin–août",
    "mar–may": "Mars–mai",
    "clarity": "La clarté",
    "icelandic deep reset": "Grande remise à zéro islandaise",
    "westfjords, iceland": "Fjords de l'Ouest, Islande",
    "presence": "La présence",
    "kyoto forest immersion": "Immersion en forêt de Kyoto",
    "arashiyama, japan": "Arashiyama, Japon",
    "neuro-plasticity": "Neuroplasticité",
    "circadian sync": "Synchronisation circadienne",
    "somatic recall": "Mémoire somatique",
    "contemplative guide": "Guide contemplatif",
    "somatic therapist": "Thérapeute somatique",
    "former neuropsychologist specialized in burnout recovery, clara developed the luminal method after a decade in clinical practice": "Ancienne neuropsychologue spécialisée dans la sortie du burnout, Clara a mis au point la Méthode Luminale après dix ans de pratique clinique",
    "expert in nervous system regulation and trauma release, elena leads the somatic re-patterning sessions": "Spécialiste de la régulation du système nerveux et de la libération du trauma, Elena conduit les séances de reprogrammation somatique",
    "a 21-day pre-arrival protocol to begin the process of digital and cognitive deceleration.": "Un protocole de pré-arrivée de 21 jours pour commencer le processus de décélération numérique et cognitive.",
    "a 45-minute consultation with a guide to ensure alignment with our method and group dynamics.": "Une consultation de 45 minutes avec un guide pour garantir l'alignement avec notre méthode et la dynamique de groupe.",
    "a detailed questionnaire mapping your current psychological and physiological baseline.": "Un questionnaire détaillé cartographiant votre base psychologique et physiologique actuelle.",
    "a zen monk with 30 years of practice in the rinzai lineage, juro oversees all meditation and walking sequences": "Moine zen de la lignée Rinzai, trente ans de pratique, Juro veille sur toutes les séances de méditation et de marche",
    "body-based interventions that target the vagus nerve to down-regulate high-stress arousal states permanently.": "Interventions basées sur le corps qui ciblent le nerf vague pour réguler de manière permanente les états d'excitation liés au stress élevé.",
    "ce qu'on nous pose.": "Ce qu'on nous pose.",
    "crafted with stillness": "Fait dans le calme",
    "descend into stillness": "Descendre vers le calme",
    "explore 2026 programme": "Explorer le Programme 2026",
    "founder & lead clinician": "Fondatrice et praticienne principale",
    "from $4,200": "à partir de 4 200 $",
    "from $5,800": "à partir de 5 800 $",
    "from $6,100": "à partir de 6 100 $",
    "geothermal pools at midnight beneath the aurora. five days designed to dissolve the residue of over-functioning and restore access to your own thinking.": "Des piscines géothermiques à minuit sous l'aurore. Cinq jours conçus pour dissoudre les résidus de surfonctionnement et restaurer l'accès à votre propre pensée.",
    "our environments are chosen to maximize cognitive flexibility through novel sensory input and radical reduction of digital noise.": "Nos lieux sont choisis pour ouvrir l'esprit : des sensations nouvelles, et le bruit numérique réduit à presque rien.",
    "protocols are timed to natural light cycles to reset the hypothalamic-pituitary-adrenal axis and restore sleep architecture.": "Les protocoles sont synchronisés avec les cycles de lumière naturelle pour réinitialiser l'axe hypothalamo-hypophysaire-surrénalien et restaurer l'architecture du sommeil.",
    "selection of the retreat landscape best suited to your specific restorative needs.": "Sélection du paysage de retraite le mieux adapté à vos besoins de restauration spécifiques.",
    "shinrin-yoku through arashiyama bamboo groves. zen walking sequences with a lineage-trained teacher. tea ceremony as contemplative practice.": "Shinrin-yoku à travers les forêts de bambous d'Arashiyama. Séquences de marche zen avec un enseignant formé par lignée. Cérémonie du thé comme pratique contemplative.",
    "terms of access": "Conditions d'accès",
    "the luminal method": "La méthode Luminal",
  },
  es: {
    "retreats": "Los retiros",
    "lineage": "Linaje",
    "rest is": "El descanso es",
    "the work.": "el verdadero trabajo.",
    "luminal designs profound retreat experiences in the world's most transformative landscapes. we create the conditions for genuine rest through carefully calibrated stillness.": "Luminal diseña retiros profundos en los paisajes más transformadores del mundo. Creamos las condiciones de un descanso verdadero, mediante una calma cuidadosamente dosificada.",
    "stillness": "La calma",
    "sonoran silence": "Silencio de Sonora",
    "arizona desert, usa": "Desierto de Arizona, Estados Unidos",
    "7 nights": "7 noches",
    "5 nights": "5 noches",
    "6 nights": "6 noches",
    "oct–apr": "Oct.–abr.",
    "jun–aug": "Jun.–ago.",
    "mar–may": "Mar.–may.",
    "clarity": "La claridad",
    "icelandic deep reset": "Gran reinicio islandés",
    "westfjords, iceland": "Fiordos del Oeste, Islandia",
    "presence": "La presencia",
    "kyoto forest immersion": "Inmersión en el bosque de Kioto",
    "arashiyama, japan": "Arashiyama, Japón",
    "neuro-plasticity": "Neuroplasticidad",
    "circadian sync": "Sincronización circadiana",
    "somatic recall": "Memoria somática",
    "contemplative guide": "Guía contemplativo",
    "somatic therapist": "Terapeuta somática",
    "former neuropsychologist specialized in burnout recovery, clara developed the luminal method after a decade in clinical practice": "Antigua neuropsicóloga especializada en la salida del burnout, Clara desarrolló el Método Luminal tras diez años de práctica clínica",
    "expert in nervous system regulation and trauma release, elena leads the somatic re-patterning sessions": "Especialista en regulación del sistema nervioso y liberación del trauma, Elena dirige las sesiones de reprogramación somática",
    "a 21-day pre-arrival protocol to begin the process of digital and cognitive deceleration.": "Un protocolo de pre-llegada de 21 días para comenzar el proceso de desaceleración digital y cognitiva.",
    "a 45-minute consultation with a guide to ensure alignment with our method and group dynamics.": "Una consulta de 45 minutos con un guía para asegurar la alineación con nuestro método y la dinámica del grupo.",
    "a detailed questionnaire mapping your current psychological and physiological baseline.": "Un cuestionario detallado que mapea tu línea base psicológica y fisiológica actual.",
    "a zen monk with 30 years of practice in the rinzai lineage, juro oversees all meditation and walking sequences": "Monje zen del linaje Rinzai, con treinta años de práctica, Juro supervisa todas las sesiones de meditación y de marcha",
    "body-based interventions that target the vagus nerve to down-regulate high-stress arousal states permanently.": "Intervenciones basadas en el cuerpo que apuntan al nervio vago para regular permanentemente los estados de excitación por estrés alto.",
    "ce qu'on nous pose.": "Lo que nos preguntan.",
    "crafted with stillness": "Hecho en la calma",
    "descend into stillness": "Descender hacia la calma",
    "explore 2026 programme": "Explorar el Programa 2026",
    "founder & lead clinician": "Fundadora y clínica principal",
    "from $4,200": "desde 4 200 $",
    "from $5,800": "desde 5 800 $",
    "from $6,100": "desde 6 100 $",
    "geothermal pools at midnight beneath the aurora. five days designed to dissolve the residue of over-functioning and restore access to your own thinking.": "Piscinas geotérmicas a medianoche bajo la aurora. Cinco días diseñados para disolver el residuo del sobrefuncionamiento y restaurar el acceso a tu propio pensamiento.",
    "our environments are chosen to maximize cognitive flexibility through novel sensory input and radical reduction of digital noise.": "Nuestros lugares se eligen para abrir la mente: sensaciones nuevas y el ruido digital reducido casi a nada.",
    "protocols are timed to natural light cycles to reset the hypothalamic-pituitary-adrenal axis and restore sleep architecture.": "Los protocolos están sincronizados con los ciclos de luz natural para restablecer el eje hipotálamo-hipofisario-adrenal y restaurar la arquitectura del sueño.",
    "selection of the retreat landscape best suited to your specific restorative needs.": "Selección del paisaje de retiro más adecuado a tus necesidades restaurativas específicas.",
    "shinrin-yoku through arashiyama bamboo groves. zen walking sequences with a lineage-trained teacher. tea ceremony as contemplative practice.": "Shinrin-yoku a través de los bosques de bambú de Arashiyama. Secuencias de caminata zen con un maestro entrenado por linaje. Ceremonia del té como práctica contemplativa.",
    "terms of access": "Términos de acceso",
    "the luminal method": "El método Luminal",
  },
  de: {
    "retreats": "Die Retreats",
    "lineage": "Herkunft",
    "rest is": "Ruhe ist",
    "the work.": "die eigentliche Arbeit.",
    "luminal designs profound retreat experiences in the world's most transformative landscapes. we create the conditions for genuine rest through carefully calibrated stillness.": "Luminal gestaltet tiefgreifende Retreats in den verwandelndsten Landschaften der Welt. Wir schaffen die Bedingungen für echte Ruhe durch sorgfältig abgestimmte Stille.",
    "stillness": "Die Stille",
    "sonoran silence": "Stille der Sonora",
    "arizona desert, usa": "Arizona-Wüste, USA",
    "7 nights": "7 Nächte",
    "5 nights": "5 Nächte",
    "6 nights": "6 Nächte",
    "oct–apr": "Okt.–Apr.",
    "jun–aug": "Juni–Aug.",
    "mar–may": "März–Mai",
    "clarity": "Die Klarheit",
    "icelandic deep reset": "Isländischer Tiefen-Reset",
    "westfjords, iceland": "Westfjorde, Island",
    "presence": "Die Präsenz",
    "kyoto forest immersion": "Waldimmersion in Kyoto",
    "arashiyama, japan": "Arashiyama, Japan",
    "neuro-plasticity": "Neuroplastizität",
    "circadian sync": "Zirkadiane Synchronisation",
    "somatic recall": "Somatisches Gedächtnis",
    "contemplative guide": "Kontemplativer Begleiter",
    "somatic therapist": "Somatische Therapeutin",
    "former neuropsychologist specialized in burnout recovery, clara developed the luminal method after a decade in clinical practice": "Als frühere Neuropsychologin mit Schwerpunkt Burnout-Genesung entwickelte Clara die Luminal-Methode nach zehn Jahren klinischer Praxis",
    "expert in nervous system regulation and trauma release, elena leads the somatic re-patterning sessions": "Als Expertin für die Regulation des Nervensystems und Traumalösung leitet Elena die Sitzungen zur somatischen Neuprägung",
    "a 21-day pre-arrival protocol to begin the process of digital and cognitive deceleration.": "Ein 21-tägiges Protokoll vor der Ankunft, um den Prozess der digitalen und kognitiven Verlangsamung zu beginnen.",
    "a 45-minute consultation with a guide to ensure alignment with our method and group dynamics.": "Eine 45-minütige Beratung mit einem Guide, um die Übereinstimmung mit unserer Methode und den Gruppendynamiken sicherzustellen.",
    "a detailed questionnaire mapping your current psychological and physiological baseline.": "Ein detaillierter Fragebogen, der Ihre aktuelle psychologische und physiologische Basis erfasst.",
    "a zen monk with 30 years of practice in the rinzai lineage, juro oversees all meditation and walking sequences": "Zen-Mönch der Rinzai-Linie mit dreißig Jahren Praxis, betreut Juro alle Meditations- und Gehsequenzen",
    "body-based interventions that target the vagus nerve to down-regulate high-stress arousal states permanently.": "Körperbasierte Interventionen, die den Vagusnerv anvisieren, um hochstressbedingte Erregungszustände dauerhaft zu regulieren.",
    "ce qu'on nous pose.": "Was uns gefragt wird.",
    "crafted with stillness": "In Stille gefertigt",
    "descend into stillness": "Hinab in die Stille",
    "explore 2026 programme": "Erforschen Sie das Programm 2026",
    "founder & lead clinician": "Gründerin und leitende Therapeutin",
    "from $4,200": "ab 4 200 $",
    "from $5,800": "ab 5 800 $",
    "from $6,100": "ab 6 100 $",
    "geothermal pools at midnight beneath the aurora. five days designed to dissolve the residue of over-functioning and restore access to your own thinking.": "Geothermische Pools um Mitternacht unter der Aurora. Fünf Tage, die darauf ausgelegt sind, die Rückstände von Überfunktion zu lösen und den Zugang zu deinem eigenen Denken wiederherzustellen.",
    "our environments are chosen to maximize cognitive flexibility through novel sensory input and radical reduction of digital noise.": "Unsere Orte sind so gewählt, dass sie den Geist öffnen: neue Sinneseindrücke und digitales Rauschen auf fast null reduziert.",
    "protocols are timed to natural light cycles to reset the hypothalamic-pituitary-adrenal axis and restore sleep architecture.": "Die Protokolle sind auf natürliche Lichtzyklen abgestimmt, um die hypothalamisch-hypophysär-adrenalen Achse zurückzusetzen und die Schlafarchitektur wiederherzustellen.",
    "selection of the retreat landscape best suited to your specific restorative needs.": "Auswahl der Rückzugslandschaft, die am besten zu Ihren spezifischen Wiederherstellungsbedürfnissen passt.",
    "shinrin-yoku through arashiyama bamboo groves. zen walking sequences with a lineage-trained teacher. tea ceremony as contemplative practice.": "Shinrin-yoku durch die Bambuswälder von Arashiyama. Zen-Wandersequenzen mit einem linienausgebildeten Lehrer. Teezeremonie als kontemplative Praxis.",
    "terms of access": "Zugangsbedingungen",
    "the luminal method": "Die Luminal-Methode",
  },
  pt: {
    "retreats": "Os retiros",
    "lineage": "Linhagem",
    "rest is": "O descanso é",
    "the work.": "o verdadeiro trabalho.",
    "luminal designs profound retreat experiences in the world's most transformative landscapes. we create the conditions for genuine rest through carefully calibrated stillness.": "A Luminal concebe retiros profundos nas paisagens mais transformadoras do mundo. Criamos as condições de um descanso verdadeiro, através de uma calma cuidadosamente doseada.",
    "stillness": "A calma",
    "sonoran silence": "Silêncio de Sonora",
    "arizona desert, usa": "Deserto do Arizona, Estados Unidos",
    "7 nights": "7 noites",
    "5 nights": "5 noites",
    "6 nights": "6 noites",
    "oct–apr": "Out.–abr.",
    "jun–aug": "Jun.–ago.",
    "mar–may": "Mar.–maio",
    "clarity": "A clareza",
    "icelandic deep reset": "Grande reinício islandês",
    "westfjords, iceland": "Fiordes do Oeste, Islândia",
    "presence": "A presença",
    "kyoto forest immersion": "Imersão na floresta de Quioto",
    "arashiyama, japan": "Arashiyama, Japão",
    "neuro-plasticity": "Neuroplasticidade",
    "circadian sync": "Sincronização circadiana",
    "somatic recall": "Memória somática",
    "contemplative guide": "Guia contemplativo",
    "somatic therapist": "Terapeuta somática",
    "former neuropsychologist specialized in burnout recovery, clara developed the luminal method after a decade in clinical practice": "Antiga neuropsicóloga especializada na saída do burnout, Clara desenvolveu o Método Luminal após dez anos de prática clínica",
    "expert in nervous system regulation and trauma release, elena leads the somatic re-patterning sessions": "Especialista na regulação do sistema nervoso e na libertação do trauma, Elena conduz as sessões de reprogramação somática",
    "a 21-day pre-arrival protocol to begin the process of digital and cognitive deceleration.": "Um protocolo de pré-chegada de 21 dias para iniciar o processo de desaceleração digital e cognitiva.",
    "a 45-minute consultation with a guide to ensure alignment with our method and group dynamics.": "Uma consulta de 45 minutos com um guia para garantir a alinhamento com o nosso método e a dinâmica de grupo.",
    "a detailed questionnaire mapping your current psychological and physiological baseline.": "Um questionário detalhado que mapeia sua linha de base psicológica e fisiológica atual.",
    "a zen monk with 30 years of practice in the rinzai lineage, juro oversees all meditation and walking sequences": "Monge zen da linhagem Rinzai, com trinta anos de prática, Juro acompanha todas as sessões de meditação e de marcha",
    "body-based interventions that target the vagus nerve to down-regulate high-stress arousal states permanently.": "Intervenções baseadas no corpo que visam o nervo vago para regular permanentemente os estados de excitação de alto estresse.",
    "ce qu'on nous pose.": "O que nos perguntam.",
    "crafted with stillness": "Feito na calma",
    "descend into stillness": "Descer até à calma",
    "explore 2026 programme": "Explorar o Programa 2026",
    "founder & lead clinician": "Fundadora e clínica principal",
    "from $4,200": "a partir de 4 200 $",
    "from $5,800": "a partir de 5 800 $",
    "from $6,100": "a partir de 6 100 $",
    "geothermal pools at midnight beneath the aurora. five days designed to dissolve the residue of over-functioning and restore access to your own thinking.": "Piscinas geotérmicas à meia-noite sob a aurora. Cinco dias projetados para dissolver o resíduo do sobrefuncionamento e restaurar o acesso ao seu próprio pensamento.",
    "our environments are chosen to maximize cognitive flexibility through novel sensory input and radical reduction of digital noise.": "Os nossos lugares são escolhidos para abrir a mente: sensações novas e o ruído digital reduzido a quase nada.",
    "protocols are timed to natural light cycles to reset the hypothalamic-pituitary-adrenal axis and restore sleep architecture.": "Os protocolos estão sincronizados com os ciclos de luz natural para redefinir o eixo hipotálamo-hipofisário-adrenal e restaurar a arquitetura do sono.",
    "selection of the retreat landscape best suited to your specific restorative needs.": "Seleção da paisagem de retiro mais adequada às suas necessidades restaurativas específicas.",
    "shinrin-yoku through arashiyama bamboo groves. zen walking sequences with a lineage-trained teacher. tea ceremony as contemplative practice.": "Shinrin-yoku através dos bosques de bambu de Arashiyama. Sequências de caminhada zen com um professor treinado por linhagem. Cerimônia do chá como prática contemplativa.",
    "terms of access": "Condições de Acesso",
    "the luminal method": "O método Luminal",
  },
};
