/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in light.\"": "« L'architecture est le jeu savant, correct et magnifique, des volumes assemblés sous la lumière. »",
    "\"we subtract until only the": "« Nous retranchons jusqu'à ce que seul le",
    "archdaily building of the year": "Bâtiment de l'Année Archdaily",
    "architectural interventions that harmonize human ritual with the absolute geometry of nature.": "Interventions architecturales qui harmonisent le rituel humain avec la géométrie absolue de la nature.",
    "archive of form": "Archive de la forme",
    "as seen": "Comme vu",
    "build the": "Construire le",
    "build.": "construire.",
    "can i visit your studio?": "Puis-je visiter votre studio ?",
    "commercial design": "Design Commercial",
    "concept design": "Conception de concept",
    "design": "Design",
    "design director": "Directeur de Design",
    "do you work internationally?": "Travaillez-vous à l'international ?",
    "elias vorn: 'we subtract until only the essential remains'": "Elias Vorn : « Nous retranchons jusqu'à ce qu'il ne reste que l'essentiel »",
    "every space is designed from its light source outward. natural illumination is the primary material — all structure serves it.": "Chaque espace est conçu à partir de sa source de lumière vers l'extérieur. L'illumination naturelle est le matériau principal — toute structure lui sert.",
    "how long does a typical project take?": "Combien de temps dure un projet typique ?",
    "how we": "Comment nous",
    "inside the obsidian villa: restraint as luxury": "À l'intérieur de la Villa Obsidienne : la retenue comme luxe",
    "lighting design": "Conception d'éclairage",
    "material memory: how symmetry studio chooses its palette": "Mémoire Matérielle : comment Symmetry Studio choisit sa palette",
    "method // process": "Méthode // Processus",
    "people // studio": "Équipe // Studio",
    "post-occupancy review": "Revue post-occupation",
    "questions // answers": "Questions // Réponses",
    "raw concrete, unfinished oak, and oxidized copper. we select materials for their capacity to age with grace and accumulate meaning.": "Béton brut, chêne non fini et cuivre oxydé. Nous sélectionnons des matériaux pour leur capacité à vieillir avec grâce et à accumuler du sens.",
    "schematic design developed through models, drawings, and material samples. we present three distinct concepts and refine the selected direction iteratively.": "Conception schématique développée à travers des modèles, des dessins et des échantillons de matériaux. Nous présentons trois concepts distincts et affinons la direction sélectionnée de manière itérative.",
    "site supervision throughout the construction phase. we conduct weekly reviews with the contractor and issue formal site observation reports.": "Supervision de site tout au long de la phase de construction. Nous effectuons des revues hebdomadaires avec l'entrepreneur et émettons des rapports d'observation de site formels.",
    "the absence of form is form. empty space is designed with the same rigour as occupied volume.": "L'absence de forme est une forme. L'espace vide est conçu avec la même rigueur que le volume occupé.",
    "the obsidian villa": "La Villa Obsidienne",
    "the return of the pure volume": "Le retour du volume pur",
    "the studio.": "L'agence.",
    "the vision": "La vision",
    "trained at the eth zürich and the architectural association. elias leads design strategy and maintains relationships with structural engineering consultants across europe.": "Formé à l'ETH Zurich et à l'Architectural Association. Elias mène la stratégie de conception et entretient les liens avec les bureaux d'études de structure en Europe.",
    "view all work": "Voir toutes les réalisations",
    "view map of silence": "Voir la carte du silence",
    "wallpaper* design award": "Prix de Design Wallpaper*",
    "we accept a limited number of commissions each cycle to ensure the structural integrity and conceptual purity of every space.": "Nous acceptons un nombre limité de commandes à chaque cycle pour garantir l'intégrité structurelle et la pureté conceptuelle de chaque espace.",
    "we welcome site visits by appointment. our material library and model archive are available for viewing during studio hours, tuesday through friday.": "Nous accueillons les visites sur site sur rendez-vous. Notre bibliothèque de matériaux et notre archive de modèles sont disponibles à la consultation pendant les heures d'ouverture du studio, du mardi au vendredi.",
    "what is your minimum project budget?": "Quel est votre budget minimum pour un projet ?",
    "what we": "Ce que nous",
    "work.": "travail.",
    "years practice": "Années de Pratique",
  },
  es: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in light.\"": "«La arquitectura es el juego sabio, correcto y magnífico, de los volúmenes reunidos bajo la luz.»",
    "\"we subtract until only the": "«Restamos hasta que solo lo",
    "archdaily building of the year": "Edificio del Año Archdaily",
    "architectural interventions that harmonize human ritual with the absolute geometry of nature.": "Intervenciones arquitectónicas que armonizan el ritual humano con la geometría absoluta de la naturaleza.",
    "archive of form": "Archivo de la forma",
    "as seen": "Como se ve",
    "build the": "Construir el",
    "build.": "construir.",
    "can i visit your studio?": "¿Puedo visitar su estudio?",
    "commercial design": "Diseño Comercial",
    "concept design": "Diseño conceptual",
    "design": "Diseño",
    "design director": "Director de Diseño",
    "do you work internationally?": "¿Trabajan internacionalmente?",
    "elias vorn: 'we subtract until only the essential remains'": "Elias Vorn: «Restamos hasta que solo queda lo esencial»",
    "every space is designed from its light source outward. natural illumination is the primary material — all structure serves it.": "Cada espacio está diseñado desde su fuente de luz hacia afuera. La iluminación natural es el material principal — toda estructura le sirve.",
    "how long does a typical project take?": "¿Cuánto tiempo tarda un proyecto típico?",
    "how we": "Cómo nosotros",
    "inside the obsidian villa: restraint as luxury": "Dentro de la Villa Obsidiana: la contención como lujo",
    "lighting design": "Diseño de iluminación",
    "material memory: how symmetry studio chooses its palette": "Memoria Material: cómo Symmetry Studio elige su paleta",
    "method // process": "Método // Proceso",
    "people // studio": "Gente // Estudio",
    "post-occupancy review": "Revisión post-ocupación",
    "questions // answers": "Preguntas // Respuestas",
    "raw concrete, unfinished oak, and oxidized copper. we select materials for their capacity to age with grace and accumulate meaning.": "Hormigón crudo, roble sin terminar y cobre oxidado. Seleccionamos materiales por su capacidad de envejecer con gracia y acumular significado.",
    "schematic design developed through models, drawings, and material samples. we present three distinct concepts and refine the selected direction iteratively.": "Diseño esquemático desarrollado a través de modelos, dibujos y muestras de materiales. Presentamos tres conceptos distintos y refinamos la dirección seleccionada de manera iterativa.",
    "site supervision throughout the construction phase. we conduct weekly reviews with the contractor and issue formal site observation reports.": "Supervisión del sitio durante toda la fase de construcción. Realizamos revisiones semanales con el contratista y emitimos informes formales de observación del sitio.",
    "the absence of form is form. empty space is designed with the same rigour as occupied volume.": "La ausencia de forma es forma. El espacio vacío se diseña con la misma rigurosidad que el volumen ocupado.",
    "the obsidian villa": "La Villa Obsidiana",
    "the return of the pure volume": "El retorno del volumen puro",
    "the studio.": "El estudio.",
    "the vision": "La visión",
    "trained at the eth zürich and the architectural association. elias leads design strategy and maintains relationships with structural engineering consultants across europe.": "Formado en la ETH de Zúrich y en la Architectural Association. Elias dirige la estrategia de diseño y mantiene la relación con las oficinas de cálculo de estructuras en Europa.",
    "view all work": "Ver todos los trabajos",
    "view map of silence": "Ver mapa del silencio",
    "wallpaper* design award": "Premio de Diseño Wallpaper*",
    "we accept a limited number of commissions each cycle to ensure the structural integrity and conceptual purity of every space.": "Aceptamos un número limitado de comisiones en cada ciclo para garantizar la integridad estructural y la pureza conceptual de cada espacio.",
    "we welcome site visits by appointment. our material library and model archive are available for viewing during studio hours, tuesday through friday.": "Damos la bienvenida a las visitas al sitio con cita previa. Nuestra biblioteca de materiales y archivo de modelos están disponibles para su consulta durante el horario de estudio, de martes a viernes.",
    "what is your minimum project budget?": "¿Cuál es su presupuesto mínimo para el proyecto?",
    "what we": "Lo que",
    "work.": "trabajo.",
    "years practice": "Años de Práctica",
  },
  de: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in light.\"": "„Architektur ist das kunstvolle, korrekte und großartige Spiel der unter dem Licht versammelten Baukörper.“",
    "\"we subtract until only the": "„Wir ziehen ab, bis nur noch das",
    "archdaily building of the year": "Archdaily Gebäude des Jahres",
    "architectural interventions that harmonize human ritual with the absolute geometry of nature.": "Architektonische Interventionen, die menschliche Rituale mit der absoluten Geometrie der Natur harmonisieren.",
    "archive of form": "Archiv der Form",
    "as seen": "Wie gesehen",
    "build the": "Bauen Sie das",
    "build.": "bauen.",
    "can i visit your studio?": "Kann ich Ihr Studio besuchen?",
    "commercial design": "Kommerzielles Design",
    "concept design": "Konzeptdesign",
    "design": "Design",
    "design director": "Design-Direktor",
    "do you work internationally?": "Arbeiten Sie international?",
    "elias vorn: 'we subtract until only the essential remains'": "Elias Vorn: „Wir ziehen ab, bis nur das Wesentliche bleibt“",
    "every space is designed from its light source outward. natural illumination is the primary material — all structure serves it.": "Jeder Raum ist von seiner Lichtquelle nach außen gestaltet. Natürliche Beleuchtung ist das primäre Material — alle Struktur dient ihr.",
    "how long does a typical project take?": "Wie lange dauert ein typisches Projekt?",
    "how we": "Wie wir",
    "inside the obsidian villa: restraint as luxury": "Im Inneren der Obsidianvilla: Zurückhaltung als Luxus",
    "lighting design": "Lichtdesign",
    "material memory: how symmetry studio chooses its palette": "Materialgedächtnis: wie das Symmetry Studio seine Farbpalette wählt",
    "method // process": "Methode // Prozess",
    "people // studio": "Menschen // Studio",
    "post-occupancy review": "Nachnutzungsbewertung",
    "questions // answers": "Fragen // Antworten",
    "raw concrete, unfinished oak, and oxidized copper. we select materials for their capacity to age with grace and accumulate meaning.": "Rohbeton, unbehandelter Eichenholz und oxidiertes Kupfer. Wir wählen Materialien nach ihrer Fähigkeit aus, mit Anmut zu altern und Bedeutung zu sammeln.",
    "schematic design developed through models, drawings, and material samples. we present three distinct concepts and refine the selected direction iteratively.": "Schematische Gestaltung, die durch Modelle, Zeichnungen und Materialproben entwickelt wurde. Wir präsentieren drei unterschiedliche Konzepte und verfeinern die ausgewählte Richtung iterativ.",
    "site supervision throughout the construction phase. we conduct weekly reviews with the contractor and issue formal site observation reports.": "Baustellenüberwachung während der gesamten Bauphase. Wir führen wöchentliche Überprüfungen mit dem Auftragnehmer durch und erstellen formelle Baustellenbeobachtungsberichte.",
    "the absence of form is form. empty space is designed with the same rigour as occupied volume.": "Die Abwesenheit von Form ist Form. Leerraum wird mit der gleichen Strenge gestaltet wie besetztes Volumen.",
    "the obsidian villa": "Die Obsidianvilla",
    "the return of the pure volume": "Die Rückkehr des reinen Volumens",
    "the studio.": "Das Büro.",
    "the vision": "Die Vision",
    "trained at the eth zürich and the architectural association. elias leads design strategy and maintains relationships with structural engineering consultants across europe.": "Ausgebildet an der ETH Zürich und der Architectural Association. Elias leitet die Entwurfsstrategie und pflegt die Kontakte zu Tragwerksplanern in ganz Europa.",
    "view all work": "Alle Arbeiten ansehen",
    "view map of silence": "Karte der Stille anzeigen",
    "wallpaper* design award": "Wallpaper* Designpreis",
    "we accept a limited number of commissions each cycle to ensure the structural integrity and conceptual purity of every space.": "Wir akzeptieren in jedem Zyklus eine begrenzte Anzahl von Aufträgen, um die strukturelle Integrität und die konzeptionelle Reinheit jedes Raumes zu gewährleisten.",
    "we welcome site visits by appointment. our material library and model archive are available for viewing during studio hours, tuesday through friday.": "Wir begrüßen Besuche vor Ort nach Vereinbarung. Unsere Materialbibliothek und unser Modellarchiv sind während der Studiozeiten, von Dienstag bis Freitag, zur Einsichtnahme verfügbar.",
    "what is your minimum project budget?": "Was ist Ihr Mindestprojektbudget?",
    "what we": "Was wir",
    "work.": "arbeit.",
    "years practice": "Jahre Praxis",
  },
  pt: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in light.\"": "«A arquitetura é o jogo sábio, correto e magnífico, dos volumes reunidos sob a luz.»",
    "\"we subtract until only the": "«Subtraímos até que só o",
    "archdaily building of the year": "Edifício do Ano Archdaily",
    "architectural interventions that harmonize human ritual with the absolute geometry of nature.": "Intervenções arquitetónicas que harmonizam o ritual humano com a geometria absoluta da natureza.",
    "archive of form": "Arquivo da forma",
    "as seen": "Como visto",
    "build the": "Construir o",
    "build.": "construir.",
    "can i visit your studio?": "Posso visitar o seu estúdio?",
    "commercial design": "Design Comercial",
    "concept design": "Design de conceito",
    "design": "Design",
    "design director": "Diretor de Design",
    "do you work internationally?": "Trabalham internacionalmente?",
    "elias vorn: 'we subtract until only the essential remains'": "Elias Vorn: «Subtraímos até só restar o essencial»",
    "every space is designed from its light source outward. natural illumination is the primary material — all structure serves it.": "Cada espaço é projetado a partir da sua fonte de luz para fora. A iluminação natural é o material principal — toda a estrutura serve-a.",
    "how long does a typical project take?": "Quanto tempo leva um projeto típico?",
    "how we": "Como nós",
    "inside the obsidian villa: restraint as luxury": "Dentro de la Vila Obsidiana: contenção como luxo",
    "lighting design": "Design de iluminação",
    "material memory: how symmetry studio chooses its palette": "Memória Material: como o Symmetry Studio escolhe a sua palete",
    "method // process": "Método // Processo",
    "people // studio": "Pessoas // Estúdio",
    "post-occupancy review": "Revisão pós-ocupação",
    "questions // answers": "Perguntas // Respostas",
    "raw concrete, unfinished oak, and oxidized copper. we select materials for their capacity to age with grace and accumulate meaning.": "Betão cru, carvalho não acabado e cobre oxidado. Selecionamos materiais pela sua capacidade de envelhecer com graça e acumular significado.",
    "schematic design developed through models, drawings, and material samples. we present three distinct concepts and refine the selected direction iteratively.": "Design esquemático desenvolvido através de modelos, desenhos e amostras de materiais. Apresentamos três conceitos distintos e refinamos a direção selecionada de forma iterativa.",
    "site supervision throughout the construction phase. we conduct weekly reviews with the contractor and issue formal site observation reports.": "Supervisão do local durante toda a fase de construção. Realizamos revisões semanais com o empreiteiro e emitimos relatórios formais de observação do local.",
    "the absence of form is form. empty space is designed with the same rigour as occupied volume.": "A ausência de forma é forma. O espaço vazio é projetado com a mesma rigor que o volume ocupado.",
    "the obsidian villa": "A Vila Obsidiana",
    "the return of the pure volume": "O regresso do volume puro",
    "the studio.": "O atelier.",
    "the vision": "A visão",
    "trained at the eth zürich and the architectural association. elias leads design strategy and maintains relationships with structural engineering consultants across europe.": "Formado na ETH de Zurique e na Architectural Association. Elias lidera a estratégia de conceção e mantém a relação com os gabinetes de estruturas na Europa.",
    "view all work": "Ver todos os trabalhos",
    "view map of silence": "Ver mapa do silêncio",
    "wallpaper* design award": "Prémio de Design Wallpaper*",
    "we accept a limited number of commissions each cycle to ensure the structural integrity and conceptual purity of every space.": "Aceitamos um número limitado de comissões a cada ciclo para garantir a integridade estrutural e a pureza conceptual de cada espaço.",
    "we welcome site visits by appointment. our material library and model archive are available for viewing during studio hours, tuesday through friday.": "Recebemos visitas ao local com marcação. A nossa biblioteca de materiais e arquivo de modelos estão disponíveis para consulta durante o horário de estúdio, de terça a sexta-feira.",
    "what is your minimum project budget?": "Qual é o seu orçamento mínimo para o projeto?",
    "what we": "O que",
    "work.": "trabalho.",
    "years practice": "Anos de Prática",
  },
};
