/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "rituals": "Rituels",
    "sculpted & structured": "Sculpté et structuré",
    "architectural nails": "Ongles architecturaux",
    "couture volume": "Volume couture",
    "velvet lashes": "Cils velours",
    "bio-active glow": "Éclat bio-actif",
    "pure facial ritual": "Rituel visage pur",
    "lamination & tint": "Laminage et teinture",
    "brow architecture": "Architecture du sourcil",
    "cellular": "Infusion",
    "infusion.": "cellulaire.",
    "preparation": "Préparation",
    "deep thermal cleansing using ozonated steam.": "Nettoyage thermique profond à la vapeur ozonée.",
    "a minimalist approach to nail architecture. focused on structural health and clean aesthetic lines.": "Une approche minimaliste de l'architecture des ongles. Axée sur la santé structurelle et des lignes esthétiques épurées.",
    "book your ritual.": "Réservez votre Rituel.",
    "framing the face through geometric mapping and custom pigment blending.": "Encadrer le visage grâce à une cartographie géométrique et un mélange de pigments sur mesure.",
    "from €120": "à partir de 120 €",
    "from €145": "à partir de 145 €",
    "from €65": "à partir de 65 €",
    "from €85": "à partir de 85 €",
    "l'atelier is more like a laboratory than a salon. the precision is unmatched.": "L'Atelier est plus comme un laboratoire qu'un salon. La précision est inégalée.",
    "less but": "Moins, mais",
    "select time": "Sélectionnez l'heure",
    "the art of precision": "L'art de la précision",
    "the facial ritual is a total sensory reset. my skin feels architectural.": "Le rituel facial est une réinitialisation sensorielle totale. Ma peau se sent architecturale.",
    "the most clinical yet calming environment i've ever experienced. my nails have never been this healthy.": "L'endroit le plus rigoureux et le plus apaisant que j'aie connu. Mes ongles n'ont jamais été aussi sains.",
    "weightless silk extensions applied with surgical precision for a natural yet profound gaze.": "Extensions en soie légères appliquées avec une précision chirurgicale pour un regard naturel mais profond.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "rituals": "Rituales",
    "sculpted & structured": "Esculpido y estructurado",
    "architectural nails": "Uñas arquitectónicas",
    "couture volume": "Volumen couture",
    "velvet lashes": "Pestañas terciopelo",
    "bio-active glow": "Luminosidad bioactiva",
    "pure facial ritual": "Ritual facial puro",
    "lamination & tint": "Laminado y tinte",
    "brow architecture": "Arquitectura de cejas",
    "cellular": "Infusión",
    "infusion.": "celular.",
    "preparation": "Preparación",
    "deep thermal cleansing using ozonated steam.": "Limpieza térmica profunda con vapor ozonizado.",
    "a minimalist approach to nail architecture. focused on structural health and clean aesthetic lines.": "Un enfoque minimalista de la arquitectura de uñas. Enfocado en la salud estructural y líneas estéticas limpias.",
    "book your ritual.": "Reserva tu Ritual.",
    "framing the face through geometric mapping and custom pigment blending.": "Enmarcando el rostro a través de un mapeo geométrico y una mezcla de pigmentos personalizada.",
    "from €120": "desde 120 €",
    "from €145": "desde 145 €",
    "from €65": "desde 65 €",
    "from €85": "desde 85 €",
    "l'atelier is more like a laboratory than a salon. the precision is unmatched.": "L'Atelier es más como un laboratorio que un salón. La precisión es inigualable.",
    "less but": "Menos, pero",
    "select time": "Selecciona la hora",
    "the art of precision": "El arte de la precisión",
    "the facial ritual is a total sensory reset. my skin feels architectural.": "El ritual facial es un reinicio sensorial total. Mi piel se siente arquitectónica.",
    "the most clinical yet calming environment i've ever experienced. my nails have never been this healthy.": "El lugar más riguroso y a la vez más sereno que he conocido. Mis uñas nunca han estado tan sanas.",
    "weightless silk extensions applied with surgical precision for a natural yet profound gaze.": "Extensiones de seda sin peso aplicadas con precisión quirúrgica para una mirada natural pero profunda.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "rituals": "Rituale",
    "sculpted & structured": "Skulptiert und strukturiert",
    "architectural nails": "Architektonische Nägel",
    "couture volume": "Couture-Volumen",
    "velvet lashes": "Samtwimpern",
    "bio-active glow": "Bioaktiver Glow",
    "pure facial ritual": "Reines Gesichtsritual",
    "lamination & tint": "Lamination und Färbung",
    "brow architecture": "Augenbrauen-Architektur",
    "cellular": "Zelluläre",
    "infusion.": "Infusion.",
    "preparation": "Vorbereitung",
    "deep thermal cleansing using ozonated steam.": "Tiefe thermische Reinigung mit ozonisiertem Dampf.",
    "a minimalist approach to nail architecture. focused on structural health and clean aesthetic lines.": "Ein minimalistischer Ansatz zur Nagelarchitektur. Fokussiert auf strukturelle Gesundheit und klare ästhetische Linien.",
    "book your ritual.": "Buchen Sie Ihr Ritual.",
    "framing the face through geometric mapping and custom pigment blending.": "Das Gesicht durch geometrische Kartierung und maßgeschneiderte Pigmentmischung einrahmen.",
    "from €120": "ab 120 €",
    "from €145": "ab 145 €",
    "from €65": "ab 65 €",
    "from €85": "ab 85 €",
    "l'atelier is more like a laboratory than a salon. the precision is unmatched.": "L'Atelier ist mehr wie ein Labor als ein Salon. Die Präzision ist unübertroffen.",
    "less but": "Weniger, aber",
    "select time": "Wählen Sie die Uhrzeit",
    "the art of precision": "Die Kunst der Präzision",
    "the facial ritual is a total sensory reset. my skin feels architectural.": "Das Gesichtsritual ist ein totaler sensorischer Reset. Meine Haut fühlt sich architektonisch an.",
    "the most clinical yet calming environment i've ever experienced. my nails have never been this healthy.": "Der klinisch sauberste und zugleich ruhigste Ort, den ich je erlebt habe. Meine Nägel waren nie gesünder.",
    "weightless silk extensions applied with surgical precision for a natural yet profound gaze.": "Gewichtslose Seidenverlängerungen, die mit chirurgischer Präzision für einen natürlichen, aber tiefen Blick aufgetragen werden.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "rituals": "Rituais",
    "sculpted & structured": "Esculpido e estruturado",
    "architectural nails": "Unhas arquitetónicas",
    "couture volume": "Volume couture",
    "velvet lashes": "Pestanas veludo",
    "bio-active glow": "Brilho bioativo",
    "pure facial ritual": "Ritual de rosto puro",
    "lamination & tint": "Laminação e coloração",
    "brow architecture": "Arquitetura da sobrancelha",
    "cellular": "Infusão",
    "infusion.": "celular.",
    "preparation": "Preparação",
    "deep thermal cleansing using ozonated steam.": "Limpeza térmica profunda com vapor ozonizado.",
    "a minimalist approach to nail architecture. focused on structural health and clean aesthetic lines.": "Uma abordagem minimalista à arquitetura das unhas. Focada na saúde estrutural e em linhas estéticas limpas.",
    "book your ritual.": "Reserve o seu Ritual.",
    "framing the face through geometric mapping and custom pigment blending.": "Emoldurando o rosto através de mapeamento geométrico e mistura de pigmentos personalizada.",
    "from €120": "a partir de 120 €",
    "from €145": "a partir de 145 €",
    "from €65": "a partir de 65 €",
    "from €85": "a partir de 85 €",
    "l'atelier is more like a laboratory than a salon. the precision is unmatched.": "L'Atelier é mais como um laboratório do que um salão. A precisão é incomparável.",
    "less but": "Menos, mas",
    "select time": "Selecione a hora",
    "the art of precision": "A arte da precisão",
    "the facial ritual is a total sensory reset. my skin feels architectural.": "O ritual facial é um reinício sensorial total. A minha pele sente-se arquitetónica.",
    "the most clinical yet calming environment i've ever experienced. my nails have never been this healthy.": "O sítio mais rigoroso e ao mesmo tempo mais sereno que conheci. As minhas unhas nunca estiveram tão saudáveis.",
    "weightless silk extensions applied with surgical precision for a natural yet profound gaze.": "Extensões de seda sem peso aplicadas com precisão cirúrgica para um olhar natural, mas profundo.",
  },
};
