/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Une sélection d'affaires marquantes où notre conseil a créé un précédent, protégé des intérêts souverains, ou obtenu des décisions qui ont déplacé les limites du droit international.",
    "attorneys worldwide": "Avocats dans le Monde Entier",
    "begin the conversation": "Entamer la conversation",
    "carve-out & spin-off counsel": "Conseiller en carve-out et spin-off",
    "cases that": "Des dossiers qui",
    "client portal": "Portail Client",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Chaque bureau applique les mêmes protocoles, la même qualité de conseil et le même engagement de confidentialité — quel que soit le fuseau horaire.",
    "head of global litigation": "Responsable des Litiges Mondiaux",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Survolez un portrait pour lire la biographie d'un associé. Notre direction vient des plus hauts rangs du barreau international, de l'administration et de la magistrature.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Conseil en droit international d'une distinction singulière, opérant dans six bureaux à travers le monde depuis plus d'un siècle.",
    "new york": "New York",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "Notre équipe d'accueil est joignable à toute heure. Toute demande est traitée en confidentialité absolue, sous le secret professionnel.",
    "request a consultation": "Demander une consultation",
    "request counsel": "Demander un conseil",
    "schedule a consultation": "Planifier une consultation",
    "the berlin infrastructure accord": "L'Accord sur l'Infrastructure de Berlin",
    "the firm in numbers": "Le cabinet en chiffres",
    "the law.": "font le droit.",
    "view all partners": "Voir tous les associés",
    "view practice areas": "Voir les domaines de pratique",
    "years of combined partnership": "Années de Partenariat Combiné",
  },
  es: {
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Una selección de asuntos señalados en los que nuestro consejo creó precedente, protegió intereses soberanos u obtuvo resoluciones que desplazaron los límites del derecho internacional.",
    "attorneys worldwide": "Abogados en Todo el Mundo",
    "begin the conversation": "Iniciar la conversación",
    "carve-out & spin-off counsel": "Asesor en carve-out y spin-off",
    "cases that": "Casos que",
    "client portal": "Portal del Cliente",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Cada oficina aplica los mismos protocolos, la misma calidad de consejo y el mismo compromiso de confidencialidad, sea cual sea el huso horario.",
    "head of global litigation": "Jefe de Litigios Globales",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Pase el cursor sobre un retrato para leer la biografía de un socio. Nuestra dirección procede de los rangos más altos de la abogacía internacional, la administración y la magistratura.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Asesoría en derecho internacional de singular distinción, operando en seis oficinas globales durante más de un siglo.",
    "new york": "Nueva York",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "Nuestro equipo de recepción está disponible a cualquier hora. Toda consulta se trata con confidencialidad absoluta, bajo el secreto profesional.",
    "request a consultation": "Solicitar una consulta",
    "request counsel": "Solicitar asesoramiento",
    "schedule a consultation": "Programar una consulta",
    "the berlin infrastructure accord": "El Acuerdo de Infraestructura de Berlín",
    "the firm in numbers": "El despacho en cifras",
    "the law.": "hacen el derecho.",
    "view all partners": "Ver todos los socios",
    "view practice areas": "Ver áreas de práctica",
    "years of combined partnership": "Años de Asociación Combinada",
  },
  de: {
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Eine Auswahl wegweisender Mandate, in denen unsere Beratung Präzedenz schuf, souveräne Interessen schützte oder Entscheidungen erwirkte, die die Grenzen des Völkerrechts verschoben.",
    "attorneys worldwide": "Rechtsanwälte weltweit",
    "begin the conversation": "Das Gespräch beginnen",
    "carve-out & spin-off counsel": "Berater für Carve-out und Spin-off",
    "cases that": "Fälle, die",
    "client portal": "Kundenportal",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Jedes Büro arbeitet nach denselben Protokollen, mit derselben Beratungsqualität und derselben Verschwiegenheitspflicht — unabhängig von der Zeitzone.",
    "head of global litigation": "Leiter der globalen Rechtsstreitigkeiten",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Fahren Sie über ein Porträt, um die Biografie eines Partners zu lesen. Unsere Führung stammt aus den höchsten Rängen der internationalen Anwaltschaft, der Verwaltung und der Justiz.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Internationale Rechtsberatung von singularer Bedeutung, die seit über einem Jahrhundert in sechs globalen Büros tätig ist.",
    "new york": "New York",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "Unser Aufnahmeteam ist rund um die Uhr erreichbar. Jede Anfrage wird unter dem Anwaltsgeheimnis absolut vertraulich behandelt.",
    "request a consultation": "Eine Beratung anfordern",
    "request counsel": "Rechtsberatung anfordern",
    "schedule a consultation": "Eine Beratung planen",
    "the berlin infrastructure accord": "Der Berliner Infrastrukturvertrag",
    "the firm in numbers": "Die Kanzlei in Zahlen",
    "the law.": "das Recht prägen.",
    "view all partners": "Alle Partner ansehen",
    "view practice areas": "Praxisbereiche anzeigen",
    "years of combined partnership": "Jahre kombinierter Partnerschaft",
  },
  pt: {
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Uma seleção de casos marcantes em que o nosso aconselhamento criou precedente, protegeu interesses soberanos ou obteve decisões que deslocaram os limites do direito internacional.",
    "attorneys worldwide": "Advogados em Todo o Mundo",
    "begin the conversation": "Iniciar a conversa",
    "carve-out & spin-off counsel": "Consultor de carve-out e spin-off",
    "cases that": "Casos que",
    "client portal": "Portal do Cliente",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Cada escritório aplica os mesmos protocolos, a mesma qualidade de aconselhamento e o mesmo compromisso de confidencialidade — seja qual for o fuso horário.",
    "head of global litigation": "Chefe de Litígios Globais",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Passe o cursor sobre um retrato para ler a biografia de um sócio. A nossa direção vem dos mais altos escalões da advocacia internacional, da administração e da magistratura.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Assessoria em direito internacional de distinção singular, operando em seis escritórios globais há mais de um século.",
    "new york": "Nova Iorque",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "A nossa equipa de receção está disponível a qualquer hora. Todo o pedido é tratado com confidencialidade absoluta, ao abrigo do segredo profissional.",
    "request a consultation": "Solicitar uma consulta",
    "request counsel": "Solicitar aconselhamento",
    "schedule a consultation": "Agendar uma consulta",
    "the berlin infrastructure accord": "O Acordo de Infraestrutura de Berlim",
    "the firm in numbers": "A sociedade em números",
    "the law.": "fazem o direito.",
    "view all partners": "Ver todos os sócios",
    "view practice areas": "Ver áreas de prática",
    "years of combined partnership": "Anos de Parceria Combinada",
  },
};
