/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "for over a century, alderton & sterling has represented sovereign governments, global corporations, and ultra-high-net-worth families in the most consequential legal matters of the age.": "Depuis plus d'un siècle, le cabinet représente des États, des groupes internationaux et de grandes familles dans les dossiers les plus complexes.",
    "four integrated practice groups, each ranked band 1 by chambers & partners globally. our practitioners operate across 60 countries, drawing on a depth of expertise that comes only from a century of unbroken practice at the highest level.": "Quatre pôles intégrés, tous classés Band 1 par Chambers & Partners. Nos avocats interviennent dans soixante pays.",
    "our m&a practice advises on the most consequential cross-border transactions in the world — sovereign fund acquisitions, hostile takeover defenses, and transformative restructurings where billions and reputations are at stake.": "Notre pôle fusions-acquisitions conseille les opérations transfrontalières les plus lourdes : acquisitions par des fonds souverains, défense contre les offres hostiles.",
    "advised three sovereign governments on the legal architecture underpinning a €34 billion cross-border energy infrastructure treaty — a matter of first impression before the european court of justice.": "Conseil de trois États sur l'architecture juridique d'un traité d'infrastructures énergétiques transfrontalier de 34 milliards d'euros.",
    "led the defence in the largest antitrust proceeding in singapore's history, establishing the evidentiary standard for algorithmic market dominance across apac jurisdictions.": "Défense dans la plus grande procédure de concurrence de l'histoire de Singapour, qui a fixé le standard de preuve de la position dominante algorithmique.",
    "orchestrated simultaneous chapter 11 and english administration proceedings for a 12  €billion asset manager, preserving value for 60 000 investors across 14 countries.": "Conduite simultanée d'une procédure Chapter 11 et d'une administration anglaise pour un gestionnaire d'actifs de 12 milliards d'euros, en préservant la valeur pour 60 000 investisseurs.",
    "represented claimant in an icsid arbitration arising from unlawful expropriation of pharmaceutical manufacturing assets, a proceeding spanning seven years and four continents.": "Représentation du demandeur dans un arbitrage CIRDI né de l'expropriation illicite d'actifs de production pharmaceutique, sur plusieurs années.",
    "2.1b € award — largest icsid award in the pharmaceutical sector.": "Sentence de 2,1 Md€ — la plus élevée jamais rendue par le CIRDI dans le secteur pharmaceutique.",
    ". regulated by the solicitors regulation authority. all rights reserved.": ". Réglementé par la Solicitors Regulation Authority. Tous droits réservés.",
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Une sélection d'affaires marquantes où notre conseil a créé un précédent, protégé des intérêts souverains, ou obtenu des décisions qui ont déplacé les limites du droit international.",
    "attorneys worldwide": "Avocats dans le Monde Entier",
    "begin the conversation": "Entamer la conversation",
    "carve-out & spin-off counsel": "Conseiller en carve-out et spin-off",
    "cases that": "Des dossiers qui",
    "client portal": "Portail Client",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Chaque bureau applique les mêmes protocoles, la même qualité de conseil et le même engagement de confidentialité — quel que soit le fuseau horaire.",
    "head of global litigation": "Responsable des Litiges Mondiaux",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Survolez un portrait pour lire la biographie d'un associé. Notre direction vient des plus hauts rangs du barreau international, de l'administration et de la magistrature.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Conseil en droit international d'une distinction singulière, opérant dans six bureaux à travers le monde depuis plus d'un siècle.",
    "new york": "New York",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "Notre équipe d'accueil est joignable à toute heure. Toute demande est traitée en confidentialité absolue, sous le secret professionnel.",
    "request a consultation": "Demander une consultation",
    "request counsel": "Demander un conseil",
    "schedule a consultation": "Planifier une consultation",
    "the berlin infrastructure accord": "L'Accord sur l'Infrastructure de Berlin",
    "the firm in numbers": "Le cabinet en chiffres",
    "the law.": "font le droit.",
    "view all partners": "Voir tous les associés",
    "view practice areas": "Voir les domaines de pratique",
    "years of combined partnership": "Années de Partenariat Combiné",
  },
  es: {
    "for over a century, alderton & sterling has represented sovereign governments, global corporations, and ultra-high-net-worth families in the most consequential legal matters of the age.": "Desde hace más de un siglo, el despacho representa a Estados, grupos internacionales y grandes familias en los asuntos más complejos.",
    "four integrated practice groups, each ranked band 1 by chambers & partners globally. our practitioners operate across 60 countries, drawing on a depth of expertise that comes only from a century of unbroken practice at the highest level.": "Cuatro áreas integradas, todas clasificadas Band 1 por Chambers & Partners. Nuestros abogados intervienen en sesenta países.",
    "our m&a practice advises on the most consequential cross-border transactions in the world — sovereign fund acquisitions, hostile takeover defenses, and transformative restructurings where billions and reputations are at stake.": "Nuestra área de fusiones y adquisiciones asesora las operaciones transfronterizas más pesadas: adquisiciones por fondos soberanos, defensa ante ofertas hostiles.",
    "advised three sovereign governments on the legal architecture underpinning a €34 billion cross-border energy infrastructure treaty — a matter of first impression before the european court of justice.": "Asesoramiento a tres Estados sobre la arquitectura jurídica de un tratado de infraestructuras energéticas transfronterizo de 34 000 millones de euros.",
    "led the defence in the largest antitrust proceeding in singapore's history, establishing the evidentiary standard for algorithmic market dominance across apac jurisdictions.": "Defensa en el mayor procedimiento de competencia de la historia de Singapur, que fijó el estándar probatorio de la posición dominante algorítmica.",
    "orchestrated simultaneous chapter 11 and english administration proceedings for a 12  €billion asset manager, preserving value for 60 000 investors across 14 countries.": "Conducción simultánea de un Chapter 11 y de una administración inglesa para una gestora de 12 000 millones de euros, preservando el valor para 60 000 inversores.",
    "represented claimant in an icsid arbitration arising from unlawful expropriation of pharmaceutical manufacturing assets, a proceeding spanning seven years and four continents.": "Representación del demandante en un arbitraje CIADI nacido de la expropiación ilícita de activos de producción farmacéutica, a lo largo de varios años.",
    "2.1b € award — largest icsid award in the pharmaceutical sector.": "Laudo de 2 100 M€ — el más alto dictado por el CIADI en el sector farmacéutico.",
    ". regulated by the solicitors regulation authority. all rights reserved.": ". Regulado por la Solicitors Regulation Authority. Todos los derechos reservados.",
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Una selección de asuntos señalados en los que nuestro consejo creó precedente, protegió intereses soberanos u obtuvo resoluciones que desplazaron los límites del derecho internacional.",
    "attorneys worldwide": "Abogados en Todo el Mundo",
    "begin the conversation": "Iniciar la conversación",
    "carve-out & spin-off counsel": "Asesor en carve-out y spin-off",
    "cases that": "Casos que",
    "client portal": "Portal del Cliente",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Cada oficina aplica los mismos protocolos, la misma calidad de consejo y el mismo compromiso de confidencialidad, sea cual sea el huso horario.",
    "head of global litigation": "Jefe de Litigios Globales",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Pase el cursor sobre un retrato para leer la biografía de un socio. Nuestra dirección procede de los rangos más altos de la abogacía internacional, la administración y la magistratura.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Asesoría en derecho internacional de singular distinción, operando en seis oficinas globales durante más de un siglo.",
    "new york": "Nueva York",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "Nuestro equipo de recepción está disponible a cualquier hora. Toda consulta se trata con confidencialidad absoluta, bajo el secreto profesional.",
    "request a consultation": "Solicitar una consulta",
    "request counsel": "Solicitar asesoramiento",
    "schedule a consultation": "Programar una consulta",
    "the berlin infrastructure accord": "El Acuerdo de Infraestructura de Berlín",
    "the firm in numbers": "El despacho en cifras",
    "the law.": "hacen el derecho.",
    "view all partners": "Ver todos los socios",
    "view practice areas": "Ver áreas de práctica",
    "years of combined partnership": "Años de Asociación Combinada",
  },
  de: {
    "for over a century, alderton & sterling has represented sovereign governments, global corporations, and ultra-high-net-worth families in the most consequential legal matters of the age.": "Seit über einem Jahrhundert vertritt die Kanzlei Staaten, internationale Konzerne und große Familien in den komplexesten Verfahren.",
    "four integrated practice groups, each ranked band 1 by chambers & partners globally. our practitioners operate across 60 countries, drawing on a depth of expertise that comes only from a century of unbroken practice at the highest level.": "Vier integrierte Praxisgruppen, sämtlich von Chambers & Partners als Band 1 eingestuft. Unsere Anwälte arbeiten in sechzig Ländern.",
    "our m&a practice advises on the most consequential cross-border transactions in the world — sovereign fund acquisitions, hostile takeover defenses, and transformative restructurings where billions and reputations are at stake.": "Unsere M&A-Praxis berät bei den gewichtigsten grenzüberschreitenden Transaktionen: Übernahmen durch Staatsfonds, Abwehr feindlicher Angebote.",
    "advised three sovereign governments on the legal architecture underpinning a €34 billion cross-border energy infrastructure treaty — a matter of first impression before the european court of justice.": "Beratung von drei Staaten zur rechtlichen Architektur eines grenzüberschreitenden Energieinfrastruktur-Vertrags über 34 Milliarden Euro.",
    "led the defence in the largest antitrust proceeding in singapore's history, establishing the evidentiary standard for algorithmic market dominance across apac jurisdictions.": "Verteidigung im größten Kartellverfahren der Geschichte Singapurs, das den Beweisstandard für algorithmische Marktbeherrschung setzte.",
    "orchestrated simultaneous chapter 11 and english administration proceedings for a 12  €billion asset manager, preserving value for 60 000 investors across 14 countries.": "Gleichzeitige Führung eines Chapter-11- und eines englischen Administrationsverfahrens für einen Vermögensverwalter über 12 Milliarden Euro, unter Erhalt des Werts für 60 000 Anleger.",
    "represented claimant in an icsid arbitration arising from unlawful expropriation of pharmaceutical manufacturing assets, a proceeding spanning seven years and four continents.": "Vertretung der Klägerin in einem ICSID-Schiedsverfahren wegen rechtswidriger Enteignung pharmazeutischer Produktionsanlagen, über mehrere Jahre.",
    "2.1b € award — largest icsid award in the pharmaceutical sector.": "Schiedsspruch über 2,1 Mrd. € — der höchste ICSID-Spruch im Pharmasektor.",
    ". regulated by the solicitors regulation authority. all rights reserved.": ". Reguliert durch die Solicitors Regulation Authority. Alle Rechte vorbehalten.",
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Eine Auswahl wegweisender Mandate, in denen unsere Beratung Präzedenz schuf, souveräne Interessen schützte oder Entscheidungen erwirkte, die die Grenzen des Völkerrechts verschoben.",
    "attorneys worldwide": "Rechtsanwälte weltweit",
    "begin the conversation": "Das Gespräch beginnen",
    "carve-out & spin-off counsel": "Berater für Carve-out und Spin-off",
    "cases that": "Fälle, die",
    "client portal": "Kundenportal",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Jedes Büro arbeitet nach denselben Protokollen, mit derselben Beratungsqualität und derselben Verschwiegenheitspflicht — unabhängig von der Zeitzone.",
    "head of global litigation": "Leiter der globalen Rechtsstreitigkeiten",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Fahren Sie über ein Porträt, um die Biografie eines Partners zu lesen. Unsere Führung stammt aus den höchsten Rängen der internationalen Anwaltschaft, der Verwaltung und der Justiz.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Internationale Rechtsberatung von singularer Bedeutung, die seit über einem Jahrhundert in sechs globalen Büros tätig ist.",
    "new york": "New York",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "Unser Aufnahmeteam ist rund um die Uhr erreichbar. Jede Anfrage wird unter dem Anwaltsgeheimnis absolut vertraulich behandelt.",
    "request a consultation": "Eine Beratung anfordern",
    "request counsel": "Rechtsberatung anfordern",
    "schedule a consultation": "Eine Beratung planen",
    "the berlin infrastructure accord": "Der Berliner Infrastrukturvertrag",
    "the firm in numbers": "Die Kanzlei in Zahlen",
    "the law.": "das Recht prägen.",
    "view all partners": "Alle Partner ansehen",
    "view practice areas": "Praxisbereiche anzeigen",
    "years of combined partnership": "Jahre kombinierter Partnerschaft",
  },
  pt: {
    "for over a century, alderton & sterling has represented sovereign governments, global corporations, and ultra-high-net-worth families in the most consequential legal matters of the age.": "Há mais de um século, o escritório representa Estados, grupos internacionais e grandes famílias nos processos mais complexos.",
    "four integrated practice groups, each ranked band 1 by chambers & partners globally. our practitioners operate across 60 countries, drawing on a depth of expertise that comes only from a century of unbroken practice at the highest level.": "Quatro áreas integradas, todas classificadas Band 1 pela Chambers & Partners. Os nossos advogados intervêm em sessenta países.",
    "our m&a practice advises on the most consequential cross-border transactions in the world — sovereign fund acquisitions, hostile takeover defenses, and transformative restructurings where billions and reputations are at stake.": "A nossa área de fusões e aquisições aconselha as operações transfronteiriças mais pesadas: aquisições por fundos soberanos, defesa contra ofertas hostis.",
    "advised three sovereign governments on the legal architecture underpinning a €34 billion cross-border energy infrastructure treaty — a matter of first impression before the european court of justice.": "Aconselhamento a três Estados sobre a arquitetura jurídica de um tratado de infraestruturas energéticas transfronteiriço de 34 mil milhões de euros.",
    "led the defence in the largest antitrust proceeding in singapore's history, establishing the evidentiary standard for algorithmic market dominance across apac jurisdictions.": "Defesa no maior processo de concorrência da história de Singapura, que fixou o padrão de prova da posição dominante algorítmica.",
    "orchestrated simultaneous chapter 11 and english administration proceedings for a 12  €billion asset manager, preserving value for 60 000 investors across 14 countries.": "Condução simultânea de um Chapter 11 e de uma administração inglesa para uma gestora de 12 mil milhões de euros, preservando o valor para 60 000 investidores.",
    "represented claimant in an icsid arbitration arising from unlawful expropriation of pharmaceutical manufacturing assets, a proceeding spanning seven years and four continents.": "Representação do demandante numa arbitragem CIRDI nascida da expropriação ilícita de ativos de produção farmacêutica, ao longo de vários anos.",
    "2.1b € award — largest icsid award in the pharmaceutical sector.": "Sentença de 2,1 mil M€ — a mais alta alguma vez proferida pelo CIRDI no setor farmacêutico.",
    ". regulated by the solicitors regulation authority. all rights reserved.": ". Regulado pela Solicitors Regulation Authority. Todos os direitos reservados.",
    "a selection of landmark matters in which our counsel established new precedent, protected sovereign interests, or delivered outcomes that redefined the boundaries of what is possible in international law.": "Uma seleção de casos marcantes em que o nosso aconselhamento criou precedente, protegeu interesses soberanos ou obteve decisões que deslocaram os limites do direito internacional.",
    "attorneys worldwide": "Advogados em Todo o Mundo",
    "begin the conversation": "Iniciar a conversa",
    "carve-out & spin-off counsel": "Consultor de carve-out e spin-off",
    "cases that": "Casos que",
    "client portal": "Portal do Cliente",
    "each office operates under the same protocols, the same quality of counsel, and the same commitment to client confidentiality — regardless of time zone.": "Cada escritório aplica os mesmos protocolos, a mesma qualidade de aconselhamento e o mesmo compromisso de confidencialidade — seja qual for o fuso horário.",
    "head of global litigation": "Chefe de Litígios Globais",
    "hover any portrait to read a partner biography. our leadership team is drawn from the most senior ranks of the international bar, government, and the judiciary.": "Passe o cursor sobre um retrato para ler a biografia de um sócio. A nossa direção vem dos mais altos escalões da advocacia internacional, da administração e da magistratura.",
    "international law counsel of singular distinction, operating across six global offices for over a century.": "Assessoria em direito internacional de distinção singular, operando em seis escritórios globais há mais de um século.",
    "new york": "Nova Iorque",
    "our intake team is available around the clock. all enquiries are treated with absolute confidentiality under our global attorney-client privilege policy.": "A nossa equipa de receção está disponível a qualquer hora. Todo o pedido é tratado com confidencialidade absoluta, ao abrigo do segredo profissional.",
    "request a consultation": "Solicitar uma consulta",
    "request counsel": "Solicitar aconselhamento",
    "schedule a consultation": "Agendar uma consulta",
    "the berlin infrastructure accord": "O Acordo de Infraestrutura de Berlim",
    "the firm in numbers": "A sociedade em números",
    "the law.": "fazem o direito.",
    "view all partners": "Ver todos os sócios",
    "view practice areas": "Ver áreas de prática",
    "years of combined partnership": "Anos de Parceria Combinada",
  },
};
