/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "manifesto": "Manifeste",
    "commission": "Nous confier un projet",
    "markets": "Marchés",
    "strategies": "Stratégies",
    "traders": "Opérateurs",
    "archive": "Archives",
    "e-commerce": "Commerce en ligne",
    "origins": "Origines",
    "source": "Origine",
    "roast": "Torréfaction",
    "cup": "Tasse",
    "programs": "Programmes",
    "members": "Membres",
    "destinations": "Destinations",
    "years experience": "Ans d'expérience",
    "releases": "Sorties",
    "tour": "Tournée",
    "store": "Boutique",
    "waste diverted": "Déchets détournés",
    "residential": "Résidentiel",
    "penthouse": "Attique",
    "concierge": "Conciergerie",
    "locations": "Nos adresses",
    "seller portal": "Espace vendeurs",
    "legacy": "Héritage",
    "select seat": "Choisir sa place",
    "offense": "Attaque",
    "intelligence": "Renseignement",
    "global nodes": "Nœuds mondiaux",
    "enlist": "Nous rejoindre",
    "market": "Marché",
    "curators": "Curateurs",
    "stats": "Chiffres",
    "connect wallet": "Connecter le portefeuille",
    "sanctuary": "Le sanctuaire",
    "retreats": "Retraites",
    "essence": "Essence",
    "landmark cases": "Affaires marquantes",
    "authority": "Autorité",
    "vegan & cruelty-free": "Végane et sans cruauté",
    "design": "DESIGN",
    "content": "CONTENU",
    "we design digital experiences that": "Nous concevons des expériences numériques qui",
    "\"a brand is no longer just a logo or a color palette. in the digital age, a brand is defined by how it behaves, how it moves, and the friction it introduces to force engagement.\"": "« Une marque n'est plus un logo ni une palette de couleurs. À l'ère numérique, une marque se définit par sa manière de se comporter, de bouger, et par la friction qu'elle impose pour créer l'engagement. »",
    "digital": "RÉALITÉ",
    "reality": "NUMÉRIQUE",
    "in a sea of templates and infinite scrolling, user attention is the most valuable currency. we believe that true digital luxury isn't about minimalism—it's about intentional friction and memorable interactions.": "Dans un océan de gabarits et de défilement sans fin, l'attention est la monnaie la plus rare. Le vrai luxe numérique n'est pas le minimalisme : c'est la friction choisie et l'interaction dont on se souvient.",
    "by combining brutalist architectural principles with hyper-fluid webgl rendering, we construct platforms that don't just inform users; they make them feel something.": "En croisant les principes de l'architecture brutaliste et un rendu WebGL très fluide, nous construisons des plateformes qui ne se contentent pas d'informer : elles font ressentir quelque chose.",
    "deep dive into your industry, competitors, and technical constraints. we define the baseline metrics for success.": "Plongée dans votre métier, vos concurrents et vos contraintes techniques. Nous fixons les repères chiffrés de la réussite.",
    "structural architecture. we establish the skeleton of the product without the distraction of visual design.": "Architecture structurelle : on pose le squelette du produit avant toute question d'apparence.",
    "exploring typography, motion, and visual paradigms. creating the moodboards that define the final aesthetic.": "Exploration des typographies, du mouvement et des partis pris visuels. Les planches d'ambiance fixent l'esthétique finale.",
    "pixel-perfect execution. bridging the gap between design and development with fluid animations.": "Exécution au pixel près : le pont entre la maquette et le code, avec des animations fluides.",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Un digest mensuel des tendances en design, des expériences WebGL et des nouvelles du studio.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Un cadre rigoureux, éprouvé au combat, conçu pour éliminer l'ambiguïté et fournir des résultats exceptionnels dans les délais.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Une expérience numérique sensorielle axée sur des interactions fluides en webgl pour refléter la viscosité des sérums premium.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Création de systèmes visuels qui s'adaptent d'un écran de smartwatch à un panneau d'affichage. Typographie, théorie des couleurs et directives de mouvement.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Architecture UX basée sur les données conçue pour réduire les frictions et améliorer la rétention des utilisateurs. Nous cartographions l'ensemble du parcours utilisateur avant d'écrire une ligne de code.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Archive numérique pour une maison de mode légendaire, utilisant le scroll-jacking typographique pour raconter des récits historiques.",
    "let's": "Allons-y",
    "new york": "New York",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Repousser ce qu'un navigateur sait afficher. WebGL, Three.js et chaînes de rendu sur mesure, qui font d'un simple défilement une expérience de cinéma.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Configureur de voiture basé sur le navigateur en temps réel utilisant WebGPU pour un ray tracing photoréaliste.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Redéfinir les plateformes de trading institutionnelles grâce à une interface utilisateur brutaliste et une visualisation de données à micro-latence.",
    "scroll to expand": "Faites défiler pour développer",
    "the reveal doctrine": "Notre doctrine",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Nous bâtissons des sites et des applications qui deviennent le centre de gravité de votre marque. Conversion, performance et tenue esthétique.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Nous agissons comme une extension de votre équipe interne, fournissant la puissance spécialisée nécessaire pour exécuter des transformations numériques ambitieuses.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "manifesto": "Manifiesto",
    "commission": "Encargar un proyecto",
    "markets": "Mercados",
    "strategies": "Estrategias",
    "traders": "Operadores",
    "archive": "Archivo",
    "e-commerce": "Comercio electrónico",
    "origins": "Orígenes",
    "source": "Origen",
    "roast": "Tueste",
    "cup": "Taza",
    "programs": "Programas",
    "members": "Miembros",
    "destinations": "Destinos",
    "years experience": "Años de experiencia",
    "releases": "Lanzamientos",
    "tour": "Gira",
    "store": "Tienda",
    "waste diverted": "Residuos desviados",
    "residential": "Residencial",
    "penthouse": "Ático",
    "concierge": "Conserjería",
    "locations": "Nuestras direcciones",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Elegir asiento",
    "offense": "Ataque",
    "intelligence": "Inteligencia",
    "global nodes": "Nodos mundiales",
    "enlist": "Únase a nosotros",
    "market": "Mercado",
    "curators": "Comisarios",
    "stats": "Cifras",
    "connect wallet": "Conectar la cartera",
    "sanctuary": "El santuario",
    "retreats": "Retiros",
    "essence": "Esencia",
    "landmark cases": "Casos emblemáticos",
    "authority": "Autoridad",
    "vegan & cruelty-free": "Vegano y sin crueldad",
    "design": "DISEÑO",
    "content": "CONTENIDO",
    "we design digital experiences that": "Diseñamos experiencias digitales que",
    "\"a brand is no longer just a logo or a color palette. in the digital age, a brand is defined by how it behaves, how it moves, and the friction it introduces to force engagement.\"": "«Una marca ya no es un logo ni una paleta de colores. En la era digital, una marca se define por cómo se comporta, cómo se mueve y por la fricción que impone para generar compromiso.»",
    "digital": "REALIDAD",
    "reality": "DIGITAL",
    "in a sea of templates and infinite scrolling, user attention is the most valuable currency. we believe that true digital luxury isn't about minimalism—it's about intentional friction and memorable interactions.": "En un océano de plantillas y scroll infinito, la atención es la moneda más escasa. El verdadero lujo digital no es el minimalismo: es la fricción elegida y la interacción que se recuerda.",
    "by combining brutalist architectural principles with hyper-fluid webgl rendering, we construct platforms that don't just inform users; they make them feel something.": "Cruzando los principios de la arquitectura brutalista con un renderizado WebGL muy fluido, construimos plataformas que no solo informan: hacen sentir algo.",
    "deep dive into your industry, competitors, and technical constraints. we define the baseline metrics for success.": "Inmersión en su sector, sus competidores y sus limitaciones técnicas. Fijamos las métricas de referencia del éxito.",
    "structural architecture. we establish the skeleton of the product without the distraction of visual design.": "Arquitectura estructural: colocamos el esqueleto del producto antes de cualquier cuestión de apariencia.",
    "exploring typography, motion, and visual paradigms. creating the moodboards that define the final aesthetic.": "Exploración de tipografías, movimiento y partidos visuales. Los moodboards fijan la estética final.",
    "pixel-perfect execution. bridging the gap between design and development with fluid animations.": "Ejecución al píxel: el puente entre la maqueta y el código, con animaciones fluidas.",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Un resumen mensual de tendencias de diseño, experimentos de WebGL y noticias del estudio.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Un marco riguroso, probado en batalla, diseñado para eliminar la ambigüedad y ofrecer resultados excepcionales en el plazo.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Una experiencia digital sensorial centrada en interacciones fluidas de webgl para reflejar la viscosidad de los sueros premium.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Creando sistemas visuales que escalan desde la pantalla de un smartwatch hasta una valla publicitaria. Tipografía, teoría del color y directrices de movimiento.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Arquitectura UX basada en datos diseñada para reducir la fricción y elevar la retención de usuarios. Mapeamos todo el viaje del usuario antes de escribir una línea de código.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Archivo digital para una casa de moda legendaria, utilizando scroll-jacking tipográfico para contar narrativas históricas.",
    "let's": "Vamos",
    "new york": "Nueva York",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Empujar lo que un navegador puede mostrar. WebGL, Three.js y cadenas de render a medida, que convierten el desplazamiento en una experiencia de cine.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Configurador de coches basado en navegador en tiempo real que utiliza WebGPU para trazado de rayos fotorrealista.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Redefiniendo las plataformas de trading institucionales a través de una interfaz de usuario brutalista y visualización de datos de micro-latencia.",
    "scroll to expand": "Desplázate para expandir",
    "the reveal doctrine": "Nuestra doctrina",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Construimos sitios y aplicaciones que se convierten en el centro de gravedad de su marca. Conversión, rendimiento y calidad estética.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Operamos como una extensión de su equipo interno, proporcionando la potencia especializada necesaria para ejecutar transformaciones digitales ambiciosas.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "manifesto": "Manifest",
    "commission": "Projekt anfragen",
    "markets": "Märkte",
    "strategies": "Strategien",
    "traders": "Händler",
    "archive": "Archiv",
    "e-commerce": "E-Commerce",
    "origins": "Herkünfte",
    "source": "Ursprung",
    "roast": "Röstung",
    "cup": "Tasse",
    "programs": "Programme",
    "members": "Mitglieder",
    "destinations": "Reiseziele",
    "years experience": "Jahre Erfahrung",
    "releases": "Veröffentlichungen",
    "tour": "Tour",
    "store": "Shop",
    "waste diverted": "Umgeleitete Abfälle",
    "residential": "Wohnbau",
    "penthouse": "Penthouse",
    "concierge": "Concierge-Service",
    "locations": "Unsere Standorte",
    "seller portal": "Verkäuferbereich",
    "legacy": "Erbe",
    "select seat": "Platz wählen",
    "offense": "Angriff",
    "intelligence": "Aufklärung",
    "global nodes": "Weltweite Knoten",
    "enlist": "Mitmachen",
    "market": "Markt",
    "curators": "Kuratoren",
    "stats": "Zahlen",
    "connect wallet": "Wallet verbinden",
    "sanctuary": "Das Refugium",
    "retreats": "Retreats",
    "essence": "Essenz",
    "landmark cases": "Wegweisende Fälle",
    "authority": "Autorität",
    "vegan & cruelty-free": "Vegan und tierversuchsfrei",
    "design": "DESIGN",
    "content": "INHALT",
    "we design digital experiences that": "Wir gestalten digitale Erlebnisse, die",
    "\"a brand is no longer just a logo or a color palette. in the digital age, a brand is defined by how it behaves, how it moves, and the friction it introduces to force engagement.\"": "„Eine Marke ist längst kein Logo und keine Farbpalette mehr. Im digitalen Zeitalter zeigt sie sich darin, wie sie sich verhält, wie sie sich bewegt, und in der Reibung, die sie erzeugt.“",
    "digital": "DIGITALE",
    "reality": "WIRKLICHKEIT",
    "in a sea of templates and infinite scrolling, user attention is the most valuable currency. we believe that true digital luxury isn't about minimalism—it's about intentional friction and memorable interactions.": "In einem Meer aus Vorlagen und endlosem Scrollen ist Aufmerksamkeit die knappste Währung. Echter digitaler Luxus ist nicht Minimalismus, sondern gewollte Reibung und Interaktionen, die bleiben.",
    "by combining brutalist architectural principles with hyper-fluid webgl rendering, we construct platforms that don't just inform users; they make them feel something.": "Wir verbinden die Prinzipien brutalistischer Architektur mit sehr flüssigem WebGL-Rendering und bauen Plattformen, die nicht nur informieren, sondern etwas auslösen.",
    "deep dive into your industry, competitors, and technical constraints. we define the baseline metrics for success.": "Tiefer Einstieg in Ihre Branche, Ihre Wettbewerber und Ihre technischen Grenzen. Wir legen die Kennzahlen für den Erfolg fest.",
    "structural architecture. we establish the skeleton of the product without the distraction of visual design.": "Strukturelle Architektur: Wir setzen das Skelett des Produkts, bevor es um Optik geht.",
    "exploring typography, motion, and visual paradigms. creating the moodboards that define the final aesthetic.": "Erkundung von Typografie, Bewegung und visuellen Setzungen. Die Moodboards legen die endgültige Ästhetik fest.",
    "pixel-perfect execution. bridging the gap between design and development with fluid animations.": "Pixelgenaue Umsetzung: die Brücke zwischen Entwurf und Code, mit flüssigen Animationen.",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Ein monatlicher Überblick über Designtrends, WebGL-Experimente und Studio-Nachrichten.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Ein rigoroser, kampferprobter Rahmen, der entwickelt wurde, um Unklarheiten zu beseitigen und außergewöhnliche Ergebnisse im Zeitrahmen zu liefern.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Ein sensorisches digitales Erlebnis, das sich auf flüssige WebGL-Interaktionen konzentriert, um die Viskosität von Premium-Seren widerzuspiegeln.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Visuelle Systeme gestalten, die von einem Smartwatch-Bildschirm bis zu einem Billboard skalieren. Typografie, Farbtheorie und Bewegungsrichtlinien.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Datengetriebene UX-Architektur, die darauf ausgelegt ist, Reibung zu reduzieren und die Benutzerbindung zu erhöhen. Wir kartieren die gesamte Benutzerreise, bevor wir eine Zeile Code schreiben.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Digitales Archiv für ein traditionsreiches Modehaus, das typografisches Scroll-Jacking nutzt, um historische Erzählungen zu erzählen.",
    "let's": "Lass uns",
    "new york": "New York",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Die Grenzen dessen verschieben, was ein Browser darstellen kann. WebGL, Three.js und eigene Shader-Pipelines, die aus bloßem Scrollen ein Kinoerlebnis machen.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Echtzeit-Browser-basierter Auto-Konfigurator, der WebGPU für fotorealistisches Raytracing nutzt.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Institutionelle Handelsplattformen durch brutalistische UI und Mikro-Latenz-Datenvisualisierung neu definieren.",
    "scroll to expand": "Scrollen zum Erweitern",
    "the reveal doctrine": "Unsere Doktrin",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Wir bauen Websites und Anwendungen, die zum Schwerpunkt Ihrer Marke werden. Konversion, Leistung und ästhetische Souveränität.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Wir agieren als Erweiterung Ihres internen Teams und bieten die spezialisierte Schlagkraft, die erforderlich ist, um ehrgeizige digitale Transformationen umzusetzen.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "manifesto": "Manifesto",
    "commission": "Confiar-nos um projeto",
    "markets": "Mercados",
    "strategies": "Estratégias",
    "traders": "Operadores",
    "archive": "Arquivo",
    "e-commerce": "Comércio eletrónico",
    "origins": "Origens",
    "source": "Origem",
    "roast": "Torra",
    "cup": "Chávena",
    "programs": "Programas",
    "members": "Membros",
    "destinations": "Destinos",
    "years experience": "Anos de experiência",
    "releases": "Lançamentos",
    "tour": "Digressão",
    "store": "Loja",
    "waste diverted": "Resíduos desviados",
    "residential": "Residencial",
    "penthouse": "Cobertura",
    "concierge": "Concierge",
    "locations": "As nossas moradas",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Escolher lugar",
    "offense": "Ataque",
    "intelligence": "Informações",
    "global nodes": "Nós mundiais",
    "enlist": "Junte-se a nós",
    "market": "Mercado",
    "curators": "Curadores",
    "stats": "Números",
    "connect wallet": "Ligar a carteira",
    "sanctuary": "O santuário",
    "retreats": "Retiros",
    "essence": "Essência",
    "landmark cases": "Casos marcantes",
    "authority": "Autoridade",
    "vegan & cruelty-free": "Vegano e sem crueldade",
    "design": "DESIGN",
    "content": "CONTEÚDO",
    "we design digital experiences that": "Concebemos experiências digitais que",
    "\"a brand is no longer just a logo or a color palette. in the digital age, a brand is defined by how it behaves, how it moves, and the friction it introduces to force engagement.\"": "«Uma marca já não é um logótipo nem uma paleta de cores. Na era digital, define-se pela forma como se comporta, como se move e pela fricção que impõe para criar envolvimento.»",
    "digital": "REALIDADE",
    "reality": "DIGITAL",
    "in a sea of templates and infinite scrolling, user attention is the most valuable currency. we believe that true digital luxury isn't about minimalism—it's about intentional friction and memorable interactions.": "Num oceano de modelos e scroll infinito, a atenção é a moeda mais rara. O verdadeiro luxo digital não é o minimalismo: é a fricção escolhida e a interação de que nos lembramos.",
    "by combining brutalist architectural principles with hyper-fluid webgl rendering, we construct platforms that don't just inform users; they make them feel something.": "Ao cruzar os princípios da arquitetura brutalista com uma renderização WebGL muito fluida, construímos plataformas que não se limitam a informar: fazem sentir algo.",
    "deep dive into your industry, competitors, and technical constraints. we define the baseline metrics for success.": "Mergulho no seu setor, nos concorrentes e nas restrições técnicas. Definimos as métricas de referência do sucesso.",
    "structural architecture. we establish the skeleton of the product without the distraction of visual design.": "Arquitetura estrutural: colocamos o esqueleto do produto antes de qualquer questão de aparência.",
    "exploring typography, motion, and visual paradigms. creating the moodboards that define the final aesthetic.": "Exploração de tipografias, movimento e partidos visuais. Os moodboards fixam a estética final.",
    "pixel-perfect execution. bridging the gap between design and development with fluid animations.": "Execução ao pixel: a ponte entre a maquete e o código, com animações fluidas.",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Um resumo mensal de tendências de design, experiências WebGL e notícias do estúdio.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Uma estrutura rigorosa, testada em batalha, projetada para eliminar a ambiguidade e entregar resultados excepcionais dentro do prazo.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Uma experiência digital sensorial focada em interações fluidas de webgl para espelhar a viscosidade de soros premium.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Criando sistemas visuais que escalam de uma tela de smartwatch a um outdoor. Tipografia, teoria das cores e diretrizes de movimento.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Arquitetura UX orientada a dados projetada para reduzir a fricção e aumentar a retenção de usuários. Mapeamos toda a jornada do usuário antes de escrever uma linha de código.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Arquivo digital para uma casa de moda lendária, utilizando scroll-jacking tipográfico para contar narrativas históricas.",
    "let's": "Vamos",
    "new york": "Nova Iorque",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Empurrar o que um navegador consegue mostrar. WebGL, Three.js e cadeias de render à medida, que transformam o deslocamento numa experiência de cinema.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Configurador de automóveis baseado em navegador em tempo real que utiliza WebGPU para rastreamento de raios fotorrealista.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Redefinindo plataformas de negociação institucionais através de uma interface de utilizador brutalista e visualização de dados de micro-latência.",
    "scroll to expand": "Desça para expandir",
    "the reveal doctrine": "A nossa doutrina",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Construímos sites e aplicações que se tornam o centro de gravidade da sua marca. Conversão, desempenho e qualidade estética.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Operamos como uma extensão da sua equipe interna, fornecendo a força especializada necessária para executar transformações digitais ambiciosas.",
  },
};
