/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    ", and the": ", et le",
    ", how it": ", comment il",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Un digest mensuel des tendances en design, des expériences WebGL et des nouvelles du studio.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Un cadre rigoureux, éprouvé au combat, conçu pour éliminer l'ambiguïté et fournir des résultats exceptionnels dans les délais.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Une expérience numérique sensorielle axée sur des interactions fluides en webgl pour refléter la viscosité des sérums premium.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Création de systèmes visuels qui s'adaptent d'un écran de smartwatch à un panneau d'affichage. Typographie, théorie des couleurs et directives de mouvement.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Architecture UX basée sur les données conçue pour réduire les frictions et améliorer la rétention des utilisateurs. Nous cartographions l'ensemble du parcours utilisateur avant d'écrire une ligne de code.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Archive numérique pour une maison de mode légendaire, utilisant le scroll-jacking typographique pour raconter des récits historiques.",
    "it introduces to force engagement.\"": "il introduit pour forcer l'engagement.\"",
    "let's": "Allons-y",
    "new york": "New York",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Repousser ce qu'un navigateur sait afficher. WebGL, Three.js et chaînes de rendu sur mesure, qui font d'un simple défilement une expérience de cinéma.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Configureur de voiture basé sur le navigateur en temps réel utilisant WebGPU pour un ray tracing photoréaliste.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Redéfinir les plateformes de trading institutionnelles grâce à une interface utilisateur brutaliste et une visualisation de données à micro-latence.",
    "scroll to expand": "Faites défiler pour développer",
    "the reveal doctrine": "Notre doctrine",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Nous bâtissons des sites et des applications qui deviennent le centre de gravité de votre marque. Conversion, performance et tenue esthétique.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Nous agissons comme une extension de votre équipe interne, fournissant la puissance spécialisée nécessaire pour exécuter des transformations numériques ambitieuses.",
  },
  es: {
    ", and the": ", y el",
    ", how it": ", cómo",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Un resumen mensual de tendencias de diseño, experimentos de WebGL y noticias del estudio.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Un marco riguroso, probado en batalla, diseñado para eliminar la ambigüedad y ofrecer resultados excepcionales en el plazo.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Una experiencia digital sensorial centrada en interacciones fluidas de webgl para reflejar la viscosidad de los sueros premium.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Creando sistemas visuales que escalan desde la pantalla de un smartwatch hasta una valla publicitaria. Tipografía, teoría del color y directrices de movimiento.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Arquitectura UX basada en datos diseñada para reducir la fricción y elevar la retención de usuarios. Mapeamos todo el viaje del usuario antes de escribir una línea de código.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Archivo digital para una casa de moda legendaria, utilizando scroll-jacking tipográfico para contar narrativas históricas.",
    "it introduces to force engagement.\"": "introduce para forzar el compromiso.\"",
    "let's": "Vamos",
    "new york": "Nueva York",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Empujar lo que un navegador puede mostrar. WebGL, Three.js y cadenas de render a medida, que convierten el desplazamiento en una experiencia de cine.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Configurador de coches basado en navegador en tiempo real que utiliza WebGPU para trazado de rayos fotorrealista.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Redefiniendo las plataformas de trading institucionales a través de una interfaz de usuario brutalista y visualización de datos de micro-latencia.",
    "scroll to expand": "Desplázate para expandir",
    "the reveal doctrine": "Nuestra doctrina",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Construimos sitios y aplicaciones que se convierten en el centro de gravedad de su marca. Conversión, rendimiento y calidad estética.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Operamos como una extensión de su equipo interno, proporcionando la potencia especializada necesaria para ejecutar transformaciones digitales ambiciosas.",
  },
  de: {
    ", and the": ", und das",
    ", how it": ", wie es",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Ein monatlicher Überblick über Designtrends, WebGL-Experimente und Studio-Nachrichten.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Ein rigoroser, kampferprobter Rahmen, der entwickelt wurde, um Unklarheiten zu beseitigen und außergewöhnliche Ergebnisse im Zeitrahmen zu liefern.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Ein sensorisches digitales Erlebnis, das sich auf flüssige WebGL-Interaktionen konzentriert, um die Viskosität von Premium-Seren widerzuspiegeln.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Visuelle Systeme gestalten, die von einem Smartwatch-Bildschirm bis zu einem Billboard skalieren. Typografie, Farbtheorie und Bewegungsrichtlinien.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Datengetriebene UX-Architektur, die darauf ausgelegt ist, Reibung zu reduzieren und die Benutzerbindung zu erhöhen. Wir kartieren die gesamte Benutzerreise, bevor wir eine Zeile Code schreiben.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Digitales Archiv für ein traditionsreiches Modehaus, das typografisches Scroll-Jacking nutzt, um historische Erzählungen zu erzählen.",
    "it introduces to force engagement.\"": "es führt ein, um Engagement zu erzwingen.\"",
    "let's": "Lass uns",
    "new york": "New York",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Die Grenzen dessen verschieben, was ein Browser darstellen kann. WebGL, Three.js und eigene Shader-Pipelines, die aus bloßem Scrollen ein Kinoerlebnis machen.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Echtzeit-Browser-basierter Auto-Konfigurator, der WebGPU für fotorealistisches Raytracing nutzt.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Institutionelle Handelsplattformen durch brutalistische UI und Mikro-Latenz-Datenvisualisierung neu definieren.",
    "scroll to expand": "Scrollen zum Erweitern",
    "the reveal doctrine": "Unsere Doktrin",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Wir bauen Websites und Anwendungen, die zum Schwerpunkt Ihrer Marke werden. Konversion, Leistung und ästhetische Souveränität.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Wir agieren als Erweiterung Ihres internen Teams und bieten die spezialisierte Schlagkraft, die erforderlich ist, um ehrgeizige digitale Transformationen umzusetzen.",
  },
  pt: {
    ", and the": ", e o",
    ", how it": ", como",
    "a monthly digest of design trends, webgl experiments, and studio news.": "Um resumo mensal de tendências de design, experiências WebGL e notícias do estúdio.",
    "a rigorous, battle-tested framework designed to eliminate ambiguity and deliver exceptional results on timeline.": "Uma estrutura rigorosa, testada em batalha, projetada para eliminar a ambiguidade e entregar resultados excepcionais dentro do prazo.",
    "a sensory digital experience focusing on fluid webgl interactions to mirror the viscosity of premium serums.": "Uma experiência digital sensorial focada em interações fluidas de webgl para espelhar a viscosidade de soros premium.",
    "crafting visual systems that scale from a smartwatch screen to a billboard. typography, color theory, and motion guidelines.": "Criando sistemas visuais que escalam de uma tela de smartwatch a um outdoor. Tipografia, teoria das cores e diretrizes de movimento.",
    "data-driven ux architecture designed to reduce friction and elevate user retention. we map the entire user journey before writing a line of code.": "Arquitetura UX orientada a dados projetada para reduzir a fricção e aumentar a retenção de usuários. Mapeamos toda a jornada do usuário antes de escrever uma linha de código.",
    "digital archive for a legacy fashion house, utilizing typographic scroll-jacking to tell historical narratives.": "Arquivo digital para uma casa de moda lendária, utilizando scroll-jacking tipográfico para contar narrativas históricas.",
    "it introduces to force engagement.\"": "introduz para forçar o envolvimento.\"",
    "let's": "Vamos",
    "new york": "Nova Iorque",
    "pushing the boundaries of what a browser can render. webgl, three.js, and custom shader pipelines that turn ordinary scroll into cinematic experiences.": "Empurrar o que um navegador consegue mostrar. WebGL, Three.js e cadeias de render à medida, que transformam o deslocamento numa experiência de cinema.",
    "real-time browser-based car configurator utilizing webgpu for photorealistic ray tracing.": "Configurador de automóveis baseado em navegador em tempo real que utiliza WebGPU para rastreamento de raios fotorrealista.",
    "redefining institutional trading platforms through brutalist ui and micro-latency data visualization.": "Redefinindo plataformas de negociação institucionais através de uma interface de utilizador brutalista e visualização de dados de micro-latência.",
    "scroll to expand": "Desça para expandir",
    "the reveal doctrine": "A nossa doutrina",
    "we build flagship websites and web applications that serve as the digital epicenter of your brand. focusing on conversion, performance, and aesthetic dominance.": "Construímos sites e aplicações que se tornam o centro de gravidade da sua marca. Conversão, desempenho e qualidade estética.",
    "we operate as an extension of your internal team, providing the specialized firepower needed to execute ambitious digital transformations.": "Operamos como uma extensão da sua equipe interna, fornecendo a força especializada necessária para executar transformações digitais ambiciosas.",
  },
};
