/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "equipment": "Équipement",
    "enquiry": "Nous écrire",
    "highest": "Les plus hauts",
    "summits": "sommets",
    "elite art conservation & private registry": "Conservation d'œuvres et registre privé",
    "collector vault": "Coffre du collectionneur",
    "materials": "Matériaux",
    "specs": "Caractéristiques",
    "applications": "Applications",
    "research": "Recherche",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Soie au graphène. Maille bioluminescente CRISPR. Laine à mémoire de forme en nitinol. Nous concevons des textiles au croisement de la science des matériaux, de la biotechnologie et de la haute couture.",
    "core directive": "Directive fondamentale",
    "uptime protocol": "Protocole de disponibilité",
    "expandable storage": "Stockage extensible",
    "provision node": "Provisionner un nœud",
    "product": "Produit",
    "marketing": "Marketing",
    "properties": "Nos biens",
    "market": "Le marché",
    "neighborhoods": "Les quartiers",
    "establishment": "Fondation",
    "gold": "Or",
    "time": "Le temps",
    "newsletter": "Lettre d'information",
    "planning": "Le planning",
    "heritage": "Héritage",
    "every mandate begins with an hour-long consultation. we listen to what you want, what you truly need, and what history you want to inherit.": "Chaque mandat commence par une heure d'entretien. Nous écoutons ce que vous voulez, ce dont vous avez réellement besoin, et l'histoire dont vous voulez hériter.",
    "70% of our transactions never appear on public listings. our network of notaires, architects, and owners gives you access to the invisible market.": "Sept transactions sur dix ne paraissent jamais dans une annonce. Notre réseau de notaires, d'architectes et de propriétaires vous ouvre le marché invisible.",
    "we negotiate with rigor and discretion. our legal and technical partners ensure every stone of the transaction is solid before you commit.": "Nous négocions avec rigueur et discrétion. Nos partenaires juridiques et techniques vérifient chaque pierre de l'opération avant que vous ne vous engagiez.",
    "from the promesse to the acte authentique, we stand beside you at every signature. after the keys: we remain your resource for everything that follows.": "De la promesse à l'acte authentique, nous sommes à côté de vous à chaque signature. Après les clés, nous restons votre interlocuteur pour tout ce qui suit.",
    "the negotiation they conducted on our behalf saved us €180 000. quietly, professionally, without drama.": "La négociation qu'ils ont menée pour nous a économisé 180 000 €. Sans bruit, avec professionnalisme.",
    "i had worked with three agencies before. this was different from the first meeting. they asked questions no one had asked.": "J'avais travaillé avec trois agences auparavant. C'était différent de la première rencontre. Ils ont posé des questions que personne n'avait posées.",
    "literary, artistic, refined. the spiritual home of the parisian intellectual. cafés where sartre wrote, galleries where history was made.": "Littéraire, artistique, raffiné. La patrie spirituelle de l'intellectuel parisien. Des cafés où Sartre écrivait, des galeries où l'histoire s'est faite.",
    "plan du site": "Plan du site",
    "rive gauche found us our apartment in four weeks. three off-market viewings, one offer. they know this city in a way that takes decades to learn.": "Rive Gauche nous a trouvé notre appartement en quatre semaines. Trois visites hors marché, une offre. Ils connaissent cette ville d'une manière qui prend des décennies à apprendre.",
    "the negotiation they conducted on our behalf saved us €180,000. quietly, professionally, without drama.": "La négociation qu'ils ont menée en notre nom nous a fait économiser 180 000 €. Discrètement, professionnellement, sans drame.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "equipment": "Equipamiento",
    "enquiry": "Escríbanos",
    "highest": "Las más altas",
    "summits": "cumbres",
    "elite art conservation & private registry": "Conservación de obras y registro privado",
    "collector vault": "Cámara del coleccionista",
    "materials": "Materiales",
    "specs": "Características",
    "applications": "Aplicaciones",
    "research": "Investigación",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda con grafeno. Malla bioluminiscente CRISPR. Lana con memoria de forma de nitinol. Diseñamos textiles en el cruce de la ciencia de materiales, la biotecnología y la alta costura.",
    "core directive": "Directiva fundamental",
    "uptime protocol": "Protocolo de disponibilidad",
    "expandable storage": "Almacenamiento ampliable",
    "provision node": "Aprovisionar un nodo",
    "product": "Producto",
    "marketing": "Marketing",
    "properties": "Nuestros inmuebles",
    "market": "El mercado",
    "neighborhoods": "Los barrios",
    "establishment": "Fundación",
    "gold": "Oro",
    "time": "El tiempo",
    "newsletter": "Boletín",
    "planning": "El horario",
    "heritage": "Herencia",
    "every mandate begins with an hour-long consultation. we listen to what you want, what you truly need, and what history you want to inherit.": "Cada mandato empieza por una hora de entrevista. Escuchamos lo que quiere, lo que realmente necesita y la historia que quiere heredar.",
    "70% of our transactions never appear on public listings. our network of notaires, architects, and owners gives you access to the invisible market.": "Siete de cada diez operaciones nunca aparecen en un anuncio. Nuestra red de notarios, arquitectos y propietarios le abre el mercado invisible.",
    "we negotiate with rigor and discretion. our legal and technical partners ensure every stone of the transaction is solid before you commit.": "Negociamos con rigor y discreción. Nuestros socios jurídicos y técnicos verifican cada piedra de la operación antes de que se comprometa.",
    "from the promesse to the acte authentique, we stand beside you at every signature. after the keys: we remain your resource for everything that follows.": "De la promesa a la escritura pública, estamos a su lado en cada firma. Tras las llaves, seguimos siendo su interlocutor para todo lo que venga.",
    "the negotiation they conducted on our behalf saved us €180 000. quietly, professionally, without drama.": "La negociación que llevaron por nosotros ahorró 180 000 €. Sin ruido, con profesionalidad.",
    "i had worked with three agencies before. this was different from the first meeting. they asked questions no one had asked.": "Había trabajado con tres agencias antes. Esto fue diferente de la primera reunión. Hicieron preguntas que nadie había hecho.",
    "literary, artistic, refined. the spiritual home of the parisian intellectual. cafés where sartre wrote, galleries where history was made.": "Literario, artístico, refinado. La patria espiritual del intelectual parisino. Cafés donde escribía Sartre, galerías donde se hizo la historia.",
    "plan du site": "Mapa del sitio",
    "rive gauche found us our apartment in four weeks. three off-market viewings, one offer. they know this city in a way that takes decades to learn.": "Rive Gauche nos encontró nuestro apartamento en cuatro semanas. Tres visitas fuera del mercado, una oferta. Conocen esta ciudad de una manera que lleva décadas aprender.",
    "the negotiation they conducted on our behalf saved us €180,000. quietly, professionally, without drama.": "La negociación que llevaron a cabo en nuestro nombre nos ahorró 180.000 €. Silenciosamente, profesionalmente, sin drama.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "equipment": "Ausrüstung",
    "enquiry": "Anfrage",
    "highest": "Die höchsten",
    "summits": "Gipfel",
    "elite art conservation & private registry": "Kunstkonservierung und privates Register",
    "collector vault": "Sammlertresor",
    "materials": "Werkstoffe",
    "specs": "Kenndaten",
    "applications": "Anwendungen",
    "research": "Forschung",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seide mit Graphen. Biolumineszentes CRISPR-Gewebe. Formgedächtniswolle aus Nitinol. Wir entwickeln Textilien an der Schnittstelle von Materialwissenschaft, Biotechnologie und Haute Couture.",
    "core directive": "Grundsatzdirektive",
    "uptime protocol": "Verfügbarkeitsprotokoll",
    "expandable storage": "Erweiterbarer Speicher",
    "provision node": "Knoten bereitstellen",
    "product": "Produkt",
    "marketing": "Marketing",
    "properties": "Unsere Objekte",
    "market": "Der Markt",
    "neighborhoods": "Die Viertel",
    "establishment": "Gründung",
    "gold": "Gold",
    "time": "Die Zeit",
    "newsletter": "Newsletter",
    "planning": "Der Stundenplan",
    "heritage": "Erbe",
    "every mandate begins with an hour-long consultation. we listen to what you want, what you truly need, and what history you want to inherit.": "Jedes Mandat beginnt mit einem einstündigen Gespräch. Wir hören, was Sie wollen, was Sie wirklich brauchen und welche Geschichte Sie erben möchten.",
    "70% of our transactions never appear on public listings. our network of notaires, architects, and owners gives you access to the invisible market.": "Sieben von zehn Transaktionen erscheinen nie in einem Inserat. Unser Netz aus Notaren, Architekten und Eigentümern öffnet Ihnen den unsichtbaren Markt.",
    "we negotiate with rigor and discretion. our legal and technical partners ensure every stone of the transaction is solid before you commit.": "Wir verhandeln streng und diskret. Unsere juristischen und technischen Partner prüfen jeden Stein des Geschäfts, bevor Sie sich binden.",
    "from the promesse to the acte authentique, we stand beside you at every signature. after the keys: we remain your resource for everything that follows.": "Vom Vorvertrag bis zur notariellen Urkunde stehen wir bei jeder Unterschrift neben Ihnen. Nach der Schlüsselübergabe bleiben wir Ihr Ansprechpartner.",
    "the negotiation they conducted on our behalf saved us €180 000. quietly, professionally, without drama.": "Die Verhandlung, die sie für uns geführt haben, sparte 180 000 €. Ohne Lärm, professionell.",
    "i had worked with three agencies before. this was different from the first meeting. they asked questions no one had asked.": "Ich hatte zuvor mit drei Agenturen gearbeitet. Das war anders als beim ersten Treffen. Sie stellten Fragen, die niemand gestellt hatte.",
    "literary, artistic, refined. the spiritual home of the parisian intellectual. cafés where sartre wrote, galleries where history was made.": "Literarisch, künstlerisch, fein. Die geistige Heimat des Pariser Intellektuellen. Cafés, in denen Sartre schrieb, Galerien, in denen Geschichte gemacht wurde.",
    "plan du site": "Seitenplan",
    "rive gauche found us our apartment in four weeks. three off-market viewings, one offer. they know this city in a way that takes decades to learn.": "Rive Gauche hat uns in vier Wochen unsere Wohnung gefunden. Drei Besichtigungen außerhalb des Marktes, ein Angebot. Sie kennen diese Stadt auf eine Weise, die Jahrzehnte dauert, um sie zu lernen.",
    "the negotiation they conducted on our behalf saved us €180,000. quietly, professionally, without drama.": "Die Verhandlung, die sie in unserem Namen führten, hat uns 180.000 € gespart. Leise, professionell, ohne Drama.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "equipment": "Equipamento",
    "enquiry": "Escreva-nos",
    "highest": "Os mais altos",
    "summits": "cumes",
    "elite art conservation & private registry": "Conservação de obras e registo privado",
    "collector vault": "Cofre do colecionador",
    "materials": "Materiais",
    "specs": "Características",
    "applications": "Aplicações",
    "research": "Investigação",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda com grafeno. Malha bioluminescente CRISPR. Lã com memória de forma em nitinol. Concebemos têxteis no cruzamento da ciência dos materiais, da biotecnologia e da alta-costura.",
    "core directive": "Diretiva fundamental",
    "uptime protocol": "Protocolo de disponibilidade",
    "expandable storage": "Armazenamento expansível",
    "provision node": "Aprovisionar um nó",
    "product": "Produto",
    "marketing": "Marketing",
    "properties": "Os nossos imóveis",
    "market": "O mercado",
    "neighborhoods": "Os bairros",
    "establishment": "Fundação",
    "gold": "Ouro",
    "time": "O tempo",
    "newsletter": "Boletim",
    "planning": "O horário",
    "heritage": "Herança",
    "every mandate begins with an hour-long consultation. we listen to what you want, what you truly need, and what history you want to inherit.": "Cada mandato começa com uma hora de conversa. Ouvimos o que quer, aquilo de que precisa mesmo e a história que quer herdar.",
    "70% of our transactions never appear on public listings. our network of notaires, architects, and owners gives you access to the invisible market.": "Sete em cada dez transações nunca aparecem num anúncio. A nossa rede de notários, arquitetos e proprietários abre-lhe o mercado invisível.",
    "we negotiate with rigor and discretion. our legal and technical partners ensure every stone of the transaction is solid before you commit.": "Negociamos com rigor e discrição. Os nossos parceiros jurídicos e técnicos verificam cada pedra da operação antes de se comprometer.",
    "from the promesse to the acte authentique, we stand beside you at every signature. after the keys: we remain your resource for everything that follows.": "Da promessa à escritura, estamos ao seu lado em cada assinatura. Depois das chaves, continuamos a ser o seu interlocutor para tudo o que venha a seguir.",
    "the negotiation they conducted on our behalf saved us €180 000. quietly, professionally, without drama.": "A negociação que conduziram por nós poupou 180 000 €. Sem ruído, com profissionalismo.",
    "i had worked with three agencies before. this was different from the first meeting. they asked questions no one had asked.": "Eu tinha trabalhado com três agências antes. Isto foi diferente do primeiro encontro. Fizeram perguntas que ninguém tinha feito.",
    "literary, artistic, refined. the spiritual home of the parisian intellectual. cafés where sartre wrote, galleries where history was made.": "Literário, artístico, requintado. A pátria espiritual do intelectual parisiense. Cafés onde Sartre escrevia, galerias onde se fez história.",
    "plan du site": "Mapa do site",
    "rive gauche found us our apartment in four weeks. three off-market viewings, one offer. they know this city in a way that takes decades to learn.": "Rive Gauche encontrou-nos o apartamento em quatro semanas. Três visitas fora do mercado, uma oferta. Eles conhecem esta cidade de uma forma que leva décadas a aprender.",
    "the negotiation they conducted on our behalf saved us €180,000. quietly, professionally, without drama.": "A negociação que realizaram em nosso nome poupou-nos 180.000 €. Silenciosamente, profissionalmente, sem drama.",
  },
};
