/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    ". the universal eye.": ". L'ŒIL UNIVERSEL.",
    "\"situational awareness is no longer a luxury. it is the primary variable of global leadership. master the orbit.\"": "« La connaissance de la situation n'est plus un luxe. C'est la variable première du commandement mondial. Maîtrisez l'orbite. »",
    "best-sellers": "Meilleures ventes",
    "clients satisfaits": "Clients satisfaits",
    "eta 2824-2 / in-house": "ETA 2824-2 / Interne",
    "new season": "Nouvelle Saison",
    "the telegraph": "Le Telegraph",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    ". the universal eye.": ". EL OJO UNIVERSAL.",
    "\"situational awareness is no longer a luxury. it is the primary variable of global leadership. master the orbit.\"": "«La conciencia situacional ya no es un lujo. Es la variable primera del liderazgo mundial. Domine la órbita.»",
    "best-sellers": "Más vendidos",
    "clients satisfaits": "Clientes satisfechos",
    "eta 2824-2 / in-house": "ETA 2824-2 / Interno",
    "new season": "Nueva Temporada",
    "the telegraph": "El Telegraph",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    ". the universal eye.": ". DAS UNIVERSELLE AUGE.",
    "\"situational awareness is no longer a luxury. it is the primary variable of global leadership. master the orbit.\"": "„Lagebewusstsein ist kein Luxus mehr. Es ist die erste Variable globaler Führung. Beherrschen Sie den Orbit.“",
    "best-sellers": "Bestseller",
    "clients satisfaits": "Zufriedene Kunden",
    "eta 2824-2 / in-house": "ETA 2824-2 / In-house",
    "new season": "Neue Saison",
    "the telegraph": "Der Telegraph",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    ". the universal eye.": ". O OLHO UNIVERSAL.",
    "\"situational awareness is no longer a luxury. it is the primary variable of global leadership. master the orbit.\"": "«A consciência situacional já não é um luxo. É a variável primeira da liderança mundial. Domine a órbita.»",
    "best-sellers": "Mais vendidos",
    "clients satisfaits": "Clientes satisfeitos",
    "eta 2824-2 / in-house": "ETA 2824-2 / Interno",
    "new season": "Nova Temporada",
    "the telegraph": "O Telegraph",
  },
};
