/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "programs": "Programmes",
    "coaches": "Les coachs",
    "membership": "Abonnement",
    "types": "Types",
    "integrations": "Intégrations",
    "gdpr": "RGPD",
    "podcast": "Balado",
    "the art": "L'art",
    "finance": "Finance",
    "./view projects": "./voir les projets",
    "/in/rafael-moreau": "/in/rafael-moreau",
    "$ echo $available for work": "$ echo $DISPONIBLE POUR TRAVAILLER",
    "120k req/day": "120K demandes/jour",
    "3 200+ clients": "3 200+ clients",
    "4c72b8e perf: reduce p99 latency by 40% with query optimization": "4c72b8e perf : réduire la latence p99 de 40 % grâce à l'optimisation des requêtes",
    "api design (rest/graphql)": "Conception d'API (REST/GraphQL)",
    "b91e4a1 fix: race condition in concurrent request handler": "b91e4a1 correction : condition de concurrence dans le gestionnaire de requêtes concurrentes",
    "hire me()": "engagez-moi()",
    "rafael.moreau — lead engineer & open-source contributor": "rafael.moreau — ingénieur principal, contributeur au logiciel libre",
    "system design": "Conception de systèmes",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "programs": "Programas",
    "coaches": "Los entrenadores",
    "membership": "Abono",
    "types": "Tipos",
    "integrations": "Integraciones",
    "gdpr": "RGPD",
    "podcast": "Pódcast",
    "the art": "El arte",
    "finance": "Finanzas",
    "./view projects": "./ver proyectos",
    "/in/rafael-moreau": "/in/rafael-moreau",
    "$ echo $available for work": "$ echo $DISPONIBLE PARA TRABAJAR",
    "120k req/day": "120K req/día",
    "3 200+ clients": "3 200+ clientes",
    "4c72b8e perf: reduce p99 latency by 40% with query optimization": "4c72b8e perf: reducir la latencia p99 en un 40% con optimización de consultas",
    "api design (rest/graphql)": "Diseño de API (REST/GraphQL)",
    "b91e4a1 fix: race condition in concurrent request handler": "b91e4a1 corrección: condición de carrera en el manejador de solicitudes concurrentes",
    "hire me()": "contrátame()",
    "rafael.moreau — lead engineer & open-source contributor": "rafael.moreau — ingeniero jefe y colaborador de código abierto",
    "system design": "Diseño de sistemas",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "programs": "Programme",
    "coaches": "Die Coaches",
    "membership": "Mitgliedschaft",
    "types": "Typen",
    "integrations": "Integrationen",
    "gdpr": "DSGVO",
    "podcast": "Podcast",
    "the art": "Die Kunst",
    "finance": "Finanzen",
    "./view projects": "./projekte ansehen",
    "/in/rafael-moreau": "/in/rafael-moreau",
    "$ echo $available for work": "$ echo $VERFÜGBAR FÜR ARBEIT",
    "120k req/day": "120K Anfragen/Tag",
    "3 200+ clients": "3 200+ Kunden",
    "4c72b8e perf: reduce p99 latency by 40% with query optimization": "4c72b8e perf: p99-Latenz um 40 % durch Abfrageoptimierung reduzieren",
    "api design (rest/graphql)": "API-Design (REST/GraphQL)",
    "b91e4a1 fix: race condition in concurrent request handler": "b91e4a1 Fehlerbehebung: Wettlaufbedingung im gleichzeitigen Anforderungs-Handler",
    "hire me()": "stell mich ein()",
    "rafael.moreau — lead engineer & open-source contributor": "rafael.moreau — leitender Entwickler und Open-Source-Beitragender",
    "system design": "Systemdesign",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "programs": "Programas",
    "coaches": "Os treinadores",
    "membership": "Assinatura",
    "types": "Tipos",
    "integrations": "Integrações",
    "gdpr": "RGPD",
    "podcast": "Podcast",
    "the art": "A arte",
    "finance": "Finanças",
    "./view projects": "./ver projetos",
    "/in/rafael-moreau": "/in/rafael-moreau",
    "$ echo $available for work": "$ echo $DISPONÍVEL PARA TRABALHAR",
    "120k req/day": "120K pedidos/dia",
    "3 200+ clients": "3 200+ clientes",
    "4c72b8e perf: reduce p99 latency by 40% with query optimization": "4c72b8e perf: reduzir a latência p99 em 40% com otimização de consultas",
    "api design (rest/graphql)": "Design de API (REST/GraphQL)",
    "b91e4a1 fix: race condition in concurrent request handler": "b91e4a1 correção: condição de corrida no manipulador de solicitações concorrentes",
    "hire me()": "contrate-me()",
    "rafael.moreau — lead engineer & open-source contributor": "rafael.moreau — engenheiro principal e contribuidor de código aberto",
    "system design": "Design de sistemas",
  },
};
