/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "active parcels in our global network right now": "Colis en circulation dans notre réseau en ce moment",
    "client voices": "Voix des clients",
    "delivery journey": "Parcours de livraison",
    "door-to-door in 24–72 hours": "De porte à porte en 24 à 72 heures",
    "end-to-end freight intelligence for modern supply chains. 43 countries, 6 continents, one platform.": "Intelligence de fret de bout en bout pour les chaînes d'approvisionnement modernes. 43 pays, 6 continents, une plateforme.",
    "every mode.": "Tous les modes.",
    "final-mile delivery with signature capture. real-time photo proof uploaded instantly to your tracking portal.": "Livraison du dernier kilomètre avec capture de signature. Preuve photo en temps réel téléchargée instantanément sur votre portail de suivi.",
    "freight quote request": "Demande de devis de fret",
    "from pickup to": "De l'enlèvement à",
    "ftl, ltl, and groupage": "Camion complet, lot partiel et groupage",
    "full container load (fcl) and less-than-container load (lcl) solutions with carrier diversity across 200+ shipping lanes.": "Solutions de chargement complet de conteneur (FCL) et de chargement inférieur au conteneur (LCL) avec diversité de transporteurs sur plus de 200 voies maritimes.",
    "full-truck loads, partial loads, and groupage across europe and beyond — with cross-border clearance in every corridor.": "Chargements complets de camions, chargements partiels et groupage à travers l'Europe et au-delà — avec dédouanement transfrontalier dans chaque corridor.",
    "in transit": "En transit",
    "let&apos;s talk.": "Parlons-en.",
    "long-haul transport via road, air, or sea. gps updates every 15 minutes. predictive eta re-calculated in real time.": "Transport longue distance par route, air ou mer. Mises à jour GPS toutes les 15 minutes. ETA prédictif recalculé en temps réel.",
    "multimodal freight solutions engineered for complex global supply chains — from single pallets to full charter aircraft loads.": "Solutions de fret multimodal conçues pour des chaînes d'approvisionnement mondiales complexes — des palettes uniques aux chargements complets d'avions affrétés.",
    "next-day and same-day options": "Options de livraison le lendemain et le jour même",
    "nexusfreight cut our cross-border transit times by 35%. the customs pre-clearance alone saves us two days on every eu shipment.": "NexusFreight a réduit nos temps de transit transfrontaliers de 35 %. Le pré-dédouanement seul nous fait gagner deux jours sur chaque expédition vers l'UE.",
    "numbers that speak": "Des chiffres qui parlent",
    "on-time rate": "Taux de ponctualité",
    "our brokers handle documentation at every border. pre-clearance reduces dwell time to under 4 hours on average.": "Nos courtiers gèrent la documentation à chaque frontière. Le pré-dédouanement réduit le temps d'attente à moins de 4 heures en moyenne.",
    "our driver collects from your door or warehouse. parcel scanned, weighed, and entered into the system within 60 seconds.": "Notre chauffeur collecte à votre porte ou à votre entrepôt. Colis scanné, pesé et enregistré dans le système en 60 secondes.",
    "our fleet spans short-haul urban delivery vans to long-haul articulated trucks — every vehicle gps-tracked, temperature-monitored, and route-optimized in real time.": "Notre flotte s'étend des fourgonnettes de livraison urbaines à courte distance aux camions articulés à long distance — chaque véhicule est suivi par GPS, surveillé en température et optimisé en temps réel.",
    "port-to-port and door-to-door": "De port à port et de porte à porte",
    "priority air cargo with same-day and next-flight-out options for time-critical shipments across our global airport network.": "Fret aérien prioritaire avec options de livraison le jour même et de prochain vol pour les envois critiques à temps à travers notre réseau aéroportuaire mondial.",
    "proof of delivery.": "preuve de livraison.",
    "quote request received": "Demande de devis reçue",
    "ready to move?": "Prêt à bouger ?",
    "real-time performance metrics from our global operations center — updated every 60 seconds.": "Des indicateurs en temps réel depuis notre centre d'exploitation — actualisés toutes les soixante secondes.",
    "real-time tracking per piece": "Suivi en temps réel, colis par colis",
    "request quote": "Demander un devis",
    "scheduled and on-demand": "Programmé ou à la demande",
    "tell us where you need to go — we'll build a tailored freight solution with competitive rates and a dedicated account manager.": "Dites-nous où il faut aller — nous bâtissons une solution de transport sur mesure, à un tarif compétitif, avec un interlocuteur dédié.",
    "tell us where you need to go — we&apos;ll build a tailored freight solution with competitive rates and a dedicated account manager.": "Dites-nous où vous devez aller — nous construirons une solution de fret sur mesure avec des tarifs compétitifs et un gestionnaire de compte dédié.",
    "the tracking portal is genuinely better than anything we've used before. real-time gps plus predictive etas has transformed our planning.": "Le portail de suivi est vraiment meilleur que tout ce que nous avons utilisé auparavant. Le GPS en temps réel plus les ETA prédictifs a transformé notre planification.",
    "time-guaranteed delivery with proof of delivery, signature capture, and white-glove handling for your most valuable shipments.": "Livraison garantie dans les délais avec preuve de livraison, capture de signature et manutention soignée pour vos envois les plus précieux.",
    "trusted by supply chain leaders": "Fiable pour les leaders de la chaîne d'approvisionnement",
    "we respond within 2 business hours. by submitting, you agree to our terms.": "Nous répondons sous deux heures ouvrées. En envoyant, vous acceptez nos conditions.",
    "we ship temperature-sensitive pharma across 18 countries. nexusfreight's cold-chain compliance has been flawless for 3 years running.": "Nous expédions des produits pharmaceutiques sensibles à la température dans 18 pays. La conformité de la chaîne du froid de NexusFreight est impeccable depuis 3 ans.",
    "weekly departures on all lanes": "Départs hebdomadaires sur toutes les lignes",
    "what we move": "Ce que nous transportons",
    "without limits.": "Sans limites.",
    "your dedicated account manager will reach out within 2 business hours with a tailored freight proposal.": "Votre gestionnaire de compte dédié vous contactera dans les 2 heures ouvrables avec une proposition de fret sur mesure.",
    "your name *": "Votre nom *",
    "your shipment reaches our regional hub. automated sorting, route assignment, and consolidation with compatible loads.": "Votre envoi atteint notre hub régional. Tri automatisé, attribution de routes et consolidation avec des chargements compatibles.",
  },
  es: {
    "active parcels in our global network right now": "Paquetes en circulación en nuestra red en este momento",
    "client voices": "Voces de los clientes",
    "delivery journey": "Viaje de entrega",
    "door-to-door in 24–72 hours": "De puerta a puerta en 24 a 72 horas",
    "end-to-end freight intelligence for modern supply chains. 43 countries, 6 continents, one platform.": "Inteligencia de carga de extremo a extremo para cadenas de suministro modernas. 43 países, 6 continentes, una plataforma.",
    "every mode.": "Todos los modos.",
    "final-mile delivery with signature capture. real-time photo proof uploaded instantly to your tracking portal.": "Entrega de última milla con captura de firma. Prueba fotográfica en tiempo real cargada instantáneamente en su portal de seguimiento.",
    "freight quote request": "Solicitud de cotización de carga",
    "from pickup to": "De la recogida a",
    "ftl, ltl, and groupage": "Camión completo, carga parcial y grupaje",
    "full container load (fcl) and less-than-container load (lcl) solutions with carrier diversity across 200+ shipping lanes.": "Soluciones de Carga Completa de Contenedor (FCL) y Carga Menor que el Contenedor (LCL) con diversidad de transportistas en más de 200 rutas de envío.",
    "full-truck loads, partial loads, and groupage across europe and beyond — with cross-border clearance in every corridor.": "Cargas completas de camiones, cargas parciales y agrupamiento en Europa y más allá — con despacho aduanero transfronterizo en cada corredor.",
    "in transit": "En tránsito",
    "let&apos;s talk.": "Hablemos.",
    "long-haul transport via road, air, or sea. gps updates every 15 minutes. predictive eta re-calculated in real time.": "Transporte de larga distancia por carretera, aire o mar. Actualizaciones de GPS cada 15 minutos. ETA predictivo recalculado en tiempo real.",
    "multimodal freight solutions engineered for complex global supply chains — from single pallets to full charter aircraft loads.": "Soluciones de carga multimodal diseñadas para cadenas de suministro globales complejas — desde palets individuales hasta cargas completas de aviones chárter.",
    "next-day and same-day options": "Opciones de entrega al día siguiente y el mismo día",
    "nexusfreight cut our cross-border transit times by 35%. the customs pre-clearance alone saves us two days on every eu shipment.": "NexusFreight redujo nuestros tiempos de tránsito transfronterizos en un 35%. La pre-autorización aduanera por sí sola nos ahorra dos días en cada envío a la UE.",
    "numbers that speak": "Cifras que hablan",
    "on-time rate": "Tasa de puntualidad",
    "our brokers handle documentation at every border. pre-clearance reduces dwell time to under 4 hours on average.": "Nuestros corredores manejan la documentación en cada frontera. La pre-autorización reduce el tiempo de espera a menos de 4 horas en promedio.",
    "our driver collects from your door or warehouse. parcel scanned, weighed, and entered into the system within 60 seconds.": "Nuestro conductor recoge de su puerta o almacén. Paquete escaneado, pesado e ingresado en el sistema en 60 segundos.",
    "our fleet spans short-haul urban delivery vans to long-haul articulated trucks — every vehicle gps-tracked, temperature-monitored, and route-optimized in real time.": "Nuestra flota abarca furgonetas de entrega urbanas de corta distancia hasta camiones articulados de larga distancia — cada vehículo es rastreado por GPS, monitoreado por temperatura y optimizado en ruta en tiempo real.",
    "port-to-port and door-to-door": "De puerto a puerto y de puerta a puerta",
    "priority air cargo with same-day and next-flight-out options for time-critical shipments across our global airport network.": "Carga aérea prioritaria con opciones de entrega el mismo día y el próximo vuelo para envíos críticos en el tiempo a través de nuestra red aeroportuaria global.",
    "proof of delivery.": "prueba de entrega.",
    "quote request received": "Solicitud de cotización recibida",
    "ready to move?": "¿Listo para moverte?",
    "real-time performance metrics from our global operations center — updated every 60 seconds.": "Indicadores en tiempo real desde nuestro centro de operaciones, actualizados cada sesenta segundos.",
    "real-time tracking per piece": "Seguimiento en tiempo real, bulto a bulto",
    "request quote": "Solicitar cotización",
    "scheduled and on-demand": "Programado o a demanda",
    "tell us where you need to go — we'll build a tailored freight solution with competitive rates and a dedicated account manager.": "Díganos adónde hay que ir: construimos una solución de transporte a medida, a un precio competitivo y con un interlocutor dedicado.",
    "tell us where you need to go — we&apos;ll build a tailored freight solution with competitive rates and a dedicated account manager.": "Díganos a dónde necesita ir — construiremos una solución de carga a medida con tarifas competitivas y un gerente de cuentas dedicado.",
    "the tracking portal is genuinely better than anything we've used before. real-time gps plus predictive etas has transformed our planning.": "El portal de seguimiento es genuinamente mejor que cualquier cosa que hayamos utilizado antes. El GPS en tiempo real más los ETA predictivos ha transformado nuestra planificación.",
    "time-guaranteed delivery with proof of delivery, signature capture, and white-glove handling for your most valuable shipments.": "Entrega garantizada a tiempo con prueba de entrega, captura de firma y manejo de guante blanco para sus envíos más valiosos.",
    "trusted by supply chain leaders": "Confiable para los líderes de la cadena de suministro",
    "we respond within 2 business hours. by submitting, you agree to our terms.": "Respondemos en dos horas hábiles. Al enviar, acepta nuestras condiciones.",
    "we ship temperature-sensitive pharma across 18 countries. nexusfreight's cold-chain compliance has been flawless for 3 years running.": "Enviamos productos farmacéuticos sensibles a la temperatura a 18 países. La conformidad de la cadena de frío de NexusFreight ha sido impecable durante 3 años.",
    "weekly departures on all lanes": "Salidas semanales en todas las rutas",
    "what we move": "Lo que transportamos",
    "without limits.": "Sin límites.",
    "your dedicated account manager will reach out within 2 business hours with a tailored freight proposal.": "Su gerente de cuentas dedicado se comunicará dentro de 2 horas hábiles con una propuesta de carga a medida.",
    "your name *": "Su nombre *",
    "your shipment reaches our regional hub. automated sorting, route assignment, and consolidation with compatible loads.": "Su envío llega a nuestro centro regional. Clasificación automatizada, asignación de rutas y consolidación con cargas compatibles.",
  },
  de: {
    "active parcels in our global network right now": "Sendungen, die gerade in unserem Netz unterwegs sind",
    "client voices": "Stimmen der Kunden",
    "delivery journey": "Lieferreise",
    "door-to-door in 24–72 hours": "Tür-zu-Tür in 24–72 Stunden",
    "end-to-end freight intelligence for modern supply chains. 43 countries, 6 continents, one platform.": "End-to-End-Frachtintelligenz für moderne Lieferketten. 43 Länder, 6 Kontinente, eine Plattform.",
    "every mode.": "Jeder Verkehrsträger.",
    "final-mile delivery with signature capture. real-time photo proof uploaded instantly to your tracking portal.": "Lieferung der letzten Meile mit Unterschriftserfassung. Echtzeit-Fotobeweis wird sofort in Ihr Tracking-Portal hochgeladen.",
    "freight quote request": "Anfrage für Frachtangebot",
    "from pickup to": "Von der Abholung bis",
    "ftl, ltl, and groupage": "Komplettladung, Teilladung und Sammelgut",
    "full container load (fcl) and less-than-container load (lcl) solutions with carrier diversity across 200+ shipping lanes.": "Lösungen für Vollcontainerladung (FCL) und Teilladung (LCL) mit Carrier-Vielfalt über 200+ Versandrouten.",
    "full-truck loads, partial loads, and groupage across europe and beyond — with cross-border clearance in every corridor.": "Voll-Lkw-Ladungen, Teilladungen und Sammelladungen in ganz Europa und darüber hinaus — mit grenzüberschreitender Zollabfertigung in jedem Korridor.",
    "in transit": "Unterwegs",
    "let&apos;s talk.": "Lass uns reden.",
    "long-haul transport via road, air, or sea. gps updates every 15 minutes. predictive eta re-calculated in real time.": "Langstreckentransport über Straße, Luft oder See. GPS-Updates alle 15 Minuten. Vorhergesagte ETA wird in Echtzeit neu berechnet.",
    "multimodal freight solutions engineered for complex global supply chains — from single pallets to full charter aircraft loads.": "Multimodale Frachtlösungen, die für komplexe globale Lieferketten entwickelt wurden — von einzelnen Paletten bis hin zu kompletten Charterflugzeugladungen.",
    "next-day and same-day options": "Optionen für die Lieferung am nächsten Tag und am selben Tag",
    "nexusfreight cut our cross-border transit times by 35%. the customs pre-clearance alone saves us two days on every eu shipment.": "NexusFreight hat unsere grenzüberschreitenden Transitzeiten um 35 % verkürzt. Die Zollvorabfreigabe allein spart uns zwei Tage bei jeder EU-Sendung.",
    "numbers that speak": "Zahlen, die sprechen",
    "on-time rate": "Pünktlichkeitsrate",
    "our brokers handle documentation at every border. pre-clearance reduces dwell time to under 4 hours on average.": "Unsere Broker kümmern sich an jeder Grenze um die Dokumentation. Die Vorabfreigabe reduziert die Verweildauer im Durchschnitt auf unter 4 Stunden.",
    "our driver collects from your door or warehouse. parcel scanned, weighed, and entered into the system within 60 seconds.": "Unser Fahrer holt an Ihrer Tür oder in Ihrem Lager ab. Paket innerhalb von 60 Sekunden gescannt, gewogen und ins System eingegeben.",
    "our fleet spans short-haul urban delivery vans to long-haul articulated trucks — every vehicle gps-tracked, temperature-monitored, and route-optimized in real time.": "Unsere Flotte reicht von städtischen Lieferwagen für Kurzstrecken bis zu Langstrecken-Sattelzügen — jedes Fahrzeug wird GPS-überwacht, temperaturüberwacht und in Echtzeit routenoptimiert.",
    "port-to-port and door-to-door": "Von Hafen zu Hafen und von Tür zu Tür",
    "priority air cargo with same-day and next-flight-out options for time-critical shipments across our global airport network.": "Prioritätsluftfracht mit Optionen für die Lieferung am selben Tag und den nächsten Flug für zeitkritische Sendungen in unserem globalen Flughafen-Netzwerk.",
    "proof of delivery.": "Liefernachweis.",
    "quote request received": "Anfrage für Frachtangebot erhalten",
    "ready to move?": "Bereit zu bewegen?",
    "real-time performance metrics from our global operations center — updated every 60 seconds.": "Echtzeit-Kennzahlen aus unserer Leitstelle — alle sechzig Sekunden aktualisiert.",
    "real-time tracking per piece": "Echtzeitverfolgung, Stück für Stück",
    "request quote": "Angebot anfordern",
    "scheduled and on-demand": "Planmäßig oder auf Abruf",
    "tell us where you need to go — we'll build a tailored freight solution with competitive rates and a dedicated account manager.": "Sagen Sie uns, wohin es gehen soll — wir bauen eine maßgeschneiderte Transportlösung zu wettbewerbsfähigen Sätzen, mit festem Ansprechpartner.",
    "tell us where you need to go — we&apos;ll build a tailored freight solution with competitive rates and a dedicated account manager.": "Sagen Sie uns, wohin Sie gehen müssen — wir erstellen eine maßgeschneiderte Frachtlösung mit wettbewerbsfähigen Preisen und einem engagierten Kundenbetreuer.",
    "the tracking portal is genuinely better than anything we've used before. real-time gps plus predictive etas has transformed our planning.": "Das Tracking-Portal ist wirklich besser als alles, was wir zuvor verwendet haben. Echtzeit-GPS plus voraussichtliche Ankunftszeiten haben unsere Planung revolutioniert.",
    "time-guaranteed delivery with proof of delivery, signature capture, and white-glove handling for your most valuable shipments.": "Zeitgarantierte Lieferung mit Liefernachweis, Unterschriftenerfassung und Weißhandschuhbehandlung für Ihre wertvollsten Sendungen.",
    "trusted by supply chain leaders": "Vertraut von Führungskräften der Lieferkette",
    "we respond within 2 business hours. by submitting, you agree to our terms.": "Wir antworten binnen zwei Geschäftsstunden. Mit dem Absenden akzeptieren Sie unsere Bedingungen.",
    "we ship temperature-sensitive pharma across 18 countries. nexusfreight's cold-chain compliance has been flawless for 3 years running.": "Wir versenden temperaturempfindliche Pharmazeutika in 18 Länder. Die Einhaltung der Kühlkette von NexusFreight ist seit 3 Jahren fehlerfrei.",
    "weekly departures on all lanes": "Wöchentliche Abfahrten auf allen Strecken",
    "what we move": "Was wir bewegen",
    "without limits.": "Ohne Grenzen.",
    "your dedicated account manager will reach out within 2 business hours with a tailored freight proposal.": "Ihr engagierter Kundenbetreuer wird sich innerhalb von 2 Geschäftsstunden mit einem maßgeschneiderten Frachtvorschlag bei Ihnen melden.",
    "your name *": "Ihr Name *",
    "your shipment reaches our regional hub. automated sorting, route assignment, and consolidation with compatible loads.": "Ihre Sendung erreicht unser regionales Zentrum. Automatisierte Sortierung, Routenvergabe und Konsolidierung mit kompatiblen Lasten.",
  },
  pt: {
    "active parcels in our global network right now": "Encomendas em circulação na nossa rede neste momento",
    "client voices": "Vozes dos clientes",
    "delivery journey": "Jornada de entrega",
    "door-to-door in 24–72 hours": "De porta a porta em 24 a 72 horas",
    "end-to-end freight intelligence for modern supply chains. 43 countries, 6 continents, one platform.": "Inteligência de carga de ponta a ponta para cadeias de suprimento modernas. 43 países, 6 continentes, uma plataforma.",
    "every mode.": "Todos os modos.",
    "final-mile delivery with signature capture. real-time photo proof uploaded instantly to your tracking portal.": "Entrega da última milha com captura de assinatura. Prova fotográfica em tempo real carregada instantaneamente no seu portal de rastreamento.",
    "freight quote request": "Pedido de cotação de carga",
    "from pickup to": "Da recolha até",
    "ftl, ltl, and groupage": "Camião completo, carga parcial e grupagem",
    "full container load (fcl) and less-than-container load (lcl) solutions with carrier diversity across 200+ shipping lanes.": "Soluções de Carga de Contêiner Completo (FCL) e Carga Menor que o Contêiner (LCL) com diversidade de transportadoras em mais de 200 rotas de envio.",
    "full-truck loads, partial loads, and groupage across europe and beyond — with cross-border clearance in every corridor.": "Cargas completas de camião, cargas parciais e agrupamento em toda a Europa e além — com desalfandegamento transfronteiriço em cada corredor.",
    "in transit": "Em trânsito",
    "let&apos;s talk.": "Vamos conversar.",
    "long-haul transport via road, air, or sea. gps updates every 15 minutes. predictive eta re-calculated in real time.": "Transporte de longa distância por estrada, ar ou mar. Atualizações de GPS a cada 15 minutos. ETA preditiva recalculada em tempo real.",
    "multimodal freight solutions engineered for complex global supply chains — from single pallets to full charter aircraft loads.": "Soluções de carga multimodal projetadas para cadeias de suprimento globais complexas — desde paletes únicos até cargas completas de aeronaves fretadas.",
    "next-day and same-day options": "Opções de entrega no dia seguinte e no mesmo dia",
    "nexusfreight cut our cross-border transit times by 35%. the customs pre-clearance alone saves us two days on every eu shipment.": "A NexusFreight reduziu os nossos tempos de trânsito transfronteiriços em 35%. A pré-liberação aduaneira sozinha poupa-nos dois dias em cada envio para a UE.",
    "numbers that speak": "Números que falam",
    "on-time rate": "Taxa de pontualidade",
    "our brokers handle documentation at every border. pre-clearance reduces dwell time to under 4 hours on average.": "Os nossos corretores tratam da documentação em todas as fronteiras. A pré-liberação reduz o tempo de espera para menos de 4 horas, em média.",
    "our driver collects from your door or warehouse. parcel scanned, weighed, and entered into the system within 60 seconds.": "O nosso motorista recolhe à sua porta ou armazém. Pacote escaneado, pesado e inserido no sistema em 60 segundos.",
    "our fleet spans short-haul urban delivery vans to long-haul articulated trucks — every vehicle gps-tracked, temperature-monitored, and route-optimized in real time.": "A nossa frota abrange furgões de entrega urbanos de curta distância a camiões articulados de longa distância — cada veículo é rastreado por GPS, monitorizado em temperatura e otimizado em rota em tempo real.",
    "port-to-port and door-to-door": "De porto a porto e de porta a porta",
    "priority air cargo with same-day and next-flight-out options for time-critical shipments across our global airport network.": "Carga aérea prioritária com opções de entrega no mesmo dia e no próximo voo para envios críticos em tempo em nossa rede aeroportuária global.",
    "proof of delivery.": "comprovativo de entrega.",
    "quote request received": "Pedido de cotação recebido",
    "ready to move?": "Pronto para mover-se?",
    "real-time performance metrics from our global operations center — updated every 60 seconds.": "Indicadores em tempo real do nosso centro de operações — atualizados a cada sessenta segundos.",
    "real-time tracking per piece": "Seguimento em tempo real, volume a volume",
    "request quote": "Solicitar cotação",
    "scheduled and on-demand": "Programado ou a pedido",
    "tell us where you need to go — we'll build a tailored freight solution with competitive rates and a dedicated account manager.": "Diga-nos para onde é preciso ir — construímos uma solução de transporte à medida, a um preço competitivo e com um interlocutor dedicado.",
    "tell us where you need to go — we&apos;ll build a tailored freight solution with competitive rates and a dedicated account manager.": "Diga-nos para onde precisa de ir — construiremos uma solução de carga personalizada com tarifas competitivas e um gestor de conta dedicado.",
    "the tracking portal is genuinely better than anything we've used before. real-time gps plus predictive etas has transformed our planning.": "O portal de rastreamento é genuinamente melhor do que qualquer coisa que tenhamos usado antes. O GPS em tempo real mais os ETAs preditivos transformaram o nosso planeamento.",
    "time-guaranteed delivery with proof of delivery, signature capture, and white-glove handling for your most valuable shipments.": "Entrega garantida a tempo com comprovativo de entrega, captura de assinatura e manuseio de luva branca para os seus envios mais valiosos.",
    "trusted by supply chain leaders": "Confiável por líderes da cadeia de abastecimento",
    "we respond within 2 business hours. by submitting, you agree to our terms.": "Respondemos em duas horas úteis. Ao enviar, aceita as nossas condições.",
    "we ship temperature-sensitive pharma across 18 countries. nexusfreight's cold-chain compliance has been flawless for 3 years running.": "Enviamos produtos farmacêuticos sensíveis à temperatura para 18 países. A conformidade da cadeia de frio da NexusFreight tem sido impecável durante 3 anos.",
    "weekly departures on all lanes": "Partidas semanais em todas as rotas",
    "what we move": "O que transportamos",
    "without limits.": "Sem limites.",
    "your dedicated account manager will reach out within 2 business hours with a tailored freight proposal.": "O seu gestor de conta dedicado entrará em contacto dentro de 2 horas úteis com uma proposta de carga personalizada.",
    "your name *": "O seu nome *",
    "your shipment reaches our regional hub. automated sorting, route assignment, and consolidation with compatible loads.": "A sua remessa chega ao nosso centro regional. Classificação automatizada, atribuição de rotas e consolidação com cargas compatíveis.",
  },
};
