/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"in the silence of the room, the only story told is that of the season.\" ginza, tokyo.": "\"Dans le silence de la pièce, la seule histoire racontée est celle de la saison.\" Ginza, Tokyo.",
    "\"to find the soul of the fish, we must remove everything that is not the fish.\"": "\"Pour trouver l'âme du poisson, nous devons enlever tout ce qui n'est pas le poisson.\"",
    "&times;": "&times;",
    "an intimate 8-seat sanctuary dedicated to the seasonal purity of edomae-style sushi. leave the decision to the chef.": "Un sanctuaire intime de 8 places dédié à la pureté saisonnière du sushi de style Edomae. Laissez la décision au Chef.",
    "an introduction to the kuro kitchen. ideal for first visits.": "Une entrée en matière dans notre cuisine. Idéale pour une première visite.",
    "every element of the menu changes with the lunar calendar. what you taste tonight has never been served before, and will never be served again.": "Chaque élément de la carte change avec le calendrier lunaire. Ce que vous goûtez ce soir n'a jamais été servi, et ne le sera plus.",
    "in zero.": "Dans Zero.",
    "is flavor.": "EST LE GOÛT.",
    "kuro omakase follows the strict principle of ma (間) — the space between, the silence, the void that allows the flavor to truly exist.": "Kuro Omakase suit le principe strict de Ma (間) — l'espace entre, le silence, le vide qui permet à la saveur d'exister vraiment.",
    "new york": "NEW YORK",
    "request reservation": "Demander une réservation",
    "reservations are released on the first of every month for the following 30 days. we look forward to your visit.": "Les réservations ouvrent le premier de chaque mois, pour les trente jours suivants. Au plaisir de vous recevoir.",
    "reserve your": "Réservez votre",
    "secure a seat": "Réservez une place",
    "slow-steamed for 6 hours in sake and kelp dashi for optimal texture.": "Cuit six heures à la vapeur douce, dans un dashi de saké et d'algue, pour la texture juste.",
    "the artisan": "L'artisan",
    "the chef": "Le chef",
    "the origin": "L'origine",
    "the philosophy": "La philosophie",
    "the ritual": "Le rituel",
    "the sourcing": "L'approvisionnement",
    "triple-marbled belly cut, cured for 48 hours in house-made shoyu.": "Ventrèche trois fois persillée, marinée quarante-huit heures dans notre shoyu maison.",
    "trust the": "FAITES CONFIANCE AU",
    "witness the ritual": "Assister au rituel",
  },
  es: {
    "\"in the silence of the room, the only story told is that of the season.\" ginza, tokyo.": "\"En el silencio de la habitación, la única historia contada es la de la temporada.\" Ginza, Tokio.",
    "\"to find the soul of the fish, we must remove everything that is not the fish.\"": "\"Para encontrar el alma del pez, debemos quitar todo lo que no es el pez.\"",
    "&times;": "&times;",
    "an intimate 8-seat sanctuary dedicated to the seasonal purity of edomae-style sushi. leave the decision to the chef.": "Un santuario íntimo de 8 asientos dedicado a la pureza estacional del sushi al estilo Edomae. Deje la decisión al Chef.",
    "an introduction to the kuro kitchen. ideal for first visits.": "Una introducción a nuestra cocina. Ideal para una primera visita.",
    "every element of the menu changes with the lunar calendar. what you taste tonight has never been served before, and will never be served again.": "Cada elemento de la carta cambia con el calendario lunar. Lo que prueba esta noche nunca se ha servido, y no volverá a servirse.",
    "in zero.": "En Zero.",
    "is flavor.": "ES EL SABOR.",
    "kuro omakase follows the strict principle of ma (間) — the space between, the silence, the void that allows the flavor to truly exist.": "Kuro Omakase sigue el estricto principio de Ma (間) — el espacio entre, el silencio, el vacío que permite que el sabor exista realmente.",
    "new york": "NUEVA YORK",
    "request reservation": "Solicitar reserva",
    "reservations are released on the first of every month for the following 30 days. we look forward to your visit.": "Las reservas se abren el primero de cada mes, para los treinta días siguientes. Será un placer recibirle.",
    "reserve your": "Reserva tu",
    "secure a seat": "Asegura un asiento",
    "slow-steamed for 6 hours in sake and kelp dashi for optimal texture.": "Cocido seis horas al vapor suave, en un dashi de sake y alga, para la textura justa.",
    "the artisan": "El artesano",
    "the chef": "El chef",
    "the origin": "El origen",
    "the philosophy": "La filosofía",
    "the ritual": "El ritual",
    "the sourcing": "El aprovisionamiento",
    "triple-marbled belly cut, cured for 48 hours in house-made shoyu.": "Ventresca de triple veteado, marinada cuarenta y ocho horas en nuestro shoyu casero.",
    "trust the": "CONFÍE EN EL",
    "witness the ritual": "Asistir al ritual",
  },
  de: {
    "\"in the silence of the room, the only story told is that of the season.\" ginza, tokyo.": "\"Im Schweigen des Raumes ist die einzige erzählte Geschichte die der Saison.\" Ginza, Tokio.",
    "\"to find the soul of the fish, we must remove everything that is not the fish.\"": "\"Um die Seele des Fisches zu finden, müssen wir alles entfernen, was nicht der Fisch ist.\"",
    "&times;": "&times;",
    "an intimate 8-seat sanctuary dedicated to the seasonal purity of edomae-style sushi. leave the decision to the chef.": "Ein intimes 8-Sitz-Sanktuarium, das der saisonalen Reinheit des Edomae-Sushi gewidmet ist. Überlassen Sie die Entscheidung dem Chef.",
    "an introduction to the kuro kitchen. ideal for first visits.": "Ein Einstieg in unsere Küche. Ideal für den ersten Besuch.",
    "every element of the menu changes with the lunar calendar. what you taste tonight has never been served before, and will never be served again.": "Jedes Element der Karte wechselt mit dem Mondkalender. Was Sie heute Abend kosten, wurde nie zuvor serviert und wird es nie wieder.",
    "in zero.": "In Zero.",
    "is flavor.": "IST DER GESCHMACK.",
    "kuro omakase follows the strict principle of ma (間) — the space between, the silence, the void that allows the flavor to truly exist.": "Kuro Omakase folgt dem strengen Prinzip von Ma (間) — dem Raum dazwischen, der Stille, der Leere, die es dem Geschmack ermöglicht, wirklich zu existieren.",
    "new york": "NEW YORK",
    "request reservation": "Reservierung anfragen",
    "reservations are released on the first of every month for the following 30 days. we look forward to your visit.": "Reservierungen öffnen am Ersten jedes Monats für die folgenden dreißig Tage. Wir freuen uns auf Ihren Besuch.",
    "reserve your": "Reservieren Sie Ihr",
    "secure a seat": "Sichern Sie sich einen Platz",
    "slow-steamed for 6 hours in sake and kelp dashi for optimal texture.": "Sechs Stunden sanft gedämpft in einem Dashi aus Sake und Kombu, für die richtige Textur.",
    "the artisan": "Der Handwerker",
    "the chef": "Der Küchenchef",
    "the origin": "Der Ursprung",
    "the philosophy": "Die Philosophie",
    "the ritual": "Das Ritual",
    "the sourcing": "Die Beschaffung",
    "triple-marbled belly cut, cured for 48 hours in house-made shoyu.": "Dreifach marmorierter Bauchschnitt, achtundvierzig Stunden in hauseigenem Shoyu gereift.",
    "trust the": "VERTRAUEN SIE DEM",
    "witness the ritual": "Dem Ritual beiwohnen",
  },
  pt: {
    "\"in the silence of the room, the only story told is that of the season.\" ginza, tokyo.": "\"No silêncio da sala, a única história contada é a da estação.\" Ginza, Tóquio.",
    "\"to find the soul of the fish, we must remove everything that is not the fish.\"": "\"Para encontrar a alma do peixe, devemos remover tudo que não é o peixe.\"",
    "&times;": "&times;",
    "an intimate 8-seat sanctuary dedicated to the seasonal purity of edomae-style sushi. leave the decision to the chef.": "Um santuário íntimo de 8 lugares dedicado à pureza sazonal do sushi ao estilo Edomae. Deixe a decisão para o Chef.",
    "an introduction to the kuro kitchen. ideal for first visits.": "Uma introdução à nossa cozinha. Ideal para uma primeira visita.",
    "every element of the menu changes with the lunar calendar. what you taste tonight has never been served before, and will never be served again.": "Cada elemento da carta muda com o calendário lunar. O que prova esta noite nunca foi servido, e nunca mais o será.",
    "in zero.": "Em Zero.",
    "is flavor.": "É O SABOR.",
    "kuro omakase follows the strict principle of ma (間) — the space between, the silence, the void that allows the flavor to truly exist.": "Kuro Omakase segue o princípio estrito de Ma (間) — o espaço entre, o silêncio, o vazio que permite que o sabor realmente exista.",
    "new york": "NOVA IORQUE",
    "request reservation": "Pedir reserva",
    "reservations are released on the first of every month for the following 30 days. we look forward to your visit.": "As reservas abrem no primeiro dia de cada mês, para os trinta dias seguintes. Será um prazer recebê-lo.",
    "reserve your": "Reserve o seu",
    "secure a seat": "Garanta um lugar",
    "slow-steamed for 6 hours in sake and kelp dashi for optimal texture.": "Cozido seis horas a vapor suave, num dashi de saqué e alga, para a textura certa.",
    "the artisan": "O artesão",
    "the chef": "O chefe",
    "the origin": "A origem",
    "the philosophy": "A filosofia",
    "the ritual": "O ritual",
    "the sourcing": "O aprovisionamento",
    "triple-marbled belly cut, cured for 48 hours in house-made shoyu.": "Ventresca de triplo marmoreado, marinada quarenta e oito horas no nosso shoyu caseiro.",
    "trust the": "CONFIE NO",
    "witness the ritual": "Assistir ao ritual",
  },
};
