/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "equipment": "Équipement",
    "enquiry": "Nous écrire",
    "highest": "Les plus hauts",
    "summits": "sommets",
    "elite art conservation & private registry": "Conservation d'œuvres et registre privé",
    "collector vault": "Coffre du collectionneur",
    "materials": "Matériaux",
    "specs": "Caractéristiques",
    "applications": "Applications",
    "research": "Recherche",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Soie au graphène. Maille bioluminescente CRISPR. Laine à mémoire de forme en nitinol. Nous concevons des textiles au croisement de la science des matériaux, de la biotechnologie et de la haute couture.",
    "core directive": "Directive fondamentale",
    "uptime protocol": "Protocole de disponibilité",
    "expandable storage": "Stockage extensible",
    "provision node": "Provisionner un nœud",
    "product": "Produit",
    "marketing": "Marketing",
    "properties": "Nos biens",
    "market": "Le marché",
    "neighborhoods": "Les quartiers",
    "establishment": "Fondation",
    "gold": "Or",
    "time": "Le temps",
    "newsletter": "Lettre d'information",
    "planning": "Le planning",
    "heritage": "Héritage",
    "clients": "clients",
    "note clients": "Note des clients",
    "prix de design": "Prix de design",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "equipment": "Equipamiento",
    "enquiry": "Escríbanos",
    "highest": "Las más altas",
    "summits": "cumbres",
    "elite art conservation & private registry": "Conservación de obras y registro privado",
    "collector vault": "Cámara del coleccionista",
    "materials": "Materiales",
    "specs": "Características",
    "applications": "Aplicaciones",
    "research": "Investigación",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda con grafeno. Malla bioluminiscente CRISPR. Lana con memoria de forma de nitinol. Diseñamos textiles en el cruce de la ciencia de materiales, la biotecnología y la alta costura.",
    "core directive": "Directiva fundamental",
    "uptime protocol": "Protocolo de disponibilidad",
    "expandable storage": "Almacenamiento ampliable",
    "provision node": "Aprovisionar un nodo",
    "product": "Producto",
    "marketing": "Marketing",
    "properties": "Nuestros inmuebles",
    "market": "El mercado",
    "neighborhoods": "Los barrios",
    "establishment": "Fundación",
    "gold": "Oro",
    "time": "El tiempo",
    "newsletter": "Boletín",
    "planning": "El horario",
    "heritage": "Herencia",
    "clients": "clientes",
    "note clients": "Nota de clientes",
    "prix de design": "Precio de diseño",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "equipment": "Ausrüstung",
    "enquiry": "Anfrage",
    "highest": "Die höchsten",
    "summits": "Gipfel",
    "elite art conservation & private registry": "Kunstkonservierung und privates Register",
    "collector vault": "Sammlertresor",
    "materials": "Werkstoffe",
    "specs": "Kenndaten",
    "applications": "Anwendungen",
    "research": "Forschung",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seide mit Graphen. Biolumineszentes CRISPR-Gewebe. Formgedächtniswolle aus Nitinol. Wir entwickeln Textilien an der Schnittstelle von Materialwissenschaft, Biotechnologie und Haute Couture.",
    "core directive": "Grundsatzdirektive",
    "uptime protocol": "Verfügbarkeitsprotokoll",
    "expandable storage": "Erweiterbarer Speicher",
    "provision node": "Knoten bereitstellen",
    "product": "Produkt",
    "marketing": "Marketing",
    "properties": "Unsere Objekte",
    "market": "Der Markt",
    "neighborhoods": "Die Viertel",
    "establishment": "Gründung",
    "gold": "Gold",
    "time": "Die Zeit",
    "newsletter": "Newsletter",
    "planning": "Der Stundenplan",
    "heritage": "Erbe",
    "clients": "Kunden",
    "note clients": "Kundenbewertung",
    "prix de design": "Designpreis",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "equipment": "Equipamento",
    "enquiry": "Escreva-nos",
    "highest": "Os mais altos",
    "summits": "cumes",
    "elite art conservation & private registry": "Conservação de obras e registo privado",
    "collector vault": "Cofre do colecionador",
    "materials": "Materiais",
    "specs": "Características",
    "applications": "Aplicações",
    "research": "Investigação",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda com grafeno. Malha bioluminescente CRISPR. Lã com memória de forma em nitinol. Concebemos têxteis no cruzamento da ciência dos materiais, da biotecnologia e da alta-costura.",
    "core directive": "Diretiva fundamental",
    "uptime protocol": "Protocolo de disponibilidade",
    "expandable storage": "Armazenamento expansível",
    "provision node": "Aprovisionar um nó",
    "product": "Produto",
    "marketing": "Marketing",
    "properties": "Os nossos imóveis",
    "market": "O mercado",
    "neighborhoods": "Os bairros",
    "establishment": "Fundação",
    "gold": "Ouro",
    "time": "O tempo",
    "newsletter": "Boletim",
    "planning": "O horário",
    "heritage": "Herança",
    "clients": "clientes",
    "note clients": "Nota de clientes",
    "prix de design": "Preço de design",
  },
};
