/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "our lineages": "Nos lignées",
    "explore our signature lineages. from rigorous ashtanga to restorative yin.": "Explorez nos lignées signature, de l'ashtanga rigoureux au yin réparateur.",
    "beginner": "Débutant",
    "advanced": "Avancé",
    "lineage keepers": "Gardiens de la lignée",
    "your": "Vos",
    "guides.": "guides.",
    "meet the experienced practitioners guiding your evolution.": "Rencontrez les praticiens expérimentés qui guident votre évolution.",
    "vinyasa & meditation": "Vinyasa et méditation",
    "ashtanga & pranayama": "Ashtanga et pranayama",
    "yin & sound healing": "Yin et soin par le son",
    "yin & sound bath": "Yin et bain sonore",
    "dedicated to sharing traditional, breath-centered yoga with anatomical safety. over 1 000 hours of training in mysore and rishikesh.": "Vouée à transmettre un yoga traditionnel centré sur le souffle, dans le respect de l'anatomie. Plus de 1 000 heures de formation à Mysore et Rishikesh.",
    "extraction physics": "Physique de l'extraction",
    "brew": "Logique",
    "logic.": "d'extraction.",
    "maximize the genetic potential of your beans. our laboratory-tested protocols ensure peak extraction efficiency.": "Tirez le meilleur du potentiel de vos grains : nos protocoles éprouvés en laboratoire garantissent une extraction optimale.",
    "extraction yield": "Rendement d'extraction",
    "the sweet spot of soluble solids. balancing acidity and body.": "Le point d'équilibre des solides solubles, entre acidité et corps.",
    "water purity": "Pureté de l'eau",
    "how do you integrate generative ai in your process?": "Comment intégrez-vous l'IA générative dans votre méthode ?",
    "what is your approach to sustainable materials?": "Quelle est votre approche des matériaux durables ?",
    "can you handle international project management?": "Assurez-vous la conduite de projets à l'international ?",
    "what are your standard consultation fees?": "Quels sont vos honoraires de consultation ?",
    "request": "Demander une",
    "invitation.": "invitation.",
    "membership is strictly regulated to preserve the atmosphere. provide your credentials below.": "L'adhésion est strictement encadrée pour préserver l'atmosphère. Présentez-vous ci-dessous.",
    "✓ access to private rooms across berlin, ibiza, tokyo, and miami.": "✓ Accès aux salons privés de Berlin, Ibiza, Tokyo et Miami.",
    "✓ custom sensory key card with encrypted nfc security.": "✓ Carte d'accès sensorielle personnalisée, sécurisée par NFC chiffré.",
    "✓ private invitations to pop-up secret architectural stages.": "✓ Invitations privées aux scènes éphémères secrètes.",
    "contact email": "Adresse e-mail",
    "primary node": "Ville principale",
    "berlin hub": "Berlin",
    "ibiza retreat": "Ibiza",
    "tokyo underground": "Tokyo",
    "curated fleet": "Flotte choisie",
    "pratiques.": "pratiques.",
    "archive": "Archives",
    "full archive": "Toutes les archives",
    "global operations": "Nos implantations",
    "global inventory": "Stock mondial",
    "global sourcing": "Approvisionnement mondial",
    "residential": "Résidentiel",
    "commercial": "Tertiaire",
    "cultural": "Culturel",
    "countries": "Pays",
    "completed projects": "Projets livrés",
    "publications": "Publications",
    "location:": "Lieu :",
    "materials": "Matériaux",
    "philosophy": "Philosophie",
    "anatomy": "Anatomie",
    "heritage": "Héritage",
    "brewing": "L'extraction",
    "origins": "Origines",
    "ovens": "Nos fours",
    "subscription": "Abonnement",
    "fresh batch": "Fournée du jour",
    "modern.": "Moderne.",
    "artisanal.": "Artisanal.",
    "celestial.": "Céleste.",
    "void &": "Le vide",
    "volume.": "et le volume.",
    "pure": "Volume",
    "mastery of": "La maîtrise",
    "duration.": "de la durée.",
    "examine portals": "Voir les projets",
    "structure / light / materiality / void": "STRUCTURE / LUMIÈRE / MATIÈRE / VIDE",
    "riba awards": "Prix RIBA",
    "established 1924 // geneva, ch": "Fondée en 1924 // Genève, Suisse",
    "swiss alps, ch": "Alpes suisses, Suisse",
    "dubai, uae": "Dubaï, Émirats arabes unis",
    "tokyo, jp": "Tokyo, Japon",
    "oslo, no": "Oslo, Norvège",
    "seoul, kr": "Séoul, Corée du Sud",
    "berlin, de": "Berlin, Allemagne",
    "kyoto, jp": "Kyoto, Japon",
    "malibu, ca": "Malibu, Californie",
    "projects.": "Réalisations.",
    "art direction": "Direction artistique",
    "retail": "Point de vente",
    "sourdough": "Pain au levain",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentation de 48 heures. Croûte au charbon végétal. Assemblage de blés anciens.",
    "aop butter. 256 layers. golden honeycomb structure.": "Beurre AOP. 256 couches. Alvéolage doré.",
    "high hydration. stone-baked. intense caramelization.": "Forte hydratation. Cuisson sur pierre. Caramélisation intense.",
    "add_to_bag": "Ajouter_au_panier",
    "baking": "Protocole",
    "protocol.": "de cuisson.",
    "hydration ratio": "Taux d'hydratation",
    "maximizing crumb elasticity through high-hydration dough processing.": "Une mie plus élastique, obtenue par un pétrissage à forte hydratation.",
    "cold fermentation": "Fermentation à froid",
    "the": "La",
    "daily batch.": "fournée du jour.",
    "a rare studio that treats every project like it is their own brand — obsessive, principled, and relentlessly precise.": "Un studio rare qui traite chaque projet comme s'il s'agissait de sa propre marque — obsessionnel, principiel et d'une précision implacable.",
    "aether studio and the precision of creative systems": "L'atelier et la précision des systèmes créatifs",
    "aether transformed our visual identity into something we are genuinely proud to put in front of the world. the attention to craft is unreal.": "Aether a transformé notre identité visuelle en quelque chose dont nous sommes vraiment fiers de présenter au monde. L'attention portée à l'artisanat est irréelle.",
    "brand audit, logo redesign, and core identity system. for startups and early-stage brands.": "Audit de marque, refonte du logo et système d'identité. Pour les jeunes pousses et les marques naissantes.",
    "brand new": "Identité neuve",
    "clients actifs": "Clients actifs",
    "complete brand system with motion identity, digital templates, and campaign direction.": "Système de marque complet avec identité en mouvement, modèles numériques et direction de campagne.",
    "conceptual development under pressure. we synthesize findings into a series of bold creative directions.": "Développement conceptuel sous pression. Nous synthétisons les résultats en une série de directions créatives audacieuses.",
    "dedicated creative team": "Équipe créative dédiée",
    "deep-dive research into your brand dna, competitors, and target signal. we map the chemical composition of the problem.": "Recherche approfondie sur l'ADN de votre marque, les concurrents et le signal cible. Nous cartographions la composition chimique du problème.",
    "design systems": "Systèmes de design",
    "end-to-end brand architecture: identity, tone of voice, touchpoint design, and living system documentation.": "Architecture de marque de bout en bout : identité, ton de voix, design des points de contact et documentation des systèmes vivants.",
    "everything in espresso": "Tout en Espresso",
    "everything in full extraction": "Tout en extraction complète",
    "explore roast spectrum": "Explorer le Spectre de Torréfaction",
    "flawless delivery across all touchpoints. post-launch analysis and system documentation included.": "Livraison impeccable sur tous les points de contact. Analyse post-lancement et documentation du système incluses.",
    "fluid motion design and three-dimensional worldbuilding for film titles, product reveals, and brand campaigns.": "Design de mouvement fluide et création de mondes en trois dimensions pour les titres de films, les révélations de produits et les campagnes de marque.",
    "from €12,000": "À partir de 12 000 €",
    "from €28,000": "À partir de 28 000 €",
    "from €6,500/mo": "À partir de 6 500 €/mois",
    "generative visuals, custom tooling, and interactive installations at the intersection of code and sensory experience.": "Visuels génératifs, outils personnalisés et installations interactives à l'intersection du code et de l'expérience sensorielle.",
    "identity design": "Conception d'identité",
    "in caffeine we trust": "Nous croyons à la caféine",
    "it's annecy that": "C'est Annecy qui",
    "iterative production with precision control. every element calibrated against your brand temperature.": "Production itérative avec contrôle de précision. Chaque élément est calibré en fonction de la température de votre marque.",
    "motion, matter, and the molecular brand": "Le mouvement, la matière et la marque moléculaire",
    "precision-roasted molecular coffee. sourced at origin. analyzed in lab. delivered in spectrum.": "Café moléculaire rôti avec précision. Sourcé à l'origine. Analysé en laboratoire. Livré en spectre.",
    "quarterly brand review": "Revue de marque trimestrielle",
    "red dot best of best": "Red Dot Meilleur des Meilleurs",
    "shop beans": "ACHETER DES HARICOTS",
    "start a": "Commencer un",
    "submit brief": "Soumettre le Brief",
    "the infrastructure for the next generation of specialty coffee. est. 2026. precision roasted. globally sourced.": "L'infrastructure pour la prochaine génération de café de spécialité. Est. 2026. Rôti avec précision. Sourced mondialement.",
    "they said.": "Ils ont dit.",
    "they think at a frequency we had never encountered before. the final campaign exceeded every brief metric we set.": "Ils pensent à une fréquence que nous n'avions jamais rencontrée auparavant. La campagne finale a dépassé tous les critères que nous avions fixés.",
    "we take on a limited number of new clients each quarter. submit your brief and we will respond within 48 hours.": "Nous acceptons un nombre limité de nouveaux clients chaque trimestre. Soumettez votre brief et nous répondrons dans les 48 heures.",
    "what we do.": "Ce que nous faisons.",
    "when coffee meets computation": "Quand le café rencontre l'informatique",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "our lineages": "Nuestros linajes",
    "explore our signature lineages. from rigorous ashtanga to restorative yin.": "Explore nuestros linajes, del ashtanga riguroso al yin reparador.",
    "beginner": "Principiante",
    "advanced": "Avanzado",
    "lineage keepers": "Guardianes del linaje",
    "your": "Sus",
    "guides.": "guías.",
    "meet the experienced practitioners guiding your evolution.": "Conozca a los practicantes experimentados que guían su evolución.",
    "vinyasa & meditation": "Vinyasa y meditación",
    "ashtanga & pranayama": "Ashtanga y pranayama",
    "yin & sound healing": "Yin y sonoterapia",
    "yin & sound bath": "Yin y baño sonoro",
    "dedicated to sharing traditional, breath-centered yoga with anatomical safety. over 1 000 hours of training in mysore and rishikesh.": "Dedicada a transmitir un yoga tradicional centrado en la respiración, con seguridad anatómica. Más de 1 000 horas de formación en Mysore y Rishikesh.",
    "extraction physics": "Física de la extracción",
    "brew": "Lógica",
    "logic.": "de extracción.",
    "maximize the genetic potential of your beans. our laboratory-tested protocols ensure peak extraction efficiency.": "Aproveche todo el potencial de sus granos: nuestros protocolos probados en laboratorio garantizan una extracción óptima.",
    "extraction yield": "Rendimiento de extracción",
    "the sweet spot of soluble solids. balancing acidity and body.": "El punto de equilibrio de los sólidos solubles, entre acidez y cuerpo.",
    "water purity": "Pureza del agua",
    "how do you integrate generative ai in your process?": "¿Cómo integran la IA generativa en su método?",
    "what is your approach to sustainable materials?": "¿Cuál es su enfoque de los materiales sostenibles?",
    "can you handle international project management?": "¿Gestionan proyectos internacionales?",
    "what are your standard consultation fees?": "¿Cuáles son sus honorarios de consulta?",
    "request": "Solicitar una",
    "invitation.": "invitación.",
    "membership is strictly regulated to preserve the atmosphere. provide your credentials below.": "La adhesión está estrictamente regulada para preservar la atmósfera. Preséntese a continuación.",
    "✓ access to private rooms across berlin, ibiza, tokyo, and miami.": "✓ Acceso a los salones privados de Berlín, Ibiza, Tokio y Miami.",
    "✓ custom sensory key card with encrypted nfc security.": "✓ Tarjeta de acceso sensorial personalizada, con seguridad NFC cifrada.",
    "✓ private invitations to pop-up secret architectural stages.": "✓ Invitaciones privadas a los escenarios efímeros secretos.",
    "contact email": "Correo electrónico",
    "primary node": "Ciudad principal",
    "berlin hub": "Berlín",
    "ibiza retreat": "Ibiza",
    "tokyo underground": "Tokio",
    "curated fleet": "Flota seleccionada",
    "pratiques.": "prácticas.",
    "archive": "Archivo",
    "full archive": "Todo el archivo",
    "global operations": "Nuestras sedes",
    "global inventory": "Inventario mundial",
    "global sourcing": "Abastecimiento mundial",
    "residential": "Residencial",
    "commercial": "Terciario",
    "cultural": "Cultural",
    "countries": "Países",
    "completed projects": "Proyectos entregados",
    "publications": "Publicaciones",
    "location:": "Lugar:",
    "materials": "Materiales",
    "philosophy": "Filosofía",
    "anatomy": "Anatomía",
    "heritage": "Herencia",
    "brewing": "La extracción",
    "origins": "Orígenes",
    "ovens": "Nuestros hornos",
    "subscription": "Suscripción",
    "fresh batch": "Hornada del día",
    "modern.": "Moderno.",
    "artisanal.": "Artesanal.",
    "celestial.": "Celeste.",
    "void &": "El vacío",
    "volume.": "y el volumen.",
    "pure": "Volumen",
    "mastery of": "El dominio",
    "duration.": "de la duración.",
    "examine portals": "Ver los proyectos",
    "structure / light / materiality / void": "ESTRUCTURA / LUZ / MATERIA / VACÍO",
    "riba awards": "Premios RIBA",
    "established 1924 // geneva, ch": "Fundada en 1924 // Ginebra, Suiza",
    "swiss alps, ch": "Alpes suizos, Suiza",
    "dubai, uae": "Dubái, Emiratos Árabes Unidos",
    "tokyo, jp": "Tokio, Japón",
    "oslo, no": "Oslo, Noruega",
    "seoul, kr": "Seúl, Corea del Sur",
    "berlin, de": "Berlín, Alemania",
    "kyoto, jp": "Kioto, Japón",
    "malibu, ca": "Malibú, California",
    "projects.": "Trabajos.",
    "art direction": "Dirección de arte",
    "retail": "Punto de venta",
    "sourdough": "Pan de masa madre",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentación de 48 horas. Corteza al carbón vegetal. Mezcla de granos antiguos.",
    "aop butter. 256 layers. golden honeycomb structure.": "Mantequilla DOP. 256 capas. Alveolado dorado.",
    "high hydration. stone-baked. intense caramelization.": "Alta hidratación. Cocción en piedra. Caramelización intensa.",
    "add_to_bag": "Añadir_a_la_cesta",
    "baking": "Protocolo",
    "protocol.": "de cocción.",
    "hydration ratio": "Tasa de hidratación",
    "maximizing crumb elasticity through high-hydration dough processing.": "Una miga más elástica, obtenida mediante un amasado de alta hidratación.",
    "cold fermentation": "Fermentación en frío",
    "the": "La",
    "daily batch.": "hornada del día.",
    "a rare studio that treats every project like it is their own brand — obsessive, principled, and relentlessly precise.": "Un estudio raro que trata cada proyecto como si fuera su propia marca — obsesivo, principiado y rigurosamente preciso.",
    "aether studio and the precision of creative systems": "El estudio y la precisión de los sistemas creativos",
    "aether transformed our visual identity into something we are genuinely proud to put in front of the world. the attention to craft is unreal.": "Aether transformó nuestra identidad visual en algo de lo que realmente estamos orgullosos de presentar al mundo. La atención al detalle es irreal.",
    "brand audit, logo redesign, and core identity system. for startups and early-stage brands.": "Auditoría de marca, rediseño del logotipo y sistema de identidad. Para startups y marcas nacientes.",
    "brand new": "Identidad nueva",
    "clients actifs": "Clientes activos",
    "complete brand system with motion identity, digital templates, and campaign direction.": "Sistema de marca completo con identidad en movimiento, plantillas digitales y dirección de campaña.",
    "conceptual development under pressure. we synthesize findings into a series of bold creative directions.": "Desarrollo conceptual bajo presión. Sintetizamos los hallazgos en una serie de audaces direcciones creativas.",
    "dedicated creative team": "Equipo creativo dedicado",
    "deep-dive research into your brand dna, competitors, and target signal. we map the chemical composition of the problem.": "Investigación profunda sobre el ADN de su marca, competidores y señal objetivo. Mapeamos la composición química del problema.",
    "design systems": "Sistemas de diseño",
    "end-to-end brand architecture: identity, tone of voice, touchpoint design, and living system documentation.": "Arquitectura de marca de principio a fin: identidad, tono de voz, diseño de puntos de contacto y documentación de sistemas vivos.",
    "everything in espresso": "Todo en Espresso",
    "everything in full extraction": "Todo en extracción completa",
    "explore roast spectrum": "Explorar el Espectro de Tostado",
    "flawless delivery across all touchpoints. post-launch analysis and system documentation included.": "Entrega impecable en todos los puntos de contacto. Análisis posterior al lanzamiento y documentación del sistema incluidos.",
    "fluid motion design and three-dimensional worldbuilding for film titles, product reveals, and brand campaigns.": "Diseño de movimiento fluido y construcción de mundos tridimensionales para títulos de películas, revelaciones de productos y campañas de marca.",
    "from €12,000": "Desde 12 000 €",
    "from €28,000": "Desde 28 000 €",
    "from €6,500/mo": "Desde 6 500 €/mes",
    "generative visuals, custom tooling, and interactive installations at the intersection of code and sensory experience.": "Visuales generativos, herramientas personalizadas e instalaciones interactivas en la intersección del código y la experiencia sensorial.",
    "identity design": "Diseño de identidad",
    "in caffeine we trust": "Creemos en la cafeína",
    "it's annecy that": "Es Annecy quien",
    "iterative production with precision control. every element calibrated against your brand temperature.": "Producción iterativa con control de precisión. Cada elemento calibrado según la temperatura de su marca.",
    "motion, matter, and the molecular brand": "El movimiento, la materia y la marca molecular",
    "precision-roasted molecular coffee. sourced at origin. analyzed in lab. delivered in spectrum.": "Café molecular tostado con precisión. Con origen trazado. Analizado en laboratorio. Entregado en espectro.",
    "quarterly brand review": "Revisión de marca trimestral",
    "red dot best of best": "Red Dot Mejor de los Mejores",
    "shop beans": "COMPRAR GRANOS",
    "start a": "Iniciar un",
    "submit brief": "Enviar Resumen",
    "the infrastructure for the next generation of specialty coffee. est. 2026. precision roasted. globally sourced.": "La infraestructura para la próxima generación de café de especialidad. Est. 2026. Tostado con precisión. Sourced globalmente.",
    "they said.": "Dijeron.",
    "they think at a frequency we had never encountered before. the final campaign exceeded every brief metric we set.": "Piensan a una frecuencia que nunca habíamos encontrado antes. La campaña final superó cada métrica del brief que establecimos.",
    "we take on a limited number of new clients each quarter. submit your brief and we will respond within 48 hours.": "Aceptamos un número limitado de nuevos clientes cada trimestre. Envíe su resumen y responderemos en 48 horas.",
    "what we do.": "Lo que hacemos.",
    "when coffee meets computation": "Cuando el café se encuentra con la computación",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "our lineages": "Unsere Linien",
    "explore our signature lineages. from rigorous ashtanga to restorative yin.": "Entdecken Sie unsere Linien, vom strengen Ashtanga zum regenerierenden Yin.",
    "beginner": "Anfänger",
    "advanced": "Fortgeschritten",
    "lineage keepers": "Hüter der Linie",
    "your": "Ihre",
    "guides.": "Guides.",
    "meet the experienced practitioners guiding your evolution.": "Lernen Sie die erfahrenen Lehrenden kennen, die Ihre Entwicklung begleiten.",
    "vinyasa & meditation": "Vinyasa und Meditation",
    "ashtanga & pranayama": "Ashtanga und Pranayama",
    "yin & sound healing": "Yin und Klangheilung",
    "yin & sound bath": "Yin und Klangbad",
    "dedicated to sharing traditional, breath-centered yoga with anatomical safety. over 1 000 hours of training in mysore and rishikesh.": "Der Weitergabe eines traditionellen, atemzentrierten Yoga mit anatomischer Sicherheit verschrieben. Über 1 000 Stunden Ausbildung in Mysore und Rishikesh.",
    "extraction physics": "Physik der Extraktion",
    "brew": "Brüh-",
    "logic.": "logik.",
    "maximize the genetic potential of your beans. our laboratory-tested protocols ensure peak extraction efficiency.": "Holen Sie das Beste aus Ihren Bohnen heraus: unsere laborgeprüften Protokolle garantieren optimale Extraktion.",
    "extraction yield": "Extraktionsausbeute",
    "the sweet spot of soluble solids. balancing acidity and body.": "Der Idealwert gelöster Feststoffe, zwischen Säure und Körper.",
    "water purity": "Wasserreinheit",
    "how do you integrate generative ai in your process?": "Wie integrieren Sie generative KI in Ihre Methode?",
    "what is your approach to sustainable materials?": "Wie gehen Sie mit nachhaltigen Materialien um?",
    "can you handle international project management?": "Übernehmen Sie internationales Projektmanagement?",
    "what are your standard consultation fees?": "Wie hoch sind Ihre Beratungshonorare?",
    "request": "Einladung",
    "invitation.": "anfragen.",
    "membership is strictly regulated to preserve the atmosphere. provide your credentials below.": "Die Mitgliedschaft ist streng geregelt, um die Atmosphäre zu wahren. Stellen Sie sich unten vor.",
    "✓ access to private rooms across berlin, ibiza, tokyo, and miami.": "✓ Zugang zu den privaten Räumen in Berlin, Ibiza, Tokio und Miami.",
    "✓ custom sensory key card with encrypted nfc security.": "✓ Personalisierte sensorische Schlüsselkarte mit verschlüsselter NFC-Sicherheit.",
    "✓ private invitations to pop-up secret architectural stages.": "✓ Private Einladungen zu geheimen Pop-up-Bühnen.",
    "contact email": "E-Mail-Adresse",
    "primary node": "Hauptstadtpunkt",
    "berlin hub": "Berlin",
    "ibiza retreat": "Ibiza",
    "tokyo underground": "Tokio",
    "curated fleet": "Ausgewählte Flotte",
    "pratiques.": "Praktiken.",
    "archive": "Archiv",
    "full archive": "Gesamtes Archiv",
    "global operations": "Unsere Standorte",
    "global inventory": "Weltweiter Bestand",
    "global sourcing": "Weltweite Beschaffung",
    "residential": "Wohnbau",
    "commercial": "Gewerbe",
    "cultural": "Kultur",
    "countries": "Länder",
    "completed projects": "Fertiggestellte Projekte",
    "publications": "Publikationen",
    "location:": "Ort:",
    "materials": "Werkstoffe",
    "philosophy": "Philosophie",
    "anatomy": "Anatomie",
    "heritage": "Erbe",
    "brewing": "Die Zubereitung",
    "origins": "Herkünfte",
    "ovens": "Unsere Öfen",
    "subscription": "Abonnement",
    "fresh batch": "Frische Charge",
    "modern.": "Modern.",
    "artisanal.": "Handwerklich.",
    "celestial.": "Himmlisch.",
    "void &": "Leere und",
    "volume.": "Volumen.",
    "pure": "Reines",
    "mastery of": "Die Beherrschung",
    "duration.": "der Dauer.",
    "examine portals": "Projekte ansehen",
    "structure / light / materiality / void": "STRUKTUR / LICHT / MATERIAL / LEERE",
    "riba awards": "RIBA-Preise",
    "established 1924 // geneva, ch": "Gegründet 1924 // Genf, Schweiz",
    "swiss alps, ch": "Schweizer Alpen, CH",
    "dubai, uae": "Dubai, VAE",
    "tokyo, jp": "Tokio, Japan",
    "oslo, no": "Oslo, Norwegen",
    "seoul, kr": "Seoul, Südkorea",
    "berlin, de": "Berlin, Deutschland",
    "kyoto, jp": "Kyoto, Japan",
    "malibu, ca": "Malibu, Kalifornien",
    "projects.": "Arbeiten.",
    "art direction": "Art Direction",
    "retail": "Einzelhandel",
    "sourdough": "Sauerteigbrot",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "48 Stunden Fermentation. Kruste mit Aktivkohle. Mischung alter Getreidesorten.",
    "aop butter. 256 layers. golden honeycomb structure.": "AOP-Butter. 256 Schichten. Goldene Wabenstruktur.",
    "high hydration. stone-baked. intense caramelization.": "Hohe Hydratation. Steinofengebacken. Intensive Karamellisierung.",
    "add_to_bag": "In_den_Korb",
    "baking": "Back-",
    "protocol.": "protokoll.",
    "hydration ratio": "Hydratationsgrad",
    "maximizing crumb elasticity through high-hydration dough processing.": "Elastischere Krume durch Teigführung mit hoher Hydratation.",
    "cold fermentation": "Kalte Führung",
    "the": "Die",
    "daily batch.": "Tagescharge.",
    "a rare studio that treats every project like it is their own brand — obsessive, principled, and relentlessly precise.": "Ein seltenes Studio, das jedes Projekt behandelt, als wäre es die eigene Marke — obsessiv, prinzipientreu und unermüdlich präzise.",
    "aether studio and the precision of creative systems": "Das Atelier und die Präzision kreativer Systeme",
    "aether transformed our visual identity into something we are genuinely proud to put in front of the world. the attention to craft is unreal.": "Aether hat unsere visuelle Identität in etwas verwandelt, auf das wir wirklich stolz sind, es der Welt zu präsentieren. Die Liebe zum Handwerk ist unrealistisch.",
    "brand audit, logo redesign, and core identity system. for startups and early-stage brands.": "Markenaudit, Logo-Neugestaltung und Identitätssystem. Für Start-ups und junge Marken.",
    "brand new": "Neue Marke",
    "clients actifs": "Aktive Kunden",
    "complete brand system with motion identity, digital templates, and campaign direction.": "Vollständiges Markensystem mit Bewegungsidentität, digitalen Vorlagen und Kampagnenleitung.",
    "conceptual development under pressure. we synthesize findings into a series of bold creative directions.": "Konzeptionelle Entwicklung unter Druck. Wir synthetisieren die Ergebnisse in eine Reihe von mutigen kreativen Richtungen.",
    "dedicated creative team": "Engagiertes Kreativteam",
    "deep-dive research into your brand dna, competitors, and target signal. we map the chemical composition of the problem.": "Tiefenforschung in Ihre Marken-DNA, Wettbewerber und Zielsignal. Wir kartieren die chemische Zusammensetzung des Problems.",
    "design systems": "Designsysteme",
    "end-to-end brand architecture: identity, tone of voice, touchpoint design, and living system documentation.": "End-to-End-Markenarchitektur: Identität, Tonalität, Touchpoint-Design und Dokumentation lebendiger Systeme.",
    "everything in espresso": "Alles in Espresso",
    "everything in full extraction": "Alles in voller Extraktion",
    "explore roast spectrum": "Röstspektrum erkunden",
    "flawless delivery across all touchpoints. post-launch analysis and system documentation included.": "Makellose Lieferung über alle Touchpoints. Analyse nach dem Start und Systemdokumentation inklusive.",
    "fluid motion design and three-dimensional worldbuilding for film titles, product reveals, and brand campaigns.": "Flüssiges Motion Design und dreidimensionales Weltenbauen für Filmtitel, Produktenthüllungen und Marken-Kampagnen.",
    "from €12,000": "Ab 12 000 €",
    "from €28,000": "Ab 28 000 €",
    "from €6,500/mo": "Ab 6 500 €/Monat",
    "generative visuals, custom tooling, and interactive installations at the intersection of code and sensory experience.": "Generative Visuals, maßgeschneiderte Werkzeuge und interaktive Installationen an der Schnittstelle von Code und sensorischer Erfahrung.",
    "identity design": "Identitätsdesign",
    "in caffeine we trust": "Wir vertrauen dem Koffein",
    "it's annecy that": "Es ist Annecy, das",
    "iterative production with precision control. every element calibrated against your brand temperature.": "Iterative Produktion mit präziser Kontrolle. Jedes Element wird an die Temperatur Ihrer Marke angepasst.",
    "motion, matter, and the molecular brand": "Bewegung, Materie und die molekulare Marke",
    "precision-roasted molecular coffee. sourced at origin. analyzed in lab. delivered in spectrum.": "Molekular gerösteter Kaffee mit Präzision. An der Quelle bezogen. Im Labor analysiert. Im Spektrum geliefert.",
    "quarterly brand review": "Vierteljährliche Markenbewertung",
    "red dot best of best": "Red Dot Beste der Besten",
    "shop beans": "BOHNEN KAUFEN",
    "start a": "Starten Sie ein",
    "submit brief": "Brief einreichen",
    "the infrastructure for the next generation of specialty coffee. est. 2026. precision roasted. globally sourced.": "Die Infrastruktur für die nächste Generation von Spezialitätenkaffee. Est. 2026. Präzise geröstet. Global bezogen.",
    "they said.": "Sie sagten.",
    "they think at a frequency we had never encountered before. the final campaign exceeded every brief metric we set.": "Sie denken in einer Frequenz, die wir zuvor noch nie erlebt hatten. Die endgültige Kampagne übertraf jede von uns festgelegte Kennzahl.",
    "we take on a limited number of new clients each quarter. submit your brief and we will respond within 48 hours.": "Wir nehmen jedes Quartal eine begrenzte Anzahl neuer Kunden an. Reichen Sie Ihr Briefing ein und wir werden innerhalb von 48 Stunden antworten.",
    "what we do.": "Was wir tun.",
    "when coffee meets computation": "Wenn Kaffee auf Berechnung trifft",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "our lineages": "As nossas linhagens",
    "explore our signature lineages. from rigorous ashtanga to restorative yin.": "Explore as nossas linhagens, do ashtanga rigoroso ao yin reparador.",
    "beginner": "Principiante",
    "advanced": "Avançado",
    "lineage keepers": "Guardiões da linhagem",
    "your": "Os seus",
    "guides.": "guias.",
    "meet the experienced practitioners guiding your evolution.": "Conheça os praticantes experientes que guiam a sua evolução.",
    "vinyasa & meditation": "Vinyasa e meditação",
    "ashtanga & pranayama": "Ashtanga e pranayama",
    "yin & sound healing": "Yin e sonoterapia",
    "yin & sound bath": "Yin e banho sonoro",
    "dedicated to sharing traditional, breath-centered yoga with anatomical safety. over 1 000 hours of training in mysore and rishikesh.": "Dedicada a transmitir um yoga tradicional centrado na respiração, com segurança anatómica. Mais de 1 000 horas de formação em Mysore e Rishikesh.",
    "extraction physics": "Física da extração",
    "brew": "Lógica",
    "logic.": "de extração.",
    "maximize the genetic potential of your beans. our laboratory-tested protocols ensure peak extraction efficiency.": "Tire o melhor do potencial dos seus grãos: os nossos protocolos testados em laboratório garantem uma extração ótima.",
    "extraction yield": "Rendimento de extração",
    "the sweet spot of soluble solids. balancing acidity and body.": "O ponto de equilíbrio dos sólidos solúveis, entre acidez e corpo.",
    "water purity": "Pureza da água",
    "how do you integrate generative ai in your process?": "Como integram a IA generativa no vosso método?",
    "what is your approach to sustainable materials?": "Qual é a vossa abordagem aos materiais duráveis?",
    "can you handle international project management?": "Asseguram a gestão de projetos internacionais?",
    "what are your standard consultation fees?": "Quais são os vossos honorários de consulta?",
    "request": "Pedir um",
    "invitation.": "convite.",
    "membership is strictly regulated to preserve the atmosphere. provide your credentials below.": "A adesão é estritamente regulada para preservar a atmosfera. Apresente-se abaixo.",
    "✓ access to private rooms across berlin, ibiza, tokyo, and miami.": "✓ Acesso aos salões privados de Berlim, Ibiza, Tóquio e Miami.",
    "✓ custom sensory key card with encrypted nfc security.": "✓ Cartão de acesso sensorial personalizado, com segurança NFC cifrada.",
    "✓ private invitations to pop-up secret architectural stages.": "✓ Convites privados para os palcos efémeros secretos.",
    "contact email": "Endereço de e-mail",
    "primary node": "Cidade principal",
    "berlin hub": "Berlim",
    "ibiza retreat": "Ibiza",
    "tokyo underground": "Tóquio",
    "curated fleet": "Frota selecionada",
    "pratiques.": "práticas.",
    "archive": "Arquivo",
    "full archive": "Todo o arquivo",
    "global operations": "As nossas implantações",
    "global inventory": "Inventário mundial",
    "global sourcing": "Aprovisionamento mundial",
    "residential": "Residencial",
    "commercial": "Terciário",
    "cultural": "Cultural",
    "countries": "Países",
    "completed projects": "Projetos entregues",
    "publications": "Publicações",
    "location:": "Local:",
    "materials": "Materiais",
    "philosophy": "Filosofia",
    "anatomy": "Anatomia",
    "heritage": "Herança",
    "brewing": "A extração",
    "origins": "Origens",
    "ovens": "Os nossos fornos",
    "subscription": "Assinatura",
    "fresh batch": "Fornada do dia",
    "modern.": "Moderno.",
    "artisanal.": "Artesanal.",
    "celestial.": "Celeste.",
    "void &": "O vazio",
    "volume.": "e o volume.",
    "pure": "Volume",
    "mastery of": "O domínio",
    "duration.": "da duração.",
    "examine portals": "Ver os projetos",
    "structure / light / materiality / void": "ESTRUTURA / LUZ / MATÉRIA / VAZIO",
    "riba awards": "Prémios RIBA",
    "established 1924 // geneva, ch": "Fundada em 1924 // Genebra, Suíça",
    "swiss alps, ch": "Alpes suíços, Suíça",
    "dubai, uae": "Dubai, Emirados Árabes Unidos",
    "tokyo, jp": "Tóquio, Japão",
    "oslo, no": "Oslo, Noruega",
    "seoul, kr": "Seul, Coreia do Sul",
    "berlin, de": "Berlim, Alemanha",
    "kyoto, jp": "Quioto, Japão",
    "malibu, ca": "Malibu, Califórnia",
    "projects.": "Trabalhos.",
    "art direction": "Direção de arte",
    "retail": "Ponto de venda",
    "sourdough": "Pão de massa-mãe",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentação de 48 horas. Côdea com carvão vegetal. Mistura de cereais antigos.",
    "aop butter. 256 layers. golden honeycomb structure.": "Manteiga DOP. 256 camadas. Alveolado dourado.",
    "high hydration. stone-baked. intense caramelization.": "Alta hidratação. Cozedura em pedra. Caramelização intensa.",
    "add_to_bag": "Juntar_ao_cesto",
    "baking": "Protocolo",
    "protocol.": "de cozedura.",
    "hydration ratio": "Taxa de hidratação",
    "maximizing crumb elasticity through high-hydration dough processing.": "Um miolo mais elástico, obtido por amassadura de alta hidratação.",
    "cold fermentation": "Fermentação a frio",
    "the": "A",
    "daily batch.": "fornada do dia.",
    "a rare studio that treats every project like it is their own brand — obsessive, principled, and relentlessly precise.": "Um estúdio raro que trata cada projeto como se fosse a sua própria marca — obsessivo, principiado e implacavelmente preciso.",
    "aether studio and the precision of creative systems": "O atelier e a precisão dos sistemas criativos",
    "aether transformed our visual identity into something we are genuinely proud to put in front of the world. the attention to craft is unreal.": "Aether transformou a nossa identidade visual em algo de que estamos genuinamente orgulhosos de apresentar ao mundo. A atenção ao detalhe é irreal.",
    "brand audit, logo redesign, and core identity system. for startups and early-stage brands.": "Auditoria de marca, redesenho do logótipo e sistema de identidade. Para startups e marcas nascentes.",
    "brand new": "Identidade nova",
    "clients actifs": "Clientes ativos",
    "complete brand system with motion identity, digital templates, and campaign direction.": "Sistema de marca completo com identidade em movimento, modelos digitais e direção de campanha.",
    "conceptual development under pressure. we synthesize findings into a series of bold creative directions.": "Desenvolvimento conceitual sob pressão. Sintetizamos as descobertas em uma série de ousadas direções criativas.",
    "dedicated creative team": "Equipe criativa dedicada",
    "deep-dive research into your brand dna, competitors, and target signal. we map the chemical composition of the problem.": "Pesquisa aprofundada sobre o DNA da sua marca, concorrentes e sinal-alvo. Mapeamos a composição química do problema.",
    "design systems": "Sistemas de design",
    "end-to-end brand architecture: identity, tone of voice, touchpoint design, and living system documentation.": "Arquitetura de marca de ponta a ponta: identidade, tom de voz, design de pontos de contato e documentação de sistemas vivos.",
    "everything in espresso": "Tudo em Espresso",
    "everything in full extraction": "Tudo em extração total",
    "explore roast spectrum": "Explorar o Espectro de Torrefação",
    "flawless delivery across all touchpoints. post-launch analysis and system documentation included.": "Entrega impecável em todos os pontos de contato. Análise pós-lançamento e documentação do sistema incluídas.",
    "fluid motion design and three-dimensional worldbuilding for film titles, product reveals, and brand campaigns.": "Design de movimento fluido e construção de mundos tridimensionais para títulos de filmes, revelações de produtos e campanhas de marca.",
    "from €12,000": "A partir de 12 000 €",
    "from €28,000": "A partir de 28 000 €",
    "from €6,500/mo": "A partir de 6 500 €/mês",
    "generative visuals, custom tooling, and interactive installations at the intersection of code and sensory experience.": "Visuais generativos, ferramentas personalizadas e instalações interativas na interseção do código e da experiência sensorial.",
    "identity design": "Design de identidade",
    "in caffeine we trust": "Acreditamos na cafeína",
    "it's annecy that": "É Annecy que",
    "iterative production with precision control. every element calibrated against your brand temperature.": "Produção iterativa com controle de precisão. Cada elemento calibrado de acordo com a temperatura da sua marca.",
    "motion, matter, and the molecular brand": "O movimento, a matéria e a marca molecular",
    "precision-roasted molecular coffee. sourced at origin. analyzed in lab. delivered in spectrum.": "Café molecular torrado com precisão. Com origem rastreada. Analisado em laboratório. Entregue em espectro.",
    "quarterly brand review": "Revisão de marca trimestral",
    "red dot best of best": "Red Dot Melhor dos Melhores",
    "shop beans": "COMPRAR FEIJÕES",
    "start a": "Iniciar um",
    "submit brief": "Submeter Resumo",
    "the infrastructure for the next generation of specialty coffee. est. 2026. precision roasted. globally sourced.": "A infraestrutura para a próxima geração de café especial. Est. 2026. Torrado com precisão. Sourced globalmente.",
    "they said.": "Disseram.",
    "they think at a frequency we had never encountered before. the final campaign exceeded every brief metric we set.": "Eles pensam a uma frequência que nunca havíamos encontrado antes. A campanha final superou todas as métricas do briefing que definimos.",
    "we take on a limited number of new clients each quarter. submit your brief and we will respond within 48 hours.": "Aceitamos um número limitado de novos clientes a cada trimestre. Submeta o seu resumo e responderemos dentro de 48 horas.",
    "what we do.": "O que fazemos.",
    "when coffee meets computation": "Quando o café encontra a computação",
  },
};
