/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Disponible pour des commandes éditoriales, commerciales et d'art imprimé. Réponse sous 48 heures.",
    "browse archive": "Parcourir l'archive",
    "client signals // testimonials": "SIGNALS CLIENTS // TÉMOIGNAGES",
    "contact_node // open": "CONTACT // OUVERT",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Mouvements de manufacture assemblés à la main pour le collectionneur exigeant. Précision suisse, finition exceptionnelle — calibrée à la perfection.",
    "in mastery we trust": "Nous croyons à la maîtrise",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "L'horlogerie institutionnelle, pour le siècle à venir. Depuis 1924. Calibrer l'infini par la précision de la structure.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Impressions d'archives en édition limitée sur papier de qualité muséale. Chaque pièce est signée et numérotée.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "La capacité de Luca à extraire l'essentiel d'une scène est sans pareil. Sa campagne Vogue a doublé nos ventes en kiosque.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Couvres de magazines, éditoriaux de mode et direction créative pour des publications haut de gamme dans le monde entier.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Galas privées, ouvertures architecturales et événements culturels exclusifs capturés dans un style documentaire.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Campagnes produits, photographie d'identité de marque et séances photo publicitaires pour des clients de luxe.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "La campagne Dior que nous avons produite ensemble reste la plus partagée de notre histoire. Son œil pour la précision temporelle est extraordinaire.",
    "the photographer // about": "LE PHOTOGRAPHE // À PROPOS",
    "the silent hour": "L'heure silencieuse",
    "the_photographer // about": "LE_PHOTOGRAPHE // À PROPOS",
    "they said.": "Ils ont dit.",
    "view manifesto": "Voir le manifeste",
    "work.": "Travail.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Travailler avec Luca sur la série d'architecture Wallpaper* a été une révélation. Il voit dans la géométrie là où d'autres voient dans la lumière.",
  },
  es: {
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Disponible para comisiones editoriales, comerciales y de impresión fina. Respuesta en 48 horas.",
    "browse archive": "Explorar archivo",
    "client signals // testimonials": "SEÑALES DEL CLIENTE // TESTIMONIOS",
    "contact_node // open": "CONTACTO // ABIERTO",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Movimientos de manufactura ensamblados a mano para el coleccionista exigente. Precisión suiza, acabado excepcional — calibrado a la perfección.",
    "in mastery we trust": "Creemos en la maestría",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "La relojería institucional, para el siglo venidero. Desde 1924. Calibrar el infinito mediante la precisión de la estructura.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Impresiones de archivo de edición limitada en papel de calidad de museo. Cada pieza está firmada y numerada.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "La habilidad de Luca para extraer lo esencial de una escena es única. Su campaña de Vogue duplicó nuestras cifras de quiosco.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Portadas de revistas, editoriales de moda y dirección creativa para publicaciones de alta gama en todo el mundo.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Galas privadas, aperturas arquitectónicas y eventos culturales exclusivos capturados en estilo documental.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Campañas de productos, fotografía de identidad de marca y sesiones publicitarias para clientes de lujo.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "La campaña de Dior que producimos juntos sigue siendo la más compartida en nuestra historia. Su ojo para la precisión temporal es extraordinario.",
    "the photographer // about": "EL FOTÓGRAFO // ACERCA DE",
    "the silent hour": "La hora silenciosa",
    "the_photographer // about": "EL_FOTÓGRAFO // SOBRE",
    "they said.": "Dijeron.",
    "view manifesto": "Ver manifiesto",
    "work.": "Trabajo.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Trabajar con Luca en la serie de arquitectura Wallpaper* fue una revelación. Él ve en la geometría donde otros ven en la luz.",
  },
  de: {
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Verfügbar für redaktionelle, kommerzielle und feine Druckaufträge. Antwort innerhalb von 48 Stunden.",
    "browse archive": "Archiv durchsuchen",
    "client signals // testimonials": "KUNDENSIGNAL // TESTIMONIALS",
    "contact_node // open": "KONTAKT // OFFEN",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Handgefertigte Manufakturwerke für den anspruchsvollen Sammler. Schweizer Präzision, außergewöhnliche Verarbeitung — auf Perfektion kalibriert.",
    "in mastery we trust": "Wir vertrauen der Meisterschaft",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "Institutionelle Uhrmacherkunst für das kommende Jahrhundert. Seit 1924. Das Unendliche durch strukturelle Präzision kalibrieren.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Limitierte Archivdrucke auf museumsgüte Papier. Jedes Stück ist signiert und nummeriert.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "Lucas Fähigkeit, das Wesentliche aus einer Szene herauszuziehen, ist einzigartig. Seine Vogue-Kampagne verdoppelte unsere Verkaufszahlen am Kiosk.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Magazincover, Modeeditorials und kreative Leitung für hochwertige Publikationen weltweit.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Private Galas, architektonische Eröffnungen und exklusive kulturelle Veranstaltungen im dokumentarischen Stil festgehalten.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Produktkampagnen, Markenidentitätsfotografie und Werbeaufnahmen für Luxusklienten.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "Die Dior-Kampagne, die wir gemeinsam produziert haben, bleibt die meistgeteilte in unserer Geschichte. Sein Auge für zeitliche Präzision ist außergewöhnlich.",
    "the photographer // about": "DER FOTOGRAF // ÜBER",
    "the silent hour": "Die stille Stunde",
    "the_photographer // about": "DER_FOTOGRAF // ÜBER",
    "they said.": "Sie sagten.",
    "view manifesto": "Manifest ansehen",
    "work.": "Arbeit.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Die Zusammenarbeit mit Luca an der Wallpaper*-Architektureihe war eine Offenbarung. Er sieht in der Geometrie, wo andere im Licht sehen.",
  },
  pt: {
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Disponível para comissões editoriais, comerciais e de impressão fina. Resposta em 48 horas.",
    "browse archive": "Navegar pelo arquivo",
    "client signals // testimonials": "SINAIS DO CLIENTE // TESTEMUNHOS",
    "contact_node // open": "CONTACTO // ABERTO",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Movimentos de manufatura montados à mão para o colecionador exigente. Precisão suíça, acabamento excepcional — calibrado à perfeição.",
    "in mastery we trust": "Acreditamos na mestria",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "A relojoaria institucional, para o século vindouro. Desde 1924. Calibrar o infinito pela precisão da estrutura.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Impressões de arquivo em edição limitada em papel de qualidade museológica. Cada peça é assinada e numerada.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "A capacidade de Luca de extrair o essencial de uma cena é incomparável. A sua campanha da Vogue duplicou as nossas vendas em quiosques.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Capa de revistas, editoriais de moda e direção criativa para publicações de alta gama em todo o mundo.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Gala privadas, aberturas arquitetónicas e eventos culturais exclusivos capturados em estilo documental.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Campanhas de produtos, fotografia de identidade de marca e sessões publicitárias para clientes de luxo.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "A campanha da Dior que produzimos juntos continua a ser a mais partilhada da nossa história. O seu olhar para a precisão temporal é extraordinário.",
    "the photographer // about": "O FOTÓGRAFO // SOBRE",
    "the silent hour": "A hora silenciosa",
    "the_photographer // about": "O_FOTÓGRAFO // SOBRE",
    "they said.": "Disseram.",
    "view manifesto": "Ver manifesto",
    "work.": "Trabalho.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Trabalhar com Luca na série de arquitetura Wallpaper* foi uma revelação. Ele vê na geometria onde outros veem na luz.",
  },
};
