/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "what is your global service protocol?": "Comment fonctionne votre service après-vente mondial ?",
    "do you offer bespoke dial commissions?": "Réalisez-vous des cadrans sur mesure ?",
    "what is the lead time for a new reservation?": "Quel est le délai pour une nouvelle réservation ?",
    "are your timepieces cryptocurrency compatible?": "Acceptez-vous le paiement en cryptomonnaie ?",
    "submit your response": "Envoyer votre réponse",
    "legal_mentions": "Mentions_légales",
    "headquarters": "Siège",
    "regulatory_terms": "Conditions_générales",
    "privacy_buffer": "Confidentialité",
    "geneva // tokyo // dubai": "Genève // Tokyo // Dubaï",
    "network": "Réseau",
    "private_viewing": "Présentation_privée",
    "service_ledger": "Carnet_d_entretien",
    "archive": "Archives",
    "full archive": "Toutes les archives",
    "global operations": "Nos implantations",
    "global inventory": "Stock mondial",
    "global sourcing": "Approvisionnement mondial",
    "residential": "Résidentiel",
    "commercial": "Tertiaire",
    "cultural": "Culturel",
    "countries": "Pays",
    "completed projects": "Projets livrés",
    "publications": "Publications",
    "location:": "Lieu :",
    "materials": "Matériaux",
    "philosophy": "Philosophie",
    "anatomy": "Anatomie",
    "heritage": "Héritage",
    "brewing": "L'extraction",
    "origins": "Origines",
    "ovens": "Nos fours",
    "subscription": "Abonnement",
    "fresh batch": "Fournée du jour",
    "modern.": "Moderne.",
    "artisanal.": "Artisanal.",
    "celestial.": "Céleste.",
    "void &": "Le vide",
    "volume.": "et le volume.",
    "pure": "Volume",
    "mastery of": "La maîtrise",
    "duration.": "de la durée.",
    "examine portals": "Voir les projets",
    "structure / light / materiality / void": "STRUCTURE / LUMIÈRE / MATIÈRE / VIDE",
    "riba awards": "Prix RIBA",
    "established 1924 // geneva, ch": "Fondée en 1924 // Genève, Suisse",
    "swiss alps, ch": "Alpes suisses, Suisse",
    "dubai, uae": "Dubaï, Émirats arabes unis",
    "tokyo, jp": "Tokyo, Japon",
    "oslo, no": "Oslo, Norvège",
    "seoul, kr": "Séoul, Corée du Sud",
    "berlin, de": "Berlin, Allemagne",
    "kyoto, jp": "Kyoto, Japon",
    "malibu, ca": "Malibu, Californie",
    "projects.": "Réalisations.",
    "art direction": "Direction artistique",
    "retail": "Point de vente",
    "sourdough": "Pain au levain",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentation de 48 heures. Croûte au charbon végétal. Assemblage de blés anciens.",
    "aop butter. 256 layers. golden honeycomb structure.": "Beurre AOP. 256 couches. Alvéolage doré.",
    "high hydration. stone-baked. intense caramelization.": "Forte hydratation. Cuisson sur pierre. Caramélisation intense.",
    "add_to_bag": "Ajouter_au_panier",
    "baking": "Protocole",
    "protocol.": "de cuisson.",
    "hydration ratio": "Taux d'hydratation",
    "maximizing crumb elasticity through high-hydration dough processing.": "Une mie plus élastique, obtenue par un pétrissage à forte hydratation.",
    "cold fermentation": "Fermentation à froid",
    "the": "La",
    "daily batch.": "fournée du jour.",
    "the_photographer // about": "LE_PHOTOGRAPHE // À PROPOS",
    "based between geneva and tokyo, luca arantes built his practice on the precision of mechanical time — transposing the watchmaker's obsession with detail into the photographic frame. every composition is a calibration. every exposure a deliberate act of structural intelligence. working exclusively on medium format, his images have appeared in vogue, wallpaper*, and dezeen, and hang in private collections across 12 countries.": "Installé entre Genève et Tokyo, il a bâti sa pratique sur la précision du temps mécanique — l'obsession du détail d'un horloger transposée dans le cadre. Chaque composition est un réglage, chaque exposition un acte délibéré. Il travaille exclusivement au moyen format ; ses images ont paru dans Vogue, Wallpaper* et Dezeen, et figurent dans des collections privées de douze pays.",
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Disponible pour des commandes éditoriales, commerciales et d'art imprimé. Réponse sous 48 heures.",
    "browse archive": "Parcourir l'archive",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Mouvements de manufacture assemblés à la main pour le collectionneur exigeant. Précision suisse, finition exceptionnelle — calibrée à la perfection.",
    "in mastery we trust": "Nous croyons à la maîtrise",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "L'horlogerie institutionnelle, pour le siècle à venir. Depuis 1924. Calibrer l'infini par la précision de la structure.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Impressions d'archives en édition limitée sur papier de qualité muséale. Chaque pièce est signée et numérotée.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "La capacité de Luca à extraire l'essentiel d'une scène est sans pareil. Sa campagne Vogue a doublé nos ventes en kiosque.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Couvres de magazines, éditoriaux de mode et direction créative pour des publications haut de gamme dans le monde entier.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Galas privées, ouvertures architecturales et événements culturels exclusifs capturés dans un style documentaire.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Campagnes produits, photographie d'identité de marque et séances photo publicitaires pour des clients de luxe.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "La campagne Dior que nous avons produite ensemble reste la plus partagée de notre histoire. Son œil pour la précision temporelle est extraordinaire.",
    "the silent hour": "L'heure silencieuse",
    "they said.": "Ils ont dit.",
    "view manifesto": "Voir le manifeste",
    "work.": "Travail.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Travailler avec Luca sur la série d'architecture Wallpaper* a été une révélation. Il voit dans la géométrie là où d'autres voient dans la lumière.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "what is your global service protocol?": "¿Cómo funciona su servicio posventa mundial?",
    "do you offer bespoke dial commissions?": "¿Realizan esferas a medida?",
    "what is the lead time for a new reservation?": "¿Cuál es el plazo para una nueva reserva?",
    "are your timepieces cryptocurrency compatible?": "¿Aceptan el pago en criptomonedas?",
    "submit your response": "Enviar su respuesta",
    "legal_mentions": "Aviso_legal",
    "headquarters": "Sede",
    "regulatory_terms": "Condiciones_generales",
    "privacy_buffer": "Confidencialidad",
    "geneva // tokyo // dubai": "Ginebra // Tokio // Dubái",
    "network": "Red",
    "private_viewing": "Presentación_privada",
    "service_ledger": "Registro_de_servicio",
    "archive": "Archivo",
    "full archive": "Todo el archivo",
    "global operations": "Nuestras sedes",
    "global inventory": "Inventario mundial",
    "global sourcing": "Abastecimiento mundial",
    "residential": "Residencial",
    "commercial": "Terciario",
    "cultural": "Cultural",
    "countries": "Países",
    "completed projects": "Proyectos entregados",
    "publications": "Publicaciones",
    "location:": "Lugar:",
    "materials": "Materiales",
    "philosophy": "Filosofía",
    "anatomy": "Anatomía",
    "heritage": "Herencia",
    "brewing": "La extracción",
    "origins": "Orígenes",
    "ovens": "Nuestros hornos",
    "subscription": "Suscripción",
    "fresh batch": "Hornada del día",
    "modern.": "Moderno.",
    "artisanal.": "Artesanal.",
    "celestial.": "Celeste.",
    "void &": "El vacío",
    "volume.": "y el volumen.",
    "pure": "Volumen",
    "mastery of": "El dominio",
    "duration.": "de la duración.",
    "examine portals": "Ver los proyectos",
    "structure / light / materiality / void": "ESTRUCTURA / LUZ / MATERIA / VACÍO",
    "riba awards": "Premios RIBA",
    "established 1924 // geneva, ch": "Fundada en 1924 // Ginebra, Suiza",
    "swiss alps, ch": "Alpes suizos, Suiza",
    "dubai, uae": "Dubái, Emiratos Árabes Unidos",
    "tokyo, jp": "Tokio, Japón",
    "oslo, no": "Oslo, Noruega",
    "seoul, kr": "Seúl, Corea del Sur",
    "berlin, de": "Berlín, Alemania",
    "kyoto, jp": "Kioto, Japón",
    "malibu, ca": "Malibú, California",
    "projects.": "Trabajos.",
    "art direction": "Dirección de arte",
    "retail": "Punto de venta",
    "sourdough": "Pan de masa madre",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentación de 48 horas. Corteza al carbón vegetal. Mezcla de granos antiguos.",
    "aop butter. 256 layers. golden honeycomb structure.": "Mantequilla DOP. 256 capas. Alveolado dorado.",
    "high hydration. stone-baked. intense caramelization.": "Alta hidratación. Cocción en piedra. Caramelización intensa.",
    "add_to_bag": "Añadir_a_la_cesta",
    "baking": "Protocolo",
    "protocol.": "de cocción.",
    "hydration ratio": "Tasa de hidratación",
    "maximizing crumb elasticity through high-hydration dough processing.": "Una miga más elástica, obtenida mediante un amasado de alta hidratación.",
    "cold fermentation": "Fermentación en frío",
    "the": "La",
    "daily batch.": "hornada del día.",
    "the_photographer // about": "EL_FOTÓGRAFO // SOBRE MÍ",
    "based between geneva and tokyo, luca arantes built his practice on the precision of mechanical time — transposing the watchmaker's obsession with detail into the photographic frame. every composition is a calibration. every exposure a deliberate act of structural intelligence. working exclusively on medium format, his images have appeared in vogue, wallpaper*, and dezeen, and hang in private collections across 12 countries.": "Instalado entre Ginebra y Tokio, ha construido su práctica sobre la precisión del tiempo mecánico — la obsesión por el detalle de un relojero llevada al encuadre. Cada composición es un ajuste, cada exposición un acto deliberado. Trabaja exclusivamente en formato medio; sus imágenes han aparecido en Vogue, Wallpaper* y Dezeen, y están en colecciones privadas de doce países.",
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Disponible para comisiones editoriales, comerciales y de impresión fina. Respuesta en 48 horas.",
    "browse archive": "Explorar archivo",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Movimientos de manufactura ensamblados a mano para el coleccionista exigente. Precisión suiza, acabado excepcional — calibrado a la perfección.",
    "in mastery we trust": "Creemos en la maestría",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "La relojería institucional, para el siglo venidero. Desde 1924. Calibrar el infinito mediante la precisión de la estructura.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Impresiones de archivo de edición limitada en papel de calidad de museo. Cada pieza está firmada y numerada.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "La habilidad de Luca para extraer lo esencial de una escena es única. Su campaña de Vogue duplicó nuestras cifras de quiosco.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Portadas de revistas, editoriales de moda y dirección creativa para publicaciones de alta gama en todo el mundo.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Galas privadas, aperturas arquitectónicas y eventos culturales exclusivos capturados en estilo documental.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Campañas de productos, fotografía de identidad de marca y sesiones publicitarias para clientes de lujo.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "La campaña de Dior que producimos juntos sigue siendo la más compartida en nuestra historia. Su ojo para la precisión temporal es extraordinario.",
    "the silent hour": "La hora silenciosa",
    "they said.": "Dijeron.",
    "view manifesto": "Ver manifiesto",
    "work.": "Trabajo.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Trabajar con Luca en la serie de arquitectura Wallpaper* fue una revelación. Él ve en la geometría donde otros ven en la luz.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "what is your global service protocol?": "Wie funktioniert Ihr weltweiter Kundendienst?",
    "do you offer bespoke dial commissions?": "Fertigen Sie Zifferblätter nach Maß?",
    "what is the lead time for a new reservation?": "Wie lang ist die Wartezeit bei einer neuen Reservierung?",
    "are your timepieces cryptocurrency compatible?": "Akzeptieren Sie Zahlung in Kryptowährung?",
    "submit your response": "Antwort senden",
    "legal_mentions": "Impressum",
    "headquarters": "Hauptsitz",
    "regulatory_terms": "Allgemeine_Bedingungen",
    "privacy_buffer": "Datenschutz",
    "geneva // tokyo // dubai": "Genf // Tokio // Dubai",
    "network": "Netzwerk",
    "private_viewing": "Private_Vorführung",
    "service_ledger": "Serviceheft",
    "archive": "Archiv",
    "full archive": "Gesamtes Archiv",
    "global operations": "Unsere Standorte",
    "global inventory": "Weltweiter Bestand",
    "global sourcing": "Weltweite Beschaffung",
    "residential": "Wohnbau",
    "commercial": "Gewerbe",
    "cultural": "Kultur",
    "countries": "Länder",
    "completed projects": "Fertiggestellte Projekte",
    "publications": "Publikationen",
    "location:": "Ort:",
    "materials": "Werkstoffe",
    "philosophy": "Philosophie",
    "anatomy": "Anatomie",
    "heritage": "Erbe",
    "brewing": "Die Zubereitung",
    "origins": "Herkünfte",
    "ovens": "Unsere Öfen",
    "subscription": "Abonnement",
    "fresh batch": "Frische Charge",
    "modern.": "Modern.",
    "artisanal.": "Handwerklich.",
    "celestial.": "Himmlisch.",
    "void &": "Leere und",
    "volume.": "Volumen.",
    "pure": "Reines",
    "mastery of": "Die Beherrschung",
    "duration.": "der Dauer.",
    "examine portals": "Projekte ansehen",
    "structure / light / materiality / void": "STRUKTUR / LICHT / MATERIAL / LEERE",
    "riba awards": "RIBA-Preise",
    "established 1924 // geneva, ch": "Gegründet 1924 // Genf, Schweiz",
    "swiss alps, ch": "Schweizer Alpen, CH",
    "dubai, uae": "Dubai, VAE",
    "tokyo, jp": "Tokio, Japan",
    "oslo, no": "Oslo, Norwegen",
    "seoul, kr": "Seoul, Südkorea",
    "berlin, de": "Berlin, Deutschland",
    "kyoto, jp": "Kyoto, Japan",
    "malibu, ca": "Malibu, Kalifornien",
    "projects.": "Arbeiten.",
    "art direction": "Art Direction",
    "retail": "Einzelhandel",
    "sourdough": "Sauerteigbrot",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "48 Stunden Fermentation. Kruste mit Aktivkohle. Mischung alter Getreidesorten.",
    "aop butter. 256 layers. golden honeycomb structure.": "AOP-Butter. 256 Schichten. Goldene Wabenstruktur.",
    "high hydration. stone-baked. intense caramelization.": "Hohe Hydratation. Steinofengebacken. Intensive Karamellisierung.",
    "add_to_bag": "In_den_Korb",
    "baking": "Back-",
    "protocol.": "protokoll.",
    "hydration ratio": "Hydratationsgrad",
    "maximizing crumb elasticity through high-hydration dough processing.": "Elastischere Krume durch Teigführung mit hoher Hydratation.",
    "cold fermentation": "Kalte Führung",
    "the": "Die",
    "daily batch.": "Tagescharge.",
    "the_photographer // about": "DER_FOTOGRAF // ÜBER MICH",
    "based between geneva and tokyo, luca arantes built his practice on the precision of mechanical time — transposing the watchmaker's obsession with detail into the photographic frame. every composition is a calibration. every exposure a deliberate act of structural intelligence. working exclusively on medium format, his images have appeared in vogue, wallpaper*, and dezeen, and hang in private collections across 12 countries.": "Zwischen Genf und Tokio ansässig, gründet seine Arbeit auf der Präzision mechanischer Zeit — die Detailbesessenheit eines Uhrmachers, übertragen auf den Bildausschnitt. Jede Komposition ist eine Justierung, jede Belichtung ein bewusster Akt. Er arbeitet ausschließlich im Mittelformat; seine Bilder erschienen in Vogue, Wallpaper* und Dezeen und hängen in Privatsammlungen in zwölf Ländern.",
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Verfügbar für redaktionelle, kommerzielle und feine Druckaufträge. Antwort innerhalb von 48 Stunden.",
    "browse archive": "Archiv durchsuchen",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Handgefertigte Manufakturwerke für den anspruchsvollen Sammler. Schweizer Präzision, außergewöhnliche Verarbeitung — auf Perfektion kalibriert.",
    "in mastery we trust": "Wir vertrauen der Meisterschaft",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "Institutionelle Uhrmacherkunst für das kommende Jahrhundert. Seit 1924. Das Unendliche durch strukturelle Präzision kalibrieren.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Limitierte Archivdrucke auf museumsgüte Papier. Jedes Stück ist signiert und nummeriert.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "Lucas Fähigkeit, das Wesentliche aus einer Szene herauszuziehen, ist einzigartig. Seine Vogue-Kampagne verdoppelte unsere Verkaufszahlen am Kiosk.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Magazincover, Modeeditorials und kreative Leitung für hochwertige Publikationen weltweit.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Private Galas, architektonische Eröffnungen und exklusive kulturelle Veranstaltungen im dokumentarischen Stil festgehalten.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Produktkampagnen, Markenidentitätsfotografie und Werbeaufnahmen für Luxusklienten.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "Die Dior-Kampagne, die wir gemeinsam produziert haben, bleibt die meistgeteilte in unserer Geschichte. Sein Auge für zeitliche Präzision ist außergewöhnlich.",
    "the silent hour": "Die stille Stunde",
    "they said.": "Sie sagten.",
    "view manifesto": "Manifest ansehen",
    "work.": "Arbeit.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Die Zusammenarbeit mit Luca an der Wallpaper*-Architektureihe war eine Offenbarung. Er sieht in der Geometrie, wo andere im Licht sehen.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "what is your global service protocol?": "Como funciona o vosso serviço pós-venda mundial?",
    "do you offer bespoke dial commissions?": "Fazem mostradores por medida?",
    "what is the lead time for a new reservation?": "Qual é o prazo para uma nova reserva?",
    "are your timepieces cryptocurrency compatible?": "Aceitam pagamento em criptomoeda?",
    "submit your response": "Enviar a sua resposta",
    "legal_mentions": "Menções_legais",
    "headquarters": "Sede",
    "regulatory_terms": "Condições_gerais",
    "privacy_buffer": "Confidencialidade",
    "geneva // tokyo // dubai": "Genebra // Tóquio // Dubai",
    "network": "Rede",
    "private_viewing": "Apresentação_privada",
    "service_ledger": "Registo_de_serviço",
    "archive": "Arquivo",
    "full archive": "Todo o arquivo",
    "global operations": "As nossas implantações",
    "global inventory": "Inventário mundial",
    "global sourcing": "Aprovisionamento mundial",
    "residential": "Residencial",
    "commercial": "Terciário",
    "cultural": "Cultural",
    "countries": "Países",
    "completed projects": "Projetos entregues",
    "publications": "Publicações",
    "location:": "Local:",
    "materials": "Materiais",
    "philosophy": "Filosofia",
    "anatomy": "Anatomia",
    "heritage": "Herança",
    "brewing": "A extração",
    "origins": "Origens",
    "ovens": "Os nossos fornos",
    "subscription": "Assinatura",
    "fresh batch": "Fornada do dia",
    "modern.": "Moderno.",
    "artisanal.": "Artesanal.",
    "celestial.": "Celeste.",
    "void &": "O vazio",
    "volume.": "e o volume.",
    "pure": "Volume",
    "mastery of": "O domínio",
    "duration.": "da duração.",
    "examine portals": "Ver os projetos",
    "structure / light / materiality / void": "ESTRUTURA / LUZ / MATÉRIA / VAZIO",
    "riba awards": "Prémios RIBA",
    "established 1924 // geneva, ch": "Fundada em 1924 // Genebra, Suíça",
    "swiss alps, ch": "Alpes suíços, Suíça",
    "dubai, uae": "Dubai, Emirados Árabes Unidos",
    "tokyo, jp": "Tóquio, Japão",
    "oslo, no": "Oslo, Noruega",
    "seoul, kr": "Seul, Coreia do Sul",
    "berlin, de": "Berlim, Alemanha",
    "kyoto, jp": "Quioto, Japão",
    "malibu, ca": "Malibu, Califórnia",
    "projects.": "Trabalhos.",
    "art direction": "Direção de arte",
    "retail": "Ponto de venda",
    "sourdough": "Pão de massa-mãe",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentação de 48 horas. Côdea com carvão vegetal. Mistura de cereais antigos.",
    "aop butter. 256 layers. golden honeycomb structure.": "Manteiga DOP. 256 camadas. Alveolado dourado.",
    "high hydration. stone-baked. intense caramelization.": "Alta hidratação. Cozedura em pedra. Caramelização intensa.",
    "add_to_bag": "Juntar_ao_cesto",
    "baking": "Protocolo",
    "protocol.": "de cozedura.",
    "hydration ratio": "Taxa de hidratação",
    "maximizing crumb elasticity through high-hydration dough processing.": "Um miolo mais elástico, obtido por amassadura de alta hidratação.",
    "cold fermentation": "Fermentação a frio",
    "the": "A",
    "daily batch.": "fornada do dia.",
    "the_photographer // about": "O_FOTÓGRAFO // SOBRE MIM",
    "based between geneva and tokyo, luca arantes built his practice on the precision of mechanical time — transposing the watchmaker's obsession with detail into the photographic frame. every composition is a calibration. every exposure a deliberate act of structural intelligence. working exclusively on medium format, his images have appeared in vogue, wallpaper*, and dezeen, and hang in private collections across 12 countries.": "Instalado entre Genebra e Tóquio, construiu a sua prática sobre a precisão do tempo mecânico — a obsessão pelo detalhe de um relojoeiro transposta para o enquadramento. Cada composição é uma afinação, cada exposição um ato deliberado. Trabalha exclusivamente em médio formato; as suas imagens saíram na Vogue, na Wallpaper* e na Dezeen, e estão em coleções privadas de doze países.",
    "available for editorial, commercial, and fine print commissions. response within 48 hours.": "Disponível para comissões editoriais, comerciais e de impressão fina. Resposta em 48 horas.",
    "browse archive": "Navegar pelo arquivo",
    "hand-assembled manufacture movements for the discerning collector. swiss precision, exceptional finishing — calibrated to perfection.": "Movimentos de manufatura montados à mão para o colecionador exigente. Precisão suíça, acabamento excepcional — calibrado à perfeição.",
    "in mastery we trust": "Acreditamos na mestria",
    "institutional horology for the next century of timekeepers. est. 1924. calibrating the infinite through structural precision.": "A relojoaria institucional, para o século vindouro. Desde 1924. Calibrar o infinito pela precisão da estrutura.",
    "limited-edition archival prints on museum-grade paper. each piece signed and numbered.": "Impressões de arquivo em edição limitada em papel de qualidade museológica. Cada peça é assinada e numerada.",
    "luca's ability to extract the essential from a scene is unlike anything we have encountered. his vogue campaign doubled our newsstand numbers.": "A capacidade de Luca de extrair o essencial de uma cena é incomparável. A sua campanha da Vogue duplicou as nossas vendas em quiosques.",
    "magazine covers, fashion editorials, and creative direction for high-end publications worldwide.": "Capa de revistas, editoriais de moda e direção criativa para publicações de alta gama em todo o mundo.",
    "private galas, architectural openings, and exclusive cultural events captured in documentary style.": "Gala privadas, aberturas arquitetónicas e eventos culturais exclusivos capturados em estilo documental.",
    "product campaigns, brand identity photography, and advertising shoots for luxury clients.": "Campanhas de produtos, fotografia de identidade de marca e sessões publicitárias para clientes de luxo.",
    "the dior campaign we produced together remains the most-shared in our history. his eye for temporal precision is extraordinary.": "A campanha da Dior que produzimos juntos continua a ser a mais partilhada da nossa história. O seu olhar para a precisão temporal é extraordinário.",
    "the silent hour": "A hora silenciosa",
    "they said.": "Disseram.",
    "view manifesto": "Ver manifesto",
    "work.": "Trabalho.",
    "working with luca on the wallpaper* architecture series was a revelation. he sees in geometry where others see in light.": "Trabalhar com Luca na série de arquitetura Wallpaper* foi uma revelação. Ele vê na geometria onde outros veem na luz.",
  },
};
