/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "buildings completed": "Bâtiments livrés",
    "years practice": "Ans d'exercice",
    "countries": "Pays",
    "studio philosophy": "Notre philosophie",
    "next century.": "siècle prochain.",
    "space": "L'espace",
    "defines": "fait",
    "culture.": "la culture.",
    "space defines culture.": "L'espace fait la culture.",
    "architecture's primary obligation is not to its client's ego or its architect's portfolio. it is to the public realm — the street, the neighbourhood, the city — that inherits every building long after the brief is forgotten.": "L'architecture ne doit rien à l'ego du client ni au portfolio de l'architecte. Elle doit à l'espace public — la rue, le quartier, la ville — qui hérite de chaque bâtiment longtemps après que le programme est oublié.",
    "as method": "comme Méthode",
    "by the numbers": "En chiffres",
    "click any project to expand": "Cliquez sur n'importe quel projet pour développer",
    "design vision, institutional work, competition strategy": "Vision de conception, commande publique, stratégie de concours",
    "for the": "pour le",
    "is a paris-based architecture and urbanism studio. we design buildings, cities, and interiors that resist the ordinary and endure beyond fashion.": "est une agence d'architecture et d'urbanisme. Nous concevons des bâtiments, des villes et des intérieurs qui résistent à l'ordinaire et durent au-delà des modes.",
    "start a": "Démarrer un",
    "thank you!": "Merci !",
    "the studio": "L'agence",
    "we begin every project with a conversation — no brief, no fee, no obligation. tell us about your project and we will arrange an introductory meeting within five working days.": "Chaque projet commence par une conversation — sans programme, sans honoraires, sans engagement. Parlez-nous du vôtre : nous fixons un premier rendez-vous sous cinq jours ouvrés.",
    "we build": "Nous bâtissons",
    "we work on the scale of blocks, districts and towns. each project has a civic duty: repair the urban fabric rather than enclose it.": "Nous travaillons à l'échelle des blocs, des quartiers et des villes. Chaque projet a un devoir civique : réparer le tissu urbain plutôt que de l'enfermer.",
    "we work with robust materials, structural honesty, and spatial generosity. our buildings are designed to be loved, maintained, and adapted — not demolished.": "Nous travaillons des matières robustes, une structure honnête et un espace généreux. Nos bâtiments sont faits pour être aimés, entretenus et transformés — pas démolis.",
    "who we are": "Qui nous sommes",
  },
  es: {
    "buildings completed": "Edificios entregados",
    "years practice": "Años de ejercicio",
    "countries": "Países",
    "studio philosophy": "Nuestra filosofía",
    "next century.": "próximo siglo.",
    "space": "El espacio",
    "defines": "hace",
    "culture.": "la cultura.",
    "space defines culture.": "El espacio hace la cultura.",
    "architecture's primary obligation is not to its client's ego or its architect's portfolio. it is to the public realm — the street, the neighbourhood, the city — that inherits every building long after the brief is forgotten.": "La arquitectura no debe nada al ego del cliente ni a la cartera del arquitecto. Debe al espacio público —la calle, el barrio, la ciudad— que hereda cada edificio mucho después de olvidado el encargo.",
    "as method": "como Método",
    "by the numbers": "En cifras",
    "click any project to expand": "Haga clic en cualquier proyecto para expandir",
    "design vision, institutional work, competition strategy": "Visión de diseño, encargo público, estrategia de concursos",
    "for the": "para el",
    "is a paris-based architecture and urbanism studio. we design buildings, cities, and interiors that resist the ordinary and endure beyond fashion.": "es un estudio de arquitectura y urbanismo. Concebimos edificios, ciudades e interiores que resisten lo ordinario y perduran más allá de las modas.",
    "start a": "Iniciar un",
    "thank you!": "¡Gracias!",
    "the studio": "El estudio",
    "we begin every project with a conversation — no brief, no fee, no obligation. tell us about your project and we will arrange an introductory meeting within five working days.": "Cada proyecto empieza con una conversación: sin programa, sin honorarios, sin compromiso. Háblenos del suyo y fijaremos una primera cita en cinco días hábiles.",
    "we build": "Construimos",
    "we work on the scale of blocks, districts and towns. each project has a civic duty: repair the urban fabric rather than enclose it.": "Trabajamos a la escala de bloques, distritos y ciudades. Cada proyecto tiene un deber cívico: reparar el tejido urbano en lugar de encerrarlo.",
    "we work with robust materials, structural honesty, and spatial generosity. our buildings are designed to be loved, maintained, and adapted — not demolished.": "Trabajamos materias robustas, una estructura honesta y un espacio generoso. Nuestros edificios están hechos para ser queridos, mantenidos y transformados, no demolidos.",
    "who we are": "Quiénes somos",
  },
  de: {
    "buildings completed": "Fertiggestellte Gebäude",
    "years practice": "Jahre Praxis",
    "countries": "Länder",
    "studio philosophy": "Unsere Haltung",
    "next century.": "nächste Jahrhundert.",
    "space": "Der Raum",
    "defines": "formt",
    "culture.": "die Kultur.",
    "space defines culture.": "Der Raum formt die Kultur.",
    "architecture's primary obligation is not to its client's ego or its architect's portfolio. it is to the public realm — the street, the neighbourhood, the city — that inherits every building long after the brief is forgotten.": "Architektur schuldet weder dem Ego des Bauherrn noch dem Portfolio des Architekten etwas. Sie schuldet dem öffentlichen Raum — der Straße, dem Viertel, der Stadt —, der jedes Gebäude erbt, lange nachdem das Programm vergessen ist.",
    "as method": "als Methode",
    "by the numbers": "In Zahlen",
    "click any project to expand": "Klicken Sie auf ein beliebiges Projekt, um es zu erweitern",
    "design vision, institutional work, competition strategy": "Entwurfsvision, öffentliche Bauten, Wettbewerbsstrategie",
    "for the": "für das",
    "is a paris-based architecture and urbanism studio. we design buildings, cities, and interiors that resist the ordinary and endure beyond fashion.": "ist ein Büro für Architektur und Städtebau. Wir entwerfen Gebäude, Städte und Innenräume, die dem Gewöhnlichen widerstehen und Moden überdauern.",
    "start a": "Starten Sie ein",
    "thank you!": "Danke!",
    "the studio": "Das Büro",
    "we begin every project with a conversation — no brief, no fee, no obligation. tell us about your project and we will arrange an introductory meeting within five working days.": "Jedes Projekt beginnt mit einem Gespräch — ohne Programm, ohne Honorar, ohne Verpflichtung. Erzählen Sie uns von Ihrem, wir vereinbaren binnen fünf Werktagen einen ersten Termin.",
    "we build": "Wir bauen",
    "we work on the scale of blocks, districts and towns. each project has a civic duty: repair the urban fabric rather than enclose it.": "Wir arbeiten auf der Ebene von Blöcken, Stadtteilen und Städten. Jedes Projekt hat eine bürgerliche Pflicht: das urbane Gewebe zu reparieren, anstatt es einzuschließen.",
    "we work with robust materials, structural honesty, and spatial generosity. our buildings are designed to be loved, maintained, and adapted — not demolished.": "Wir arbeiten mit robusten Materialien, ehrlicher Struktur und großzügigem Raum. Unsere Gebäude sind gebaut, um geliebt, gepflegt und umgebaut zu werden — nicht abgerissen.",
    "who we are": "Wer wir sind",
  },
  pt: {
    "buildings completed": "Edifícios entregues",
    "years practice": "Anos de exercício",
    "countries": "Países",
    "studio philosophy": "A nossa filosofia",
    "next century.": "próximo século.",
    "space": "O espaço",
    "defines": "faz",
    "culture.": "a cultura.",
    "space defines culture.": "O espaço faz a cultura.",
    "architecture's primary obligation is not to its client's ego or its architect's portfolio. it is to the public realm — the street, the neighbourhood, the city — that inherits every building long after the brief is forgotten.": "A arquitetura não deve nada ao ego do cliente nem à carteira do arquiteto. Deve ao espaço público — a rua, o bairro, a cidade — que herda cada edifício muito depois de esquecido o programa.",
    "as method": "como Método",
    "by the numbers": "Em números",
    "click any project to expand": "Clique em qualquer projeto para expandir",
    "design vision, institutional work, competition strategy": "Visão de conceção, encomenda pública, estratégia de concursos",
    "for the": "para o",
    "is a paris-based architecture and urbanism studio. we design buildings, cities, and interiors that resist the ordinary and endure beyond fashion.": "é um atelier de arquitetura e urbanismo. Concebemos edifícios, cidades e interiores que resistem ao comum e duram para além das modas.",
    "start a": "Iniciar um",
    "thank you!": "Obrigado!",
    "the studio": "O atelier",
    "we begin every project with a conversation — no brief, no fee, no obligation. tell us about your project and we will arrange an introductory meeting within five working days.": "Cada projeto começa com uma conversa — sem programa, sem honorários, sem compromisso. Fale-nos do seu: marcamos uma primeira reunião em cinco dias úteis.",
    "we build": "Construímos",
    "we work on the scale of blocks, districts and towns. each project has a civic duty: repair the urban fabric rather than enclose it.": "Trabalhamos na escala de quarteirões, bairros e cidades. Cada projeto tem um dever cívico: reparar o tecido urbano em vez de o enclausurar.",
    "we work with robust materials, structural honesty, and spatial generosity. our buildings are designed to be loved, maintained, and adapted — not demolished.": "Trabalhamos matérias robustas, uma estrutura honesta e um espaço generoso. Os nossos edifícios são feitos para serem amados, mantidos e transformados — não demolidos.",
    "who we are": "Quem somos",
  },
};
