/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "creative studio": "STUDIO CRÉATIF",
    "brands that": "des marques qui",
    "break rules.": "cassent les codes.",
    "awards awwwards": "Prix AWWWARDS",
    "brand identity · campaign": "Identité de marque · campagne",
    "digital experience · ar": "Expérience numérique · réalité augmentée",
    "editorial · motion": "Éditorial · motion design",
    "campaign · digital": "Campagne · numérique",
    "brand film · identity": "Film de marque · identité",
    "brand film": "Film de marque",
    "brand films livrés": "Films de marque livrés",
    "product reveal": "Lancement de produit",
    "installation film": "Film d'installation",
    "social campaign": "Campagne sur les réseaux",
    "generative": "Génératif",
    "editorial": "Éditorial",
    "campaign": "Campagne",
    "social": "Réseaux",
    "loop": "Boucle",
    "motion design": "Design de mouvement",
    "new projects": "Nouveaux projets",
    "see work →": "VOIR LES RÉALISATIONS →",
    "sound design": "Conception sonore",
    "start project": "DÉMARRER UN PROJET",
    "sxsw best short": "SXSW Meilleur Court Métrage",
  },
  es: {
    "creative studio": "ESTUDIO CREATIVO",
    "brands that": "marcas que",
    "break rules.": "rompen los códigos.",
    "awards awwwards": "Premios AWWWARDS",
    "brand identity · campaign": "Identidad de marca · campaña",
    "digital experience · ar": "Experiencia digital · realidad aumentada",
    "editorial · motion": "Editorial · motion design",
    "campaign · digital": "Campaña · digital",
    "brand film · identity": "Film de marca · identidad",
    "brand film": "Film de marca",
    "brand films livrés": "Films de marca entregados",
    "product reveal": "Lanzamiento de producto",
    "installation film": "Film de instalación",
    "social campaign": "Campaña en redes",
    "generative": "Generativo",
    "editorial": "Editorial",
    "campaign": "Campaña",
    "social": "Redes",
    "loop": "Bucle",
    "motion design": "Diseño de movimiento",
    "new projects": "Nuevos proyectos",
    "see work →": "VER LOS TRABAJOS →",
    "sound design": "Diseño de sonido",
    "start project": "INICIAR UN PROYECTO",
    "sxsw best short": "SXSW Mejor Cortometraje",
  },
  de: {
    "creative studio": "KREATIVSTUDIO",
    "brands that": "Marken, die",
    "break rules.": "Regeln brechen.",
    "awards awwwards": "AWWWARDS-Preise",
    "brand identity · campaign": "Markenidentität · Kampagne",
    "digital experience · ar": "Digitales Erlebnis · AR",
    "editorial · motion": "Editorial · Motion Design",
    "campaign · digital": "Kampagne · digital",
    "brand film · identity": "Markenfilm · Identität",
    "brand film": "Markenfilm",
    "brand films livrés": "Ausgelieferte Markenfilme",
    "product reveal": "Produktpremiere",
    "installation film": "Installationsfilm",
    "social campaign": "Social-Media-Kampagne",
    "generative": "Generativ",
    "editorial": "Editorial",
    "campaign": "Kampagne",
    "social": "Social",
    "loop": "Loop",
    "motion design": "Bewegungsdesign",
    "new projects": "Neue Projekte",
    "see work →": "ARBEITEN ANSEHEN →",
    "sound design": "Sounddesign",
    "start project": "PROJEKT STARTEN",
    "sxsw best short": "SXSW Bester Kurzfilm",
  },
  pt: {
    "creative studio": "ESTÚDIO CRIATIVO",
    "brands that": "marcas que",
    "break rules.": "quebram os códigos.",
    "awards awwwards": "Prémios AWWWARDS",
    "brand identity · campaign": "Identidade de marca · campanha",
    "digital experience · ar": "Experiência digital · realidade aumentada",
    "editorial · motion": "Editorial · motion design",
    "campaign · digital": "Campanha · digital",
    "brand film · identity": "Filme de marca · identidade",
    "brand film": "Filme de marca",
    "brand films livrés": "Filmes de marca entregues",
    "product reveal": "Lançamento de produto",
    "installation film": "Filme de instalação",
    "social campaign": "Campanha nas redes",
    "generative": "Generativo",
    "editorial": "Editorial",
    "campaign": "Campanha",
    "social": "Redes",
    "loop": "Ciclo",
    "motion design": "Design de movimento",
    "new projects": "Novos projetos",
    "see work →": "VER OS TRABALHOS →",
    "sound design": "Design de som",
    "start project": "INICIAR UM PROJETO",
    "sxsw best short": "SXSW Melhor Curta",
  },
};
