/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "audit and strategy direction": "Audit et direction stratégique",
    "book a private viewing": "Réserver une visite privée",
    "css design awards": "CSS Design Awards",
    "design director": "Directeur de Design",
    "discover more": "En savoir plus",
    "do you offer post-launch support?": "Offrez-vous un support après le lancement ?",
    "do you work with startups or enterprises?": "Travaillez-vous avec des startups ou des entreprises ?",
    "folio is an independent creative studio based in stockholm, focusing on art direction, digital product design, and front-end engineering.": "Folio est un studio créatif indépendant basé à Stockholm, axé sur la direction artistique, le design de produits numériques et l'ingénierie front-end.",
    "frequent questions": "Questions Fréquemment Posées",
    "how do you handle project management?": "Comment gérez-vous la gestion de projet ?",
    "long-term dedicated team": "Équipe dédiée à long terme",
    "motion design": "Design de Mouvement",
    "product design": "Design de Produit",
    "the collection": "La collection",
    "the difference between good and great is in the details. we sweat the micro-interactions.": "La différence entre le bon et le grand réside dans les détails. Nous nous concentrons sur les micro-interactions.",
    "the first idea is rarely the best. we iterate relentlessly until the solution feels inevitable.": "La première idée n'est rarement la meilleure. Nous itérons sans relâche jusqu'à ce que la solution semble inévitable.",
    "we believe in direct, honest feedback to push the work further. no egos, just excellence.": "Nous croyons en un retour direct et honnête pour faire avancer le travail. Pas d'ego, juste de l'excellence.",
    "we partner with teams at various stages, offering flexible engagement structures tailored to your immediate needs.": "Nous collaborons avec des équipes à différents stades, offrant des structures d'engagement flexibles adaptées à vos besoins immédiats.",
    "we run agile sprints with weekly stand-ups and deliverable reviews. clients have direct access to our slack channels and notion boards for total transparency.": "Nous exécutons des sprints agiles avec des réunions hebdomadaires et des revues de livrables. Les clients ont un accès direct à nos canaux Slack et à nos tableaux Notion pour une transparence totale.",
    "what is your tech stack?": "Quelle est votre pile technologique ?",
    "what is your typical project timeline?": "Quel est votre calendrier typique de projet ?",
    "yes. we offer retainer agreements for ongoing optimization, feature additions, and technical maintenance after the initial launch.": "Oui. Nous proposons des contrats de maintenance pour l'optimisation continue, l'ajout de fonctionnalités et la maintenance technique après le lancement initial.",
  },
  es: {
    "audit and strategy direction": "Auditoría y dirección estratégica",
    "book a private viewing": "Reservar una visita privada",
    "css design awards": "CSS Design Awards",
    "design director": "Director de Diseño",
    "discover more": "Descubrir más",
    "do you offer post-launch support?": "¿Ofrecen soporte post-lanzamiento?",
    "do you work with startups or enterprises?": "¿Trabajan con startups o empresas?",
    "folio is an independent creative studio based in stockholm, focusing on art direction, digital product design, and front-end engineering.": "Folio es un estudio creativo independiente con sede en Estocolmo, centrado en la dirección de arte, el diseño de productos digitales y la ingeniería front-end.",
    "frequent questions": "Preguntas Frecuentes",
    "how do you handle project management?": "¿Cómo manejan la gestión de proyectos?",
    "long-term dedicated team": "Equipo dedicado a largo plazo",
    "motion design": "Diseño de Movimiento",
    "product design": "Diseño de Producto",
    "the collection": "La colección",
    "the difference between good and great is in the details. we sweat the micro-interactions.": "La diferencia entre lo bueno y lo grandioso está en los detalles. Nos preocupamos por las microinteracciones.",
    "the first idea is rarely the best. we iterate relentlessly until the solution feels inevitable.": "La primera idea rara vez es la mejor. Iteramos incansablemente hasta que la solución se siente inevitable.",
    "we believe in direct, honest feedback to push the work further. no egos, just excellence.": "Creemos en la retroalimentación directa y honesta para llevar el trabajo más lejos. Sin egos, solo excelencia.",
    "we partner with teams at various stages, offering flexible engagement structures tailored to your immediate needs.": "Colaboramos con equipos en diversas etapas, ofreciendo estructuras de compromiso flexibles adaptadas a sus necesidades inmediatas.",
    "we run agile sprints with weekly stand-ups and deliverable reviews. clients have direct access to our slack channels and notion boards for total transparency.": "Realizamos sprints ágiles con reuniones semanales y revisiones de entregables. Los clientes tienen acceso directo a nuestros canales de Slack y tableros de Notion para una transparencia total.",
    "what is your tech stack?": "¿Cuál es su pila tecnológica?",
    "what is your typical project timeline?": "¿Cuál es su cronograma típico de proyecto?",
    "yes. we offer retainer agreements for ongoing optimization, feature additions, and technical maintenance after the initial launch.": "Sí. Ofrecemos acuerdos de retención para la optimización continua, adiciones de características y mantenimiento técnico después del lanzamiento inicial.",
  },
  de: {
    "audit and strategy direction": "Audit und strategische Ausrichtung",
    "book a private viewing": "Private Besichtigung buchen",
    "css design awards": "CSS Design Awards",
    "design director": "Design-Direktor",
    "discover more": "Mehr entdecken",
    "do you offer post-launch support?": "Bieten Sie Unterstützung nach dem Start an?",
    "do you work with startups or enterprises?": "Arbeiten Sie mit Startups oder Unternehmen?",
    "folio is an independent creative studio based in stockholm, focusing on art direction, digital product design, and front-end engineering.": "Folio ist ein unabhängiges kreatives Studio mit Sitz in Stockholm, das sich auf Art Direction, digitales Produktdesign und Front-End-Engineering konzentriert.",
    "frequent questions": "Häufige Fragen",
    "how do you handle project management?": "Wie gehen Sie mit dem Projektmanagement um?",
    "long-term dedicated team": "Langfristig engagiertes Team",
    "motion design": "Bewegungsdesign",
    "product design": "Produktdesign",
    "the collection": "Die Kollektion",
    "the difference between good and great is in the details. we sweat the micro-interactions.": "Der Unterschied zwischen gut und großartig liegt im Detail. Wir achten auf die Mikro-Interaktionen.",
    "the first idea is rarely the best. we iterate relentlessly until the solution feels inevitable.": "Die erste Idee ist selten die beste. Wir iterieren unermüdlich, bis die Lösung unvermeidlich erscheint.",
    "we believe in direct, honest feedback to push the work further. no egos, just excellence.": "Wir glauben an direktes, ehrliches Feedback, um die Arbeit weiter voranzutreiben. Keine Egos, nur Exzellenz.",
    "we partner with teams at various stages, offering flexible engagement structures tailored to your immediate needs.": "Wir arbeiten mit Teams in verschiedenen Phasen zusammen und bieten flexible Engagement-Strukturen, die auf Ihre unmittelbaren Bedürfnisse zugeschnitten sind.",
    "we run agile sprints with weekly stand-ups and deliverable reviews. clients have direct access to our slack channels and notion boards for total transparency.": "Wir führen agile Sprints mit wöchentlichen Stand-ups und Lieferüberprüfungen durch. Kunden haben direkten Zugang zu unseren Slack-Kanälen und Notion-Boards für totale Transparenz.",
    "what is your tech stack?": "Was ist Ihr Tech-Stack?",
    "what is your typical project timeline?": "Wie sieht Ihr typischer Projektzeitplan aus?",
    "yes. we offer retainer agreements for ongoing optimization, feature additions, and technical maintenance after the initial launch.": "Ja. Wir bieten Rahmenverträge für fortlaufende Optimierungen, Funktionsergänzungen und technische Wartung nach dem ursprünglichen Start an.",
  },
  pt: {
    "audit and strategy direction": "Auditoria e direção estratégica",
    "book a private viewing": "Reservar uma visita privada",
    "css design awards": "CSS Design Awards",
    "design director": "Diretor de Design",
    "discover more": "Saber mais",
    "do you offer post-launch support?": "Oferecem suporte pós-lançamento?",
    "do you work with startups or enterprises?": "Trabalham com startups ou empresas?",
    "folio is an independent creative studio based in stockholm, focusing on art direction, digital product design, and front-end engineering.": "Folio é um estúdio criativo independente com sede em Estocolmo, focado em direção de arte, design de produtos digitais e engenharia front-end.",
    "frequent questions": "Perguntas Frequentes",
    "how do you handle project management?": "Como gerenciam a gestão de projetos?",
    "long-term dedicated team": "Equipa dedicada a longo prazo",
    "motion design": "Design de Movimento",
    "product design": "Design de Produto",
    "the collection": "A coleção",
    "the difference between good and great is in the details. we sweat the micro-interactions.": "A diferença entre o bom e o grande está nos detalhes. Nós nos preocupamos com as microinterações.",
    "the first idea is rarely the best. we iterate relentlessly until the solution feels inevitable.": "A primeira ideia raramente é a melhor. Iteramos incansavelmente até que a solução pareça inevitável.",
    "we believe in direct, honest feedback to push the work further. no egos, just excellence.": "Acreditamos em feedback direto e honesto para levar o trabalho mais longe. Sem egos, apenas excelência.",
    "we partner with teams at various stages, offering flexible engagement structures tailored to your immediate needs.": "Colaboramos com equipas em várias fases, oferecendo estruturas de envolvimento flexíveis adaptadas às suas necessidades imediatas.",
    "we run agile sprints with weekly stand-ups and deliverable reviews. clients have direct access to our slack channels and notion boards for total transparency.": "Realizamos sprints ágeis com reuniões semanais e revisões de entregáveis. Os clientes têm acesso direto aos nossos canais Slack e quadros Notion para total transparência.",
    "what is your tech stack?": "Qual é a sua pilha tecnológica?",
    "what is your typical project timeline?": "Qual é o seu cronograma típico de projeto?",
    "yes. we offer retainer agreements for ongoing optimization, feature additions, and technical maintenance after the initial launch.": "Sim. Oferecemos acordos de retenção para otimização contínua, adição de funcionalidades e manutenção técnica após o lançamento inicial.",
  },
};
