/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "from idea to": "De l'idée au",
    "to one is a 12-week accelerator for pre-seed founders. we invest €500k, open our network, and help you build the company you imagined.": "est un accélérateur de douze semaines pour fondateurs en amorçage. Nous investissons 500 k€, ouvrons notre réseau et vous aidons à bâtir l'entreprise que vous aviez en tête.",
    "we built": "Nous avons créé",
    "to one because we know what founders actually need. not just money — but the right introductions, the hard feedback, and the community that keeps you going.": "parce que nous savons ce dont un fondateur a réellement besoin. Pas seulement de l'argent : les bonnes introductions, les retours francs, et la communauté qui vous tient debout.",
    "perks, events, and co-founder matching — forever.": "Avantages, événements et mise en relation entre cofondateurs — à vie.",
    "12+ years in product · 2 companies built · 1 acquisition": "12+ ans dans le produit · 2 entreprises construites · 1 acquisition",
    "120+ startups across ai, fintech, health, climate, and developer tools. here are some of the teams we&apos;re proudest to partner with.": "Plus de 120 startups dans l'IA, la fintech, la santé, le climat et les outils pour développeurs. Voici quelques-unes des équipes avec lesquelles nous sommes les plus fiers de collaborer.",
    "14+ years in gtm · 1 exit · $2b+ aum at a16z": "14+ ans en GTM · 1 sortie · 2B$+ d'AUM chez a16z",
    "15+ years in tech · 40+ portfolio companies · 3 unicorns backed": "15+ ans dans la technologie · 40+ entreprises en portefeuille · 3 licornes soutenues",
    "18+ years in engineering · 3,000+ engineers managed · $100b+ infrastructure": "18+ ans en ingénierie · 3 000+ ingénieurs gérés · 100B$+ d'infrastructure",
    "200+ vcs and angels at demo day. warm intros to the right ones.": "Plus de 200 investisseurs en capital-risque et business angels au Demo Day. Présentations chaleureuses aux bonnes personnes.",
    "a structured sprint from idea validation to series a readiness. every week has a purpose.": "Un sprint structuré de la validation de l'idée à la préparation pour la Série A. Chaque semaine a un but.",
    "access to operators who've built $100m+ companies.": "Accès à des opérateurs ayant construit des entreprises de plus de 100 millions de dollars.",
    "applications for cohort w24 are open. 20 companies selected. we read every application.": "Les candidatures pour la promotion W24 sont ouvertes. Vingt entreprises retenues. Nous lisons chaque dossier.",
    "applications for cohort w24 close november 15th, 2026. we accept ~20 companies per cohort.": "Les candidatures pour la cohorte W24 se terminent le 15 novembre 2026. Nous acceptons environ 20 entreprises par cohorte.",
    "apply for w24": "Candidater à la promotion W24",
    "back-to-back pitch meetings": "Réunions de pitch consécutives",
    "build & ship": "Construire et expédier",
    "build & validate": "Construire et valider",
    "build something": "Construire quelque chose",
    "companies built": "Entreprises construites",
    "companies we've backed": "Les entreprises que nous avons soutenues",
    "companies we&apos;ve backed": "Entreprises que nous avons soutenues",
    "customer discovery": "Découverte client",
    "customer feedback synthesis workshop": "Atelier de synthèse des retours clients",
    "demo day (500 attendees)": "Journée de démonstration (500 participants)",
    "demo day & beyond": "Journée de démonstration et au-delà",
    "design tools": "Outils de conception",
    "first customers": "Premiers clients",
    "first paying customers": "Premiers clients payants",
    "follow-on rate": "Taux de suivi",
    "growth": "Croissance",
    "growth loop identification": "Identification de la boucle de croissance",
    "growth loops": "Boucles de croissance",
    "growth loops, retention, pricing, gtm": "Boucles de croissance, rétention, tarification, GTM",
    "how much equity do you take?": "Combien de parts prenez-vous ?",
    "in-person program": "Programme en personne",
    "is the program remote or in-person?": "Le programme est-il à distance ou en personne ?",
    "launch to first 10 paying customers": "Lancement auprès des 10 premiers clients payants",
    "learn from the best.": "Apprendre auprès des meilleurs.",
    "limitation of liability": "Limitation de responsabilité",
    "more than capital.": "Plus que du capital.",
    "next demo day": "Prochain Demo Day",
    "no personal data is collected without explicit consent. this site is fully gdpr compliant.": "Aucune donnée personnelle n'est collectée sans consentement explicite. Ce site est entièrement conforme au RGPD.",
    "other": "Autre",
    "our mentors have built, scaled, and invested in companies worth billions. they&apos;ve lived through the problems you&apos;re facing — and they&apos;re here every week to help you solve them.": "Nos mentors ont construit, développé et investi dans des entreprises valant des milliards. Ils ont vécu les problèmes auxquels vous êtes confronté — et ils sont ici chaque semaine pour vous aider à les résoudre.",
    "pitch coaching with gps": "Entraînement au discours avec les associés",
    "pitch deck v1 review with all partners": "Révision du pitch deck v1 avec tous les partenaires",
    "plg, community-driven growth, bottom-up saas": "PLG, croissance axée sur la communauté, SaaS de bas en haut",
    "pricing strategy fundamentals": "Fondamentaux de la stratégie de tarification",
    "ready for the most intense 12 weeks of your life?": "Prêt pour les 12 semaines les plus intenses de votre vie ?",
    "retention and nps tracking": "Suivi de la rétention et de la recommandation",
    "revenue architecture": "Architecture des revenus",
    "revenue model architecture": "Architecture du modèle de revenus",
    "revenue model stress-testing": "Tests de résistance du modèle de revenus",
    "see portfolio": "Voir le portefeuille",
    "set up 25 customer discovery interviews": "Organiser 25 entretiens de découverte client",
    "start application": "Commencer la candidature",
    "story structure coaching session": "Session de coaching sur la structure de l'histoire",
    "submit application": "Soumettre la candidature",
    "that matters.": "qui compte.",
    "the 12-week program is primarily in-person in": "Le programme de 12 semaines se déroule principalement en personne à",
    "the program": "Le programme",
    "this site uses only essential, non-tracking cookies required for basic functionality. no analytics, advertising, or third-party tracking cookies are used without your explicit consent.": "Ce site utilise uniquement des cookies essentiels, non traçants, nécessaires à la fonctionnalité de base. Aucune analyse, publicité ou cookies de suivi tiers ne sont utilisés sans votre consentement explicite.",
    "ux review session with design partners": "Session de révision UX avec des partenaires de design",
    "want to be on this list?": "Vous voulez être sur cette liste ?",
    "want to work with these mentors?": "Vous voulez travailler avec ces mentors ?",
    "we invest pre-seed and seed — ideally you have an mvp and first users, but exceptional teams can apply earlier.": "Nous investissons au stade pré-amorçage et amorçage - idéalement, vous avez un MVP et des premiers utilisateurs, mais des équipes exceptionnelles peuvent postuler plus tôt.",
    "we take 7% equity in exchange for $500k and access to our full accelerator program.": "Nous prenons 7 % de participation en échange de 500 000 $ et d'un accès à notre programme d'accélérateur complet.",
    "website or deck link": "Lien vers le site Web ou la présentation",
    "weekly schedule": "Planning hebdomadaire",
    "what is your startup building?": "Que construit votre startup ?",
    "what stage do you invest at?": "À quel stade investissez-vous ?",
    "what you get": "Ce que vous obtenez",
    "when is the next application deadline?": "Quand est la prochaine date limite de candidature ?",
    "you have the right to access, modify, or delete your personal data at any time by contacting us at": "Vous avez le droit d'accéder, de modifier ou de supprimer vos données personnelles à tout moment en nous contactant à",
  },
  es: {
    "from idea to": "De la idea al",
    "to one is a 12-week accelerator for pre-seed founders. we invest €500k, open our network, and help you build the company you imagined.": "es una aceleradora de doce semanas para fundadores en fase pre-semilla. Invertimos 500 k€, abrimos nuestra red y le ayudamos a construir la empresa que imaginó.",
    "we built": "Creamos",
    "to one because we know what founders actually need. not just money — but the right introductions, the hard feedback, and the community that keeps you going.": "porque sabemos lo que un fundador necesita de verdad. No solo dinero: las presentaciones adecuadas, la crítica franca y la comunidad que le mantiene en pie.",
    "perks, events, and co-founder matching — forever.": "Ventajas, eventos y emparejamiento entre cofundadores — de por vida.",
    "12+ years in product · 2 companies built · 1 acquisition": "12+ años en producto · 2 empresas construidas · 1 adquisición",
    "120+ startups across ai, fintech, health, climate, and developer tools. here are some of the teams we&apos;re proudest to partner with.": "Más de 120 startups en IA, fintech, salud, clima y herramientas para desarrolladores. Aquí están algunos de los equipos con los que estamos más orgullosos de asociarnos.",
    "14+ years in gtm · 1 exit · $2b+ aum at a16z": "14+ años en GTM · 1 salida · $2B+ AUM en a16z",
    "15+ years in tech · 40+ portfolio companies · 3 unicorns backed": "15+ años en tecnología · 40+ empresas en cartera · 3 unicornios respaldados",
    "18+ years in engineering · 3,000+ engineers managed · $100b+ infrastructure": "18+ años en ingeniería · 3,000+ ingenieros gestionados · $100B+ en infraestructura",
    "200+ vcs and angels at demo day. warm intros to the right ones.": "Más de 200 VCs y ángeles en el Demo Day. Presentaciones cálidas a los adecuados.",
    "a structured sprint from idea validation to series a readiness. every week has a purpose.": "Un sprint estructurado desde la validación de la idea hasta la preparación para la Serie A. Cada semana tiene un propósito.",
    "access to operators who've built $100m+ companies.": "Acceso a operadores que han construido empresas de más de 100 millones de dólares.",
    "applications for cohort w24 are open. 20 companies selected. we read every application.": "Las candidaturas para la promoción W24 están abiertas. Veinte empresas seleccionadas. Leemos cada expediente.",
    "applications for cohort w24 close november 15th, 2026. we accept ~20 companies per cohort.": "Las solicitudes para la Cohorte W24 cierran el 15 de noviembre de 2026. Aceptamos ~20 empresas por cohorte.",
    "apply for w24": "Presentar candidatura a la promoción W24",
    "back-to-back pitch meetings": "Reuniones de pitch consecutivas",
    "build & ship": "Construir y enviar",
    "build & validate": "Construir y validar",
    "build something": "Construir algo",
    "companies built": "Empresas construidas",
    "companies we've backed": "Las empresas que hemos apoyado",
    "companies we&apos;ve backed": "Empresas que hemos respaldado",
    "customer discovery": "Descubrimiento de clientes",
    "customer feedback synthesis workshop": "Taller de síntesis de comentarios de clientes",
    "demo day (500 attendees)": "Día de demostración (500 asistentes)",
    "demo day & beyond": "Día de demostración y más allá",
    "design tools": "Herramientas de diseño",
    "first customers": "Primeros clientes",
    "first paying customers": "Primeros clientes que pagan",
    "follow-on rate": "Tasa de seguimiento",
    "growth": "Crecimiento",
    "growth loop identification": "Identificación del bucle de crecimiento",
    "growth loops": "Bucles de crecimiento",
    "growth loops, retention, pricing, gtm": "Bucles de crecimiento, retención, precios, GTM",
    "how much equity do you take?": "¿Cuánta participación toma?",
    "in-person program": "Programa en persona",
    "is the program remote or in-person?": "¿El programa es remoto o presencial?",
    "launch to first 10 paying customers": "Lanzamiento a los primeros 10 clientes que pagan",
    "learn from the best.": "Aprender de los mejores.",
    "limitation of liability": "Limitación de responsabilidad",
    "more than capital.": "Más que capital.",
    "next demo day": "Próximo Día de Demostración",
    "no personal data is collected without explicit consent. this site is fully gdpr compliant.": "No se recopilan datos personales sin consentimiento explícito. Este sitio es completamente compatible con el RGPD.",
    "other": "Otro",
    "our mentors have built, scaled, and invested in companies worth billions. they&apos;ve lived through the problems you&apos;re facing — and they&apos;re here every week to help you solve them.": "Nuestros mentores han construido, escalado e invertido en empresas valoradas en miles de millones. Han vivido los problemas que enfrentas — y están aquí cada semana para ayudarte a resolverlos.",
    "pitch coaching with gps": "Entrenamiento del discurso con los socios",
    "pitch deck v1 review with all partners": "Revisión del pitch deck v1 con todos los socios",
    "plg, community-driven growth, bottom-up saas": "PLG, crecimiento impulsado por la comunidad, SaaS de abajo hacia arriba",
    "pricing strategy fundamentals": "Fundamentos de la estrategia de precios",
    "ready for the most intense 12 weeks of your life?": "¿Listo para las 12 semanas más intensas de tu vida?",
    "retention and nps tracking": "Seguimiento de la retención y la recomendación",
    "revenue architecture": "Arquitectura de ingresos",
    "revenue model architecture": "Arquitectura del modelo de ingresos",
    "revenue model stress-testing": "Pruebas de resistencia del modelo de ingresos",
    "see portfolio": "Ver la cartera",
    "set up 25 customer discovery interviews": "Configurar 25 entrevistas de descubrimiento de clientes",
    "start application": "Empezar la candidatura",
    "story structure coaching session": "Sesión de coaching sobre la estructura de la historia",
    "submit application": "Enviar solicitud",
    "that matters.": "que importe.",
    "the 12-week program is primarily in-person in": "El programa de 12 semanas es principalmente presencial en",
    "the program": "El programa",
    "this site uses only essential, non-tracking cookies required for basic functionality. no analytics, advertising, or third-party tracking cookies are used without your explicit consent.": "Este sitio utiliza solo cookies esenciales, no rastreadores, requeridas para la funcionalidad básica. No se utilizan cookies de análisis, publicidad o seguimiento de terceros sin su consentimiento explícito.",
    "ux review session with design partners": "Sesión de revisión de UX con socios de diseño",
    "want to be on this list?": "¿Quieres estar en esta lista?",
    "want to work with these mentors?": "¿Quieres trabajar con estos mentores?",
    "we invest pre-seed and seed — ideally you have an mvp and first users, but exceptional teams can apply earlier.": "Invertimos en pre-semilla y semilla; idealmente, tiene un MVP y primeros usuarios, pero equipos excepcionales pueden postularse antes.",
    "we take 7% equity in exchange for $500k and access to our full accelerator program.": "Tomamos un 7% de participación a cambio de 500K $ y acceso a nuestro programa completo de aceleración.",
    "website or deck link": "Enlace al sitio web o a la presentación",
    "weekly schedule": "Horario semanal",
    "what is your startup building?": "¿Qué está construyendo su startup?",
    "what stage do you invest at?": "¿En qué etapa invierte?",
    "what you get": "Lo que obtiene",
    "when is the next application deadline?": "¿Cuándo es la próxima fecha límite de solicitud?",
    "you have the right to access, modify, or delete your personal data at any time by contacting us at": "Tiene derecho a acceder, modificar o eliminar sus datos personales en cualquier momento contactándonos en",
  },
  de: {
    "from idea to": "Von der Idee zum",
    "to one is a 12-week accelerator for pre-seed founders. we invest €500k, open our network, and help you build the company you imagined.": "ist ein zwölfwöchiger Accelerator für Gründer in der Pre-Seed-Phase. Wir investieren 500 Tsd. €, öffnen unser Netzwerk und helfen, das Unternehmen zu bauen, das Sie im Kopf hatten.",
    "we built": "Wir haben",
    "to one because we know what founders actually need. not just money — but the right introductions, the hard feedback, and the community that keeps you going.": "weil wir wissen, was Gründer wirklich brauchen. Nicht nur Geld: die richtigen Kontakte, ehrliches Feedback und die Gemeinschaft, die einen trägt.",
    "perks, events, and co-founder matching — forever.": "Vorteile, Events und Co-Founder-Matching — auf Lebenszeit.",
    "12+ years in product · 2 companies built · 1 acquisition": "12+ Jahre im Produkt · 2 Unternehmen gegründet · 1 Akquisition",
    "120+ startups across ai, fintech, health, climate, and developer tools. here are some of the teams we&apos;re proudest to partner with.": "Über 120 Startups in den Bereichen KI, Fintech, Gesundheit, Klima und Entwickler-Tools. Hier sind einige der Teams, mit denen wir am stolzesten zusammenarbeiten.",
    "14+ years in gtm · 1 exit · $2b+ aum at a16z": "14+ Jahre in GTM · 1 Exit · 2B$+ AUM bei a16z",
    "15+ years in tech · 40+ portfolio companies · 3 unicorns backed": "15+ Jahre in der Technik · 40+ Portfoliounternehmen · 3 unterstützte Einhörner",
    "18+ years in engineering · 3,000+ engineers managed · $100b+ infrastructure": "18+ Jahre in der Technik · 3.000+ verwaltete Ingenieure · 100B$+ Infrastruktur",
    "200+ vcs and angels at demo day. warm intros to the right ones.": "Über 200 VCs und Engel beim Demo Day. Warme Einführungen zu den richtigen.",
    "a structured sprint from idea validation to series a readiness. every week has a purpose.": "Ein strukturierter Sprint von der Ideenvalidierung bis zur Bereitschaft für die Series A. Jede Woche hat einen Zweck.",
    "access to operators who've built $100m+ companies.": "Zugang zu Betreibern, die Unternehmen mit über 100 Millionen Dollar aufgebaut haben.",
    "applications for cohort w24 are open. 20 companies selected. we read every application.": "Die Bewerbungen für den Jahrgang W24 sind offen. Zwanzig Unternehmen werden ausgewählt. Wir lesen jede Bewerbung.",
    "applications for cohort w24 close november 15th, 2026. we accept ~20 companies per cohort.": "Bewerbungen für die Kohorte W24 schließen am 15. November 2026. Wir akzeptieren ~20 Unternehmen pro Kohorte.",
    "apply for w24": "Für den Jahrgang W24 bewerben",
    "back-to-back pitch meetings": "Back-to-back-Pitch-Meetings",
    "build & ship": "Bauen und versenden",
    "build & validate": "Bauen und validieren",
    "build something": "Etwas bauen",
    "companies built": "Unternehmen aufgebaut",
    "companies we've backed": "Unternehmen, die wir unterstützt haben",
    "companies we&apos;ve backed": "Unternehmen, die wir unterstützt haben",
    "customer discovery": "Kundenentdeckung",
    "customer feedback synthesis workshop": "Workshop zur Synthese von Kundenfeedback",
    "demo day (500 attendees)": "Demo-Tag (500 Teilnehmer)",
    "demo day & beyond": "Demo-Tag und darüber hinaus",
    "design tools": "Design-Tools",
    "first customers": "Erste Kunden",
    "first paying customers": "Erste zahlende Kunden",
    "follow-on rate": "Follow-on-Rate",
    "growth": "Wachstum",
    "growth loop identification": "Identifizierung der Wachstumschleife",
    "growth loops": "Wachstumsloops",
    "growth loops, retention, pricing, gtm": "Wachstumsloops, Retention, Preisgestaltung, GTM",
    "how much equity do you take?": "Wie viel Eigenkapital nehmen Sie?",
    "in-person program": "Präsenzprogramm",
    "is the program remote or in-person?": "Ist das Programm remote oder persönlich?",
    "launch to first 10 paying customers": "Start bei den ersten 10 zahlenden Kunden",
    "learn from the best.": "Von den Besten lernen.",
    "limitation of liability": "Haftungsbeschränkung",
    "more than capital.": "Mehr als Kapital.",
    "next demo day": "Nächster Demo Day",
    "no personal data is collected without explicit consent. this site is fully gdpr compliant.": "Es werden keine personenbezogenen Daten ohne ausdrückliche Zustimmung erhoben. Diese Seite ist vollständig DSGVO-konform.",
    "other": "Andere",
    "our mentors have built, scaled, and invested in companies worth billions. they&apos;ve lived through the problems you&apos;re facing — and they&apos;re here every week to help you solve them.": "Unsere Mentoren haben Unternehmen im Wert von Milliarden aufgebaut, skaliert und investiert. Sie haben die Probleme erlebt, mit denen Sie konfrontiert sind — und sie sind jede Woche hier, um Ihnen zu helfen, sie zu lösen.",
    "pitch coaching with gps": "Pitch-Training mit den Partnern",
    "pitch deck v1 review with all partners": "Pitch-Deck v1-Überprüfung mit allen Partnern",
    "plg, community-driven growth, bottom-up saas": "PLG, gemeinschaftsgetriebenes Wachstum, Bottom-up-SaaS",
    "pricing strategy fundamentals": "Grundlagen der Preisstrategie",
    "ready for the most intense 12 weeks of your life?": "Bereit für die intensivsten 12 Wochen deines Lebens?",
    "retention and nps tracking": "Verfolgung von Bindung und Weiterempfehlung",
    "revenue architecture": "Einnahmenarchitektur",
    "revenue model architecture": "Architektur des Einnahmenmodells",
    "revenue model stress-testing": "Stresstest des Einnahmenmodells",
    "see portfolio": "Portfolio ansehen",
    "set up 25 customer discovery interviews": "25 Kundenentdeckungsinterviews einrichten",
    "start application": "Bewerbung beginnen",
    "story structure coaching session": "Coaching-Sitzung zur Struktur der Geschichte",
    "submit application": "Bewerbung einreichen",
    "that matters.": "das zählt.",
    "the 12-week program is primarily in-person in": "Das 12-wöchige Programm findet hauptsächlich persönlich in statt",
    "the program": "Das Programm",
    "this site uses only essential, non-tracking cookies required for basic functionality. no analytics, advertising, or third-party tracking cookies are used without your explicit consent.": "Diese Website verwendet nur essentielle, nicht verfolgende Cookies, die für die grundlegende Funktionalität erforderlich sind. Keine Analyse-, Werbe- oder Drittanbieter-Tracking-Cookies werden ohne Ihre ausdrückliche Zustimmung verwendet.",
    "ux review session with design partners": "UX-Überprüfungssitzung mit Designpartnern",
    "want to be on this list?": "Möchten Sie auf dieser Liste stehen?",
    "want to work with these mentors?": "Möchten Sie mit diesen Mentoren arbeiten?",
    "we invest pre-seed and seed — ideally you have an mvp and first users, but exceptional teams can apply earlier.": "Wir investieren in Pre-Seed und Seed - idealerweise haben Sie ein MVP und erste Nutzer, aber außergewöhnliche Teams können sich früher bewerben.",
    "we take 7% equity in exchange for $500k and access to our full accelerator program.": "Wir nehmen 7 % Eigenkapital im Austausch für 500.000 $ und Zugang zu unserem vollständigen Accelerator-Programm.",
    "website or deck link": "Website- oder Deck-Link",
    "weekly schedule": "Wochenplan",
    "what is your startup building?": "Was bauten Sie mit Ihrem Startup?",
    "what stage do you invest at?": "In welcher Phase investieren Sie?",
    "what you get": "Was Sie bekommen",
    "when is the next application deadline?": "Wann ist die nächste Bewerbungsfrist?",
    "you have the right to access, modify, or delete your personal data at any time by contacting us at": "Sie haben das Recht, Ihre personenbezogenen Daten jederzeit zuzugreifen, zu ändern oder zu löschen, indem Sie uns unter kontaktieren",
  },
  pt: {
    "from idea to": "Da ideia ao",
    "to one is a 12-week accelerator for pre-seed founders. we invest €500k, open our network, and help you build the company you imagined.": "é uma aceleradora de doze semanas para fundadores em pré-semente. Investimos 500 mil €, abrimos a nossa rede e ajudamos a construir a empresa que imaginou.",
    "we built": "Criámos",
    "to one because we know what founders actually need. not just money — but the right introductions, the hard feedback, and the community that keeps you going.": "porque sabemos do que um fundador precisa mesmo. Não só dinheiro: as apresentações certas, o retorno franco e a comunidade que nos mantém de pé.",
    "perks, events, and co-founder matching — forever.": "Vantagens, eventos e emparelhamento entre cofundadores — para sempre.",
    "12+ years in product · 2 companies built · 1 acquisition": "12+ anos em produto · 2 empresas construídas · 1 aquisição",
    "120+ startups across ai, fintech, health, climate, and developer tools. here are some of the teams we&apos;re proudest to partner with.": "Mais de 120 startups em IA, fintech, saúde, clima e ferramentas para desenvolvedores. Aqui estão algumas das equipas com as quais temos mais orgulho de colaborar.",
    "14+ years in gtm · 1 exit · $2b+ aum at a16z": "14+ anos em GTM · 1 saída · $2B+ AUM na a16z",
    "15+ years in tech · 40+ portfolio companies · 3 unicorns backed": "15+ anos em tecnologia · 40+ empresas no portfólio · 3 unicórnios apoiados",
    "18+ years in engineering · 3,000+ engineers managed · $100b+ infrastructure": "18+ anos em engenharia · 3.000+ engenheiros geridos · $100B+ em infraestrutura",
    "200+ vcs and angels at demo day. warm intros to the right ones.": "Mais de 200 VCs e investidores anjo no Demo Day. Apresentações calorosas aos certos.",
    "a structured sprint from idea validation to series a readiness. every week has a purpose.": "Um sprint estruturado da validação da ideia até a prontidão para a Série A. Cada semana tem um propósito.",
    "access to operators who've built $100m+ companies.": "Acesso a operadores que construíram empresas de mais de 100 milhões de dólares.",
    "applications for cohort w24 are open. 20 companies selected. we read every application.": "As candidaturas para a turma W24 estão abertas. Vinte empresas selecionadas. Lemos cada processo.",
    "applications for cohort w24 close november 15th, 2026. we accept ~20 companies per cohort.": "As candidaturas para a Coorte W24 encerram-se a 15 de novembro de 2026. Aceitamos ~20 empresas por coorte.",
    "apply for w24": "Candidatar-se à turma W24",
    "back-to-back pitch meetings": "Reuniões de pitch consecutivas",
    "build & ship": "Construir e enviar",
    "build & validate": "Construir e validar",
    "build something": "Construir algo",
    "companies built": "Empresas construídas",
    "companies we've backed": "As empresas que apoiámos",
    "companies we&apos;ve backed": "Empresas que apoiámos",
    "customer discovery": "Descoberta de clientes",
    "customer feedback synthesis workshop": "Oficina de síntese de feedback de clientes",
    "demo day (500 attendees)": "Dia de demonstração (500 participantes)",
    "demo day & beyond": "Dia de demonstração e além",
    "design tools": "Ferramentas de design",
    "first customers": "Primeiros clientes",
    "first paying customers": "Primeiros clientes pagantes",
    "follow-on rate": "Taxa de seguimento",
    "growth": "Crescimento",
    "growth loop identification": "Identificação do ciclo de crescimento",
    "growth loops": "Ciclos de crescimento",
    "growth loops, retention, pricing, gtm": "Ciclos de crescimento, retenção, preços, GTM",
    "how much equity do you take?": "Quanto capital próprio você toma?",
    "in-person program": "Programa presencial",
    "is the program remote or in-person?": "O programa é remoto ou presencial?",
    "launch to first 10 paying customers": "Lançamento para os primeiros 10 clientes pagantes",
    "learn from the best.": "Aprender com os melhores.",
    "limitation of liability": "Limitação de responsabilidade",
    "more than capital.": "Mais do que capital.",
    "next demo day": "Próximo Dia de Demonstração",
    "no personal data is collected without explicit consent. this site is fully gdpr compliant.": "Nenhum dado pessoal é coletado sem consentimento explícito. Este site está totalmente em conformidade com o RGPD.",
    "other": "Outro",
    "our mentors have built, scaled, and invested in companies worth billions. they&apos;ve lived through the problems you&apos;re facing — and they&apos;re here every week to help you solve them.": "Os nossos mentores construíram, escalaram e investiram em empresas no valor de bilhões. Eles viveram os problemas que você está enfrentando — e estão aqui todas as semanas para ajudá-lo a resolvê-los.",
    "pitch coaching with gps": "Treino do discurso com os sócios",
    "pitch deck v1 review with all partners": "Revisão do pitch deck v1 com todos os parceiros",
    "plg, community-driven growth, bottom-up saas": "PLG, crescimento orientado pela comunidade, SaaS de baixo para cima",
    "pricing strategy fundamentals": "Fundamentos da estratégia de preços",
    "ready for the most intense 12 weeks of your life?": "Pronto para as 12 semanas mais intensas da sua vida?",
    "retention and nps tracking": "Acompanhamento da retenção e da recomendação",
    "revenue architecture": "Arquitetura de receitas",
    "revenue model architecture": "Arquitetura do modelo de receita",
    "revenue model stress-testing": "Teste de resistência do modelo de receita",
    "see portfolio": "Ver a carteira",
    "set up 25 customer discovery interviews": "Configurar 25 entrevistas de descoberta de clientes",
    "start application": "Começar a candidatura",
    "story structure coaching session": "Sessão de coaching sobre a estrutura da história",
    "submit application": "Enviar candidatura",
    "that matters.": "que conte.",
    "the 12-week program is primarily in-person in": "O programa de 12 semanas é principalmente presencial em",
    "the program": "O programa",
    "this site uses only essential, non-tracking cookies required for basic functionality. no analytics, advertising, or third-party tracking cookies are used without your explicit consent.": "Este site utiliza apenas cookies essenciais, não rastreadores, necessários para a funcionalidade básica. Nenhum cookie de análise, publicidade ou rastreamento de terceiros é utilizado sem o seu consentimento explícito.",
    "ux review session with design partners": "Sessão de revisão de UX com parceiros de design",
    "want to be on this list?": "Quer estar nesta lista?",
    "want to work with these mentors?": "Quer trabalhar com estes mentores?",
    "we invest pre-seed and seed — ideally you have an mvp and first users, but exceptional teams can apply earlier.": "Investimos em pré-seed e seed - idealmente você tem um MVP e primeiros usuários, mas equipes excepcionais podem se inscrever mais cedo.",
    "we take 7% equity in exchange for $500k and access to our full accelerator program.": "Tomamos 7% de capital próprio em troca de 500K € e acesso ao nosso programa completo de aceleração.",
    "website or deck link": "Link para o site ou apresentação",
    "weekly schedule": "Horário semanal",
    "what is your startup building?": "O que está a construir a sua startup?",
    "what stage do you invest at?": "Em que fase investe?",
    "what you get": "O que recebe",
    "when is the next application deadline?": "Quando é o próximo prazo de candidatura?",
    "you have the right to access, modify, or delete your personal data at any time by contacting us at": "Tem o direito de aceder, modificar ou eliminar os seus dados pessoais a qualquer momento, entrando em contacto connosco em",
  },
};
