/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    ". limited runs, built to outlast the hype.": ". Séries limitées, faites pour durer plus longtemps que la mode.",
    "4.9 / 5 from": "4,9 / 5 sur",
    "built in the workshop, not the boardroom": "Conçu à l'atelier, pas en salle de réunion",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "Les sorties partent en quelques minutes. Les membres ont vingt-quatre heures d'avance, des coloris exclusifs et la livraison express offerte.",
    "free express over €150": "Express offert dès 150 €",
    "free shipping over €150": "LIVRAISON OFFERTE DÈS 150 €",
    "get the next drop first": "Recevez la prochaine sortie en avant-première",
    "have a question about our drops, sizing, or shipping? drop us a line.": "Une question sur nos sorties, les tailles ou la livraison ? Écrivez-nous.",
    "into every pair": "dans chaque paire",
    "join the forge": "Rejoindre l'atelier",
    "materials that age with you": "Des matières qui vieillissent avec vous",
    "new drop": "Nouveauté",
    "new drops": "Nouveautés",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Semelle intermédiaire à l'azote, réglée pour restituer 14 % d'énergie en plus.",
    "on the street": "Dans la rue",
    "shop the drop": "Voir la collection",
    "the anatomy": "L'anatomie",
    "the craft": "Le savoir-faire",
    "the forge": "L'atelier",
    "this season's": "De la saison",
    "to the stitch": "jusqu'à la couture",
    "view all 24 styles": "Voir les 24 modèles",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Disponible",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Nous choisissons des daims pleine fleur et des mailles recyclées qui prennent du caractère. Au bout d'un an, votre paire ne ressemblera à aucune autre — c'est le but.",
    "your cart is empty": "Votre panier est vide",
  },
  es: {
    ". limited runs, built to outlast the hype.": ". Series limitadas, hechas para durar más que la moda.",
    "4.9 / 5 from": "4,9 / 5 de",
    "built in the workshop, not the boardroom": "Hecho en el taller, no en la sala de juntas",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "Las colecciones se agotan en minutos. Los socios disponen de veinticuatro horas de ventaja, colores exclusivos y envío exprés gratuito.",
    "free express over €150": "Exprés gratis desde 150 €",
    "free shipping over €150": "ENVÍO GRATIS DESDE 150 €",
    "get the next drop first": "Reciba la próxima colección en primicia",
    "have a question about our drops, sizing, or shipping? drop us a line.": "¿Alguna duda sobre las colecciones, las tallas o el envío? Escríbanos.",
    "into every pair": "en cada par",
    "join the forge": "Únase al taller",
    "materials that age with you": "Materiales que envejecen con usted",
    "new drop": "Novedad",
    "new drops": "Novedades",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Entresuela con nitrógeno, ajustada para devolver un 14 % más de energía.",
    "on the street": "En la calle",
    "shop the drop": "Ver la colección",
    "the anatomy": "La anatomía",
    "the craft": "El oficio",
    "the forge": "El taller",
    "this season's": "De la temporada",
    "to the stitch": "hasta la costura",
    "view all 24 styles": "Ver los 24 modelos",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Ya disponible",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Elegimos ante de flor entera y tejidos reciclados que ganan carácter. Al cabo de un año, su par no se parecerá a ningún otro: esa es la idea.",
    "your cart is empty": "Tu carrito está vacío",
  },
  de: {
    ". limited runs, built to outlast the hype.": ". Limitierte Serien, gebaut, um länger zu halten als der Hype.",
    "4.9 / 5 from": "4,9 / 5 aus",
    "built in the workshop, not the boardroom": "In der Werkstatt entstanden, nicht im Sitzungssaal",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "Kollektionen sind in Minuten vergriffen. Mitglieder erhalten vierundzwanzig Stunden Vorsprung, exklusive Farben und kostenlosen Expressversand.",
    "free express over €150": "Expressversand gratis ab 150 €",
    "free shipping over €150": "VERSANDKOSTENFREI AB 150 €",
    "get the next drop first": "Erhalten Sie die nächste Kollektion zuerst",
    "have a question about our drops, sizing, or shipping? drop us a line.": "Fragen zu Kollektionen, Größen oder Versand? Schreiben Sie uns.",
    "into every pair": "in jedes Paar",
    "join the forge": "Der Werkstatt beitreten",
    "materials that age with you": "Materialien, die mit Ihnen altern",
    "new drop": "Neuheit",
    "new drops": "Neuheiten",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Stickstoffgefüllte Zwischensohle, abgestimmt auf 14 % mehr Energierückgabe.",
    "on the street": "Auf der Straße",
    "shop the drop": "Zur Kollektion",
    "the anatomy": "Die Anatomie",
    "the craft": "Das Handwerk",
    "the forge": "Die Werkstatt",
    "this season's": "Der Saison",
    "to the stitch": "bis zur Naht",
    "view all 24 styles": "Alle 24 Modelle ansehen",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Jetzt erhältlich",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Wir wählen Veloursleder aus vollem Narben und recycelte Strickstoffe, die Charakter entwickeln. Nach einem Jahr gleicht Ihr Paar keinem anderen — genau darum geht es.",
    "your cart is empty": "Ihr Warenkorb ist leer",
  },
  pt: {
    ". limited runs, built to outlast the hype.": ". Séries limitadas, feitas para durar mais do que a moda.",
    "4.9 / 5 from": "4,9 / 5 de",
    "built in the workshop, not the boardroom": "Feito na oficina, não na sala de reuniões",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "As coleções esgotam em minutos. Os membros têm vinte e quatro horas de avanço, cores exclusivas e envio expresso gratuito.",
    "free express over €150": "Expresso grátis a partir de 150 €",
    "free shipping over €150": "PORTES GRÁTIS A PARTIR DE 150 €",
    "get the next drop first": "Receba a próxima coleção em primeira mão",
    "have a question about our drops, sizing, or shipping? drop us a line.": "Alguma dúvida sobre coleções, tamanhos ou envio? Escreva-nos.",
    "into every pair": "em cada par",
    "join the forge": "Junte-se à oficina",
    "materials that age with you": "Materiais que envelhecem consigo",
    "new drop": "Novidade",
    "new drops": "Novidades",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Entressola com azoto, afinada para devolver mais 14 % de energia.",
    "on the street": "Na rua",
    "shop the drop": "Ver a coleção",
    "the anatomy": "A anatomia",
    "the craft": "O ofício",
    "the forge": "A oficina",
    "this season's": "Da estação",
    "to the stitch": "até à costura",
    "view all 24 styles": "Ver os 24 modelos",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Já disponível",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Escolhemos camurça de flor inteira e malhas recicladas que ganham carácter. Ao fim de um ano, o seu par não se parecerá com nenhum outro — é essa a intenção.",
    "your cart is empty": "O seu carrinho está vazio",
  },
};
