/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "streets": "RUE",
    "performance-grade sneakers, built like industrial machinery and finished like couture. limited runs. forged to outlast.": "Des baskets de niveau performance, construites comme une machine industrielle et finies comme une pièce de couture. Séries limitées. Faites pour durer.",
    "airforge started in a lyon garage with a heat press and an obsession. every silhouette is prototyped by hand, stress-tested on real streets, and refined until it earns the name.": "Tout a commencé dans un garage lyonnais, avec une presse à chaud et une obsession. Chaque silhouette est prototypée à la main, éprouvée dans la rue, et retravaillée jusqu'à mériter son nom.",
    "a pressurized nitrogen core wrapped in supercritical foam. lighter than the air it traps, springier than anything we have built.": "Un noyau d'azote sous pression enveloppé de mousse supercritique. Plus léger que l'air qu'il retient, plus vif que tout ce que nous avons fait jusqu'ici.",
    "tanned in tuscany, cut by hand. each upper develops its own patina, so no two pairs age the same way.": "Tannée en Toscane, coupée à la main. Chaque tige prend sa patine : deux paires ne vieillissent jamais pareil.",
    "a forged carbon-rubber outsole with directional lugs engineered for wet concrete, gravel, and everything between.": "Une semelle carbone-caoutchouc forgée, à crampons directionnels, pensée pour le béton mouillé, le gravier et tout ce qu'il y a entre les deux.",
    "a breathable, moisture-wicking ankle collar spun from 92% recycled ocean-bound plastics.": "Un col de cheville respirant, qui évacue l'humidité, filé à partir de 92 % de plastiques récupérés avant qu'ils n'atteignent l'océan.",
    "these replaced three pairs in my rotation. the sole is unreal — i forget i am wearing them on a 10k.": "Elles ont remplacé trois paires dans ma rotation. La semelle est irréelle — j'oublie que je les porte sur dix kilomètres.",
    "the suede is genuinely premium. people stop me on the street. worth every euro and then some.": "Le daim est vraiment haut de gamme. On m'arrête dans la rue. Elles valent chaque euro, et plus encore.",
    "copped the vol. 02 drop in seconds. build quality crushes brands twice the price. shipping was fast too.": "J'ai eu la série Vol. 02 en quelques secondes. La fabrication écrase des marques deux fois plus chères. Livraison rapide en prime.",
    "the streets": "LA RUE",
    "the": "la",
    ". limited runs, built to outlast the hype.": ". Séries limitées, faites pour durer plus longtemps que la mode.",
    "← back to cart": "← Retour au panier",
    "30-day forge guarantee": "Garantie forge de 30 jours",
    "4.9 / 5 from": "4,9 / 5 sur",
    "add to cart": "Ajouter au panier",
    "built in the workshop, not the boardroom": "Conçu à l'atelier, pas en salle de réunion",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "Les sorties partent en quelques minutes. Les membres ont vingt-quatre heures d'avance, des coloris exclusifs et la livraison express offerte.",
    "engineered down": "Conçu pour",
    "forged for": "Forgé pour",
    "free express over €150": "Express offert dès 150 €",
    "free shipping over €150": "LIVRAISON OFFERTE DÈS 150 €",
    "get the next drop first": "Recevez la prochaine sortie en avant-première",
    "have a question about our drops, sizing, or shipping? drop us a line.": "Une question sur nos sorties, les tailles ou la livraison ? Écrivez-nous.",
    "into every pair": "dans chaque paire",
    "join the forge": "Rejoindre l'atelier",
    "materials that age with you": "Des matières qui vieillissent avec vous",
    "new drop": "Nouveauté",
    "new drops": "Nouveautés",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Semelle intermédiaire à l'azote, réglée pour restituer 14 % d'énergie en plus.",
    "notify me": "Prévenez-moi",
    "on the street": "Dans la rue",
    "order confirmed": "Commande confirmée",
    "shop the drop": "Voir la collection",
    "the anatomy": "L'anatomie",
    "the craft": "Le savoir-faire",
    "the forge": "L'atelier",
    "this season's": "De la saison",
    "this season's": "Cette saison's",
    "to the stitch": "jusqu'à la couture",
    "view all 24 styles": "Voir les 24 modèles",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Disponible",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Nous choisissons des daims pleine fleur et des mailles recyclées qui prennent du caractère. Au bout d'un an, votre paire ne ressemblera à aucune autre — c'est le but.",
    "you're in": "Vous êtes dans",
    "your cart is empty": "Votre panier est vide",
  },
  es: {
    "streets": "CALLE",
    "performance-grade sneakers, built like industrial machinery and finished like couture. limited runs. forged to outlast.": "Zapatillas de nivel rendimiento, construidas como una máquina industrial y acabadas como una pieza de alta costura. Series limitadas. Hechas para durar.",
    "airforge started in a lyon garage with a heat press and an obsession. every silhouette is prototyped by hand, stress-tested on real streets, and refined until it earns the name.": "Todo empezó en un garaje de Lyon, con una prensa térmica y una obsesión. Cada silueta se prototipa a mano, se prueba en la calle y se retrabaja hasta merecer su nombre.",
    "a pressurized nitrogen core wrapped in supercritical foam. lighter than the air it traps, springier than anything we have built.": "Un núcleo de nitrógeno a presión envuelto en espuma supercrítica. Más ligero que el aire que retiene, más vivo que todo lo que hemos hecho.",
    "tanned in tuscany, cut by hand. each upper develops its own patina, so no two pairs age the same way.": "Curtida en Toscana, cortada a mano. Cada corte toma su pátina: dos pares nunca envejecen igual.",
    "a forged carbon-rubber outsole with directional lugs engineered for wet concrete, gravel, and everything between.": "Una suela de carbono y caucho forjada, con tacos direccionales, pensada para el hormigón mojado, la grava y todo lo que hay en medio.",
    "a breathable, moisture-wicking ankle collar spun from 92% recycled ocean-bound plastics.": "Un cuello de tobillo transpirable, que evacua la humedad, hilado con un 92 % de plásticos recuperados antes de llegar al océano.",
    "these replaced three pairs in my rotation. the sole is unreal — i forget i am wearing them on a 10k.": "Han sustituido tres pares en mi rotación. La suela es irreal: olvido que las llevo en diez kilómetros.",
    "the suede is genuinely premium. people stop me on the street. worth every euro and then some.": "El ante es realmente de gama alta. Me paran por la calle. Valen cada euro, y más.",
    "copped the vol. 02 drop in seconds. build quality crushes brands twice the price. shipping was fast too.": "Conseguí la serie Vol. 02 en segundos. La fabricación aplasta a marcas del doble de precio. Y el envío fue rápido.",
    "the streets": "LA CALLE",
    "the": "la",
    ". limited runs, built to outlast the hype.": ". Series limitadas, hechas para durar más que la moda.",
    "← back to cart": "← Volver al carrito",
    "30-day forge guarantee": "Garantía de forja de 30 días",
    "4.9 / 5 from": "4,9 / 5 de",
    "add to cart": "Añadir al carrito",
    "built in the workshop, not the boardroom": "Hecho en el taller, no en la sala de juntas",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "Las colecciones se agotan en minutos. Los socios disponen de veinticuatro horas de ventaja, colores exclusivos y envío exprés gratuito.",
    "engineered down": "Diseñado para",
    "forged for": "Forjado para",
    "free express over €150": "Exprés gratis desde 150 €",
    "free shipping over €150": "ENVÍO GRATIS DESDE 150 €",
    "get the next drop first": "Reciba la próxima colección en primicia",
    "have a question about our drops, sizing, or shipping? drop us a line.": "¿Alguna duda sobre las colecciones, las tallas o el envío? Escríbanos.",
    "into every pair": "en cada par",
    "join the forge": "Únase al taller",
    "materials that age with you": "Materiales que envejecen con usted",
    "new drop": "Novedad",
    "new drops": "Novedades",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Entresuela con nitrógeno, ajustada para devolver un 14 % más de energía.",
    "notify me": "Notifícame",
    "on the street": "En la calle",
    "order confirmed": "Pedido confirmado",
    "shop the drop": "Ver la colección",
    "the anatomy": "La anatomía",
    "the craft": "El oficio",
    "the forge": "El taller",
    "this season's": "De la temporada",
    "this season's": "De esta temporada",
    "to the stitch": "hasta la costura",
    "view all 24 styles": "Ver los 24 modelos",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Ya disponible",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Elegimos ante de flor entera y tejidos reciclados que ganan carácter. Al cabo de un año, su par no se parecerá a ningún otro: esa es la idea.",
    "you're in": "Estás en",
    "your cart is empty": "Tu carrito está vacío",
  },
  de: {
    "streets": "STRASSE",
    "performance-grade sneakers, built like industrial machinery and finished like couture. limited runs. forged to outlast.": "Sneaker auf Performance-Niveau, gebaut wie eine Industriemaschine und verarbeitet wie ein Couture-Stück. Limitierte Serien. Gemacht, um zu halten.",
    "airforge started in a lyon garage with a heat press and an obsession. every silhouette is prototyped by hand, stress-tested on real streets, and refined until it earns the name.": "Alles begann in einer Garage in Lyon, mit einer Heißpresse und einer Obsession. Jede Silhouette wird von Hand prototypisiert, auf der Straße getestet und überarbeitet, bis sie ihren Namen verdient.",
    "a pressurized nitrogen core wrapped in supercritical foam. lighter than the air it traps, springier than anything we have built.": "Ein Stickstoffkern unter Druck, umhüllt von superkritischem Schaum. Leichter als die Luft, die er hält, und sprungfreudiger als alles bisher.",
    "tanned in tuscany, cut by hand. each upper develops its own patina, so no two pairs age the same way.": "In der Toskana gegerbt, von Hand geschnitten. Jedes Obermaterial bekommt seine eigene Patina — zwei Paare altern nie gleich.",
    "a forged carbon-rubber outsole with directional lugs engineered for wet concrete, gravel, and everything between.": "Eine geschmiedete Carbon-Gummi-Sohle mit gerichteten Stollen, ausgelegt für nassen Beton, Schotter und alles dazwischen.",
    "a breathable, moisture-wicking ankle collar spun from 92% recycled ocean-bound plastics.": "Ein atmungsaktiver Schaft, der Feuchtigkeit ableitet, gesponnen aus 92 % Kunststoff, der vor dem Meer aufgefangen wurde.",
    "these replaced three pairs in my rotation. the sole is unreal — i forget i am wearing them on a 10k.": "Sie haben drei Paare in meiner Rotation ersetzt. Die Sohle ist unwirklich — auf zehn Kilometern vergesse ich, dass ich sie trage.",
    "the suede is genuinely premium. people stop me on the street. worth every euro and then some.": "Das Wildleder ist wirklich hochwertig. Man spricht mich auf der Straße an. Jeden Euro wert, und mehr.",
    "copped the vol. 02 drop in seconds. build quality crushes brands twice the price. shipping was fast too.": "Den Vol.-02-Drop hatte ich in Sekunden. Die Verarbeitung schlägt Marken zum doppelten Preis. Der Versand war obendrein schnell.",
    "the streets": "DIE STRASSE",
    "the": "die",
    ". limited runs, built to outlast the hype.": ". Limitierte Serien, gebaut, um länger zu halten als der Hype.",
    "← back to cart": "← Zurück zum Warenkorb",
    "30-day forge guarantee": "30-Tage Schmiede-Garantie",
    "4.9 / 5 from": "4,9 / 5 aus",
    "add to cart": "In den Warenkorb legen",
    "built in the workshop, not the boardroom": "In der Werkstatt entstanden, nicht im Sitzungssaal",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "Kollektionen sind in Minuten vergriffen. Mitglieder erhalten vierundzwanzig Stunden Vorsprung, exklusive Farben und kostenlosen Expressversand.",
    "engineered down": "Entwickelt für",
    "forged for": "Geschmiedet für",
    "free express over €150": "Expressversand gratis ab 150 €",
    "free shipping over €150": "VERSANDKOSTENFREI AB 150 €",
    "get the next drop first": "Erhalten Sie die nächste Kollektion zuerst",
    "have a question about our drops, sizing, or shipping? drop us a line.": "Fragen zu Kollektionen, Größen oder Versand? Schreiben Sie uns.",
    "into every pair": "in jedes Paar",
    "join the forge": "Der Werkstatt beitreten",
    "materials that age with you": "Materialien, die mit Ihnen altern",
    "new drop": "Neuheit",
    "new drops": "Neuheiten",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Stickstoffgefüllte Zwischensohle, abgestimmt auf 14 % mehr Energierückgabe.",
    "notify me": "Benachrichtige mich",
    "on the street": "Auf der Straße",
    "order confirmed": "Bestellung bestätigt",
    "shop the drop": "Zur Kollektion",
    "the anatomy": "Die Anatomie",
    "the craft": "Das Handwerk",
    "the forge": "Die Werkstatt",
    "this season's": "Der Saison",
    "this season's": "Diese Saison's",
    "to the stitch": "bis zur Naht",
    "view all 24 styles": "Alle 24 Modelle ansehen",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Jetzt erhältlich",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Wir wählen Veloursleder aus vollem Narben und recycelte Strickstoffe, die Charakter entwickeln. Nach einem Jahr gleicht Ihr Paar keinem anderen — genau darum geht es.",
    "you're in": "Du bist in",
    "your cart is empty": "Ihr Warenkorb ist leer",
  },
  pt: {
    "streets": "RUA",
    "performance-grade sneakers, built like industrial machinery and finished like couture. limited runs. forged to outlast.": "Ténis de nível desempenho, construídos como uma máquina industrial e acabados como uma peça de alta-costura. Séries limitadas. Feitos para durar.",
    "airforge started in a lyon garage with a heat press and an obsession. every silhouette is prototyped by hand, stress-tested on real streets, and refined until it earns the name.": "Tudo começou numa garagem em Lyon, com uma prensa térmica e uma obsessão. Cada silhueta é prototipada à mão, testada na rua e retrabalhada até merecer o nome.",
    "a pressurized nitrogen core wrapped in supercritical foam. lighter than the air it traps, springier than anything we have built.": "Um núcleo de azoto sob pressão envolvido em espuma supercrítica. Mais leve do que o ar que retém, mais vivo do que tudo o que já fizemos.",
    "tanned in tuscany, cut by hand. each upper develops its own patina, so no two pairs age the same way.": "Curtida na Toscana, cortada à mão. Cada gáspea ganha a sua pátina: dois pares nunca envelhecem igual.",
    "a forged carbon-rubber outsole with directional lugs engineered for wet concrete, gravel, and everything between.": "Uma sola de carbono e borracha forjada, com pitons direcionais, pensada para betão molhado, gravilha e tudo o que está pelo meio.",
    "a breathable, moisture-wicking ankle collar spun from 92% recycled ocean-bound plastics.": "Um colarinho respirável, que evacua a humidade, fiado a partir de 92 % de plásticos recuperados antes de chegarem ao oceano.",
    "these replaced three pairs in my rotation. the sole is unreal — i forget i am wearing them on a 10k.": "Substituíram três pares na minha rotação. A sola é irreal — esqueço-me de que as tenho nos pés ao fim de dez quilómetros.",
    "the suede is genuinely premium. people stop me on the street. worth every euro and then some.": "A camurça é mesmo de gama alta. Param-me na rua. Valem cada euro, e mais.",
    "copped the vol. 02 drop in seconds. build quality crushes brands twice the price. shipping was fast too.": "Apanhei a série Vol. 02 em segundos. O fabrico esmaga marcas do dobro do preço. E o envio foi rápido.",
    "the streets": "A RUA",
    "the": "a",
    ". limited runs, built to outlast the hype.": ". Séries limitadas, feitas para durar mais do que a moda.",
    "← back to cart": "← Voltar ao carrinho",
    "30-day forge guarantee": "Garantia de forja de 30 dias",
    "4.9 / 5 from": "4,9 / 5 de",
    "add to cart": "Adicionar ao carrinho",
    "built in the workshop, not the boardroom": "Feito na oficina, não na sala de reuniões",
    "drops sell out in minutes. members get a 24-hour early window, exclusive colorways, and free express shipping.": "As coleções esgotam em minutos. Os membros têm vinte e quatro horas de avanço, cores exclusivas e envio expresso gratuito.",
    "engineered down": "Projetado para",
    "forged for": "Forjado para",
    "free express over €150": "Expresso grátis a partir de 150 €",
    "free shipping over €150": "PORTES GRÁTIS A PARTIR DE 150 €",
    "get the next drop first": "Receba a próxima coleção em primeira mão",
    "have a question about our drops, sizing, or shipping? drop us a line.": "Alguma dúvida sobre coleções, tamanhos ou envio? Escreva-nos.",
    "into every pair": "em cada par",
    "join the forge": "Junte-se à oficina",
    "materials that age with you": "Materiais que envelhecem consigo",
    "new drop": "Novidade",
    "new drops": "Novidades",
    "nitrogen-charged midsole tuned for 14% more energy return.": "Entressola com azoto, afinada para devolver mais 14 % de energia.",
    "notify me": "Notifique-me",
    "on the street": "Na rua",
    "order confirmed": "Pedido confirmado",
    "shop the drop": "Ver a coleção",
    "the anatomy": "A anatomia",
    "the craft": "O ofício",
    "the forge": "A oficina",
    "this season's": "Da estação",
    "this season's": "Desta temporada",
    "to the stitch": "até à costura",
    "view all 24 styles": "Ver os 24 modelos",
    "vol. 04 — onyx · out now": "Vol. 04 — Onyx · Já disponível",
    "we source full-grain suede and recycled knits that develop character. your pair will not look like anyone else’s after a year — that is the point.": "Escolhemos camurça de flor inteira e malhas recicladas que ganham carácter. Ao fim de um ano, o seu par não se parecerá com nenhum outro — é essa a intenção.",
    "you're in": "Você está em",
    "your cart is empty": "O seu carrinho está vazio",
  },
};
