/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "manifesto": "Manifeste",
    "commission": "Nous confier un projet",
    "markets": "Marchés",
    "strategies": "Stratégies",
    "traders": "Opérateurs",
    "archive": "Archives",
    "e-commerce": "Commerce en ligne",
    "origins": "Origines",
    "source": "Origine",
    "roast": "Torréfaction",
    "cup": "Tasse",
    "programs": "Programmes",
    "members": "Membres",
    "destinations": "Destinations",
    "years experience": "Ans d'expérience",
    "releases": "Sorties",
    "tour": "Tournée",
    "store": "Boutique",
    "waste diverted": "Déchets détournés",
    "residential": "Résidentiel",
    "penthouse": "Attique",
    "concierge": "Conciergerie",
    "locations": "Nos adresses",
    "seller portal": "Espace vendeurs",
    "legacy": "Héritage",
    "select seat": "Choisir sa place",
    "offense": "Attaque",
    "intelligence": "Renseignement",
    "global nodes": "Nœuds mondiaux",
    "enlist": "Nous rejoindre",
    "market": "Marché",
    "curators": "Curateurs",
    "stats": "Chiffres",
    "connect wallet": "Connecter le portefeuille",
    "sanctuary": "Le sanctuaire",
    "retreats": "Retraites",
    "essence": "Essence",
    "landmark cases": "Affaires marquantes",
    "authority": "Autorité",
    "vegan & cruelty-free": "Végane et sans cruauté",
    "design": "DESIGN",
    "content": "CONTENU",
    "we design digital experiences that": "Nous concevons des expériences numériques qui",
    "a journey through synthetic soundscapes.": "Un voyage à travers des paysages sonores synthétiques.",
    "about the album": "À propos de l'album",
    "all dates": "Toutes les dates",
    "discover the minds behind the frequencies.": "Découvrez les esprits derrière les fréquences.",
    "get early access to tour tickets and limited vinyl pressing announcements.": "Obtenez un accès anticipé aux billets de tournée et aux annonces de pressage vinyle limité.",
    "independent label pushing the boundaries of electronic music since 2018.": "Label indépendant repoussant les limites de la musique électronique depuis 2018.",
    "independent record label and artist collective exploring the intersection of synthetic audio and digital art.": "Label de musique indépendant et collectif d'artistes explorant l'intersection de l'audio synthétique et de l'art numérique.",
    "join the frequency": "Rejoindre la fréquence",
    "listen live": "Écoutez en direct",
    "new york, us": "New York, États-Unis",
    "overture: the grid": "Ouverture : la grille",
    "pre-save on apple music": "Pré-enregistrez sur Apple Music",
    "pre-save on spotify": "Pré-enregistrez sur Spotify",
    "read manifesto": "Lire le manifeste",
    "the collective": "Le collectif",
  },
  es: {
    "manifesto": "Manifiesto",
    "commission": "Encargar un proyecto",
    "markets": "Mercados",
    "strategies": "Estrategias",
    "traders": "Operadores",
    "archive": "Archivo",
    "e-commerce": "Comercio electrónico",
    "origins": "Orígenes",
    "source": "Origen",
    "roast": "Tueste",
    "cup": "Taza",
    "programs": "Programas",
    "members": "Miembros",
    "destinations": "Destinos",
    "years experience": "Años de experiencia",
    "releases": "Lanzamientos",
    "tour": "Gira",
    "store": "Tienda",
    "waste diverted": "Residuos desviados",
    "residential": "Residencial",
    "penthouse": "Ático",
    "concierge": "Conserjería",
    "locations": "Nuestras direcciones",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Elegir asiento",
    "offense": "Ataque",
    "intelligence": "Inteligencia",
    "global nodes": "Nodos mundiales",
    "enlist": "Únase a nosotros",
    "market": "Mercado",
    "curators": "Comisarios",
    "stats": "Cifras",
    "connect wallet": "Conectar la cartera",
    "sanctuary": "El santuario",
    "retreats": "Retiros",
    "essence": "Esencia",
    "landmark cases": "Casos emblemáticos",
    "authority": "Autoridad",
    "vegan & cruelty-free": "Vegano y sin crueldad",
    "design": "DISEÑO",
    "content": "CONTENIDO",
    "we design digital experiences that": "Diseñamos experiencias digitales que",
    "a journey through synthetic soundscapes.": "Un viaje a través de paisajes sonoros sintéticos.",
    "about the album": "Sobre el álbum",
    "all dates": "Todas las fechas",
    "discover the minds behind the frequencies.": "Descubra las mentes tras las frecuencias.",
    "get early access to tour tickets and limited vinyl pressing announcements.": "Obtén acceso anticipado a las entradas de la gira y anuncios de prensado de vinilo limitado.",
    "independent label pushing the boundaries of electronic music since 2018.": "Sello independiente que empuja los límites de la música electrónica desde 2018.",
    "independent record label and artist collective exploring the intersection of synthetic audio and digital art.": "Sello discográfico independiente y colectivo de artistas que explora la intersección del audio sintético y el arte digital.",
    "join the frequency": "Únase a la frecuencia",
    "listen live": "Escucha en vivo",
    "new york, us": "Nueva York, EE. UU.",
    "overture: the grid": "Obertura: la cuadrícula",
    "pre-save on apple music": "Pre-guarda en Apple Music",
    "pre-save on spotify": "Pre-guarda en Spotify",
    "read manifesto": "Leer el manifiesto",
    "the collective": "El colectivo",
  },
  de: {
    "manifesto": "Manifest",
    "commission": "Projekt anfragen",
    "markets": "Märkte",
    "strategies": "Strategien",
    "traders": "Händler",
    "archive": "Archiv",
    "e-commerce": "E-Commerce",
    "origins": "Herkünfte",
    "source": "Ursprung",
    "roast": "Röstung",
    "cup": "Tasse",
    "programs": "Programme",
    "members": "Mitglieder",
    "destinations": "Reiseziele",
    "years experience": "Jahre Erfahrung",
    "releases": "Veröffentlichungen",
    "tour": "Tour",
    "store": "Shop",
    "waste diverted": "Umgeleitete Abfälle",
    "residential": "Wohnbau",
    "penthouse": "Penthouse",
    "concierge": "Concierge-Service",
    "locations": "Unsere Standorte",
    "seller portal": "Verkäuferbereich",
    "legacy": "Erbe",
    "select seat": "Platz wählen",
    "offense": "Angriff",
    "intelligence": "Aufklärung",
    "global nodes": "Weltweite Knoten",
    "enlist": "Mitmachen",
    "market": "Markt",
    "curators": "Kuratoren",
    "stats": "Zahlen",
    "connect wallet": "Wallet verbinden",
    "sanctuary": "Das Refugium",
    "retreats": "Retreats",
    "essence": "Essenz",
    "landmark cases": "Wegweisende Fälle",
    "authority": "Autorität",
    "vegan & cruelty-free": "Vegan und tierversuchsfrei",
    "design": "DESIGN",
    "content": "INHALT",
    "we design digital experiences that": "Wir gestalten digitale Erlebnisse, die",
    "a journey through synthetic soundscapes.": "Eine Reise durch synthetische Klanglandschaften.",
    "about the album": "Über das Album",
    "all dates": "Alle Termine",
    "discover the minds behind the frequencies.": "Entdecken Sie die Köpfe hinter den Frequenzen.",
    "get early access to tour tickets and limited vinyl pressing announcements.": "Erhalten Sie frühzeitigen Zugang zu Tourtickets und Ankündigungen von limitierten Vinylpressungen.",
    "independent label pushing the boundaries of electronic music since 2018.": "Unabhängiges Label, das die Grenzen der elektronischen Musik seit 2018 verschiebt.",
    "independent record label and artist collective exploring the intersection of synthetic audio and digital art.": "Unabhängiges Plattenlabel und Künstlerkollektiv, das die Schnittstelle zwischen synthetischem Audio und digitaler Kunst erkundet.",
    "join the frequency": "Der Frequenz beitreten",
    "listen live": "Live hören",
    "new york, us": "New York, USA",
    "overture: the grid": "Ouvertüre: das Raster",
    "pre-save on apple music": "Vorab speichern auf Apple Music",
    "pre-save on spotify": "Vorab speichern auf Spotify",
    "read manifesto": "Manifest lesen",
    "the collective": "Das Kollektiv",
  },
  pt: {
    "manifesto": "Manifesto",
    "commission": "Confiar-nos um projeto",
    "markets": "Mercados",
    "strategies": "Estratégias",
    "traders": "Operadores",
    "archive": "Arquivo",
    "e-commerce": "Comércio eletrónico",
    "origins": "Origens",
    "source": "Origem",
    "roast": "Torra",
    "cup": "Chávena",
    "programs": "Programas",
    "members": "Membros",
    "destinations": "Destinos",
    "years experience": "Anos de experiência",
    "releases": "Lançamentos",
    "tour": "Digressão",
    "store": "Loja",
    "waste diverted": "Resíduos desviados",
    "residential": "Residencial",
    "penthouse": "Cobertura",
    "concierge": "Concierge",
    "locations": "As nossas moradas",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Escolher lugar",
    "offense": "Ataque",
    "intelligence": "Informações",
    "global nodes": "Nós mundiais",
    "enlist": "Junte-se a nós",
    "market": "Mercado",
    "curators": "Curadores",
    "stats": "Números",
    "connect wallet": "Ligar a carteira",
    "sanctuary": "O santuário",
    "retreats": "Retiros",
    "essence": "Essência",
    "landmark cases": "Casos marcantes",
    "authority": "Autoridade",
    "vegan & cruelty-free": "Vegano e sem crueldade",
    "design": "DESIGN",
    "content": "CONTEÚDO",
    "we design digital experiences that": "Concebemos experiências digitais que",
    "a journey through synthetic soundscapes.": "Uma jornada através de paisagens sonoras sintéticas.",
    "about the album": "Sobre o álbum",
    "all dates": "Todas as datas",
    "discover the minds behind the frequencies.": "Descubra as mentes por trás das frequências.",
    "get early access to tour tickets and limited vinyl pressing announcements.": "Obtenha acesso antecipado a bilhetes de turnê e anúncios de prensagem de vinil limitada.",
    "independent label pushing the boundaries of electronic music since 2018.": "Editora independente que ultrapassa os limites da música eletrônica desde 2018.",
    "independent record label and artist collective exploring the intersection of synthetic audio and digital art.": "Editora independente e coletivo de artistas que explora a interseção entre áudio sintético e arte digital.",
    "join the frequency": "Junte-se à frequência",
    "listen live": "Ouça ao vivo",
    "new york, us": "Nova Iorque, EUA",
    "overture: the grid": "Abertura: a grelha",
    "pre-save on apple music": "Pré-salve no Apple Music",
    "pre-save on spotify": "Pré-salve no Spotify",
    "read manifesto": "Ler o manifesto",
    "the collective": "O coletivo",
  },
};
