/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "birds of paradise, proteas, and tropical foliage statement piece.": "Oiseaux de paradis, proteas et pièce maîtresse de feuillage tropical.",
    "book a workshop": "Réservez un atelier",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Bouquets de mariée, installations de cérémonie, centres de table pour la réception et direction florale complète de l'brief initial au dernier pétale du jour.",
    "browse occasions": "Parcourir les occasions",
    "can i pause or cancel my subscription?": "Puis-je mettre en pause ou annuler mon abonnement ?",
    "can i request specific flowers or colours?": "Puis-je demander des fleurs ou des couleurs spécifiques ?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Tiges de fleurs de cerisier avec de délicates pois sucrés et des freesias.",
    "clients satisfaits": "clients satisfaits",
    "do you do same-day delivery?": "Faites-vous des livraisons le jour même ?",
    "do you offer workshops?": "Proposez-vous des ateliers ?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eucalyptus, fougères et feuillages saisonniers avec des fleurs blanches.",
    "flowers for every chapter": "Des fleurs pour chaque chapitre",
    "for every": "Pour chaque",
    "free delivery île-de-france": "Livraison offerte en Île-de-France",
    "free delivery nantes": "Livraison offerte à Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "De la fête la plus joyeuse à l'adieu le plus tendre — nous sommes là pour chaque occasion qui compte.",
    "garden roses in deep coral and orange with jasmine vine.": "Roses de jardin en corail profond et orange avec de la vigne de jasmin.",
    "how far in advance should i order for a wedding?": "Combien de temps à l'avance dois-je commander pour un mariage ?",
    "made by hand,": "Fait à la main,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Un bouquet artisanal livré chaque semaine. Sélection saisonnière, choisie par nos fleuristes.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Une pièce maîtresse par mois — plus grande, plus dramatique, un véritable point focal pour votre maison.",
    "order": "Commander",
    "our parisian studio": "Notre atelier parisien",
    "peonies, tulipes, and garden roses in blush and cream.": "Pivoines, tulipes et roses de jardin en rose et crème.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Des compositions belles et respectueuses pour les cérémonies. Nous travaillons directement avec les familles et les pompes funèbres, avec délicatesse.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Bouquets saisonniers, soigneusement sélectionnés à la main, livrés chez vous à l'heure prévue. Mettez en pause ou annulez à tout moment.",
    "shop subscriptions": "Abonnements de boutique",
    "single-variety hellebore and dried cotton stems in clean lines.": "Hellebore de variété unique et tiges de coton séchées aux lignes épurées.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "De grandes compositions livrées à la porte, ou un atelier où chacun compose son bouquet — mémorable dans les deux cas.",
    "subscribe biweekly": "Abonnement bimensuel",
    "subscribe monthly": "Abonnement mensuel",
    "subscribe weekly": "Abonnement hebdomadaire",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Tournesols, dahlias, lavande et roses de jardin luxuriantes à leur apogée.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Tournesols, lavande et dahlias dorés en abondance chaleureuse.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulipes, pivoines, renoncules et fleurs de cerisier — la saison des nouveaux départs.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Deux bouquets par mois — le bon rythme pour qui aime les fleurs sans vouloir s'engager.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Nous travaillons autant que possible avec de petits producteurs français, choisissons la fleur de saison plutôt que l'importation, et composons tout à la main — d'une tige unique à une arche de mariage.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Livraison hebdomadaire de l'arrangement saisonnier. Je suis abonné depuis 14 mois et ils ne se sont jamais répétés. Chaque semaine est une petite surprise.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Fleurs de bureau hebdomadaires, installations d'événements pour les lancements de produits, showrooms et galas. Facturé mensuellement, entièrement géré.",
    "what areas do you deliver to?": "Dans quelles zones livrez-vous ?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Amaryllis blanc, hellébores, pin et le rouge profond des baies d'hiver.",
    "with intention.": "Avec intention.",
    "workshop from": "Atelier à partir de",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Oui. Vous pouvez mettre en pause jusqu'à 4 semaines par an ou annuler à tout moment avec un préavis d'une semaine. Pas de pénalités, pas de questions.",
  },
  es: {
    "birds of paradise, proteas, and tropical foliage statement piece.": "Aves del paraíso, proteas y pieza central de follaje tropical.",
    "book a workshop": "Reserva un taller",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Ramos de novia, instalaciones de ceremonia, centros de mesa para la recepción y dirección floral completa desde el primer briefing hasta el último pétalo del día.",
    "browse occasions": "Ver ocasiones",
    "can i pause or cancel my subscription?": "¿Puedo pausar o cancelar mi suscripción?",
    "can i request specific flowers or colours?": "¿Puedo solicitar flores o colores específicos?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Tallos de flores de cerezo con delicados guisantes de olor y fresias.",
    "clients satisfaits": "clientes satisfechos",
    "do you do same-day delivery?": "¿Hacen entregas el mismo día?",
    "do you offer workshops?": "¿Ofrecen talleres?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eucalipto, helechos y verdes de temporada con flores blancas.",
    "flowers for every chapter": "Flores para cada capítulo",
    "for every": "Para cada",
    "free delivery île-de-france": "Envío gratis en Île-de-France",
    "free delivery nantes": "Envío gratis en Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "De la celebración más alegre a la despedida más tierna: estamos para cada ocasión que importa.",
    "garden roses in deep coral and orange with jasmine vine.": "Rosas de jardín en coral profundo y naranja con enredadera de jazmín.",
    "how far in advance should i order for a wedding?": "¿Con cuánta antelación debo hacer un pedido para una boda?",
    "made by hand,": "Hecho a mano,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Un ramo artesanal entregado cada semana. Selección estacional, curada por nuestros floristas.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Una pieza destacada por mes — más grande, más dramática, un verdadero punto focal para tu hogar.",
    "order": "Ordenar",
    "our parisian studio": "Nuestro taller parisino",
    "peonies, tulipes, and garden roses in blush and cream.": "Peonías, tulipanes y rosas de jardín en rosa y crema.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Composiciones bellas y respetuosas para las ceremonias. Trabajamos directamente con las familias y las funerarias, con delicadeza.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Ramos de temporada, seleccionados a mano, entregados en su puerta a tiempo. Pausa o cancela en cualquier momento.",
    "shop subscriptions": "Suscripciones de tienda",
    "single-variety hellebore and dried cotton stems in clean lines.": "Helleboro de variedad única y tallos de algodón secos en líneas limpias.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "Grandes composiciones entregadas en la puerta, o un taller donde cada uno compone su ramo: memorable en ambos casos.",
    "subscribe biweekly": "Suscripción quincenal",
    "subscribe monthly": "Suscripción mensual",
    "subscribe weekly": "Suscripción semanal",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Girasoles, dalias, lavanda y exuberantes rosas de jardín en su mejor momento.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Girasoles, lavanda y dalias doradas en abundancia cálida.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulipanes, peonías, ranúnculos y flores de cerezo — la temporada de nuevos comienzos.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Dos ramos al mes: el ritmo justo para quien ama las flores sin querer atarse.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Trabajamos siempre que podemos con pequeños productores franceses, elegimos la flor de temporada frente a la importada y componemos todo a mano: de un solo tallo a un arco de boda.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Entrega semanal del arreglo estacional. He sido suscriptor durante 14 meses y nunca se han repetido. Cada semana es una pequeña sorpresa.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Flores de oficina semanales, instalaciones de eventos para lanzamientos de productos, salas de exposición y galas. Facturado mensualmente, totalmente gestionado.",
    "what areas do you deliver to?": "¿A qué áreas entregan?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Amaryllis blanca, heléboros, pino y el rojo profundo de las bayas de invierno.",
    "with intention.": "Con intención.",
    "workshop from": "Taller desde",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Sí. Puedes pausar hasta 4 semanas al año o cancelar en cualquier momento con una semana de aviso. Sin penalizaciones, sin preguntas.",
  },
  de: {
    "birds of paradise, proteas, and tropical foliage statement piece.": "Paradiesvögel, Proteas und tropisches Laub als Blickfang.",
    "book a workshop": "Buchen Sie einen Workshop",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Hochzeitssträuße, Zeremonie-Installationen, Empfangszentren und vollständige florale Anleitung vom ersten Briefing bis zum letzten Blatt am Tag.",
    "browse occasions": "Anlässe entdecken",
    "can i pause or cancel my subscription?": "Kann ich mein Abonnement pausieren oder kündigen?",
    "can i request specific flowers or colours?": "Kann ich bestimmte Blumen oder Farben anfordern?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Kirschblütenstiele mit zarten Süßerbsen und Freesien.",
    "clients satisfaits": "zufriedene Kunden",
    "do you do same-day delivery?": "Bieten Sie Same-Day-Lieferungen an?",
    "do you offer workshops?": "Bieten Sie Workshops an?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eukalyptus, Farne und saisonales Grün mit weißen Blüten.",
    "flowers for every chapter": "Blumen für jedes Kapitel",
    "for every": "Für jeden",
    "free delivery île-de-france": "Kostenlose Lieferung in der Île-de-France",
    "free delivery nantes": "Kostenlose Lieferung in Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "Von der fröhlichsten Feier bis zum zartesten Abschied — wir sind für jeden Anlass da, der zählt.",
    "garden roses in deep coral and orange with jasmine vine.": "Gartenrosen in tiefem Koralle und Orange mit Jasminranke.",
    "how far in advance should i order for a wedding?": "Wie weit im Voraus sollte ich für eine Hochzeit bestellen?",
    "made by hand,": "Handgemacht,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Ein handwerklicher Strauß wird jede Woche geliefert. Saisonale Auswahl, kuratiert von unseren Floristen.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Ein Statement-Stück pro Monat — größer, dramatischer, ein echter Blickfang für Ihr Zuhause.",
    "order": "Bestellen",
    "our parisian studio": "Unser Pariser Atelier",
    "peonies, tulipes, and garden roses in blush and cream.": "Pfingstrosen, Tulpen und Gartenrosen in Blush und Creme.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Schöne, würdevolle Gestecke für Trauerfeiern. Wir arbeiten einfühlsam direkt mit Familien und Bestattern.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Saisonale Sträuße, handverlesen, pünktlich zu Ihnen nach Hause geliefert. Pausieren oder jederzeit kündigen.",
    "shop subscriptions": "Shop-Abonnements",
    "single-variety hellebore and dried cotton stems in clean lines.": "Einzelne Helleborus-Sorte und getrocknete Baumwollstängel in klaren Linien.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "Große Arrangements bis vor die Tür geliefert, oder ein Workshop, bei dem jeder seinen Strauß bindet — beides bleibt in Erinnerung.",
    "subscribe biweekly": "Zweiwöchentliches Abo",
    "subscribe monthly": "Monatliches Abo",
    "subscribe weekly": "Wöchentliches Abo",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Sonnenblumen, Dahlien, Lavendel und üppige Gartenrosen auf ihrem Höhepunkt.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Sonnenblumen, Lavendel und goldene Dahlien in warmer Fülle.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulpen, Pfingstrosen, Ranunkeln und Kirschblüten — die Saison frischer Anfänge.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Zwei Sträuße im Monat — der richtige Rhythmus für alle, die Blumen lieben, sich aber nicht binden wollen.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Wir arbeiten, wo möglich, mit kleinen französischen Gärtnereien, wählen Saisonblumen statt Importware und binden alles von Hand — von der einzelnen Blüte bis zum Hochzeitsbogen.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Wöchentliche Lieferung des saisonalen Arrangements. Ich bin seit 14 Monaten Abonnent und sie haben sich nie wiederholt. Jede Woche ist eine kleine Überraschung.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Wöchentliche Büroblumen, Veranstaltungsinstallationen für Produkteinführungen, Showrooms und Galas. Monatlich in Rechnung gestellt, vollständig verwaltet.",
    "what areas do you deliver to?": "In welchen Bereichen liefern Sie?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Weiße Amaryllis, Helleborus, Kiefer und das tiefrote Winterbeeren.",
    "with intention.": "Mit Absicht.",
    "workshop from": "Workshop ab",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Ja. Sie können bis zu 4 Wochen pro Jahr pausieren oder jederzeit mit einer Woche Vorankündigung kündigen. Keine Strafen, keine Fragen.",
  },
  pt: {
    "birds of paradise, proteas, and tropical foliage statement piece.": "Aves do paraíso, proteas e peça central de folhagem tropical.",
    "book a workshop": "Reserve um workshop",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Buquês de noiva, instalações de cerimônia, centros de mesa para a recepção e direção floral completa desde o briefing inicial até a última pétala do dia.",
    "browse occasions": "Ver ocasiões",
    "can i pause or cancel my subscription?": "Posso pausar ou cancelar a minha assinatura?",
    "can i request specific flowers or colours?": "Posso solicitar flores ou cores específicas?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Talos de flores de cerejeira com delicadas ervilhas-doces e fresias.",
    "clients satisfaits": "clientes satisfeitos",
    "do you do same-day delivery?": "Fazem entregas no mesmo dia?",
    "do you offer workshops?": "Oferecem workshops?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eucalipto, fetos e verdes sazonais com flores brancas.",
    "flowers for every chapter": "Flores para cada capítulo",
    "for every": "Para cada",
    "free delivery île-de-france": "Entrega grátis na Île-de-France",
    "free delivery nantes": "Entrega grátis em Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "Da celebração mais alegre à despedida mais terna — estamos para cada ocasião que importa.",
    "garden roses in deep coral and orange with jasmine vine.": "Rosas de jardim em coral profundo e laranja com trepadeira de jasmim.",
    "how far in advance should i order for a wedding?": "Com quanto tempo de antecedência devo fazer um pedido para um casamento?",
    "made by hand,": "Feito à mão,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Um bouquet artesanal entregue a cada semana. Seleção sazonal, curada pelos nossos floristas.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Uma peça de destaque por mês — maior, mais dramática, um verdadeiro ponto focal para a sua casa.",
    "order": "Pedir",
    "our parisian studio": "O nosso atelier parisiense",
    "peonies, tulipes, and garden roses in blush and cream.": "Peónias, tulipas e rosas de jardim em rosa e creme.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Composições belas e respeitosas para as cerimónias. Trabalhamos diretamente com as famílias e as agências funerárias, com delicadeza.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Arranjos sazonais, selecionados à mão, entregues à sua porta pontualmente. Pause ou cancele a qualquer momento.",
    "shop subscriptions": "Assinaturas de loja",
    "single-variety hellebore and dried cotton stems in clean lines.": "Helleboro de variedade única e hastes de algodão secas em linhas limpas.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "Grandes composições entregues à porta, ou um workshop onde cada um compõe o seu ramo — memorável nos dois casos.",
    "subscribe biweekly": "Assinatura quinzenal",
    "subscribe monthly": "Assinatura mensal",
    "subscribe weekly": "Assinatura semanal",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Girassóis, dálias, lavanda e exuberantes rosas de jardim no seu auge.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Girassóis, lavanda e dálias douradas em abundância quente.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulipas, peónias, ranúnculos e flores de cerejeira — a temporada de novos começos.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Dois ramos por mês — o ritmo certo para quem gosta de flores sem se querer prender.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Trabalhamos sempre que possível com pequenos produtores franceses, escolhemos a flor da época em vez da importada e compomos tudo à mão — de uma única haste a um arco de casamento.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Entrega semanal do arranjo sazonal. Sou assinante há 14 meses e eles nunca se repetiram. Cada semana é uma pequena surpresa.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Flores de escritório semanais, instalações de eventos para lançamentos de produtos, showrooms e galas. Faturado mensalmente, totalmente gerido.",
    "what areas do you deliver to?": "A que áreas entregam?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Amaryllis branca, heléboros, pinheiro e o vermelho profundo das bagas de inverno.",
    "with intention.": "Com intenção.",
    "workshop from": "Workshop a partir de",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Sim. Pode pausar até 4 semanas por ano ou cancelar a qualquer momento com uma semana de antecedência. Sem penalizações, sem perguntas.",
  },
};
