/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "blossom drift": "Envolée florale",
    "seasonal collections": "Collections de saison",
    "nature's calendar": "Le calendrier de la nature",
    "spring": "Printemps",
    "summer": "Été",
    "autumn": "Automne",
    "winter": "Hiver",
    "green awakening": "Réveil végétal",
    "weddings": "Mariages",
    "funerals & tribute": "Obsèques et hommages",
    "birthdays & events": "Anniversaires et événements",
    "corporate": "Entreprises",
    "session length": "Durée de l'atelier",
    "max per group": "Personnes maximum",
    "weekly": "Chaque semaine",
    "public sessions": "Ateliers ouverts à tous",
    "wedding": "Mariage",
    "workshop": "Atelier",
    "monthly sub": "Abonnement mensuel",
    "bouquet subscriptions": "Abonnements bouquets",
    "always fresh. never repeated.": "Toujours frais. Jamais deux fois le même.",
    "per week": "par semaine",
    "per month": "par mois",
    "seasonal arrangement": "Composition de saison",
    "free delivery paris": "Livraison offerte dans Paris",
    "kraft wrapping + ribbon": "Emballage kraft et ruban",
    "care card": "Carte d'entretien",
    "2 seasonal arrangements": "Deux compositions de saison",
    "choice of style": "Style au choix",
    "care card + seasonal note": "Carte d'entretien et mot de saison",
    "1 large seasonal piece": "Une grande pièce de saison",
    "statement composition": "Composition maîtresse",
    "hand-crafted seasonal arrangements, botanical bouquet subscriptions, and wedding floral direction from our parisian studio.": "Compositions de saison faites à la main, abonnements de bouquets botaniques et direction florale de mariage, depuis notre atelier parisien.",
    "was born from a simple belief: flowers shouldn't be an afterthought. founded in 2014 by florist amélie rousseau, our studio in the 11th arrondissement has become a gathering place for people who care about natural beauty.": "est né d'une conviction simple : les fleurs ne devraient jamais être une pensée d'après-coup. Fondé en 2014 par la fleuriste Amélie Rousseau, l'atelier du 11e est devenu un point de rendez-vous pour ceux qui tiennent à la beauté naturelle.",
    "pétales & co did our entire wedding — 18 arrangements, 4 arches, bridal party bouquets. every single piece was more beautiful than i imagined. they understood our vision perfectly.": "Ils ont fait tout notre mariage — 18 compositions, 4 arches, les bouquets du cortège. Chaque pièce était plus belle que ce que j'imaginais. Ils avaient parfaitement compris ce que nous voulions.",
    "i have a monthly subscription for my law office lobby. the team selects seasonally and the arrangements always receive comments from clients. it has genuinely changed the feel of the space.": "J'ai un abonnement mensuel pour l'accueil de mon cabinet. L'équipe choisit selon la saison et les compositions font toujours réagir les clients. Cela a vraiment changé l'atmosphère du lieu.",
    "we did the bouquet workshop for my sister's birthday. eight of us, two hours, incredible instruction and a gorgeous takeaway. the best afternoon we've had together in years.": "Nous avons fait l'atelier bouquet pour l'anniversaire de ma sœur. Huit personnes, deux heures, un enseignement formidable et un bouquet à emporter. La plus belle après-midi passée ensemble depuis des années.",
    "we deliver within paris and the île-de-france region. paris deliveries are free for all subscriptions. île-de-france deliveries have a €12 surcharge for one-off orders — free for monthly subscribers.": "Nous livrons dans Paris et en Île-de-France. La livraison est offerte dans Paris pour tous les abonnements. En Île-de-France, 12 € s'ajoutent pour une commande ponctuelle — offerts pour les abonnés mensuels.",
    "absolutely. at checkout or when setting up a subscription, leave your preferences. we'll do our best to honour them subject to seasonal availability. some flowers are simply unavailable out of season — part of what makes them special.": "Bien sûr. Au moment de commander ou de créer un abonnement, indiquez vos préférences. Nous ferons au mieux, selon la saison : certaines fleurs sont simplement introuvables hors saison — c'est aussi ce qui fait leur prix.",
    "we recommend 3–6 months for weddings. summer dates (june–september) are extremely popular and book out 6+ months ahead. contact us as early as possible and we'll confirm availability.": "Nous conseillons trois à six mois pour un mariage. Les dates d'été (juin-septembre) partent très vite, souvent plus de six mois à l'avance. Écrivez-nous au plus tôt, nous confirmerons les disponibilités.",
    "yes — we run weekly public workshops at our studio (€65/person, 2 hours, includes materials and takeaway bouquet) and private group bookings for up to 12 people. email us or book via our website.": "Oui — nous animons chaque semaine des ateliers ouverts à tous (65 € par personne, deux heures, matériel et bouquet à emporter compris) et des ateliers privés jusqu'à douze personnes. Écrivez-nous ou réservez en ligne.",
    "for in-stock arrangements ordered before 10h, we offer same-day delivery in paris (€18 express fee). for custom orders or workshop bookings, advance notice is required.": "Pour les compositions en stock commandées avant 10 h, la livraison le jour même est possible dans Paris (18 € en express). Pour une commande sur mesure ou un atelier, il faut prévenir à l'avance.",
    "florist home": "Accueil",
    "hand-crafted floral arrangements, seasonal subscriptions, and wedding floral direction.": "Compositions florales faites à la main, abonnements de saison et direction florale de mariage.",
    "birds of paradise, proteas, and tropical foliage statement piece.": "Oiseaux de paradis, proteas et pièce maîtresse de feuillage tropical.",
    "book a workshop": "Réservez un atelier",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Bouquets de mariée, installations de cérémonie, centres de table pour la réception et direction florale complète du premier échange au dernier pétale du jour.",
    "browse occasions": "Parcourir les occasions",
    "can i pause or cancel my subscription?": "Puis-je mettre en pause ou annuler mon abonnement ?",
    "can i request specific flowers or colours?": "Puis-je demander des fleurs ou des couleurs spécifiques ?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Tiges de fleurs de cerisier avec de délicates pois sucrés et des freesias.",
    "clients satisfaits": "clients satisfaits",
    "do you do same-day delivery?": "Faites-vous des livraisons le jour même ?",
    "do you offer workshops?": "Proposez-vous des ateliers ?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eucalyptus, fougères et feuillages saisonniers avec des fleurs blanches.",
    "flowers for every chapter": "Des fleurs pour chaque chapitre",
    "for every": "Pour chaque",
    "free delivery île-de-france": "Livraison offerte en Île-de-France",
    "free delivery nantes": "Livraison offerte à Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "De la fête la plus joyeuse à l'adieu le plus tendre — nous sommes là pour chaque occasion qui compte.",
    "garden roses in deep coral and orange with jasmine vine.": "Roses de jardin en corail profond et orange avec de la vigne de jasmin.",
    "how far in advance should i order for a wedding?": "Combien de temps à l'avance dois-je commander pour un mariage ?",
    "made by hand,": "Fait à la main,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Un bouquet artisanal livré chaque semaine. Sélection saisonnière, choisie par nos fleuristes.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Une pièce maîtresse par mois — plus grande, plus dramatique, un véritable point focal pour votre maison.",
    "order": "Commander",
    "our parisian studio": "Notre atelier parisien",
    "peonies, tulipes, and garden roses in blush and cream.": "Pivoines, tulipes et roses de jardin en rose et crème.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Des compositions belles et respectueuses pour les cérémonies. Nous travaillons directement avec les familles et les pompes funèbres, avec délicatesse.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Bouquets saisonniers, soigneusement sélectionnés à la main, livrés chez vous à l'heure prévue. Mettez en pause ou annulez à tout moment.",
    "seasonal story card": "Carte d'histoire saisonnière",
    "shop subscriptions": "Abonnements de boutique",
    "single-variety hellebore and dried cotton stems in clean lines.": "Hellebore de variété unique et tiges de coton séchées aux lignes épurées.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "De grandes compositions livrées à la porte, ou un atelier où chacun compose son bouquet — mémorable dans les deux cas.",
    "subscribe biweekly": "Abonnement bimensuel",
    "subscribe monthly": "Abonnement mensuel",
    "subscribe weekly": "Abonnement hebdomadaire",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Tournesols, dahlias, lavande et roses de jardin luxuriantes à leur apogée.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Tournesols, lavande et dahlias dorés en abondance chaleureuse.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulipes, pivoines, renoncules et fleurs de cerisier — la saison des nouveaux départs.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Deux bouquets par mois — le bon rythme pour qui aime les fleurs sans vouloir s'engager.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Nous travaillons autant que possible avec de petits producteurs français, choisissons la fleur de saison plutôt que l'importation, et composons tout à la main — d'une tige unique à une arche de mariage.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Livraison hebdomadaire de l'arrangement saisonnier. Je suis abonné depuis 14 mois et ils ne se sont jamais répétés. Chaque semaine est une petite surprise.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Fleurs de bureau hebdomadaires, installations d'événements pour les lancements de produits, showrooms et galas. Facturé mensuellement, entièrement géré.",
    "what areas do you deliver to?": "Dans quelles zones livrez-vous ?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Amaryllis blanc, hellébores, pin et le rouge profond des baies d'hiver.",
    "with intention.": "Avec intention.",
    "workshop from": "Atelier à partir de",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Oui. Vous pouvez mettre en pause jusqu'à 4 semaines par an ou annuler à tout moment avec un préavis d'une semaine. Pas de pénalités, pas de questions.",
  },
  es: {
    "blossom drift": "Vuelo floral",
    "seasonal collections": "Colecciones de temporada",
    "nature's calendar": "El calendario de la naturaleza",
    "spring": "Primavera",
    "summer": "Verano",
    "autumn": "Otoño",
    "winter": "Invierno",
    "green awakening": "Despertar vegetal",
    "weddings": "Bodas",
    "funerals & tribute": "Funerales y homenajes",
    "birthdays & events": "Cumpleaños y eventos",
    "corporate": "Empresas",
    "session length": "Duración del taller",
    "max per group": "Personas máximo",
    "weekly": "Cada semana",
    "public sessions": "Talleres abiertos a todos",
    "wedding": "Boda",
    "workshop": "Taller",
    "monthly sub": "Suscripción mensual",
    "bouquet subscriptions": "Suscripciones de ramos",
    "always fresh. never repeated.": "Siempre frescos. Nunca dos veces iguales.",
    "per week": "por semana",
    "per month": "al mes",
    "seasonal arrangement": "Composición de temporada",
    "free delivery paris": "Entrega gratuita en París",
    "kraft wrapping + ribbon": "Envoltorio kraft y cinta",
    "care card": "Tarjeta de cuidados",
    "2 seasonal arrangements": "Dos composiciones de temporada",
    "choice of style": "Estilo a elegir",
    "care card + seasonal note": "Tarjeta de cuidados y nota de temporada",
    "1 large seasonal piece": "Una gran pieza de temporada",
    "statement composition": "Composición protagonista",
    "hand-crafted seasonal arrangements, botanical bouquet subscriptions, and wedding floral direction from our parisian studio.": "Composiciones de temporada hechas a mano, suscripciones de ramos botánicos y dirección floral de bodas, desde nuestro taller parisino.",
    "was born from a simple belief: flowers shouldn't be an afterthought. founded in 2014 by florist amélie rousseau, our studio in the 11th arrondissement has become a gathering place for people who care about natural beauty.": "nació de una convicción simple: las flores nunca deberían ser un añadido de última hora. Fundado en 2014 por la florista Amélie Rousseau, el taller del distrito 11 se ha vuelto un punto de encuentro para quienes valoran la belleza natural.",
    "pétales & co did our entire wedding — 18 arrangements, 4 arches, bridal party bouquets. every single piece was more beautiful than i imagined. they understood our vision perfectly.": "Hicieron toda nuestra boda — 18 composiciones, 4 arcos, los ramos del cortejo. Cada pieza superó lo que imaginaba. Entendieron a la perfección lo que queríamos.",
    "i have a monthly subscription for my law office lobby. the team selects seasonally and the arrangements always receive comments from clients. it has genuinely changed the feel of the space.": "Tengo una suscripción mensual para la recepción de mi despacho. El equipo elige según la temporada y las composiciones siempre provocan comentarios de los clientes. Ha cambiado de verdad el ambiente del lugar.",
    "we did the bouquet workshop for my sister's birthday. eight of us, two hours, incredible instruction and a gorgeous takeaway. the best afternoon we've had together in years.": "Hicimos el taller de ramos para el cumpleaños de mi hermana. Ocho personas, dos horas, una enseñanza estupenda y un ramo para llevar. La mejor tarde juntos en años.",
    "we deliver within paris and the île-de-france region. paris deliveries are free for all subscriptions. île-de-france deliveries have a €12 surcharge for one-off orders — free for monthly subscribers.": "Entregamos en París y en Île-de-France. El envío es gratuito en París para todas las suscripciones. En Île-de-France se añaden 12 € para pedidos puntuales — gratis para los abonados mensuales.",
    "absolutely. at checkout or when setting up a subscription, leave your preferences. we'll do our best to honour them subject to seasonal availability. some flowers are simply unavailable out of season — part of what makes them special.": "Por supuesto. Al hacer el pedido o crear una suscripción, indique sus preferencias. Haremos lo posible según la temporada: algunas flores sencillamente no existen fuera de temporada — es también lo que las hace valiosas.",
    "we recommend 3–6 months for weddings. summer dates (june–september) are extremely popular and book out 6+ months ahead. contact us as early as possible and we'll confirm availability.": "Aconsejamos de tres a seis meses para una boda. Las fechas de verano (junio-septiembre) se agotan muy rápido, a menudo con más de seis meses. Escríbanos cuanto antes y confirmaremos disponibilidad.",
    "yes — we run weekly public workshops at our studio (€65/person, 2 hours, includes materials and takeaway bouquet) and private group bookings for up to 12 people. email us or book via our website.": "Sí — cada semana organizamos talleres abiertos a todos (65 € por persona, dos horas, material y ramo incluidos) y talleres privados hasta doce personas. Escríbanos o reserve en línea.",
    "for in-stock arrangements ordered before 10h, we offer same-day delivery in paris (€18 express fee). for custom orders or workshop bookings, advance notice is required.": "Para composiciones en stock pedidas antes de las 10 h, la entrega el mismo día es posible en París (18 € exprés). Para pedidos a medida o talleres, hay que avisar con antelación.",
    "florist home": "Inicio",
    "hand-crafted floral arrangements, seasonal subscriptions, and wedding floral direction.": "Composiciones florales hechas a mano, suscripciones de temporada y dirección floral de bodas.",
    "birds of paradise, proteas, and tropical foliage statement piece.": "Aves del paraíso, proteas y pieza central de follaje tropical.",
    "book a workshop": "Reserva un taller",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Ramos de novia, instalaciones de ceremonia, centros de mesa para la recepción y dirección floral completa desde el primer briefing hasta el último pétalo del día.",
    "browse occasions": "Ver ocasiones",
    "can i pause or cancel my subscription?": "¿Puedo pausar o cancelar mi suscripción?",
    "can i request specific flowers or colours?": "¿Puedo solicitar flores o colores específicos?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Tallos de flores de cerezo con delicados guisantes de olor y fresias.",
    "clients satisfaits": "clientes satisfechos",
    "do you do same-day delivery?": "¿Hacen entregas el mismo día?",
    "do you offer workshops?": "¿Ofrecen talleres?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eucalipto, helechos y verdes de temporada con flores blancas.",
    "flowers for every chapter": "Flores para cada capítulo",
    "for every": "Para cada",
    "free delivery île-de-france": "Envío gratis en Île-de-France",
    "free delivery nantes": "Envío gratis en Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "De la celebración más alegre a la despedida más tierna: estamos para cada ocasión que importa.",
    "garden roses in deep coral and orange with jasmine vine.": "Rosas de jardín en coral profundo y naranja con enredadera de jazmín.",
    "how far in advance should i order for a wedding?": "¿Con cuánta antelación debo hacer un pedido para una boda?",
    "made by hand,": "Hecho a mano,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Un ramo artesanal entregado cada semana. Selección estacional, curada por nuestros floristas.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Una pieza destacada por mes — más grande, más dramática, un verdadero punto focal para tu hogar.",
    "order": "Ordenar",
    "our parisian studio": "Nuestro taller parisino",
    "peonies, tulipes, and garden roses in blush and cream.": "Peonías, tulipanes y rosas de jardín en rosa y crema.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Composiciones bellas y respetuosas para las ceremonias. Trabajamos directamente con las familias y las funerarias, con delicadeza.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Ramos de temporada, seleccionados a mano, entregados en su puerta a tiempo. Pausa o cancela en cualquier momento.",
    "seasonal story card": "Tarjeta de historia estacional",
    "shop subscriptions": "Suscripciones de tienda",
    "single-variety hellebore and dried cotton stems in clean lines.": "Helleboro de variedad única y tallos de algodón secos en líneas limpias.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "Grandes composiciones entregadas en la puerta, o un taller donde cada uno compone su ramo: memorable en ambos casos.",
    "subscribe biweekly": "Suscripción quincenal",
    "subscribe monthly": "Suscripción mensual",
    "subscribe weekly": "Suscripción semanal",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Girasoles, dalias, lavanda y exuberantes rosas de jardín en su mejor momento.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Girasoles, lavanda y dalias doradas en abundancia cálida.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulipanes, peonías, ranúnculos y flores de cerezo — la temporada de nuevos comienzos.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Dos ramos al mes: el ritmo justo para quien ama las flores sin querer atarse.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Trabajamos siempre que podemos con pequeños productores franceses, elegimos la flor de temporada frente a la importada y componemos todo a mano: de un solo tallo a un arco de boda.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Entrega semanal del arreglo estacional. He sido suscriptor durante 14 meses y nunca se han repetido. Cada semana es una pequeña sorpresa.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Flores de oficina semanales, instalaciones de eventos para lanzamientos de productos, salas de exposición y galas. Facturado mensualmente, totalmente gestionado.",
    "what areas do you deliver to?": "¿A qué áreas entregan?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Amaryllis blanca, heléboros, pino y el rojo profundo de las bayas de invierno.",
    "with intention.": "Con intención.",
    "workshop from": "Taller desde",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Sí. Puedes pausar hasta 4 semanas al año o cancelar en cualquier momento con una semana de aviso. Sin penalizaciones, sin preguntas.",
  },
  de: {
    "blossom drift": "Blütenflug",
    "seasonal collections": "Saisonale Kollektionen",
    "nature's calendar": "Der Kalender der Natur",
    "spring": "Frühling",
    "summer": "Sommer",
    "autumn": "Herbst",
    "winter": "Winter",
    "green awakening": "Grünes Erwachen",
    "weddings": "Hochzeiten",
    "funerals & tribute": "Trauerfeiern und Gedenken",
    "birthdays & events": "Geburtstage und Feiern",
    "corporate": "Unternehmen",
    "session length": "Dauer des Workshops",
    "max per group": "Personen maximal",
    "weekly": "Wöchentlich",
    "public sessions": "Offene Workshops",
    "wedding": "Hochzeit",
    "workshop": "Workshop",
    "monthly sub": "Monatsabo",
    "bouquet subscriptions": "Blumenabos",
    "always fresh. never repeated.": "Immer frisch. Nie zweimal gleich.",
    "per week": "pro Woche",
    "per month": "pro Monat",
    "seasonal arrangement": "Saisonales Gesteck",
    "free delivery paris": "Kostenlose Lieferung in Paris",
    "kraft wrapping + ribbon": "Kraftpapier und Band",
    "care card": "Pflegekarte",
    "2 seasonal arrangements": "Zwei saisonale Gestecke",
    "choice of style": "Stil nach Wahl",
    "care card + seasonal note": "Pflegekarte und Saisonnotiz",
    "1 large seasonal piece": "Ein großes Saisonstück",
    "statement composition": "Blickfang-Komposition",
    "hand-crafted seasonal arrangements, botanical bouquet subscriptions, and wedding floral direction from our parisian studio.": "Handgefertigte Saisongestecke, Abonnements botanischer Sträuße und florale Hochzeitsleitung, aus unserem Pariser Atelier.",
    "was born from a simple belief: flowers shouldn't be an afterthought. founded in 2014 by florist amélie rousseau, our studio in the 11th arrondissement has become a gathering place for people who care about natural beauty.": "entstand aus einer einfachen Überzeugung: Blumen dürfen kein nachträglicher Einfall sein. 2014 von der Floristin Amélie Rousseau gegründet, ist das Atelier im 11. Arrondissement ein Treffpunkt für alle geworden, denen natürliche Schönheit wichtig ist.",
    "pétales & co did our entire wedding — 18 arrangements, 4 arches, bridal party bouquets. every single piece was more beautiful than i imagined. they understood our vision perfectly.": "Sie haben unsere gesamte Hochzeit gemacht — 18 Gestecke, 4 Bögen, die Sträuße der Hochzeitsgesellschaft. Jedes Stück war schöner, als ich es mir vorgestellt hatte. Sie hatten genau verstanden, was wir wollten.",
    "i have a monthly subscription for my law office lobby. the team selects seasonally and the arrangements always receive comments from clients. it has genuinely changed the feel of the space.": "Ich habe ein Monatsabo für den Empfang meiner Kanzlei. Das Team wählt nach Saison, und die Gestecke werden von Mandanten immer kommentiert. Es hat die Atmosphäre wirklich verändert.",
    "we did the bouquet workshop for my sister's birthday. eight of us, two hours, incredible instruction and a gorgeous takeaway. the best afternoon we've had together in years.": "Wir haben den Strauß-Workshop zum Geburtstag meiner Schwester gemacht. Acht Leute, zwei Stunden, großartige Anleitung und ein Strauß zum Mitnehmen. Der schönste gemeinsame Nachmittag seit Jahren.",
    "we deliver within paris and the île-de-france region. paris deliveries are free for all subscriptions. île-de-france deliveries have a €12 surcharge for one-off orders — free for monthly subscribers.": "Wir liefern in Paris und in der Île-de-France. Innerhalb von Paris ist die Lieferung für alle Abos kostenlos. In der Île-de-France kommen 12 € für Einzelbestellungen hinzu — für Monatsabonnenten kostenlos.",
    "absolutely. at checkout or when setting up a subscription, leave your preferences. we'll do our best to honour them subject to seasonal availability. some flowers are simply unavailable out of season — part of what makes them special.": "Selbstverständlich. Geben Sie beim Bestellen oder beim Einrichten des Abos Ihre Wünsche an. Wir richten uns danach, soweit die Saison es zulässt: Manche Blumen gibt es außerhalb ihrer Zeit schlicht nicht — auch das macht ihren Wert aus.",
    "we recommend 3–6 months for weddings. summer dates (june–september) are extremely popular and book out 6+ months ahead. contact us as early as possible and we'll confirm availability.": "Für Hochzeiten empfehlen wir drei bis sechs Monate. Sommertermine (Juni bis September) sind sehr gefragt und oft über sechs Monate im Voraus vergeben. Schreiben Sie uns früh, wir bestätigen die Verfügbarkeit.",
    "yes — we run weekly public workshops at our studio (€65/person, 2 hours, includes materials and takeaway bouquet) and private group bookings for up to 12 people. email us or book via our website.": "Ja — wöchentlich offene Workshops (65 € pro Person, zwei Stunden, Material und Strauß inklusive) sowie private Gruppen bis zwölf Personen. Schreiben Sie uns oder buchen Sie online.",
    "for in-stock arrangements ordered before 10h, we offer same-day delivery in paris (€18 express fee). for custom orders or workshop bookings, advance notice is required.": "Für vorrätige Gestecke, die vor 10 Uhr bestellt werden, ist Lieferung am selben Tag in Paris möglich (18 € Express). Für Sonderanfertigungen oder Workshops ist Vorlauf nötig.",
    "florist home": "Startseite",
    "hand-crafted floral arrangements, seasonal subscriptions, and wedding floral direction.": "Handgefertigte Blumengestecke, Saisonabos und florale Hochzeitsleitung.",
    "birds of paradise, proteas, and tropical foliage statement piece.": "Paradiesvögel, Proteas und tropisches Laub als Blickfang.",
    "book a workshop": "Buchen Sie einen Workshop",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Hochzeitssträuße, Zeremonie-Installationen, Empfangszentren und vollständige florale Anleitung vom ersten Briefing bis zum letzten Blatt am Tag.",
    "browse occasions": "Anlässe entdecken",
    "can i pause or cancel my subscription?": "Kann ich mein Abonnement pausieren oder kündigen?",
    "can i request specific flowers or colours?": "Kann ich bestimmte Blumen oder Farben anfordern?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Kirschblütenstiele mit zarten Süßerbsen und Freesien.",
    "clients satisfaits": "zufriedene Kunden",
    "do you do same-day delivery?": "Bieten Sie Same-Day-Lieferungen an?",
    "do you offer workshops?": "Bieten Sie Workshops an?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eukalyptus, Farne und saisonales Grün mit weißen Blüten.",
    "flowers for every chapter": "Blumen für jedes Kapitel",
    "for every": "Für jeden",
    "free delivery île-de-france": "Kostenlose Lieferung in der Île-de-France",
    "free delivery nantes": "Kostenlose Lieferung in Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "Von der fröhlichsten Feier bis zum zartesten Abschied — wir sind für jeden Anlass da, der zählt.",
    "garden roses in deep coral and orange with jasmine vine.": "Gartenrosen in tiefem Koralle und Orange mit Jasminranke.",
    "how far in advance should i order for a wedding?": "Wie weit im Voraus sollte ich für eine Hochzeit bestellen?",
    "made by hand,": "Handgemacht,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Ein handwerklicher Strauß wird jede Woche geliefert. Saisonale Auswahl, kuratiert von unseren Floristen.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Ein Statement-Stück pro Monat — größer, dramatischer, ein echter Blickfang für Ihr Zuhause.",
    "order": "Bestellen",
    "our parisian studio": "Unser Pariser Atelier",
    "peonies, tulipes, and garden roses in blush and cream.": "Pfingstrosen, Tulpen und Gartenrosen in Blush und Creme.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Schöne, würdevolle Gestecke für Trauerfeiern. Wir arbeiten einfühlsam direkt mit Familien und Bestattern.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Saisonale Sträuße, handverlesen, pünktlich zu Ihnen nach Hause geliefert. Pausieren oder jederzeit kündigen.",
    "seasonal story card": "Saisonale Geschichtskarte",
    "shop subscriptions": "Shop-Abonnements",
    "single-variety hellebore and dried cotton stems in clean lines.": "Einzelne Helleborus-Sorte und getrocknete Baumwollstängel in klaren Linien.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "Große Arrangements bis vor die Tür geliefert, oder ein Workshop, bei dem jeder seinen Strauß bindet — beides bleibt in Erinnerung.",
    "subscribe biweekly": "Zweiwöchentliches Abo",
    "subscribe monthly": "Monatliches Abo",
    "subscribe weekly": "Wöchentliches Abo",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Sonnenblumen, Dahlien, Lavendel und üppige Gartenrosen auf ihrem Höhepunkt.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Sonnenblumen, Lavendel und goldene Dahlien in warmer Fülle.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulpen, Pfingstrosen, Ranunkeln und Kirschblüten — die Saison frischer Anfänge.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Zwei Sträuße im Monat — der richtige Rhythmus für alle, die Blumen lieben, sich aber nicht binden wollen.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Wir arbeiten, wo möglich, mit kleinen französischen Gärtnereien, wählen Saisonblumen statt Importware und binden alles von Hand — von der einzelnen Blüte bis zum Hochzeitsbogen.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Wöchentliche Lieferung des saisonalen Arrangements. Ich bin seit 14 Monaten Abonnent und sie haben sich nie wiederholt. Jede Woche ist eine kleine Überraschung.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Wöchentliche Büroblumen, Veranstaltungsinstallationen für Produkteinführungen, Showrooms und Galas. Monatlich in Rechnung gestellt, vollständig verwaltet.",
    "what areas do you deliver to?": "In welchen Bereichen liefern Sie?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Weiße Amaryllis, Helleborus, Kiefer und das tiefrote Winterbeeren.",
    "with intention.": "Mit Absicht.",
    "workshop from": "Workshop ab",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Ja. Sie können bis zu 4 Wochen pro Jahr pausieren oder jederzeit mit einer Woche Vorankündigung kündigen. Keine Strafen, keine Fragen.",
  },
  pt: {
    "blossom drift": "Voo floral",
    "seasonal collections": "Coleções de época",
    "nature's calendar": "O calendário da natureza",
    "spring": "Primavera",
    "summer": "Verão",
    "autumn": "Outono",
    "winter": "Inverno",
    "green awakening": "Despertar vegetal",
    "weddings": "Casamentos",
    "funerals & tribute": "Funerais e homenagens",
    "birthdays & events": "Aniversários e eventos",
    "corporate": "Empresas",
    "session length": "Duração do ateliê",
    "max per group": "Pessoas no máximo",
    "weekly": "Todas as semanas",
    "public sessions": "Ateliês abertos a todos",
    "wedding": "Casamento",
    "workshop": "Ateliê",
    "monthly sub": "Assinatura mensal",
    "bouquet subscriptions": "Assinaturas de ramos",
    "always fresh. never repeated.": "Sempre frescos. Nunca duas vezes iguais.",
    "per week": "por semana",
    "per month": "por mês",
    "seasonal arrangement": "Composição de época",
    "free delivery paris": "Entrega gratuita em Paris",
    "kraft wrapping + ribbon": "Embalagem kraft e fita",
    "care card": "Cartão de cuidados",
    "2 seasonal arrangements": "Duas composições de época",
    "choice of style": "Estilo à escolha",
    "care card + seasonal note": "Cartão de cuidados e nota de época",
    "1 large seasonal piece": "Uma grande peça de época",
    "statement composition": "Composição principal",
    "hand-crafted seasonal arrangements, botanical bouquet subscriptions, and wedding floral direction from our parisian studio.": "Composições de época feitas à mão, assinaturas de ramos botânicos e direção floral de casamentos, a partir do nosso atelier parisiense.",
    "was born from a simple belief: flowers shouldn't be an afterthought. founded in 2014 by florist amélie rousseau, our studio in the 11th arrondissement has become a gathering place for people who care about natural beauty.": "nasceu de uma convicção simples: as flores nunca deviam ser uma ideia de última hora. Fundado em 2014 pela florista Amélie Rousseau, o atelier do 11.º tornou-se ponto de encontro para quem preza a beleza natural.",
    "pétales & co did our entire wedding — 18 arrangements, 4 arches, bridal party bouquets. every single piece was more beautiful than i imagined. they understood our vision perfectly.": "Fizeram todo o nosso casamento — 18 composições, 4 arcos, os ramos do cortejo. Cada peça superou o que imaginava. Perceberam perfeitamente o que queríamos.",
    "i have a monthly subscription for my law office lobby. the team selects seasonally and the arrangements always receive comments from clients. it has genuinely changed the feel of the space.": "Tenho uma assinatura mensal para a receção do meu escritório. A equipa escolhe conforme a época e as composições fazem sempre os clientes comentar. Mudou mesmo o ambiente do espaço.",
    "we did the bouquet workshop for my sister's birthday. eight of us, two hours, incredible instruction and a gorgeous takeaway. the best afternoon we've had together in years.": "Fizemos o workshop de ramos no aniversário da minha irmã. Oito pessoas, duas horas, uma orientação excelente e um ramo para levar. A melhor tarde juntos em anos.",
    "we deliver within paris and the île-de-france region. paris deliveries are free for all subscriptions. île-de-france deliveries have a €12 surcharge for one-off orders — free for monthly subscribers.": "Entregamos em Paris e na Île-de-France. A entrega é gratuita em Paris para todas as assinaturas. Na Île-de-France acrescem 12 € para encomendas pontuais — grátis para assinantes mensais.",
    "absolutely. at checkout or when setting up a subscription, leave your preferences. we'll do our best to honour them subject to seasonal availability. some flowers are simply unavailable out of season — part of what makes them special.": "Com certeza. Ao encomendar ou ao criar uma assinatura, indique as suas preferências. Faremos o possível conforme a época: algumas flores simplesmente não existem fora de estação — é também o que lhes dá valor.",
    "we recommend 3–6 months for weddings. summer dates (june–september) are extremely popular and book out 6+ months ahead. contact us as early as possible and we'll confirm availability.": "Aconselhamos três a seis meses para um casamento. As datas de verão (junho a setembro) esgotam muito depressa, muitas vezes com mais de seis meses. Escreva-nos cedo e confirmamos a disponibilidade.",
    "yes — we run weekly public workshops at our studio (€65/person, 2 hours, includes materials and takeaway bouquet) and private group bookings for up to 12 people. email us or book via our website.": "Sim — todas as semanas há workshops abertos a todos (65 € por pessoa, duas horas, material e ramo incluídos) e workshops privados até doze pessoas. Escreva-nos ou reserve online.",
    "for in-stock arrangements ordered before 10h, we offer same-day delivery in paris (€18 express fee). for custom orders or workshop bookings, advance notice is required.": "Para composições em stock encomendadas antes das 10 h, a entrega no próprio dia é possível em Paris (18 € expresso). Para encomendas à medida ou workshops, é preciso avisar com antecedência.",
    "florist home": "Início",
    "hand-crafted floral arrangements, seasonal subscriptions, and wedding floral direction.": "Composições florais feitas à mão, assinaturas de época e direção floral de casamentos.",
    "birds of paradise, proteas, and tropical foliage statement piece.": "Aves do paraíso, proteas e peça central de folhagem tropical.",
    "book a workshop": "Reserve um workshop",
    "bridal bouquets, ceremony installations, reception centrepieces, and full floral direction from initial brief to last petal on the day.": "Buquês de noiva, instalações de cerimônia, centros de mesa para a recepção e direção floral completa desde o briefing inicial até a última pétala do dia.",
    "browse occasions": "Ver ocasiões",
    "can i pause or cancel my subscription?": "Posso pausar ou cancelar a minha assinatura?",
    "can i request specific flowers or colours?": "Posso solicitar flores ou cores específicas?",
    "cherry blossom stems with delicate sweet peas and freesia.": "Talos de flores de cerejeira com delicadas ervilhas-doces e fresias.",
    "clients satisfaits": "clientes satisfeitos",
    "do you do same-day delivery?": "Fazem entregas no mesmo dia?",
    "do you offer workshops?": "Oferecem workshops?",
    "eucalyptus, ferns, and seasonal greens with white blooms.": "Eucalipto, fetos e verdes sazonais com flores brancas.",
    "flowers for every chapter": "Flores para cada capítulo",
    "for every": "Para cada",
    "free delivery île-de-france": "Entrega grátis na Île-de-France",
    "free delivery nantes": "Entrega grátis em Nantes",
    "from the most joyful celebration to the most tender farewell — we're here for every occasion that matters.": "Da celebração mais alegre à despedida mais terna — estamos para cada ocasião que importa.",
    "garden roses in deep coral and orange with jasmine vine.": "Rosas de jardim em coral profundo e laranja com trepadeira de jasmim.",
    "how far in advance should i order for a wedding?": "Com quanto tempo de antecedência devo fazer um pedido para um casamento?",
    "made by hand,": "Feito à mão,",
    "one artisan bouquet delivered each week. seasonal selection, curated by our florists.": "Um bouquet artesanal entregue a cada semana. Seleção sazonal, curada pelos nossos floristas.",
    "one statement piece per month — larger, more dramatic, a real focal point for your home.": "Uma peça de destaque por mês — maior, mais dramática, um verdadeiro ponto focal para a sua casa.",
    "order": "Pedir",
    "our parisian studio": "O nosso atelier parisiense",
    "peonies, tulipes, and garden roses in blush and cream.": "Peónias, tulipas e rosas de jardim em rosa e creme.",
    "respectful, beautiful arrangements for memorial services. we work directly with families and funeral homes with sensitivity and care.": "Composições belas e respeitosas para as cerimónias. Trabalhamos diretamente com as famílias e as agências funerárias, com delicadeza.",
    "seasonal bouquets, curated by hand, delivered to your door on schedule. pause or cancel anytime.": "Arranjos sazonais, selecionados à mão, entregues à sua porta pontualmente. Pause ou cancele a qualquer momento.",
    "seasonal story card": "Cartão de história sazonal",
    "shop subscriptions": "Assinaturas de loja",
    "single-variety hellebore and dried cotton stems in clean lines.": "Helleboro de variedade única e hastes de algodão secas em linhas limpas.",
    "statement arrangements delivered directly to the door, or a workshop where guests create their own bouquet — memorable both ways.": "Grandes composições entregues à porta, ou um workshop onde cada um compõe o seu ramo — memorável nos dois casos.",
    "subscribe biweekly": "Assinatura quinzenal",
    "subscribe monthly": "Assinatura mensal",
    "subscribe weekly": "Assinatura semanal",
    "sunflowers, dahlias, lavender, and lush garden roses at their peak.": "Girassóis, dálias, lavanda e exuberantes rosas de jardim no seu auge.",
    "sunflowers, lavender, and golden dahlias in warm abundance.": "Girassóis, lavanda e dálias douradas em abundância quente.",
    "tulips, peonies, ranunculus, and cherry blossom — the season of fresh beginnings.": "Tulipas, peónias, ranúnculos e flores de cerejeira — a temporada de novos começos.",
    "two bouquets per month — the perfect rhythm for those who love flowers but want flexibility.": "Dois ramos por mês — o ritmo certo para quem gosta de flores sem se querer prender.",
    "we work with small french growers wherever possible, choose seasonal flowers over imported blooms, and make every arrangement by hand — from a single stem to a wedding arch.": "Trabalhamos sempre que possível com pequenos produtores franceses, escolhemos a flor da época em vez da importada e compomos tudo à mão — de uma única haste a um arco de casamento.",
    "weekly delivery of the seasonal arrangement. i've been a subscriber for 14 months and they have never repeated themselves. each week is a small surprise.": "Entrega semanal do arranjo sazonal. Sou assinante há 14 meses e eles nunca se repetiram. Cada semana é uma pequena surpresa.",
    "weekly office flowers, event installations for product launches, showrooms, and galas. invoiced monthly, fully managed.": "Flores de escritório semanais, instalações de eventos para lançamentos de produtos, showrooms e galas. Faturado mensalmente, totalmente gerido.",
    "what areas do you deliver to?": "A que áreas entregam?",
    "white amaryllis, hellebores, pine, and the deep red of winterberries.": "Amaryllis branca, heléboros, pinheiro e o vermelho profundo das bagas de inverno.",
    "with intention.": "Com intenção.",
    "workshop from": "Workshop a partir de",
    "yes. you can pause for up to 4 weeks per year or cancel anytime with one week's notice. no penalties, no questions.": "Sim. Pode pausar até 4 semanas por ano ou cancelar a qualquer momento com uma semana de antecedência. Sem penalizações, sem perguntas.",
  },
};
