/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "equipment": "Équipement",
    "enquiry": "Nous écrire",
    "highest": "Les plus hauts",
    "summits": "sommets",
    "elite art conservation & private registry": "Conservation d'œuvres et registre privé",
    "collector vault": "Coffre du collectionneur",
    "materials": "Matériaux",
    "specs": "Caractéristiques",
    "applications": "Applications",
    "research": "Recherche",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Soie au graphène. Maille bioluminescente CRISPR. Laine à mémoire de forme en nitinol. Nous concevons des textiles au croisement de la science des matériaux, de la biotechnologie et de la haute couture.",
    "core directive": "Directive fondamentale",
    "uptime protocol": "Protocole de disponibilité",
    "expandable storage": "Stockage extensible",
    "provision node": "Provisionner un nœud",
    "product": "Produit",
    "marketing": "Marketing",
    "properties": "Nos biens",
    "market": "Le marché",
    "neighborhoods": "Les quartiers",
    "establishment": "Fondation",
    "gold": "Or",
    "time": "Le temps",
    "newsletter": "Lettre d'information",
    "planning": "Le planning",
    "heritage": "Héritage",
    "centuries of provance": "Siècles de Provence",
    "explore the repository": "Explorez le dépôt",
    "recovered from the salt mines of altaussee.": "Retrouvé dans les mines de sel d'Altaussee.",
    "reliquary of the silent order": "Reliquaire de l'Ordre Silencieux",
    "request acquisition handshake": "Demander la poignée de main d'acquisition",
    "request lab analysis log": "Demander le journal d'analyse de laboratoire",
    "secured by the ivory archive for conservation.": "Mis en sûreté pour conservation.",
    "the mandate": "Le mandat",
    "the obsidian triptych": "Le Triptyque d'Obsidienne",
    "the renaissance veil": "Le Voile de la Renaissance",
    "the repository.": "Le dépôt.",
    "the royal": "Le royal",
    "veduta of the lost city": "Veduta de la Ville Perdue",
  },
  es: {
    "equipment": "Equipamiento",
    "enquiry": "Escríbanos",
    "highest": "Las más altas",
    "summits": "cumbres",
    "elite art conservation & private registry": "Conservación de obras y registro privado",
    "collector vault": "Cámara del coleccionista",
    "materials": "Materiales",
    "specs": "Características",
    "applications": "Aplicaciones",
    "research": "Investigación",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda con grafeno. Malla bioluminiscente CRISPR. Lana con memoria de forma de nitinol. Diseñamos textiles en el cruce de la ciencia de materiales, la biotecnología y la alta costura.",
    "core directive": "Directiva fundamental",
    "uptime protocol": "Protocolo de disponibilidad",
    "expandable storage": "Almacenamiento ampliable",
    "provision node": "Aprovisionar un nodo",
    "product": "Producto",
    "marketing": "Marketing",
    "properties": "Nuestros inmuebles",
    "market": "El mercado",
    "neighborhoods": "Los barrios",
    "establishment": "Fundación",
    "gold": "Oro",
    "time": "El tiempo",
    "newsletter": "Boletín",
    "planning": "El horario",
    "heritage": "Herencia",
    "centuries of provance": "Siglos de Provenza",
    "explore the repository": "Explora el repositorio",
    "recovered from the salt mines of altaussee.": "Recuperado en las minas de sal de Altaussee.",
    "reliquary of the silent order": "Reliquario de la Orden Silenciosa",
    "request acquisition handshake": "Solicitar el apretón de manos de adquisición",
    "request lab analysis log": "Solicitar el registro de análisis de laboratorio",
    "secured by the ivory archive for conservation.": "Puesto a resguardo para su conservación.",
    "the mandate": "El mandato",
    "the obsidian triptych": "El Tríptico de Obsidiana",
    "the renaissance veil": "El Velo del Renacimiento",
    "the repository.": "El depósito.",
    "the royal": "El real",
    "veduta of the lost city": "Veduta de la Ciudad Perdida",
  },
  de: {
    "equipment": "Ausrüstung",
    "enquiry": "Anfrage",
    "highest": "Die höchsten",
    "summits": "Gipfel",
    "elite art conservation & private registry": "Kunstkonservierung und privates Register",
    "collector vault": "Sammlertresor",
    "materials": "Werkstoffe",
    "specs": "Kenndaten",
    "applications": "Anwendungen",
    "research": "Forschung",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seide mit Graphen. Biolumineszentes CRISPR-Gewebe. Formgedächtniswolle aus Nitinol. Wir entwickeln Textilien an der Schnittstelle von Materialwissenschaft, Biotechnologie und Haute Couture.",
    "core directive": "Grundsatzdirektive",
    "uptime protocol": "Verfügbarkeitsprotokoll",
    "expandable storage": "Erweiterbarer Speicher",
    "provision node": "Knoten bereitstellen",
    "product": "Produkt",
    "marketing": "Marketing",
    "properties": "Unsere Objekte",
    "market": "Der Markt",
    "neighborhoods": "Die Viertel",
    "establishment": "Gründung",
    "gold": "Gold",
    "time": "Die Zeit",
    "newsletter": "Newsletter",
    "planning": "Der Stundenplan",
    "heritage": "Erbe",
    "centuries of provance": "Jahrhunderte der Provence",
    "explore the repository": "Erkunden Sie das Repository",
    "recovered from the salt mines of altaussee.": "Aus den Salzbergwerken von Altaussee geborgen.",
    "reliquary of the silent order": "Reliquiar des Stillen Ordens",
    "request acquisition handshake": "Erwerbs-Handschlag anfordern",
    "request lab analysis log": "Lab-Analyseprotokoll anfordern",
    "secured by the ivory archive for conservation.": "Zur Erhaltung in Verwahrung genommen.",
    "the mandate": "Der Auftrag",
    "the obsidian triptych": "Das Obsidian-Triptychon",
    "the renaissance veil": "Der Renaissance-Schleier",
    "the repository.": "Das Depot.",
    "the royal": "Das Königliche",
    "veduta of the lost city": "Veduta der Verlorenen Stadt",
  },
  pt: {
    "equipment": "Equipamento",
    "enquiry": "Escreva-nos",
    "highest": "Os mais altos",
    "summits": "cumes",
    "elite art conservation & private registry": "Conservação de obras e registo privado",
    "collector vault": "Cofre do colecionador",
    "materials": "Materiais",
    "specs": "Características",
    "applications": "Aplicações",
    "research": "Investigação",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda com grafeno. Malha bioluminescente CRISPR. Lã com memória de forma em nitinol. Concebemos têxteis no cruzamento da ciência dos materiais, da biotecnologia e da alta-costura.",
    "core directive": "Diretiva fundamental",
    "uptime protocol": "Protocolo de disponibilidade",
    "expandable storage": "Armazenamento expansível",
    "provision node": "Aprovisionar um nó",
    "product": "Produto",
    "marketing": "Marketing",
    "properties": "Os nossos imóveis",
    "market": "O mercado",
    "neighborhoods": "Os bairros",
    "establishment": "Fundação",
    "gold": "Ouro",
    "time": "O tempo",
    "newsletter": "Boletim",
    "planning": "O horário",
    "heritage": "Herança",
    "centuries of provance": "Séculos de Provença",
    "explore the repository": "Explore o repositório",
    "recovered from the salt mines of altaussee.": "Recuperado nas minas de sal de Altaussee.",
    "reliquary of the silent order": "Relicário da Ordem Silenciosa",
    "request acquisition handshake": "Solicitar a negociação de aquisição",
    "request lab analysis log": "Solicitar o registo de análise de laboratório",
    "secured by the ivory archive for conservation.": "Posto em segurança para conservação.",
    "the mandate": "O mandato",
    "the obsidian triptych": "O Tríptico de Obsidiana",
    "the renaissance veil": "O Véu da Renascença",
    "the repository.": "O depósito.",
    "the royal": "O real",
    "veduta of the lost city": "Veduta da Cidade Perdida",
  },
};
