/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "from 3 400+ reviews": "sur plus de 3 400 avis",
    "novaplatform runs on 42 edge nodes worldwide. every api request is routed to the nearest region automatically, eliminating cold starts and cross-continental latency. p99 response time is under 80ms — anywhere on earth.": "La plateforme tourne sur 42 nœuds répartis dans le monde. Chaque appel d'API part automatiquement vers la région la plus proche : plus de démarrage à froid, plus de latence transatlantique. Le temps de réponse P99 reste sous 80 ms, où que l'on soit.",
    "real-time performance dashboards with 1-second granularity": "Tableaux de bord de performance en temps réel, à la seconde près",
    "we migrated from three separate tools to novaplatform over a single weekend. our engineering velocity doubled in the first month, and the on-call burden dropped by 70%. i wish we had switched sooner.": "Nous avons quitté trois outils séparés pour cette plateforme en un week-end. Notre vitesse de développement a doublé le premier mois, et les astreintes ont chuté de 70 %. On aurait dû basculer plus tôt.",
    "the analytics dashboard surfaced a 2.3m € revenue opportunity in our first week that we had completely missed. the ai-powered anomaly detection is not a marketing claim — it genuinely works.": "Le tableau de bord a fait apparaître, dès la première semaine, 2,3 M€ de chiffre d'affaires qui nous échappaient complètement. La détection d'anomalies n'est pas un argument marketing : elle fonctionne.",
    "best developer experience i have encountered in 15 years of writing software. the api documentation is genuinely a work of art, and the typescript sdk is the best i have ever used — period.": "La meilleure expérience de développement que j'aie connue en quinze ans de métier. La documentation de l'API est une œuvre en soi, et le SDK TypeScript est le meilleur que j'aie utilisé.",
    "we process 180m € in transactions per month through novaplatform's payment orchestration layer. in 18 months of production, we have had zero data incidents and three nines of uptime. that's the number that matters.": "Nous traitons 180 M€ de transactions par mois via la couche de paiement. En dix-huit mois de production : zéro incident de données et une disponibilité à trois neuf. C'est le chiffre qui compte.",
    "the branch preview environment feature alone saved us two engineering hires. our qa cycle went from 4 days to 6 hours, and our deployment frequency tripled within the first quarter. transformative.": "La seule fonction d'environnement de prévisualisation par branche nous a évité deux embauches. Notre cycle de recette est passé de quatre jours à six heures, et nos mises en production ont triplé dès le premier trimestre.",
    "join 14 200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Rejoignez plus de 14 200 équipes qui livrent plus vite. Formule gratuite à vie — sans carte bancaire.",
    "get started — it's free": "Commencer — c'est gratuit",
    "+47% this week": "+47 % cette semaine",
    "1 team member": "1 membre de l'équipe",
    "14-day pro trial": "Essai Pro de 14 jours",
    "all systems go": "Tous les systèmes sont opérationnels",
    "average worldwide": "Moyenne mondiale",
    "built from the ground up for modern teams who refuse to compromise on speed, security, or developer experience.": "Construit de A à Z pour des équipes modernes qui refusent de faire des compromis sur la vitesse, la sécurité ou l'expérience des développeurs.",
    "can i migrate from my current stack without downtime?": "Puis-je migrer depuis ma pile actuelle sans temps d'arrêt ?",
    "connect your stack": "Reliez vos outils",
    "data processed": "Données traitées",
    "deploy time": "Temps de déploiement",
    "deploy to production instantly. our ai automatically optimizes latency, cost, and scaling as you grow.": "Déployez en production instantanément. Notre IA optimise automatiquement la latence, le coût et l'évolutivité à mesure que vous grandissez.",
    "do you offer a startup programme?": "Proposez-vous un programme pour startups ?",
    "drag-and-drop workflow builder for non-technical teams. full code editor with autocomplete for engineers.": "Un constructeur de flux par glisser-déposer pour les équipes non techniques. Un éditeur de code complet, avec autocomplétion, pour les développeurs.",
    "everything in pro": "Tout dans Pro",
    "for organizations that demand the best — and can justify it.": "Pour les organisations qui exigent le meilleur — et peuvent le justifier.",
    "for side projects, prototypes, and early-stage products.": "Pour des projets secondaires, des prototypes et des produits en phase de démarrage.",
    "from 3,400+ reviews": "sur plus de 3 400 avis",
    "get started — it's free": "Commencez — c'est gratuit",
    "head of product, arkive": "Responsable produit, Arkive",
    "how does enterprise pricing work?": "Comment fonctionne la tarification entreprise ?",
    "how does the 14-day trial work?": "Comment fonctionne l'essai de 14 jours ?",
    "integrate in minutes with 200+ native connectors. rest, graphql, webhooks, or our sdks — your choice.": "Intégrez en quelques minutes avec plus de 200 connecteurs natifs. REST, GraphQL, webhooks ou nos SDK — à vous de choisir.",
    "is my data portable? what happens if i leave?": "Mes données sont-elles portables ? Que se passe-t-il si je pars ?",
    "join 14,200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Rejoignez plus de 14 200 équipes qui livrent plus rapidement avec NovaPlatform. Plan gratuit à vie — aucune carte de crédit requise.",
    "loved by": "Aimé par",
    "no credit card required for starter. all plans include a 30-day money-back guarantee.": "Aucune carte de crédit requise pour Starter. Tous les plans incluent une garantie de remboursement de 30 jours.",
    "no sign-up required · full product walkthrough": "Sans inscription · Démonstration complète du produit",
    "nothing you don't.": "Rien que vous ne pouvez pas.",
    "on g2": "sur G2",
    "on-premises deployment option": "Option de déploiement sur site",
    "ready to build the": "Prêt à bâtir le",
    "revenue processed": "Revenus traités",
    "security breaches in 6 years": "Violations de sécurité en 6 ans",
    "start 14-day trial": "Commencez l'essai de 14 jours",
    "start building for free": "Commencer gratuitement",
    "start for free": "Commencer gratuitement",
    "start free,": "Commencer gratuitement,",
    "talk to sales": "Parlez à l'équipe commerciale",
    "the all-in-one platform for modern engineering teams. build, deploy, and scale without limits.": "La plateforme tout-en-un des équipes techniques d'aujourd'hui. Construire, déployer, monter en charge sans limite.",
    "the all-in-one platform that replaces your entire infrastructure toolkit. build, deploy, and scale to millions of users without changing your workflow.": "La plateforme tout-en-un qui remplace votre boîte à outils d'infrastructure. Construisez, déployez et évoluez vers des millions d'utilisateurs sans changer votre flux de travail.",
    "three steps to": "Trois étapes vers",
    "trusted by teams at the world's best companies": "Fiable par des équipes des meilleures entreprises du monde",
    "up to 15 team members": "Jusqu'à 15 membres de l'équipe",
    "up to 3 projects": "Jusqu'à 3 projets",
    "uptime today": "Temps de disponibilité aujourd'hui",
    "watch demo (3 min)": "Regarder la démo (3 min)",
    "what does '99.99% uptime sla' mean in practice?": "Que signifie 'SLA de disponibilité de 99,99%' en pratique ?",
    "what regions does novaplatform operate in?": "Dans quelles régions NovaPlatform opère-t-elle ?",
  },
  es: {
    "from 3 400+ reviews": "sobre más de 3 400 opiniones",
    "novaplatform runs on 42 edge nodes worldwide. every api request is routed to the nearest region automatically, eliminating cold starts and cross-continental latency. p99 response time is under 80ms — anywhere on earth.": "La plataforma funciona en 42 nodos repartidos por el mundo. Cada llamada a la API va automáticamente a la región más cercana: sin arranques en frío ni latencia transatlántica. El tiempo de respuesta P99 se mantiene bajo 80 ms, esté donde esté.",
    "real-time performance dashboards with 1-second granularity": "Paneles de rendimiento en tiempo real, al segundo",
    "we migrated from three separate tools to novaplatform over a single weekend. our engineering velocity doubled in the first month, and the on-call burden dropped by 70%. i wish we had switched sooner.": "Dejamos tres herramientas separadas por esta plataforma en un fin de semana. Nuestra velocidad de desarrollo se duplicó el primer mes y las guardias cayeron un 70 %. Deberíamos haber cambiado antes.",
    "the analytics dashboard surfaced a 2.3m € revenue opportunity in our first week that we had completely missed. the ai-powered anomaly detection is not a marketing claim — it genuinely works.": "El panel hizo aparecer, ya en la primera semana, 2,3 M€ de facturación que se nos escapaban por completo. La detección de anomalías no es un argumento de marketing: funciona.",
    "best developer experience i have encountered in 15 years of writing software. the api documentation is genuinely a work of art, and the typescript sdk is the best i have ever used — period.": "La mejor experiencia de desarrollo que he conocido en quince años de oficio. La documentación de la API es una obra en sí misma, y el SDK de TypeScript es el mejor que he usado.",
    "we process 180m € in transactions per month through novaplatform's payment orchestration layer. in 18 months of production, we have had zero data incidents and three nines of uptime. that's the number that matters.": "Procesamos 180 M€ de transacciones al mes por la capa de pagos. En dieciocho meses de producción: cero incidentes de datos y disponibilidad de tres nueves. Ese es el número que cuenta.",
    "the branch preview environment feature alone saved us two engineering hires. our qa cycle went from 4 days to 6 hours, and our deployment frequency tripled within the first quarter. transformative.": "Solo la función de entorno de vista previa por rama nos ahorró dos contrataciones. Nuestro ciclo de QA pasó de cuatro días a seis horas y los despliegues se triplicaron ya el primer trimestre.",
    "join 14 200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Únase a más de 14 200 equipos que entregan más rápido. Plan gratuito de por vida — sin tarjeta.",
    "get started — it's free": "Empezar — es gratis",
    "+47% this week": "+47 % esta semana",
    "1 team member": "1 miembro del equipo",
    "14-day pro trial": "Prueba Pro de 14 días",
    "all systems go": "Todos los sistemas en marcha",
    "average worldwide": "Promedio mundial",
    "built from the ground up for modern teams who refuse to compromise on speed, security, or developer experience.": "Construido desde cero para equipos modernos que se niegan a comprometer la velocidad, la seguridad o la experiencia del desarrollador.",
    "can i migrate from my current stack without downtime?": "¿Puedo migrar desde mi pila actual sin tiempo de inactividad?",
    "connect your stack": "Conecte sus herramientas",
    "data processed": "Datos procesados",
    "deploy time": "Tiempo de implementación",
    "deploy to production instantly. our ai automatically optimizes latency, cost, and scaling as you grow.": "Despliega en producción al instante. Nuestra IA optimiza automáticamente la latencia, el costo y la escalabilidad a medida que creces.",
    "do you offer a startup programme?": "¿Ofrecen un programa para startups?",
    "drag-and-drop workflow builder for non-technical teams. full code editor with autocomplete for engineers.": "Un constructor de flujos por arrastrar y soltar para equipos no técnicos. Un editor de código completo, con autocompletado, para los desarrolladores.",
    "everything in pro": "Todo en Pro",
    "for organizations that demand the best — and can justify it.": "Para organizaciones que exigen lo mejor — y pueden justificarlo.",
    "for side projects, prototypes, and early-stage products.": "Para proyectos secundarios, prototipos y productos en etapas tempranas.",
    "from 3,400+ reviews": "de más de 3 400 opiniones",
    "get started — it's free": "Empieza — es gratis",
    "head of product, arkive": "Jefe de Producto, Arkive",
    "how does enterprise pricing work?": "¿Cómo funciona la tarificación empresarial?",
    "how does the 14-day trial work?": "¿Cómo funciona la prueba de 14 días?",
    "integrate in minutes with 200+ native connectors. rest, graphql, webhooks, or our sdks — your choice.": "Integra en minutos con más de 200 conectores nativos. REST, GraphQL, webhooks o nuestros SDK: tú eliges.",
    "is my data portable? what happens if i leave?": "¿Son mis datos portátiles? ¿Qué pasa si me voy?",
    "join 14,200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Únete a más de 14,200 equipos que envían más rápido con NovaPlatform. Plan gratuito para siempre — no se requiere tarjeta de crédito.",
    "loved by": "Amado por",
    "no credit card required for starter. all plans include a 30-day money-back guarantee.": "No se requiere tarjeta de crédito para Starter. Todos los planes incluyen una garantía de devolución de dinero de 30 días.",
    "no sign-up required · full product walkthrough": "Sin registro · Recorrido completo del producto",
    "nothing you don't.": "Nada que no puedas.",
    "on g2": "en G2",
    "on-premises deployment option": "Opción de implementación local",
    "ready to build the": "Listo para construir el",
    "revenue processed": "Ingresos procesados",
    "security breaches in 6 years": "Violaciones de seguridad en 6 años",
    "start 14-day trial": "Comienza la prueba de 14 días",
    "start building for free": "Empezar gratis",
    "start for free": "Empezar gratis",
    "start free,": "Empezar gratis,",
    "talk to sales": "Habla con ventas",
    "the all-in-one platform for modern engineering teams. build, deploy, and scale without limits.": "La plataforma todo en uno para los equipos técnicos de hoy. Construir, desplegar y escalar sin límite.",
    "the all-in-one platform that replaces your entire infrastructure toolkit. build, deploy, and scale to millions of users without changing your workflow.": "La plataforma todo en uno que reemplaza toda tu caja de herramientas de infraestructura. Construye, despliega y escala a millones de usuarios sin cambiar tu flujo de trabajo.",
    "three steps to": "Tres pasos hacia",
    "trusted by teams at the world's best companies": "Confiado por equipos de las mejores empresas del mundo",
    "up to 15 team members": "Hasta 15 miembros del equipo",
    "up to 3 projects": "Hasta 3 proyectos",
    "uptime today": "Tiempo de actividad hoy",
    "watch demo (3 min)": "Ver demo (3 min)",
    "what does '99.99% uptime sla' mean in practice?": "¿Qué significa 'SLA de tiempo de actividad del 99,99%' en la práctica?",
    "what regions does novaplatform operate in?": "¿En qué regiones opera NovaPlatform?",
  },
  de: {
    "from 3 400+ reviews": "aus über 3 400 Bewertungen",
    "novaplatform runs on 42 edge nodes worldwide. every api request is routed to the nearest region automatically, eliminating cold starts and cross-continental latency. p99 response time is under 80ms — anywhere on earth.": "Die Plattform läuft auf 42 weltweit verteilten Knoten. Jeder API-Aufruf geht automatisch in die nächstgelegene Region: keine Kaltstarts, keine transatlantische Latenz. Die P99-Antwortzeit bleibt unter 80 ms, überall.",
    "real-time performance dashboards with 1-second granularity": "Performance-Dashboards in Echtzeit, sekundengenau",
    "we migrated from three separate tools to novaplatform over a single weekend. our engineering velocity doubled in the first month, and the on-call burden dropped by 70%. i wish we had switched sooner.": "Wir haben drei getrennte Werkzeuge an einem Wochenende durch diese Plattform ersetzt. Unsere Entwicklungsgeschwindigkeit verdoppelte sich im ersten Monat, die Rufbereitschaft sank um 70 %. Wir hätten früher wechseln sollen.",
    "the analytics dashboard surfaced a 2.3m € revenue opportunity in our first week that we had completely missed. the ai-powered anomaly detection is not a marketing claim — it genuinely works.": "Das Dashboard legte schon in der ersten Woche 2,3 Mio. € Umsatz offen, die uns völlig entgangen waren. Die Anomalie-Erkennung ist kein Marketingversprechen: Sie funktioniert.",
    "best developer experience i have encountered in 15 years of writing software. the api documentation is genuinely a work of art, and the typescript sdk is the best i have ever used — period.": "Die beste Entwicklererfahrung, die mir in fünfzehn Jahren begegnet ist. Die API-Dokumentation ist für sich genommen ein Werk, und das TypeScript-SDK ist das beste, das ich je genutzt habe.",
    "we process 180m € in transactions per month through novaplatform's payment orchestration layer. in 18 months of production, we have had zero data incidents and three nines of uptime. that's the number that matters.": "Wir wickeln 180 Mio. € Transaktionen pro Monat über die Zahlungsschicht ab. In achtzehn Monaten Produktion: null Datenvorfälle und Verfügbarkeit mit drei Neunen. Das ist die Zahl, die zählt.",
    "the branch preview environment feature alone saved us two engineering hires. our qa cycle went from 4 days to 6 hours, and our deployment frequency tripled within the first quarter. transformative.": "Allein die Preview-Umgebung pro Branch hat uns zwei Einstellungen erspart. Unser QA-Zyklus fiel von vier Tagen auf sechs Stunden, die Deployments verdreifachten sich schon im ersten Quartal.",
    "join 14 200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Schließen Sie sich über 14 200 Teams an, die schneller liefern. Dauerhaft kostenloser Tarif — ohne Kreditkarte.",
    "get started — it's free": "Loslegen — kostenlos",
    "+47% this week": "+47 % diese Woche",
    "1 team member": "1 Teammitglied",
    "14-day pro trial": "14-tägige Pro-Testversion",
    "all systems go": "Alle Systeme bereit",
    "average worldwide": "Durchschnitt weltweit",
    "built from the ground up for modern teams who refuse to compromise on speed, security, or developer experience.": "Von Grund auf für moderne Teams gebaut, die nicht bereit sind, bei Geschwindigkeit, Sicherheit oder Entwicklererfahrung Kompromisse einzugehen.",
    "can i migrate from my current stack without downtime?": "Kann ich ohne Ausfallzeit von meinem aktuellen Stack migrieren?",
    "connect your stack": "Verbinden Sie Ihre Werkzeuge",
    "data processed": "Verarbeitete Daten",
    "deploy time": "Bereitstellungszeit",
    "deploy to production instantly. our ai automatically optimizes latency, cost, and scaling as you grow.": "Setzen Sie sofort in der Produktion ein. Unsere KI optimiert automatisch Latenz, Kosten und Skalierung, während Sie wachsen.",
    "do you offer a startup programme?": "Bieten Sie ein Startup-Programm an?",
    "drag-and-drop workflow builder for non-technical teams. full code editor with autocomplete for engineers.": "Ein Workflow-Baukasten per Drag-and-drop für nichttechnische Teams. Ein vollwertiger Code-Editor mit Autovervollständigung für Entwickler.",
    "everything in pro": "Alles in Pro",
    "for organizations that demand the best — and can justify it.": "Für Organisationen, die das Beste verlangen — und es rechtfertigen können.",
    "for side projects, prototypes, and early-stage products.": "Für Nebenprojekte, Prototypen und Produkte in der frühen Phase.",
    "from 3,400+ reviews": "aus über 3 400 Bewertungen",
    "get started — it's free": "Loslegen — es ist kostenlos",
    "head of product, arkive": "Leiter Produkt, Arkive",
    "how does enterprise pricing work?": "Wie funktioniert die Unternehmenspreisgestaltung?",
    "how does the 14-day trial work?": "Wie funktioniert die 14-tägige Testversion?",
    "integrate in minutes with 200+ native connectors. rest, graphql, webhooks, or our sdks — your choice.": "Integrieren Sie in wenigen Minuten mit über 200 nativen Konnektoren. REST, GraphQL, Webhooks oder unsere SDKs — Ihre Wahl.",
    "is my data portable? what happens if i leave?": "Sind meine Daten portabel? Was passiert, wenn ich gehe?",
    "join 14,200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Schließen Sie sich über 14.200 Teams an, die schneller mit NovaPlatform versenden. Kostenloser Plan für immer — keine Kreditkarte erforderlich.",
    "loved by": "Geliebt von",
    "no credit card required for starter. all plans include a 30-day money-back guarantee.": "Keine Kreditkarte für Starter erforderlich. Alle Pläne beinhalten eine 30-tägige Geld-zurück-Garantie.",
    "no sign-up required · full product walkthrough": "Ohne Anmeldung · Vollständige Produkttour",
    "nothing you don't.": "Nichts, was Sie nicht können.",
    "on g2": "auf G2",
    "on-premises deployment option": "Option zur Bereitstellung vor Ort",
    "ready to build the": "Bereit, das",
    "revenue processed": "Verarbeitete Einnahmen",
    "security breaches in 6 years": "Sicherheitsverletzungen in 6 Jahren",
    "start 14-day trial": "14-tägige Testversion starten",
    "start building for free": "Kostenlos loslegen",
    "start for free": "Kostenlos starten",
    "start free,": "Kostenlos beginnen,",
    "talk to sales": "Sprich mit dem Vertrieb",
    "the all-in-one platform for modern engineering teams. build, deploy, and scale without limits.": "Die Alles-in-einem-Plattform für moderne Entwicklerteams. Bauen, ausrollen, grenzenlos skalieren.",
    "the all-in-one platform that replaces your entire infrastructure toolkit. build, deploy, and scale to millions of users without changing your workflow.": "Die All-in-One-Plattform, die Ihr gesamtes Infrastruktur-Toolkit ersetzt. Bauen, bereitstellen und auf Millionen von Benutzern skalieren, ohne Ihren Workflow zu ändern.",
    "three steps to": "Drei Schritte zu",
    "trusted by teams at the world's best companies": "Vertraut von Teams der besten Unternehmen der Welt",
    "up to 15 team members": "Bis zu 15 Teammitglieder",
    "up to 3 projects": "Bis zu 3 Projekte",
    "uptime today": "Betriebszeit heute",
    "watch demo (3 min)": "Demo ansehen (3 Min)",
    "what does '99.99% uptime sla' mean in practice?": "Was bedeutet '99,99% Verfügbarkeits-SLA' in der Praxis?",
    "what regions does novaplatform operate in?": "In welchen Regionen ist NovaPlatform tätig?",
  },
  pt: {
    "from 3 400+ reviews": "em mais de 3 400 avaliações",
    "novaplatform runs on 42 edge nodes worldwide. every api request is routed to the nearest region automatically, eliminating cold starts and cross-continental latency. p99 response time is under 80ms — anywhere on earth.": "A plataforma corre em 42 nós distribuídos pelo mundo. Cada chamada à API vai automaticamente para a região mais próxima: sem arranques a frio nem latência transatlântica. O tempo de resposta P99 fica abaixo de 80 ms, onde quer que se esteja.",
    "real-time performance dashboards with 1-second granularity": "Painéis de desempenho em tempo real, ao segundo",
    "we migrated from three separate tools to novaplatform over a single weekend. our engineering velocity doubled in the first month, and the on-call burden dropped by 70%. i wish we had switched sooner.": "Trocámos três ferramentas separadas por esta plataforma num fim de semana. A nossa velocidade de desenvolvimento duplicou no primeiro mês e as escalas caíram 70 %. Devíamos ter mudado antes.",
    "the analytics dashboard surfaced a 2.3m € revenue opportunity in our first week that we had completely missed. the ai-powered anomaly detection is not a marketing claim — it genuinely works.": "O painel revelou, logo na primeira semana, 2,3 M€ de faturação que nos escapava por completo. A deteção de anomalias não é um argumento de marketing: funciona.",
    "best developer experience i have encountered in 15 years of writing software. the api documentation is genuinely a work of art, and the typescript sdk is the best i have ever used — period.": "A melhor experiência de programação que conheci em quinze anos de ofício. A documentação da API é uma obra em si, e o SDK TypeScript é o melhor que já usei.",
    "we process 180m € in transactions per month through novaplatform's payment orchestration layer. in 18 months of production, we have had zero data incidents and three nines of uptime. that's the number that matters.": "Processamos 180 M€ de transações por mês através da camada de pagamentos. Em dezoito meses de produção: zero incidentes de dados e disponibilidade de três noves. É o número que conta.",
    "the branch preview environment feature alone saved us two engineering hires. our qa cycle went from 4 days to 6 hours, and our deployment frequency tripled within the first quarter. transformative.": "Só a função de ambiente de pré-visualização por ramo poupou-nos duas contratações. O nosso ciclo de QA passou de quatro dias para seis horas e as entregas triplicaram logo no primeiro trimestre.",
    "join 14 200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Junte-se a mais de 14 200 equipas que entregam mais depressa. Plano gratuito para sempre — sem cartão.",
    "get started — it's free": "Começar — é grátis",
    "+47% this week": "+47 % esta semana",
    "1 team member": "1 membro da equipe",
    "14-day pro trial": "Teste Pro de 14 dias",
    "all systems go": "Todos os sistemas prontos",
    "average worldwide": "Média mundial",
    "built from the ground up for modern teams who refuse to compromise on speed, security, or developer experience.": "Construído do zero para equipas modernas que se recusam a comprometer a velocidade, a segurança ou a experiência do desenvolvedor.",
    "can i migrate from my current stack without downtime?": "Posso migrar da minha pilha atual sem tempo de inatividade?",
    "connect your stack": "Ligue as suas ferramentas",
    "data processed": "Dados processados",
    "deploy time": "Tempo de implantação",
    "deploy to production instantly. our ai automatically optimizes latency, cost, and scaling as you grow.": "Implante em produção instantaneamente. A nossa IA otimiza automaticamente a latência, o custo e a escalabilidade à medida que você cresce.",
    "do you offer a startup programme?": "Oferecem um programa para startups?",
    "drag-and-drop workflow builder for non-technical teams. full code editor with autocomplete for engineers.": "Um construtor de fluxos por arrastar e largar para equipas não técnicas. Um editor de código completo, com preenchimento automático, para os programadores.",
    "everything in pro": "Tudo em Pro",
    "for organizations that demand the best — and can justify it.": "Para organizações que exigem o melhor — e podem justificá-lo.",
    "for side projects, prototypes, and early-stage products.": "Para projetos paralelos, protótipos e produtos em fase inicial.",
    "from 3,400+ reviews": "de mais de 3 400 avaliações",
    "get started — it's free": "Comece — é grátis",
    "head of product, arkive": "Chefe de Produto, Arkive",
    "how does enterprise pricing work?": "Como funciona a precificação empresarial?",
    "how does the 14-day trial work?": "Como funciona o teste de 14 dias?",
    "integrate in minutes with 200+ native connectors. rest, graphql, webhooks, or our sdks — your choice.": "Integre em minutos com mais de 200 conectores nativos. REST, GraphQL, webhooks ou nossos SDKs — a sua escolha.",
    "is my data portable? what happens if i leave?": "Os meus dados são portáteis? O que acontece se eu sair?",
    "join 14,200+ teams shipping faster with novaplatform. free forever plan — no credit card required.": "Junte-se a mais de 14.200 equipes que enviam mais rápido com a NovaPlatform. Plano gratuito para sempre — sem necessidade de cartão de crédito.",
    "loved by": "Amado por",
    "no credit card required for starter. all plans include a 30-day money-back guarantee.": "Não é necessário cartão de crédito para Starter. Todos os planos incluem uma garantia de devolução do dinheiro de 30 dias.",
    "no sign-up required · full product walkthrough": "Sem registo · Demonstração completa do produto",
    "nothing you don't.": "Nada que não possa.",
    "on g2": "no G2",
    "on-premises deployment option": "Opção de implementação local",
    "ready to build the": "Pronto para construir o",
    "revenue processed": "Receitas processadas",
    "security breaches in 6 years": "Violação de segurança em 6 anos",
    "start 14-day trial": "Iniciar teste de 14 dias",
    "start building for free": "Começar gratuitamente",
    "start for free": "Começar gratuitamente",
    "start free,": "Começar gratuitamente,",
    "talk to sales": "Fale com vendas",
    "the all-in-one platform for modern engineering teams. build, deploy, and scale without limits.": "A plataforma tudo-em-um para as equipas técnicas de hoje. Construir, implantar e escalar sem limite.",
    "the all-in-one platform that replaces your entire infrastructure toolkit. build, deploy, and scale to millions of users without changing your workflow.": "A plataforma tudo-em-um que substitui todo o seu kit de ferramentas de infraestrutura. Construa, implemente e escale para milhões de usuários sem mudar seu fluxo de trabalho.",
    "three steps to": "Três passos para",
    "trusted by teams at the world's best companies": "Confiável por equipes das melhores empresas do mundo",
    "up to 15 team members": "Até 15 membros da equipe",
    "up to 3 projects": "Até 3 projetos",
    "uptime today": "Tempo de atividade hoje",
    "watch demo (3 min)": "Ver demonstração (3 min)",
    "what does '99.99% uptime sla' mean in practice?": "O que significa 'SLA de tempo de atividade de 99,99%' na prática?",
    "what regions does novaplatform operate in?": "Em que regiões a NovaPlatform opera?",
  },
};
