/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "absolutely. all flights can be customized with bespoke catering, specific cabin layouts, and security personnel upon request.": "Absolument. Tous les vols peuvent être personnalisés avec un catering sur mesure, des agencements de cabine spécifiques et du personnel de sécurité sur demande.",
    "access 5,000+ airports worldwide, including those inaccessible to commercial airlines.": "Accédez à plus de 5 000 aéroports dans le monde, y compris ceux inaccessibles aux compagnies aériennes commerciales.",
    "access the world's most advanced fleet of private aircraft. from rapid super-midsize charters to ultra-long-range executive suites.": "Accédez à la flotte d'avions privés la plus avancée au monde. Des charters super-midsize rapides aux suites exécutives ultra-longue portée.",
    "arrive 15 minutes before take-off. skip the queues, the security, and the compromise.": "Arrivez 15 minutes avant le décollage. Évitez les files d'attente, la sécurité et les compromis.",
    "asked questions.": "Questions Fréquemment Posées.",
    "avg activation time": "Temps d'activation moyen",
    "can i choose specific catering and cabin configurations?": "Puis-je choisir des options de restauration et des configurations de cabine spécifiques ?",
    "cancellation terms depend on the aircraft class and flight route. detailed terms are provided during the instant quote process.": "Les conditions d'annulation dépendent de la classe d'avion et de l'itinéraire de vol. Les conditions détaillées sont fournies lors du processus de devis instantané.",
    "charter a jet in as little as 4 hours. our global fleet is always on standby for you.": "Affrétez un jet en aussi peu que 4 heures. Notre flotte mondiale est toujours prête pour vous.",
    "contact our operations desk to coordinate your next flight. instant logistics mapping for any destination worldwide.": "Contactez notre bureau des opérations pour organiser votre prochain vol. Plan logistique immédiat, pour n'importe quelle destination.",
    "curated aircraft for global reach": "Une flotte choisie, pour aller partout",
    "dispatch ready": "PRÊT À DÉPLOYER",
    "download spec sheets": "Télécharger les fiches techniques",
    "endorsed by": "Approuvé par",
    "explore the fleet": "Découvrir la flotte",
    "for absolute freedom.": "Pour une liberté absolue.",
    "how quickly can a flight be activated?": "À quelle vitesse un vol peut-il être activé ?",
    "our global dispatch desk can activate an aircraft and have it ready for take-off in as little as 4 hours from booking confirmation.": "Notre bureau de dispatch mondial peut activer un aéronef et le préparer au décollage en aussi peu que 4 heures après la confirmation de la réservation.",
    "our proprietary dispatch ai monitors 2,800 aircraft across 5 partner networks to ensure 100% mission readiness at any coordinate.": "Notre IA de répartition propriétaire surveille 2 800 aéronefs à travers 5 réseaux partenaires pour garantir une préparation à la mission de 100 % à n'importe quelle coordonnée.",
    "request": "Demander",
    "request instant telemetry": "DEMANDEZ UNE TÉLÉMÉTRIE INSTANTANÉE",
    "revolutionary comfort with the lowest cabin altitude in its class.": "Confort révolutionnaire avec la plus basse altitude de cabine de sa catégorie.",
    "secure email": "EMAIL SÉCURISÉ",
    "speed and range redefined. the industry standard for international executive travel.": "Vitesse et portée redéfinies. La norme de l'industrie pour les voyages d'affaires internationaux.",
    "telemetry of trust": "Télémétrie de confiance",
    "the cabin comfort on the global 7500 was exceptional, and the crew's attention to detail was flawless. highly recommended.": "Le confort de la cabine sur le Global 7500 était exceptionnel, et l'attention portée aux détails par l'équipage était impeccable. Hautement recommandé.",
    "the edge of aviation. unlocking global movement with precision, speed, and absolute discretion.": "La pointe de l'aviation. Se déplacer partout, avec précision, vitesse et discrétion absolue.",
    "the velocity standard": "Notre exigence",
    "the world's largest and longest-range business jet. a masterclass in luxury and range.": "Le plus grand et le plus long jet d'affaires au monde. Une masterclass en luxe et en portée.",
    "velocity has transformed how we manage our global board meetings. the ability to launch a jet in under four hours is a game-changer.": "Velocity a transformé la façon dont nous gérons nos réunions de conseil d'administration mondiales. La capacité de lancer un jet en moins de quatre heures est un changement de jeu.",
    "velocity was founded on a simple insight: time is the ultimate non-renewable asset.": "Velocity a été fondée sur une simple idée : le temps est l'actif non renouvelable ultime.",
    "we hold wyvern wingman and argus gold safety ratings. every operator in our network is audited to meet and exceed faa part 135 regulations.": "Nous détenons les certifications de sécurité Wyvern Wingman et ARGUS Gold. Chaque opérateur de notre réseau est audité pour répondre et dépasser les réglementations FAA Part 135.",
    "what are your safety standards?": "Quels sont vos standards de sécurité ?",
    "what is your cancellation policy?": "Quelle est votre politique d'annulation ?",
    "wyvern wingman and argus gold rated. every flight exceeds faa part 135 standards.": "Évalué Wyvern Wingman et ARGUS Gold. Chaque vol dépasse les normes FAA Part 135.",
    "wyvern wingman safety rating and top-tier aircraft maintenance. velocity gives me absolute peace of mind on every journey.": "Évaluation de sécurité Wyvern Wingman et maintenance d'avion de premier ordre. Velocity me donne une tranquillité d'esprit absolue à chaque voyage.",
    "zero wait time": "Temps d'attente zéro",
  },
  es: {
    "absolutely. all flights can be customized with bespoke catering, specific cabin layouts, and security personnel upon request.": "Absolutamente. Todos los vuelos se pueden personalizar con catering a medida, diseños de cabina específicos y personal de seguridad a pedido.",
    "access 5,000+ airports worldwide, including those inaccessible to commercial airlines.": "Acceda a más de 5,000 aeropuertos en todo el mundo, incluidos aquellos inaccesibles para las aerolíneas comerciales.",
    "access the world's most advanced fleet of private aircraft. from rapid super-midsize charters to ultra-long-range executive suites.": "Accede a la flota de aviones privados más avanzada del mundo. Desde chárteres supermedianos rápidos hasta suites ejecutivas de ultra largo alcance.",
    "arrive 15 minutes before take-off. skip the queues, the security, and the compromise.": "Llegue 15 minutos antes del despegue. Salte las colas, la seguridad y los compromisos.",
    "asked questions.": "Preguntas Frecuentes.",
    "avg activation time": "Tiempo medio de activación",
    "can i choose specific catering and cabin configurations?": "¿Puedo elegir opciones de catering y configuraciones de cabina específicas?",
    "cancellation terms depend on the aircraft class and flight route. detailed terms are provided during the instant quote process.": "Los términos de cancelación dependen de la clase de aeronave y de la ruta de vuelo. Los términos detallados se proporcionan durante el proceso de cotización instantánea.",
    "charter a jet in as little as 4 hours. our global fleet is always on standby for you.": "Chárter un jet en tan solo 4 horas. Nuestra flota global siempre está en espera para usted.",
    "contact our operations desk to coordinate your next flight. instant logistics mapping for any destination worldwide.": "Contacte con nuestra mesa de operaciones para organizar su próximo vuelo. Plan logístico inmediato, para cualquier destino.",
    "curated aircraft for global reach": "Una flota elegida, para llegar a todas partes",
    "dispatch ready": "LISTA PARA DESPACHO",
    "download spec sheets": "Descargar hojas de especificaciones",
    "endorsed by": "Respaldado por",
    "explore the fleet": "Descubrir la flota",
    "for absolute freedom.": "Por libertad absoluta.",
    "how quickly can a flight be activated?": "¿Qué tan rápido se puede activar un vuelo?",
    "our global dispatch desk can activate an aircraft and have it ready for take-off in as little as 4 hours from booking confirmation.": "Nuestra mesa de despacho global puede activar una aeronave y tenerla lista para el despegue en tan solo 4 horas desde la confirmación de la reserva.",
    "our proprietary dispatch ai monitors 2,800 aircraft across 5 partner networks to ensure 100% mission readiness at any coordinate.": "Nuestra IA de despacho propietaria monitorea 2,800 aeronaves a través de 5 redes asociadas para garantizar un 100% de preparación para la misión en cualquier coordenada.",
    "request": "Solicitar",
    "request instant telemetry": "SOLICITE TELEMETRÍA INSTANTÁNEA",
    "revolutionary comfort with the lowest cabin altitude in its class.": "Confort revolucionario con la altitud de cabina más baja de su clase.",
    "secure email": "EMAIL SEGURO",
    "speed and range redefined. the industry standard for international executive travel.": "Velocidad y alcance redefinidos. El estándar de la industria para viajes ejecutivos internacionales.",
    "telemetry of trust": "Telemetría de confianza",
    "the cabin comfort on the global 7500 was exceptional, and the crew's attention to detail was flawless. highly recommended.": "El confort de la cabina en el Global 7500 fue excepcional, y la atención al detalle del equipo fue impecable. Muy recomendado.",
    "the edge of aviation. unlocking global movement with precision, speed, and absolute discretion.": "La vanguardia de la aviación. Moverse a cualquier parte, con precisión, rapidez y discreción absoluta.",
    "the velocity standard": "Nuestra exigencia",
    "the world's largest and longest-range business jet. a masterclass in luxury and range.": "El jet de negocios más grande y de mayor alcance del mundo. Una clase magistral en lujo y alcance.",
    "velocity has transformed how we manage our global board meetings. the ability to launch a jet in under four hours is a game-changer.": "Velocity ha transformado la forma en que gestionamos nuestras reuniones de junta globales. La capacidad de lanzar un jet en menos de cuatro horas es un cambio de juego.",
    "velocity was founded on a simple insight: time is the ultimate non-renewable asset.": "Velocity fue fundada con una idea simple: el tiempo es el activo no renovable definitivo.",
    "we hold wyvern wingman and argus gold safety ratings. every operator in our network is audited to meet and exceed faa part 135 regulations.": "Tenemos las calificaciones de seguridad Wyvern Wingman y ARGUS Gold. Cada operador en nuestra red es auditado para cumplir y superar las regulaciones de la FAA Parte 135.",
    "what are your safety standards?": "¿Cuáles son sus estándares de seguridad?",
    "what is your cancellation policy?": "¿Cuál es su política de cancelación?",
    "wyvern wingman and argus gold rated. every flight exceeds faa part 135 standards.": "Calificado como Wyvern Wingman y ARGUS Gold. Cada vuelo supera los estándares de la FAA Parte 135.",
    "wyvern wingman safety rating and top-tier aircraft maintenance. velocity gives me absolute peace of mind on every journey.": "Calificación de seguridad Wyvern Wingman y mantenimiento de aeronaves de primer nivel. Velocity me brinda una tranquilidad absoluta en cada viaje.",
    "zero wait time": "Tiempo de espera cero",
  },
  de: {
    "absolutely. all flights can be customized with bespoke catering, specific cabin layouts, and security personnel upon request.": "Absolut. Alle Flüge können auf Wunsch mit maßgeschneidertem Catering, spezifischen Kabinenlayouts und Sicherheitspersonal angepasst werden.",
    "access 5,000+ airports worldwide, including those inaccessible to commercial airlines.": "Zugang zu über 5.000 Flughäfen weltweit, einschließlich derjenigen, die für kommerzielle Fluggesellschaften unzugänglich sind.",
    "access the world's most advanced fleet of private aircraft. from rapid super-midsize charters to ultra-long-range executive suites.": "Zugriff auf die fortschrittlichste Flotte von Privatflugzeugen der Welt. Von schnellen Super-Midsize-Chartern bis hin zu ultra-langstrecken Executive-Suiten.",
    "arrive 15 minutes before take-off. skip the queues, the security, and the compromise.": "Kommen Sie 15 Minuten vor dem Abflug an. Überspringen Sie die Warteschlangen, die Sicherheitskontrollen und die Kompromisse.",
    "asked questions.": "Häufig Gestellte Fragen.",
    "avg activation time": "Durchschnittliche Aktivierungszeit",
    "can i choose specific catering and cabin configurations?": "Kann ich spezifische Catering- und Kabinenkonfigurationen wählen?",
    "cancellation terms depend on the aircraft class and flight route. detailed terms are provided during the instant quote process.": "Die Stornierungsbedingungen hängen von der Flugzeugklasse und der Flugroute ab. Detaillierte Bedingungen werden während des Sofortangebotprozesses bereitgestellt.",
    "charter a jet in as little as 4 hours. our global fleet is always on standby for you.": "Chartern Sie ein Flugzeug in nur 4 Stunden. Unsere globale Flotte steht immer für Sie bereit.",
    "contact our operations desk to coordinate your next flight. instant logistics mapping for any destination worldwide.": "Wenden Sie sich an unsere Einsatzzentrale, um Ihren nächsten Flug zu planen. Sofortige Logistikplanung für jedes Ziel.",
    "curated aircraft for global reach": "Eine ausgewählte Flotte für weltweite Reichweite",
    "dispatch ready": "BEREIT FÜR DEN EINSATZ",
    "download spec sheets": "Spezifikationsblätter herunterladen",
    "endorsed by": "Empfohlen von",
    "explore the fleet": "Die Flotte entdecken",
    "for absolute freedom.": "Für absolute Freiheit.",
    "how quickly can a flight be activated?": "Wie schnell kann ein Flug aktiviert werden?",
    "our global dispatch desk can activate an aircraft and have it ready for take-off in as little as 4 hours from booking confirmation.": "Unser globales Dispatch-Büro kann ein Flugzeug aktivieren und es in nur 4 Stunden nach Buchungsbestätigung startklar machen.",
    "our proprietary dispatch ai monitors 2,800 aircraft across 5 partner networks to ensure 100% mission readiness at any coordinate.": "Unsere proprietäre Dispatch-KI überwacht 2.800 Flugzeuge in 5 Partnernetzwerken, um 100 % Einsatzbereitschaft an jedem Standort zu gewährleisten.",
    "request": "Anfordern",
    "request instant telemetry": "FORDERN SIE SOFORTIGE TELEMETRIE AN",
    "revolutionary comfort with the lowest cabin altitude in its class.": "Revolutionärer Komfort mit der niedrigsten Kabinenhöhe seiner Klasse.",
    "secure email": "SICHERER E-MAIL",
    "speed and range redefined. the industry standard for international executive travel.": "Geschwindigkeit und Reichweite neu definiert. Der Branchenstandard für internationale Geschäftsreisen.",
    "telemetry of trust": "Telemetrie des Vertrauens",
    "the cabin comfort on the global 7500 was exceptional, and the crew's attention to detail was flawless. highly recommended.": "Der Kabinenkomfort im Global 7500 war außergewöhnlich, und die Liebe zum Detail des Personals war makellos. Sehr empfehlenswert.",
    "the edge of aviation. unlocking global movement with precision, speed, and absolute discretion.": "Die Spitze der Luftfahrt. Weltweite Mobilität mit Präzision, Tempo und absoluter Diskretion.",
    "the velocity standard": "Unser Anspruch",
    "the world's largest and longest-range business jet. a masterclass in luxury and range.": "Das größte und am weitesten reichende Geschäftsflugzeug der Welt. Eine Meisterklasse in Luxus und Reichweite.",
    "velocity has transformed how we manage our global board meetings. the ability to launch a jet in under four hours is a game-changer.": "Velocity hat verändert, wie wir unsere globalen Vorstandssitzungen verwalten. Die Möglichkeit, ein Flugzeug in weniger als vier Stunden zu starten, ist ein Wendepunkt.",
    "velocity was founded on a simple insight: time is the ultimate non-renewable asset.": "Velocity wurde auf einer einfachen Einsicht gegründet: Zeit ist das ultimative nicht erneuerbare Gut.",
    "we hold wyvern wingman and argus gold safety ratings. every operator in our network is audited to meet and exceed faa part 135 regulations.": "Wir halten die Sicherheitsbewertungen Wyvern Wingman und ARGUS Gold. Jeder Betreiber in unserem Netzwerk wird geprüft, um die FAA Part 135-Vorschriften zu erfüllen und zu übertreffen.",
    "what are your safety standards?": "Was sind Ihre Sicherheitsstandards?",
    "what is your cancellation policy?": "Was ist Ihre Stornierungsrichtlinie?",
    "wyvern wingman and argus gold rated. every flight exceeds faa part 135 standards.": "Wyvern Wingman und ARGUS Gold bewertet. Jeder Flug übertrifft die FAA Part 135 Standards.",
    "wyvern wingman safety rating and top-tier aircraft maintenance. velocity gives me absolute peace of mind on every journey.": "Wyvern Wingman Sicherheitsbewertung und erstklassige Flugzeugwartung. Velocity gibt mir absolute Sicherheit auf jeder Reise.",
    "zero wait time": "Keine Wartezeit",
  },
  pt: {
    "absolutely. all flights can be customized with bespoke catering, specific cabin layouts, and security personnel upon request.": "Absolutamente. Todos os voos podem ser personalizados com catering sob medida, layouts de cabine específicos e pessoal de segurança, mediante solicitação.",
    "access 5,000+ airports worldwide, including those inaccessible to commercial airlines.": "Acesse mais de 5.000 aeroportos em todo o mundo, incluindo aqueles inacessíveis para companhias aéreas comerciais.",
    "access the world's most advanced fleet of private aircraft. from rapid super-midsize charters to ultra-long-range executive suites.": "Aceda à a frota de aeronaves privadas mais avançada do mundo. Desde charters super-médios rápidos até suítes executivas de ultra-longa distância.",
    "arrive 15 minutes before take-off. skip the queues, the security, and the compromise.": "Chegue 15 minutos antes da decolagem. Evite as filas, a segurança e os compromissos.",
    "asked questions.": "Perguntas Frequentes.",
    "avg activation time": "Tempo Médio de Ativação",
    "can i choose specific catering and cabin configurations?": "Posso escolher opções de catering e configurações de cabine específicas?",
    "cancellation terms depend on the aircraft class and flight route. detailed terms are provided during the instant quote process.": "Os termos de cancelamento dependem da classe da aeronave e da rota do voo. Os termos detalhados são fornecidos durante o processo de cotação instantânea.",
    "charter a jet in as little as 4 hours. our global fleet is always on standby for you.": "Alugue um jato em apenas 4 horas. Nossa frota global está sempre de prontidão para você.",
    "contact our operations desk to coordinate your next flight. instant logistics mapping for any destination worldwide.": "Contacte a nossa mesa de operações para organizar o seu próximo voo. Plano logístico imediato, para qualquer destino.",
    "curated aircraft for global reach": "Uma frota escolhida, para chegar a toda a parte",
    "dispatch ready": "PRONTO PARA DESPACHO",
    "download spec sheets": "Baixar Fichas Técnicas",
    "endorsed by": "Aprovado por",
    "explore the fleet": "Descobrir a frota",
    "for absolute freedom.": "Para liberdade absoluta.",
    "how quickly can a flight be activated?": "Quão rapidamente pode um voo ser ativado?",
    "our global dispatch desk can activate an aircraft and have it ready for take-off in as little as 4 hours from booking confirmation.": "O nosso escritório de despacho global pode ativar uma aeronave e tê-la pronta para a decolagem em apenas 4 horas após a confirmação da reserva.",
    "our proprietary dispatch ai monitors 2,800 aircraft across 5 partner networks to ensure 100% mission readiness at any coordinate.": "A nossa IA de despacho proprietária monitora 2.800 aeronaves em 5 redes parceiras para garantir 100% de prontidão para a missão em qualquer coordenada.",
    "request": "Pedir",
    "request instant telemetry": "SOLICITE TELEMETRIA INSTANTÂNEA",
    "revolutionary comfort with the lowest cabin altitude in its class.": "Conforto revolucionário com a menor altitude de cabine da sua classe.",
    "secure email": "EMAIL SEGURO",
    "speed and range redefined. the industry standard for international executive travel.": "Velocidade e alcance redefinidos. O padrão da indústria para viagens executivas internacionais.",
    "telemetry of trust": "Telemetria de Confiança",
    "the cabin comfort on the global 7500 was exceptional, and the crew's attention to detail was flawless. highly recommended.": "O conforto da cabine no Global 7500 foi excepcional, e a atenção aos detalhes da tripulação foi impecável. Altamente recomendado.",
    "the edge of aviation. unlocking global movement with precision, speed, and absolute discretion.": "A vanguarda da aviação. Deslocar-se a toda a parte, com precisão, rapidez e discrição absoluta.",
    "the velocity standard": "A nossa exigência",
    "the world's largest and longest-range business jet. a masterclass in luxury and range.": "O maior e de maior alcance jato de negócios do mundo. Uma aula magistral em luxo e alcance.",
    "velocity has transformed how we manage our global board meetings. the ability to launch a jet in under four hours is a game-changer.": "A Velocity transformou a forma como gerimos as nossas reuniões de conselho globais. A capacidade de lançar um jato em menos de quatro horas é um divisor de águas.",
    "velocity was founded on a simple insight: time is the ultimate non-renewable asset.": "A Velocity foi fundada com uma ideia simples: o tempo é o ativo não renovável definitivo.",
    "we hold wyvern wingman and argus gold safety ratings. every operator in our network is audited to meet and exceed faa part 135 regulations.": "Temos as classificações de segurança Wyvern Wingman e ARGUS Gold. Cada operador na nossa rede é auditado para cumprir e exceder as regulamentações da FAA Parte 135.",
    "what are your safety standards?": "Quais são os seus padrões de segurança?",
    "what is your cancellation policy?": "Qual é a sua política de cancelamento?",
    "wyvern wingman and argus gold rated. every flight exceeds faa part 135 standards.": "Classificado como Wyvern Wingman e ARGUS Gold. Cada voo excede os padrões da FAA Parte 135.",
    "wyvern wingman safety rating and top-tier aircraft maintenance. velocity gives me absolute peace of mind on every journey.": "Classificação de segurança Wyvern Wingman e manutenção de aeronaves de primeira linha. A Velocity me dá uma paz de espírito absoluta em cada viagem.",
    "zero wait time": "Tempo de espera zero",
  },
};
