/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "the future of computation": "L'avenir du calcul",
    "is an independent quantum computing research institute advancing fault-tolerant processors, quantum algorithms, and the foundational science of the post-classical era.": "est un institut de recherche indépendant en informatique quantique : processeurs tolérants aux fautes, algorithmes quantiques et science fondamentale de l'après-classique.",
    "developing fault-tolerant qubit architectures that maintain coherence across extended computation windows using topological protection methods.": "Nous développons des architectures de qubits tolérantes aux fautes, qui gardent leur cohérence sur de longues fenêtres de calcul grâce à la protection topologique.",
    "partners with universities, national labs, and industry researchers. cloud access to our 127-qubit system is available via our research gateway program.": "travaille avec des universités, des laboratoires nationaux et des chercheurs de l'industrie. L'accès à distance à notre système de 127 qubits passe par notre programme Research Gateway.",
    "about qbit labs": "À propos de l'institut",
    "advancing the science of quantum computation. independent research, open publication, and open access infrastructure.": "Faire avancer la science du calcul quantique. Recherche indépendante, publication ouverte, infrastructure en libre accès.",
    "advancing variational quantum eigensolvers, quantum chemistry simulation, and combinatorial optimization for near-term hardware.": "Avancement des solveurs d'eigenvalues quantiques variationnels, de la simulation de chimie quantique et de l'optimisation combinatoire pour le matériel à court terme.",
    "director of quantum hardware": "Directeur du matériel quantique",
    "engineering superconducting transmon and fluxonium processors with sub-microsecond gate times and 99.9%+ two-qubit fidelity targets.": "Ingénierie de processeurs transmon et fluxonium supraconducteurs avec des temps de porte sub-microseconde et des cibles de fidélité de deux qubits de 99,9 % ou plus.",
    "explore research": "Explorer la recherche",
    "other": "Autre",
    "prototype quantum repeater architectures and entanglement distribution protocols for intercontinental quantum communication links.": "Prototypes d'architectures de répéteurs quantiques et de protocoles de distribution d'intrication pour des liaisons de communication quantique intercontinentales.",
    "quantum processor design": "Conception de processeurs quantiques",
    "request research access": "Demander l'accès à la recherche",
    "submit request": "Soumettre la demande",
    "view all 47 papers": "Voir les 47 publications",
    "view publications": "Voir les publications",
  },
  es: {
    "the future of computation": "El futuro del cálculo",
    "is an independent quantum computing research institute advancing fault-tolerant processors, quantum algorithms, and the foundational science of the post-classical era.": "es un instituto de investigación independiente en computación cuántica: procesadores tolerantes a fallos, algoritmos cuánticos y ciencia fundamental de la era posclásica.",
    "developing fault-tolerant qubit architectures that maintain coherence across extended computation windows using topological protection methods.": "Desarrollamos arquitecturas de cúbits tolerantes a fallos que mantienen la coherencia en ventanas de cálculo largas gracias a la protección topológica.",
    "partners with universities, national labs, and industry researchers. cloud access to our 127-qubit system is available via our research gateway program.": "trabaja con universidades, laboratorios nacionales e investigadores de la industria. El acceso remoto a nuestro sistema de 127 cúbits pasa por el programa Research Gateway.",
    "about qbit labs": "Sobre el instituto",
    "advancing the science of quantum computation. independent research, open publication, and open access infrastructure.": "Hacer avanzar la ciencia de la computación cuántica. Investigación independiente, publicación abierta, infraestructura de acceso libre.",
    "advancing variational quantum eigensolvers, quantum chemistry simulation, and combinatorial optimization for near-term hardware.": "Avanzando en solucionadores cuánticos variacionales, simulaciones de química cuántica y optimización combinatoria para hardware a corto plazo.",
    "director of quantum hardware": "Director de Hardware Cuántico",
    "engineering superconducting transmon and fluxonium processors with sub-microsecond gate times and 99.9%+ two-qubit fidelity targets.": "Ingeniería de procesadores transmon y fluxonio superconductores con tiempos de puerta sub-microsegundo y objetivos de fidelidad de dos qubits de más del 99,9%.",
    "explore research": "Explorar la investigación",
    "other": "Otro",
    "prototype quantum repeater architectures and entanglement distribution protocols for intercontinental quantum communication links.": "Prototipos de arquitecturas de repetidores cuánticos y protocolos de distribución de entrelazamiento para enlaces de comunicación cuántica intercontinentales.",
    "quantum processor design": "Diseño de Procesadores Cuánticos",
    "request research access": "Solicitar acceso a la investigación",
    "submit request": "Enviar solicitud",
    "view all 47 papers": "Ver las 47 publicaciones",
    "view publications": "Ver publicaciones",
  },
  de: {
    "the future of computation": "Die Zukunft des Rechnens",
    "is an independent quantum computing research institute advancing fault-tolerant processors, quantum algorithms, and the foundational science of the post-classical era.": "ist ein unabhängiges Forschungsinstitut für Quanteninformatik: fehlertolerante Prozessoren, Quantenalgorithmen und Grundlagenforschung der postklassischen Ära.",
    "developing fault-tolerant qubit architectures that maintain coherence across extended computation windows using topological protection methods.": "Wir entwickeln fehlertolerante Qubit-Architekturen, die dank topologischem Schutz über lange Rechenfenster kohärent bleiben.",
    "partners with universities, national labs, and industry researchers. cloud access to our 127-qubit system is available via our research gateway program.": "arbeitet mit Universitäten, nationalen Laboren und Forschenden aus der Industrie. Der Fernzugriff auf unser 127-Qubit-System läuft über unser Research-Gateway-Programm.",
    "about qbit labs": "Über das Institut",
    "advancing the science of quantum computation. independent research, open publication, and open access infrastructure.": "Die Wissenschaft des Quantenrechnens voranbringen. Unabhängige Forschung, offene Publikation, frei zugängliche Infrastruktur.",
    "advancing variational quantum eigensolvers, quantum chemistry simulation, and combinatorial optimization for near-term hardware.": "Fortschritte bei variationalen Quanten-Eigensolvern, der Quantenchemiesimulation und der kombinatorischen Optimierung für kurzfristige Hardware.",
    "director of quantum hardware": "Direktor für Quantenhardware",
    "engineering superconducting transmon and fluxonium processors with sub-microsecond gate times and 99.9%+ two-qubit fidelity targets.": "Ingenieurwesen von supraleitenden Transmon- und Fluxonium-Prozessoren mit Gate-Zeiten von unter einer Mikrosekunde und Zielwerten für die Zwei-Qubit-Fidelität von über 99,9%.",
    "explore research": "Forschung erkunden",
    "other": "Andere",
    "prototype quantum repeater architectures and entanglement distribution protocols for intercontinental quantum communication links.": "Prototypen von Quantenrepeater-Architekturen und Protokollen zur Verteilung von Verschränkungen für interkontinentale Quantenkommunikationsverbindungen.",
    "quantum processor design": "Entwurf von Quantenprozessoren",
    "request research access": "Forschungzugang anfordern",
    "submit request": "Anfrage einreichen",
    "view all 47 papers": "Alle 47 Veröffentlichungen ansehen",
    "view publications": "Publikationen ansehen",
  },
  pt: {
    "the future of computation": "O futuro do cálculo",
    "is an independent quantum computing research institute advancing fault-tolerant processors, quantum algorithms, and the foundational science of the post-classical era.": "é um instituto de investigação independente em computação quântica: processadores tolerantes a falhas, algoritmos quânticos e ciência fundamental da era pós-clássica.",
    "developing fault-tolerant qubit architectures that maintain coherence across extended computation windows using topological protection methods.": "Desenvolvemos arquiteturas de qubits tolerantes a falhas que mantêm a coerência em janelas de cálculo longas graças à proteção topológica.",
    "partners with universities, national labs, and industry researchers. cloud access to our 127-qubit system is available via our research gateway program.": "trabalha com universidades, laboratórios nacionais e investigadores da indústria. O acesso remoto ao nosso sistema de 127 qubits passa pelo programa Research Gateway.",
    "about qbit labs": "Sobre o instituto",
    "advancing the science of quantum computation. independent research, open publication, and open access infrastructure.": "Fazer avançar a ciência da computação quântica. Investigação independente, publicação aberta, infraestrutura de acesso livre.",
    "advancing variational quantum eigensolvers, quantum chemistry simulation, and combinatorial optimization for near-term hardware.": "Avançando em solucionadores quânticos variacionais, simulação de química quântica e otimização combinatória para hardware de curto prazo.",
    "director of quantum hardware": "Diretor de Hardware Quântico",
    "engineering superconducting transmon and fluxonium processors with sub-microsecond gate times and 99.9%+ two-qubit fidelity targets.": "Engenharia de processadores transmon e fluxônio supercondutores com tempos de porta sub-microsegundo e metas de fidelidade de dois qubits de 99,9% ou mais.",
    "explore research": "Explorar a pesquisa",
    "other": "Outro",
    "prototype quantum repeater architectures and entanglement distribution protocols for intercontinental quantum communication links.": "Protótipos de arquiteturas de repetidores quânticos e protocolos de distribuição de emaranhamento para ligações de comunicação quântica intercontinentais.",
    "quantum processor design": "Design de Processadores Quânticos",
    "request research access": "Solicitar acesso à pesquisa",
    "submit request": "Submeter pedido",
    "view all 47 papers": "Ver as 47 publicações",
    "view publications": "Ver publicações",
  },
};
