/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "about horizon": "À propos",
    "all 87 destinations": "Les 87 destinations",
    "an icon of contemporary luxury. featuring a glass-bottom pool, private owner's deck, and an expansive beach club.": "Une icône du luxe contemporain. Avec une piscine à fond de verre, un pont privé pour le propriétaire et un vaste club de plage.",
    "avoid the friction of public airports. we coordinate seamless private jet charters and helicopter transfers directly to your yacht's helipad.": "Évitez les désagréments des aéroports publics. Nous coordonnons des charters de jets privés sans faille et des transferts en hélicoptère directement vers le hélipad de votre yacht.",
    "begin your": "Commencez votre",
    "begin your journey": "Commencer votre voyage",
    "bespoke yacht charters and private aviation transfers across the world's most extraordinary waters. curated for those who demand perfection without effort.": "Charters de yachts sur mesure et transferts aériens privés à travers les eaux les plus extraordinaires du monde. Curé pour ceux qui exigent la perfection sans effort.",
    "best season": "Meilleure Saison",
    "built / refit": "Construit / Rénové",
    "caldera sunsets from your private deck": "Les couchers de soleil sur la caldeira, depuis votre pont privé",
    "classic lines with modern naval architecture. hand-finished teak decks, mahogany salon, and state-of-the-art rigging.": "Lignes classiques avec une architecture navale moderne. Ponts en teck finis à la main, salon en acajou et gréement à la pointe de la technologie.",
    "client reflections": "Réflexions des clients",
    "client return rate": "Taux de Retour des Clients",
    "communicated upon request": "communiqué sur demande",
    "design my voyage": "Concevoir mon voyage",
    "discover white-washed villages draped over volcanic cliffs. cruise private coves in folegandros and catch caldera sunsets from your deck.": "Découvrez des villages blanchis à la chaux drapés sur des falaises volcaniques. Croisez des criques privées à Folegandros et admirez les couchers de soleil sur la caldeira depuis votre pont.",
    "embarkation from port hercules. champagne welcome and evening anchorage beneath the rock.": "Embarquement à Port Hercule. Accueil au champagne et mouillage du soir au pied du Rocher.",
    "enquire": "Demander",
    "every vessel carries a premium selection of watersports equipment, from personal submarines and fast tenders to jet skis, foil boards, and diving gear.": "Chaque navire dispose d'une sélection premium d'équipements de sports nautiques, des sous-marins personnels et des annexes rapides aux jet-skis, planches à foil et équipements de plongée.",
    "every voyage is authored": "Chaque traversée est composée",
    "explore our curated portfolio of ultra-luxury vessels available for charter. each yacht is maintained to impeccable standards with hand-selected crews.": "Explorez notre portefeuille sélectionné de navires ultra-luxueux disponibles à la location. Chaque yacht est entretenu selon des normes impeccables avec des équipages soigneusement sélectionnés.",
    "figures updated in real time · est. monaco 1997": "Chiffres mis à jour en temps réel · Est. Monaco 1997",
    "for the true explorer. navigate through towering glaciers, witness polar wildlife in silence, and experience the midnight sun.": "Pour le véritable explorateur. Naviguez à travers des glaciers majestueux, observez la faune polaire en silence et vivez le soleil de minuit.",
    "ice-class explorer designed for global expeditions. complete with private submarine, heli-hangar, and science lab.": "Explorateur de classe glace conçu pour des expéditions mondiales. Équipé d'un sous-marin privé, d'un héliport et d'un laboratoire scientifique.",
    "monaco to ibiza": "Monaco à Ibiza",
    "navigate the world's most exceptional coastal waters. from sun-drenched mediterranean shores to untouched polar wilderness.": "Naviguez dans les eaux côtières les plus exceptionnelles du monde. Des rivages méditerranéens baignés de soleil aux régions polaires vierges.",
    "our fleet": "Notre flotte",
    "our fleet spans 18 to 92 metres. our crew-to-guest ratios exceed any industry standard. our chefs hold stars. our captains hold records.": "Notre flotte va de dix-huit à quatre-vingt-douze mètres. Nos ratios équipage-passagers dépassent tous les usages. Nos chefs ont des étoiles. Nos capitaines ont des records.",
    "plan custom itinerary": "Planifier un itinéraire personnalisé",
    "plan your voyage": "Préparer votre traversée",
    "pristine white sand bays reserved for the few. crystal clear waters, luxury shopping, and sunset sailing in constant trade winds.": "Baies de sable blanc immaculé réservées à quelques privilégiés. Eaux cristallines, shopping de luxe et navigation au coucher du soleil dans des alizés constants.",
    "private client, london": "Client Privé, Londres",
    "reach out to our global charter desks or submit a private enquiry. a voyage architect will respond within 4 hours.": "Contactez nos bureaux de charter mondiaux ou soumettez une demande privée. Un architecte de voyage répondra dans les 4 heures.",
    "reserved for you alone.": "réservé à vous seul.",
    "sail the glamour capital of europe. drop anchor off st. tropez, cruise monaco's port hercules, and dine cliffside in eze.": "Naviguez dans la capitale glamour de l'Europe. Jetez l'ancre au large de St. Tropez, croisez le Port Hercule de Monaco et dînez en bord de falaise à Eze.",
    "specifically for you.": "pour vous, et pour vous seul.",
    "submit private enquiry": "Soumettre une demande privée",
    "terms of charter": "Conditions de la charte",
    "the horizon": "L'Horizon",
    "the horizon standard": "Notre exigence",
    "the onboard": "À bord",
    "true luxury is the absence of friction. we manage every detail of your journey so that your only responsibility is to enjoy the open sea.": "Le véritable luxe est l'absence de friction. Nous gérons chaque détail de votre voyage afin que votre seule responsabilité soit de profiter de la mer ouverte.",
    "turquoise lagoons of utter stillness. access shallow reefs by tender, enjoy private beach dinners on sandbanks, and sleep beneath starlight.": "Lagunes turquoise d'une tranquillité absolue. Accédez aux récifs peu profonds par un annexe, profitez de dîners privés sur la plage sur des bancs de sable et dormez sous les étoiles.",
    "unrivaled scale and sophistication. features a certified helipad, onboard cinema, wellness spa, and two michelin chefs.": "Une échelle et une sophistication inégalées. Comprend un héliport certifié, un cinéma à bord, un spa de bien-être et deux chefs étoilés Michelin.",
    "vibrant towns clinging to cliffs. explore the blue grotto at dawn, anchor off positano at midnight, and experience legendary italian hospitality.": "Villes vibrantes accrochées aux falaises. Explorez la Grotte Bleue à l'aube, jetez l'ancre au large de Positano à minuit et vivez l'hospitalité italienne légendaire.",
    "view fleet": "Voir la flotte",
    "where glamour meets the open sea": "Là où l'élégance rencontre le grand large",
    "words from those who know.": "Les mots de ceux qui savent.",
    "worldwide": "Dans le monde entier",
    "years": "Années",
    "years of excellence": "Années d'Excellence",
    "your information is held in strict confidence and never shared with third parties.": "Vos informations restent strictement confidentielles et ne sont jamais transmises à des tiers.",
    "your voyage architect will respond within 4 hours. all enquiries are treated with complete discretion.": "Votre concepteur de voyage répond sous quatre heures. Toute demande est traitée avec la plus grande discrétion.",
  },
  es: {
    "about horizon": "Sobre nosotros",
    "all 87 destinations": "Los 87 destinos",
    "an icon of contemporary luxury. featuring a glass-bottom pool, private owner's deck, and an expansive beach club.": "Un ícono del lujo contemporáneo. Con una piscina de fondo de cristal, una cubierta privada para el propietario y un extenso club de playa.",
    "avoid the friction of public airports. we coordinate seamless private jet charters and helicopter transfers directly to your yacht's helipad.": "Evita la fricción de los aeropuertos públicos. Coordinamos chárteres de jets privados sin problemas y traslados en helicóptero directamente a la plataforma de su yate.",
    "begin your": "Comienza tu",
    "begin your journey": "Empezar su viaje",
    "bespoke yacht charters and private aviation transfers across the world's most extraordinary waters. curated for those who demand perfection without effort.": "Chárteres de yates a medida y traslados de aviación privada a través de las aguas más extraordinarias del mundo. Curado para aquellos que exigen perfección sin esfuerzo.",
    "best season": "Mejor Temporada",
    "built / refit": "Construido / Refit",
    "caldera sunsets from your private deck": "Las puestas de sol sobre la caldera, desde su cubierta privada",
    "classic lines with modern naval architecture. hand-finished teak decks, mahogany salon, and state-of-the-art rigging.": "Líneas clásicas con arquitectura naval moderna. Cubiertas de teca acabadas a mano, salón de caoba y aparejos de última generación.",
    "client reflections": "Reflexiones de los clientes",
    "client return rate": "Tasa de Retorno de Clientes",
    "communicated upon request": "comunicado bajo petición",
    "design my voyage": "Diseñar mi viaje",
    "discover white-washed villages draped over volcanic cliffs. cruise private coves in folegandros and catch caldera sunsets from your deck.": "Descubre pueblos encalados que se asoman a acantilados volcánicos. Navega por calas privadas en Folegandros y disfruta de los atardeceres de caldera desde tu cubierta.",
    "embarkation from port hercules. champagne welcome and evening anchorage beneath the rock.": "Embarque en Puerto Hércules. Bienvenida con champán y fondeo nocturno al pie del Peñón.",
    "enquire": "Consultar",
    "every vessel carries a premium selection of watersports equipment, from personal submarines and fast tenders to jet skis, foil boards, and diving gear.": "Cada embarcación lleva una selección premium de equipos de deportes acuáticos, desde submarinos personales y lanchas rápidas hasta motos de agua, tablas de foil y equipo de buceo.",
    "every voyage is authored": "Cada travesía se compone",
    "explore our curated portfolio of ultra-luxury vessels available for charter. each yacht is maintained to impeccable standards with hand-selected crews.": "Explora nuestro portafolio curado de embarcaciones ultra-lujosas disponibles para chárter. Cada yate se mantiene a estándares impecables con tripulaciones seleccionadas a mano.",
    "figures updated in real time · est. monaco 1997": "Cifras actualizadas en tiempo real · Est. Mónaco 1997",
    "for the true explorer. navigate through towering glaciers, witness polar wildlife in silence, and experience the midnight sun.": "Para el verdadero explorador. Navega a través de glaciares imponentes, observa la fauna polar en silencio y experimenta el sol de medianoche.",
    "ice-class explorer designed for global expeditions. complete with private submarine, heli-hangar, and science lab.": "Explorador de clase de hielo diseñado para expediciones globales. Completo con submarino privado, hangar para helicópteros y laboratorio científico.",
    "monaco to ibiza": "Mónaco a Ibiza",
    "navigate the world's most exceptional coastal waters. from sun-drenched mediterranean shores to untouched polar wilderness.": "Navega por las aguas costeras más excepcionales del mundo. Desde las costas mediterráneas bañadas por el sol hasta la salvaje polar intacta.",
    "our fleet": "Nuestra flota",
    "our fleet spans 18 to 92 metres. our crew-to-guest ratios exceed any industry standard. our chefs hold stars. our captains hold records.": "Nuestra flota va de dieciocho a noventa y dos metros. Nuestra proporción tripulación-pasajeros supera cualquier norma. Nuestros chefs tienen estrellas. Nuestros capitanes, récords.",
    "plan custom itinerary": "Planificar itinerario personalizado",
    "plan your voyage": "Planifique su travesía",
    "pristine white sand bays reserved for the few. crystal clear waters, luxury shopping, and sunset sailing in constant trade winds.": "Bahías de arena blanca prístina reservadas para unos pocos. Aguas cristalinas, compras de lujo y navegación al atardecer en vientos alisios constantes.",
    "private client, london": "Cliente Privado, Londres",
    "reach out to our global charter desks or submit a private enquiry. a voyage architect will respond within 4 hours.": "Póngase en contacto con nuestras oficinas de chárter globales o envíe una consulta privada. Un arquitecto de viajes responderá en un plazo de 4 horas.",
    "reserved for you alone.": "reservado solo para usted.",
    "sail the glamour capital of europe. drop anchor off st. tropez, cruise monaco's port hercules, and dine cliffside in eze.": "Navega por la capital del glamour de Europa. Echa el ancla frente a St. Tropez, navega por el Puerto Hércules de Mónaco y cena en un acantilado en Eze.",
    "specifically for you.": "para usted, y solo para usted.",
    "submit private enquiry": "Enviar consulta privada",
    "terms of charter": "Términos de la carta",
    "the horizon": "El Horizonte",
    "the horizon standard": "Nuestra exigencia",
    "the onboard": "A bordo",
    "true luxury is the absence of friction. we manage every detail of your journey so that your only responsibility is to enjoy the open sea.": "El verdadero lujo es la ausencia de fricción. Gestionamos cada detalle de su viaje para que su única responsabilidad sea disfrutar del mar abierto.",
    "turquoise lagoons of utter stillness. access shallow reefs by tender, enjoy private beach dinners on sandbanks, and sleep beneath starlight.": "Lagunas turquesas de total tranquilidad. Accede a los arrecifes poco profundos en un bote auxiliar, disfruta de cenas privadas en la playa sobre bancos de arena y duerme bajo la luz de las estrellas.",
    "unrivaled scale and sophistication. features a certified helipad, onboard cinema, wellness spa, and two michelin chefs.": "Escala y sofisticación sin igual. Cuenta con un helipuerto certificado, cine a bordo, spa de bienestar y dos chefs Michelin.",
    "vibrant towns clinging to cliffs. explore the blue grotto at dawn, anchor off positano at midnight, and experience legendary italian hospitality.": "Pueblos vibrantes aferrados a los acantilados. Explora la Gruta Azul al amanecer, ancla frente a Positano a medianoche y experimenta la legendaria hospitalidad italiana.",
    "view fleet": "Ver flota",
    "where glamour meets the open sea": "Donde la elegancia se encuentra con el mar abierto",
    "words from those who know.": "Las palabras de quienes saben.",
    "worldwide": "En todo el mundo",
    "years": "Años",
    "years of excellence": "Años de Excelencia",
    "your information is held in strict confidence and never shared with third parties.": "Sus datos se mantienen en estricta confidencialidad y nunca se ceden a terceros.",
    "your voyage architect will respond within 4 hours. all enquiries are treated with complete discretion.": "Su diseñador de viaje responde en cuatro horas. Toda consulta se trata con la mayor discreción.",
  },
  de: {
    "about horizon": "Über uns",
    "all 87 destinations": "Alle 87 Ziele",
    "an icon of contemporary luxury. featuring a glass-bottom pool, private owner's deck, and an expansive beach club.": "Ein Symbol zeitgenössischen Luxus. Mit einem Glasbodenpool, einem privaten Deck für den Eigentümer und einem großzügigen Strandclub.",
    "avoid the friction of public airports. we coordinate seamless private jet charters and helicopter transfers directly to your yacht's helipad.": "Vermeiden Sie die Reibung öffentlicher Flughäfen. Wir koordinieren nahtlose Privatjet-Charter und Hubschraubertransfers direkt zu Ihrem Yachthubschrauberlandeplatz.",
    "begin your": "Beginnen Sie Ihr",
    "begin your journey": "Ihre Reise beginnen",
    "bespoke yacht charters and private aviation transfers across the world's most extraordinary waters. curated for those who demand perfection without effort.": "Maßgeschneiderte Yachtcharter und private Flugzeugtransfers über die außergewöhnlichsten Gewässer der Welt. Kuratiert für diejenigen, die Perfektion ohne Mühe verlangen.",
    "best season": "Beste Saison",
    "built / refit": "Bau / Umbau",
    "caldera sunsets from your private deck": "Sonnenuntergänge über der Caldera, von Ihrem eigenen Deck",
    "classic lines with modern naval architecture. hand-finished teak decks, mahogany salon, and state-of-the-art rigging.": "Klassische Linien mit moderner Schiffsarchitektur. Handgefertigte Teakdecks, Mahagoni-Salon und modernste Takelage.",
    "client reflections": "Kundenreflexionen",
    "client return rate": "Kundenrücklaufquote",
    "communicated upon request": "auf Anfrage mitgeteilt",
    "design my voyage": "Gestalten Sie meine Reise",
    "discover white-washed villages draped over volcanic cliffs. cruise private coves in folegandros and catch caldera sunsets from your deck.": "Entdecken Sie weiß getünchte Dörfer, die sich über vulkanische Klippen erstrecken. Kreuzen Sie in privaten Buchten in Folegandros und genießen Sie die Sonnenuntergänge über der Caldera von Ihrem Deck.",
    "embarkation from port hercules. champagne welcome and evening anchorage beneath the rock.": "Einschiffung im Port Hercule. Champagnerempfang und abendlicher Ankerplatz am Fuß des Felsens.",
    "enquire": "Anfragen",
    "every vessel carries a premium selection of watersports equipment, from personal submarines and fast tenders to jet skis, foil boards, and diving gear.": "Jedes Schiff führt eine Premium-Auswahl an Wassersportausrüstung, von persönlichen U-Booten und schnellen Beibooten bis hin zu Jetskis, Foil-Boards und Tauchausrüstung.",
    "every voyage is authored": "Jede Reise wird geschrieben",
    "explore our curated portfolio of ultra-luxury vessels available for charter. each yacht is maintained to impeccable standards with hand-selected crews.": "Entdecken Sie unser kuratiertes Portfolio von ultraluxuriösen Schiffen, die zur Charter verfügbar sind. Jacht wird nach tadellosen Standards mit handverlesenen Crews gewartet.",
    "figures updated in real time · est. monaco 1997": "Zahlen in Echtzeit aktualisiert · Est. Monaco 1997",
    "for the true explorer. navigate through towering glaciers, witness polar wildlife in silence, and experience the midnight sun.": "Für den wahren Entdecker. Navigieren Sie durch hoch aufragende Gletscher, beobachten Sie die polare Tierwelt in Stille und erleben Sie die Mitternachtssonne.",
    "ice-class explorer designed for global expeditions. complete with private submarine, heli-hangar, and science lab.": "Eisklasse-Explorer, entworfen für globale Expeditionen. Komplett mit privatem U-Boot, Helihangar und Wissenschaftslabor.",
    "monaco to ibiza": "Monaco nach Ibiza",
    "navigate the world's most exceptional coastal waters. from sun-drenched mediterranean shores to untouched polar wilderness.": "Navigieren Sie durch die außergewöhnlichsten Küstengewässer der Welt. Von sonnenverwöhnten Mittelmeerküsten bis hin zu unberührter polarer Wildnis.",
    "our fleet": "Unsere Flotte",
    "our fleet spans 18 to 92 metres. our crew-to-guest ratios exceed any industry standard. our chefs hold stars. our captains hold records.": "Unsere Flotte reicht von achtzehn bis zweiundneunzig Metern. Unser Verhältnis von Crew zu Gästen übertrifft jeden Standard. Unsere Köche haben Sterne. Unsere Kapitäne halten Rekorde.",
    "plan custom itinerary": "Planen Sie eine individuelle Reiseroute",
    "plan your voyage": "Ihre Reise planen",
    "pristine white sand bays reserved for the few. crystal clear waters, luxury shopping, and sunset sailing in constant trade winds.": "Unberührte weiße Sandbuchten, die nur für wenige reserviert sind. Kristallklares Wasser, Luxus-Shopping und Segeln bei Sonnenuntergang in konstanten Passatwinden.",
    "private client, london": "Privatkunde, London",
    "reach out to our global charter desks or submit a private enquiry. a voyage architect will respond within 4 hours.": "Wenden Sie sich an unsere globalen Charterbüros oder senden Sie eine private Anfrage. Ein Reisearchitekt wird innerhalb von 4 Stunden antworten.",
    "reserved for you alone.": "allein für Sie reserviert.",
    "sail the glamour capital of europe. drop anchor off st. tropez, cruise monaco's port hercules, and dine cliffside in eze.": "Segeln Sie in der Glamourhauptstadt Europas. Lassen Sie den Anker vor St. Tropez fallen, kreuzen Sie im Hafen von Monaco und speisen Sie an der Klippe in Eze.",
    "specifically for you.": "eigens für Sie.",
    "submit private enquiry": "Private Anfrage einreichen",
    "terms of charter": "Bedingungen der Charta",
    "the horizon": "Der Horizont",
    "the horizon standard": "Unser Anspruch",
    "the onboard": "An Bord",
    "true luxury is the absence of friction. we manage every detail of your journey so that your only responsibility is to enjoy the open sea.": "Wahrer Luxus ist die Abwesenheit von Reibung. Wir kümmern uns um jedes Detail Ihrer Reise, damit Ihre einzige Verantwortung darin besteht, das offene Meer zu genießen.",
    "turquoise lagoons of utter stillness. access shallow reefs by tender, enjoy private beach dinners on sandbanks, and sleep beneath starlight.": "Türkisfarbene Lagunen völliger Stille. Erreichen Sie flache Riffe mit dem Beiboot, genießen Sie private Stranddinner auf Sandbänken und schlafen Sie unter dem Sternenlicht.",
    "unrivaled scale and sophistication. features a certified helipad, onboard cinema, wellness spa, and two michelin chefs.": "Unvergleichliche Größe und Raffinesse. Verfügt über einen zertifizierten Hubschrauberlandeplatz, ein Bordkino, ein Wellness-Spa und zwei Michelin-Köche.",
    "vibrant towns clinging to cliffs. explore the blue grotto at dawn, anchor off positano at midnight, and experience legendary italian hospitality.": "Lebendige Städte, die an Klippen haften. Erkunden Sie die Blaue Grotte bei Sonnenaufgang, ankern Sie um Mitternacht vor Positano und erleben Sie legendäre italienische Gastfreundschaft.",
    "view fleet": "Flotte anzeigen",
    "where glamour meets the open sea": "Wo Eleganz auf die offene See trifft",
    "words from those who know.": "Worte derer, die es wissen.",
    "worldwide": "Weltweit",
    "years": "Jahre",
    "years of excellence": "Jahre der Exzellenz",
    "your information is held in strict confidence and never shared with third parties.": "Ihre Angaben bleiben streng vertraulich und werden nie an Dritte weitergegeben.",
    "your voyage architect will respond within 4 hours. all enquiries are treated with complete discretion.": "Ihr Reiseplaner antwortet binnen vier Stunden. Jede Anfrage wird mit größter Diskretion behandelt.",
  },
  pt: {
    "about horizon": "Sobre nós",
    "all 87 destinations": "Os 87 destinos",
    "an icon of contemporary luxury. featuring a glass-bottom pool, private owner's deck, and an expansive beach club.": "Um ícone do luxo contemporâneo. Com uma piscina de fundo de vidro, um deck privado para o proprietário e um extenso clube de praia.",
    "avoid the friction of public airports. we coordinate seamless private jet charters and helicopter transfers directly to your yacht's helipad.": "Evite a fricção dos aeroportos públicos. Coordenamos charters de jatos privados sem interrupções e transferências de helicóptero diretamente para o heliponto do seu iate.",
    "begin your": "Comece o seu",
    "begin your journey": "Começar a sua viagem",
    "bespoke yacht charters and private aviation transfers across the world's most extraordinary waters. curated for those who demand perfection without effort.": "Charters de iates sob medida e transferências de aviação privada através das águas mais extraordinárias do mundo. Curado para aqueles que exigem perfeição sem esforço.",
    "best season": "Melhor Época",
    "built / refit": "Construído / Refit",
    "caldera sunsets from your private deck": "Os pores do sol sobre a caldeira, do seu convés privado",
    "classic lines with modern naval architecture. hand-finished teak decks, mahogany salon, and state-of-the-art rigging.": "Linhas clássicas com arquitetura naval moderna. Decks de teca acabados à mão, salão de mogno e aparelhagem de última geração.",
    "client reflections": "Reflexões dos clientes",
    "client return rate": "Taxa de Retorno de Clientes",
    "communicated upon request": "comunicado mediante pedido",
    "design my voyage": "Desenhar a minha viagem",
    "discover white-washed villages draped over volcanic cliffs. cruise private coves in folegandros and catch caldera sunsets from your deck.": "Descubra aldeias caiadas de branco que se estendem sobre falésias vulcânicas. Navegue em enseadas privadas em Folegandros e aprecie os pores do sol da caldeira a partir do seu deck.",
    "embarkation from port hercules. champagne welcome and evening anchorage beneath the rock.": "Embarque em Port Hercule. Receção com champanhe e fundeadouro noturno ao pé do Rochedo.",
    "enquire": "Pedir informações",
    "every vessel carries a premium selection of watersports equipment, from personal submarines and fast tenders to jet skis, foil boards, and diving gear.": "Cada embarcação transporta uma seleção premium de equipamentos de desportos aquáticos, desde submarinos pessoais e lanchas rápidas até jet skis, pranchas de foil e equipamentos de mergulho.",
    "every voyage is authored": "Cada travessia é composta",
    "explore our curated portfolio of ultra-luxury vessels available for charter. each yacht is maintained to impeccable standards with hand-selected crews.": "Explore o nosso portfólio selecionado de embarcações ultra-luxuosas disponíveis para charter. Cada iate é mantido a padrões impecáveis com tripulações selecionadas à mão.",
    "figures updated in real time · est. monaco 1997": "Números atualizados em tempo real · Est. Mónaco 1997",
    "for the true explorer. navigate through towering glaciers, witness polar wildlife in silence, and experience the midnight sun.": "Para o verdadeiro explorador. Navegue através de geleiras imponentes, testemunhe a vida selvagem polar em silêncio e experimente o sol da meia-noite.",
    "ice-class explorer designed for global expeditions. complete with private submarine, heli-hangar, and science lab.": "Explorador de classe de gelo projetado para expedições globais. Completo com submarino privado, hangar de helicópteros e laboratório científico.",
    "monaco to ibiza": "Mónaco para Ibiza",
    "navigate the world's most exceptional coastal waters. from sun-drenched mediterranean shores to untouched polar wilderness.": "Navegue pelas águas costeiras mais excepcionais do mundo. Desde as costas mediterrânicas banhadas pelo sol até a natureza polar intocada.",
    "our fleet": "A nossa frota",
    "our fleet spans 18 to 92 metres. our crew-to-guest ratios exceed any industry standard. our chefs hold stars. our captains hold records.": "A nossa frota vai de dezoito a noventa e dois metros. A nossa proporção tripulação-passageiros supera qualquer norma. Os nossos chefes têm estrelas. Os nossos capitães, recordes.",
    "plan custom itinerary": "Planeie um itinerário personalizado",
    "plan your voyage": "Planeie a sua travessia",
    "pristine white sand bays reserved for the few. crystal clear waters, luxury shopping, and sunset sailing in constant trade winds.": "Baías de areia branca imaculada reservadas para poucos. Águas cristalinas, compras de luxo e navegação ao pôr do sol em ventos alísios constantes.",
    "private client, london": "Cliente Privado, Londres",
    "reach out to our global charter desks or submit a private enquiry. a voyage architect will respond within 4 hours.": "Entre em contato com os nossos escritórios de charter globais ou envie uma consulta privada. Um arquiteto de viagens responderá em 4 horas.",
    "reserved for you alone.": "reservado só para si.",
    "sail the glamour capital of europe. drop anchor off st. tropez, cruise monaco's port hercules, and dine cliffside in eze.": "Navegue pela capital do glamour da Europa. Largue âncora ao largo de St. Tropez, navegue pelo Porto Hércules de Mônaco e jante à beira do penhasco em Eze.",
    "specifically for you.": "para si, e só para si.",
    "submit private enquiry": "Enviar pedido privado",
    "terms of charter": "Termos da carta",
    "the horizon": "O Horizonte",
    "the horizon standard": "A nossa exigência",
    "the onboard": "A bordo",
    "true luxury is the absence of friction. we manage every detail of your journey so that your only responsibility is to enjoy the open sea.": "O verdadeiro luxo é a ausência de atrito. Gerimos cada detalhe da sua viagem para que a sua única responsabilidade seja desfrutar do mar aberto.",
    "turquoise lagoons of utter stillness. access shallow reefs by tender, enjoy private beach dinners on sandbanks, and sleep beneath starlight.": "Lagoas turquesas de total tranquilidade. Acesse recifes rasos de barco auxiliar, desfrute de jantares privados na praia em bancos de areia e durma sob a luz das estrelas.",
    "unrivaled scale and sophistication. features a certified helipad, onboard cinema, wellness spa, and two michelin chefs.": "Escala e sofisticação inigualáveis. Inclui um heliporto certificado, cinema a bordo, spa de bem-estar e dois chefs Michelin.",
    "vibrant towns clinging to cliffs. explore the blue grotto at dawn, anchor off positano at midnight, and experience legendary italian hospitality.": "Cidades vibrantes agarradas às falésias. Explore a Gruta Azul ao amanhecer, ancore ao largo de Positano à meia-noite e experimente a lendária hospitalidade italiana.",
    "view fleet": "Ver frota",
    "where glamour meets the open sea": "Onde a elegância encontra o mar aberto",
    "words from those who know.": "As palavras de quem sabe.",
    "worldwide": "Em todo o mundo",
    "years": "Anos",
    "years of excellence": "Anos de Excelência",
    "your information is held in strict confidence and never shared with third parties.": "Os seus dados mantêm-se em estrita confidencialidade e nunca são cedidos a terceiros.",
    "your voyage architect will respond within 4 hours. all enquiries are treated with complete discretion.": "O seu criador de viagem responde em quatro horas. Todo o pedido é tratado com a maior discrição.",
  },
};
