/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "archive": "Archives",
    "full archive": "Toutes les archives",
    "global operations": "Nos implantations",
    "global inventory": "Stock mondial",
    "global sourcing": "Approvisionnement mondial",
    "residential": "Résidentiel",
    "commercial": "Tertiaire",
    "cultural": "Culturel",
    "countries": "Pays",
    "completed projects": "Projets livrés",
    "publications": "Publications",
    "location:": "Lieu :",
    "materials": "Matériaux",
    "philosophy": "Philosophie",
    "anatomy": "Anatomie",
    "heritage": "Héritage",
    "brewing": "L'extraction",
    "origins": "Origines",
    "ovens": "Nos fours",
    "subscription": "Abonnement",
    "fresh batch": "Fournée du jour",
    "modern.": "Moderne.",
    "artisanal.": "Artisanal.",
    "celestial.": "Céleste.",
    "void &": "Le vide",
    "volume.": "et le volume.",
    "pure": "Volume",
    "mastery of": "La maîtrise",
    "duration.": "de la durée.",
    "examine portals": "Voir les projets",
    "structure / light / materiality / void": "STRUCTURE / LUMIÈRE / MATIÈRE / VIDE",
    "riba awards": "Prix RIBA",
    "established 1924 // geneva, ch": "Fondée en 1924 // Genève, Suisse",
    "swiss alps, ch": "Alpes suisses, Suisse",
    "dubai, uae": "Dubaï, Émirats arabes unis",
    "tokyo, jp": "Tokyo, Japon",
    "oslo, no": "Oslo, Norvège",
    "seoul, kr": "Séoul, Corée du Sud",
    "berlin, de": "Berlin, Allemagne",
    "kyoto, jp": "Kyoto, Japon",
    "malibu, ca": "Malibu, Californie",
    "projects.": "Réalisations.",
    "art direction": "Direction artistique",
    "retail": "Point de vente",
    "sourdough": "Pain au levain",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentation de 48 heures. Croûte au charbon végétal. Assemblage de blés anciens.",
    "aop butter. 256 layers. golden honeycomb structure.": "Beurre AOP. 256 couches. Alvéolage doré.",
    "high hydration. stone-baked. intense caramelization.": "Forte hydratation. Cuisson sur pierre. Caramélisation intense.",
    "add_to_bag": "Ajouter_au_panier",
    "baking": "Protocole",
    "protocol.": "de cuisson.",
    "hydration ratio": "Taux d'hydratation",
    "maximizing crumb elasticity through high-hydration dough processing.": "Une mie plus élastique, obtenue par un pétrissage à forte hydratation.",
    "cold fermentation": "Fermentation à froid",
    "the": "La",
    "daily batch.": "fournée du jour.",
    "add to bag": "Ajouter au Panier",
    "add to batch order": "AJOUTER À LA COMMANDE EN LOT",
    "all flours are stone-milled in-house from organic regenerative farms.": "Toutes nos farines sont moulues sur meule de pierre, chez nous, à partir de fermes bio en agriculture régénératrice.",
    "all our sourdough loaves are 100% plant-based (flour, water, salt). our viennoiseries utilize high-grade aop butter and local organic eggs.": "Tous nos pains au levain sont 100 % d'origine végétale (Farine, Eau, Sel). Nos viennoiseries utilisent du beurre AOP de haute qualité et des œufs biologiques locaux.",
    "are your products vegan?": "Vos produits sont-ils végétaliens ?",
    "do you offer wholesale partnerships?": "Proposez-vous des partenariats en gros ?",
    "explore the batch": "Découvrir la fournée",
    "high-hydration molecular baking. stone hearth methodology. precision-engineered for the modern palate.": "Boulangerie moléculaire à haute hydratation. Méthodologie de four en pierre. Conçu avec précision pour le palais moderne.",
    "how should i store my sourdough?": "Comment devrais-je conserver mon pain au levain ?",
    "in grain we trust": "Au grain nous nous fions",
    "intense heat burst for maximum oven spring and thin, glass-like crust.": "Éclat de chaleur intense pour un maximum de levée au four et une croûte fine et vitreuse.",
    "never refrigerate. store at room temperature in a paper bag for the first 48 hours, then transition to a cloth bag. sourdough of this quality matures over time.": "Ne jamais réfrigérer. Conservez à température ambiante dans un sac en papier pendant les 48 premières heures, puis passez à un sac en tissu. Le pain au levain de cette qualité mûrit avec le temps.",
    "order bread": "COMMANDER DU PAIN",
    "our weekly 'manifesto' box includes 2 seasonal loaves, 4 viennoiseries, and a jar of our cultured butter. limited to 100 subscribers per city.": "Notre boîte hebdomadaire 'Manifesto' comprend 2 pains de saison, 4 viennoiseries et un pot de notre beurre fermenté. Limité à 100 abonnés par ville.",
    "precise water-to-flour ratio adjusted daily for humidity.": "Ratio précis d'eau à farine ajusté quotidiennement en fonction de l'humidité.",
    "ready now": "PRÊT MAINTENANT",
    "slow enzymatic breakdown for optimal digestibility and complex flavor profile.": "Décomposition enzymatique lente pour une digestibilité optimale et un profil de saveur complexe.",
    "the structural infrastructure for the next generation of artisanal baking. est. 2026. precision baked. stone milled.": "L'infrastructure structurelle pour la prochaine génération de boulangerie artisanale. Est. 2026. Cuit avec précision. Moulue à la pierre.",
    "the void loaf": "LE PAIN DU VIDE",
    "we treat bread as structural engineering. from grain analysis to steam-injection cycles, precision is our only ingredient.": "Nous considérons le pain comme de l'ingénierie structurelle. De l'analyse des grains aux cycles d'injection de vapeur, la précision est notre seul ingrédient.",
    "what is the 'subscription box'?": "Qu'est-ce que la formule d'abonnement ?",
    "yes. we supply a limited number of michelin-starred restaurants and specialty coffee shops. contact our 'network control' for institutional inquiries.": "Oui. Nous fournissons un nombre limité de restaurants étoilés au Michelin et de cafés spécialisés. Contactez notre 'Contrôle Réseau' pour les demandes institutionnelles.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "archive": "Archivo",
    "full archive": "Todo el archivo",
    "global operations": "Nuestras sedes",
    "global inventory": "Inventario mundial",
    "global sourcing": "Abastecimiento mundial",
    "residential": "Residencial",
    "commercial": "Terciario",
    "cultural": "Cultural",
    "countries": "Países",
    "completed projects": "Proyectos entregados",
    "publications": "Publicaciones",
    "location:": "Lugar:",
    "materials": "Materiales",
    "philosophy": "Filosofía",
    "anatomy": "Anatomía",
    "heritage": "Herencia",
    "brewing": "La extracción",
    "origins": "Orígenes",
    "ovens": "Nuestros hornos",
    "subscription": "Suscripción",
    "fresh batch": "Hornada del día",
    "modern.": "Moderno.",
    "artisanal.": "Artesanal.",
    "celestial.": "Celeste.",
    "void &": "El vacío",
    "volume.": "y el volumen.",
    "pure": "Volumen",
    "mastery of": "El dominio",
    "duration.": "de la duración.",
    "examine portals": "Ver los proyectos",
    "structure / light / materiality / void": "ESTRUCTURA / LUZ / MATERIA / VACÍO",
    "riba awards": "Premios RIBA",
    "established 1924 // geneva, ch": "Fundada en 1924 // Ginebra, Suiza",
    "swiss alps, ch": "Alpes suizos, Suiza",
    "dubai, uae": "Dubái, Emiratos Árabes Unidos",
    "tokyo, jp": "Tokio, Japón",
    "oslo, no": "Oslo, Noruega",
    "seoul, kr": "Seúl, Corea del Sur",
    "berlin, de": "Berlín, Alemania",
    "kyoto, jp": "Kioto, Japón",
    "malibu, ca": "Malibú, California",
    "projects.": "Trabajos.",
    "art direction": "Dirección de arte",
    "retail": "Punto de venta",
    "sourdough": "Pan de masa madre",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentación de 48 horas. Corteza al carbón vegetal. Mezcla de granos antiguos.",
    "aop butter. 256 layers. golden honeycomb structure.": "Mantequilla DOP. 256 capas. Alveolado dorado.",
    "high hydration. stone-baked. intense caramelization.": "Alta hidratación. Cocción en piedra. Caramelización intensa.",
    "add_to_bag": "Añadir_a_la_cesta",
    "baking": "Protocolo",
    "protocol.": "de cocción.",
    "hydration ratio": "Tasa de hidratación",
    "maximizing crumb elasticity through high-hydration dough processing.": "Una miga más elástica, obtenida mediante un amasado de alta hidratación.",
    "cold fermentation": "Fermentación en frío",
    "the": "La",
    "daily batch.": "hornada del día.",
    "add to bag": "Añadir a la Bolsa",
    "add to batch order": "AÑADIR A LA ORDEN POR LOTE",
    "all flours are stone-milled in-house from organic regenerative farms.": "Todas nuestras harinas se muelen a la piedra, en casa, a partir de fincas ecológicas de agricultura regenerativa.",
    "all our sourdough loaves are 100% plant-based (flour, water, salt). our viennoiseries utilize high-grade aop butter and local organic eggs.": "Todos nuestros panes de masa madre son 100% de origen vegetal (Harina, Agua, Sal). Nuestras viennoiseries utilizan mantequilla AOP de alta calidad y huevos orgánicos locales.",
    "are your products vegan?": "¿Sus productos son veganos?",
    "do you offer wholesale partnerships?": "¿Ofrecen acuerdos al por mayor?",
    "explore the batch": "Descubrir la hornada",
    "high-hydration molecular baking. stone hearth methodology. precision-engineered for the modern palate.": "Panadería molecular de alta hidratación. Metodología de horno de piedra. Diseñado con precisión para el paladar moderno.",
    "how should i store my sourdough?": "¿Cómo debo almacenar mi masa madre?",
    "in grain we trust": "En el grano confiamos",
    "intense heat burst for maximum oven spring and thin, glass-like crust.": "Explosión de calor intenso para un máximo crecimiento en el horno y una corteza fina y similar al vidrio.",
    "never refrigerate. store at room temperature in a paper bag for the first 48 hours, then transition to a cloth bag. sourdough of this quality matures over time.": "Nunca refrigera. Almacene a temperatura ambiente en una bolsa de papel durante las primeras 48 horas, luego cambie a una bolsa de tela. La masa madre de esta calidad madura con el tiempo.",
    "order bread": "PEDIR PAN",
    "our weekly 'manifesto' box includes 2 seasonal loaves, 4 viennoiseries, and a jar of our cultured butter. limited to 100 subscribers per city.": "Nuestra caja semanal 'Manifesto' incluye 2 panes de temporada, 4 viennoiseries y un tarro de nuestra mantequilla cultivada. Limitado a 100 suscriptores por ciudad.",
    "precise water-to-flour ratio adjusted daily for humidity.": "Relación precisa de agua a harina ajustada diariamente para la humedad.",
    "ready now": "LISTO AHORA",
    "slow enzymatic breakdown for optimal digestibility and complex flavor profile.": "Descomposición enzimática lenta para una digestibilidad óptima y un perfil de sabor complejo.",
    "the structural infrastructure for the next generation of artisanal baking. est. 2026. precision baked. stone milled.": "La infraestructura estructural para la próxima generación de panadería artesanal. Est. 2026. Horneado con precisión. Molido en piedra.",
    "the void loaf": "EL PAN DEL VACÍO",
    "we treat bread as structural engineering. from grain analysis to steam-injection cycles, precision is our only ingredient.": "Tratamos el pan como ingeniería estructural. Desde el análisis de granos hasta los ciclos de inyección de vapor, la precisión es nuestro único ingrediente.",
    "what is the 'subscription box'?": "¿Qué es la caja por suscripción?",
    "yes. we supply a limited number of michelin-starred restaurants and specialty coffee shops. contact our 'network control' for institutional inquiries.": "Sí. Suministramos un número limitado de restaurantes con estrellas Michelin y cafeterías especializadas. Contacta con nuestro 'Control de Red' para consultas institucionales.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "archive": "Archiv",
    "full archive": "Gesamtes Archiv",
    "global operations": "Unsere Standorte",
    "global inventory": "Weltweiter Bestand",
    "global sourcing": "Weltweite Beschaffung",
    "residential": "Wohnbau",
    "commercial": "Gewerbe",
    "cultural": "Kultur",
    "countries": "Länder",
    "completed projects": "Fertiggestellte Projekte",
    "publications": "Publikationen",
    "location:": "Ort:",
    "materials": "Werkstoffe",
    "philosophy": "Philosophie",
    "anatomy": "Anatomie",
    "heritage": "Erbe",
    "brewing": "Die Zubereitung",
    "origins": "Herkünfte",
    "ovens": "Unsere Öfen",
    "subscription": "Abonnement",
    "fresh batch": "Frische Charge",
    "modern.": "Modern.",
    "artisanal.": "Handwerklich.",
    "celestial.": "Himmlisch.",
    "void &": "Leere und",
    "volume.": "Volumen.",
    "pure": "Reines",
    "mastery of": "Die Beherrschung",
    "duration.": "der Dauer.",
    "examine portals": "Projekte ansehen",
    "structure / light / materiality / void": "STRUKTUR / LICHT / MATERIAL / LEERE",
    "riba awards": "RIBA-Preise",
    "established 1924 // geneva, ch": "Gegründet 1924 // Genf, Schweiz",
    "swiss alps, ch": "Schweizer Alpen, CH",
    "dubai, uae": "Dubai, VAE",
    "tokyo, jp": "Tokio, Japan",
    "oslo, no": "Oslo, Norwegen",
    "seoul, kr": "Seoul, Südkorea",
    "berlin, de": "Berlin, Deutschland",
    "kyoto, jp": "Kyoto, Japan",
    "malibu, ca": "Malibu, Kalifornien",
    "projects.": "Arbeiten.",
    "art direction": "Art Direction",
    "retail": "Einzelhandel",
    "sourdough": "Sauerteigbrot",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "48 Stunden Fermentation. Kruste mit Aktivkohle. Mischung alter Getreidesorten.",
    "aop butter. 256 layers. golden honeycomb structure.": "AOP-Butter. 256 Schichten. Goldene Wabenstruktur.",
    "high hydration. stone-baked. intense caramelization.": "Hohe Hydratation. Steinofengebacken. Intensive Karamellisierung.",
    "add_to_bag": "In_den_Korb",
    "baking": "Back-",
    "protocol.": "protokoll.",
    "hydration ratio": "Hydratationsgrad",
    "maximizing crumb elasticity through high-hydration dough processing.": "Elastischere Krume durch Teigführung mit hoher Hydratation.",
    "cold fermentation": "Kalte Führung",
    "the": "Die",
    "daily batch.": "Tagescharge.",
    "add to bag": "In den Warenkorb legen",
    "add to batch order": "ZUR SAMMELBESTELLUNG HINZUFÜGEN",
    "all flours are stone-milled in-house from organic regenerative farms.": "Alle Mehle mahlen wir im Haus auf Steinmühlen, aus Bio-Höfen mit regenerativer Landwirtschaft.",
    "all our sourdough loaves are 100% plant-based (flour, water, salt). our viennoiseries utilize high-grade aop butter and local organic eggs.": "Alle unsere Sauerteigbrote sind 100 % pflanzlich (Mehl, Wasser, Salz). Unsere Gebäckstücke verwenden hochwertige AOP-Butter und lokale Bio-Eier.",
    "are your products vegan?": "Sind Ihre Produkte vegan?",
    "do you offer wholesale partnerships?": "Bieten Sie Großhandelspartnerschaften an?",
    "explore the batch": "Die Charge entdecken",
    "high-hydration molecular baking. stone hearth methodology. precision-engineered for the modern palate.": "Molekulare Backkunst mit hoher Hydration. Steinofenmethodik. Präzise für den modernen Gaumen entwickelt.",
    "how should i store my sourdough?": "Wie sollte ich mein Sauerteigbrot lagern?",
    "in grain we trust": "Wir vertrauen dem Korn",
    "intense heat burst for maximum oven spring and thin, glass-like crust.": "Intensiver Hitzestoß für maximalen Ofensprung und dünne, glasartige Kruste.",
    "never refrigerate. store at room temperature in a paper bag for the first 48 hours, then transition to a cloth bag. sourdough of this quality matures over time.": "Nie im Kühlschrank lagern. Die ersten 48 Stunden bei Raumtemperatur in einer Papiertüte aufbewahren, dann in eine Stofftasche wechseln. Sauerteig dieser Qualität reift mit der Zeit.",
    "order bread": "BROT BESTELLEN",
    "our weekly 'manifesto' box includes 2 seasonal loaves, 4 viennoiseries, and a jar of our cultured butter. limited to 100 subscribers per city.": "Unsere wöchentliche 'Manifesto'-Box enthält 2 saisonale Brote, 4 Gebäckstücke und ein Glas unserer kultivierten Butter. Begrenzte Anzahl von 100 Abonnenten pro Stadt.",
    "precise water-to-flour ratio adjusted daily for humidity.": "Präzises Wasser-zu-Mehl-Verhältnis, das täglich an die Luftfeuchtigkeit angepasst wird.",
    "ready now": "JETZT BEREIT",
    "slow enzymatic breakdown for optimal digestibility and complex flavor profile.": "Langsame enzymatische Zersetzung für optimale Verdaulichkeit und komplexes Geschmacksprofil.",
    "the structural infrastructure for the next generation of artisanal baking. est. 2026. precision baked. stone milled.": "Die strukturelle Infrastruktur für die nächste Generation des handwerklichen Backens. Est. 2026. Präzise gebacken. Steinmühle.",
    "the void loaf": "DER LEERE BROT",
    "we treat bread as structural engineering. from grain analysis to steam-injection cycles, precision is our only ingredient.": "Wir behandeln Brot als Strukturengineering. Von der Getreideanalyse bis zu Dampfinjektionszyklen ist Präzision unsere einzige Zutat.",
    "what is the 'subscription box'?": "Was ist die Abo-Box?",
    "yes. we supply a limited number of michelin-starred restaurants and specialty coffee shops. contact our 'network control' for institutional inquiries.": "Ja. Wir beliefern eine begrenzte Anzahl von mit Michelin-Sternen ausgezeichneten Restaurants und Spezialkaffeeshops. Kontaktieren Sie unser 'Netzwerk-Kontrolle' für institutionelle Anfragen.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "archive": "Arquivo",
    "full archive": "Todo o arquivo",
    "global operations": "As nossas implantações",
    "global inventory": "Inventário mundial",
    "global sourcing": "Aprovisionamento mundial",
    "residential": "Residencial",
    "commercial": "Terciário",
    "cultural": "Cultural",
    "countries": "Países",
    "completed projects": "Projetos entregues",
    "publications": "Publicações",
    "location:": "Local:",
    "materials": "Materiais",
    "philosophy": "Filosofia",
    "anatomy": "Anatomia",
    "heritage": "Herança",
    "brewing": "A extração",
    "origins": "Origens",
    "ovens": "Os nossos fornos",
    "subscription": "Assinatura",
    "fresh batch": "Fornada do dia",
    "modern.": "Moderno.",
    "artisanal.": "Artesanal.",
    "celestial.": "Celeste.",
    "void &": "O vazio",
    "volume.": "e o volume.",
    "pure": "Volume",
    "mastery of": "O domínio",
    "duration.": "da duração.",
    "examine portals": "Ver os projetos",
    "structure / light / materiality / void": "ESTRUTURA / LUZ / MATÉRIA / VAZIO",
    "riba awards": "Prémios RIBA",
    "established 1924 // geneva, ch": "Fundada em 1924 // Genebra, Suíça",
    "swiss alps, ch": "Alpes suíços, Suíça",
    "dubai, uae": "Dubai, Emirados Árabes Unidos",
    "tokyo, jp": "Tóquio, Japão",
    "oslo, no": "Oslo, Noruega",
    "seoul, kr": "Seul, Coreia do Sul",
    "berlin, de": "Berlim, Alemanha",
    "kyoto, jp": "Quioto, Japão",
    "malibu, ca": "Malibu, Califórnia",
    "projects.": "Trabalhos.",
    "art direction": "Direção de arte",
    "retail": "Ponto de venda",
    "sourdough": "Pão de massa-mãe",
    "48-hour fermentation. charcoal-infused crust. ancient grain blend.": "Fermentação de 48 horas. Côdea com carvão vegetal. Mistura de cereais antigos.",
    "aop butter. 256 layers. golden honeycomb structure.": "Manteiga DOP. 256 camadas. Alveolado dourado.",
    "high hydration. stone-baked. intense caramelization.": "Alta hidratação. Cozedura em pedra. Caramelização intensa.",
    "add_to_bag": "Juntar_ao_cesto",
    "baking": "Protocolo",
    "protocol.": "de cozedura.",
    "hydration ratio": "Taxa de hidratação",
    "maximizing crumb elasticity through high-hydration dough processing.": "Um miolo mais elástico, obtido por amassadura de alta hidratação.",
    "cold fermentation": "Fermentação a frio",
    "the": "A",
    "daily batch.": "fornada do dia.",
    "add to bag": "Adicionar ao Carrinho",
    "add to batch order": "ADICIONAR À ENCOMENDA EM LOTE",
    "all flours are stone-milled in-house from organic regenerative farms.": "Todas as nossas farinhas são moídas em mó de pedra, em casa, a partir de quintas biológicas de agricultura regenerativa.",
    "all our sourdough loaves are 100% plant-based (flour, water, salt). our viennoiseries utilize high-grade aop butter and local organic eggs.": "Todos os nossos pães de massa madre são 100% de origem vegetal (Farinha, Água, Sal). As nossas viennoiseries utilizam manteiga AOP de alta qualidade e ovos biológicos locais.",
    "are your products vegan?": "Os vossos produtos são veganos?",
    "do you offer wholesale partnerships?": "Oferecem parcerias por grosso?",
    "explore the batch": "Descobrir a fornada",
    "high-hydration molecular baking. stone hearth methodology. precision-engineered for the modern palate.": "Panificação molecular de alta hidratação. Metodologia de forno de pedra. Projetado com precisão para o paladar moderno.",
    "how should i store my sourdough?": "Como devo armazenar o meu pão de massa madre?",
    "in grain we trust": "No grão confiamos",
    "intense heat burst for maximum oven spring and thin, glass-like crust.": "Explosão de calor intensa para um máximo crescimento no forno e uma crosta fina e semelhante ao vidro.",
    "never refrigerate. store at room temperature in a paper bag for the first 48 hours, then transition to a cloth bag. sourdough of this quality matures over time.": "Nunca refrigere. Armazene à temperatura ambiente num saco de papel durante as primeiras 48 horas, depois passe para um saco de pano. O pão de massa madre desta qualidade amadurece com o tempo.",
    "order bread": "PEDIR PÃO",
    "our weekly 'manifesto' box includes 2 seasonal loaves, 4 viennoiseries, and a jar of our cultured butter. limited to 100 subscribers per city.": "A nossa caixa semanal 'Manifesto' inclui 2 pães sazonais, 4 viennoiseries e um frasco da nossa manteiga cultivada. Limitado a 100 assinantes por cidade.",
    "precise water-to-flour ratio adjusted daily for humidity.": "Relação precisa de água para farinha ajustada diariamente para a humidade.",
    "ready now": "PRONTO AGORA",
    "slow enzymatic breakdown for optimal digestibility and complex flavor profile.": "Decomposição enzimática lenta para uma digestibilidade ideal e um perfil de sabor complexo.",
    "the structural infrastructure for the next generation of artisanal baking. est. 2026. precision baked. stone milled.": "A infraestrutura estrutural para a próxima geração de panificação artesanal. Est. 2026. Cozido com precisão. Moído em pedra.",
    "the void loaf": "O PÃO DO VAZIO",
    "we treat bread as structural engineering. from grain analysis to steam-injection cycles, precision is our only ingredient.": "Tratamos o pão como engenharia estrutural. Desde a análise de grãos até os ciclos de injeção de vapor, a precisão é o nosso único ingrediente.",
    "what is the 'subscription box'?": "O que é a caixa por subscrição?",
    "yes. we supply a limited number of michelin-starred restaurants and specialty coffee shops. contact our 'network control' for institutional inquiries.": "Sim. Fornecemos um número limitado de restaurantes com estrelas Michelin e cafés especializados. Contacte o nosso 'Controle de Rede' para consultas institucionais.",
  },
};
