/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.
  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "manifesto": "Manifeste",
    "commission": "Nous confier un projet",
    "markets": "Marchés",
    "strategies": "Stratégies",
    "traders": "Opérateurs",
    "archive": "Archives",
    "e-commerce": "Commerce en ligne",
    "origins": "Origines",
    "source": "Origine",
    "roast": "Torréfaction",
    "cup": "Tasse",
    "programs": "Programmes",
    "members": "Membres",
    "destinations": "Destinations",
    "years experience": "Ans d'expérience",
    "releases": "Sorties",
    "tour": "Tournée",
    "store": "Boutique",
    "waste diverted": "Déchets détournés",
    "residential": "Résidentiel",
    "penthouse": "Attique",
    "concierge": "Conciergerie",
    "locations": "Nos adresses",
    "seller portal": "Espace vendeurs",
    "legacy": "Héritage",
    "select seat": "Choisir sa place",
    "offense": "Attaque",
    "intelligence": "Renseignement",
    "global nodes": "Nœuds mondiaux",
    "enlist": "Nous rejoindre",
    "market": "Marché",
    "curators": "Curateurs",
    "stats": "Chiffres",
    "connect wallet": "Connecter le portefeuille",
    "sanctuary": "Le sanctuaire",
    "retreats": "Retraites",
    "essence": "Essence",
    "landmark cases": "Affaires marquantes",
    "authority": "Autorité",
    "vegan & cruelty-free": "Végane et sans cruauté",
    "design": "DESIGN",
    "content": "CONTENU",
    "we design digital experiences that": "Nous concevons des expériences numériques qui",
  },
  es: {
    "manifesto": "Manifiesto",
    "commission": "Encargar un proyecto",
    "markets": "Mercados",
    "strategies": "Estrategias",
    "traders": "Operadores",
    "archive": "Archivo",
    "e-commerce": "Comercio electrónico",
    "origins": "Orígenes",
    "source": "Origen",
    "roast": "Tueste",
    "cup": "Taza",
    "programs": "Programas",
    "members": "Miembros",
    "destinations": "Destinos",
    "years experience": "Años de experiencia",
    "releases": "Lanzamientos",
    "tour": "Gira",
    "store": "Tienda",
    "waste diverted": "Residuos desviados",
    "residential": "Residencial",
    "penthouse": "Ático",
    "concierge": "Conserjería",
    "locations": "Nuestras direcciones",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Elegir asiento",
    "offense": "Ataque",
    "intelligence": "Inteligencia",
    "global nodes": "Nodos mundiales",
    "enlist": "Únase a nosotros",
    "market": "Mercado",
    "curators": "Comisarios",
    "stats": "Cifras",
    "connect wallet": "Conectar la cartera",
    "sanctuary": "El santuario",
    "retreats": "Retiros",
    "essence": "Esencia",
    "landmark cases": "Casos emblemáticos",
    "authority": "Autoridad",
    "vegan & cruelty-free": "Vegano y sin crueldad",
    "design": "DISEÑO",
    "content": "CONTENIDO",
    "we design digital experiences that": "Diseñamos experiencias digitales que",
  },
  de: {
    "manifesto": "Manifest",
    "commission": "Projekt anfragen",
    "markets": "Märkte",
    "strategies": "Strategien",
    "traders": "Händler",
    "archive": "Archiv",
    "e-commerce": "E-Commerce",
    "origins": "Herkünfte",
    "source": "Ursprung",
    "roast": "Röstung",
    "cup": "Tasse",
    "programs": "Programme",
    "members": "Mitglieder",
    "destinations": "Reiseziele",
    "years experience": "Jahre Erfahrung",
    "releases": "Veröffentlichungen",
    "tour": "Tour",
    "store": "Shop",
    "waste diverted": "Umgeleitete Abfälle",
    "residential": "Wohnbau",
    "penthouse": "Penthouse",
    "concierge": "Concierge-Service",
    "locations": "Unsere Standorte",
    "seller portal": "Verkäuferbereich",
    "legacy": "Erbe",
    "select seat": "Platz wählen",
    "offense": "Angriff",
    "intelligence": "Aufklärung",
    "global nodes": "Weltweite Knoten",
    "enlist": "Mitmachen",
    "market": "Markt",
    "curators": "Kuratoren",
    "stats": "Zahlen",
    "connect wallet": "Wallet verbinden",
    "sanctuary": "Das Refugium",
    "retreats": "Retreats",
    "essence": "Essenz",
    "landmark cases": "Wegweisende Fälle",
    "authority": "Autorität",
    "vegan & cruelty-free": "Vegan und tierversuchsfrei",
    "design": "DESIGN",
    "content": "INHALT",
    "we design digital experiences that": "Wir gestalten digitale Erlebnisse, die",
  },
  pt: {
    "manifesto": "Manifesto",
    "commission": "Confiar-nos um projeto",
    "markets": "Mercados",
    "strategies": "Estratégias",
    "traders": "Operadores",
    "archive": "Arquivo",
    "e-commerce": "Comércio eletrónico",
    "origins": "Origens",
    "source": "Origem",
    "roast": "Torra",
    "cup": "Chávena",
    "programs": "Programas",
    "members": "Membros",
    "destinations": "Destinos",
    "years experience": "Anos de experiência",
    "releases": "Lançamentos",
    "tour": "Digressão",
    "store": "Loja",
    "waste diverted": "Resíduos desviados",
    "residential": "Residencial",
    "penthouse": "Cobertura",
    "concierge": "Concierge",
    "locations": "As nossas moradas",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Escolher lugar",
    "offense": "Ataque",
    "intelligence": "Informações",
    "global nodes": "Nós mundiais",
    "enlist": "Junte-se a nós",
    "market": "Mercado",
    "curators": "Curadores",
    "stats": "Números",
    "connect wallet": "Ligar a carteira",
    "sanctuary": "O santuário",
    "retreats": "Retiros",
    "essence": "Essência",
    "landmark cases": "Casos marcantes",
    "authority": "Autoridade",
    "vegan & cruelty-free": "Vegano e sem crueldade",
    "design": "DESIGN",
    "content": "CONTEÚDO",
    "we design digital experiences that": "Concebemos experiências digitais que",
  },
};
