/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"buildings are not objects. they are the infrastructure of human life.\"": "« UN BÂTIMENT N'EST PAS UN OBJET. C'EST L'INFRASTRUCTURE D'UNE VIE. »",
    "architectural competition strategy. we win because we think differently.": "Stratégie de compétition architecturale. Nous gagnons parce que nous pensons différemment.",
    "as seen in": "Vu dans",
    "built with us.": "BÂTI AVEC NOUS.",
    "client accounts": "Comptes clients",
    "concrete is honest.": "LE BÉTON NE MENT PAS.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "Le béton n'est pas une marchandise. Nous testons les granulats locaux, les nappes phréatiques, les cycles climatiques et les formulations régionales avant qu'un seul croquis ne soit dessiné.",
    "get in touch →": "Nous écrire →",
    "have a structure": "UN PROJET DE STRUCTURE",
    "master plans for districts, campuses, and large-scale developments.": "Plans directeurs pour des quartiers, des campus et des développements à grande échelle.",
    "new construction from concept to delivery. we design buildings that endure.": "Nouvelle construction de la conception à la livraison. Nous concevons des bâtiments qui durent.",
    "our methodology": "Notre méthode",
    "projects built": "Projets réalisés",
    "see all work": "Voir toutes les réalisations",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "Le design émerge du matériau, pas du logiciel. Les maquettes à la main, les prototypes en plâtre coulé et les études de masse sur site déterminent la forme.",
    "we are brutal.": "NOUS SOMMES BRUTS.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Nous sommes présents sur le site. Nous travaillons avec des entrepreneurs spécialisés formés au coffrage en béton brut, aux impressions en planches et à la finition au marteau-brousse.",
    "we build": "NOUS BÂTISSONS",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Nous collaborons avec des ingénieurs structurels dès le premier jour. Les murs de cisaillement, les dalles précontraintes et les géométries de noyau sont résolus lors de la phase de conception.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Nous déconstruisons votre cahier des charges pour trouver l'idée structurelle qui le sous-tend. La plupart des clients pensent qu'ils veulent un bâtiment. Ils veulent en réalité une institution.",
    "years active": "Années d'activité",
  },
  es: {
    "\"buildings are not objects. they are the infrastructure of human life.\"": "«UN EDIFICIO NO ES UN OBJETO. ES LA INFRAESTRUCTURA DE UNA VIDA.»",
    "architectural competition strategy. we win because we think differently.": "Estrategia de competencia arquitectónica. Ganamos porque pensamos de manera diferente.",
    "as seen in": "Visto en",
    "built with us.": "CONSTRUIDO CON NOSOTROS.",
    "client accounts": "Cuentas de clientes",
    "concrete is honest.": "EL HORMIGÓN NO MIENTE.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "El concreto no es una mercancía. Probamos agregados locales, mesas de agua, ciclos climáticos y formulaciones regionales antes de dibujar un solo boceto.",
    "get in touch →": "Escríbanos →",
    "have a structure": "UN PROYECTO DE ESTRUCTURA",
    "master plans for districts, campuses, and large-scale developments.": "Planes maestros para distritos, campus y desarrollos a gran escala.",
    "new construction from concept to delivery. we design buildings that endure.": "Nueva construcción desde el concepto hasta la entrega. Diseñamos edificios que perduran.",
    "our methodology": "Nuestro método",
    "projects built": "Proyectos construidos",
    "see all work": "Ver todos los trabajos",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "El diseño surge del material, no del software. Los modelos a mano, los prototipos de yeso fundido y los estudios de masa en el sitio impulsan la forma.",
    "we are brutal.": "SOMOS BRUTOS.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Estamos presentes en el sitio. Trabajamos con contratistas especializados capacitados en encofrado de hormigón en bruto, impresiones de tablones y acabado con martillo de arbusto.",
    "we build": "CONSTRUIMOS",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Colaboramos con ingenieros estructurales desde el primer día. Los muros de corte, las losas postensadas y las geometrías centrales se resuelven en la fase de concepto.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Desmontamos su encargo para encontrar la idea estructural detrás de él. La mayoría de los clientes piensan que quieren un edificio. En realidad, quieren una institución.",
    "years active": "Años activos",
  },
  de: {
    "\"buildings are not objects. they are the infrastructure of human life.\"": "„EIN GEBÄUDE IST KEIN OBJEKT. ES IST DIE INFRASTRUKTUR EINES LEBENS.“",
    "architectural competition strategy. we win because we think differently.": "Architekturwettbewerbsstrategie. Wir gewinnen, weil wir anders denken.",
    "as seen in": "Gesehen in",
    "built with us.": "MIT UNS GEBAUT.",
    "client accounts": "Kundenkonten",
    "concrete is honest.": "BETON LÜGT NICHT.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "Beton ist kein Rohstoff. Wir testen lokale Zuschläge, Grundwasserstände, Klimazyklen und regionale Formulierungen, bevor ein einziger Entwurf gezeichnet wird.",
    "get in touch →": "Kontakt aufnehmen →",
    "have a structure": "EIN BAUVORHABEN",
    "master plans for districts, campuses, and large-scale developments.": "Masterpläne für Stadtteile, Campus und großflächige Entwicklungen.",
    "new construction from concept to delivery. we design buildings that endure.": "Neubau von der Idee bis zur Lieferung. Wir entwerfen Gebäude, die Bestand haben.",
    "our methodology": "Unsere Methode",
    "projects built": "Bauten realisiert",
    "see all work": "Alle Arbeiten ansehen",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "Das Design entsteht aus dem Material, nicht aus der Software. Handmodelle, gegossene Gipsprototypen und Standortmassenstudien bestimmen die Form.",
    "we are brutal.": "WIR SIND BRUTAL.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Wir sind vor Ort präsent. Wir arbeiten mit spezialisierten Auftragnehmern, die im Rohbeton-Schalungsbau, Brettformabdrücken und Bushammer-Finishing ausgebildet sind.",
    "we build": "WIR BAUEN",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Wir arbeiten von Tag eins mit Tragwerksplanern zusammen. Scherwände, vorgespannten Platten und Kerngeometrien werden in der Konzeptphase gelöst.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Wir zerlegen Ihr Briefing, um die strukturelle Idee dahinter zu finden. Die meisten Kunden denken, sie wollen ein Gebäude. Tatsächlich wollen sie eine Institution.",
    "years active": "Aktive Jahre",
  },
  pt: {
    "\"buildings are not objects. they are the infrastructure of human life.\"": "«UM EDIFÍCIO NÃO É UM OBJETO. É A INFRAESTRUTURA DE UMA VIDA.»",
    "architectural competition strategy. we win because we think differently.": "Estratégia de competição arquitetónica. Vencemos porque pensamos de forma diferente.",
    "as seen in": "Visto em",
    "built with us.": "CONSTRUÍDO CONNOSCO.",
    "client accounts": "Contas de clientes",
    "concrete is honest.": "O BETÃO NÃO MENTE.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "O betão não é uma mercadoria. Testamos agregados locais, lençóis freáticos, ciclos climáticos e formulações regionais antes de desenhar um único esboço.",
    "get in touch →": "Fale connosco →",
    "have a structure": "UM PROJETO DE ESTRUTURA",
    "master plans for districts, campuses, and large-scale developments.": "Planos mestres para distritos, campi e desenvolvimentos em grande escala.",
    "new construction from concept to delivery. we design buildings that endure.": "Nova construção do conceito à entrega. Projetamos edifícios que perduram.",
    "our methodology": "O nosso método",
    "projects built": "Projetos construídos",
    "see all work": "Ver todos os trabalhos",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "O design emerge do material, não do software. Modelos manuais, protótipos de gesso fundido e estudos de massa no local definem a forma.",
    "we are brutal.": "SOMOS BRUTOS.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Estamos presentes no local. Trabalhamos com empreiteiros especializados treinados em cofragem de betão bruto, impressões de tábuas e acabamentos com martelo de arbusto.",
    "we build": "CONSTRUÍMOS",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Colaboramos com engenheiros estruturais desde o primeiro dia. Paredes de cisalhamento, lajes pós-tensionadas e geometrias centrais são resolvidas na fase de conceito.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Desmontamos o seu briefing para encontrar a ideia estrutural por trás dele. A maioria dos clientes pensa que quer um edifício. Na verdade, querem uma instituição.",
    "years active": "Anos ativos",
  },
};
