/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Un document sur ma façon de travailler — les outils, la philosophie, l'installation. Parce que l'environnement façonne le résultat.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Une astuce brillante que trois ingénieurs ne sauront plus lire au trimestre suivant est un passif, pas un actif. J'optimise pour le prochain ingénieur sur le code.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "L'intuition sur la performance se trompe presque toujours. Profileurs, traces distribuées et télémétrie de production doivent guider les décisions d'optimisation.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Une PR de 50 lignes livrée aujourd'hui vaut mieux qu'une PR de 500 lignes qui traîne deux semaines en relecture. Je garde des diffs lisibles et des contrôles automatisés pour que ça avance.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit est volontairement petit. Quatre projets par trimestre — jamais plus. Chaque client a tous les seniors autour de la table. C'est le modèle.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Stratège de marque, venue de la sémiotique et de l'économie comportementale. Passée par Wolff Olins à Londres. Convaincue que toute grande identité part d'un point de vue tranché.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obsédée de typographie, esprit systémique, ancienne de Pentagram. Sana transforme la clarté stratégique en précision visuelle — rien d'arbitraire, tout se déploie.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Fait passer la marque du statique au vivant — identité en mouvement, web interactif, points de contact numériques. A travaillé avec Nike Digital et Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Des composants 3D haute performance conçus pour le web moderne. Nous marions le geste créatif à une optimisation rigoureuse au niveau du GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Un rendu 3D temps réel haute fidélité, directement dans le navigateur : maillages légers, textures PBR optimisées, éclairage physiquement exact.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Des campagnes de réalité augmentée sans application : d'un simple lien, le client pose le produit chez lui, avec un réalisme photographique.",
    "camera filters and custom overlays": "Filtres caméra et surimpressions sur mesure",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism se branche nativement à votre entrepôt de données, votre CRM, votre prestataire de paiement et vos canaux publicitaires. Aucune intégration sur mesure requise.",
    "sync raw events natively from databases and query engines.": "Synchronisez les événements bruts depuis vos bases et moteurs de requête.",
    "align transaction records with user behavior metrics.": "Rapprochez les transactions des mesures de comportement.",
    "enrich user profiles and trigger messaging based on user actions.": "Enrichissez les profils et déclenchez des messages selon les actions.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Une conception de bout en bout, de l'esquisse au coulage du béton. L'honnêteté structurelle est notre directive première, sans compromis visuel.",
    "scope of work:": "Périmètre :",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Des stratégies d'aménagement à grande échelle pour institutions publiques et campus. Nos plans directeurs ancrent les ensembles bâtis dans une densité logique.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Nous laissons l'acier, le béton et les gaines apparents : les systèmes intérieurs font partie de l'esthétique au lieu d'être cachés derrière des finitions.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sept jours dans un désert ancien. Pratique somatique à l'aube, marches silencieuses à midi, cérémonies du feu le soir. Sans agenda. Sans performance.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Des retraites immersives dans les paysages les plus transformateurs du monde. Neuf participants au plus. Le calme comme pratique.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Je passe des semaines sur chaque lieu avant de faire une image. Les montagnes se moquent de mon calendrier. La brume vient quand elle veut. Cette patience est toute la méthode.",
    "each print is made in partnership with atelier gaspard in": "Chaque tirage est réalisé avec l'Atelier Gaspard à",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Pour les licences éditoriales, les usages commerciaux ou les commandes privées, écrivez-moi directement. Pour les tirages, passez par la boutique.",
    "bring the wild": "Ramenez le sauvage",
    "that's the point.": "C'est justement le but.",
    "we work with raw concrete, steel, and industrial glass. we refuse to hide the integrity of materials behind plasterboard or paint.": "Nous travaillons le béton brut, l'acier et le verre industriel. Nous refusons de cacher l'intégrité des matériaux derrière le placo ou la peinture.",
    "the columns, slabs, and shear walls that hold the building up are the architecture itself. form follows structure.": "Les poteaux, les dalles et les voiles qui portent le bâtiment sont l'architecture elle-même. La forme suit la structure.",
    "mass, weight, and light create spatial meaning. we build block-like forms that capture the shifting paths of natural light.": "La masse, le poids et la lumière donnent son sens à l'espace. Nous bâtissons des volumes francs qui captent les trajets changeants de la lumière naturelle.",
    "a structure should survive generations. we build with permanent textures that require zero maintenance and age gracefully.": "Une structure doit traverser les générations. Nous construisons avec des textures pérennes, sans entretien, qui vieillissent bien.",
    "with a simple commitment: to return architecture to its raw, structural roots. rejecting the glass-and-plasterboard standards of commercial offices, the founders built a practice devoted to raw material truth.": "avec un engagement simple : rendre l'architecture à ses racines brutes et structurelles. Refusant le tout-verre et le placo des immeubles de bureaux, les fondateurs ont bâti une agence vouée à la vérité du matériau.",
    "today, the office comprises 24 architects, engineers, and material scientists, working from three ateliers in": "Aujourd'hui, l'agence réunit 24 architectes, ingénieurs et spécialistes des matériaux, répartis entre trois ateliers à",
    "founded 2008": "Fondée en 2008",
    "what": "CE QUI",
    "matters.": "COMPTE.",
    "national awards": "Prix nationaux",
    "construction value": "Valeur construite",
    "bloc k — social housing complex": "BLOC K — ensemble de logements sociaux",
    "residential": "Résidentiel",
    "bunker office — hq renovation": "BUNKER OFFICE — réhabilitation d'un siège social",
    "concrete chapel": "CHAPELLE DE BÉTON",
    "urban planning": "Urbanisme",
    "interior architecture": "Architecture intérieure",
    "heritage renovation": "Réhabilitation du patrimoine",
    "competition": "Concours",
    "material": "LA VÉRITÉ",
    "truth": "DU MATÉRIAU",
    "founding partner": "Associé fondateur",
    "brief deconstruction": "Déconstruction du programme",
    "2 — 4 weeks": "2 à 4 semaines",
    "material research": "Recherche sur les matériaux",
    "3 — 6 weeks": "3 à 6 semaines",
    "monolithic concept": "Concept monolithique",
    "4 — 8 weeks": "4 à 8 semaines",
    "engineering integration": "Intégration de l'ingénierie",
    "6 — 12 weeks": "6 à 12 semaines",
    "construction & delivery": "Chantier et livraison",
    "12 — 36 months": "12 à 36 mois",
    "full methodology": "Toute la méthode",
    "referenced project": "Projet cité",
    "european concrete award 2023": "PRIX EUROPÉEN DU BÉTON 2023",
    "riba international prize — shortlist": "PRIX INTERNATIONAL RIBA — SÉLECTION FINALE",
    "mies van der rohe award — nomination": "PRIX MIES VAN DER ROHE — NOMINATION",
    "equerre d'argent 2015": "ÉQUERRE D'ARGENT 2015",
    "associate architect": "Architecte associée",
    "project director": "Directrice de projet",
    "next commission": "Prochaine commande",
    "main atelier:": "Atelier principal :",
    "ils": "ILS ONT",
    "we don't design for awards. we design for people and cities. brutalism is not a style — it's a conviction that architecture should be truthful about its materials and its purpose.": "Nous ne dessinons pas pour les prix. Nous dessinons pour des gens et pour des villes. Le brutalisme n'est pas un style : c'est la conviction qu'une architecture doit dire la vérité sur ses matériaux et sur son usage.",
    "our": "NOTRE",
    "brutco doesn't deliver a building. they deliver a manifesto in concrete. we had no brief — only the ambition to create something that would outlast us. they made that real.": "Ils ne livrent pas un bâtiment : ils livrent un manifeste en béton. Nous n'avions pas de cahier des charges — seulement l'ambition de faire quelque chose qui nous survive. Ils l'ont rendu réel.",
    "\"buildings are not objects. they are the infrastructure of human life.\"": "« UN BÂTIMENT N'EST PAS UN OBJET. C'EST L'INFRASTRUCTURE D'UNE VIE. »",
    "architectural competition strategy. we win because we think differently.": "Stratégie de compétition architecturale. Nous gagnons parce que nous pensons différemment.",
    "as seen in": "Vu dans",
    "built with us.": "BÂTI AVEC NOUS.",
    "client accounts": "Comptes clients",
    "concrete is honest.": "LE BÉTON NE MENT PAS.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "Le béton n'est pas une marchandise. Nous testons les granulats locaux, les nappes phréatiques, les cycles climatiques et les formulations régionales avant qu'un seul croquis ne soit dessiné.",
    "every project starts with a conversation. tell us what you want to build and we'll tell you if we're the right firm.": "Chaque projet commence par une conversation. Dites-nous ce que vous voulez construire et nous vous dirons si nous sommes le bon cabinet.",
    "get in touch →": "Nous écrire →",
    "have a structure": "UN PROJET DE STRUCTURE",
    "in mind?": "EN TÊTE ?",
    "master plans for districts, campuses, and large-scale developments.": "Plans directeurs pour des quartiers, des campus et des développements à grande échelle.",
    "new construction from concept to delivery. we design buildings that endure.": "Nouvelle construction de la conception à la livraison. Nous concevons des bâtiments qui durent.",
    "our methodology": "Notre méthode",
    "projects built": "Projets réalisés",
    "see all work": "Voir toutes les réalisations",
    "start a": "DÉMARRER UN",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "Le design émerge du matériau, pas du logiciel. Les maquettes à la main, les prototypes en plâtre coulé et les études de masse sur site déterminent la forme.",
    "they": "ILS",
    "view full catalogue": "Voir le catalogue complet",
    "we are brutal.": "NOUS SOMMES BRUTS.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Nous sommes présents sur le site. Nous travaillons avec des entrepreneurs spécialisés formés au coffrage en béton brut, aux impressions en planches et à la finition au marteau-brousse.",
    "we build": "NOUS BÂTISSONS",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Nous collaborons avec des ingénieurs structurels dès le premier jour. Les murs de cisaillement, les dalles précontraintes et les géométries de noyau sont résolus lors de la phase de conception.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Nous déconstruisons votre cahier des charges pour trouver l'idée structurelle qui le sous-tend. La plupart des clients pensent qu'ils veulent un bâtiment. Ils veulent en réalité une institution.",
    "years active": "Années d'activité",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Un documento sobre mi forma de trabajar: las herramientas, la filosofía, la instalación. Porque el entorno moldea el resultado.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Un truco brillante que tres ingenieros no sabrán leer el próximo trimestre es un pasivo, no un activo. Optimizo para el siguiente ingeniero en el código.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "La intuición sobre el rendimiento casi siempre se equivoca. Perfiles, trazas distribuidas y telemetría de producción deben guiar las decisiones de optimización.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Una PR de 50 líneas entregada hoy vale más que una de 500 que pasa dos semanas en revisión. Mantengo diffs legibles y controles automatizados para que todo avance.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit es deliberadamente pequeño. Cuatro proyectos por trimestre, nunca más. Cada cliente tiene a todos los seniors en la sala. Ese es el modelo.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Estratega de marca, con formación en semiótica y economía conductual. Antes en Wolff Olins Londres. Convencida de que toda gran identidad parte de un punto de vista afilado.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obsesa de la tipografía, mente sistémica, ex-Pentagram. Sana convierte la claridad estratégica en precisión visual: nada es arbitrario, todo escala.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Lleva la marca de lo estático a lo vivo: identidad en movimiento, web interactiva, puntos de contacto digitales. Trabajó con Nike Digital y Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Componentes 3D de alto rendimiento para la web moderna. Unimos el gesto creativo a una optimización rigurosa a nivel de GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Renderizado 3D en tiempo real de alta fidelidad, directamente en el navegador: mallas ligeras, texturas PBR optimizadas, iluminación físicamente exacta.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Campañas de realidad aumentada sin aplicación: con un simple enlace, el cliente coloca el producto en su espacio con realismo fotográfico.",
    "camera filters and custom overlays": "Filtros de cámara y superposiciones a medida",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism se conecta de forma nativa a su almacén de datos, su CRM, su procesador de pagos y sus canales publicitarios. Sin integraciones a medida.",
    "sync raw events natively from databases and query engines.": "Sincronice eventos en bruto desde sus bases y motores de consulta.",
    "align transaction records with user behavior metrics.": "Alinee las transacciones con las métricas de comportamiento.",
    "enrich user profiles and trigger messaging based on user actions.": "Enriquezca los perfiles y active mensajes según las acciones.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Diseño de principio a fin, del boceto al vertido del hormigón. La honestidad estructural es nuestra directiva primera, sin compromiso visual.",
    "scope of work:": "Alcance:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Estrategias de ordenación a gran escala para instituciones públicas y campus. Nuestros planes maestros anclan los conjuntos con una densidad lógica.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Dejamos el acero, el hormigón y los conductos a la vista: los sistemas interiores forman parte de la estética en lugar de esconderse tras acabados.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Siete días en un desierto antiguo. Práctica somática al alba, caminatas silenciosas al mediodía, ceremonias de fuego al anochecer. Sin agenda. Sin rendimiento.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Retiros inmersivos en los paisajes más transformadores del mundo. Nueve participantes como máximo. La calma como práctica.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Paso semanas en cada lugar antes de hacer una imagen. A las montañas no les importa mi calendario. La niebla llega cuando quiere. Esa paciencia es todo el método.",
    "each print is made in partnership with atelier gaspard in": "Cada copia se realiza con el Atelier Gaspard en",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Para licencias editoriales, usos comerciales o encargos privados, escríbame directamente. Para las copias, pase por la tienda.",
    "bring the wild": "Traiga lo salvaje",
    "that's the point.": "Ese es justamente el punto.",
    "we work with raw concrete, steel, and industrial glass. we refuse to hide the integrity of materials behind plasterboard or paint.": "Trabajamos el hormigón visto, el acero y el vidrio industrial. Nos negamos a esconder la integridad de los materiales tras el pladur o la pintura.",
    "the columns, slabs, and shear walls that hold the building up are the architecture itself. form follows structure.": "Los pilares, las losas y los muros que sostienen el edificio son la arquitectura misma. La forma sigue a la estructura.",
    "mass, weight, and light create spatial meaning. we build block-like forms that capture the shifting paths of natural light.": "La masa, el peso y la luz dan sentido al espacio. Construimos volúmenes francos que captan los recorridos cambiantes de la luz natural.",
    "a structure should survive generations. we build with permanent textures that require zero maintenance and age gracefully.": "Una estructura debe atravesar generaciones. Construimos con texturas perennes, sin mantenimiento, que envejecen bien.",
    "with a simple commitment: to return architecture to its raw, structural roots. rejecting the glass-and-plasterboard standards of commercial offices, the founders built a practice devoted to raw material truth.": "con un compromiso simple: devolver la arquitectura a sus raíces brutas y estructurales. Rechazando el vidrio y el pladur de las oficinas comerciales, los fundadores construyeron un estudio dedicado a la verdad del material.",
    "today, the office comprises 24 architects, engineers, and material scientists, working from three ateliers in": "Hoy, el estudio reúne a 24 arquitectos, ingenieros y especialistas en materiales, repartidos en tres talleres en",
    "founded 2008": "Fundada en 2008",
    "what": "LO QUE",
    "matters.": "IMPORTA.",
    "national awards": "Premios nacionales",
    "construction value": "Valor construido",
    "bloc k — social housing complex": "BLOC K — conjunto de viviendas sociales",
    "residential": "Residencial",
    "bunker office — hq renovation": "BUNKER OFFICE — rehabilitación de una sede",
    "concrete chapel": "CAPILLA DE HORMIGÓN",
    "urban planning": "Urbanismo",
    "interior architecture": "Arquitectura interior",
    "heritage renovation": "Rehabilitación del patrimonio",
    "competition": "Concursos",
    "material": "LA VERDAD",
    "truth": "DEL MATERIAL",
    "founding partner": "Socio fundador",
    "brief deconstruction": "Deconstrucción del encargo",
    "2 — 4 weeks": "2 a 4 semanas",
    "material research": "Investigación de materiales",
    "3 — 6 weeks": "3 a 6 semanas",
    "monolithic concept": "Concepto monolítico",
    "4 — 8 weeks": "4 a 8 semanas",
    "engineering integration": "Integración de la ingeniería",
    "6 — 12 weeks": "6 a 12 semanas",
    "construction & delivery": "Obra y entrega",
    "12 — 36 months": "12 a 36 meses",
    "full methodology": "Toda la metodología",
    "referenced project": "Proyecto citado",
    "european concrete award 2023": "PREMIO EUROPEO DEL HORMIGÓN 2023",
    "riba international prize — shortlist": "PREMIO INTERNACIONAL RIBA — FINALISTA",
    "mies van der rohe award — nomination": "PREMIO MIES VAN DER ROHE — NOMINACIÓN",
    "equerre d'argent 2015": "ÉQUERRE D'ARGENT 2015",
    "associate architect": "Arquitecta asociada",
    "project director": "Directora de proyecto",
    "next commission": "Próximo encargo",
    "main atelier:": "Taller principal:",
    "ils": "HAN",
    "we don't design for awards. we design for people and cities. brutalism is not a style — it's a conviction that architecture should be truthful about its materials and its purpose.": "No diseñamos para los premios. Diseñamos para personas y para ciudades. El brutalismo no es un estilo: es la convicción de que la arquitectura debe decir la verdad sobre sus materiales y su uso.",
    "our": "NUESTRA",
    "brutco doesn't deliver a building. they deliver a manifesto in concrete. we had no brief — only the ambition to create something that would outlast us. they made that real.": "No entregan un edificio: entregan un manifiesto en hormigón. No teníamos pliego — solo la ambición de hacer algo que nos sobreviviera. Lo hicieron real.",
    "\"buildings are not objects. they are the infrastructure of human life.\"": "«UN EDIFICIO NO ES UN OBJETO. ES LA INFRAESTRUCTURA DE UNA VIDA.»",
    "architectural competition strategy. we win because we think differently.": "Estrategia de competencia arquitectónica. Ganamos porque pensamos de manera diferente.",
    "as seen in": "Visto en",
    "built with us.": "CONSTRUIDO CON NOSOTROS.",
    "client accounts": "Cuentas de clientes",
    "concrete is honest.": "EL HORMIGÓN NO MIENTE.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "El concreto no es una mercancía. Probamos agregados locales, mesas de agua, ciclos climáticos y formulaciones regionales antes de dibujar un solo boceto.",
    "every project starts with a conversation. tell us what you want to build and we'll tell you if we're the right firm.": "Cada proyecto comienza con una conversación. Dinos qué quieres construir y te diremos si somos la empresa adecuada.",
    "get in touch →": "Escríbanos →",
    "have a structure": "UN PROYECTO DE ESTRUCTURA",
    "in mind?": "EN MENTE?",
    "master plans for districts, campuses, and large-scale developments.": "Planes maestros para distritos, campus y desarrollos a gran escala.",
    "new construction from concept to delivery. we design buildings that endure.": "Nueva construcción desde el concepto hasta la entrega. Diseñamos edificios que perduran.",
    "our methodology": "Nuestro método",
    "projects built": "Proyectos construidos",
    "see all work": "Ver todos los trabajos",
    "start a": "INICIAR UN",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "El diseño surge del material, no del software. Los modelos a mano, los prototipos de yeso fundido y los estudios de masa en el sitio impulsan la forma.",
    "they": "ELLOS",
    "view full catalogue": "Ver catálogo completo",
    "we are brutal.": "SOMOS BRUTOS.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Estamos presentes en el sitio. Trabajamos con contratistas especializados capacitados en encofrado de hormigón en bruto, impresiones de tablones y acabado con martillo de arbusto.",
    "we build": "CONSTRUIMOS",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Colaboramos con ingenieros estructurales desde el primer día. Los muros de corte, las losas postensadas y las geometrías centrales se resuelven en la fase de concepto.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Desmontamos su encargo para encontrar la idea estructural detrás de él. La mayoría de los clientes piensan que quieren un edificio. En realidad, quieren una institución.",
    "years active": "Años activos",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Ein Dokument über meine Arbeitsweise — Werkzeuge, Philosophie, Arbeitsplatz. Denn die Umgebung prägt das Ergebnis.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Ein brillanter Trick, den drei Ingenieure im nächsten Quartal nicht mehr lesen können, ist eine Last, kein Gewinn. Ich optimiere für den nächsten Menschen im Code.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "Intuition über Performance liegt meist daneben. Profiler, verteilte Traces und echte Produktionstelemetrie sollten Optimierungsentscheidungen leiten.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Ein 50-Zeilen-PR, der heute live geht, schlägt einen 500-Zeilen-PR, der zwei Wochen im Review hängt. Ich halte Diffs lesbar und Gates automatisiert, damit es vorangeht.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "Orbit ist bewusst klein. Vier Projekte pro Quartal — nie mehr. Jeder Kunde bekommt alle Senioren an den Tisch. Das ist das Modell.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Markenstrategin mit Hintergrund in Semiotik und Verhaltensökonomie. Zuvor bei Wolff Olins London. Überzeugt, dass jede große Identität mit einer klaren Haltung beginnt.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Typografie-Besessene, Systemdenkerin, früher bei Pentagram. Sana übersetzt strategische Klarheit in visuelle Präzision — nichts ist beliebig, alles skaliert.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Überführt statische Marken in lebende Systeme — Motion Identity, interaktives Web, digitale Touchpoints. Arbeitete mit Nike Digital und Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Hochperformante 3D-Komponenten für das moderne Web. Wir verbinden kreatives Können mit rigoroser Optimierung auf GPU-Ebene.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Hochauflösendes Echtzeit-3D direkt im Browser: leichte Meshes, optimierte PBR-Texturen, physikalisch korrektes Licht.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "AR-Kampagnen ohne App: Über einen Link platzieren Kunden Produkte fotorealistisch im eigenen Raum.",
    "camera filters and custom overlays": "Kamerafilter und individuelle Overlays",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "Prism verbindet sich nativ mit Ihrem Data Warehouse, CRM, Zahlungsdienstleister und Ihren Werbekanälen. Keine individuellen API-Integrationen nötig.",
    "sync raw events natively from databases and query engines.": "Rohereignisse nativ aus Datenbanken und Query-Engines synchronisieren.",
    "align transaction records with user behavior metrics.": "Transaktionen mit Verhaltensmetriken abgleichen.",
    "enrich user profiles and trigger messaging based on user actions.": "Profile anreichern und Nachrichten aktionsbasiert auslösen.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Entwurf von A bis Z, von der Skizze bis zum Betonguss. Strukturelle Ehrlichkeit ist unsere oberste Direktive, ohne visuelle Kompromisse.",
    "scope of work:": "Leistungsumfang:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Großmaßstäbliche Planungsstrategien für öffentliche Einrichtungen und Campusse. Unsere Masterpläne verankern Baugruppen in logischer Dichte.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Wir lassen Stahl, Beton und Leitungen sichtbar: Die Haustechnik ist Teil der Ästhetik, statt hinter Verkleidungen zu verschwinden.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sieben Tage in einer uralten Wüstenlandschaft. Somatische Praxis im Morgengrauen, stille Mittagswanderungen, Feuerzeremonien am Abend. Ohne Agenda. Ohne Leistung.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Immersive Retreats in den verwandelndsten Landschaften der Welt. Höchstens neun Teilnehmende. Stille als Praxis.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Ich verbringe Wochen an jedem Ort, bevor ein Bild entsteht. Den Bergen ist mein Zeitplan gleich. Der Nebel kommt, wann er will. Diese Geduld ist die ganze Methode.",
    "each print is made in partnership with atelier gaspard in": "Jeder Abzug entsteht mit dem Atelier Gaspard in",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Für redaktionelle Lizenzen, kommerzielle Nutzung oder private Aufträge schreiben Sie mir direkt. Für Drucke besuchen Sie den Shop.",
    "bring the wild": "Holen Sie die Wildnis",
    "that's the point.": "Genau darum geht es.",
    "we work with raw concrete, steel, and industrial glass. we refuse to hide the integrity of materials behind plasterboard or paint.": "Wir arbeiten mit Sichtbeton, Stahl und Industrieglas. Wir weigern uns, die Integrität der Materialien hinter Gipskarton oder Farbe zu verstecken.",
    "the columns, slabs, and shear walls that hold the building up are the architecture itself. form follows structure.": "Die Stützen, Decken und Wandscheiben, die das Gebäude tragen, sind die Architektur selbst. Die Form folgt der Struktur.",
    "mass, weight, and light create spatial meaning. we build block-like forms that capture the shifting paths of natural light.": "Masse, Gewicht und Licht geben dem Raum Bedeutung. Wir bauen blockhafte Formen, die die wandernden Wege des Tageslichts einfangen.",
    "a structure should survive generations. we build with permanent textures that require zero maintenance and age gracefully.": "Ein Bauwerk soll Generationen überdauern. Wir bauen mit dauerhaften Texturen, wartungsfrei, die in Würde altern.",
    "with a simple commitment: to return architecture to its raw, structural roots. rejecting the glass-and-plasterboard standards of commercial offices, the founders built a practice devoted to raw material truth.": "mit einem einfachen Versprechen: die Architektur zu ihren rohen, strukturellen Wurzeln zurückzuführen. Die Gründer lehnten Glas-und-Gipskarton-Standards ab und bauten ein Büro, das der Wahrheit des Materials verpflichtet ist.",
    "today, the office comprises 24 architects, engineers, and material scientists, working from three ateliers in": "Heute vereint das Büro 24 Architekten, Ingenieure und Materialforscher in drei Ateliers in",
    "founded 2008": "Gegründet 2008",
    "what": "WAS",
    "matters.": "ZÄHLT.",
    "national awards": "Nationale Auszeichnungen",
    "construction value": "Bauvolumen",
    "bloc k — social housing complex": "BLOC K — Sozialwohnungskomplex",
    "residential": "Wohnbau",
    "bunker office — hq renovation": "BUNKER OFFICE — Sanierung eines Hauptsitzes",
    "concrete chapel": "BETONKAPELLE",
    "urban planning": "Städtebau",
    "interior architecture": "Innenarchitektur",
    "heritage renovation": "Denkmalsanierung",
    "competition": "Wettbewerbe",
    "material": "DIE WAHRHEIT",
    "truth": "DES MATERIALS",
    "founding partner": "Gründungspartner",
    "brief deconstruction": "Dekonstruktion des Programms",
    "2 — 4 weeks": "2 bis 4 Wochen",
    "material research": "Materialforschung",
    "3 — 6 weeks": "3 bis 6 Wochen",
    "monolithic concept": "Monolithisches Konzept",
    "4 — 8 weeks": "4 bis 8 Wochen",
    "engineering integration": "Integration der Tragwerksplanung",
    "6 — 12 weeks": "6 bis 12 Wochen",
    "construction & delivery": "Bau und Übergabe",
    "12 — 36 months": "12 bis 36 Monate",
    "full methodology": "Die gesamte Methodik",
    "referenced project": "Genanntes Projekt",
    "european concrete award 2023": "EUROPÄISCHER BETONPREIS 2023",
    "riba international prize — shortlist": "RIBA INTERNATIONAL PRIZE — ENGERE WAHL",
    "mies van der rohe award — nomination": "MIES-VAN-DER-ROHE-PREIS — NOMINIERUNG",
    "equerre d'argent 2015": "ÉQUERRE D'ARGENT 2015",
    "associate architect": "Assoziierte Architektin",
    "project director": "Projektleiterin",
    "next commission": "Nächster Auftrag",
    "main atelier:": "Hauptatelier:",
    "ils": "SIE HABEN",
    "we don't design for awards. we design for people and cities. brutalism is not a style — it's a conviction that architecture should be truthful about its materials and its purpose.": "Wir entwerfen nicht für Preise. Wir entwerfen für Menschen und Städte. Brutalismus ist kein Stil, sondern die Überzeugung, dass Architektur die Wahrheit über ihr Material und ihren Zweck sagen muss.",
    "our": "UNSER",
    "brutco doesn't deliver a building. they deliver a manifesto in concrete. we had no brief — only the ambition to create something that would outlast us. they made that real.": "Sie liefern kein Gebäude, sondern ein Manifest in Beton. Wir hatten kein Briefing — nur den Anspruch, etwas zu schaffen, das uns überdauert. Sie haben es wahr gemacht.",
    "\"buildings are not objects. they are the infrastructure of human life.\"": "„EIN GEBÄUDE IST KEIN OBJEKT. ES IST DIE INFRASTRUKTUR EINES LEBENS.“",
    "architectural competition strategy. we win because we think differently.": "Architekturwettbewerbsstrategie. Wir gewinnen, weil wir anders denken.",
    "as seen in": "Gesehen in",
    "built with us.": "MIT UNS GEBAUT.",
    "client accounts": "Kundenkonten",
    "concrete is honest.": "BETON LÜGT NICHT.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "Beton ist kein Rohstoff. Wir testen lokale Zuschläge, Grundwasserstände, Klimazyklen und regionale Formulierungen, bevor ein einziger Entwurf gezeichnet wird.",
    "every project starts with a conversation. tell us what you want to build and we'll tell you if we're the right firm.": "Jedes Projekt beginnt mit einem Gespräch. Sagen Sie uns, was Sie bauen möchten, und wir sagen Ihnen, ob wir die richtige Firma sind.",
    "get in touch →": "Kontakt aufnehmen →",
    "have a structure": "EIN BAUVORHABEN",
    "in mind?": "IM KOPF?",
    "master plans for districts, campuses, and large-scale developments.": "Masterpläne für Stadtteile, Campus und großflächige Entwicklungen.",
    "new construction from concept to delivery. we design buildings that endure.": "Neubau von der Idee bis zur Lieferung. Wir entwerfen Gebäude, die Bestand haben.",
    "our methodology": "Unsere Methode",
    "projects built": "Bauten realisiert",
    "see all work": "Alle Arbeiten ansehen",
    "start a": "STARTEN EIN",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "Das Design entsteht aus dem Material, nicht aus der Software. Handmodelle, gegossene Gipsprototypen und Standortmassenstudien bestimmen die Form.",
    "they": "SIE",
    "view full catalogue": "Vollständigen Katalog anzeigen",
    "we are brutal.": "WIR SIND BRUTAL.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Wir sind vor Ort präsent. Wir arbeiten mit spezialisierten Auftragnehmern, die im Rohbeton-Schalungsbau, Brettformabdrücken und Bushammer-Finishing ausgebildet sind.",
    "we build": "WIR BAUEN",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Wir arbeiten von Tag eins mit Tragwerksplanern zusammen. Scherwände, vorgespannten Platten und Kerngeometrien werden in der Konzeptphase gelöst.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Wir zerlegen Ihr Briefing, um die strukturelle Idee dahinter zu finden. Die meisten Kunden denken, sie wollen ein Gebäude. Tatsächlich wollen sie eine Institution.",
    "years active": "Aktive Jahre",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "a document about how i work — the tools, the philosophy, and the physical setup. because the environment shapes the output.": "Um documento sobre a minha forma de trabalhar — as ferramentas, a filosofia, a instalação. Porque o ambiente molda o resultado.",
    "a brilliant trick that three engineers can't read next quarter is a liability, not an asset. i optimize for the next engineer on the codebase.": "Um truque brilhante que três engenheiros já não saberão ler no próximo trimestre é um passivo, não um ativo. Otimizo para o próximo engenheiro no código.",
    "intuition about performance is usually wrong. profilers, distributed traces, and real production telemetry should drive optimization decisions.": "A intuição sobre desempenho quase sempre se engana. Perfis, rastreios distribuídos e telemetria de produção devem guiar as decisões de otimização.",
    "a 50-line pr that ships today beats a 500-line pr that lives in review for two weeks. i keep diffs reviewable and gates automated so features move.": "Um PR de 50 linhas entregue hoje vale mais do que um de 500 que fica duas semanas em revisão. Mantenho diffs legíveis e controlos automatizados para que as coisas avancem.",
    "orbit is intentionally small. we take 4 projects per quarter — never more. every client gets every senior person in the room. that's the model.": "A Orbit é deliberadamente pequena. Quatro projetos por trimestre — nunca mais. Cada cliente tem todos os seniores à mesa. É o modelo.",
    "brand strategist with a background in semiotics and behavioral economics. previously at wolff olins london. believes every great identity starts with a sharp point of view.": "Estratega de marca, vinda da semiótica e da economia comportamental. Antes na Wolff Olins em Londres. Convicta de que toda a grande identidade parte de um ponto de vista afiado.",
    "typography obsessive, systems thinker, former pentagram. sana turns strategic clarity into visual precision — nothing is arbitrary, everything scales.": "Obcecada por tipografia, mente sistémica, ex-Pentagram. A Sana converte clareza estratégica em precisão visual — nada é arbitrário, tudo escala.",
    "bridges static brand into living systems — motion identity, interactive web, digital touchpoints. worked with nike digital and spotify design.": "Leva a marca do estático ao vivo — identidade em movimento, web interativa, pontos de contacto digitais. Trabalhou com a Nike Digital e o Spotify Design.",
    "high-performance 3d components engineered for the modern web. we blend creative artistry with rigorous gpu-level optimization.": "Componentes 3D de alto desempenho para a web moderna. Unimos o gesto criativo a uma otimização rigorosa ao nível do GPU.",
    "high-fidelity real-time 3d rendering directly inside the browser. we construct lightweight meshes, optimized pbr textures, and physically accurate lighting.": "Renderização 3D em tempo real de alta fidelidade, diretamente no navegador: malhas leves, texturas PBR otimizadas, iluminação fisicamente exata.",
    "no-app-install interactive augmented reality campaigns. by tapping a link, clients can place products directly in their physical space with photorealistic accuracy.": "Campanhas de realidade aumentada sem aplicação: com um simples link, o cliente coloca o produto no seu espaço com realismo fotográfico.",
    "camera filters and custom overlays": "Filtros de câmara e sobreposições à medida",
    "prism connects natively to your warehouse, crm, payments processor, and advertising channels. no custom api integrations required.": "O Prism liga-se nativamente ao seu armazém de dados, CRM, processador de pagamentos e canais publicitários. Sem integrações à medida.",
    "sync raw events natively from databases and query engines.": "Sincronize eventos em bruto das suas bases e motores de consulta.",
    "align transaction records with user behavior metrics.": "Alinhe as transações com as métricas de comportamento.",
    "enrich user profiles and trigger messaging based on user actions.": "Enriqueça os perfis e dispare mensagens conforme as ações.",
    "end-to-end design from sketch to concrete pouring. we operate with structural honesty as our primary directive, refusing visual compromise.": "Conceção de ponta a ponta, do esboço à betonagem. A honestidade estrutural é a nossa diretiva primeira, sem compromissos visuais.",
    "scope of work:": "Âmbito:",
    "large-scale layout strategies for public institutions and campuses. we design masterplans that anchor architectural clusters with logical density.": "Estratégias de ordenamento em grande escala para instituições públicas e campi. Os nossos planos diretores ancoram os conjuntos numa densidade lógica.",
    "we leave steel, concrete, and conduits exposed, making interior systems an integral part of the aesthetic rather than hiding them behind finishes.": "Deixamos o aço, o betão e as condutas à vista: os sistemas interiores fazem parte da estética em vez de se esconderem atrás de acabamentos.",
    "seven days in an ancient desert landscape. dawn somatic practice, silent midday walks, and evening fire ceremonies. no agenda. no performance.": "Sete dias num deserto antigo. Prática somática de madrugada, caminhadas silenciosas ao meio-dia, cerimónias do fogo à noite. Sem agenda. Sem desempenho.",
    "immersive retreat experiences in the world's most transformative landscapes. maximum nine participants. stillness as practice.": "Retiros imersivos nas paisagens mais transformadoras do mundo. Nove participantes no máximo. A calma como prática.",
    "i spend weeks in each location before making an image. the mountains don't care about my schedule. the fog rolls in when it wants. this patience is the whole method.": "Passo semanas em cada lugar antes de fazer uma imagem. As montanhas não querem saber do meu calendário. O nevoeiro chega quando quer. Essa paciência é todo o método.",
    "each print is made in partnership with atelier gaspard in": "Cada impressão é feita com o Atelier Gaspard em",
    "for editorial licensing, commercial usage, or private commissions, get in touch directly. for print enquiries, visit the shop.": "Para licenças editoriais, usos comerciais ou encomendas privadas, escreva-me diretamente. Para impressões, passe pela loja.",
    "bring the wild": "Traga o selvagem",
    "that's the point.": "É exatamente esse o ponto.",
    "we work with raw concrete, steel, and industrial glass. we refuse to hide the integrity of materials behind plasterboard or paint.": "Trabalhamos o betão à vista, o aço e o vidro industrial. Recusamos esconder a integridade dos materiais atrás do gesso ou da tinta.",
    "the columns, slabs, and shear walls that hold the building up are the architecture itself. form follows structure.": "Os pilares, as lajes e as paredes que sustentam o edifício são a própria arquitetura. A forma segue a estrutura.",
    "mass, weight, and light create spatial meaning. we build block-like forms that capture the shifting paths of natural light.": "A massa, o peso e a luz dão sentido ao espaço. Construímos volumes francos que captam os percursos mutáveis da luz natural.",
    "a structure should survive generations. we build with permanent textures that require zero maintenance and age gracefully.": "Uma estrutura deve atravessar gerações. Construímos com texturas perenes, sem manutenção, que envelhecem bem.",
    "with a simple commitment: to return architecture to its raw, structural roots. rejecting the glass-and-plasterboard standards of commercial offices, the founders built a practice devoted to raw material truth.": "com um compromisso simples: devolver a arquitetura às suas raízes brutas e estruturais. Recusando o vidro e o gesso dos escritórios comerciais, os fundadores construíram um gabinete dedicado à verdade do material.",
    "today, the office comprises 24 architects, engineers, and material scientists, working from three ateliers in": "Hoje, o gabinete reúne 24 arquitetos, engenheiros e especialistas em materiais, repartidos por três ateliers em",
    "founded 2008": "Fundada em 2008",
    "what": "O QUE",
    "matters.": "IMPORTA.",
    "national awards": "Prémios nacionais",
    "construction value": "Valor construído",
    "bloc k — social housing complex": "BLOC K — conjunto de habitação social",
    "residential": "Residencial",
    "bunker office — hq renovation": "BUNKER OFFICE — reabilitação de uma sede",
    "concrete chapel": "CAPELA DE BETÃO",
    "urban planning": "Urbanismo",
    "interior architecture": "Arquitetura de interiores",
    "heritage renovation": "Reabilitação do património",
    "competition": "Concursos",
    "material": "A VERDADE",
    "truth": "DO MATERIAL",
    "founding partner": "Sócio fundador",
    "brief deconstruction": "Desconstrução do programa",
    "2 — 4 weeks": "2 a 4 semanas",
    "material research": "Investigação de materiais",
    "3 — 6 weeks": "3 a 6 semanas",
    "monolithic concept": "Conceito monolítico",
    "4 — 8 weeks": "4 a 8 semanas",
    "engineering integration": "Integração da engenharia",
    "6 — 12 weeks": "6 a 12 semanas",
    "construction & delivery": "Obra e entrega",
    "12 — 36 months": "12 a 36 meses",
    "full methodology": "Toda a metodologia",
    "referenced project": "Projeto citado",
    "european concrete award 2023": "PRÉMIO EUROPEU DO BETÃO 2023",
    "riba international prize — shortlist": "PRÉMIO INTERNACIONAL RIBA — FINALISTA",
    "mies van der rohe award — nomination": "PRÉMIO MIES VAN DER ROHE — NOMEAÇÃO",
    "equerre d'argent 2015": "ÉQUERRE D'ARGENT 2015",
    "associate architect": "Arquiteta associada",
    "project director": "Diretora de projeto",
    "next commission": "Próxima encomenda",
    "main atelier:": "Atelier principal:",
    "ils": "ELES",
    "we don't design for awards. we design for people and cities. brutalism is not a style — it's a conviction that architecture should be truthful about its materials and its purpose.": "Não desenhamos para prémios. Desenhamos para pessoas e para cidades. O brutalismo não é um estilo: é a convicção de que a arquitetura deve dizer a verdade sobre os seus materiais e o seu uso.",
    "our": "O NOSSO",
    "brutco doesn't deliver a building. they deliver a manifesto in concrete. we had no brief — only the ambition to create something that would outlast us. they made that real.": "Não entregam um edifício: entregam um manifesto em betão. Não tínhamos caderno de encargos — apenas a ambição de fazer algo que nos sobrevivesse. Tornaram-no real.",
    "\"buildings are not objects. they are the infrastructure of human life.\"": "«UM EDIFÍCIO NÃO É UM OBJETO. É A INFRAESTRUTURA DE UMA VIDA.»",
    "architectural competition strategy. we win because we think differently.": "Estratégia de competição arquitetónica. Vencemos porque pensamos de forma diferente.",
    "as seen in": "Visto em",
    "built with us.": "CONSTRUÍDO CONNOSCO.",
    "client accounts": "Contas de clientes",
    "concrete is honest.": "O BETÃO NÃO MENTE.",
    "concrete is not a commodity. we test local aggregate, water tables, climate cycles, and regional formulations before a single sketch is drawn.": "O betão não é uma mercadoria. Testamos agregados locais, lençóis freáticos, ciclos climáticos e formulações regionais antes de desenhar um único esboço.",
    "every project starts with a conversation. tell us what you want to build and we'll tell you if we're the right firm.": "Cada projeto começa com uma conversa. Diga-nos o que deseja construir e diremos se somos a empresa certa.",
    "get in touch →": "Fale connosco →",
    "have a structure": "UM PROJETO DE ESTRUTURA",
    "in mind?": "EM MENTE?",
    "master plans for districts, campuses, and large-scale developments.": "Planos mestres para distritos, campi e desenvolvimentos em grande escala.",
    "new construction from concept to delivery. we design buildings that endure.": "Nova construção do conceito à entrega. Projetamos edifícios que perduram.",
    "our methodology": "O nosso método",
    "projects built": "Projetos construídos",
    "see all work": "Ver todos os trabalhos",
    "start a": "INICIAR UM",
    "the design emerges from the material, not from the software. hand models, cast plaster prototypes, and site massing studies drive the form.": "O design emerge do material, não do software. Modelos manuais, protótipos de gesso fundido e estudos de massa no local definem a forma.",
    "they": "ELES",
    "view full catalogue": "Ver catálogo completo",
    "we are brutal.": "SOMOS BRUTOS.",
    "we are present on site. we work with specialised contractors trained in raw concrete shuttering, board-form impressions, and bush-hammer finishing.": "Estamos presentes no local. Trabalhamos com empreiteiros especializados treinados em cofragem de betão bruto, impressões de tábuas e acabamentos com martelo de arbusto.",
    "we build": "CONSTRUÍMOS",
    "we collaborate with structural engineers from day one. shear walls, post-tensioned slabs, and core geometries are resolved in the concept phase.": "Colaboramos com engenheiros estruturais desde o primeiro dia. Paredes de cisalhamento, lajes pós-tensionadas e geometrias centrais são resolvidas na fase de conceito.",
    "we dismantle your brief to find the structural idea behind it. most clients think they want a building. they actually want an institution.": "Desmontamos o seu briefing para encontrar a ideia estrutural por trás dele. A maioria dos clientes pensa que quer um edifício. Na verdade, querem uma instituição.",
    "years active": "Anos ativos",
  },
};
