/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"we don't reproduce sound. we recreate the air as it was at the moment of creation.\"": "« Nous ne reproduisons pas le son. Nous recréons l'air tel qu'il était à l'instant de la création. »",
    "book private audition": "Réserver une audition privée",
    "client": "Client",
    "explore instruments": "Explorer les instruments",
    "founded on the belief that perfect audio is not measured in decibels, but in emotional resonance. engineered for the infinite.": "Fondé sur une conviction : le son juste ne se mesure pas en décibels, mais en émotion. Conçu pour durer.",
    "hear the": "Entendre le",
    "hear the void": "Entendre le silence",
    "i've designed rooms with every major brand. none hold a candle to what their engineering team achieved at this price point. extraordinary.": "J'ai conçu des salles avec toutes les grandes marques. Aucune n'égale ce que leur équipe d'ingénierie a réalisé à ce prix. Extraordinaire.",
    "luthier-grade acoustic engineering for the discerning audiophile. experience the silence between the notes.": "Ingénierie acoustique de niveau luthier pour l'audiophile exigeant. Découvrez le silence entre les notes.",
    "mass-loaded polymer shells that eliminate cabinet vibration and coloration.": "Des coques en polymère chargé, qui suppriment les vibrations et la coloration du caisson.",
    "measurement-grade accuracy for monitoring and critical listening sessions.": "Une justesse de mesure, pour l'écoute de contrôle et l'écoute critique.",
    "recognised by": "Reconnu par",
    "request audit": "Demander un audit",
    "schedule a private acoustic audit at our berlin or tokyo studios. experience the pinnacle of audio engineering.": "Planifiez un audit acoustique privé dans nos studios de Berlin ou de Tokyo. Découvrez le summum de l'ingénierie audio.",
    "tec award best hardware": "Prix TEC Meilleur Matériel",
    "the aether principle": "Notre principe",
    "the monitoring accuracy of the reference series changed my mixes. i'm hearing nuances i used to think only other engineers had the ears to perceive.": "La précision de monitoring de la Reference Series a changé mes mixages. J'entends des nuances que je pensais que seuls d'autres ingénieurs pouvaient percevoir.",
    "view specifications": "Voir les spécifications",
    "we installed the studio array in our film scoring stage. the first session, the composer wept. the clarity revealed things we had been missing for a decade.": "Nous avons installé le Studio Array dans notre studio de composition musicale. Lors de la première session, le compositeur a pleuré. La clarté a révélé des choses que nous avions manquées pendant une décennie.",
    "who listens": "Qui écoute",
    "zero-latency response times for the most complex harmonic textures.": "Une réponse sans latence, jusque dans les textures harmoniques les plus complexes.",
  },
  es: {
    "\"we don't reproduce sound. we recreate the air as it was at the moment of creation.\"": "«No reproducimos el sonido. Recreamos el aire tal como era en el instante de la creación.»",
    "book private audition": "Reservar audición privada",
    "client": "Cliente",
    "explore instruments": "Explorar instrumentos",
    "founded on the belief that perfect audio is not measured in decibels, but in emotional resonance. engineered for the infinite.": "Fundado sobre una convicción: el sonido justo no se mide en decibelios, sino en emoción. Concebido para durar.",
    "hear the": "Escuchar el",
    "hear the void": "Escuchar el silencio",
    "i've designed rooms with every major brand. none hold a candle to what their engineering team achieved at this price point. extraordinary.": "He diseñado salas con todas las grandes marcas. Ninguna se compara con lo que su equipo de ingeniería logró a este precio. Extraordinario.",
    "luthier-grade acoustic engineering for the discerning audiophile. experience the silence between the notes.": "Ingeniería acústica de nivel lutier para el audiófilo exigente. Experimenta el silencio entre las notas.",
    "mass-loaded polymer shells that eliminate cabinet vibration and coloration.": "Cajas de polímero cargado, que suprimen las vibraciones y la coloración del recinto.",
    "measurement-grade accuracy for monitoring and critical listening sessions.": "Una exactitud de medida, para la escucha de control y la escucha crítica.",
    "recognised by": "Reconocido por",
    "request audit": "Solicitar una auditoría",
    "schedule a private acoustic audit at our berlin or tokyo studios. experience the pinnacle of audio engineering.": "Programa una auditoría acústica privada en nuestros estudios de Berlín o Tokio. Experimenta la cúspide de la ingeniería de audio.",
    "tec award best hardware": "Premio TEC Mejor Hardware",
    "the aether principle": "Nuestro principio",
    "the monitoring accuracy of the reference series changed my mixes. i'm hearing nuances i used to think only other engineers had the ears to perceive.": "La precisión de monitoreo de la Reference Series cambió mis mezclas. Estoy escuchando matices que solía pensar que solo otros ingenieros podían percibir.",
    "view specifications": "Ver especificaciones",
    "we installed the studio array in our film scoring stage. the first session, the composer wept. the clarity revealed things we had been missing for a decade.": "Instalamos el Studio Array en nuestro estudio de composición musical. En la primera sesión, el compositor lloró. La claridad reveló cosas que habíamos estado perdiendo durante una década.",
    "who listens": "Quién escucha",
    "zero-latency response times for the most complex harmonic textures.": "Una respuesta sin latencia, hasta en las texturas armónicas más complejas.",
  },
  de: {
    "\"we don't reproduce sound. we recreate the air as it was at the moment of creation.\"": "„Wir geben Klang nicht wieder. Wir erschaffen die Luft neu, wie sie im Augenblick der Entstehung war.“",
    "book private audition": "Private Anhörung buchen",
    "client": "Kunde",
    "explore instruments": "Instrumente erkunden",
    "founded on the belief that perfect audio is not measured in decibels, but in emotional resonance. engineered for the infinite.": "Gegründet auf der Überzeugung, dass perfekter Klang nicht in Dezibel gemessen wird, sondern in Ergriffenheit. Für die Ewigkeit gebaut.",
    "hear the": "Hören Sie das",
    "hear the void": "Die Stille hören",
    "i've designed rooms with every major brand. none hold a candle to what their engineering team achieved at this price point. extraordinary.": "Ich habe Räume mit jeder großen Marke entworfen. Keine kann mit dem vergleichen, was ihr Ingenieurteam zu diesem Preis erreicht hat. Außergewöhnlich.",
    "luthier-grade acoustic engineering for the discerning audiophile. experience the silence between the notes.": "Akustikingenieurwesen auf Luthier-Niveau für den anspruchsvollen Audiophilen. Erleben Sie die Stille zwischen den Noten.",
    "mass-loaded polymer shells that eliminate cabinet vibration and coloration.": "Massebeladene Polymergehäuse, die Gehäusevibration und Klangfärbung ausschalten.",
    "measurement-grade accuracy for monitoring and critical listening sessions.": "Messgenauigkeit für Monitoring und kritisches Hören.",
    "recognised by": "Anerkannt von",
    "request audit": "Audit anfordern",
    "schedule a private acoustic audit at our berlin or tokyo studios. experience the pinnacle of audio engineering.": "Vereinbaren Sie eine private akustische Prüfung in unseren Studios in Berlin oder Tokio. Erleben Sie den Höhepunkt der Audioengineering.",
    "tec award best hardware": "TEC Award Bester Hardware",
    "the aether principle": "Unser Grundsatz",
    "the monitoring accuracy of the reference series changed my mixes. i'm hearing nuances i used to think only other engineers had the ears to perceive.": "Die Überwachungsgenauigkeit der Reference Series hat meine Mixe verändert. Ich höre Nuancen, von denen ich dachte, dass nur andere Ingenieure die Ohren dafür hätten.",
    "view specifications": "Spezifikationen anzeigen",
    "we installed the studio array in our film scoring stage. the first session, the composer wept. the clarity revealed things we had been missing for a decade.": "Wir haben das Studio Array in unserer Filmkompositionsbühne installiert. In der ersten Sitzung weinte der Komponist. Die Klarheit offenbarte Dinge, die wir ein Jahrzehnt lang vermisst hatten.",
    "who listens": "Wer hört",
    "zero-latency response times for the most complex harmonic textures.": "Reaktion ohne Latenz, bis in die komplexesten harmonischen Texturen.",
  },
  pt: {
    "\"we don't reproduce sound. we recreate the air as it was at the moment of creation.\"": "«Não reproduzimos o som. Recriamos o ar tal como era no instante da criação.»",
    "book private audition": "Reservar audição privada",
    "client": "Cliente",
    "explore instruments": "Explorar instrumentos",
    "founded on the belief that perfect audio is not measured in decibels, but in emotional resonance. engineered for the infinite.": "Fundado sobre uma convicção: o som justo não se mede em decibéis, mas em emoção. Concebido para durar.",
    "hear the": "Ouça o",
    "hear the void": "Ouvir o silêncio",
    "i've designed rooms with every major brand. none hold a candle to what their engineering team achieved at this price point. extraordinary.": "Projetei salas com todas as grandes marcas. Nenhuma se compara ao que a sua equipe de engenharia alcançou a este preço. Extraordinário.",
    "luthier-grade acoustic engineering for the discerning audiophile. experience the silence between the notes.": "Engenharia acústica de nível de luthier para o audiófilo exigente. Experimente o silêncio entre as notas.",
    "mass-loaded polymer shells that eliminate cabinet vibration and coloration.": "Caixas de polímero carregado, que suprimem as vibrações e a coloração da caixa.",
    "measurement-grade accuracy for monitoring and critical listening sessions.": "Uma exatidão de medida, para a escuta de controlo e a escuta crítica.",
    "recognised by": "Reconhecido por",
    "request audit": "Pedir uma auditoria",
    "schedule a private acoustic audit at our berlin or tokyo studios. experience the pinnacle of audio engineering.": "Agende uma auditoria acústica privada em nossos estúdios em Berlim ou Tóquio. Experimente o auge da engenharia de áudio.",
    "tec award best hardware": "Prémio TEC Melhor Hardware",
    "the aether principle": "O nosso princípio",
    "the monitoring accuracy of the reference series changed my mixes. i'm hearing nuances i used to think only other engineers had the ears to perceive.": "A precisão de monitorização da Reference Series mudou as minhas misturas. Estou a ouvir nuances que costumava pensar que apenas outros engenheiros conseguiam perceber.",
    "view specifications": "Ver especificações",
    "we installed the studio array in our film scoring stage. the first session, the composer wept. the clarity revealed things we had been missing for a decade.": "Instalámos o Studio Array no nosso estúdio de composição musical. Na primeira sessão, o compositor chorou. A clareza revelou coisas que tínhamos perdido durante uma década.",
    "who listens": "Quem ouve",
    "zero-latency response times for the most complex harmonic textures.": "Uma resposta sem latência, até nas texturas harmónicas mais complexas.",
  },
};
