/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "« Dans le silence des rouages, on trouve le rythme absolu de l'existence. Maîtrisé à Genève depuis 1892. »",
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "\"Dans le silence des rouages, nous trouvons le rythme absolu de l'existence. Maîtrisé à Genève depuis 1892.\"",
    "crafting high-fidelity movements that beat with the rhythm of tradition and the precision of tomorrow.": "Création de mouvements haute fidélité qui battent au rythme de la tradition et à la précision de demain.",
    "each gear is finished with artisan precision under 20x magnification.": "Chaque rouage est terminé à la main, sous grossissement vingt fois.",
    "each piece undergoes pressure, temperature, and magnetic resistance testing before certification.": "Chaque pièce passe des essais de pression, de température et de résistance magnétique avant certification.",
    "every zenith timepiece is powered by our proprietary caliber-9 series movement, featuring 242 hand-polished components and a 72-hour power reserve.": "Chaque montre Zenith est alimentée par notre mouvement de série Caliber-9, comprenant 242 composants polis à la main et une réserve de marche de 72 heures.",
    "explore collections": "Explorer les Collections",
    "i compared it directly against lange and patek at my usual dealer. zenith's movement finishing at this price point is simply audacious.": "Je l'ai comparé directement à Lange et Patek chez mon revendeur habituel. La finition du mouvement de Zenith à ce prix est tout simplement audacieuse.",
    "in their": "Selon eux",
    "limited production runs. each piece is individually numbered and accompanied by a digital certificate of authenticity on the zenith mesh.": "Séries de production limitées. Chaque pièce est numérotée individuellement et accompagnée d'un certificat numérique d'authenticité sur le maillage Zenith.",
    "made by": "Fabriqué par",
    "my lunar phase arrived with a personal letter from the atelier chief. that kind of craft and attention doesn't exist anymore. except here.": "Ma Lunar Phase est arrivée avec une lettre personnelle du chef d'atelier. Ce genre de savoir-faire et d'attention n'existe plus. Sauf ici.",
    "open caseback viewing": "Fond ouvert, mouvement visible",
    "own the": "POSSÉDEZ LE",
    "request allocation": "Demander une Allocation",
    "request bespoke": "Demande sur mesure",
    "the chronos 01": "Le Chronos 01",
    "the chronos 01 is the only watch i've worn every day for four years. it has aged the way all great things do — with more character, not less.": "Le Chronos 01 est la seule montre que j'ai portée tous les jours pendant quatre ans. Elle a vieilli comme toutes les grandes choses — avec plus de caractère, pas moins.",
    "the workshop": "L'atelier",
    "view registry": "Voir le Registre",
    "witness the movement": "Voir le mouvement",
    "zenith watch": "Zenith Montre",
  },
  es: {
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "«En el silencio de los engranajes se halla el ritmo absoluto de la existencia. Dominado en Ginebra desde 1892.»",
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "\"En el silencio de los engranajes, encontramos el ritmo absoluto de la existencia. Dominado en Ginebra desde 1892.\"",
    "crafting high-fidelity movements that beat with the rhythm of tradition and the precision of tomorrow.": "Creando movimientos de alta fidelidad que laten con el ritmo de la tradición y la precisión del mañana.",
    "each gear is finished with artisan precision under 20x magnification.": "Cada engranaje se acaba a mano, con un aumento de veinte veces.",
    "each piece undergoes pressure, temperature, and magnetic resistance testing before certification.": "Cada pieza pasa ensayos de presión, temperatura y resistencia magnética antes de la certificación.",
    "every zenith timepiece is powered by our proprietary caliber-9 series movement, featuring 242 hand-polished components and a 72-hour power reserve.": "Cada reloj Zenith está impulsado por nuestro movimiento de la serie Caliber-9, que cuenta con 242 componentes pulidos a mano y una reserva de marcha de 72 horas.",
    "explore collections": "Explorar Colecciones",
    "i compared it directly against lange and patek at my usual dealer. zenith's movement finishing at this price point is simply audacious.": "Lo comparé directamente con Lange y Patek en mi distribuidor habitual. El acabado del movimiento de Zenith a este precio es simplemente audaz.",
    "in their": "Según ellos",
    "limited production runs. each piece is individually numbered and accompanied by a digital certificate of authenticity on the zenith mesh.": "Tiradas de producción limitadas. Cada pieza está numerada individualmente y acompañada de un certificado digital de autenticidad en la malla Zenith.",
    "made by": "Hecho por",
    "my lunar phase arrived with a personal letter from the atelier chief. that kind of craft and attention doesn't exist anymore. except here.": "Mi Lunar Phase llegó con una carta personal del jefe del taller. Ese tipo de artesanía y atención ya no existe. Excepto aquí.",
    "open caseback viewing": "Fondo abierto, movimiento a la vista",
    "own the": "POSEA EL",
    "request allocation": "Solicitar Asignación",
    "request bespoke": "Solicitud a medida",
    "the chronos 01": "El Chronos 01",
    "the chronos 01 is the only watch i've worn every day for four years. it has aged the way all great things do — with more character, not less.": "El Chronos 01 es el único reloj que he llevado todos los días durante cuatro años. Ha envejecido como todas las grandes cosas — con más carácter, no menos.",
    "the workshop": "El taller",
    "view registry": "Ver Registro",
    "witness the movement": "Ver el movimiento",
    "zenith watch": "Zenith Reloj",
  },
  de: {
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "„In der Stille der Zahnräder findet sich der absolute Rhythmus des Daseins. Seit 1892 in Genf gemeistert.“",
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "\"In der Stille der Zahnräder finden wir den absoluten Rhythmus des Daseins. Seit 1892 in Genf gemeistert.\"",
    "crafting high-fidelity movements that beat with the rhythm of tradition and the precision of tomorrow.": "Gestaltung von hochpräzisen Bewegungen, die im Rhythmus der Tradition und mit der Präzision von morgen schlagen.",
    "each gear is finished with artisan precision under 20x magnification.": "Jedes Zahnrad wird von Hand bei zwanzigfacher Vergrößerung vollendet.",
    "each piece undergoes pressure, temperature, and magnetic resistance testing before certification.": "Jedes Stück durchläuft Druck-, Temperatur- und Magnetfeldprüfungen vor der Zertifizierung.",
    "every zenith timepiece is powered by our proprietary caliber-9 series movement, featuring 242 hand-polished components and a 72-hour power reserve.": "Jede Zenith-Uhr wird von unserem proprietären Caliber-9-Serie-Movement angetrieben, das 242 handpolierte Komponenten und eine Gangreserve von 72 Stunden umfasst.",
    "explore collections": "Kollektionen Entdecken",
    "i compared it directly against lange and patek at my usual dealer. zenith's movement finishing at this price point is simply audacious.": "Ich habe es direkt mit Lange und Patek bei meinem gewohnten Händler verglichen. Die Bewegung von Zenith in dieser Preisklasse ist einfach kühn.",
    "in their": "In ihren Worten",
    "limited production runs. each piece is individually numbered and accompanied by a digital certificate of authenticity on the zenith mesh.": "Limitierte Produktionsläufe. Jedes Stück ist einzeln nummeriert und wird von einem digitalen Echtheitszertifikat im Zenith-Netz begleitet.",
    "made by": "Hergestellt von",
    "my lunar phase arrived with a personal letter from the atelier chief. that kind of craft and attention doesn't exist anymore. except here.": "Meine Lunar Phase kam mit einem persönlichen Brief vom Atelierleiter. So eine Handwerkskunst und Aufmerksamkeit gibt es nicht mehr. Außer hier.",
    "open caseback viewing": "Offener Boden, sichtbares Werk",
    "own the": "BESITZEN SIE DIE",
    "request allocation": "Zuteilung Anfordern",
    "request bespoke": "Maßanfertigung anfragen",
    "the chronos 01": "Die Chronos 01",
    "the chronos 01 is the only watch i've worn every day for four years. it has aged the way all great things do — with more character, not less.": "Die Chronos 01 ist die einzige Uhr, die ich vier Jahre lang jeden Tag getragen habe. Sie ist gealtert, wie es bei allen großen Dingen der Fall ist — mit mehr Charakter, nicht weniger.",
    "the workshop": "Die Werkstatt",
    "view registry": "Registrierung Ansehen",
    "witness the movement": "Das Uhrwerk sehen",
    "zenith watch": "Zenith Uhr",
  },
  pt: {
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "«No silêncio das rodas dentadas encontra-se o ritmo absoluto da existência. Dominado em Genebra desde 1892.»",
    "\"in the silence of the gears, we find the absolute rhythm of existence. mastered in geneva since 1892.\"": "\"No silêncio das engrenagens, encontramos o ritmo absoluto da existência. Dominado em Genebra desde 1892.\"",
    "crafting high-fidelity movements that beat with the rhythm of tradition and the precision of tomorrow.": "Criando movimentos de alta fidelidade que batem com o ritmo da tradição e a precisão do amanhã.",
    "each gear is finished with artisan precision under 20x magnification.": "Cada roda dentada é acabada à mão, com ampliação de vinte vezes.",
    "each piece undergoes pressure, temperature, and magnetic resistance testing before certification.": "Cada peça passa ensaios de pressão, temperatura e resistência magnética antes da certificação.",
    "every zenith timepiece is powered by our proprietary caliber-9 series movement, featuring 242 hand-polished components and a 72-hour power reserve.": "Cada peça da Zenith é alimentada pelo nosso movimento da série Caliber-9, com 242 componentes polidos à mão e uma reserva de marcha de 72 horas.",
    "explore collections": "Explorar Coleções",
    "i compared it directly against lange and patek at my usual dealer. zenith's movement finishing at this price point is simply audacious.": "Comparei-o diretamente com Lange e Patek no meu revendedor habitual. O acabamento do movimento da Zenith a este preço é simplesmente audacioso.",
    "in their": "Segundo eles",
    "limited production runs. each piece is individually numbered and accompanied by a digital certificate of authenticity on the zenith mesh.": "Produções limitadas. Cada peça é numerada individualmente e acompanhada de um certificado digital de autenticidade na malha Zenith.",
    "made by": "Feito por",
    "my lunar phase arrived with a personal letter from the atelier chief. that kind of craft and attention doesn't exist anymore. except here.": "A minha Lunar Phase chegou com uma carta pessoal do chefe do ateliê. Esse tipo de artesanato e atenção já não existe. Exceto aqui.",
    "open caseback viewing": "Fundo aberto, movimento à vista",
    "own the": "POSSUA O",
    "request allocation": "Solicitar Atribuição",
    "request bespoke": "Pedido por medida",
    "the chronos 01": "O Chronos 01",
    "the chronos 01 is the only watch i've worn every day for four years. it has aged the way all great things do — with more character, not less.": "O Chronos 01 é o único relógio que usei todos os dias durante quatro anos. Ele envelheceu como todas as grandes coisas — com mais caráter, não menos.",
    "the workshop": "A oficina",
    "view registry": "Ver Registo",
    "witness the movement": "Ver o movimento",
    "zenith watch": "Zenith Relógio",
  },
};
