/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "14-day free trial": "Essai gratuit de 14 jours",
    "14-day free trial on all plans. no credit card required.": "Essai gratuit de 14 jours sur tous les plans. Aucune carte de crédit requise.",
    "all time": "DEPUIS TOUJOURS",
    "book a demo": "Réservez une démo",
    "co-located servers in nyse, nasdaq, and cme data centers. your orders arrive before the competition blinks.": "Des serveurs hébergés dans les centres du NYSE, du NASDAQ et du CME. Vos ordres arrivent avant que la concurrence ait cligné des yeux.",
    "deploy pre-built quant strategies or write your own in python. backtesting engine with 20 years of tick data.": "Déployez des stratégies quantitatives prêtes à l'emploi ou écrivez les vôtres en Python. Moteur de rétro-test avec vingt ans de données tick à tick.",
    "every position. every trade. every p&l metric — unified in a single real-time dashboard. know exactly where you stand at all times.": "Chaque position. Chaque transaction. Chaque métrique de P&L — unifiée dans un seul tableau de bord en temps réel. Sachez exactement où vous en êtes à tout moment.",
    "everything in pro": "Tout dans Pro",
    "everything wall street uses — now available for anyone serious enough to trade like a pro.": "Tout ce que Wall Street utilise — maintenant disponible pour quiconque est assez sérieux pour trader comme un pro.",
    "get access": "OBTENIR L'ACCÈS",
    "i went from losing $8k/month to profitably running 3 automated strategies. the risk controls saved me twice from blowing up my account during flash crashes.": "Je suis passé de pertes de 8 000 $/mois à gérer de manière rentable 3 stratégies automatisées. Les contrôles de risque m'ont sauvé deux fois d'exploser mon compte lors de krachs éclair.",
    "in real-time.": "En temps réel.",
    "join 48,000+ traders already running on trade os. 14 days free, no card required.": "Rejoignez plus de 48 000 traders déjà sur Trade OS. 14 jours gratuits, sans carte requise.",
    "level ii order book": "Carnet d'ordres de niveau II",
    "no subscription lock-in": "Pas de verrouillage d'abonnement",
    "per-position limits, daily drawdown kills, volatility circuit breakers. sleep while the system runs.": "Limites par position, les pertes quotidiennes tuent, les coupe-circuits de volatilité. Dormez pendant que le système fonctionne.",
    "real results from real traders — not cherry-picked demos.": "De vrais résultats, de vrais opérateurs — pas des démonstrations choisies.",
    "real-time": "Temps réel",
    "real-time alerts": "Alertes en temps réel",
    "real-time depth-of-market data across all major exchanges. see exactly where the liquidity sits.": "Le carnet d'ordres en temps réel sur toutes les grandes places. Voyez exactement où se trouve la liquidité.",
    "retail trader → full-time": "Trader de détail → Temps plein",
    "route to 40+ brokers simultaneously for best-price execution. smart order routing included.": "Acheminement vers plus de 40 courtiers simultanément pour une exécution au meilleur prix. Routage d'ordres intelligent inclus.",
    "sms, telegram, discord, email. conditional triggers on price, volume, volatility, or custom signals.": "SMS, Telegram, Discord, email. Déclencheurs conditionnels sur le prix, le volume, la volatilité ou des signaux personnalisés.",
    "start free trial →": "Essayer gratuitement →",
    "start trading smarter.": "Négociez plus finement.",
    "sub-millisecond execution. bloomberg-grade data. unlimited algorithmic strategies. built for traders who play at the highest level.": "Exécution en sous-millisecondes. Données de niveau Bloomberg. Stratégies algorithmiques illimitées. Conçu pour les traders qui jouent au plus haut niveau.",
    "the institutional-grade trading platform built for serious traders who demand sub-millisecond execution and professional-grade analytics.": "La plateforme de négociation de niveau institutionnel, faite pour ceux qui exigent une exécution sous la milliseconde et des analyses de professionnel.",
    "today's p&l": "P&L d'aujourd'hui",
    "track every asset.": "Suivez chaque actif.",
    "traders who": "Ceux qui",
    "trading involves substantial risk of loss. past performance does not guarantee future results.": "Le trading comporte un risque substantiel de perte. Les performances passées ne garantissent pas les résultats futurs.",
    "transparent pricing.": "Tarification transparente.",
    "up to 5 simultaneous strategies": "Jusqu'à 5 stratégies simultanées",
    "view live markets": "Voir les marchés en direct",
    "volume processed/year": "Volume traité/an",
    "your edge is waiting.": "Votre avantage vous attend.",
  },
  es: {
    "14-day free trial": "Prueba gratuita de 14 días",
    "14-day free trial on all plans. no credit card required.": "Prueba gratuita de 14 días en todos los planes. No se requiere tarjeta de crédito.",
    "all time": "DESDE SIEMPRE",
    "book a demo": "Reservar una demostración",
    "co-located servers in nyse, nasdaq, and cme data centers. your orders arrive before the competition blinks.": "Servidores alojados en los centros del NYSE, el NASDAQ y el CME. Sus órdenes llegan antes de que la competencia parpadee.",
    "deploy pre-built quant strategies or write your own in python. backtesting engine with 20 years of tick data.": "Despliegue estrategias cuantitativas listas o escriba las suyas en Python. Motor de backtesting con veinte años de datos tick a tick.",
    "every position. every trade. every p&l metric — unified in a single real-time dashboard. know exactly where you stand at all times.": "Cada posición. Cada operación. Cada métrica de P&L — unificada en un solo panel en tiempo real. Sepa exactamente dónde se encuentra en todo momento.",
    "everything in pro": "Todo en Pro",
    "everything wall street uses — now available for anyone serious enough to trade like a pro.": "Todo lo que utiliza Wall Street — ahora disponible para cualquiera que sea lo suficientemente serio como para operar como un profesional.",
    "get access": "OBTENER ACCESO",
    "i went from losing $8k/month to profitably running 3 automated strategies. the risk controls saved me twice from blowing up my account during flash crashes.": "Pasé de perder $8K/mes a gestionar de manera rentable 3 estrategias automatizadas. Los controles de riesgo me salvaron dos veces de hacer estallar mi cuenta durante caídas repentinas.",
    "in real-time.": "En tiempo real.",
    "join 48,000+ traders already running on trade os. 14 days free, no card required.": "Únete a más de 48,000 traders que ya utilizan Trade OS. 14 días gratis, sin tarjeta requerida.",
    "level ii order book": "Libro de órdenes de nivel II",
    "no subscription lock-in": "Sin compromiso de suscripción",
    "per-position limits, daily drawdown kills, volatility circuit breakers. sleep while the system runs.": "Límites por posición, las pérdidas diarias matan, los cortacircuitos de volatilidad. Duerme mientras el sistema funciona.",
    "real results from real traders — not cherry-picked demos.": "Resultados reales de operadores reales, no demostraciones escogidas.",
    "real-time": "Tiempo real",
    "real-time alerts": "Alertas en tiempo real",
    "real-time depth-of-market data across all major exchanges. see exactly where the liquidity sits.": "El libro de órdenes en tiempo real en todas las grandes plazas. Vea exactamente dónde está la liquidez.",
    "retail trader → full-time": "Operador minorista → Tiempo completo",
    "route to 40+ brokers simultaneously for best-price execution. smart order routing included.": "Ruta a más de 40 corredores simultáneamente para la ejecución al mejor precio. Enrutamiento de órdenes inteligente incluido.",
    "sms, telegram, discord, email. conditional triggers on price, volume, volatility, or custom signals.": "SMS, Telegram, Discord, correo electrónico. Disparadores condicionales en precio, volumen, volatilidad o señales personalizadas.",
    "start free trial →": "Probar gratis →",
    "start trading smarter.": "Opere con más criterio.",
    "sub-millisecond execution. bloomberg-grade data. unlimited algorithmic strategies. built for traders who play at the highest level.": "Ejecución en submilisegundos. Datos de nivel Bloomberg. Estrategias algorítmicas ilimitadas. Construido para traders que juegan al más alto nivel.",
    "the institutional-grade trading platform built for serious traders who demand sub-millisecond execution and professional-grade analytics.": "La plataforma de negociación de nivel institucional, hecha para quienes exigen ejecución por debajo del milisegundo y análisis profesionales.",
    "today's p&l": "P&L de hoy",
    "track every asset.": "Siga cada activo.",
    "traders who": "Quienes",
    "trading involves substantial risk of loss. past performance does not guarantee future results.": "El trading implica un riesgo sustancial de pérdida. El rendimiento pasado no garantiza resultados futuros.",
    "transparent pricing.": "Precios transparentes.",
    "up to 5 simultaneous strategies": "Hasta 5 estrategias simultáneas",
    "view live markets": "Ver Mercados en Vivo",
    "volume processed/year": "Volumen procesado/año",
    "your edge is waiting.": "Su ventaja le espera.",
  },
  de: {
    "14-day free trial": "14-tägige kostenlose Testversion",
    "14-day free trial on all plans. no credit card required.": "14-tägige kostenlose Testversion für alle Pläne. Keine Kreditkarte erforderlich.",
    "all time": "SEIT BEGINN",
    "book a demo": "Demo buchen",
    "co-located servers in nyse, nasdaq, and cme data centers. your orders arrive before the competition blinks.": "Server in den Rechenzentren von NYSE, NASDAQ und CME. Ihre Aufträge treffen ein, bevor die Konkurrenz blinzelt.",
    "deploy pre-built quant strategies or write your own in python. backtesting engine with 20 years of tick data.": "Setzen Sie fertige Quant-Strategien ein oder schreiben Sie eigene in Python. Backtesting-Engine mit zwanzig Jahren Tick-Daten.",
    "every position. every trade. every p&l metric — unified in a single real-time dashboard. know exactly where you stand at all times.": "Jede Position. Jeder Handel. Jede P&L-Metrik — in einem einzigen Echtzeit-Dashboard vereint. Wissen Sie jederzeit genau, wo Sie stehen.",
    "everything in pro": "Alles in Pro",
    "everything wall street uses — now available for anyone serious enough to trade like a pro.": "Alles, was die Wall Street nutzt — jetzt für jeden verfügbar, der ernsthaft wie ein Profi handeln möchte.",
    "get access": "ZUGANG ERHALTEN",
    "i went from losing $8k/month to profitably running 3 automated strategies. the risk controls saved me twice from blowing up my account during flash crashes.": "Ich ging von einem Verlust von 8.000 $/Monat zu einem profitablen Betrieb von 3 automatisierten Strategien über. Die Risikokontrollen haben mich zweimal davor bewahrt, mein Konto während Flash-Crashes zu sprengen.",
    "in real-time.": "In Echtzeit.",
    "join 48,000+ traders already running on trade os. 14 days free, no card required.": "Schließen Sie sich über 48.000 Trader an, die bereits auf Trade OS laufen. 14 Tage kostenlos, keine Karte erforderlich.",
    "level ii order book": "Orderbuch der Stufe II",
    "no subscription lock-in": "Keine Bindung an ein Abonnement",
    "per-position limits, daily drawdown kills, volatility circuit breakers. sleep while the system runs.": "Positionslimits, tägliche Drawdown-Limits, Volatilitätsunterbrecher. Schlafen Sie, während das System läuft.",
    "real results from real traders — not cherry-picked demos.": "Echte Ergebnisse echter Händler — keine ausgesuchten Demos.",
    "real-time": "Echtzeit",
    "real-time alerts": "Echtzeitwarnungen",
    "real-time depth-of-market data across all major exchanges. see exactly where the liquidity sits.": "Marktttiefe in Echtzeit an allen großen Börsen. Sehen Sie genau, wo die Liquidität liegt.",
    "retail trader → full-time": "Einzelhändler → Vollzeit",
    "route to 40+ brokers simultaneously for best-price execution. smart order routing included.": "Routing zu über 40 Brokern gleichzeitig für die beste Preisausführung. Intelligentes Orderrouting enthalten.",
    "sms, telegram, discord, email. conditional triggers on price, volume, volatility, or custom signals.": "SMS, Telegram, Discord, E-Mail. Bedingte Auslöser für Preis, Volumen, Volatilität oder benutzerdefinierte Signale.",
    "start free trial →": "Kostenlos testen →",
    "start trading smarter.": "Handeln Sie klüger.",
    "sub-millisecond execution. bloomberg-grade data. unlimited algorithmic strategies. built for traders who play at the highest level.": "Unter-Millisekunden-Ausführung. Bloomberg-Qualitätsdaten. Unbegrenzte algorithmische Strategien. Entwickelt für Trader, die auf höchstem Niveau spielen.",
    "the institutional-grade trading platform built for serious traders who demand sub-millisecond execution and professional-grade analytics.": "Die Handelsplattform auf institutionellem Niveau, für alle, die Ausführung unter einer Millisekunde und professionelle Analysen verlangen.",
    "today's p&l": "Heutige P&L",
    "track every asset.": "Verfolgen Sie jeden Wert.",
    "traders who": "Wer",
    "trading involves substantial risk of loss. past performance does not guarantee future results.": "Der Handel birgt ein erhebliches Risiko von Verlusten. Frühere Leistungen garantieren keine zukünftigen Ergebnisse.",
    "transparent pricing.": "Transparente Preisgestaltung.",
    "up to 5 simultaneous strategies": "Bis zu 5 gleichzeitige Strategien",
    "view live markets": "Live-Märkte anzeigen",
    "volume processed/year": "Verarbeitetes Volumen/Jahr",
    "your edge is waiting.": "Ihr Vorsprung wartet.",
  },
  pt: {
    "14-day free trial": "Teste gratuito de 14 dias",
    "14-day free trial on all plans. no credit card required.": "Teste gratuito de 14 dias em todos os planos. Não é necessário cartão de crédito.",
    "all time": "DESDE SEMPRE",
    "book a demo": "Agendar uma Demonstração",
    "co-located servers in nyse, nasdaq, and cme data centers. your orders arrive before the competition blinks.": "Servidores alojados nos centros da NYSE, da NASDAQ e da CME. As suas ordens chegam antes de a concorrência pestanejar.",
    "deploy pre-built quant strategies or write your own in python. backtesting engine with 20 years of tick data.": "Implante estratégias quantitativas prontas ou escreva as suas em Python. Motor de backtesting com vinte anos de dados tick a tick.",
    "every position. every trade. every p&l metric — unified in a single real-time dashboard. know exactly where you stand at all times.": "Cada posição. Cada negociação. Cada métrica de P&L — unificada em um único painel em tempo real. Saiba exatamente onde você está a todo momento.",
    "everything in pro": "Tudo no Pro",
    "everything wall street uses — now available for anyone serious enough to trade like a pro.": "Tudo o que Wall Street usa — agora disponível para quem é sério o suficiente para negociar como um profissional.",
    "get access": "OBTER ACESSO",
    "i went from losing $8k/month to profitably running 3 automated strategies. the risk controls saved me twice from blowing up my account during flash crashes.": "Passei de perder 8 mil dólares/mês a operar de forma lucrativa 3 estratégias automatizadas. Os controles de risco me salvaram duas vezes de estourar minha conta durante quedas repentinas.",
    "in real-time.": "Em tempo real.",
    "join 48,000+ traders already running on trade os. 14 days free, no card required.": "Junte-se a mais de 48.000 traders que já utilizam o Trade OS. 14 dias grátis, sem necessidade de cartão.",
    "level ii order book": "Livro de ordens de nível II",
    "no subscription lock-in": "Sem compromisso de subscrição",
    "per-position limits, daily drawdown kills, volatility circuit breakers. sleep while the system runs.": "Limites por posição, perdas diárias matam, disjuntores de volatilidade. Durma enquanto o sistema funciona.",
    "real results from real traders — not cherry-picked demos.": "Resultados reais de operadores reais — não demonstrações escolhidas.",
    "real-time": "Tempo real",
    "real-time alerts": "Alertas em tempo real",
    "real-time depth-of-market data across all major exchanges. see exactly where the liquidity sits.": "O livro de ordens em tempo real em todas as grandes praças. Veja exatamente onde está a liquidez.",
    "retail trader → full-time": "Trader de retalho → Tempo integral",
    "route to 40+ brokers simultaneously for best-price execution. smart order routing included.": "Roteamento para mais de 40 corretores simultaneamente para execução ao melhor preço. Roteamento inteligente de ordens incluído.",
    "sms, telegram, discord, email. conditional triggers on price, volume, volatility, or custom signals.": "SMS, Telegram, Discord, email. Disparadores condicionais em preço, volume, volatilidade ou sinais personalizados.",
    "start free trial →": "Testar gratuitamente →",
    "start trading smarter.": "Negoceie com mais critério.",
    "sub-millisecond execution. bloomberg-grade data. unlimited algorithmic strategies. built for traders who play at the highest level.": "Execução em submilissegundos. Dados de nível Bloomberg. Estratégias algorítmicas ilimitadas. Construído para traders que jogam no mais alto nível.",
    "the institutional-grade trading platform built for serious traders who demand sub-millisecond execution and professional-grade analytics.": "A plataforma de negociação de nível institucional, feita para quem exige execução abaixo do milissegundo e análises profissionais.",
    "today's p&l": "P&L de hoje",
    "track every asset.": "Siga cada ativo.",
    "traders who": "Quem",
    "trading involves substantial risk of loss. past performance does not guarantee future results.": "A negociação envolve um risco substancial de perda. O desempenho passado não garante resultados futuros.",
    "transparent pricing.": "Preços transparentes.",
    "up to 5 simultaneous strategies": "Até 5 estratégias simultâneas",
    "view live markets": "Ver Mercados ao Vivo",
    "volume processed/year": "Volume processado/ano",
    "your edge is waiting.": "A sua vantagem espera por si.",
  },
};
