/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "avg. conversion uplift": "Gain de conversion moyen",
    "3d branding": "Identité 3D",
    "valo — brand identity in 3d": "VALO — une identité de marque en 3D",
    "340% conversion uplift": "+340 % de conversion",
    "augmented reality": "Réalité augmentée",
    "arcspace — ar real estate": "ArcSpace — l'immobilier en réalité augmentée",
    "2.1m sessions in month 1": "2,1 M de sessions le premier mois",
    "3d configurator": "Configurateur 3D",
    "phantom — product visualizer": "Phantom — visualiseur de produits",
    "78% bundle size reduction": "−78 % sur le poids du paquet",
    "virtual try-on": "Essayage virtuel",
    "luminary — virtual fashion": "Luminary — la mode virtuelle",
    "60% return rate reduction": "−60 % de retours",
    "virtual environments": "Environnements virtuels",
    "forma — architectural walkthrough": "Forma — visite architecturale",
    "10 000 concurrent visitors": "10 000 visiteurs simultanés",
    "real-time render": "Rendu temps réel",
    "nexus — data center visualization": "Nexus — visualisation de centre de données",
    "sub-12ms frame time": "Moins de 12 ms par image",
    "full service details": "Le détail des prestations",
    "3d product visualization": "Visualisation de produits en 3D",
    "webgl rendering": "Rendu WebGL",
    "declarative 3d": "3D déclarative",
    "gpu programming": "Programmation GPU",
    "3d authoring": "Création 3D",
    "spatial computing": "Informatique spatiale",
    "photorealistic browser-native 3d that loads in under 2 seconds. we build interactive configurators with pbr materials, custom lighting rigs, and gltf asset pipelines.": "De la 3D photoréaliste, native au navigateur, chargée en moins de deux secondes. Nous construisons des configurateurs interactifs à matériaux PBR, avec éclairages sur mesure et chaînes d'assets glTF.",
    "asset audit & geometry retopo": "Audit des assets et retopologie",
    "pbr texture baking (4k)": "Cuisson des textures PBR (4K)",
    "platform api integration": "Intégration à l'API de la plateforme",
    "head of digital, phantom motors": "Directeur du numérique, Phantom Motors",
    "discovery": "Découverte",
    "one-time": "une fois",
    "per project": "par projet",
    "brand & asset audit": "Audit de marque et d'assets",
    "1 interactive 3d prototype": "Un prototype 3D interactif",
    "technical feasibility report": "Rapport de faisabilité technique",
    "performance benchmark": "Mesure des performances",
    "48h turnaround": "Rendu sous 48 heures",
    "unlimited revisions": "Retouches illimitées",
    "platform integration": "Intégration à votre plateforme",
    "3 months post-launch support": "Trois mois d'accompagnement après la mise en ligne",
    "retainer available": "en régie possible",
    "unlimited deliverables": "Livrables illimités",
    "custom shader r&d": "Recherche et développement de shaders sur mesure",
    "priority escalation": "Escalade prioritaire",
    "spatial?": "dans l'espace ?",
    "avg. frame time": "Temps moyen par image",
    "avg. render time": "Temps de rendu moyen",
    "book discovery sprint": "Réserver le sprint de découverte",
    "built with the best": "Bâti avec les meilleurs",
    "client satisfaction": "Satisfaction client",
    "client stories": "Histoires de clients",
    "currently taking new projects": "Actuellement en acceptation de nouveaux projets",
    "dedicated team embed for brands with ongoing 3d or spatial computing needs.": "Équipe dédiée intégrée pour les marques ayant des besoins continus en 3D ou en informatique spatiale.",
    "dedicated vertex team": "Équipe Vertex dédiée",
    "every engagement is scoped before we start. no surprise invoices.": "Chaque engagement est défini avant de commencer. Pas de factures surprises.",
    "everything in discovery": "Tout dans la découverte",
    "full-cycle 3d or ar production. from concept to production-ready web integration.": "Production 3D ou AR en cycle complet. Du concept à l'intégration web prête à la production.",
    "fully interactive 3d spaces — showrooms, galleries, architectural walkthroughs — supporting thousands of concurrent visitors in the browser.": "Espaces 3D entièrement interactifs — showrooms, galeries, visites architecturales — supportant des milliers de visiteurs simultanés dans le navigateur.",
    "global clients": "Clients mondiaux",
    "gpu-accelerated real-time 3d for interactive product configurators and live experiences.": "3D en temps réel accéléré par GPU pour des configurateurs de produits interactifs et des expériences en direct.",
    "immersive 3d environments for events, showrooms, and metaverse platforms.": "Environnements 3D immersifs pour des événements, des salles d'exposition et des plateformes de métavers.",
    "level-of-detail scripting": "Script de niveau de détail",
    "on-site workshops": "Ateliers sur site",
    "perfect for brands exploring 3d for the first time. two-day intensive audit and prototype.": "Idéal pour une marque qui aborde la 3D. Deux jours d'audit intensif et un prototype.",
    "photorealistic 3d models for e-commerce, marketing, and configurators. real-time or pre-rendered.": "Modèles 3D photoréalistes pour le commerce électronique, le marketing et les configurateurs. En temps réel ou pré-rendus.",
    "process steps": "Les étapes",
    "ready to go": "Prêt à partir",
    "real-time": "Temps réel",
    "real-time cg": "CG en temps réel",
    "real-time lighting setup": "Configuration d'éclairage en temps réel",
    "real-time metaverse": "Métavers en temps réel",
    "real-time rendering": "Rendu en temps réel",
    "see our work": "Voir nos réalisations",
    "sla with 99.9% uptime": "Engagement de service, 99,9 % de disponibilité",
    "start studio project": "Démarrer le projet studio",
    "talk to us": "Parlez-nous",
    "tell us about your project. we'll get back to you within 24 hours with a scope and timeline — no sales call required.": "Parlez-nous de votre projet. Nous revenons sous vingt-quatre heures avec un périmètre et un calendrier — sans rendez-vous commercial.",
    "the webar campaign they delivered was flawless on every device. our 48-hour launch saw 2.1 million sessions. truly unprecedented results.": "La campagne WebAR qu'ils ont livrée était impeccable sur chaque appareil. Notre lancement de 48 heures a vu 2,1 millions de sessions. Des résultats véritablement sans précédent.",
    "transparent pricing": "Tarification transparente",
    "up to 4 deliverables": "Jusqu'à 4 livrables",
    "vertex studio creates 3d product visualizations, ar experiences, and real-time environments for brands that want to stand out in the spatial era.": "Vertex Studio crée des visualisations de produits 3D, des expériences AR et des environnements en temps réel pour les marques qui souhaitent se démarquer dans l'ère spatiale.",
    "vertex turned our static product catalogue into a living, interactive 3d experience. conversion rate jumped 340% in the first quarter.": "Vertex a transformé notre catalogue de produits statique en une expérience 3D interactive et vivante. Le taux de conversion a augmenté de 340 % au premier trimestre.",
    "view full portfolio": "Voir le portfolio complet",
    "view our work": "Voir nos réalisations",
    "watch showreel": "Regarder le showreel",
    "we pick tools with proven gpu headroom, strong community backing, and real-world production track records.": "Nous choisissons des outils avec une marge GPU prouvée, un fort soutien communautaire et des antécédents de production dans le monde réel.",
    "we push webgl to its limits with custom glsl shaders, webassembly physics engines, and asset pipelines that target 60 fps on mid-range mobile devices.": "Nous poussons WebGL à ses limites avec des shaders GLSL personnalisés, des moteurs physiques WebAssembly et des pipelines d'actifs visant 60 FPS sur des appareils mobiles de milieu de gamme.",
    "webar and native ar experiences. try-before-you-buy, spatial computing, and brand activations.": "Expériences WebAR et AR natives. Essayer avant d'acheter, informatique spatiale et activations de marque.",
    "webar or configurator build": "WebAR ou construction de configurateur",
    "what clients say": "Ce que disent les clients",
    "what we build": "Ce que nous construisons",
    "working with vertex was like having a gpu wizard on the team. they optimised our 3d assets to 78% smaller with zero visual loss. remarkable.": "Travailler avec Vertex était comme avoir un magicien GPU dans l'équipe. Ils ont optimisé nos actifs 3D pour les réduire de 78 % sans aucune perte visuelle. Remarquable.",
  },
  es: {
    "avg. conversion uplift": "Aumento medio de conversión",
    "3d branding": "Identidad 3D",
    "valo — brand identity in 3d": "VALO — identidad de marca en 3D",
    "340% conversion uplift": "+340 % de conversión",
    "augmented reality": "Realidad aumentada",
    "arcspace — ar real estate": "ArcSpace — inmobiliaria en realidad aumentada",
    "2.1m sessions in month 1": "2,1 M de sesiones el primer mes",
    "3d configurator": "Configurador 3D",
    "phantom — product visualizer": "Phantom — visualizador de productos",
    "78% bundle size reduction": "−78 % en el peso del paquete",
    "virtual try-on": "Prueba virtual",
    "luminary — virtual fashion": "Luminary — moda virtual",
    "60% return rate reduction": "−60 % de devoluciones",
    "virtual environments": "Entornos virtuales",
    "forma — architectural walkthrough": "Forma — recorrido arquitectónico",
    "10 000 concurrent visitors": "10 000 visitantes simultáneos",
    "real-time render": "Renderizado en tiempo real",
    "nexus — data center visualization": "Nexus — visualización de centro de datos",
    "sub-12ms frame time": "Menos de 12 ms por fotograma",
    "full service details": "El detalle de los servicios",
    "3d product visualization": "Visualización de productos en 3D",
    "webgl rendering": "Renderizado WebGL",
    "declarative 3d": "3D declarativa",
    "gpu programming": "Programación GPU",
    "3d authoring": "Creación 3D",
    "spatial computing": "Computación espacial",
    "photorealistic browser-native 3d that loads in under 2 seconds. we build interactive configurators with pbr materials, custom lighting rigs, and gltf asset pipelines.": "3D fotorrealista, nativa del navegador, cargada en menos de dos segundos. Construimos configuradores interactivos con materiales PBR, iluminación a medida y cadenas de assets glTF.",
    "asset audit & geometry retopo": "Auditoría de assets y retopología",
    "pbr texture baking (4k)": "Horneado de texturas PBR (4K)",
    "platform api integration": "Integración con la API de la plataforma",
    "head of digital, phantom motors": "Director digital, Phantom Motors",
    "discovery": "Descubrimiento",
    "one-time": "pago único",
    "per project": "por proyecto",
    "brand & asset audit": "Auditoría de marca y assets",
    "1 interactive 3d prototype": "Un prototipo 3D interactivo",
    "technical feasibility report": "Informe de viabilidad técnica",
    "performance benchmark": "Medición de rendimiento",
    "48h turnaround": "Entrega en 48 horas",
    "unlimited revisions": "Revisiones ilimitadas",
    "platform integration": "Integración en su plataforma",
    "3 months post-launch support": "Tres meses de acompañamiento tras el lanzamiento",
    "retainer available": "en modalidad de retainer",
    "unlimited deliverables": "Entregables ilimitados",
    "custom shader r&d": "I+D de shaders a medida",
    "priority escalation": "Escalado prioritario",
    "spatial?": "al espacio?",
    "avg. frame time": "Tiempo medio por fotograma",
    "avg. render time": "Tiempo de renderizado medio",
    "book discovery sprint": "Reservar el sprint de descubrimiento",
    "built with the best": "Construido con los mejores",
    "client satisfaction": "Satisfacción del cliente",
    "client stories": "Historias de clientes",
    "currently taking new projects": "Actualmente aceptando nuevos proyectos",
    "dedicated team embed for brands with ongoing 3d or spatial computing needs.": "Equipo dedicado integrado para marcas con necesidades continuas de 3D o computación espacial.",
    "dedicated vertex team": "Equipo Vertex dedicado",
    "every engagement is scoped before we start. no surprise invoices.": "Cada compromiso se define antes de comenzar. Sin sorpresas en las facturas.",
    "everything in discovery": "Todo en Discovery",
    "full-cycle 3d or ar production. from concept to production-ready web integration.": "Producción 3D o AR de ciclo completo. Desde el concepto hasta la integración web lista para producción.",
    "fully interactive 3d spaces — showrooms, galleries, architectural walkthroughs — supporting thousands of concurrent visitors in the browser.": "Espacios 3D totalmente interactivos — salas de exposición, galerías, recorridos arquitectónicos — que admiten miles de visitantes concurrentes en el navegador.",
    "global clients": "Clientes globales",
    "gpu-accelerated real-time 3d for interactive product configurators and live experiences.": "3D en tiempo real acelerado por GPU para configuradores de productos interactivos y experiencias en vivo.",
    "immersive 3d environments for events, showrooms, and metaverse platforms.": "Entornos 3D inmersivos para eventos, salas de exposición y plataformas de metaverso.",
    "level-of-detail scripting": "Script de nivel de detalle",
    "on-site workshops": "Talleres in situ",
    "perfect for brands exploring 3d for the first time. two-day intensive audit and prototype.": "Ideal para una marca que se acerca al 3D por primera vez. Dos días de auditoría intensiva y un prototipo.",
    "photorealistic 3d models for e-commerce, marketing, and configurators. real-time or pre-rendered.": "Modelos 3D fotorrealistas para comercio electrónico, marketing y configuradores. En tiempo real o pre-renderizados.",
    "process steps": "Las etapas",
    "ready to go": "Listo para empezar",
    "real-time": "Tiempo real",
    "real-time cg": "CG en tiempo real",
    "real-time lighting setup": "Configuración de iluminación en tiempo real",
    "real-time metaverse": "Metaverso en tiempo real",
    "real-time rendering": "Renderizado en tiempo real",
    "see our work": "Ver nuestros trabajos",
    "sla with 99.9% uptime": "Acuerdo de servicio, 99,9 % de disponibilidad",
    "start studio project": "Iniciar proyecto de estudio",
    "talk to us": "Háblanos",
    "tell us about your project. we'll get back to you within 24 hours with a scope and timeline — no sales call required.": "Háblenos de su proyecto. Volvemos en veinticuatro horas con un alcance y un calendario, sin llamada comercial.",
    "the webar campaign they delivered was flawless on every device. our 48-hour launch saw 2.1 million sessions. truly unprecedented results.": "La campaña WebAR que entregaron fue impecable en cada dispositivo. Nuestro lanzamiento de 48 horas tuvo 2,1 millones de sesiones. Resultados verdaderamente sin precedentes.",
    "transparent pricing": "Precios transparentes",
    "up to 4 deliverables": "Hasta 4 entregables",
    "vertex studio creates 3d product visualizations, ar experiences, and real-time environments for brands that want to stand out in the spatial era.": "Vertex Studio crea visualizaciones de productos en 3D, experiencias de AR y entornos en tiempo real para marcas que quieren destacarse en la era espacial.",
    "vertex turned our static product catalogue into a living, interactive 3d experience. conversion rate jumped 340% in the first quarter.": "Vertex convirtió nuestro catálogo de productos estático en una experiencia 3D interactiva y viva. La tasa de conversión aumentó un 340 % en el primer trimestre.",
    "view full portfolio": "Ver portfolio completo",
    "view our work": "Ver nuestros trabajos",
    "watch showreel": "Ver el showreel",
    "we pick tools with proven gpu headroom, strong community backing, and real-world production track records.": "Elegimos herramientas con margen de GPU comprobado, fuerte respaldo de la comunidad y antecedentes de producción en el mundo real.",
    "we push webgl to its limits with custom glsl shaders, webassembly physics engines, and asset pipelines that target 60 fps on mid-range mobile devices.": "Llevamos WebGL al límite con shaders GLSL personalizados, motores de física WebAssembly y tuberías de activos que apuntan a 60 FPS en dispositivos móviles de gama media.",
    "webar and native ar experiences. try-before-you-buy, spatial computing, and brand activations.": "Experiencias WebAR y AR nativas. Prueba antes de comprar, computación espacial y activaciones de marca.",
    "webar or configurator build": "WebAR o construcción de configurador",
    "what clients say": "Lo que dicen los clientes",
    "what we build": "Lo que construimos",
    "working with vertex was like having a gpu wizard on the team. they optimised our 3d assets to 78% smaller with zero visual loss. remarkable.": "Trabajar con Vertex fue como tener un mago de GPU en el equipo. Optimizaron nuestros activos 3D para que fueran un 78 % más pequeños sin pérdida visual. Notable.",
  },
  de: {
    "avg. conversion uplift": "Durchschnittliche Conversion-Steigerung",
    "3d branding": "3D-Markenauftritt",
    "valo — brand identity in 3d": "VALO — Markenidentität in 3D",
    "340% conversion uplift": "+340 % Conversion",
    "augmented reality": "Erweiterte Realität",
    "arcspace — ar real estate": "ArcSpace — Immobilien in AR",
    "2.1m sessions in month 1": "2,1 Mio. Sitzungen im ersten Monat",
    "3d configurator": "3D-Konfigurator",
    "phantom — product visualizer": "Phantom — Produktvisualisierer",
    "78% bundle size reduction": "−78 % Bundle-Größe",
    "virtual try-on": "Virtuelle Anprobe",
    "luminary — virtual fashion": "Luminary — virtuelle Mode",
    "60% return rate reduction": "−60 % Retouren",
    "virtual environments": "Virtuelle Umgebungen",
    "forma — architectural walkthrough": "Forma — Architekturrundgang",
    "10 000 concurrent visitors": "10 000 gleichzeitige Besucher",
    "real-time render": "Echtzeit-Rendering",
    "nexus — data center visualization": "Nexus — Rechenzentrums-Visualisierung",
    "sub-12ms frame time": "Unter 12 ms pro Bild",
    "full service details": "Alle Leistungen im Detail",
    "3d product visualization": "3D-Produktvisualisierung",
    "webgl rendering": "WebGL-Rendering",
    "declarative 3d": "Deklaratives 3D",
    "gpu programming": "GPU-Programmierung",
    "3d authoring": "3D-Erstellung",
    "spatial computing": "Spatial Computing",
    "photorealistic browser-native 3d that loads in under 2 seconds. we build interactive configurators with pbr materials, custom lighting rigs, and gltf asset pipelines.": "Fotorealistisches 3D direkt im Browser, in weniger als zwei Sekunden geladen. Wir bauen interaktive Konfiguratoren mit PBR-Materialien, eigenen Lichtsetups und glTF-Asset-Pipelines.",
    "asset audit & geometry retopo": "Asset-Audit und Retopologie",
    "pbr texture baking (4k)": "PBR-Texture-Baking (4K)",
    "platform api integration": "Integration der Plattform-API",
    "head of digital, phantom motors": "Leiter Digital, Phantom Motors",
    "discovery": "Erkundung",
    "one-time": "einmalig",
    "per project": "pro Projekt",
    "brand & asset audit": "Marken- und Asset-Audit",
    "1 interactive 3d prototype": "Ein interaktiver 3D-Prototyp",
    "technical feasibility report": "Bericht zur technischen Machbarkeit",
    "performance benchmark": "Performance-Messung",
    "48h turnaround": "Lieferung in 48 Stunden",
    "unlimited revisions": "Unbegrenzte Korrekturschleifen",
    "platform integration": "Integration in Ihre Plattform",
    "3 months post-launch support": "Drei Monate Begleitung nach dem Start",
    "retainer available": "auf Abrufbasis möglich",
    "unlimited deliverables": "Unbegrenzte Lieferungen",
    "custom shader r&d": "Individuelle Shader-Entwicklung",
    "priority escalation": "Vorrangige Eskalation",
    "spatial?": "in den Raum?",
    "avg. frame time": "Durchschnittliche Bildrate",
    "avg. render time": "Durchschnittliche Renderzeit",
    "book discovery sprint": "Discovery-Sprint buchen",
    "built with the best": "Mit den Besten gebaut",
    "client satisfaction": "Kundenzufriedenheit",
    "client stories": "Kundenberichte",
    "currently taking new projects": "Derzeit neue Projekte annehmen",
    "dedicated team embed for brands with ongoing 3d or spatial computing needs.": "Dediziertes Team für Marken mit laufendem Bedarf an 3D- oder räumlicher Computertechnik.",
    "dedicated vertex team": "Dediziertes Vertex-Team",
    "every engagement is scoped before we start. no surprise invoices.": "Jedes Engagement wird vor Beginn festgelegt. Keine Überraschungsrechnungen.",
    "everything in discovery": "Alles in Discovery",
    "full-cycle 3d or ar production. from concept to production-ready web integration.": "Vollständige 3D- oder AR-Produktion. Vom Konzept bis zur produktionsbereiten Web-Integration.",
    "fully interactive 3d spaces — showrooms, galleries, architectural walkthroughs — supporting thousands of concurrent visitors in the browser.": "Vollständig interaktive 3D-Räume — Showrooms, Galerien, architektonische Rundgänge — die Tausende von gleichzeitigen Besuchern im Browser unterstützen.",
    "global clients": "Globale Kunden",
    "gpu-accelerated real-time 3d for interactive product configurators and live experiences.": "GPU-beschleunigtes Echtzeit-3D für interaktive Produktkonfiguratoren und Live-Erlebnisse.",
    "immersive 3d environments for events, showrooms, and metaverse platforms.": "Immersive 3D-Umgebungen für Veranstaltungen, Showrooms und Metaverse-Plattformen.",
    "level-of-detail scripting": "Level-of-Detail-Scripting",
    "on-site workshops": "Workshops vor Ort",
    "perfect for brands exploring 3d for the first time. two-day intensive audit and prototype.": "Ideal für Marken, die 3D zum ersten Mal angehen. Zwei Tage intensives Audit und ein Prototyp.",
    "photorealistic 3d models for e-commerce, marketing, and configurators. real-time or pre-rendered.": "Fotorealistische 3D-Modelle für E-Commerce, Marketing und Konfiguratoren. In Echtzeit oder vorgerendert.",
    "process steps": "Die Schritte",
    "ready to go": "Bereit zu gehen",
    "real-time": "Echtzeit",
    "real-time cg": "Echtzeit-CG",
    "real-time lighting setup": "Echtzeit-Beleuchtungseinrichtung",
    "real-time metaverse": "Echtzeit-Metaversum",
    "real-time rendering": "Echtzeit-Rendering",
    "see our work": "Unsere Arbeiten ansehen",
    "sla with 99.9% uptime": "Service-Level mit 99,9 % Verfügbarkeit",
    "start studio project": "Studio-Projekt starten",
    "talk to us": "Sprich mit uns",
    "tell us about your project. we'll get back to you within 24 hours with a scope and timeline — no sales call required.": "Erzählen Sie uns von Ihrem Projekt. Wir melden uns binnen vierundzwanzig Stunden mit Umfang und Zeitplan — ohne Verkaufsgespräch.",
    "the webar campaign they delivered was flawless on every device. our 48-hour launch saw 2.1 million sessions. truly unprecedented results.": "Die WebAR-Kampagne, die sie geliefert haben, war auf jedem Gerät fehlerfrei. Unser 48-Stunden-Start verzeichnete 2,1 Millionen Sitzungen. Wirklich beispiellose Ergebnisse.",
    "transparent pricing": "Transparente Preisgestaltung",
    "up to 4 deliverables": "Bis zu 4 Liefergegenstände",
    "vertex studio creates 3d product visualizations, ar experiences, and real-time environments for brands that want to stand out in the spatial era.": "Vertex Studio erstellt 3D-Produktvisualisierungen, AR-Erlebnisse und Echtzeitumgebungen für Marken, die in der räumlichen Ära auffallen möchten.",
    "vertex turned our static product catalogue into a living, interactive 3d experience. conversion rate jumped 340% in the first quarter.": "Vertex verwandelte unseren statischen Produktkatalog in ein lebendiges, interaktives 3D-Erlebnis. Die Konversionsrate stieg im ersten Quartal um 340 %.",
    "view full portfolio": "Vollständiges Portfolio anzeigen",
    "view our work": "Unsere Arbeiten ansehen",
    "watch showreel": "Showreel ansehen",
    "we pick tools with proven gpu headroom, strong community backing, and real-world production track records.": "Wir wählen Werkzeuge mit nachgewiesenem GPU-Spielraum, starker Unterstützung durch die Community und nachweislichen Produktionsaufzeichnungen aus.",
    "we push webgl to its limits with custom glsl shaders, webassembly physics engines, and asset pipelines that target 60 fps on mid-range mobile devices.": "Wir treiben WebGL an seine Grenzen mit benutzerdefinierten GLSL-Shadern, WebAssembly-Physik-Engines und Asset-Pipelines, die 60 FPS auf Mittelklasse-Mobilgeräten anstreben.",
    "webar and native ar experiences. try-before-you-buy, spatial computing, and brand activations.": "WebAR- und native AR-Erlebnisse. Ausprobieren vor dem Kauf, räumliches Rechnen und Markenaktivierungen.",
    "webar or configurator build": "WebAR oder Konfigurator-Bau",
    "what clients say": "Was Kunden sagen",
    "what we build": "Was wir bauen",
    "working with vertex was like having a gpu wizard on the team. they optimised our 3d assets to 78% smaller with zero visual loss. remarkable.": "Die Zusammenarbeit mit Vertex war wie einen GPU-Zauberer im Team zu haben. Sie optimierten unsere 3D-Assets auf 78 % kleiner bei null visuellen Verlusten. Bemerkenswert.",
  },
  pt: {
    "avg. conversion uplift": "Ganho médio de conversão",
    "3d branding": "Identidade 3D",
    "valo — brand identity in 3d": "VALO — identidade de marca em 3D",
    "340% conversion uplift": "+340 % de conversão",
    "augmented reality": "Realidade aumentada",
    "arcspace — ar real estate": "ArcSpace — imobiliário em realidade aumentada",
    "2.1m sessions in month 1": "2,1 M de sessões no primeiro mês",
    "3d configurator": "Configurador 3D",
    "phantom — product visualizer": "Phantom — visualizador de produtos",
    "78% bundle size reduction": "−78 % no peso do pacote",
    "virtual try-on": "Prova virtual",
    "luminary — virtual fashion": "Luminary — moda virtual",
    "60% return rate reduction": "−60 % de devoluções",
    "virtual environments": "Ambientes virtuais",
    "forma — architectural walkthrough": "Forma — visita arquitetónica",
    "10 000 concurrent visitors": "10 000 visitantes em simultâneo",
    "real-time render": "Renderização em tempo real",
    "nexus — data center visualization": "Nexus — visualização de centro de dados",
    "sub-12ms frame time": "Menos de 12 ms por imagem",
    "full service details": "O detalhe dos serviços",
    "3d product visualization": "Visualização de produtos em 3D",
    "webgl rendering": "Renderização WebGL",
    "declarative 3d": "3D declarativa",
    "gpu programming": "Programação GPU",
    "3d authoring": "Criação 3D",
    "spatial computing": "Computação espacial",
    "photorealistic browser-native 3d that loads in under 2 seconds. we build interactive configurators with pbr materials, custom lighting rigs, and gltf asset pipelines.": "3D fotorrealista, nativa do navegador, carregada em menos de dois segundos. Construímos configuradores interativos com materiais PBR, iluminação à medida e cadeias de assets glTF.",
    "asset audit & geometry retopo": "Auditoria de assets e retopologia",
    "pbr texture baking (4k)": "Cozedura de texturas PBR (4K)",
    "platform api integration": "Integração com a API da plataforma",
    "head of digital, phantom motors": "Diretor digital, Phantom Motors",
    "discovery": "Descoberta",
    "one-time": "pagamento único",
    "per project": "por projeto",
    "brand & asset audit": "Auditoria de marca e assets",
    "1 interactive 3d prototype": "Um protótipo 3D interativo",
    "technical feasibility report": "Relatório de viabilidade técnica",
    "performance benchmark": "Medição de desempenho",
    "48h turnaround": "Entrega em 48 horas",
    "unlimited revisions": "Revisões ilimitadas",
    "platform integration": "Integração na sua plataforma",
    "3 months post-launch support": "Três meses de acompanhamento após o lançamento",
    "retainer available": "em regime de avença",
    "unlimited deliverables": "Entregáveis ilimitados",
    "custom shader r&d": "Investigação de shaders à medida",
    "priority escalation": "Escalonamento prioritário",
    "spatial?": "para o espaço?",
    "avg. frame time": "Tempo médio por quadro",
    "avg. render time": "Tempo médio de renderização",
    "book discovery sprint": "Reservar o sprint de descoberta",
    "built with the best": "Construído com os melhores",
    "client satisfaction": "Satisfação do cliente",
    "client stories": "Histórias de clientes",
    "currently taking new projects": "Atualmente aceitando novos projetos",
    "dedicated team embed for brands with ongoing 3d or spatial computing needs.": "Equipe dedicada integrada para marcas com necessidades contínuas de 3D ou computação espacial.",
    "dedicated vertex team": "Equipe Vertex dedicada",
    "every engagement is scoped before we start. no surprise invoices.": "Cada compromisso é definido antes de começarmos. Sem faturas surpresa.",
    "everything in discovery": "Tudo em Discovery",
    "full-cycle 3d or ar production. from concept to production-ready web integration.": "Produção 3D ou AR em ciclo completo. Do conceito à integração web pronta para produção.",
    "fully interactive 3d spaces — showrooms, galleries, architectural walkthroughs — supporting thousands of concurrent visitors in the browser.": "Espaços 3D totalmente interativos — salas de exposições, galerias, passeios arquitetónicos — suportando milhares de visitantes simultâneos no navegador.",
    "global clients": "Clientes globais",
    "gpu-accelerated real-time 3d for interactive product configurators and live experiences.": "3D em tempo real acelerado por GPU para configuradores de produtos interativos e experiências ao vivo.",
    "immersive 3d environments for events, showrooms, and metaverse platforms.": "Ambientes 3D imersivos para eventos, salas de exposições e plataformas de metaverso.",
    "level-of-detail scripting": "Script de nível de detalhe",
    "on-site workshops": "Workshops no local",
    "perfect for brands exploring 3d for the first time. two-day intensive audit and prototype.": "Ideal para uma marca que aborda o 3D pela primeira vez. Dois dias de auditoria intensiva e um protótipo.",
    "photorealistic 3d models for e-commerce, marketing, and configurators. real-time or pre-rendered.": "Modelos 3D fotorrealistas para e-commerce, marketing e configuradores. Em tempo real ou pré-renderizados.",
    "process steps": "As etapas",
    "ready to go": "Pronto para começar",
    "real-time": "Tempo real",
    "real-time cg": "CG em tempo real",
    "real-time lighting setup": "Configuração de iluminação em tempo real",
    "real-time metaverse": "Metaverso em tempo real",
    "real-time rendering": "Renderização em tempo real",
    "see our work": "Ver os nossos trabalhos",
    "sla with 99.9% uptime": "Acordo de serviço, 99,9 % de disponibilidade",
    "start studio project": "Iniciar projeto de estúdio",
    "talk to us": "Fale connosco",
    "tell us about your project. we'll get back to you within 24 hours with a scope and timeline — no sales call required.": "Fale-nos do seu projeto. Voltamos em vinte e quatro horas com um âmbito e um calendário — sem chamada comercial.",
    "the webar campaign they delivered was flawless on every device. our 48-hour launch saw 2.1 million sessions. truly unprecedented results.": "A campanha WebAR que eles entregaram foi impecável em todos os dispositivos. O nosso lançamento de 48 horas teve 2,1 milhões de sessões. Resultados verdadeiramente sem precedentes.",
    "transparent pricing": "Preços transparentes",
    "up to 4 deliverables": "Até 4 entregáveis",
    "vertex studio creates 3d product visualizations, ar experiences, and real-time environments for brands that want to stand out in the spatial era.": "Vertex Studio cria visualizações de produtos em 3D, experiências de AR e ambientes em tempo real para marcas que desejam se destacar na era espacial.",
    "vertex turned our static product catalogue into a living, interactive 3d experience. conversion rate jumped 340% in the first quarter.": "A Vertex transformou o nosso catálogo de produtos estático numa experiência 3D interativa e viva. A taxa de conversão aumentou 340% no primeiro trimestre.",
    "view full portfolio": "Ver portfólio completo",
    "view our work": "Ver os nossos trabalhos",
    "watch showreel": "Assistir ao showreel",
    "we pick tools with proven gpu headroom, strong community backing, and real-world production track records.": "Escolhemos ferramentas com margem de GPU comprovada, forte apoio da comunidade e históricos de produção no mundo real.",
    "we push webgl to its limits with custom glsl shaders, webassembly physics engines, and asset pipelines that target 60 fps on mid-range mobile devices.": "Levamos o WebGL ao limite com shaders GLSL personalizados, motores de física WebAssembly e pipelines de ativos que visam 60 FPS em dispositivos móveis de gama média.",
    "webar and native ar experiences. try-before-you-buy, spatial computing, and brand activations.": "Experiências WebAR e AR nativas. Experimente antes de comprar, computação espacial e ativações de marca.",
    "webar or configurator build": "WebAR ou construção de configurador",
    "what clients say": "O que os clientes dizem",
    "what we build": "O que construímos",
    "working with vertex was like having a gpu wizard on the team. they optimised our 3d assets to 78% smaller with zero visual loss. remarkable.": "Trabalhar com a Vertex foi como ter um mago de GPU na equipe. Eles otimizaram os nossos ativos 3D para serem 78% menores sem perda visual. Notável.",
  },
};
