/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"a watch does not simply tell the time; it tells a story of patience, precision, and the pursuit of perfection.\"": "« Une montre ne donne pas seulement l'heure : elle raconte la patience, la précision et la recherche du juste. »",
    "\"time is the most valuable luxury of all. we simply provide the vessel to measure it.\"": "« Le temps est le plus précieux des luxes. Nous ne faisons que fournir l'écrin pour le mesurer. »",
    "100% of our movements and casings are crafted in geneva.": "100 % de nos mouvements et boîtiers sont fabriqués à Genève.",
    "28 years of legacy": "28 ans d'héritage",
    "a behind-the-scenes look at reviving one of leo aris's early lunar complications.": "Un aperçu des coulisses de la renaissance de l'une des premières complications lunaires de Leo Aris.",
    "all series": "Toutes les séries",
    "an exploration of the technique of hand-polishing sharp edges in high watchmaking.": "Une exploration de la technique de polissage à la main des bords vifs dans la haute horlogerie.",
    "born in": "Né en",
    "browse all": "Tout parcourir",
    "brushed titanium case with a 72-hour power reserve and sapphire crystal.": "Boîtier en titane brossé avec une réserve de marche de 72 heures et un cristal saphir.",
    "calibrated to +/- 1 second per day, surpassing traditional cosc standards.": "Calibré à +/- 1 seconde par jour, dépassant les normes COSC traditionnelles.",
    "client care": "Service client",
    "constant refinement of the classic tourbillon complication.": "Affinement constant de la complication tourbillon classique.",
    "flying tourbillon with manual winding, hand-beveled titanium cage, and power reserve indicator.": "Tourbillon volant avec remontage manuel, cage en titane à biseau manuel et indicateur de réserve de marche.",
    "grade 5 titanium and scratch-proof sapphire with multi-layer anti-reflective coating.": "Titane de grade 5 et saphir résistant aux rayures avec un revêtement anti-reflet multicouche.",
    "how our watches survive the decompression phase of professional saturation diving.": "Comment nos montres survivent à la phase de décompression de la plongée professionnelle en saturation.",
    "in-house calibre": "Calibre maison",
    "our atelier": "Notre atelier",
    "our legacy": "Notre héritage",
    "over 200 hours of precision assembly by master horologists in our swiss atelier.": "Plus de 200 heures d'assemblage de précision par des horlogers maîtres dans notre atelier suisse.",
    "professional diver's watch water resistant to 1000m with helium escape valve.": "Montre de plongée professionnelle étanche jusqu'à 1000m avec valve d'échappement pour l'hélium.",
    "since 1924": "Depuis 1924",
    "the art of anglage: hand-beveling": "L'Art de l'Anglage : Chanfreinage à la Main",
    "the flying tourbillon": "Le Tourbillon Volant",
    "the founding father": "Le Père Fondateur",
    "timepiece of interest": "Montre d'intérêt",
  },
  es: {
    "\"a watch does not simply tell the time; it tells a story of patience, precision, and the pursuit of perfection.\"": "«Un reloj no solo da la hora: cuenta la paciencia, la precisión y la búsqueda de lo justo.»",
    "\"time is the most valuable luxury of all. we simply provide the vessel to measure it.\"": "«El tiempo es el más valioso de los lujos. Nosotros solo damos el estuche para medirlo.»",
    "100% of our movements and casings are crafted in geneva.": "El 100 % de nuestros movimientos y cajas se fabrican en Ginebra.",
    "28 years of legacy": "28 años de legado",
    "a behind-the-scenes look at reviving one of leo aris's early lunar complications.": "Una mirada entre bastidores a la revitalización de una de las primeras complicaciones lunares de Leo Aris.",
    "all series": "Todas las series",
    "an exploration of the technique of hand-polishing sharp edges in high watchmaking.": "Una exploración de la técnica de pulido a mano de bordes afilados en la alta relojería.",
    "born in": "Nacido en",
    "browse all": "Ver todo",
    "brushed titanium case with a 72-hour power reserve and sapphire crystal.": "Caja de titanio cepillado con una reserva de marcha de 72 horas y cristal de zafiro.",
    "calibrated to +/- 1 second per day, surpassing traditional cosc standards.": "Calibrado a +/- 1 segundo por día, superando los estándares COSC tradicionales.",
    "client care": "Atención al cliente",
    "constant refinement of the classic tourbillon complication.": "Refinamiento constante de la complicación de tourbillon clásica.",
    "flying tourbillon with manual winding, hand-beveled titanium cage, and power reserve indicator.": "Tourbillon volante con cuerda manual, jaula de titanio biselada a mano e indicador de reserva de marcha.",
    "grade 5 titanium and scratch-proof sapphire with multi-layer anti-reflective coating.": "Titanio de grado 5 y zafiro a prueba de rayones con recubrimiento antirreflejo multicapa.",
    "how our watches survive the decompression phase of professional saturation diving.": "Cómo nuestros relojes sobreviven a la fase de descompresión del buceo profesional en saturación.",
    "in-house calibre": "Calibre interno",
    "our atelier": "Nuestro taller",
    "our legacy": "Nuestro legado",
    "over 200 hours of precision assembly by master horologists in our swiss atelier.": "Más de 200 horas de ensamblaje de precisión por maestros relojeros en nuestro taller suizo.",
    "professional diver's watch water resistant to 1000m with helium escape valve.": "Reloj de buceo profesional resistente al agua hasta 1000m con válvula de escape de helio.",
    "since 1924": "Desde 1924",
    "the art of anglage: hand-beveling": "El Arte del Anglage: Chaflán a Mano",
    "the flying tourbillon": "El Tourbillon Volante",
    "the founding father": "El Padre Fundador",
    "timepiece of interest": "Reloj de interés",
  },
  de: {
    "\"a watch does not simply tell the time; it tells a story of patience, precision, and the pursuit of perfection.\"": "„Eine Uhr sagt nicht bloß die Zeit; sie erzählt von Geduld, Präzision und dem Streben nach Vollkommenheit.“",
    "\"time is the most valuable luxury of all. we simply provide the vessel to measure it.\"": "„Zeit ist der wertvollste Luxus. Wir liefern nur das Gefäß, sie zu messen.“",
    "100% of our movements and casings are crafted in geneva.": "100 % unserer Uhrwerke und Gehäuse werden in Genf gefertigt.",
    "28 years of legacy": "28 Jahre Erbe",
    "a behind-the-scenes look at reviving one of leo aris's early lunar complications.": "Ein Blick hinter die Kulissen der Wiederbelebung einer der frühen Mondkomplikationen von Leo Aris.",
    "all series": "Alle Serien",
    "an exploration of the technique of hand-polishing sharp edges in high watchmaking.": "Eine Erkundung der Technik des Handpolierens von scharfen Kanten in der hochwertigen Uhrenmacherei.",
    "born in": "Geboren in",
    "browse all": "Alles ansehen",
    "brushed titanium case with a 72-hour power reserve and sapphire crystal.": "Gehäuse aus gebürstetem Titan mit einer Gangreserve von 72 Stunden und Saphirglas.",
    "calibrated to +/- 1 second per day, surpassing traditional cosc standards.": "Kalibriert auf +/- 1 Sekunde pro Tag, übertrifft die traditionellen COSC-Standards.",
    "client care": "Kundenbetreuung",
    "constant refinement of the classic tourbillon complication.": "Ständige Verfeinerung der klassischen Tourbillon-Komplikation.",
    "flying tourbillon with manual winding, hand-beveled titanium cage, and power reserve indicator.": "Fliegendes Tourbillon mit Handaufzug, handgefeiltem Titan-Gehäuse und Gangreserveanzeige.",
    "grade 5 titanium and scratch-proof sapphire with multi-layer anti-reflective coating.": "Titan Grade 5 und kratzfester Saphir mit mehrschichtiger Antireflexbeschichtung.",
    "how our watches survive the decompression phase of professional saturation diving.": "Wie unsere Uhren die Dekompressionsphase des professionellen Sättigungstauchens überstehen.",
    "in-house calibre": "In-House-Kaliber",
    "our atelier": "Unser Atelier",
    "our legacy": "Unser Erbe",
    "over 200 hours of precision assembly by master horologists in our swiss atelier.": "Über 200 Stunden präziser Montage durch Meisteruhrmacher in unserem Schweizer Atelier.",
    "professional diver's watch water resistant to 1000m with helium escape valve.": "Professionelle Taucheruhr wasserdicht bis 1000m mit Heliumauslassventil.",
    "since 1924": "Seit 1924",
    "the art of anglage: hand-beveling": "Die Kunst des Anglage: Hand-Fasen",
    "the flying tourbillon": "Das Fliegende Tourbillon",
    "the founding father": "Der Gründungsvater",
    "timepiece of interest": "Uhr von Interesse",
  },
  pt: {
    "\"a watch does not simply tell the time; it tells a story of patience, precision, and the pursuit of perfection.\"": "«Um relógio não dá apenas as horas: conta a paciência, a precisão e a busca do justo.»",
    "\"time is the most valuable luxury of all. we simply provide the vessel to measure it.\"": "«O tempo é o mais precioso dos luxos. Nós apenas fornecemos o estojo para o medir.»",
    "100% of our movements and casings are crafted in geneva.": "100 % dos nossos movimentos e caixas são fabricados em Genebra.",
    "28 years of legacy": "28 anos de legado",
    "a behind-the-scenes look at reviving one of leo aris's early lunar complications.": "Um olhar nos bastidores sobre a revitalização de uma das primeiras complicações lunares de Leo Aris.",
    "all series": "Todas as séries",
    "an exploration of the technique of hand-polishing sharp edges in high watchmaking.": "Uma exploração da técnica de polimento manual de bordas afiadas na alta relojoaria.",
    "born in": "Nascido em",
    "browse all": "Ver tudo",
    "brushed titanium case with a 72-hour power reserve and sapphire crystal.": "Caixa em titânio escovado com reserva de marcha de 72 horas e cristal de safira.",
    "calibrated to +/- 1 second per day, surpassing traditional cosc standards.": "Calibrado a +/- 1 segundo por dia, superando os padrões COSC tradicionais.",
    "client care": "Atendimento ao cliente",
    "constant refinement of the classic tourbillon complication.": "Aperfeiçoamento constante da complicação clássica do tourbillon.",
    "flying tourbillon with manual winding, hand-beveled titanium cage, and power reserve indicator.": "Tourbillon volante com corda manual, gaiola de titânio chanfrada à mão e indicador de reserva de marcha.",
    "grade 5 titanium and scratch-proof sapphire with multi-layer anti-reflective coating.": "Titânio de grau 5 e safira à prova de riscos com revestimento antirreflexo de múltiplas camadas.",
    "how our watches survive the decompression phase of professional saturation diving.": "Como os nossos relógios sobrevivem à fase de descompressão do mergulho profissional em saturação.",
    "in-house calibre": "Calibre interno",
    "our atelier": "O nosso atelier",
    "our legacy": "O nosso legado",
    "over 200 hours of precision assembly by master horologists in our swiss atelier.": "Mais de 200 horas de montagem de precisão por mestres relojoeiros no nosso ateliê suíço.",
    "professional diver's watch water resistant to 1000m with helium escape valve.": "Relógio de mergulho profissional à prova d'água até 1000m com válvula de escape de hélio.",
    "since 1924": "Desde 1924",
    "the art of anglage: hand-beveling": "A Arte do Anglage: Chanfro à Mão",
    "the flying tourbillon": "O Tourbillon Voador",
    "the founding father": "O Pai Fundador",
    "timepiece of interest": "Relógio de interesse",
  },
};
