/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "four": "Quatre",
    "chapters.": "chapitres.",
    "expedition storytelling": "Récits d'expédition",
    "expeditions led": "Expéditions menées",
    "countries traversed": "Pays traversés",
    "safety record": "Sans incident",
    "max group size": "Taille maximale du groupe",
    "upcoming": "Prochaines",
    "18 days": "18 jours",
    "12 days": "12 jours",
    "10 days": "10 jours",
    "expert": "Confirmé",
    "moderate": "Modéré",
    "challenging": "Exigeant",
    "arctic norway": "Norvège arctique",
    "namibia": "Namibie",
    "karakoram traverse": "Traversée du Karakoram",
    "svalbard polar": "Svalbard polaire",
    "namib desert crossing": "Traversée du désert du Namib",
    "\"the patagonia expedition changed my life. not hyperbole — i genuinely made different career and family decisions in the weeks after. meridian creates that kind of space.\"": "« L'expédition en Patagonie a changé ma vie. Ce n'est pas une figure de style : j'ai pris, dans les semaines qui ont suivi, d'autres décisions de carrière et de famille. Ils créent cet espace-là. »",
    "\"i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.\"": "« J'ai fait onze expéditions avec différentes agences. C'est la seule où le guide sait quand parler et quand se taire. C'est rare, et ça n'a pas de prix. »",
    "\"my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.\"": "« Mon fils et moi avons fait la côte du Groenland. Il a quatorze ans. Il en parle encore. Je ne trouverai jamais meilleur emploi de deux semaines. »",
    "all expeditions": "Toutes les expéditions",
    "answer the": "Répondre à",
    "applications for 2026 expeditions are now open. limited to 8 per journey.": "Les candidatures pour les expéditions 2026 sont ouvertes. Huit places par voyage.",
    "cross the world's most dramatic mountain range through ancient silk road passes.": "Traversez la chaîne de montagnes la plus spectaculaire du monde à travers les anciens passages de la Route de la Soie.",
    "every expedition begins months before departure — with research, conditioning, and route reconnaissance.": "Chaque expédition commence des mois avant le départ : recherche, préparation physique, reconnaissance de l'itinéraire.",
    "every journey is documented. photography, field notes, and gps data become your permanent record.": "Chaque voyage est consigné. Photographies, carnets de terrain et traces GPS deviennent votre archive.",
    "expedition storytelling and guided wilderness journeys since 2017.": "Récits d'expédition et voyages guidés en pleine nature depuis 2017.",
    "expeditions": "Expéditions",
    "expeditions.": "Expéditions.",
    "gear": "Équipement",
    "gear list": "Liste de matériel",
    "glacier treks and polar wildlife encounters at 78°n latitude.": "Randonnées glaciaires et rencontres avec la faune polaire à 78°N de latitude.",
    "guided expeditions to the world's most remote landscapes. small teams, real challenge, permanent transformation.": "Expéditions guidées vers les paysages les plus reculés du monde. Petites équipes, vrai défi, transformation permanente.",
    "i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.": "J'ai fait 11 expéditions avec diverses entreprises. Meridian est la seule où le guide sait quand parler et quand ne pas parler. C'est rare et inestimable.",
    "in their": "Selon eux",
    "into the unknown.": "VERS L'INCONNU.",
    "join expedition": "Rejoindre l'Expédition",
    "my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.": "Mon fils et moi avons fait la route côtière du Groenland. Il a 14 ans. Il en parle encore. Je ne trouverai jamais un meilleur investissement de deux semaines.",
    "navigate the world's oldest desert, from deadvlei to the skeleton coast.": "Naviguez dans le plus ancien désert du monde, de Deadvlei à la Côte des Squelettes.",
    "plan": "Planifier",
    "small teams of 4-8, moving through terrain with purpose. camps built for recovery, not luxury.": "De petites équipes de quatre à huit, qui avancent avec un but. Des camps faits pour récupérer, pas pour le confort.",
    "the approach": "L'approche",
    "the field": "Le terrain",
    "the objective is never the top. it's the transformation that happens on the way.": "L'objectif n'est jamais le sommet. C'est ce qui change en chemin.",
    "the summit": "Le sommet",
    "view expedition": "Voir l'Expédition",
  },
  es: {
    "four": "Cuatro",
    "chapters.": "capítulos.",
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "expedition storytelling": "Relatos de expedición",
    "expeditions led": "Expediciones dirigidas",
    "countries traversed": "Países atravesados",
    "safety record": "Sin incidentes",
    "max group size": "Tamaño máximo del grupo",
    "upcoming": "Próximas",
    "18 days": "18 días",
    "12 days": "12 días",
    "10 days": "10 días",
    "expert": "Experto",
    "moderate": "Moderado",
    "challenging": "Exigente",
    "arctic norway": "Noruega ártica",
    "namibia": "Namibia",
    "karakoram traverse": "Travesía del Karakórum",
    "svalbard polar": "Svalbard polar",
    "namib desert crossing": "Travesía del desierto del Namib",
    "\"the patagonia expedition changed my life. not hyperbole — i genuinely made different career and family decisions in the weeks after. meridian creates that kind of space.\"": "«La expedición a la Patagonia cambió mi vida. No es una figura retórica: en las semanas siguientes tomé otras decisiones de carrera y de familia. Ellos crean ese espacio.»",
    "\"i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.\"": "«He hecho once expediciones con distintas agencias. Es la única donde el guía sabe cuándo hablar y cuándo callar. Es raro y no tiene precio.»",
    "\"my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.\"": "«Mi hijo y yo hicimos la costa de Groenlandia. Tiene catorce años. Todavía habla de ello. Nunca encontraré mejor uso para dos semanas.»",
    "all expeditions": "Todas las expediciones",
    "answer the": "Responder a",
    "applications for 2026 expeditions are now open. limited to 8 per journey.": "Las candidaturas para las expediciones de 2026 están abiertas. Ocho plazas por viaje.",
    "cross the world's most dramatic mountain range through ancient silk road passes.": "Cruza la cadena montañosa más dramática del mundo a través de antiguos pasos de la Ruta de la Seda.",
    "every expedition begins months before departure — with research, conditioning, and route reconnaissance.": "Cada expedición empieza meses antes de la salida: investigación, preparación física y reconocimiento del itinerario.",
    "every journey is documented. photography, field notes, and gps data become your permanent record.": "Cada viaje queda documentado. Fotografías, cuadernos de campo y trazas GPS se convierten en su archivo.",
    "expedition storytelling and guided wilderness journeys since 2017.": "Relatos de expedición y viajes guiados en plena naturaleza desde 2017.",
    "expeditions": "Expediciones",
    "expeditions.": "Expediciones.",
    "gear": "Equipo",
    "gear list": "Lista de equipo",
    "glacier treks and polar wildlife encounters at 78°n latitude.": "Caminatas por glaciares y encuentros con la fauna polar a 78°N de latitud.",
    "guided expeditions to the world's most remote landscapes. small teams, real challenge, permanent transformation.": "Expediciones guiadas a los paisajes más remotos del mundo. Equipos pequeños, verdadero desafío, transformación permanente.",
    "i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.": "He hecho 11 expediciones con varias empresas. Meridian es la única donde el guía sabe cuándo hablar y cuándo no. Eso es raro y invaluable.",
    "in their": "Según ellos",
    "into the unknown.": "HACIA LO DESCONOCIDO.",
    "join expedition": "Únete a la Expedición",
    "my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.": "Mi hijo y yo hicimos la ruta costera de Groenlandia. Él tiene 14 años. Aún habla de ello. Nunca encontraré una mejor inversión de dos semanas.",
    "navigate the world's oldest desert, from deadvlei to the skeleton coast.": "Navega por el desierto más antiguo del mundo, desde Deadvlei hasta la Costa de los Esqueletos.",
    "plan": "Planificar",
    "small teams of 4-8, moving through terrain with purpose. camps built for recovery, not luxury.": "Equipos pequeños de cuatro a ocho, que avanzan con un propósito. Campamentos hechos para recuperarse, no para el lujo.",
    "the approach": "El enfoque",
    "the field": "El terreno",
    "the objective is never the top. it's the transformation that happens on the way.": "El objetivo nunca es la cima. Es lo que cambia por el camino.",
    "the summit": "La cumbre",
    "view expedition": "Ver Expedición",
  },
  de: {
    "four": "Vier",
    "chapters.": "Kapitel.",
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "expedition storytelling": "Expeditionsgeschichten",
    "expeditions led": "Geleitete Expeditionen",
    "countries traversed": "Durchquerte Länder",
    "safety record": "Ohne Zwischenfall",
    "max group size": "Maximale Gruppengröße",
    "upcoming": "Kommende",
    "18 days": "18 Tage",
    "12 days": "12 Tage",
    "10 days": "10 Tage",
    "expert": "Erfahren",
    "moderate": "Mittel",
    "challenging": "Anspruchsvoll",
    "arctic norway": "Arktisches Norwegen",
    "namibia": "Namibia",
    "karakoram traverse": "Karakorum-Durchquerung",
    "svalbard polar": "Svalbard polar",
    "namib desert crossing": "Durchquerung der Namib",
    "\"the patagonia expedition changed my life. not hyperbole — i genuinely made different career and family decisions in the weeks after. meridian creates that kind of space.\"": "„Die Patagonien-Expedition hat mein Leben verändert. Das ist keine Floskel: In den Wochen danach habe ich andere Entscheidungen für Beruf und Familie getroffen. Sie schaffen genau diesen Raum.“",
    "\"i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.\"": "„Ich habe elf Expeditionen mit verschiedenen Anbietern gemacht. Nur hier weiß der Guide, wann er spricht und wann nicht. Das ist selten und unbezahlbar.“",
    "\"my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.\"": "„Mein Sohn und ich sind die grönländische Küste gefahren. Er ist vierzehn. Er spricht noch heute davon. Zwei Wochen lassen sich nicht besser anlegen.“",
    "all expeditions": "Alle Expeditionen",
    "answer the": "Beantworten Sie den",
    "applications for 2026 expeditions are now open. limited to 8 per journey.": "Die Bewerbungen für die Expeditionen 2026 sind offen. Acht Plätze pro Reise.",
    "cross the world's most dramatic mountain range through ancient silk road passes.": "Überqueren Sie das dramatischste Gebirge der Welt durch alte Seidenstraßenpässe.",
    "every expedition begins months before departure — with research, conditioning, and route reconnaissance.": "Jede Expedition beginnt Monate vor der Abreise — mit Recherche, Konditionsaufbau und Routenerkundung.",
    "every journey is documented. photography, field notes, and gps data become your permanent record.": "Jede Reise wird dokumentiert. Fotos, Feldnotizen und GPS-Daten werden zu Ihrem Archiv.",
    "expedition storytelling and guided wilderness journeys since 2017.": "Expeditionserzählung und geführte Wildnisreisen seit 2017.",
    "expeditions": "Expeditionen",
    "expeditions.": "Expeditionen.",
    "gear": "Ausrüstung",
    "gear list": "Ausrüstungsliste",
    "glacier treks and polar wildlife encounters at 78°n latitude.": "Gletscherwanderungen und Begegnungen mit der arktischen Tierwelt auf 78°N Breitengrad.",
    "guided expeditions to the world's most remote landscapes. small teams, real challenge, permanent transformation.": "Geführte Expeditionen zu den entlegensten Landschaften der Welt. Kleine Teams, echte Herausforderung, permanente Transformation.",
    "i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.": "Ich habe 11 Expeditionen mit verschiedenen Unternehmen gemacht. Meridian ist das einzige, bei dem der Guide weiß, wann er sprechen und wann nicht sprechen soll. Das ist selten und unbezahlbar.",
    "in their": "In ihren Worten",
    "into the unknown.": "INS UNBEKANNTE.",
    "join expedition": "Expedition beitreten",
    "my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.": "Mein Sohn und ich haben die Küstenroute Grönlands gemacht. Er ist 14. Er spricht immer noch darüber. Ich werde nie eine bessere Investition von zwei Wochen finden.",
    "navigate the world's oldest desert, from deadvlei to the skeleton coast.": "Navigieren Sie durch die älteste Wüste der Welt, von Deadvlei bis zur Skelettküste.",
    "plan": "Planen",
    "small teams of 4-8, moving through terrain with purpose. camps built for recovery, not luxury.": "Kleine Teams von vier bis acht, die zielgerichtet vorankommen. Camps zur Erholung, nicht zum Luxus.",
    "the approach": "Der Ansatz",
    "the field": "Das Gelände",
    "the objective is never the top. it's the transformation that happens on the way.": "Das Ziel ist nie der Gipfel. Es ist die Verwandlung unterwegs.",
    "the summit": "Der Gipfel",
    "view expedition": "Expedition ansehen",
  },
  pt: {
    "four": "Quatro",
    "chapters.": "capítulos.",
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "expedition storytelling": "Relatos de expedição",
    "expeditions led": "Expedições conduzidas",
    "countries traversed": "Países atravessados",
    "safety record": "Sem incidentes",
    "max group size": "Tamanho máximo do grupo",
    "upcoming": "Próximas",
    "18 days": "18 dias",
    "12 days": "12 dias",
    "10 days": "10 dias",
    "expert": "Experiente",
    "moderate": "Moderado",
    "challenging": "Exigente",
    "arctic norway": "Noruega ártica",
    "namibia": "Namíbia",
    "karakoram traverse": "Travessia do Caracórum",
    "svalbard polar": "Svalbard polar",
    "namib desert crossing": "Travessia do deserto do Namibe",
    "\"the patagonia expedition changed my life. not hyperbole — i genuinely made different career and family decisions in the weeks after. meridian creates that kind of space.\"": "«A expedição à Patagónia mudou a minha vida. Não é figura de estilo: nas semanas seguintes tomei outras decisões de carreira e de família. Eles criam esse espaço.»",
    "\"i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.\"": "«Fiz onze expedições com várias agências. É a única onde o guia sabe quando falar e quando calar. É raro e não tem preço.»",
    "\"my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.\"": "«Eu e o meu filho fizemos a costa da Gronelândia. Tem catorze anos. Ainda fala nisso. Nunca encontrarei melhor uso para duas semanas.»",
    "all expeditions": "Todas as expedições",
    "answer the": "Responder ao",
    "applications for 2026 expeditions are now open. limited to 8 per journey.": "As candidaturas para as expedições de 2026 estão abertas. Oito lugares por viagem.",
    "cross the world's most dramatic mountain range through ancient silk road passes.": "Atravesse a cadeia montanhosa mais dramática do mundo através de antigos passes da Rota da Seda.",
    "every expedition begins months before departure — with research, conditioning, and route reconnaissance.": "Cada expedição começa meses antes da partida: pesquisa, preparação física e reconhecimento do itinerário.",
    "every journey is documented. photography, field notes, and gps data become your permanent record.": "Cada viagem fica documentada. Fotografias, cadernos de campo e traçados GPS tornam-se o seu arquivo.",
    "expedition storytelling and guided wilderness journeys since 2017.": "Relatos de expedição e viagens guiadas em plena natureza desde 2017.",
    "expeditions": "Expedições",
    "expeditions.": "Expedições.",
    "gear": "Equipamento",
    "gear list": "Lista de equipamento",
    "glacier treks and polar wildlife encounters at 78°n latitude.": "Caminhadas em glaciares e encontros com a vida selvagem polar a 78°N de latitude.",
    "guided expeditions to the world's most remote landscapes. small teams, real challenge, permanent transformation.": "Expedições guiadas para as paisagens mais remotas do mundo. Pequenas equipas, verdadeiro desafio, transformação permanente.",
    "i've done 11 expeditions with various companies. meridian is the only one where the guide knows when to speak and when not to. that's rare and priceless.": "Fiz 11 expedições com várias empresas. A Meridian é a única onde o guia sabe quando falar e quando não falar. Isso é raro e inestimável.",
    "in their": "Segundo eles",
    "into the unknown.": "RUMO AO DESCONHECIDO.",
    "join expedition": "Junte-se à Expedição",
    "my son and i did the greenland coastal route. he's 14. he still talks about it. i'll never find a better investment of two weeks.": "Meu filho e eu fizemos a rota costeira da Groenlândia. Ele tem 14 anos. Ele ainda fala sobre isso. Nunca encontrarei um melhor investimento de duas semanas.",
    "navigate the world's oldest desert, from deadvlei to the skeleton coast.": "Navegue pelo deserto mais antigo do mundo, de Deadvlei até a Costa dos Esqueletos.",
    "plan": "Planear",
    "small teams of 4-8, moving through terrain with purpose. camps built for recovery, not luxury.": "Equipas pequenas de quatro a oito, que avançam com um propósito. Campos feitos para recuperar, não para o luxo.",
    "the approach": "A abordagem",
    "the field": "O terreno",
    "the objective is never the top. it's the transformation that happens on the way.": "O objetivo nunca é o cume. É o que muda pelo caminho.",
    "the summit": "O cume",
    "view expedition": "Ver Expedição",
  },
};
