/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "12 days": "12 Jours",
    "curators of extraordinary journeys to the most remote corners of the globe.": "Concepteurs de voyages d'exception, jusqu'aux confins du monde.",
    "expeditions": "Expéditions",
    "fairy chimneys, underground cities, and dawn balloon flights over ancient volcanic valleys.": "Cheminées de fées, villes souterraines et vols en montgolfière à l'aube au-dessus des anciennes vallées volcaniques.",
    "field notes, photography, and exclusive expedition announcements.": "Notes de terrain, photographie et annonces d'expéditions exclusives.",
    "fully tailored itineraries crafted by local experts. go where the guidebooks don't.": "Itinéraires entièrement personnalisés conçus par des experts locaux. Allez là où les guides ne vont pas.",
    "gain a new perspective. charter flights over inaccessible terrain and untouched wilderness.": "Gagnez une nouvelle perspective. Vols affrétés au-dessus de terrains inaccessibles et de la nature vierge.",
    "guided by maasai warriors with generations of knowledge.": "Guidés par des guerriers Maasai avec des générations de connaissances.",
    "high-altitude salt flats, active geysers, and the clearest night skies on earth. an alien landscape waiting to be explored.": "Des salins en haute altitude, des geysers actifs et les ciels nocturnes les plus clairs de la Terre. Un paysage extraterrestre attendant d'être exploré.",
    "led by national geographic award winners. master landscape and wildlife photography.": "Dirigé par des lauréats du National Geographic. Maîtrisez la photographie de paysages et de la faune.",
    "our expedition designers are ready to craft your next great adventure.": "Nos concepteurs d'expédition sont prêts à composer votre prochaine grande aventure.",
    "plan your trip": "Préparer votre voyage",
    "private expeditions": "Expéditions privées",
    "ready for the": "Prêt pour",
    "sleeping in the namib desert under a billion stars, with nothing but silence around us. absolute perfection from start to finish.": "Dormir dans le désert du Namib sous un milliard d'étoiles, avec rien d'autre que le silence autour de nous. Perfection absolue du début à la fin.",
    "spend time with indigenous communities, learning ancient survival and crafting techniques.": "Passez du temps avec des communautés autochtones, apprenant des techniques anciennes de survie et d'artisanat.",
    "start planning": "Commencer à préparer",
    "terms of booking": "Conditions de réservation",
    "the atacama expedition changed the way i see the world. the logistics were flawless, allowing us to just focus on the overwhelming beauty of the landscape.": "L'expédition Atacama a changé ma façon de voir le monde. La logistique était impeccable, nous permettant de nous concentrer uniquement sur la beauté écrasante du paysage.",
    "the great migration": "La grande migration",
    "the valley of the moon. sleep in luxury glass domes under the stars and ride through sandstone canyons.": "La Vallée de la Lune. Dormez dans des dômes en verre de luxe sous les étoiles et parcourez des canyons de grès.",
    "track millions of wildebeest and zebra across the serengeti and masai mara. stay in exclusive mobile camps that move with the herds, ensuring you are always at the heart of the action.": "Suivez des millions de gnous et de zèbres à travers le Serengeti et le Masai Mara. Logez dans des camps mobiles qui se déplacent avec les troupeaux : vous êtes toujours au cœur de la scène.",
    "traveler stories": "Histoires de voyageurs",
    "traverse the oldest desert in the world. witness the towering red dunes of sossusvlei and the surreal dead-tree valleys of deadvlei.": "Traverse le plus ancien désert du monde. Admirez les dunes rouges imposantes de Sossusvlei et les vallées surréalistes des arbres morts de Deadvlei.",
    "uncompromising comfort in the most remote locations.": "Un confort sans compromis, dans les lieux les plus reculés.",
    "view full itinerary": "Voir l'itinéraire complet",
    "view itinerary": "Voir l'itinéraire",
    "wanderlust doesn't just book trips; they architect life-changing moments. worth every single penny.": "Wanderlust ne se contente pas de réserver des voyages ; ils conçoivent des moments qui changent la vie. Ça vaut chaque centime.",
    "we design travel experiences for those who seek the extraordinary. away from the crowds, immersed in the authentic rhythm of the planet.": "Nous concevons des expériences de voyage pour ceux qui recherchent l'extraordinaire. Loin des foules, immergés dans le rythme authentique de la planète.",
    "witness the greatest show on earth.": "Assistez au plus grand spectacle du monde.",
    "words from the wild": "Des mots venus du bout du monde",
  },
  es: {
    "12 days": "12 Días",
    "curators of extraordinary journeys to the most remote corners of the globe.": "Creadores de viajes excepcionales, hasta los confines del mundo.",
    "expeditions": "Expediciones",
    "fairy chimneys, underground cities, and dawn balloon flights over ancient volcanic valleys.": "Chimeneas de hadas, ciudades subterráneas y vuelos en globo al amanecer sobre antiguas valles volcánicos.",
    "field notes, photography, and exclusive expedition announcements.": "Notas de campo, fotografía y anuncios de expediciones exclusivas.",
    "fully tailored itineraries crafted by local experts. go where the guidebooks don't.": "Itinerarios completamente personalizados elaborados por expertos locales. Ve a donde los guías no van.",
    "gain a new perspective. charter flights over inaccessible terrain and untouched wilderness.": "Gana una nueva perspectiva. Vuelos chárter sobre terrenos inaccesibles y naturaleza virgen.",
    "guided by maasai warriors with generations of knowledge.": "Guiados por guerreros Maasai con generaciones de conocimiento.",
    "high-altitude salt flats, active geysers, and the clearest night skies on earth. an alien landscape waiting to be explored.": "Salinas de gran altitud, géiseres activos y los cielos nocturnos más claros de la Tierra. Un paisaje alienígena esperando ser explorado.",
    "led by national geographic award winners. master landscape and wildlife photography.": "Dirigido por ganadores de premios de National Geographic. Domina la fotografía de paisajes y vida salvaje.",
    "our expedition designers are ready to craft your next great adventure.": "Nuestros diseñadores de expediciones están listos para componer su próxima gran aventura.",
    "plan your trip": "Planifique su viaje",
    "private expeditions": "Expediciones privadas",
    "ready for the": "Listo para",
    "sleeping in the namib desert under a billion stars, with nothing but silence around us. absolute perfection from start to finish.": "Durmiendo en el desierto de Namib bajo mil millones de estrellas, con nada más que silencio a nuestro alrededor. Perfección absoluta de principio a fin.",
    "spend time with indigenous communities, learning ancient survival and crafting techniques.": "Pasa tiempo con comunidades indígenas, aprendiendo técnicas antiguas de supervivencia y artesanía.",
    "start planning": "Empezar a planificar",
    "terms of booking": "Términos de reserva",
    "the atacama expedition changed the way i see the world. the logistics were flawless, allowing us to just focus on the overwhelming beauty of the landscape.": "La expedición de Atacama cambió la forma en que veo el mundo. La logística fue impecable, permitiéndonos centrarnos solo en la abrumadora belleza del paisaje.",
    "the great migration": "La gran migración",
    "the valley of the moon. sleep in luxury glass domes under the stars and ride through sandstone canyons.": "El Valle de la Luna. Duerme en lujosos domos de vidrio bajo las estrellas y recorre cañones de arenisca.",
    "track millions of wildebeest and zebra across the serengeti and masai mara. stay in exclusive mobile camps that move with the herds, ensuring you are always at the heart of the action.": "Siga a millones de ñus y cebras por el Serengeti y el Masai Mara. Alójese en campamentos móviles que se desplazan con las manadas: siempre estará en el centro de la escena.",
    "traveler stories": "Historias de viajeros",
    "traverse the oldest desert in the world. witness the towering red dunes of sossusvlei and the surreal dead-tree valleys of deadvlei.": "Atravesar el desierto más antiguo del mundo. Testigo de las imponentes dunas rojas de Sossusvlei y los surrealistas valles de árboles muertos de Deadvlei.",
    "uncompromising comfort in the most remote locations.": "Un confort sin concesiones, en los lugares más remotos.",
    "view full itinerary": "Ver itinerario completo",
    "view itinerary": "Ver itinerario",
    "wanderlust doesn't just book trips; they architect life-changing moments. worth every single penny.": "Wanderlust no solo reserva viajes; ellos arquitectan momentos que cambian la vida. Vale cada centavo.",
    "we design travel experiences for those who seek the extraordinary. away from the crowds, immersed in the authentic rhythm of the planet.": "Diseñamos experiencias de viaje para aquellos que buscan lo extraordinario. Lejos de las multitudes, inmersos en el ritmo auténtico del planeta.",
    "witness the greatest show on earth.": "Asista al mayor espectáculo del mundo.",
    "words from the wild": "Palabras del fin del mundo",
  },
  de: {
    "12 days": "12 Tage",
    "curators of extraordinary journeys to the most remote corners of the globe.": "Gestalter außergewöhnlicher Reisen bis in die entlegensten Winkel der Welt.",
    "expeditions": "Expeditionen",
    "fairy chimneys, underground cities, and dawn balloon flights over ancient volcanic valleys.": "Feenkamine, unterirdische Städte und Ballonflüge bei Sonnenaufgang über alten Vulkantälern.",
    "field notes, photography, and exclusive expedition announcements.": "Feldnotizen, Fotografie und exklusive Expeditionsankündigungen.",
    "fully tailored itineraries crafted by local experts. go where the guidebooks don't.": "Vollständig maßgeschneiderte Reiserouten, die von lokalen Experten erstellt wurden. Gehen Sie dorthin, wo die Reiseführer nicht hingehen.",
    "gain a new perspective. charter flights over inaccessible terrain and untouched wilderness.": "Gewinnen Sie eine neue Perspektive. Charterflüge über unzugängliches Terrain und unberührte Wildnis.",
    "guided by maasai warriors with generations of knowledge.": "Geführt von Maasai-Kriegern mit Generationen von Wissen.",
    "high-altitude salt flats, active geysers, and the clearest night skies on earth. an alien landscape waiting to be explored.": "Hochgelegene Salzwiesen, aktive Geysire und die klarsten Nachthimmel der Erde. Eine fremdartige Landschaft, die darauf wartet, erkundet zu werden.",
    "led by national geographic award winners. master landscape and wildlife photography.": "Geleitet von National Geographic-Preisträgern. Meistern Sie die Landschafts- und Tierfotografie.",
    "our expedition designers are ready to craft your next great adventure.": "Unsere Expeditionsplaner sind bereit, Ihr nächstes großes Abenteuer zu gestalten.",
    "plan your trip": "Reise planen",
    "private expeditions": "Private Expeditionen",
    "ready for the": "Bereit für",
    "sleeping in the namib desert under a billion stars, with nothing but silence around us. absolute perfection from start to finish.": "Im Namib-Wüste unter einer Milliarde Sterne schlafen, mit nichts als Stille um uns herum. Absolute Perfektion von Anfang bis Ende.",
    "spend time with indigenous communities, learning ancient survival and crafting techniques.": "Verbringen Sie Zeit mit indigenen Gemeinschaften und lernen Sie alte Überlebens- und Handwerkstechniken.",
    "start planning": "Planung beginnen",
    "terms of booking": "Buchungsbedingungen",
    "the atacama expedition changed the way i see the world. the logistics were flawless, allowing us to just focus on the overwhelming beauty of the landscape.": "Die Atacama-Expedition hat meine Sicht auf die Welt verändert. Die Logistik war makellos, sodass wir uns nur auf die überwältigende Schönheit der Landschaft konzentrieren konnten.",
    "the great migration": "Die große Wanderung",
    "the valley of the moon. sleep in luxury glass domes under the stars and ride through sandstone canyons.": "Das Tal des Mondes. Schlafen Sie in luxuriösen Glaskuppeln unter den Sternen und fahren Sie durch Sandsteinschluchten.",
    "track millions of wildebeest and zebra across the serengeti and masai mara. stay in exclusive mobile camps that move with the herds, ensuring you are always at the heart of the action.": "Folgen Sie Millionen Gnus und Zebras durch die Serengeti und die Masai Mara. Wohnen Sie in mobilen Camps, die mit den Herden ziehen — Sie sind immer mittendrin.",
    "traveler stories": "Reisegeschichten",
    "traverse the oldest desert in the world. witness the towering red dunes of sossusvlei and the surreal dead-tree valleys of deadvlei.": "Durchqueren Sie die älteste Wüste der Welt. Erleben Sie die majestätischen roten Dünen von Sossusvlei und die surrealen toten Baumtäler von Deadvlei.",
    "uncompromising comfort in the most remote locations.": "Kompromissloser Komfort an den entlegensten Orten.",
    "view full itinerary": "Vollständigen Reiseverlauf anzeigen",
    "view itinerary": "Reiseverlauf anzeigen",
    "wanderlust doesn't just book trips; they architect life-changing moments. worth every single penny.": "Wanderlust bucht nicht nur Reisen; sie gestalten lebensverändernde Momente. Jeden einzelnen Cent wert.",
    "we design travel experiences for those who seek the extraordinary. away from the crowds, immersed in the authentic rhythm of the planet.": "Wir gestalten Reiseerlebnisse für diejenigen, die das Außergewöhnliche suchen. Abseits der Menschenmengen, eingetaucht in den authentischen Rhythmus des Planeten.",
    "witness the greatest show on earth.": "Erleben Sie das größte Schauspiel der Erde.",
    "words from the wild": "Stimmen aus der Wildnis",
  },
  pt: {
    "12 days": "12 Dias",
    "curators of extraordinary journeys to the most remote corners of the globe.": "Criadores de viagens de exceção, até aos confins do mundo.",
    "expeditions": "Expedições",
    "fairy chimneys, underground cities, and dawn balloon flights over ancient volcanic valleys.": "Chaminés de fadas, cidades subterrâneas e voos de balão ao amanhecer sobre antigas vales vulcânicos.",
    "field notes, photography, and exclusive expedition announcements.": "Notas de campo, fotografia e anúncios de expedições exclusivas.",
    "fully tailored itineraries crafted by local experts. go where the guidebooks don't.": "Itinerários totalmente personalizados elaborados por especialistas locais. Vá onde os guias não vão.",
    "gain a new perspective. charter flights over inaccessible terrain and untouched wilderness.": "Ganhe uma nova perspectiva. Voos charter sobre terrenos inacessíveis e natureza intocada.",
    "guided by maasai warriors with generations of knowledge.": "Guiados por guerreiros Maasai com gerações de conhecimento.",
    "high-altitude salt flats, active geysers, and the clearest night skies on earth. an alien landscape waiting to be explored.": "Planícies de sal em alta altitude, gêiseres ativos e os céus noturnos mais claros da Terra. Uma paisagem alienígena esperando para ser explorada.",
    "led by national geographic award winners. master landscape and wildlife photography.": "Liderado por vencedores de prêmios da National Geographic. Domine a fotografia de paisagens e vida selvagem.",
    "our expedition designers are ready to craft your next great adventure.": "Os nossos criadores de expedições estão prontos para compor a sua próxima grande aventura.",
    "plan your trip": "Planeie a sua viagem",
    "private expeditions": "Expedições privadas",
    "ready for the": "Pronto para",
    "sleeping in the namib desert under a billion stars, with nothing but silence around us. absolute perfection from start to finish.": "Dormir no deserto da Namíbia sob um bilhão de estrelas, com nada além de silêncio ao nosso redor. Perfeição absoluta do início ao fim.",
    "spend time with indigenous communities, learning ancient survival and crafting techniques.": "Passe tempo com comunidades indígenas, aprendendo técnicas antigas de sobrevivência e artesanato.",
    "start planning": "Começar a planear",
    "terms of booking": "Condições de reserva",
    "the atacama expedition changed the way i see the world. the logistics were flawless, allowing us to just focus on the overwhelming beauty of the landscape.": "A expedição Atacama mudou a forma como vejo o mundo. A logística foi impecável, permitindo-nos focar apenas na beleza avassaladora da paisagem.",
    "the great migration": "A grande migração",
    "the valley of the moon. sleep in luxury glass domes under the stars and ride through sandstone canyons.": "O Vale da Lua. Durma em luxuosos domos de vidro sob as estrelas e passeie por cânions de arenito.",
    "track millions of wildebeest and zebra across the serengeti and masai mara. stay in exclusive mobile camps that move with the herds, ensuring you are always at the heart of the action.": "Siga milhões de gnus e zebras pelo Serengeti e pelo Masai Mara. Fique em campos móveis que se deslocam com as manadas: estará sempre no centro da cena.",
    "traveler stories": "Histórias de viajantes",
    "traverse the oldest desert in the world. witness the towering red dunes of sossusvlei and the surreal dead-tree valleys of deadvlei.": "Atravessar o deserto mais antigo do mundo. Testemunhe as imponentes dunas vermelhas de Sossusvlei e os surrealistas vales de árvores mortas de Deadvlei.",
    "uncompromising comfort in the most remote locations.": "Um conforto sem cedências, nos lugares mais remotos.",
    "view full itinerary": "Ver itinerário completo",
    "view itinerary": "Ver itinerário",
    "wanderlust doesn't just book trips; they architect life-changing moments. worth every single penny.": "Wanderlust não apenas reserva viagens; eles arquitetam momentos que mudam a vida. Vale cada cêntimo.",
    "we design travel experiences for those who seek the extraordinary. away from the crowds, immersed in the authentic rhythm of the planet.": "Nós desenhamos experiências de viagem para aqueles que buscam o extraordinário. Longe das multidões, imersos no ritmo autêntico do planeta.",
    "witness the greatest show on earth.": "Assista ao maior espetáculo do mundo.",
    "words from the wild": "Palavras do fim do mundo",
  },
};
