/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "manifesto": "Manifeste",
    "commission": "Nous confier un projet",
    "markets": "Marchés",
    "strategies": "Stratégies",
    "traders": "Opérateurs",
    "archive": "Archives",
    "e-commerce": "Commerce en ligne",
    "origins": "Origines",
    "source": "Origine",
    "roast": "Torréfaction",
    "cup": "Tasse",
    "programs": "Programmes",
    "members": "Membres",
    "destinations": "Destinations",
    "years experience": "Ans d'expérience",
    "releases": "Sorties",
    "tour": "Tournée",
    "store": "Boutique",
    "waste diverted": "Déchets détournés",
    "residential": "Résidentiel",
    "penthouse": "Attique",
    "concierge": "Conciergerie",
    "locations": "Nos adresses",
    "seller portal": "Espace vendeurs",
    "legacy": "Héritage",
    "select seat": "Choisir sa place",
    "offense": "Attaque",
    "intelligence": "Renseignement",
    "global nodes": "Nœuds mondiaux",
    "enlist": "Nous rejoindre",
    "market": "Marché",
    "curators": "Curateurs",
    "stats": "Chiffres",
    "connect wallet": "Connecter le portefeuille",
    "sanctuary": "Le sanctuaire",
    "retreats": "Retraites",
    "essence": "Essence",
    "landmark cases": "Affaires marquantes",
    "authority": "Autorité",
    "vegan & cruelty-free": "Végane et sans cruauté",
    "design": "DESIGN",
    "content": "CONTENU",
    "we design digital experiences that": "Nous concevons des expériences numériques qui",
    "our": "Notre",
    "our story": "Notre histoire",
    "wholesale": "Vente en gros",
    "company": "La maison",
    "from seed": "Du grain",
    "single-origin specialty coffee, roasted in small batches in our": "Café de spécialité pure origine, torréfié en petits lots dans notre",
    "direct trade with fourth-generation farming families across 14 origins.": "Commerce direct avec des familles de producteurs de quatrième génération, sur quatorze origines.",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in paris — torréfié is in a class of its own.": "Le yirgacheffe éthiopien a changé ma façon de penser le café. J'ai essayé tous les torréfacteurs de spécialité à Paris — celui-ci est à part.",
    "the full torréfié experience. four origins, access to pre-release lots, priority allocation.": "L'expérience complète : quatre origines, accès aux lots en avant-première, allocation prioritaire.",
    "all origins": "Toutes les origines",
    "discover origins": "Découvrez les origines",
    "every lot scored blind by three q-graders. minimum 85 points to pass.": "Chaque lot est noté à l'aveugle par trois Q-Graders. Minimum 85 points pour réussir.",
    "finally a subscription that actually rotates origins intelligently. my palate has evolved more in three months than in three years.": "Enfin un abonnement qui fait tourner les origines avec intelligence. Mon palais a plus évolué en trois mois qu'en trois ans.",
    "free express shipping": "Livraison express gratuite",
    "free shipping": "Livraison gratuite",
    "freshness is unreal. roasted tuesday, on my desk thursday. the kenyan nyeri aa is extraordinary — the blackcurrant notes are no marketing gimmick.": "La fraîcheur est irréelle. Torréfié mardi, sur mon bureau jeudi. Le Kenyan Nyeri AA est extraordinaire — les notes de cassis ne sont pas un gadget marketing.",
    "one single-origin, chosen by our q-graders each cycle. perfect for the curious palate.": "Une origine unique, choisie par nos dégustateurs à chaque cycle. Idéale pour un palais curieux.",
    "origin stories": "Histoires d'origine",
    "plan.": "Plan.",
    "precision-profiled in small 12kg batches on a restored probat ug22.": "Profilé avec précision en petites séries de 12 kg sur un Probat UG22 restauré.",
    "process.": "Processus.",
    "reviews.": "Avis.",
    "roasted to order, shipped every two weeks. pause or cancel anytime.": "Rôti sur commande, expédié toutes les deux semaines. Faites une pause ou annulez à tout moment.",
    "roasted to order, shipped within 24 hours in fully compostable packaging.": "Rôti sur commande, expédié sous 24 heures dans un emballage entièrement compostable.",
    "shop coffee": "Boutique de café",
    "specialty coffee, roasted with precision, sourced with conscience.": "Café de spécialité, torréfié avec précision, sourcé en conscience.",
    "start your subscription": "Souscrire un abonnement",
    "subscribe and receive freshly roasted single-origin coffee at your door every two weeks.": "Abonnez-vous et recevez du café fraîchement torréfié d'origine unique chez vous toutes les deux semaines.",
    "taste the": "Goûtez le",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in": "L'Ethiopian Yirgacheffe a changé ma façon de penser le café. J'ai essayé chaque torréfacteur spécialisé dans",
    "the roastery": "La brûlerie",
    "two carefully paired origins — explore contrasts of terroir, altitude, and process.": "Deux origines soigneusement associées — explorez les contrastes de terroir, d'altitude et de processus.",
    "what clients say": "Ce que disent nos clients",
    "your": "Votre",
  },
  es: {
    "manifesto": "Manifiesto",
    "commission": "Encargar un proyecto",
    "markets": "Mercados",
    "strategies": "Estrategias",
    "traders": "Operadores",
    "archive": "Archivo",
    "e-commerce": "Comercio electrónico",
    "origins": "Orígenes",
    "source": "Origen",
    "roast": "Tueste",
    "cup": "Taza",
    "programs": "Programas",
    "members": "Miembros",
    "destinations": "Destinos",
    "years experience": "Años de experiencia",
    "releases": "Lanzamientos",
    "tour": "Gira",
    "store": "Tienda",
    "waste diverted": "Residuos desviados",
    "residential": "Residencial",
    "penthouse": "Ático",
    "concierge": "Conserjería",
    "locations": "Nuestras direcciones",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Elegir asiento",
    "offense": "Ataque",
    "intelligence": "Inteligencia",
    "global nodes": "Nodos mundiales",
    "enlist": "Únase a nosotros",
    "market": "Mercado",
    "curators": "Comisarios",
    "stats": "Cifras",
    "connect wallet": "Conectar la cartera",
    "sanctuary": "El santuario",
    "retreats": "Retiros",
    "essence": "Esencia",
    "landmark cases": "Casos emblemáticos",
    "authority": "Autoridad",
    "vegan & cruelty-free": "Vegano y sin crueldad",
    "design": "DISEÑO",
    "content": "CONTENIDO",
    "we design digital experiences that": "Diseñamos experiencias digitales que",
    "our": "Nuestro",
    "our story": "Nuestra historia",
    "wholesale": "Venta al por mayor",
    "company": "La empresa",
    "from seed": "Del grano",
    "single-origin specialty coffee, roasted in small batches in our": "Café de especialidad de origen único, tostado en pequeños lotes en nuestro",
    "direct trade with fourth-generation farming families across 14 origins.": "Comercio directo con familias productoras de cuarta generación, en catorce orígenes.",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in paris — torréfié is in a class of its own.": "El yirgacheffe etíope cambió mi forma de pensar el café. He probado todos los tostadores de especialidad de París — este está aparte.",
    "the full torréfié experience. four origins, access to pre-release lots, priority allocation.": "La experiencia completa: cuatro orígenes, acceso a lotes en preventa, asignación prioritaria.",
    "all origins": "Todos los orígenes",
    "discover origins": "Descubre los orígenes",
    "every lot scored blind by three q-graders. minimum 85 points to pass.": "Cada lote es puntuado a ciegas por tres Q-Graders. Mínimo 85 puntos para aprobar.",
    "finally a subscription that actually rotates origins intelligently. my palate has evolved more in three months than in three years.": "Por fin una suscripción que rota los orígenes con inteligencia. Mi paladar ha evolucionado más en tres meses que en tres años.",
    "free express shipping": "Envío exprés gratuito",
    "free shipping": "Envío gratuito",
    "freshness is unreal. roasted tuesday, on my desk thursday. the kenyan nyeri aa is extraordinary — the blackcurrant notes are no marketing gimmick.": "La frescura es irreal. Tostado el martes, en mi escritorio el jueves. El Kenyan Nyeri AA es extraordinario — las notas de grosella negra no son un truco de marketing.",
    "one single-origin, chosen by our q-graders each cycle. perfect for the curious palate.": "Un origen único, elegido por nuestros catadores en cada ciclo. Ideal para un paladar curioso.",
    "origin stories": "Historias de origen",
    "plan.": "Plan.",
    "precision-profiled in small 12kg batches on a restored probat ug22.": "Perfilado con precisión en pequeños lotes de 12 kg en un Probat UG22 restaurado.",
    "process.": "Proceso.",
    "reviews.": "Reseñas.",
    "roasted to order, shipped every two weeks. pause or cancel anytime.": "Tostado por encargo, enviado cada dos semanas. Pausa o cancela en cualquier momento.",
    "roasted to order, shipped within 24 hours in fully compostable packaging.": "Tostado por encargo, enviado en 24 horas en un embalaje completamente compostable.",
    "shop coffee": "Tienda de café",
    "specialty coffee, roasted with precision, sourced with conscience.": "Café de especialidad, tostado con precisión, comprado con conciencia.",
    "start your subscription": "Suscribirse",
    "subscribe and receive freshly roasted single-origin coffee at your door every two weeks.": "Suscríbete y recibe café de origen único recién tostado en tu puerta cada dos semanas.",
    "taste the": "Prueba el",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in": "El Yirgacheffe etíope cambió la forma en que pienso sobre el café. He probado cada tostador especializado en",
    "the roastery": "El tostadero",
    "two carefully paired origins — explore contrasts of terroir, altitude, and process.": "Dos orígenes cuidadosamente emparejados — explora los contrastes de terruño, altitud y proceso.",
    "what clients say": "Lo que dicen nuestros clientes",
    "your": "Tu",
  },
  de: {
    "manifesto": "Manifest",
    "commission": "Projekt anfragen",
    "markets": "Märkte",
    "strategies": "Strategien",
    "traders": "Händler",
    "archive": "Archiv",
    "e-commerce": "E-Commerce",
    "origins": "Herkünfte",
    "source": "Ursprung",
    "roast": "Röstung",
    "cup": "Tasse",
    "programs": "Programme",
    "members": "Mitglieder",
    "destinations": "Reiseziele",
    "years experience": "Jahre Erfahrung",
    "releases": "Veröffentlichungen",
    "tour": "Tour",
    "store": "Shop",
    "waste diverted": "Umgeleitete Abfälle",
    "residential": "Wohnbau",
    "penthouse": "Penthouse",
    "concierge": "Concierge-Service",
    "locations": "Unsere Standorte",
    "seller portal": "Verkäuferbereich",
    "legacy": "Erbe",
    "select seat": "Platz wählen",
    "offense": "Angriff",
    "intelligence": "Aufklärung",
    "global nodes": "Weltweite Knoten",
    "enlist": "Mitmachen",
    "market": "Markt",
    "curators": "Kuratoren",
    "stats": "Zahlen",
    "connect wallet": "Wallet verbinden",
    "sanctuary": "Das Refugium",
    "retreats": "Retreats",
    "essence": "Essenz",
    "landmark cases": "Wegweisende Fälle",
    "authority": "Autorität",
    "vegan & cruelty-free": "Vegan und tierversuchsfrei",
    "design": "DESIGN",
    "content": "INHALT",
    "we design digital experiences that": "Wir gestalten digitale Erlebnisse, die",
    "our": "Unser",
    "our story": "Unsere Geschichte",
    "wholesale": "Großhandel",
    "company": "Das Unternehmen",
    "from seed": "Von der Bohne",
    "single-origin specialty coffee, roasted in small batches in our": "Spezialitätenkaffee sortenrein, in kleinen Chargen geröstet in unserer",
    "direct trade with fourth-generation farming families across 14 origins.": "Direkter Handel mit Erzeugerfamilien in vierter Generation, aus vierzehn Herkünften.",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in paris — torréfié is in a class of its own.": "Der äthiopische Yirgacheffe hat verändert, wie ich über Kaffee denke. Ich habe jede Spezialitätenrösterei in Paris probiert — diese ist eine Klasse für sich.",
    "the full torréfié experience. four origins, access to pre-release lots, priority allocation.": "Das volle Erlebnis: vier Herkünfte, Zugang zu Vorab-Lots, bevorzugte Zuteilung.",
    "all origins": "Alle Herkünfte",
    "discover origins": "Entdecken Sie die Ursprünge",
    "every lot scored blind by three q-graders. minimum 85 points to pass.": "Jede Charge wird blind von drei Q-Graders bewertet. Mindestens 85 Punkte zum Bestehen.",
    "finally a subscription that actually rotates origins intelligently. my palate has evolved more in three months than in three years.": "Endlich ein Abo, das die Herkünfte klug wechselt. Mein Gaumen hat sich in drei Monaten mehr entwickelt als in drei Jahren.",
    "free express shipping": "Kostenloser Expressversand",
    "free shipping": "Kostenloser Versand",
    "freshness is unreal. roasted tuesday, on my desk thursday. the kenyan nyeri aa is extraordinary — the blackcurrant notes are no marketing gimmick.": "Frische ist unrealistisch. Am Dienstag geröstet, am Donnerstag auf meinem Schreibtisch. Der kenianische Nyeri AA ist außergewöhnlich — die Johannisbeernoten sind kein Marketingtrick.",
    "one single-origin, chosen by our q-graders each cycle. perfect for the curious palate.": "Ein Single Origin, von unseren Verkostern in jedem Zyklus gewählt. Ideal für den neugierigen Gaumen.",
    "origin stories": "Ursprungs-Geschichten",
    "plan.": "Plan.",
    "precision-profiled in small 12kg batches on a restored probat ug22.": "Präzise profiliert in kleinen 12-kg-Batches auf einem restaurierten Probat UG22.",
    "process.": "Prozess.",
    "reviews.": "Bewertungen.",
    "roasted to order, shipped every two weeks. pause or cancel anytime.": "Auf Bestellung geröstet, alle zwei Wochen versendet. Pausieren oder jederzeit kündigen.",
    "roasted to order, shipped within 24 hours in fully compostable packaging.": "Auf Bestellung geröstet, innerhalb von 24 Stunden in vollständig kompostierbarer Verpackung versendet.",
    "shop coffee": "Kaffee-Shop",
    "specialty coffee, roasted with precision, sourced with conscience.": "Spezialitätenkaffee, präzise geröstet, bewusst eingekauft.",
    "start your subscription": "Abo abschließen",
    "subscribe and receive freshly roasted single-origin coffee at your door every two weeks.": "Abonnieren Sie sich und erhalten Sie alle zwei Wochen frisch gerösteten Kaffee aus einer einzigen Herkunft an Ihre Tür.",
    "taste the": "Schmecken Sie den",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in": "Der äthiopische Yirgacheffe hat meine Sicht auf Kaffee verändert. Ich habe jeden Spezialitätenröster in",
    "the roastery": "Die Rösterei",
    "two carefully paired origins — explore contrasts of terroir, altitude, and process.": "Zwei sorgfältig abgestimmte Ursprünge — erkunden Sie die Kontraste von Terroir, Höhe und Prozess.",
    "what clients say": "Was Kunden sagen",
    "your": "Ihr",
  },
  pt: {
    "manifesto": "Manifesto",
    "commission": "Confiar-nos um projeto",
    "markets": "Mercados",
    "strategies": "Estratégias",
    "traders": "Operadores",
    "archive": "Arquivo",
    "e-commerce": "Comércio eletrónico",
    "origins": "Origens",
    "source": "Origem",
    "roast": "Torra",
    "cup": "Chávena",
    "programs": "Programas",
    "members": "Membros",
    "destinations": "Destinos",
    "years experience": "Anos de experiência",
    "releases": "Lançamentos",
    "tour": "Digressão",
    "store": "Loja",
    "waste diverted": "Resíduos desviados",
    "residential": "Residencial",
    "penthouse": "Cobertura",
    "concierge": "Concierge",
    "locations": "As nossas moradas",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Escolher lugar",
    "offense": "Ataque",
    "intelligence": "Informações",
    "global nodes": "Nós mundiais",
    "enlist": "Junte-se a nós",
    "market": "Mercado",
    "curators": "Curadores",
    "stats": "Números",
    "connect wallet": "Ligar a carteira",
    "sanctuary": "O santuário",
    "retreats": "Retiros",
    "essence": "Essência",
    "landmark cases": "Casos marcantes",
    "authority": "Autoridade",
    "vegan & cruelty-free": "Vegano e sem crueldade",
    "design": "DESIGN",
    "content": "CONTEÚDO",
    "we design digital experiences that": "Concebemos experiências digitais que",
    "our": "Nosso",
    "our story": "A nossa história",
    "wholesale": "Venda por grosso",
    "company": "A empresa",
    "from seed": "Do grão",
    "single-origin specialty coffee, roasted in small batches in our": "Café de especialidade de origem única, torrado em pequenos lotes na nossa",
    "direct trade with fourth-generation farming families across 14 origins.": "Comércio direto com famílias produtoras de quarta geração, em catorze origens.",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in paris — torréfié is in a class of its own.": "O yirgacheffe etíope mudou a minha forma de pensar o café. Provei todos os torrefatores de especialidade de Paris — este está à parte.",
    "the full torréfié experience. four origins, access to pre-release lots, priority allocation.": "A experiência completa: quatro origens, acesso a lotes em pré-lançamento, alocação prioritária.",
    "all origins": "Todas as origens",
    "discover origins": "Descubra as origens",
    "every lot scored blind by three q-graders. minimum 85 points to pass.": "Cada lote é avaliado às cegas por três Q-Graders. Mínimo 85 pontos para passar.",
    "finally a subscription that actually rotates origins intelligently. my palate has evolved more in three months than in three years.": "Finalmente uma subscrição que roda as origens com inteligência. O meu paladar evoluiu mais em três meses do que em três anos.",
    "free express shipping": "Envio expresso gratuito",
    "free shipping": "Envio gratuito",
    "freshness is unreal. roasted tuesday, on my desk thursday. the kenyan nyeri aa is extraordinary — the blackcurrant notes are no marketing gimmick.": "A frescura é irreal. Tostado na terça, na minha mesa na quinta. O Kenyan Nyeri AA é extraordinário — as notas de groselha negra não são um truque de marketing.",
    "one single-origin, chosen by our q-graders each cycle. perfect for the curious palate.": "Uma origem única, escolhida pelos nossos provadores em cada ciclo. Ideal para um paladar curioso.",
    "origin stories": "Histórias de origem",
    "plan.": "Plano.",
    "precision-profiled in small 12kg batches on a restored probat ug22.": "Perfilado com precisão em pequenos lotes de 12 kg num Probat UG22 restaurado.",
    "process.": "Processo.",
    "reviews.": "Avaliações.",
    "roasted to order, shipped every two weeks. pause or cancel anytime.": "Torrado por encomenda, enviado a cada duas semanas. Pause ou cancele a qualquer momento.",
    "roasted to order, shipped within 24 hours in fully compostable packaging.": "Tostado por encomenda, enviado dentro de 24 horas em embalagens totalmente compostáveis.",
    "shop coffee": "Loja de café",
    "specialty coffee, roasted with precision, sourced with conscience.": "Café de especialidade, torrado com precisão, comprado com consciência.",
    "start your subscription": "Subscrever",
    "subscribe and receive freshly roasted single-origin coffee at your door every two weeks.": "Assine-se e receba café de origem única recém-torrado à sua porta a cada duas semanas.",
    "taste the": "Prove o",
    "the ethiopian yirgacheffe changed the way i think about coffee. i've tried every specialty roaster in": "O Yirgacheffe etíope mudou a forma como penso sobre café. Já experimentei todos os torrefatores especializados em",
    "the roastery": "A torrefação",
    "two carefully paired origins — explore contrasts of terroir, altitude, and process.": "Duas origens cuidadosamente emparelhadas — explore os contrastes de terroir, altitude e processo.",
    "what clients say": "O que dizem os nossos clientes",
    "your": "Seu",
  },
};
