/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "elite legal counsel": "Conseil juridique d'exception",
    "power": "La force",
    "in truth.": "de la vérité.",
    "high-stakes litigation": "Contentieux à enjeux majeurs",
    "strategic m&a": "Fusions-acquisitions stratégiques",
    "regulatory affairs": "Affaires réglementaires",
    "managing partner": "Associé gérant",
    "senior partner": "Associée senior",
    "founding partner": "Associé fondateur",
    "global litigation": "Contentieux international",
    "m&a / private equity": "Fusions-acquisitions / capital-investissement",
    "international law": "Droit international",
    "a legacy": "Un héritage",
    "of": "d'",
    "excellence.": "excellence.",
    "transaction volume handled": "Volume d'opérations traité",
    "expertise in large-scale corporate consolidation and global capital flows.": "Expertise des consolidations d'entreprises de grande taille et des flux de capitaux internationaux.",
    "preparation is our strongest weapon. we never step into a courtroom we haven't already mastered.": "La préparation est notre meilleure arme. Nous n'entrons jamais dans une salle d'audience que nous n'avons pas déjà maîtrisée.",
    "a truly international reach with local expertise in key financial hubs.": "Une présence réellement internationale, avec une connaissance locale des grandes places financières.",
    "lumina law navigated our cross-border merger with precision and discretion. their partners think like strategists, not just lawyers. the outcome exceeded expectations at every level.": "Le cabinet a mené notre fusion transfrontalière avec précision et discrétion. Leurs associés raisonnent en stratèges, pas seulement en juristes.",
    "when we faced a regulatory crisis, their team assembled overnight and had a response strategy by morning. lumina's institutional knowledge is unmatched in our industry.": "Quand nous avons affronté une crise réglementaire, leur équipe s'est réunie dans la nuit et avait une stratégie de réponse au matin. Leur connaissance des institutions n'a pas d'équivalent.",
    "the earn-out clause that survives a downturn": "La clause d'earn-out qui survit à un retournement",
    "three quarters of the disputes we see on acquisitions start in the same paragraph. what we now insist on drafting differently.": "Trois quarts des litiges que nous voyons sur les acquisitions naissent dans le même paragraphe. Voici ce que nous rédigeons désormais autrement.",
    "why we settle more cases than we try": "Pourquoi nous transigeons plus souvent que nous ne plaidons",
    "a 98% trial record is only meaningful next to the cases that never reached a courtroom. the arithmetic, in full.": "Un taux de réussite de 98 % au procès n'a de sens qu'à côté des dossiers qui n'ont jamais vu de tribunal. Le calcul, en entier.",
    "financial entities operating in the eu now answer for their ict suppliers. the obligations that carry real penalties.": "Les entités financières qui opèrent dans l'Union répondent désormais de leurs fournisseurs informatiques. Les obligations qui portent de vraies sanctions.",
    "the hague 2019 route, its exclusions, and where a fresh action in the local court is still faster.": "La voie de La Haye 2019, ses exclusions, et les cas où une action nouvelle devant le tribunal local reste plus rapide.",
    "fourteen jurisdictions, eleven months, one regulator holding it up until the last week. closed without a price adjustment.": "Quatorze juridictions, onze mois, un régulateur qui bloque jusqu'à la dernière semaine. Clôturé sans ajustement de prix.",
    "a €340m derivative action against a listed board. struck out on standing before the merits were ever argued.": "Une action sociale de 340 M€ contre le conseil d'une société cotée. Rejetée pour défaut de qualité à agir, avant tout débat au fond.",
    "court-sanctioned in under six months, with 94% approval in the largest class.": "Homologué par le tribunal en moins de six mois, avec 94 % d'approbation dans le groupe le plus nombreux.",
    "matters are described in outline only. named parties, figures and jurisdictions are altered or omitted wherever the engagement or its settlement remains confidential.": "Les dossiers ne sont décrits qu'à grands traits. Noms, montants et juridictions sont modifiés ou omis chaque fois que le mandat ou le secret professionnel l'exige.",
    "\"integrity is the only foundation upon which true victory can be built.\"": "« L'intégrité est le seul socle sur lequel bâtir une véritable victoire. »",
    "\"the law is a shield for the righteous and a sword for the strategic. we provide both.\"": "\"La loi est un bouclier pour les justes et une épée pour les stratégiques. Nous fournissons les deux.\"",
    "120+ years of combined experience": "Plus de 120 ans d'expérience combinée",
    "aggressive representation in complex civil and criminal proceedings with a track record of landmark victories.": "Représentation agressive dans des procédures civiles et pénales complexes avec un bilan de victoires marquantes.",
    "client portal": "Portail Client",
    "client testimonials": "Témoignages de Clients",
    "contact our intake team for a strictly confidential consultation. we handle the complexities so you can focus on your legacy.": "Contactez notre équipe d'accueil pour une consultation strictement confidentielle. Nous gérons les complexités afin que vous puissiez vous concentrer sur votre héritage.",
    "define your": "Définissez votre",
    "lumina law is a high-stakes firm dedicated to complex litigation and corporate strategy. when the outcome defines your legacy, we are the standard.": "Lumina Law est un cabinet de haut niveau dédié aux litiges complexes et à la stratégie d'entreprise. Lorsque le résultat définit votre héritage, nous sommes la référence.",
    "meet the partners": "Les associés",
    "navigating multi-billion dollar transactions with surgical precision and cross-border expertise.": "Naviguer dans des transactions de plusieurs milliards de dollars avec une précision chirurgicale et une expertise transfrontalière.",
    "our dominance": "Notre force",
    "our success map": "Notre carte des succès",
    "request initial brief": "Demander un bref initial",
    "shaping the landscape of tomorrow through deep-level engagement with legislative and regulatory bodies.": "Façonner le paysage de demain grâce à un engagement de haut niveau avec les organes législatifs et réglementaires.",
    "we've retained lumina for eight years across litigation, m&a, and regulatory matters. they have become an indispensable extension of our executive leadership.": "Nous avons retenu Lumina pendant huit ans pour des litiges, des fusions et acquisitions, et des questions réglementaires. Ils sont devenus une extension indispensable de notre direction exécutive.",
    "what our clients": "Ce que nos clients",
    "what we": "Ce que nous",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "elite legal counsel": "Asesoría jurídica de excepción",
    "power": "La fuerza",
    "in truth.": "de la verdad.",
    "high-stakes litigation": "Litigios de alto riesgo",
    "strategic m&a": "Fusiones y adquisiciones estratégicas",
    "regulatory affairs": "Asuntos regulatorios",
    "managing partner": "Socio director",
    "senior partner": "Socia sénior",
    "founding partner": "Socio fundador",
    "global litigation": "Litigio internacional",
    "m&a / private equity": "Fusiones y adquisiciones / capital riesgo",
    "international law": "Derecho internacional",
    "a legacy": "Un legado",
    "of": "de",
    "excellence.": "excelencia.",
    "transaction volume handled": "Volumen de operaciones gestionado",
    "expertise in large-scale corporate consolidation and global capital flows.": "Experiencia en consolidaciones empresariales de gran tamaño y flujos de capital internacionales.",
    "preparation is our strongest weapon. we never step into a courtroom we haven't already mastered.": "La preparación es nuestra mejor arma. Nunca entramos en una sala de vistas que no dominemos ya.",
    "a truly international reach with local expertise in key financial hubs.": "Una presencia realmente internacional, con conocimiento local de las grandes plazas financieras.",
    "lumina law navigated our cross-border merger with precision and discretion. their partners think like strategists, not just lawyers. the outcome exceeded expectations at every level.": "El despacho llevó nuestra fusión transfronteriza con precisión y discreción. Sus socios razonan como estrategas, no solo como juristas.",
    "when we faced a regulatory crisis, their team assembled overnight and had a response strategy by morning. lumina's institutional knowledge is unmatched in our industry.": "Cuando afrontamos una crisis regulatoria, su equipo se reunió de noche y tenía una estrategia de respuesta por la mañana. Su conocimiento institucional no tiene igual.",
    "the earn-out clause that survives a downturn": "La cláusula de earn-out que sobrevive a una caída",
    "three quarters of the disputes we see on acquisitions start in the same paragraph. what we now insist on drafting differently.": "Tres cuartas partes de los litigios que vemos en adquisiciones nacen en el mismo párrafo. Esto es lo que ahora redactamos de otro modo.",
    "why we settle more cases than we try": "Por qué transamos más de lo que litigamos",
    "a 98% trial record is only meaningful next to the cases that never reached a courtroom. the arithmetic, in full.": "Un 98 % de éxito en juicio solo tiene sentido junto a los casos que nunca llegaron a los tribunales. El cálculo, completo.",
    "financial entities operating in the eu now answer for their ict suppliers. the obligations that carry real penalties.": "Las entidades financieras que operan en la Unión responden ahora de sus proveedores informáticos. Las obligaciones que traen sanciones reales.",
    "the hague 2019 route, its exclusions, and where a fresh action in the local court is still faster.": "La vía de La Haya 2019, sus exclusiones y los casos en que una nueva acción ante el tribunal local sigue siendo más rápida.",
    "fourteen jurisdictions, eleven months, one regulator holding it up until the last week. closed without a price adjustment.": "Catorce jurisdicciones, once meses, un regulador que bloquea hasta la última semana. Cerrado sin ajuste de precio.",
    "a €340m derivative action against a listed board. struck out on standing before the merits were ever argued.": "Una acción social de 340 M€ contra el consejo de una cotizada. Rechazada por falta de legitimación, antes de todo debate de fondo.",
    "court-sanctioned in under six months, with 94% approval in the largest class.": "Homologado por el tribunal en menos de seis meses, con un 94 % de aprobación en el grupo más numeroso.",
    "matters are described in outline only. named parties, figures and jurisdictions are altered or omitted wherever the engagement or its settlement remains confidential.": "Los asuntos se describen solo a grandes rasgos. Nombres, importes y jurisdicciones se alteran u omiten siempre que el mandato o el secreto profesional lo exija.",
    "\"integrity is the only foundation upon which true victory can be built.\"": "«La integridad es el único cimiento sobre el que se construye una verdadera victoria.»",
    "\"the law is a shield for the righteous and a sword for the strategic. we provide both.\"": "\"La ley es un escudo para los justos y una espada para los estratégicos. Proporcionamos ambos.\"",
    "120+ years of combined experience": "Más de 120 años de experiencia combinada",
    "aggressive representation in complex civil and criminal proceedings with a track record of landmark victories.": "Representación agresiva en procedimientos civiles y penales complejos con un historial de victorias emblemáticas.",
    "client portal": "Portal del Cliente",
    "client testimonials": "Testimonios de Clientes",
    "contact our intake team for a strictly confidential consultation. we handle the complexities so you can focus on your legacy.": "Contacta a nuestro equipo de admisión para una consulta estrictamente confidencial. Nos encargamos de las complejidades para que puedas centrarte en tu legado.",
    "define your": "Define tu",
    "lumina law is a high-stakes firm dedicated to complex litigation and corporate strategy. when the outcome defines your legacy, we are the standard.": "Lumina Law es una firma de alto riesgo dedicada a litigios complejos y estrategia corporativa. Cuando el resultado define tu legado, somos el estándar.",
    "meet the partners": "Los socios",
    "navigating multi-billion dollar transactions with surgical precision and cross-border expertise.": "Navegando transacciones de varios miles de millones de dólares con precisión quirúrgica y experiencia transfronteriza.",
    "our dominance": "Nuestra fuerza",
    "our success map": "Nuestro mapa de éxitos",
    "request initial brief": "Solicitar un informe inicial",
    "shaping the landscape of tomorrow through deep-level engagement with legislative and regulatory bodies.": "Dando forma al paisaje del mañana a través de un compromiso profundo con los organismos legislativos y regulatorios.",
    "we've retained lumina for eight years across litigation, m&a, and regulatory matters. they have become an indispensable extension of our executive leadership.": "Hemos contratado a Lumina durante ocho años en litigios, M&A y asuntos regulatorios. Se han convertido en una extensión indispensable de nuestro liderazgo ejecutivo.",
    "what our clients": "Lo que nuestros clientes",
    "what we": "Lo que hacemos",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "elite legal counsel": "Juristische Beratung auf höchstem Niveau",
    "power": "Die Kraft",
    "in truth.": "der Wahrheit.",
    "high-stakes litigation": "Verfahren mit hohem Einsatz",
    "strategic m&a": "Strategische M&A",
    "regulatory affairs": "Regulierungsfragen",
    "managing partner": "Geschäftsführender Partner",
    "senior partner": "Senior-Partnerin",
    "founding partner": "Gründungspartner",
    "global litigation": "Internationale Prozessführung",
    "m&a / private equity": "M&A / Private Equity",
    "international law": "Internationales Recht",
    "a legacy": "Ein Erbe",
    "of": "der",
    "excellence.": "Exzellenz.",
    "transaction volume handled": "Bearbeitetes Transaktionsvolumen",
    "expertise in large-scale corporate consolidation and global capital flows.": "Expertise bei großen Unternehmenszusammenschlüssen und internationalen Kapitalflüssen.",
    "preparation is our strongest weapon. we never step into a courtroom we haven't already mastered.": "Vorbereitung ist unsere stärkste Waffe. Wir betreten keinen Gerichtssaal, den wir nicht schon beherrschen.",
    "a truly international reach with local expertise in key financial hubs.": "Eine wirklich internationale Präsenz mit lokaler Kenntnis der großen Finanzplätze.",
    "lumina law navigated our cross-border merger with precision and discretion. their partners think like strategists, not just lawyers. the outcome exceeded expectations at every level.": "Die Kanzlei hat unsere grenzüberschreitende Fusion präzise und diskret geführt. Ihre Partner denken wie Strategen, nicht nur wie Juristen.",
    "when we faced a regulatory crisis, their team assembled overnight and had a response strategy by morning. lumina's institutional knowledge is unmatched in our industry.": "Als wir in eine Regulierungskrise gerieten, kam ihr Team über Nacht zusammen und hatte am Morgen eine Antwortstrategie. Ihre institutionelle Kenntnis ist unerreicht.",
    "the earn-out clause that survives a downturn": "Die Earn-out-Klausel, die einen Abschwung übersteht",
    "three quarters of the disputes we see on acquisitions start in the same paragraph. what we now insist on drafting differently.": "Drei Viertel der Streitigkeiten, die wir bei Übernahmen sehen, entstehen im selben Absatz. Das formulieren wir inzwischen anders.",
    "why we settle more cases than we try": "Warum wir häufiger vergleichen als prozessieren",
    "a 98% trial record is only meaningful next to the cases that never reached a courtroom. the arithmetic, in full.": "Eine Erfolgsquote von 98 % vor Gericht sagt nur etwas neben den Fällen, die nie vor Gericht kamen. Die Rechnung, vollständig.",
    "financial entities operating in the eu now answer for their ict suppliers. the obligations that carry real penalties.": "Finanzunternehmen in der EU haften nun für ihre IT-Dienstleister. Die Pflichten, an denen echte Sanktionen hängen.",
    "the hague 2019 route, its exclusions, and where a fresh action in the local court is still faster.": "Der Weg über Haag 2019, seine Ausnahmen — und wo eine neue Klage vor dem lokalen Gericht schneller bleibt.",
    "fourteen jurisdictions, eleven months, one regulator holding it up until the last week. closed without a price adjustment.": "Vierzehn Jurisdiktionen, elf Monate, eine Aufsichtsbehörde, die bis zur letzten Woche blockiert. Ohne Kaufpreisanpassung abgeschlossen.",
    "a €340m derivative action against a listed board. struck out on standing before the merits were ever argued.": "Eine Gesellschafterklage über 340 Mio. € gegen den Vorstand eines börsennotierten Unternehmens. Mangels Klagebefugnis abgewiesen, bevor es zur Sache kam.",
    "court-sanctioned in under six months, with 94% approval in the largest class.": "Gerichtlich bestätigt in unter sechs Monaten, mit 94 % Zustimmung in der größten Gruppe.",
    "matters are described in outline only. named parties, figures and jurisdictions are altered or omitted wherever the engagement or its settlement remains confidential.": "Die Mandate sind nur in Umrissen beschrieben. Namen, Beträge und Gerichtsstände werden geändert oder weggelassen, wo Mandat oder Verschwiegenheit es verlangen.",
    "\"integrity is the only foundation upon which true victory can be built.\"": "„Integrität ist das einzige Fundament, auf dem sich ein wahrer Sieg errichten lässt.“",
    "\"the law is a shield for the righteous and a sword for the strategic. we provide both.\"": "\"Das Gesetz ist ein Schild für die Gerechten und ein Schwert für die Strategen. Wir bieten beides an.\"",
    "120+ years of combined experience": "Über 120 Jahre kombinierte Erfahrung",
    "aggressive representation in complex civil and criminal proceedings with a track record of landmark victories.": "Aggressive Vertretung in komplexen zivil- und strafrechtlichen Verfahren mit einer Erfolgsbilanz von wegweisenden Siegen.",
    "client portal": "Kundenportal",
    "client testimonials": "Kundenbewertungen",
    "contact our intake team for a strictly confidential consultation. we handle the complexities so you can focus on your legacy.": "Kontaktieren Sie unser Aufnahmeteam für eine streng vertrauliche Beratung. Wir kümmern uns um die Komplexitäten, damit Sie sich auf Ihr Erbe konzentrieren können.",
    "define your": "Definieren Sie Ihr",
    "lumina law is a high-stakes firm dedicated to complex litigation and corporate strategy. when the outcome defines your legacy, we are the standard.": "Lumina Law ist eine Hochrisikofirma, die sich auf komplexe Rechtsstreitigkeiten und Unternehmensstrategien spezialisiert hat. Wenn das Ergebnis Ihr Erbe definiert, sind wir der Maßstab.",
    "meet the partners": "Die Partner",
    "navigating multi-billion dollar transactions with surgical precision and cross-border expertise.": "Navigieren durch Transaktionen im Wert von mehreren Milliarden Dollar mit chirurgischer Präzision und grenzüberschreitender Expertise.",
    "our dominance": "Unsere Stärke",
    "our success map": "Unsere Erfolgskarte",
    "request initial brief": "Anfrage nach einem ersten Briefing",
    "shaping the landscape of tomorrow through deep-level engagement with legislative and regulatory bodies.": "Die Landschaft von morgen gestalten durch tiefgreifendes Engagement mit legislativen und regulatorischen Stellen.",
    "we've retained lumina for eight years across litigation, m&a, and regulatory matters. they have become an indispensable extension of our executive leadership.": "Wir haben Lumina seit acht Jahren in Rechtsstreitigkeiten, M&A und regulatorischen Angelegenheiten beauftragt. Sie sind zu einer unverzichtbaren Erweiterung unserer Geschäftsführung geworden.",
    "what our clients": "Was unsere Kunden",
    "what we": "Was wir",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "elite legal counsel": "Consultoria jurídica de exceção",
    "power": "A força",
    "in truth.": "da verdade.",
    "high-stakes litigation": "Contencioso de grandes riscos",
    "strategic m&a": "Fusões e aquisições estratégicas",
    "regulatory affairs": "Assuntos regulatórios",
    "managing partner": "Sócio-gerente",
    "senior partner": "Sócia sénior",
    "founding partner": "Sócio fundador",
    "global litigation": "Contencioso internacional",
    "m&a / private equity": "Fusões e aquisições / capital de risco",
    "international law": "Direito internacional",
    "a legacy": "Um legado",
    "of": "de",
    "excellence.": "excelência.",
    "transaction volume handled": "Volume de operações tratado",
    "expertise in large-scale corporate consolidation and global capital flows.": "Experiência em consolidações empresariais de grande dimensão e fluxos de capitais internacionais.",
    "preparation is our strongest weapon. we never step into a courtroom we haven't already mastered.": "A preparação é a nossa melhor arma. Nunca entramos numa sala de audiências que não dominemos já.",
    "a truly international reach with local expertise in key financial hubs.": "Uma presença verdadeiramente internacional, com conhecimento local das grandes praças financeiras.",
    "lumina law navigated our cross-border merger with precision and discretion. their partners think like strategists, not just lawyers. the outcome exceeded expectations at every level.": "O escritório conduziu a nossa fusão transfronteiriça com precisão e discrição. Os sócios raciocinam como estrategas, não apenas como juristas.",
    "when we faced a regulatory crisis, their team assembled overnight and had a response strategy by morning. lumina's institutional knowledge is unmatched in our industry.": "Quando enfrentámos uma crise regulatória, a equipa reuniu-se durante a noite e tinha uma estratégia de resposta pela manhã. O seu conhecimento institucional não tem igual.",
    "the earn-out clause that survives a downturn": "A cláusula de earn-out que sobrevive a uma queda",
    "three quarters of the disputes we see on acquisitions start in the same paragraph. what we now insist on drafting differently.": "Três quartos dos litígios que vemos em aquisições nascem no mesmo parágrafo. É isto que passámos a redigir de outra forma.",
    "why we settle more cases than we try": "Porque transigimos mais do que litigamos",
    "a 98% trial record is only meaningful next to the cases that never reached a courtroom. the arithmetic, in full.": "Uma taxa de 98 % de êxito em julgamento só faz sentido ao lado dos casos que nunca chegaram a tribunal. A conta, por inteiro.",
    "financial entities operating in the eu now answer for their ict suppliers. the obligations that carry real penalties.": "As entidades financeiras que operam na União respondem agora pelos seus fornecedores informáticos. As obrigações que trazem sanções reais.",
    "the hague 2019 route, its exclusions, and where a fresh action in the local court is still faster.": "A via da Haia 2019, as suas exclusões e os casos em que uma nova ação no tribunal local continua a ser mais rápida.",
    "fourteen jurisdictions, eleven months, one regulator holding it up until the last week. closed without a price adjustment.": "Catorze jurisdições, onze meses, um regulador a bloquear até à última semana. Fechado sem ajustamento de preço.",
    "a €340m derivative action against a listed board. struck out on standing before the merits were ever argued.": "Uma ação social de 340 M€ contra o conselho de uma cotada. Rejeitada por falta de legitimidade, antes de qualquer debate de fundo.",
    "court-sanctioned in under six months, with 94% approval in the largest class.": "Homologado pelo tribunal em menos de seis meses, com 94 % de aprovação no grupo mais numeroso.",
    "matters are described in outline only. named parties, figures and jurisdictions are altered or omitted wherever the engagement or its settlement remains confidential.": "Os processos são descritos apenas em traços gerais. Nomes, montantes e jurisdições são alterados ou omitidos sempre que o mandato ou o sigilo o exijam.",
    "\"integrity is the only foundation upon which true victory can be built.\"": "«A integridade é o único alicerce sobre o qual se constrói uma verdadeira vitória.»",
    "\"the law is a shield for the righteous and a sword for the strategic. we provide both.\"": "\"A lei é um escudo para os justos e uma espada para os estratégicos. Nós fornecemos ambos.\"",
    "120+ years of combined experience": "Mais de 120 anos de experiência combinada",
    "aggressive representation in complex civil and criminal proceedings with a track record of landmark victories.": "Representação agressiva em processos civis e criminais complexos com um histórico de vitórias marcantes.",
    "client portal": "Portal do Cliente",
    "client testimonials": "Testemunhos de Clientes",
    "contact our intake team for a strictly confidential consultation. we handle the complexities so you can focus on your legacy.": "Contacte a nossa equipa de acolhimento para uma consulta estritamente confidencial. Nós tratamos das complexidades para que você possa se concentrar no seu legado.",
    "define your": "Defina o seu",
    "lumina law is a high-stakes firm dedicated to complex litigation and corporate strategy. when the outcome defines your legacy, we are the standard.": "Lumina Law é uma firma de alto risco dedicada a litígios complexos e estratégia corporativa. Quando o resultado define o seu legado, somos o padrão.",
    "meet the partners": "Os sócios",
    "navigating multi-billion dollar transactions with surgical precision and cross-border expertise.": "Navegando em transações de vários bilhões de dólares com precisão cirúrgica e expertise transfronteiriça.",
    "our dominance": "A nossa força",
    "our success map": "O nosso mapa de sucessos",
    "request initial brief": "Solicitar um resumo inicial",
    "shaping the landscape of tomorrow through deep-level engagement with legislative and regulatory bodies.": "Moldando a paisagem do amanhã através de um envolvimento profundo com os órgãos legislativos e regulatórios.",
    "we've retained lumina for eight years across litigation, m&a, and regulatory matters. they have become an indispensable extension of our executive leadership.": "Mantivemos a Lumina durante oito anos em litígios, M&A e questões regulatórias. Eles se tornaram uma extensão indispensável da nossa liderança executiva.",
    "what our clients": "O que os nossos clientes",
    "what we": "O que fazemos",
  },
};
