/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "architectural design": "Conception Architecturale",
    "architecture does not end at the facade. we design the soil, the water table, the micro-climate, and the habitat corridors that make a building truly alive.": "L'architecture ne s'arrête pas à la façade. Nous concevons le sol, la nappe phréatique, le microclimat et les corridors de habitat qui rendent un bâtiment vraiment vivant.",
    "biophilic architecture and sustainable design. oslo — singapore — bali.": "Architecture biophilique et design durable. Oslo — Singapour — Bali.",
    "carved into the mountainside and clad in local quartzite, these baths harness geothermal energy to maintain perfect temperatures year-round — zero combustion.": "Taillés dans la montagne et revêtus de quartzite local, ces bains exploitent l'énergie géothermique pour maintenir des températures parfaites toute l'année — zéro combustion.",
    "elena rostova's studio designs living structures that regenerate their ecosystems, sequester carbon, and evolve alongside their inhabitants.": "Le studio d'Elena Rostova conçoit des structures vivantes qui régénèrent leurs écosystèmes, séquestrent le carbone et évoluent aux côtés de leurs habitants.",
    "eleven years of practice. forty-seven completed projects. a growing archive of international recognition — but never the reason we build.": "Onze ans d'exercice. Quarante-sept projets livrés. Des distinctions internationales qui s'accumulent — mais qui ne sont jamais la raison de bâtir.",
    "enquire": "Demander",
    "every branch": "Chaque branche",
    "every project begins with a conversation. tell us about your site, your vision, and the ecosystem you want to protect.": "Chaque projet commence par une conversation. Parlez-nous de votre terrain, de votre projet, et du milieu que vous voulez préserver.",
    "honoured by the": "Distingué par",
    "living with the living": "Vivre avec le vivant",
    "materials that heal": "Des matières qui soignent",
    "most innovative architecture firm": "Agence d'architecture la plus innovante",
    "nature as blueprint": "La nature comme plan",
    "navigation of breeam, leed, and well certification pathways. we've achieved platinum on our last six projects and we don't accept less.": "Navigation des voies de certification BREEAM, LEED et WELL. Nous avons obtenu le Platine sur nos six derniers projets et nous n'acceptons pas moins.",
    "our in-house lab tests emerging bio-based materials — algae panels, fungal insulation, mycelium composites — before they reach the mainstream.": "Notre laboratoire interne teste les nouveaux matériaux biosourcés — panneaux en algues, isolation fongique, composites de mycélium — avant qu'ils n'atteignent le grand public.",
    "ready to build": "Prêt à bâtir",
    "structural bamboo arches span 24 metres, creating a community hub that withstands typhoon-force winds and remains fully biodegradable at end of life.": "Des arches en bambou structurel s'étendent sur 24 mètres, créant un centre communautaire qui résiste aux vents de force typhon et reste entièrement biodégradable en fin de vie.",
    "sustainable building of the year": "Bâtiment Durable de l'Année",
    "sustainable design studio of the year": "Agence de conception durable de l'année",
    "tells a story.": "raconte une histoire.",
    "the glass house": "La Maison de Verre",
    "the matter.": "la matière.",
    "the minds behind": "Les esprits derrière",
    "the studio in numbers": "L'agence en chiffres",
    "view all projects →": "Voir tous les projets →",
  },
  es: {
    "architectural design": "Diseño Arquitectónico",
    "architecture does not end at the facade. we design the soil, the water table, the micro-climate, and the habitat corridors that make a building truly alive.": "La arquitectura no termina en la fachada. Diseñamos el suelo, la tabla de agua, el microclima y los corredores de hábitat que hacen que un edificio esté verdaderamente vivo.",
    "biophilic architecture and sustainable design. oslo — singapore — bali.": "Arquitectura biofílica y diseño sostenible. Oslo — Singapur — Bali.",
    "carved into the mountainside and clad in local quartzite, these baths harness geothermal energy to maintain perfect temperatures year-round — zero combustion.": "Tallados en la ladera de la montaña y revestidos de cuarcita local, estos baños aprovechan la energía geotérmica para mantener temperaturas perfectas durante todo el año — cero combustión.",
    "elena rostova's studio designs living structures that regenerate their ecosystems, sequester carbon, and evolve alongside their inhabitants.": "El estudio de Elena Rostova diseña estructuras vivas que regeneran sus ecosistemas, secuestran carbono y evolucionan junto a sus habitantes.",
    "eleven years of practice. forty-seven completed projects. a growing archive of international recognition — but never the reason we build.": "Once años de ejercicio. Cuarenta y siete proyectos entregados. Distinciones internacionales que se acumulan, pero que nunca son la razón de construir.",
    "enquire": "Consultar",
    "every branch": "Cada rama",
    "every project begins with a conversation. tell us about your site, your vision, and the ecosystem you want to protect.": "Cada proyecto empieza con una conversación. Háblenos de su terreno, de su visión y del entorno que quiere preservar.",
    "honoured by the": "Distinguido por",
    "living with the living": "Vivir con lo vivo",
    "materials that heal": "Materias que curan",
    "most innovative architecture firm": "Estudio de arquitectura más innovador",
    "nature as blueprint": "La naturaleza como plano",
    "navigation of breeam, leed, and well certification pathways. we've achieved platinum on our last six projects and we don't accept less.": "Navegación de las vías de certificación BREEAM, LEED y WELL. Hemos logrado Platino en nuestros últimos seis proyectos y no aceptamos menos.",
    "our in-house lab tests emerging bio-based materials — algae panels, fungal insulation, mycelium composites — before they reach the mainstream.": "Nuestro laboratorio interno prueba materiales bio-basados emergentes — paneles de algas, aislamiento fúngico, compuestos de micelio — antes de que lleguen al mercado masivo.",
    "ready to build": "Listo para construir",
    "structural bamboo arches span 24 metres, creating a community hub that withstands typhoon-force winds and remains fully biodegradable at end of life.": "Arcos de bambú estructurales se extienden 24 metros, creando un centro comunitario que soporta vientos de fuerza tifón y sigue siendo completamente biodegradable al final de su vida.",
    "sustainable building of the year": "Edificio Sostenible del Año",
    "sustainable design studio of the year": "Estudio de diseño sostenible del año",
    "tells a story.": "cuenta una historia.",
    "the glass house": "La Casa de Vidrio",
    "the matter.": "la materia.",
    "the minds behind": "Las mentes tras",
    "the studio in numbers": "El estudio en cifras",
    "view all projects →": "Ver todos los proyectos →",
  },
  de: {
    "architectural design": "Architekturdesign",
    "architecture does not end at the facade. we design the soil, the water table, the micro-climate, and the habitat corridors that make a building truly alive.": "Architektur endet nicht an der Fassade. Wir gestalten den Boden, den Grundwasserspiegel, das Mikroklima und die Lebensraumkorridore, die ein Gebäude wirklich lebendig machen.",
    "biophilic architecture and sustainable design. oslo — singapore — bali.": "Biophile Architektur und nachhaltiges Design. Oslo — Singapur — Bali.",
    "carved into the mountainside and clad in local quartzite, these baths harness geothermal energy to maintain perfect temperatures year-round — zero combustion.": "In die Bergseite gemeißelt und mit lokalem Quarzit verkleidet, nutzen diese Bäder geothermische Energie, um das ganze Jahr über perfekte Temperaturen zu halten — null Verbrennung.",
    "elena rostova's studio designs living structures that regenerate their ecosystems, sequester carbon, and evolve alongside their inhabitants.": "Das Studio von Elena Rostova entwirft lebende Strukturen, die ihre Ökosysteme regenerieren, Kohlenstoff speichern und sich zusammen mit ihren Bewohnern entwickeln.",
    "eleven years of practice. forty-seven completed projects. a growing archive of international recognition — but never the reason we build.": "Elf Jahre Praxis. Siebenundvierzig fertige Projekte. Ein wachsendes Archiv internationaler Anerkennung — nie aber der Grund, warum wir bauen.",
    "enquire": "Anfragen",
    "every branch": "Jeder Zweig",
    "every project begins with a conversation. tell us about your site, your vision, and the ecosystem you want to protect.": "Jedes Projekt beginnt mit einem Gespräch. Erzählen Sie uns von Ihrem Grundstück, Ihrer Vision und dem Ökosystem, das Sie schützen wollen.",
    "honoured by the": "Ausgezeichnet von",
    "living with the living": "Mit dem Lebendigen leben",
    "materials that heal": "Materialien, die heilen",
    "most innovative architecture firm": "Innovativstes Architekturbüro",
    "nature as blueprint": "Die Natur als Blaupause",
    "navigation of breeam, leed, and well certification pathways. we've achieved platinum on our last six projects and we don't accept less.": "Navigation der Zertifizierungspfade BREEAM, LEED und WELL. Wir haben in unseren letzten sechs Projekten Platin erreicht und akzeptieren nicht weniger.",
    "our in-house lab tests emerging bio-based materials — algae panels, fungal insulation, mycelium composites — before they reach the mainstream.": "Unser internes Labor testet aufkommende biobasierte Materialien — Algenpaneele, Pilzdämmung, Myzelkomposite — bevor sie den Mainstream erreichen.",
    "ready to build": "Bereit zu bauen",
    "structural bamboo arches span 24 metres, creating a community hub that withstands typhoon-force winds and remains fully biodegradable at end of life.": "Strukturelle Bambusbögen spannen sich über 24 Meter und schaffen ein Gemeinschaftszentrum, das taifunstarken Winden standhält und am Ende seiner Lebensdauer vollständig biologisch abbaubar bleibt.",
    "sustainable building of the year": "Nachhaltiges Gebäude des Jahres",
    "sustainable design studio of the year": "Büro für nachhaltiges Design des Jahres",
    "tells a story.": "erzählt eine Geschichte.",
    "the glass house": "Das Glashaus",
    "the matter.": "der Materie.",
    "the minds behind": "Die Köpfe hinter",
    "the studio in numbers": "Das Büro in Zahlen",
    "view all projects →": "Alle Projekte ansehen →",
  },
  pt: {
    "architectural design": "Design Arquitetónico",
    "architecture does not end at the facade. we design the soil, the water table, the micro-climate, and the habitat corridors that make a building truly alive.": "A arquitetura não termina na fachada. Nós projetamos o solo, a tabela de água, o microclima e os corredores de habitat que tornam um edifício verdadeiramente vivo.",
    "biophilic architecture and sustainable design. oslo — singapore — bali.": "Arquitetura biofílica e design sustentável. Oslo — Singapura — Bali.",
    "carved into the mountainside and clad in local quartzite, these baths harness geothermal energy to maintain perfect temperatures year-round — zero combustion.": "Esculpidos na encosta da montanha e revestidos com quartzito local, estes banhos aproveitam a energia geotérmica para manter temperaturas perfeitas durante todo o ano — zero combustão.",
    "elena rostova's studio designs living structures that regenerate their ecosystems, sequester carbon, and evolve alongside their inhabitants.": "O estúdio de Elena Rostova projeta estruturas vivas que regeneram seus ecossistemas, sequestram carbono e evoluem ao lado de seus habitantes.",
    "eleven years of practice. forty-seven completed projects. a growing archive of international recognition — but never the reason we build.": "Onze anos de exercício. Quarenta e sete projetos entregues. Distinções internacionais que se acumulam — mas que nunca são a razão de construir.",
    "enquire": "Perguntar",
    "every branch": "Cada ramo",
    "every project begins with a conversation. tell us about your site, your vision, and the ecosystem you want to protect.": "Cada projeto começa com uma conversa. Fale-nos do seu terreno, da sua visão e do meio que quer preservar.",
    "honoured by the": "Distinguido por",
    "living with the living": "Viver com o vivo",
    "materials that heal": "Matérias que curam",
    "most innovative architecture firm": "Atelier de arquitetura mais inovador",
    "nature as blueprint": "A natureza como plano",
    "navigation of breeam, leed, and well certification pathways. we've achieved platinum on our last six projects and we don't accept less.": "Navegação dos caminhos de certificação BREEAM, LEED e WELL. Alcançámos o Platina nos nossos últimos seis projetos e não aceitamos menos.",
    "our in-house lab tests emerging bio-based materials — algae panels, fungal insulation, mycelium composites — before they reach the mainstream.": "O nosso laboratório interno testa materiais bio-base emergentes — painéis de algas, isolamento fúngico, compósitos de micélio — antes de chegarem ao mercado.",
    "ready to build": "Pronto para construir",
    "structural bamboo arches span 24 metres, creating a community hub that withstands typhoon-force winds and remains fully biodegradable at end of life.": "Arcos de bambu estruturais abrangem 24 metros, criando um centro comunitário que resiste a ventos de força de tufão e permanece totalmente biodegradável no final da vida útil.",
    "sustainable building of the year": "Edifício Sustentável do Ano",
    "sustainable design studio of the year": "Atelier de conceção sustentável do ano",
    "tells a story.": "conta uma história.",
    "the glass house": "A Casa de Vidro",
    "the matter.": "da matéria.",
    "the minds behind": "As mentes por trás",
    "the studio in numbers": "O atelier em números",
    "view all projects →": "Ver todos os projetos →",
  },
};
