/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "enter property": "Entrer dans le bien",
    "portfolio_manifesto": "Notre_manifeste",
    "spatial protocol": "Protocole spatial",
    "neural": "Rendu",
    "rendering.": "neuronal.",
    "lidar precision": "Précision LiDAR",
    "military-grade sensors capturing every architectural nuance.": "Des capteurs de qualité militaire qui saisissent chaque nuance architecturale.",
    "polygon count": "Nombre de polygones",
    "stream latency": "Latence de diffusion",
    "buffer load": "Charge du tampon",
    "properties": "Biens",
    "scanned.": "numérisés.",
    "spatial_anatomy": "Anatomie_spatiale",
    "book your": "Réserver votre",
    "digitizing the physical world into volumetric data streams. built for the next era of luxury real estate.": "Numériser le monde physique en flux de données volumétriques. Conçu pour la prochaine ère de l'immobilier de prestige.",
    "instant response on any device, from vr to mobile.": "Réponse instantanée sur tout appareil, du casque au téléphone.",
    "our proprietary engine digitizes physical assets into interactive volumetric twins with sub-millimeter precision.": "Notre moteur propriétaire numérise les actifs physiques en jumeaux volumétriques interactifs avec une précision sub-millimétrique.",
    "plan.": "Plan.",
    "secure access": "Accès Sécurisé",
    "space as data": "Espace en tant que données",
    "start scan": "DÉMARRER L'ANALYSE",
    "sub-millimeter lidar scanning and neural radiance fields for immersive real estate experiences at the speed of thought.": "Numérisation LiDAR sub-millimétrique et champs de radiance neuronaux pour des expériences immobilières immersives à la vitesse de la pensée.",
    "the engine": "Le Moteur",
    "the knightsbridge": "Le Knightsbridge",
    "the obsidian atrium": "L'Atrium Obsidien",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "enter property": "Entrar en el inmueble",
    "portfolio_manifesto": "Nuestro_manifiesto",
    "spatial protocol": "Protocolo espacial",
    "neural": "Renderizado",
    "rendering.": "neuronal.",
    "lidar precision": "Precisión LiDAR",
    "military-grade sensors capturing every architectural nuance.": "Sensores de grado militar que captan cada matiz arquitectónico.",
    "polygon count": "Número de polígonos",
    "stream latency": "Latencia de transmisión",
    "buffer load": "Carga del búfer",
    "properties": "Inmuebles",
    "scanned.": "escaneados.",
    "spatial_anatomy": "Anatomía_espacial",
    "book your": "Reserve su",
    "digitizing the physical world into volumetric data streams. built for the next era of luxury real estate.": "Digitalizar el mundo físico en flujos de datos volumétricos. Pensado para la próxima era del inmobiliario de lujo.",
    "instant response on any device, from vr to mobile.": "Respuesta instantánea en cualquier dispositivo, de las gafas al móvil.",
    "our proprietary engine digitizes physical assets into interactive volumetric twins with sub-millimeter precision.": "Nuestro motor propietario digitaliza activos físicos en gemelos volumétricos interactivos con precisión submilimétrica.",
    "plan.": "Plan.",
    "secure access": "Acceso Seguro",
    "space as data": "Espacio como datos",
    "start scan": "INICIAR ESCANEO",
    "sub-millimeter lidar scanning and neural radiance fields for immersive real estate experiences at the speed of thought.": "Escaneo LiDAR submilimétrico y campos de radiancia neuronal para experiencias inmobiliarias inmersivas a la velocidad del pensamiento.",
    "the engine": "El Motor",
    "the knightsbridge": "El Knightsbridge",
    "the obsidian atrium": "El Atrio Obsidiana",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "enter property": "Immobilie betreten",
    "portfolio_manifesto": "Unser_Manifest",
    "spatial protocol": "Raumprotokoll",
    "neural": "Neuronales",
    "rendering.": "Rendering.",
    "lidar precision": "LiDAR-Präzision",
    "military-grade sensors capturing every architectural nuance.": "Sensoren in Militärqualität, die jede architektonische Nuance erfassen.",
    "polygon count": "Polygonanzahl",
    "stream latency": "Streaming-Latenz",
    "buffer load": "Pufferauslastung",
    "properties": "Immobilien",
    "scanned.": "gescannt.",
    "spatial_anatomy": "Raum_Anatomie",
    "book your": "Buchen Sie Ihren",
    "digitizing the physical world into volumetric data streams. built for the next era of luxury real estate.": "Die physische Welt in volumetrische Datenströme überführen. Gebaut für die nächste Ära der Luxusimmobilie.",
    "instant response on any device, from vr to mobile.": "Sofortige Reaktion auf jedem Gerät, von der Brille bis zum Handy.",
    "our proprietary engine digitizes physical assets into interactive volumetric twins with sub-millimeter precision.": "Unsere proprietäre Engine digitalisiert physische Vermögenswerte in interaktive volumetrische Zwillinge mit sub-millimeter Präzision.",
    "plan.": "Plan.",
    "secure access": "Sicherer Zugang",
    "space as data": "Raum als Daten",
    "start scan": "SCAN STARTEN",
    "sub-millimeter lidar scanning and neural radiance fields for immersive real estate experiences at the speed of thought.": "Sub-millimeter LiDAR-Scanning und neuronale Strahlungsfelder für immersive Immobilienerlebnisse in Gedanken.",
    "the engine": "Der Motor",
    "the knightsbridge": "Das Knightsbridge",
    "the obsidian atrium": "Das Obsidian-Atrium",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "enter property": "Entrar no imóvel",
    "portfolio_manifesto": "O_nosso_manifesto",
    "spatial protocol": "Protocolo espacial",
    "neural": "Renderização",
    "rendering.": "neuronal.",
    "lidar precision": "Precisão LiDAR",
    "military-grade sensors capturing every architectural nuance.": "Sensores de grau militar que captam cada nuance arquitetónica.",
    "polygon count": "Número de polígonos",
    "stream latency": "Latência de transmissão",
    "buffer load": "Carga do buffer",
    "properties": "Imóveis",
    "scanned.": "digitalizados.",
    "spatial_anatomy": "Anatomia_espacial",
    "book your": "Reserve o seu",
    "digitizing the physical world into volumetric data streams. built for the next era of luxury real estate.": "Digitalizar o mundo físico em fluxos de dados volumétricos. Pensado para a próxima era do imobiliário de luxo.",
    "instant response on any device, from vr to mobile.": "Resposta instantânea em qualquer dispositivo, dos óculos ao telemóvel.",
    "our proprietary engine digitizes physical assets into interactive volumetric twins with sub-millimeter precision.": "O nosso motor proprietário digitaliza ativos físicos em gêmeos volumétricos interativos com precisão submilimétrica.",
    "plan.": "Plano.",
    "secure access": "Acesso Seguro",
    "space as data": "Espaço como dados",
    "start scan": "INICIAR ANÁLISE",
    "sub-millimeter lidar scanning and neural radiance fields for immersive real estate experiences at the speed of thought.": "Digitalização LiDAR submilimétrica e campos de radiação neural para experiências imobiliárias imersivas à velocidade do pensamento.",
    "the engine": "O Motor",
    "the knightsbridge": "O Knightsbridge",
    "the obsidian atrium": "O Átrio Obsidiana",
  },
};
