/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "components per watch": "Composants par montre",
    "download technical deck": "Télécharger le dossier technique",
    "every bridge is beveled by hand and every gear is polished to a mirror finish in our swiss workshops.": "Chaque pont est anglé à la main et chaque rouage poli au miroir dans nos ateliers suisses.",
    "global time": "Temps Global",
    "heritage years": "Années d'héritage",
    "hours of testing": "Heures de test",
    "in gold.": "En or.",
    "our legacy": "Notre Héritage",
    "our proprietary gold and titanium alloys are engineered for eternal luster and scratch resistance.": "Nos alliages d'or et de titane sont conçus pour un éclat sans fin et une grande résistance aux rayures.",
    "rose gold moonphase calendar that requires no adjustment for the next 122 years.": "Calendrier de phase de lune en or rose qui ne nécessite aucun réglage pendant les 122 prochaines années.",
    "since 1899": "Depuis 1899",
    "testing standards that exceed cosc certification by 300% for absolute timekeeping integrity.": "Normes de test qui dépassent la certification COSC de 300 % pour une intégrité de chronométrage absolue.",
    "the absolute mechanical mastery of time. engineered for the next millennium in our le locle sanctuary.": "La maîtrise mécanique absolue du temps. Conçue pour le millénaire à venir, dans notre sanctuaire du Locle.",
    "the absolute mechanical mastery of time. engineered for the next millennium.": "La maîtrise mécanique absolue du temps. Conçu pour le prochain millénaire.",
    "the masterpiece archive": "L'archive des pièces maîtresses",
    "the philosophy": "La philosophie",
    "titanium grade 5 case, water-resistant to 1000m with a helium escape valve and ceramic bezel.": "Boîtier en titane grade 5, résistant à l'eau jusqu'à 1000m avec une valve d'échappement pour l'hélium et une lunette en céramique.",
    "we don't sell watches. we sell the mastery over the fourth dimension. a zenith is a perpetual heartbeat on your wrist.": "Nous ne vendons pas de montres. Nous vendons la maîtrise de la quatrième dimension. Un Zenith est un battement de cœur perpétuel à votre poignet.",
  },
  es: {
    "components per watch": "Componentes por reloj",
    "download technical deck": "Descargar el documento técnico",
    "every bridge is beveled by hand and every gear is polished to a mirror finish in our swiss workshops.": "Cada puente se bisela a mano y cada engranaje se pule a espejo en nuestros talleres suizos.",
    "global time": "Tiempo Global",
    "heritage years": "Años de herencia",
    "hours of testing": "Horas de prueba",
    "in gold.": "En oro.",
    "our legacy": "Nuestro Legado",
    "our proprietary gold and titanium alloys are engineered for eternal luster and scratch resistance.": "Nuestras aleaciones de oro y titanio están concebidas para un brillo sin fin y una gran resistencia a los arañazos.",
    "rose gold moonphase calendar that requires no adjustment for the next 122 years.": "Calendario de fase lunar en oro rosa que no requiere ajustes durante los próximos 122 años.",
    "since 1899": "Desde 1899",
    "testing standards that exceed cosc certification by 300% for absolute timekeeping integrity.": "Normas de prueba que superan la certificación COSC en un 300 % para una integridad absoluta en la medición del tiempo.",
    "the absolute mechanical mastery of time. engineered for the next millennium in our le locle sanctuary.": "El dominio mecánico absoluto del tiempo. Concebido para el milenio venidero, en nuestro santuario de Le Locle.",
    "the absolute mechanical mastery of time. engineered for the next millennium.": "El dominio mecánico absoluto del tiempo. Diseñado para el próximo milenio.",
    "the masterpiece archive": "El archivo de las obras maestras",
    "the philosophy": "La filosofía",
    "titanium grade 5 case, water-resistant to 1000m with a helium escape valve and ceramic bezel.": "Caja de titanio de grado 5, resistente al agua hasta 1000m con una válvula de escape de helio y bisel de cerámica.",
    "we don't sell watches. we sell the mastery over the fourth dimension. a zenith is a perpetual heartbeat on your wrist.": "No vendemos relojes. Vendemos el dominio sobre la cuarta dimensión. Un Zenith es un latido perpetuo en tu muñeca.",
  },
  de: {
    "components per watch": "Komponenten pro Uhr",
    "download technical deck": "Technisches Deck herunterladen",
    "every bridge is beveled by hand and every gear is polished to a mirror finish in our swiss workshops.": "Jede Brücke wird von Hand angliert und jedes Zahnrad in unseren Schweizer Werkstätten spiegelblank poliert.",
    "global time": "Globale Zeit",
    "heritage years": "Erbe Jahre",
    "hours of testing": "Stunden der Prüfung",
    "in gold.": "In Gold.",
    "our legacy": "Unser Erbe",
    "our proprietary gold and titanium alloys are engineered for eternal luster and scratch resistance.": "Unsere Gold- und Titanlegierungen sind auf ewigen Glanz und hohe Kratzfestigkeit ausgelegt.",
    "rose gold moonphase calendar that requires no adjustment for the next 122 years.": "Mondphasen-Kalender aus Roségold, der in den nächsten 122 Jahren keine Anpassung benötigt.",
    "since 1899": "Seit 1899",
    "testing standards that exceed cosc certification by 300% for absolute timekeeping integrity.": "Teststandards, die die COSC-Zertifizierung um 300 % übertreffen, um absolute Zeitgenauigkeit zu gewährleisten.",
    "the absolute mechanical mastery of time. engineered for the next millennium in our le locle sanctuary.": "Die absolute mechanische Beherrschung der Zeit. Für das kommende Jahrtausend gebaut, in unserem Refugium in Le Locle.",
    "the absolute mechanical mastery of time. engineered for the next millennium.": "Die absolute mechanische Beherrschung der Zeit. Für das nächste Jahrtausend entwickelt.",
    "the masterpiece archive": "Das Archiv der Meisterstücke",
    "the philosophy": "Die Philosophie",
    "titanium grade 5 case, water-resistant to 1000m with a helium escape valve and ceramic bezel.": "Gehäuse aus Titan der Klasse 5, wasserdicht bis 1000m mit einem Heliumauslassventil und einer Keramiklünette.",
    "we don't sell watches. we sell the mastery over the fourth dimension. a zenith is a perpetual heartbeat on your wrist.": "Wir verkaufen keine Uhren. Wir verkaufen die Beherrschung der vierten Dimension. Ein Zenith ist ein ewiger Herzschlag an Ihrem Handgelenk.",
  },
  pt: {
    "components per watch": "Componentes por relógio",
    "download technical deck": "Baixar o documento técnico",
    "every bridge is beveled by hand and every gear is polished to a mirror finish in our swiss workshops.": "Cada ponte é chanfrada à mão e cada roda dentada polida a espelho nas nossas oficinas suíças.",
    "global time": "Tempo Global",
    "heritage years": "Anos de herança",
    "hours of testing": "Horas de teste",
    "in gold.": "Em ouro.",
    "our legacy": "O Nosso Legado",
    "our proprietary gold and titanium alloys are engineered for eternal luster and scratch resistance.": "As nossas ligas de ouro e titânio são concebidas para um brilho sem fim e uma grande resistência aos riscos.",
    "rose gold moonphase calendar that requires no adjustment for the next 122 years.": "Calendário de fase lunar em ouro rosa que não requer ajustes nos próximos 122 anos.",
    "since 1899": "Desde 1899",
    "testing standards that exceed cosc certification by 300% for absolute timekeeping integrity.": "Normas de teste que superam a certificação COSC em 300% para uma integridade absoluta na medição do tempo.",
    "the absolute mechanical mastery of time. engineered for the next millennium in our le locle sanctuary.": "O domínio mecânico absoluto do tempo. Concebido para o milénio vindouro, no nosso santuário de Le Locle.",
    "the absolute mechanical mastery of time. engineered for the next millennium.": "A maestria mecânica absoluta do tempo. Projetado para o próximo milénio.",
    "the masterpiece archive": "O arquivo das obras-primas",
    "the philosophy": "A filosofia",
    "titanium grade 5 case, water-resistant to 1000m with a helium escape valve and ceramic bezel.": "Caixa de titânio grau 5, resistente à água até 1000m com uma válvula de escape de hélio e bisel de cerâmica.",
    "we don't sell watches. we sell the mastery over the fourth dimension. a zenith is a perpetual heartbeat on your wrist.": "Não vendemos relógios. Vendemos a maestria sobre a quarta dimensão. Um Zenith é um batimento cardíaco perpétuo no seu pulso.",
  },
};
