/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Nous sommes une agence créative qui relie le design d'exception à l'ingénierie de haut niveau. Nous accompagnons les visionnaires dans leurs expériences numériques.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Réflexions, méthodes et stratégies de l'équipe sur le design, l'ingénierie et la croissance numérique.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Au-delà du référencement, la vitesse de chargement façonne la perception de votre marque et la conversion de votre site.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Un système de design bien construit n'est pas un luxe d'agence : c'est l'outil qui aligne design et développement et raccourcit vos délais.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Nous couvrons le numérique de bout en bout : conseil stratégique, identité de marque, développement full-stack et motion design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Toutes les photographies de ce site sont la propriété exclusive du studio Elena Korr, sauf mention contraire. Unsplash fournit les images de démonstration.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Ce portfolio a été conçu et développé avec précision, avec Next.js, Tailwind CSS et Framer Motion, pour une expérience fluide et cinématographique.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Nous utilisons des polices modernes et lisibles, choisies pour équilibrer élégance et lisibilité, à l'image de l'esthétique du studio.",
    "the weight of light at dusk": "Le poids de la lumière au crépuscule",
    "behind the scenes": "Dans les coulisses",
    "behind the lens: maison lumière": "Derrière l'objectif : Maison Lumière",
    "finding geometry in the sahara": "Trouver la géométrie au Sahara",
    "the philosophy of slow fashion": "La philosophie de la mode lente",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Homard bleu de Bretagne entier, sauce thermidor au corail, gratin dauphinois, jeunes pousses de saison",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Carré d'agneau en croûte d'herbes, jus à la provençale, cassoulet de flageolets, ris d'agneau",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Soufflé classique au chocolat noir Valrhona 70 %, crème anglaise à la vanille, zestes d'orange confits",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Bourgogne, France · 2022 — Minéral, silex, fruits blancs à noyau",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Bordeaux, France · 2015 — Truffe, prune noire, fer — le sommet",
    "visual storyteller": "Raconteuse d'images",
    "awards": "Distinctions",
    "selected": "Sélection",
    "photography": "Photographie",
    "street": "Rue",
    "fashion": "Mode",
    "landscape": "Paysage",
    "capabilities": "Savoir-faire",
    "creative": "Création",
    "editorial photography": "Photographie éditoriale",
    "art direction": "Direction artistique",
    "commercial": "Publicité",
    "portraiture": "Portrait",
    "based between": "Installée entre",
    "methodology": "Méthode",
    "brands & agencies": "marques et agences",
    "creative director, vogue": "Directrice de création, Vogue",
    "founder, thorne architecture": "Fondateur, Thorne Architecture",
    "recognition": "Reconnaissance",
    "honors": "Distinctions",
    "fine art": "Art contemporain",
    "credits": "Crédits",
    "profoto lighting": "Éclairage Profoto",
    "analog 35mm": "Argentique 35 mm",
    "and tokyo, i specialize in capturing moments that transcend the ordinary. my work has been featured in national geographic, vogue, and bbc earth — but the images i am most proud of are the ones that make strangers feel something they cannot quite name.": "et Tokyo, je photographie ce qui dépasse l'ordinaire. Mon travail a paru dans National Geographic, Vogue et BBC Earth — mais les images dont je suis le plus fier sont celles qui font ressentir à un inconnu quelque chose qu'il ne sait pas nommer.",
    "with a background in fine arts from école des beaux-arts, i bring a deeply personal yet universally resonant perspective. whether documenting street life in shinjuku or creating haute couture editorials, i seek the same truth wrapped in beauty.": "Formé aux beaux-arts, j'apporte un regard intime qui parle pourtant à tout le monde. Reportage de rue à Shinjuku ou éditorial de haute couture : je cherche la même vérité, enveloppée de beauté.",
    "we begin by understanding your vision, target audience, and the core message. we develop moodboards, lighting plans, and a comprehensive shoot strategy to ensure alignment.": "Nous commençons par comprendre votre intention, le public visé et le message. Viennent ensuite les planches d'ambiance, les plans de lumière et la stratégie de prise de vue, pour que tout le monde vise la même chose.",
    "yes. while based between paris and tokyo, i frequently travel globally for campaigns and editorial assignments. travel fees are calculated based on the project scope.": "Oui. Basé entre Paris et Tokyo, je me déplace régulièrement dans le monde entier pour des campagnes et des commandes éditoriales. Les frais de déplacement se calculent selon l'ampleur du projet.",
    "a minimalist approach to the sahara. using harsh midday light to create striking geometric compositions out of shifting dunes.": "Une approche minimaliste du Sahara. Utilisant la lumière dure de midi pour créer des compositions géométriques frappantes à partir de dunes mouvantes.",
    "a nocturnal exploration of shinjuku's electric veins — where neon bleeds into rain-slicked asphalt and human stories unfold in 1/125th of a second.": "Une exploration nocturne des veines électriques de Shinjuku — où le néon se mêle à l'asphalte mouillé par la pluie et où les histoires humaines se déroulent en 1/125ème de seconde.",
    "about the artist": "À propos de l'artiste",
    "an intimate portrait series celebrating the raw beauty of the human form — unretouched, unfiltered, unapologetically real.": "Une série de portraits intimes célébrant la beauté brute de la forme humaine — non retouchée, non filtrée, sans excuses.",
    "are you available for international travel?": "Êtes-vous disponible pour des voyages internationaux ?",
    "available for commissions, editorial work, and creative collaborations worldwide. bookings open for q4 2026.": "Disponible pour des commandes, des travaux éditoriaux et des collaborations partout dans le monde. Réservations ouvertes pour le dernier trimestre 2026.",
    "brutalist structures reimagined as sculptural poems. exploring the tension between mass and void in post-war european architecture.": "Structures brutalistes réimaginées en poèmes sculpturaux. Exploration de la tension entre la masse et le vide dans l'architecture européenne d'après-guerre.",
    "capturing the ephemeral dance between sky and sea along the icelandic coastline. a study in vastness, silence, and the weight of light at dusk.": "Capturer la danse éphémère entre le ciel et la mer le long de la côte islandaise. Une étude sur l'immensité, le silence et le poids de la lumière au crépuscule.",
    "capturing the world through a lens of emotion, light, and uncompromising beauty. cinematic photography for global brands.": "Capturer le monde à travers un objectif d'émotion, de lumière et de beauté sans compromis. Photographie cinématographique pour des marques mondiales.",
    "client": "Client",
    "comprehensive visual strategy from concept to final execution, ensuring cohesive brand identity.": "Stratégie visuelle complète, de la conception à l'exécution finale, garantissant une identité de marque cohérente.",
    "dates are secured upon signature of the contract and receipt of a 50% retainer. given my travel schedule, i recommend booking at least 2-3 months in advance.": "Les dates sont sécurisées dès la signature du contrat et la réception d'un acompte de 50 %. Étant donné mon emploi du temps de voyage, je recommande de réserver au moins 2 à 3 mois à l'avance.",
    "delivering uncompromising quality across multiple disciplines. each project is approached with the same cinematic eye and obsessive attention to detail.": "Offrir une qualité sans compromis dans plusieurs disciplines. Chaque projet est abordé avec le même œil cinématographique et une attention obsessionnelle aux détails.",
    "do you handle full production?": "Gérez-vous la production complète ?",
    "elena doesn't just take photographs; she crafts cinematic narratives. her ability to command light and direct talent is unparalleled in the industry today.": "Elena ne se contente pas de prendre des photographies ; elle crée des récits cinématographiques. Sa capacité à maîtriser la lumière et à diriger les talents est sans égal dans l'industrie aujourd'hui.",
    "executing the vision with precision. using state-of-the-art medium format cameras and lighting setups to capture high-fidelity imagery on set or on location.": "Exécutant la vision avec précision. Utilisant des appareils photo moyen format à la pointe de la technologie et des configurations d'éclairage pour capturer des images haute fidélité sur le plateau ou en extérieur.",
    "fine art and commercial photography studio operating globally. crafting timeless visual narratives for visionaries.": "Studio de photographie d'art et commerciale opérant à l'échelle mondiale. Création de récits visuels intemporels pour les visionnaires.",
    "frames of light": "cadres de lumière",
    "high-end fashion and lifestyle imagery for magazines and global campaigns. focused on narrative-driven compositions that elevate brand storytelling.": "Des images de mode et de style de vie haut de gamme pour des magazines et des campagnes mondiales. Axé sur des compositions narratives qui élèvent le storytelling de la marque.",
    "how do we secure booking dates?": "Comment sécuriser les dates de réservation ?",
    "i see the world in": "Je vois le monde en",
    "intimate, character-driven portraits for artists, executives, and public figures seeking authentic representation.": "Portraits intimes et axés sur le caractère pour artistes, dirigeants et figures publiques cherchant une représentation authentique.",
    "let's shoot.": "Photographions ensemble.",
    "meticulous color grading, compositing, and high-end retouching to polish the final assets, delivered in all necessary formats for print and digital.": "Étalonnage minutieux, composition et retouche haut de gamme pour peaufiner les actifs finaux, livrés dans tous les formats nécessaires pour l'impression et le numérique.",
    "more from this series": "Plus de cette série",
    "product and brand photography designed to convert, crafted with meticulous attention to lighting and detail.": "Photographie de produits et de marques conçue pour convertir, réalisée avec une attention méticuleuse à l'éclairage et aux détails.",
    "return to gallery": "Retour à la galerie",
    "securing locations, assembling the creative team (stylists, mua, set designers), casting talent, and finalizing the call sheet for a seamless shoot day.": "Sécuriser les lieux, assembler l'équipe créative (stylistes, MUA, décorateurs), sélectionner les talents et finaliser la feuille de service pour une journée de tournage sans accroc.",
    "she captured our brutalist structures with a sensitivity we didn't know was possible. the resulting images completely redefined our portfolio presentation.": "Elle a capturé nos structures brutalistes avec une sensibilité que nous ne savions pas possible. Les images résultantes ont complètement redéfini notre présentation de portfolio.",
    "subscribe for studio updates, print releases, and travel dates.": "Abonnez-vous pour les nouvelles de l'atelier, les sorties de tirages et les dates de voyage.",
    "the aftermath of eruption — where destruction creates a canvas more beautiful than any human could conceive. shot over three expeditions.": "Les conséquences de l'éruption — où la destruction crée une toile plus belle que tout ce qu'un humain pourrait concevoir. Tourné lors de trois expéditions.",
    "the chaos of new york city distilled into frozen moments. a monochrome series focusing on the isolation within the crowd.": "Le chaos de New York réduit à des moments figés. Une série monochrome axée sur l'isolement au sein de la foule.",
    "the shoot": "La Tournée",
    "trusted by visionary": "Fidèle aux visionnaires",
    "what camera systems do you use?": "Quels systèmes de caméra utilisez-vous ?",
    "what is your typical turnaround time?": "Quel est votre délai de réponse habituel ?",
    "working with elena elevated our campaign to fine art. her pre-production planning is exhaustive, and her execution on set is flawlessly calm and decisive.": "Travailler avec Elena a élevé notre campagne à l'art. Sa planification en pré-production est exhaustive, et son exécution sur le plateau est d'un calme et d'une détermination impeccables.",
    "years": "Années",
    "yes. while based between": "Oui. Tout en étant basé entre",
  },
  es: {
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Somos una agencia creativa que une el diseño excepcional a la ingeniería de alto nivel. Acompañamos a los visionarios en sus experiencias digitales.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Reflexiones, métodos y estrategias del equipo sobre diseño, ingeniería y crecimiento digital.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Más allá del SEO, la velocidad de carga moldea la percepción de su marca y la conversión de su sitio.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Un sistema de diseño bien construido no es un lujo de agencia: es la herramienta que alinea diseño y desarrollo y acorta sus plazos.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Cubrimos lo digital de principio a fin: consultoría estratégica, identidad de marca, desarrollo full-stack y motion design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Todas las fotografías de este sitio son propiedad exclusiva del estudio Elena Korr, salvo mención contraria. Unsplash aporta las imágenes de muestra.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Este portafolio fue diseñado y desarrollado con precisión, con Next.js, Tailwind CSS y Framer Motion, para una experiencia fluida y cinematográfica.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Usamos tipografías modernas y legibles, elegidas para equilibrar elegancia y legibilidad, a imagen de la estética del estudio.",
    "the weight of light at dusk": "El peso de la luz al atardecer",
    "behind the scenes": "Entre bastidores",
    "behind the lens: maison lumière": "Detrás del objetivo: Maison Lumière",
    "finding geometry in the sahara": "Encontrar la geometría en el Sáhara",
    "the philosophy of slow fashion": "La filosofía de la moda lenta",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Bogavante azul de Bretaña entero, salsa thermidor al coral, gratén delfinés, brotes de temporada",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Costillar de cordero en costra de hierbas, jugo a la provenzal, cassoulet de judías, mollejas de cordero",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Suflé clásico de chocolate negro Valrhona 70 %, crema inglesa de vainilla, ralladura de naranja confitada",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Borgoña, Francia · 2022 — Mineral, sílex, fruta blanca de hueso",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Burdeos, Francia · 2015 — Trufa, ciruela negra, hierro — la cumbre",
    "visual storyteller": "Narradora visual",
    "awards": "Premios",
    "selected": "Selección",
    "photography": "Fotografía",
    "street": "Calle",
    "fashion": "Moda",
    "landscape": "Paisaje",
    "capabilities": "Competencias",
    "creative": "Creación",
    "editorial photography": "Fotografía editorial",
    "art direction": "Dirección de arte",
    "commercial": "Publicidad",
    "portraiture": "Retrato",
    "based between": "Afincada entre",
    "methodology": "Metodología",
    "brands & agencies": "marcas y agencias",
    "creative director, vogue": "Directora creativa, Vogue",
    "founder, thorne architecture": "Fundador, Thorne Architecture",
    "recognition": "Reconocimiento",
    "honors": "Galardones",
    "fine art": "Arte contemporáneo",
    "credits": "Créditos",
    "profoto lighting": "Iluminación Profoto",
    "analog 35mm": "Analógico 35 mm",
    "and tokyo, i specialize in capturing moments that transcend the ordinary. my work has been featured in national geographic, vogue, and bbc earth — but the images i am most proud of are the ones that make strangers feel something they cannot quite name.": "y Tokio, fotografío lo que supera lo ordinario. Mi trabajo ha aparecido en National Geographic, Vogue y BBC Earth — pero las imágenes de las que más me enorgullezco son las que hacen sentir a un desconocido algo que no sabe nombrar.",
    "with a background in fine arts from école des beaux-arts, i bring a deeply personal yet universally resonant perspective. whether documenting street life in shinjuku or creating haute couture editorials, i seek the same truth wrapped in beauty.": "Formado en bellas artes, aporto una mirada íntima que, sin embargo, habla a todos. Reportaje callejero en Shinjuku o editorial de alta costura: busco la misma verdad, envuelta en belleza.",
    "we begin by understanding your vision, target audience, and the core message. we develop moodboards, lighting plans, and a comprehensive shoot strategy to ensure alignment.": "Empezamos por entender su intención, el público al que se dirige y el mensaje. Luego llegan los moodboards, los planes de luz y la estrategia de rodaje, para que todos apunten a lo mismo.",
    "yes. while based between paris and tokyo, i frequently travel globally for campaigns and editorial assignments. travel fees are calculated based on the project scope.": "Sí. Con base entre París y Tokio, viajo con regularidad por todo el mundo para campañas y encargos editoriales. Los gastos de viaje se calculan según el alcance del proyecto.",
    "a minimalist approach to the sahara. using harsh midday light to create striking geometric compositions out of shifting dunes.": "Un enfoque minimalista del Sahara. Usando la dura luz del mediodía para crear composiciones geométricas impactantes a partir de dunas en movimiento.",
    "a nocturnal exploration of shinjuku's electric veins — where neon bleeds into rain-slicked asphalt and human stories unfold in 1/125th of a second.": "Una exploración nocturna de las venas eléctricas de Shinjuku — donde el neón se mezcla con el asfalto mojado por la lluvia y las historias humanas se despliegan en 1/125 de segundo.",
    "about the artist": "Sobre el artista",
    "an intimate portrait series celebrating the raw beauty of the human form — unretouched, unfiltered, unapologetically real.": "Una serie de retratos íntimos que celebran la belleza cruda de la forma humana — sin retoques, sin filtros, sin disculpas.",
    "are you available for international travel?": "¿Está disponible para viajar internacionalmente?",
    "available for commissions, editorial work, and creative collaborations worldwide. bookings open for q4 2026.": "Disponible para encargos, trabajos editoriales y colaboraciones en todo el mundo. Reservas abiertas para el último trimestre de 2026.",
    "brutalist structures reimagined as sculptural poems. exploring the tension between mass and void in post-war european architecture.": "Estructuras brutalistas reimaginadas como poemas escultóricos. Explorando la tensión entre masa y vacío en la arquitectura europea de posguerra.",
    "capturing the ephemeral dance between sky and sea along the icelandic coastline. a study in vastness, silence, and the weight of light at dusk.": "Capturando la danza efímera entre el cielo y el mar a lo largo de la costa islandesa. Un estudio en vastedad, silencio y el peso de la luz al anochecer.",
    "capturing the world through a lens of emotion, light, and uncompromising beauty. cinematic photography for global brands.": "Capturando el mundo a través de un lente de emoción, luz y belleza sin compromisos. Fotografía cinematográfica para marcas globales.",
    "client": "Cliente",
    "comprehensive visual strategy from concept to final execution, ensuring cohesive brand identity.": "Estrategia visual integral desde el concepto hasta la ejecución final, asegurando una identidad de marca cohesiva.",
    "dates are secured upon signature of the contract and receipt of a 50% retainer. given my travel schedule, i recommend booking at least 2-3 months in advance.": "Las fechas se aseguran al firmar el contrato y recibir un anticipo del 50%. Dado mi horario de viaje, recomiendo reservar con al menos 2-3 meses de anticipación.",
    "delivering uncompromising quality across multiple disciplines. each project is approached with the same cinematic eye and obsessive attention to detail.": "Ofreciendo calidad intransigente en múltiples disciplinas. Cada proyecto se aborda con el mismo ojo cinematográfico y una atención obsesiva al detalle.",
    "do you handle full production?": "¿Maneja la producción completa?",
    "elena doesn't just take photographs; she crafts cinematic narratives. her ability to command light and direct talent is unparalleled in the industry today.": "Elena no solo toma fotografías; crea narrativas cinematográficas. Su capacidad para dominar la luz y dirigir el talento es inigualable en la industria actual.",
    "executing the vision with precision. using state-of-the-art medium format cameras and lighting setups to capture high-fidelity imagery on set or on location.": "Ejecutando la visión con precisión. Usando cámaras de formato medio de última generación y configuraciones de iluminación para capturar imágenes de alta fidelidad en el set o en locaciones.",
    "fine art and commercial photography studio operating globally. crafting timeless visual narratives for visionaries.": "Estudio de fotografía de arte y comercial que opera a nivel mundial. Creando narrativas visuales atemporales para visionarios.",
    "frames of light": "marcos de luz",
    "high-end fashion and lifestyle imagery for magazines and global campaigns. focused on narrative-driven compositions that elevate brand storytelling.": "Imágenes de moda y estilo de vida de alta gama para revistas y campañas globales. Enfocado en composiciones impulsadas por narrativas que elevan la narración de la marca.",
    "how do we secure booking dates?": "¿Cómo aseguramos las fechas de reserva?",
    "i see the world in": "Veo el mundo en",
    "intimate, character-driven portraits for artists, executives, and public figures seeking authentic representation.": "Retratos íntimos y centrados en el carácter para artistas, ejecutivos y figuras públicas que buscan una representación auténtica.",
    "let's shoot.": "Vamos a disparar.",
    "meticulous color grading, compositing, and high-end retouching to polish the final assets, delivered in all necessary formats for print and digital.": "Calibración de color meticulosa, composición y retoque de alta gama para pulir los activos finales, entregados en todos los formatos necesarios para impresión y digital.",
    "more from this series": "Más de esta serie",
    "product and brand photography designed to convert, crafted with meticulous attention to lighting and detail.": "Fotografía de productos y marcas diseñada para convertir, elaborada con meticulosa atención a la iluminación y los detalles.",
    "return to gallery": "Volver a la galería",
    "securing locations, assembling the creative team (stylists, mua, set designers), casting talent, and finalizing the call sheet for a seamless shoot day.": "Asegurando locaciones, ensamblando el equipo creativo (estilistas, MUA, diseñadores de sets), seleccionando talento y finalizando la hoja de llamada para un día de rodaje sin problemas.",
    "she captured our brutalist structures with a sensitivity we didn't know was possible. the resulting images completely redefined our portfolio presentation.": "Capturó nuestras estructuras brutalistas con una sensibilidad que no sabíamos que era posible. Las imágenes resultantes redefinieron completamente nuestra presentación de portafolio.",
    "subscribe for studio updates, print releases, and travel dates.": "Suscríbase para recibir novedades del estudio, salidas de copias y fechas de viaje.",
    "the aftermath of eruption — where destruction creates a canvas more beautiful than any human could conceive. shot over three expeditions.": "Las secuelas de la erupción — donde la destrucción crea un lienzo más hermoso de lo que cualquier humano podría concebir. Filmado en tres expediciones.",
    "the chaos of new york city distilled into frozen moments. a monochrome series focusing on the isolation within the crowd.": "El caos de la ciudad de Nueva York destilado en momentos congelados. Una serie en monocromo centrada en la soledad dentro de la multitud.",
    "the shoot": "La Toma",
    "trusted by visionary": "Confiado por visionarios",
    "what camera systems do you use?": "¿Qué sistemas de cámara utiliza?",
    "what is your typical turnaround time?": "¿Cuál es su tiempo de respuesta típico?",
    "working with elena elevated our campaign to fine art. her pre-production planning is exhaustive, and her execution on set is flawlessly calm and decisive.": "Trabajar con Elena elevó nuestra campaña a una obra de arte. Su planificación de preproducción es exhaustiva y su ejecución en el set es impecablemente tranquila y decisiva.",
    "years": "Años",
    "yes. while based between": "Sí. Mientras estoy basado entre",
  },
  de: {
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Wir sind eine Kreativagentur, die außergewöhnliches Design mit erstklassiger Technik verbindet. Wir begleiten Visionäre bei digitalen Erlebnissen.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Gedanken, Methoden und Strategien des Teams zu Design, Technik und digitalem Wachstum.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Jenseits von SEO prägt die Ladegeschwindigkeit, wie Ihre Marke wahrgenommen wird und wie gut Ihre Seite konvertiert.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Ein gut gebautes Designsystem ist kein Agenturluxus: Es ist das Werkzeug, das Design und Entwicklung ausrichtet und Ihre Fristen verkürzt.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Wir decken Digitales von A bis Z ab: strategische Beratung, Markenidentität, Full-Stack-Entwicklung und Motion Design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Alle Fotografien dieser Website sind exklusives Eigentum des Studios Elena Korr, sofern nicht anders angegeben. Unsplash liefert die Platzhalterbilder.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Dieses Portfolio wurde mit Präzision gestaltet und entwickelt — mit Next.js, Tailwind CSS und Framer Motion für ein flüssiges, filmisches Erlebnis.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Wir verwenden moderne, gut lesbare Schriften, gewählt für die Balance aus Eleganz und Lesbarkeit, im Geist der Studioästhetik.",
    "the weight of light at dusk": "Das Gewicht des Lichts in der Dämmerung",
    "behind the scenes": "Hinter den Kulissen",
    "behind the lens: maison lumière": "Hinter der Linse: Maison Lumière",
    "finding geometry in the sahara": "Geometrie in der Sahara finden",
    "the philosophy of slow fashion": "Die Philosophie der Slow Fashion",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Ganzer bretonischer Hummer, Thermidor-Sauce mit Corail, Gratin dauphinois, Saisonkeimlinge",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Lammkarree in Kräuterkruste, provenzalischer Jus, Flageolet-Cassoulet, Lammbries",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Klassisches Soufflé mit Valrhona-Bitterschokolade 70 %, Vanille-Crème-anglaise, kandierte Orangenzesten",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Burgund, Frankreich · 2022 — Mineralisch, Feuerstein, weißes Steinobst",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Bordeaux, Frankreich · 2015 — Trüffel, dunkle Pflaume, Eisen — der Gipfel",
    "visual storyteller": "Bildautorin",
    "awards": "Auszeichnungen",
    "selected": "Auswahl",
    "photography": "Fotografie",
    "street": "Straße",
    "fashion": "Mode",
    "landscape": "Landschaft",
    "capabilities": "Leistungen",
    "creative": "Kreation",
    "editorial photography": "Editorial-Fotografie",
    "art direction": "Art Direction",
    "commercial": "Werbung",
    "portraiture": "Porträt",
    "based between": "Ansässig zwischen",
    "methodology": "Methodik",
    "brands & agencies": "Marken und Agenturen",
    "creative director, vogue": "Kreativdirektorin, Vogue",
    "founder, thorne architecture": "Gründer, Thorne Architecture",
    "recognition": "Anerkennung",
    "honors": "Auszeichnungen",
    "fine art": "Bildende Kunst",
    "credits": "Impressum",
    "profoto lighting": "Profoto-Licht",
    "analog 35mm": "Analog 35 mm",
    "and tokyo, i specialize in capturing moments that transcend the ordinary. my work has been featured in national geographic, vogue, and bbc earth — but the images i am most proud of are the ones that make strangers feel something they cannot quite name.": "und Tokio fotografiere ich, was über das Gewöhnliche hinausgeht. Meine Arbeiten erschienen in National Geographic, Vogue und BBC Earth — doch am meisten bedeuten mir die Bilder, die einem Fremden etwas fühlen lassen, das er nicht benennen kann.",
    "with a background in fine arts from école des beaux-arts, i bring a deeply personal yet universally resonant perspective. whether documenting street life in shinjuku or creating haute couture editorials, i seek the same truth wrapped in beauty.": "Ausgebildet an einer Kunsthochschule, bringe ich einen sehr persönlichen Blick mit, der dennoch alle erreicht. Straßenreportage in Shinjuku oder Haute-Couture-Strecke: Ich suche dieselbe Wahrheit, in Schönheit gehüllt.",
    "we begin by understanding your vision, target audience, and the core message. we develop moodboards, lighting plans, and a comprehensive shoot strategy to ensure alignment.": "Wir beginnen mit Ihrer Absicht, dem Publikum und der Botschaft. Danach folgen Moodboards, Lichtpläne und die Shooting-Strategie, damit alle dasselbe Ziel verfolgen.",
    "yes. while based between paris and tokyo, i frequently travel globally for campaigns and editorial assignments. travel fees are calculated based on the project scope.": "Ja. Mit Basis zwischen Paris und Tokio reise ich regelmäßig weltweit für Kampagnen und redaktionelle Aufträge. Die Reisekosten richten sich nach dem Umfang des Projekts.",
    "a minimalist approach to the sahara. using harsh midday light to create striking geometric compositions out of shifting dunes.": "Ein minimalistischer Ansatz für die Sahara. Mit harter Mittagsbeleuchtung, um auffällige geometrische Kompositionen aus sich verändernden Dünen zu schaffen.",
    "a nocturnal exploration of shinjuku's electric veins — where neon bleeds into rain-slicked asphalt and human stories unfold in 1/125th of a second.": "Eine nächtliche Erkundung der elektrischen Adern von Shinjuku — wo Neon in den regennassen Asphalt blutet und menschliche Geschichten in 1/125 Sekunde entfaltet werden.",
    "about the artist": "Über den Künstler",
    "an intimate portrait series celebrating the raw beauty of the human form — unretouched, unfiltered, unapologetically real.": "Eine intime Porträtserie, die die rohe Schönheit der menschlichen Form feiert — unretuschiert, ungefiltert, unverblümt echt.",
    "are you available for international travel?": "Sind Sie für internationale Reisen verfügbar?",
    "available for commissions, editorial work, and creative collaborations worldwide. bookings open for q4 2026.": "Verfügbar für Auftragsarbeiten, redaktionelle Arbeiten und Kooperationen weltweit. Buchungen für das vierte Quartal 2026 geöffnet.",
    "brutalist structures reimagined as sculptural poems. exploring the tension between mass and void in post-war european architecture.": "Brutalistische Strukturen neu interpretiert als skulpturale Gedichte. Erforschung der Spannung zwischen Masse und Leere in der europäischen Architektur nach dem Krieg.",
    "capturing the ephemeral dance between sky and sea along the icelandic coastline. a study in vastness, silence, and the weight of light at dusk.": "Das Einfangen des vergänglichen Tanzes zwischen Himmel und Meer entlang der isländischen Küste. Eine Studie über Weite, Stille und das Gewicht des Lichts in der Dämmerung.",
    "capturing the world through a lens of emotion, light, and uncompromising beauty. cinematic photography for global brands.": "Die Welt durch eine Linse von Emotion, Licht und kompromissloser Schönheit einfangen. Cinematische Fotografie für globale Marken.",
    "client": "Kunde",
    "comprehensive visual strategy from concept to final execution, ensuring cohesive brand identity.": "Umfassende visuelle Strategie von der Konzeption bis zur endgültigen Ausführung, die eine kohärente Markenidentität gewährleistet.",
    "dates are secured upon signature of the contract and receipt of a 50% retainer. given my travel schedule, i recommend booking at least 2-3 months in advance.": "Die Termine werden nach Unterzeichnung des Vertrags und Erhalt einer Anzahlung von 50 % gesichert. Angesichts meines Reiseplans empfehle ich, mindestens 2-3 Monate im Voraus zu buchen.",
    "delivering uncompromising quality across multiple disciplines. each project is approached with the same cinematic eye and obsessive attention to detail.": "Kompromisslose Qualität in mehreren Disziplinen liefern. Jedes Projekt wird mit dem gleichen cineastischen Blick und obsessiver Detailgenauigkeit angegangen.",
    "do you handle full production?": "Übernehmen Sie die vollständige Produktion?",
    "elena doesn't just take photographs; she crafts cinematic narratives. her ability to command light and direct talent is unparalleled in the industry today.": "Elena macht nicht nur Fotos; sie kreiert filmische Erzählungen. Ihre Fähigkeit, Licht zu beherrschen und Talente zu leiten, ist in der heutigen Branche unübertroffen.",
    "executing the vision with precision. using state-of-the-art medium format cameras and lighting setups to capture high-fidelity imagery on set or on location.": "Die Vision präzise umsetzen. Mit modernsten Mittelformatkameras und Beleuchtungseinrichtungen, um hochauflösende Bilder am Set oder vor Ort festzuhalten.",
    "fine art and commercial photography studio operating globally. crafting timeless visual narratives for visionaries.": "Feinbild- und kommerzielles Fotostudio, das weltweit tätig ist. Zeitlose visuelle Erzählungen für Visionäre gestalten.",
    "frames of light": "Lichtrahmen",
    "high-end fashion and lifestyle imagery for magazines and global campaigns. focused on narrative-driven compositions that elevate brand storytelling.": "Hochwertige Mode- und Lifestyle-Bilder für Magazine und globale Kampagnen. Fokussiert auf narrativ getriebene Kompositionen, die das Storytelling der Marke erhöhen.",
    "how do we secure booking dates?": "Wie sichern wir die Buchungsdaten?",
    "i see the world in": "Ich sehe die Welt in",
    "intimate, character-driven portraits for artists, executives, and public figures seeking authentic representation.": "Intime, charakterorientierte Porträts für Künstler, Führungskräfte und öffentliche Personen, die eine authentische Darstellung suchen.",
    "let's shoot.": "Lass uns shooten.",
    "meticulous color grading, compositing, and high-end retouching to polish the final assets, delivered in all necessary formats for print and digital.": "Sorgfältige Farbkorrektur, Compositing und hochwertige Retusche zur Verfeinerung der finalen Assets, die in allen erforderlichen Formaten für Druck und Digital bereitgestellt werden.",
    "more from this series": "Mehr aus dieser Serie",
    "product and brand photography designed to convert, crafted with meticulous attention to lighting and detail.": "Produkt- und Markenfotografie, die zum Konvertieren entworfen wurde, mit akribischer Aufmerksamkeit für Licht und Detail gefertigt.",
    "return to gallery": "Zurück zur Galerie",
    "securing locations, assembling the creative team (stylists, mua, set designers), casting talent, and finalizing the call sheet for a seamless shoot day.": "Standorte sichern, das Kreativteam (Stylisten, MUA, Set-Designer) zusammenstellen, Talente casten und das Call-Sheet für einen reibungslosen Drehtag finalisieren.",
    "she captured our brutalist structures with a sensitivity we didn't know was possible. the resulting images completely redefined our portfolio presentation.": "Sie hat unsere brutalistischen Strukturen mit einer Sensibilität eingefangen, von der wir nicht wussten, dass sie möglich ist. Die resultierenden Bilder haben unsere Portfolio-Präsentation vollständig neu definiert.",
    "subscribe for studio updates, print releases, and travel dates.": "Abonnieren Sie Neuigkeiten aus dem Atelier, neue Drucke und Reisetermine.",
    "the aftermath of eruption — where destruction creates a canvas more beautiful than any human could conceive. shot over three expeditions.": "Die Folgen des Ausbruchs — wo Zerstörung eine Leinwand schafft, die schöner ist als alles, was ein Mensch sich vorstellen könnte. Gedreht über drei Expeditionen.",
    "the chaos of new york city distilled into frozen moments. a monochrome series focusing on the isolation within the crowd.": "Das Chaos von New York City in gefrorene Momente destilliert. Eine monochrome Serie, die sich auf die Isolation in der Menge konzentriert.",
    "the shoot": "Der Dreh",
    "trusted by visionary": "Vertraut von Visionären",
    "what camera systems do you use?": "Welche Kamerasysteme verwenden Sie?",
    "what is your typical turnaround time?": "Wie lange ist Ihre typische Bearbeitungszeit?",
    "working with elena elevated our campaign to fine art. her pre-production planning is exhaustive, and her execution on set is flawlessly calm and decisive.": "Die Zusammenarbeit mit Elena hat unsere Kampagne zur Kunst erhoben. Ihre Planung in der Vorproduktion ist umfassend, und ihre Ausführung am Set ist makellos ruhig und entscheidend.",
    "years": "Jahre",
    "yes. while based between": "Ja. Während ich zwischen",
  },
  pt: {
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Somos uma agência criativa que liga o design de exceção à engenharia de alto nível. Acompanhamos visionários nas suas experiências digitais.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Reflexões, métodos e estratégias da equipa sobre design, engenharia e crescimento digital.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Para além do SEO, a velocidade de carregamento molda a perceção da sua marca e a conversão do seu site.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Um sistema de design bem construído não é um luxo de agência: é a ferramenta que alinha design e desenvolvimento e encurta os seus prazos.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Cobrimos o digital de ponta a ponta: consultoria estratégica, identidade de marca, desenvolvimento full-stack e motion design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Todas as fotografias deste site são propriedade exclusiva do estúdio Elena Korr, salvo indicação em contrário. O Unsplash fornece as imagens de demonstração.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Este portefólio foi concebido e desenvolvido com precisão, com Next.js, Tailwind CSS e Framer Motion, para uma experiência fluida e cinematográfica.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Usamos tipos de letra modernos e legíveis, escolhidos para equilibrar elegância e legibilidade, à imagem da estética do estúdio.",
    "the weight of light at dusk": "O peso da luz ao crepúsculo",
    "behind the scenes": "Nos bastidores",
    "behind the lens: maison lumière": "Por trás da objetiva: Maison Lumière",
    "finding geometry in the sahara": "Encontrar a geometria no Saara",
    "the philosophy of slow fashion": "A filosofia da moda lenta",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Lavagante azul da Bretanha inteiro, molho thermidor ao coral, gratinado dauphinois, rebentos da época",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Costeleta de borrego em crosta de ervas, molho à provençal, cassoulet de feijão, moleja de borrego",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Soufflé clássico de chocolate negro Valrhona 70 %, creme inglês de baunilha, raspas de laranja cristalizadas",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Borgonha, França · 2022 — Mineral, sílex, fruta branca de caroço",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Bordéus, França · 2015 — Trufa, ameixa preta, ferro — o cume",
    "visual storyteller": "Narradora de imagens",
    "awards": "Distinções",
    "selected": "Seleção",
    "photography": "Fotografia",
    "street": "Rua",
    "fashion": "Moda",
    "landscape": "Paisagem",
    "capabilities": "Competências",
    "creative": "Criação",
    "editorial photography": "Fotografia editorial",
    "art direction": "Direção de arte",
    "commercial": "Publicidade",
    "portraiture": "Retrato",
    "based between": "Instalada entre",
    "methodology": "Metodologia",
    "brands & agencies": "marcas e agências",
    "creative director, vogue": "Diretora criativa, Vogue",
    "founder, thorne architecture": "Fundador, Thorne Architecture",
    "recognition": "Reconhecimento",
    "honors": "Distinções",
    "fine art": "Arte contemporânea",
    "credits": "Créditos",
    "profoto lighting": "Iluminação Profoto",
    "analog 35mm": "Analógico 35 mm",
    "and tokyo, i specialize in capturing moments that transcend the ordinary. my work has been featured in national geographic, vogue, and bbc earth — but the images i am most proud of are the ones that make strangers feel something they cannot quite name.": "e Tóquio, fotografo o que ultrapassa o comum. O meu trabalho saiu na National Geographic, na Vogue e na BBC Earth — mas as imagens de que mais me orgulho são as que fazem um desconhecido sentir algo que não sabe nomear.",
    "with a background in fine arts from école des beaux-arts, i bring a deeply personal yet universally resonant perspective. whether documenting street life in shinjuku or creating haute couture editorials, i seek the same truth wrapped in beauty.": "Formado em belas-artes, trago um olhar íntimo que fala, ainda assim, a toda a gente. Reportagem de rua em Shinjuku ou editorial de alta-costura: procuro a mesma verdade, envolta em beleza.",
    "we begin by understanding your vision, target audience, and the core message. we develop moodboards, lighting plans, and a comprehensive shoot strategy to ensure alignment.": "Começamos por perceber a sua intenção, o público visado e a mensagem. Seguem-se os moodboards, os planos de luz e a estratégia de captação, para que todos apontem ao mesmo.",
    "yes. while based between paris and tokyo, i frequently travel globally for campaigns and editorial assignments. travel fees are calculated based on the project scope.": "Sim. Com base entre Paris e Tóquio, viajo regularmente pelo mundo para campanhas e trabalhos editoriais. As despesas de deslocação calculam-se conforme a dimensão do projeto.",
    "a minimalist approach to the sahara. using harsh midday light to create striking geometric compositions out of shifting dunes.": "Uma abordagem minimalista ao Saara. Usando a dura luz do meio-dia para criar composições geométricas impressionantes a partir de dunas em movimento.",
    "a nocturnal exploration of shinjuku's electric veins — where neon bleeds into rain-slicked asphalt and human stories unfold in 1/125th of a second.": "Uma exploração noturna das veias elétricas de Shinjuku — onde o néon se mistura com o asfalto molhado pela chuva e as histórias humanas se desenrolam em 1/125 de segundo.",
    "about the artist": "Sobre o artista",
    "an intimate portrait series celebrating the raw beauty of the human form — unretouched, unfiltered, unapologetically real.": "Uma série de retratos íntimos que celebra a beleza crua da forma humana — não retocada, não filtrada, sem desculpas.",
    "are you available for international travel?": "Você está disponível para viagens internacionais?",
    "available for commissions, editorial work, and creative collaborations worldwide. bookings open for q4 2026.": "Disponível para encomendas, trabalhos editoriais e colaborações em todo o mundo. Reservas abertas para o último trimestre de 2026.",
    "brutalist structures reimagined as sculptural poems. exploring the tension between mass and void in post-war european architecture.": "Estruturas brutalistas reimaginadas como poemas esculturais. Explorando a tensão entre massa e vazio na arquitetura europeia do pós-guerra.",
    "capturing the ephemeral dance between sky and sea along the icelandic coastline. a study in vastness, silence, and the weight of light at dusk.": "Capturando a dança efémera entre o céu e o mar ao longo da costa islandesa. Um estudo na vastidão, silêncio e o peso da luz ao crepúsculo.",
    "capturing the world through a lens of emotion, light, and uncompromising beauty. cinematic photography for global brands.": "Capturando o mundo através de uma lente de emoção, luz e beleza intransigente. Fotografia cinematográfica para marcas globais.",
    "client": "Cliente",
    "comprehensive visual strategy from concept to final execution, ensuring cohesive brand identity.": "Estratégia visual abrangente desde o conceito até a execução final, garantindo uma identidade de marca coesa.",
    "dates are secured upon signature of the contract and receipt of a 50% retainer. given my travel schedule, i recommend booking at least 2-3 months in advance.": "As datas são garantidas mediante assinatura do contrato e recebimento de um adiantamento de 50%. Dada a minha agenda de viagens, recomendo reservar com pelo menos 2-3 meses de antecedência.",
    "delivering uncompromising quality across multiple disciplines. each project is approached with the same cinematic eye and obsessive attention to detail.": "Entregando qualidade intransigente em várias disciplinas. Cada projeto é abordado com o mesmo olhar cinematográfico e uma atenção obsessiva aos detalhes.",
    "do you handle full production?": "Você cuida da produção completa?",
    "elena doesn't just take photographs; she crafts cinematic narratives. her ability to command light and direct talent is unparalleled in the industry today.": "Elena não tira apenas fotografias; ela cria narrativas cinematográficas. Sua capacidade de dominar a luz e dirigir talentos é incomparável na indústria hoje.",
    "executing the vision with precision. using state-of-the-art medium format cameras and lighting setups to capture high-fidelity imagery on set or on location.": "Executando a visão com precisão. Usando câmaras de formato médio de última geração e configurações de iluminação para capturar imagens de alta fidelidade no set ou em locação.",
    "fine art and commercial photography studio operating globally. crafting timeless visual narratives for visionaries.": "Estúdio de fotografia de arte e comercial que opera globalmente. Criando narrativas visuais intemporais para visionários.",
    "frames of light": "quadros de luz",
    "high-end fashion and lifestyle imagery for magazines and global campaigns. focused on narrative-driven compositions that elevate brand storytelling.": "Imagens de moda e estilo de vida de alta gama para revistas e campanhas globais. Focado em composições orientadas para a narrativa que elevam a contação de histórias da marca.",
    "how do we secure booking dates?": "Como garantimos as datas de reserva?",
    "i see the world in": "Vejo o mundo em",
    "intimate, character-driven portraits for artists, executives, and public figures seeking authentic representation.": "Retratos íntimos e orientados para o caráter para artistas, executivos e figuras públicas que buscam uma representação autêntica.",
    "let's shoot.": "Vamos fotografar.",
    "meticulous color grading, compositing, and high-end retouching to polish the final assets, delivered in all necessary formats for print and digital.": "Classificação de cores meticulosa, composição e retoque de alta qualidade para polir os ativos finais, entregues em todos os formatos necessários para impressão e digital.",
    "more from this series": "Mais desta série",
    "product and brand photography designed to convert, crafted with meticulous attention to lighting and detail.": "Fotografia de produtos e marcas projetada para converter, elaborada com meticulosa atenção à iluminação e aos detalhes.",
    "return to gallery": "Voltar à Galeria",
    "securing locations, assembling the creative team (stylists, mua, set designers), casting talent, and finalizing the call sheet for a seamless shoot day.": "Garantir locais, montar a equipe criativa (estilistas, MUA, cenógrafos), selecionar talentos e finalizar a folha de chamada para um dia de filmagem sem problemas.",
    "she captured our brutalist structures with a sensitivity we didn't know was possible. the resulting images completely redefined our portfolio presentation.": "Ela capturou nossas estruturas brutalistas com uma sensibilidade que não sabíamos ser possível. As imagens resultantes redefiniram completamente nossa apresentação de portfólio.",
    "subscribe for studio updates, print releases, and travel dates.": "Subscreva para receber novidades do atelier, saídas de provas e datas de viagem.",
    "the aftermath of eruption — where destruction creates a canvas more beautiful than any human could conceive. shot over three expeditions.": "As consequências da erupção — onde a destruição cria uma tela mais bonita do que qualquer humano poderia conceber. Filmado em três expedições.",
    "the chaos of new york city distilled into frozen moments. a monochrome series focusing on the isolation within the crowd.": "O caos da cidade de Nova Iorque destilado em momentos congelados. Uma série em monocromático focada na solidão dentro da multidão.",
    "the shoot": "A Filmagem",
    "trusted by visionary": "Confiável por visionários",
    "what camera systems do you use?": "Quais sistemas de câmera você usa?",
    "what is your typical turnaround time?": "Qual é o seu tempo de resposta típico?",
    "working with elena elevated our campaign to fine art. her pre-production planning is exhaustive, and her execution on set is flawlessly calm and decisive.": "Trabalhar com Elena elevou nossa campanha a uma obra de arte. Seu planejamento de pré-produção é exaustivo, e sua execução no set é impecavelmente calma e decisiva.",
    "years": "Anos",
    "yes. while based between": "Sim. Enquanto estou baseado entre",
  },
};
