/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Un beau travail qui ne convertit pas n'est qu'une décoration. Nous mesurons notre succès par les résultats de nos clients.",
    "behind it.": "derrière cela.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Interfaces sur mesure conçues avec une précision pixel parfaite et une réflexion UX stratégique qui convertit les visiteurs en clients.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Interfaces sur mesure conçues avec une précision pixel parfaite et une réflexion stratégique sur l'UX qui transforme les visiteurs en clients.",
    "build": "Construire",
    "build websites.": "faire des sites.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Animations cinématographiques et micro-interactions qui élèvent la perception et rendent chaque point de contact mémorable.",
    "client satisfaction": "Satisfaction client",
    "clients worldwide": "Clients dans le monde entier",
    "conversion funnels: five frictions that cost you customers": "Entonnoirs de conversion : cinq frictions qui vous coûtent des clients",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Optimisation des Core Web Vitals, architecture CDN et réglage de l'infrastructure pour des temps de chargement inférieurs à une seconde dans le monde entier.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Optimisation des Core Web Vitals, architecture CDN et réglage de l'infrastructure pour des temps de chargement inférieurs à une seconde.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Stratégies de croissance basées sur les données qui s'accumulent au fil du temps et construisent une fidélité durable avec votre public.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Stratégies de croissance basées sur les données qui s'accumulent au fil du temps, transformant les visiteurs en défenseurs fidèles de la marque.",
    "design": "Conception",
    "design system, development": "Système de design, Développement",
    "design systems: the investment that speeds up every release": "Systèmes de design : l'investissement qui accélère chaque publication",
    "design, development, branding": "Conception, Développement, Branding",
    "design, development, motion": "Conception, Développement, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Identités visuelles distinctives qui résonnent profondément avec votre public et vous distinguent de vos concurrents.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Identités visuelles distinctives qui résonnent profondément avec votre public cible et se démarquent des concurrents.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Chaque pixel est voulu. Chaque interaction est pensée. Chaque ligne de code est écrite pour durer. Nous joignons l'exigence esthétique à un effet mesurable, parce qu'un beau travail qui ne convertit pas n'est que décoration.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Chaque pixel est intentionnel. Nous croyons que l'excellence réside dans les détails que personne ne remarque consciemment.",
    "for impact.": "pour un impact.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "De la conception au code, nous anticipons les cas limites et construisons pour durer. Un site magnifique qui tombe en panne n'est qu'une promesse brisée.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Des maquettes aux prototypes haute fidélité, nous concevons des interfaces à la fois belles et fonctionnellement précises.",
    "growth": "Croissance",
    "guides us.": "nous guide.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Applications haute performance construites sur des technologies modernes avec des intégrations fluides et une fiabilité à toute épreuve.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Applications haute performance construites sur des stacks modernes, avec des intégrations transparentes et une fiabilité à toute épreuve.",
    "internet&apos;s best.": "le meilleur d'internet.",
    "motion design": "Design Motion",
    "motion design: when animation serves the experience (and when it hurts it)": "Design d'animation : quand l'animation sert l'expérience (et quand elle la nuit)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Nos ingénieurs traduisent les conceptions en code de qualité production. Propre, performant et conçu pour évoluer sous une charge réelle.",
    "our role": "Notre rôle",
    "purpose and legal basis": "Objectif et base légale",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "Une QA rigoureuse, des audits de performance et un déploiement par étapes garantissent un lancement sans faille qui fait la bonne première impression.",
    "step by step.": "étape par étape.",
    "we build empires.": "Nous bâtissons des maisons qui durent.",
    "we don't just": "Nous ne faisons pas que",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Nous nous immergeons dans votre entreprise, vos utilisateurs et votre paysage concurrentiel. Une recherche approfondie guide chaque décision que nous prenons.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Nous ne prenons qu'un nombre restreint de clients par trimestre. Si vous avez un projet, parlons-en avant que les places soient prises.",
    "web design": "Conception Web",
    "year": "Année",
    "years of craft": "Années de savoir-faire",
    "your rights": "Vos droits",
  },
  es: {
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Un trabajo hermoso que no convierte es solo decoración. Medimos nuestro éxito por los resultados de nuestros clientes.",
    "behind it.": "detrás de ello.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Interfaces personalizadas elaboradas con precisión perfecta de píxeles y un pensamiento estratégico de UX que convierte a los visitantes en clientes.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Interfaces personalizadas elaboradas con precisión perfecta en píxeles y un pensamiento estratégico de UX que convierte visitantes en clientes.",
    "build": "Construir",
    "build websites.": "hacemos sitios web.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Animaciones cinematográficas e microinteracciones que elevan la percepción y hacen que cada punto de contacto sea memorable.",
    "client satisfaction": "Satisfacción del cliente",
    "clients worldwide": "Clientes en todo el mundo",
    "conversion funnels: five frictions that cost you customers": "Embudos de conversión: cinco fricciones que te cuestan clientes",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Optimización de Core Web Vitals, arquitectura CDN y ajuste de infraestructura para tiempos de carga de menos de un segundo a nivel mundial.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Optimización de Core Web Vitals, arquitectura CDN y ajuste de infraestructura para tiempos de carga de menos de un segundo.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Estrategias de crecimiento basadas en datos que se acumulan con el tiempo y construyen lealtad duradera con su audiencia.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Estrategias de crecimiento basadas en datos que se acumulan con el tiempo, convirtiendo a los visitantes en defensores leales de la marca.",
    "design": "Diseño",
    "design system, development": "Sistema de diseño, Desarrollo",
    "design systems: the investment that speeds up every release": "Sistemas de diseño: la inversión que acelera cada lanzamiento",
    "design, development, branding": "Diseño, Desarrollo, Branding",
    "design, development, motion": "Diseño, Desarrollo, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Identidades visuales distintivas que resuenan profundamente con su audiencia y lo diferencian de los competidores.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Identidades visuales distintivas que resuenan profundamente con su público objetivo y se destacan de los competidores.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Cada píxel es intencionado. Cada interacción está pensada. Cada línea de código se escribe para durar. Unimos la exigencia estética a un efecto medible, porque un trabajo bonito que no convierte es solo decoración.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Cada píxel es intencional. Creemos que la excelencia vive en los detalles que nadie nota conscientemente.",
    "for impact.": "para el impacto.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "Desde el diseño hasta el código, anticipamos casos extremos y construimos para durar. Un sitio hermoso que se rompe es solo una promesa rota.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Desde wireframes hasta prototipos de alta fidelidad, creamos interfaces que son tanto bellas como funcionalmente precisas.",
    "growth": "Crecimiento",
    "guides us.": "nos guía.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Aplicaciones de alto rendimiento construidas sobre pilas modernas con integraciones sin problemas y fiabilidad a prueba de balas.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Aplicaciones de alto rendimiento construidas sobre pilas modernas, con integraciones sin problemas y fiabilidad a prueba de balas.",
    "internet&apos;s best.": "lo mejor de internet.",
    "motion design": "Diseño de Movimiento",
    "motion design: when animation serves the experience (and when it hurts it)": "Diseño de movimiento: cuando la animación sirve a la experiencia (y cuando la perjudica)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Nuestros ingenieros traducen diseños en código de calidad de producción. Limpio, eficiente y construido para escalar bajo carga del mundo real.",
    "our role": "Nuestro papel",
    "purpose and legal basis": "Propósito y base legal",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "QA rigurosa, auditorías de rendimiento y un lanzamiento por etapas aseguran un lanzamiento impecable que causa la impresión correcta.",
    "step by step.": "paso a paso.",
    "we build empires.": "Construimos casas que perduran.",
    "we don't just": "No solo",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Nos sumergimos en su negocio, sus usuarios y su panorama competitivo. La investigación profunda impulsa cada decisión que tomamos.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Solo aceptamos un número limitado de clientes por trimestre. Si tiene un proyecto, hablemos antes de que se agoten las plazas.",
    "web design": "Diseño Web",
    "year": "Año",
    "years of craft": "Años de artesanía",
    "your rights": "Tus derechos",
  },
  de: {
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Schöne Arbeit, die nicht konvertiert, ist nur Dekoration. Wir messen unseren Erfolg an den Ergebnissen unserer Kunden.",
    "behind it.": "dahinter.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Maßgeschneiderte Schnittstellen, die mit pixelgenauer Präzision und strategischem UX-Denken entwickelt wurden, um Besucher in Kunden zu verwandeln.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Maßgeschneiderte Schnittstellen, die mit pixelgenauer Präzision und strategischem UX-Denken gestaltet sind, um Besucher in Kunden zu verwandeln.",
    "build": "Bauen",
    "build websites.": "Websites.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Kinematische Animationen und Mikrointeraktionen, die die Wahrnehmung erhöhen und jeden Berührungspunkt unvergesslich machen.",
    "client satisfaction": "Kundenzufriedenheit",
    "clients worldwide": "Kunden weltweit",
    "conversion funnels: five frictions that cost you customers": "Conversionstrichter: fünf Reibungen, die Sie Kunden kosten",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Optimierung der Core Web Vitals, CDN-Architektur und Infrastrukturabstimmung für Ladezeiten von unter einer Sekunde weltweit.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Optimierung der Core Web Vitals, CDN-Architektur und Infrastrukturabstimmung für Ladezeiten von unter einer Sekunde.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Datengetriebene Wachstumsstrategien, die sich im Laufe der Zeit summieren und eine dauerhafte Loyalität zu Ihrem Publikum aufbauen.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Datengetriebene Wachstumsstrategien, die sich im Laufe der Zeit summieren und Besucher in treue Markenbotschafter verwandeln.",
    "design": "Design",
    "design system, development": "Designsystem, Entwicklung",
    "design systems: the investment that speeds up every release": "Designsysteme: die Investition, die jede Veröffentlichung beschleunigt",
    "design, development, branding": "Design, Entwicklung, Branding",
    "design, development, motion": "Design, Entwicklung, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Unverwechselbare visuelle Identitäten, die tief mit Ihrem Publikum resonieren und Sie von Ihren Mitbewerbern abheben.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Unverwechselbare visuelle Identitäten, die tief mit Ihrer Zielgruppe resonieren und sich von Wettbewerbern abheben.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Jedes Pixel ist gewollt. Jede Interaktion ist durchdacht. Jede Codezeile ist auf Dauer geschrieben. Wir verbinden ästhetischen Anspruch mit messbarer Wirkung, denn schöne Arbeit, die nicht konvertiert, ist bloß Dekoration.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Jeder Pixel ist absichtlich. Wir glauben, dass Exzellenz in den Details lebt, die niemand bewusst bemerkt.",
    "for impact.": "für Wirkung.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "Von Design zu Code antizipieren wir Randfälle und bauen für die Ewigkeit. Eine schöne Seite, die abstürzt, ist nur ein gebrochenes Versprechen.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Von Wireframes bis hin zu hochauflösenden Prototypen gestalten wir Schnittstellen, die sowohl schön als auch funktional präzise sind.",
    "growth": "Wachstum",
    "guides us.": "führt uns.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Hochleistungsanwendungen, die auf modernen Stacks mit nahtlosen Integrationen und absoluter Zuverlässigkeit basieren.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Hochleistungsanwendungen, die auf modernen Stacks basieren, mit nahtlosen Integrationen und absoluter Zuverlässigkeit.",
    "internet&apos;s best.": "das Beste des Internets.",
    "motion design": "Bewegungsdesign",
    "motion design: when animation serves the experience (and when it hurts it)": "Motion Design: wenn Animation das Erlebnis dient (und wenn es schadet)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Unsere Ingenieure übersetzen Designs in produktionsreifes Code. Sauber, leistungsfähig und für die Skalierung unter realen Lasten gebaut.",
    "our role": "Unsere Rolle",
    "purpose and legal basis": "Zweck und rechtliche Grundlage",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "Strenge QA, Leistungsprüfungen und ein gestaffelter Rollout sorgen für einen fehlerfreien Start, der den richtigen ersten Eindruck hinterlässt.",
    "step by step.": "Schritt für Schritt.",
    "we build empires.": "Wir bauen, was Bestand hat.",
    "we don't just": "Wir bauen nicht nur",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Wir tauchen in Ihr Geschäft, Ihre Nutzer und Ihr Wettbewerbsumfeld ein. Tiefgehende Forschung treibt jede Entscheidung, die wir treffen.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Wir nehmen pro Quartal nur wenige Kunden an. Wenn Sie ein Vorhaben haben, sprechen wir, bevor die Plätze vergeben sind.",
    "web design": "Webdesign",
    "year": "Jahr",
    "years of craft": "Jahre des Handwerks",
    "your rights": "Ihre Rechte",
  },
  pt: {
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Um trabalho bonito que não converte é apenas decoração. Medimos nosso sucesso pelos resultados de nossos clientes.",
    "behind it.": "por trás disso.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Interfaces personalizadas criadas com precisão perfeita de pixels e pensamento estratégico de UX que converte visitantes em clientes.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Interfaces personalizadas criadas com precisão perfeita em pixels e um pensamento estratégico de UX que transforma visitantes em clientes.",
    "build": "Construir",
    "build websites.": "sites.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Animações cinematográficas e microinterações que elevam a percepção e tornam cada ponto de contato memorável.",
    "client satisfaction": "Satisfação do cliente",
    "clients worldwide": "Clientes em todo o mundo",
    "conversion funnels: five frictions that cost you customers": "Funis de conversão: cinco fricções que lhe custam clientes",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Otimização dos Core Web Vitals, arquitetura CDN e ajuste de infraestrutura para tempos de carregamento abaixo de um segundo globalmente.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Otimização dos Core Web Vitals, arquitetura CDN e ajuste de infraestrutura para tempos de carregamento abaixo de um segundo.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Estratégias de crescimento orientadas por dados que se acumulam ao longo do tempo e constroem lealdade duradoura com o seu público.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Estratégias de crescimento orientadas por dados que se acumulam ao longo do tempo, convertendo visitantes em defensores leais da marca.",
    "design": "Design",
    "design system, development": "Sistema de design, Desenvolvimento",
    "design systems: the investment that speeds up every release": "Sistemas de design: o investimento que acelera cada lançamento",
    "design, development, branding": "Design, Desenvolvimento, Branding",
    "design, development, motion": "Design, Desenvolvimento, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Identidades visuais distintas que ressoam profundamente com o seu público e o diferenciam dos concorrentes.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Identidades visuais distintas que ressoam profundamente com o seu público-alvo e se destacam dos concorrentes.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Cada píxel é intencional. Cada interação é pensada. Cada linha de código é escrita para durar. Juntamos a exigência estética a um efeito mensurável, porque um belo trabalho que não converte é apenas decoração.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Cada pixel é intencional. Acreditamos que a excelência vive nos detalhes que ninguém nota conscientemente.",
    "for impact.": "para impacto.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "Do design ao código, antecipamos casos extremos e construímos para durar. Um site bonito que quebra é apenas uma promessa quebrada.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Desde wireframes até protótipos de alta fidelidade, criamos interfaces que são tanto bonitas quanto funcionalmente precisas.",
    "growth": "Crescimento",
    "guides us.": "nos guia.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Aplicações de alto desempenho construídas em pilhas modernas com integrações perfeitas e fiabilidade à prova de falhas.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Aplicações de alto desempenho construídas em pilhas modernas, com integrações perfeitas e fiabilidade à prova de falhas.",
    "internet&apos;s best.": "o melhor da internet.",
    "motion design": "Design de Movimento",
    "motion design: when animation serves the experience (and when it hurts it)": "Design de movimento: quando a animação serve a experiência (e quando a prejudica)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Os nossos engenheiros traduzem designs em código de qualidade de produção. Limpo, eficiente e construído para escalar sob carga do mundo real.",
    "our role": "O nosso papel",
    "purpose and legal basis": "Propósito e base legal",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "QA rigorosa, auditorias de desempenho e um lançamento em etapas garantem um lançamento impecável que causa a impressão certa.",
    "step by step.": "passo a passo.",
    "we build empires.": "Construímos casas que perduram.",
    "we don't just": "Não fazemos apenas",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Mergulhamos no seu negócio, nos seus usuários e no seu panorama competitivo. Uma pesquisa aprofundada orienta cada decisão que tomamos.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Só aceitamos um número limitado de clientes por trimestre. Se tem um projeto, falemos antes de as vagas se esgotarem.",
    "web design": "Design de Websites",
    "year": "Ano",
    "years of craft": "Anos de artesanato",
    "your rights": "Seus direitos",
  },
};
