/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Nous sommes une agence créative qui relie le design d'exception à l'ingénierie de haut niveau. Nous accompagnons les visionnaires dans leurs expériences numériques.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Réflexions, méthodes et stratégies de l'équipe sur le design, l'ingénierie et la croissance numérique.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Au-delà du référencement, la vitesse de chargement façonne la perception de votre marque et la conversion de votre site.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Un système de design bien construit n'est pas un luxe d'agence : c'est l'outil qui aligne design et développement et raccourcit vos délais.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Nous couvrons le numérique de bout en bout : conseil stratégique, identité de marque, développement full-stack et motion design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Toutes les photographies de ce site sont la propriété exclusive du studio Elena Korr, sauf mention contraire. Unsplash fournit les images de démonstration.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Ce portfolio a été conçu et développé avec précision, avec Next.js, Tailwind CSS et Framer Motion, pour une expérience fluide et cinématographique.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Nous utilisons des polices modernes et lisibles, choisies pour équilibrer élégance et lisibilité, à l'image de l'esthétique du studio.",
    "the weight of light at dusk": "Le poids de la lumière au crépuscule",
    "behind the scenes": "Dans les coulisses",
    "behind the lens: maison lumière": "Derrière l'objectif : Maison Lumière",
    "finding geometry in the sahara": "Trouver la géométrie au Sahara",
    "the philosophy of slow fashion": "La philosophie de la mode lente",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Homard bleu de Bretagne entier, sauce thermidor au corail, gratin dauphinois, jeunes pousses de saison",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Carré d'agneau en croûte d'herbes, jus à la provençale, cassoulet de flageolets, ris d'agneau",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Soufflé classique au chocolat noir Valrhona 70 %, crème anglaise à la vanille, zestes d'orange confits",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Bourgogne, France · 2022 — Minéral, silex, fruits blancs à noyau",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Bordeaux, France · 2015 — Truffe, prune noire, fer — le sommet",
    "let's start a": "Lançons un",
    "project.": "projet.",
    "ready to elevate your digital presence? we're currently accepting new projects for q3. fill out the form below and we'll get back to you within 24 hours.": "Prêt à hausser votre présence en ligne ? Nous acceptons de nouveaux projets pour le troisième trimestre. Remplissez le formulaire, nous revenons vers vous sous 24 heures.",
    "name": "Nom",
    "project details": "Votre projet",
    "contact information": "Nos coordonnées",
    "visit us": "Nous rendre visite",
    "a curated selection of our recent projects. we partner with ambitious brands to create digital experiences that stand out and deliver results.": "Une sélection de nos projets récents. Nous accompagnons des marques ambitieuses pour créer des expériences numériques qui se démarquent et produisent des résultats.",
    "everything you need to know about novaplatform's pricing. built for speed, security, and developer experience.": "Tout ce qu'il faut savoir sur les tarifs de NovaPlatform. Pensés pour la vitesse, la sécurité et le confort des développeurs.",
    "founded in": "Fondée à",
    "in 2021, atelier noir is an independent fashion house dedicated to the art of quiet luxury. we reject the rapid cycles of fast fashion in favor of a slower, more deliberate method of creation.": "en 2021, Atelier NOIR est une maison de mode indépendante vouée à l'art du luxe discret. Nous refusons les cycles rapides de la fast fashion au profit d'une création plus lente et plus délibérée.",
    "our garments are defined by architectural simplicity, meticulous tailoring, and exceptional materials. we work exclusively with certified natural fibers—organic cashmere, french flax linen, and japanese silk—sourced from mills that guarantee raw material traceability and ecological responsibility.": "Nos vêtements se définissent par une simplicité architecturale, une coupe méticuleuse et des matières d'exception. Nous ne travaillons que des fibres naturelles certifiées — cachemire biologique, lin de France, soie du Japon — issues de filatures qui garantissent la traçabilité et la responsabilité écologique.",
    "every piece is handcrafted to order in our parisian atelier by master artisans who bring decades of high-fashion experience. by making only what is ordered, we eliminate excess production and waste, creating garments that are as responsible as they are beautiful.": "Chaque pièce est façonnée à la commande dans notre atelier parisien par des maîtres artisans forts de décennies de haute couture. En ne produisant que ce qui est commandé, nous éliminons la surproduction et le gaspillage : des vêtements aussi responsables que beaux.",
    "founded in 2018, impact studio is a collective of designers, engineers, and strategists obsessed with excellence. we partner with ambitious brands — from seed-stage startups to fortune 500 companies — delivering work that consistently outperforms.": "Fondé en 2018, le studio IMPACT réunit des designers, des développeurs et des stratèges obsédés par l'exigence. Nous accompagnons des marques ambitieuses — de la jeune pousse au grand groupe — avec un travail qui dépasse régulièrement les objectifs fixés.",
    "strategic thinking": "Réflexion stratégique",
    "pixel perfection": "Précision au pixel",
    "clean code": "Code propre",
    "fast delivery": "Livraison rapide",
    "engineering": "Développement",
    "development": "Développement",
    "identity": "Identité",
    "branding": "Identité de marque",
    "strategy": "Stratégie",
    "design motion": "Motion design",
    "speed": "Vitesse",
    "performance": "Performance",
    "launch": "Mise en ligne",
    "load testing, lighthouse audits, staging environments, go-live support.": "Tests de charge, audits Lighthouse, environnements de préproduction, accompagnement le jour de la mise en ligne.",
    "stakeholder interviews, user research, competitor analysis, technical audit.": "Entretiens avec les parties prenantes, étude des utilisateurs, analyse de la concurrence, audit technique.",
    "projects delivered": "Projets livrés",
    "web ecosystem": "Écosystème web",
    "brand identity": "Identité de marque",
    "fintech app": "Application fintech",
    "healthcare portal": "Portail santé",
    "saas platform": "Plateforme SaaS",
    "something great?": "quelque chose de grand ?",
    "resources": "Ressources",
    "connect": "Nous suivre",
    "all articles": "Tous les articles",
    "all work": "Tout le travail",
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Un beau travail qui ne convertit pas n'est qu'une décoration. Nous mesurons notre succès par les résultats de nos clients.",
    "behind it.": "derrière cela.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Interfaces sur mesure conçues avec une précision pixel parfaite et une réflexion UX stratégique qui convertit les visiteurs en clients.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Interfaces sur mesure conçues avec une précision pixel parfaite et une réflexion stratégique sur l'UX qui transforme les visiteurs en clients.",
    "build": "Construire",
    "build websites.": "faire des sites.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Animations cinématographiques et micro-interactions qui élèvent la perception et rendent chaque point de contact mémorable.",
    "client satisfaction": "Satisfaction client",
    "clients worldwide": "Clients dans le monde entier",
    "conversion funnels: five frictions that cost you customers": "Entonnoirs de conversion : cinq frictions qui vous coûtent des clients",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Optimisation des Core Web Vitals, architecture CDN et réglage de l'infrastructure pour des temps de chargement inférieurs à une seconde dans le monde entier.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Optimisation des Core Web Vitals, architecture CDN et réglage de l'infrastructure pour des temps de chargement inférieurs à une seconde.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Stratégies de croissance basées sur les données qui s'accumulent au fil du temps et construisent une fidélité durable avec votre public.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Stratégies de croissance basées sur les données qui s'accumulent au fil du temps, transformant les visiteurs en défenseurs fidèles de la marque.",
    "design": "Conception",
    "design system, development": "Système de design, Développement",
    "design systems: the investment that speeds up every release": "Systèmes de design : l'investissement qui accélère chaque publication",
    "design, development, branding": "Conception, Développement, Branding",
    "design, development, motion": "Conception, Développement, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Identités visuelles distinctives qui résonnent profondément avec votre public et vous distinguent de vos concurrents.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Identités visuelles distinctives qui résonnent profondément avec votre public cible et se démarquent des concurrents.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Chaque pixel est voulu. Chaque interaction est pensée. Chaque ligne de code est écrite pour durer. Nous joignons l'exigence esthétique à un effet mesurable, parce qu'un beau travail qui ne convertit pas n'est que décoration.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Chaque pixel est intentionnel. Nous croyons que l'excellence réside dans les détails que personne ne remarque consciemment.",
    "for impact.": "pour un impact.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "De la conception au code, nous anticipons les cas limites et construisons pour durer. Un site magnifique qui tombe en panne n'est qu'une promesse brisée.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Des maquettes aux prototypes haute fidélité, nous concevons des interfaces à la fois belles et fonctionnellement précises.",
    "full-service creative studio crafting immersive digital experiences, brand identities, and high-performance products for ambitious brands.": "Studio créatif à service complet créant des expériences numériques immersives, des identités de marque et des produits haute performance pour des marques ambitieuses.",
    "growth": "Croissance",
    "guides us.": "nous guide.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Applications haute performance construites sur des technologies modernes avec des intégrations fluides et une fiabilité à toute épreuve.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Applications haute performance construites sur des stacks modernes, avec des intégrations transparentes et une fiabilité à toute épreuve.",
    "internet's best.": "le meilleur d'internet.",
    "let's talk": "Parlons-en",
    "motion design": "Design Motion",
    "motion design: when animation serves the experience (and when it hurts it)": "Design d'animation : quand l'animation sert l'expérience (et quand elle la nuit)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Nos ingénieurs traduisent les conceptions en code de qualité production. Propre, performant et conçu pour évoluer sous une charge réelle.",
    "our process,": "Notre processus,",
    "our role": "Notre rôle",
    "prefer a call? mention it in your message and we'll suggest a time slot.": "Préférez-vous un appel ? Mentionnez-le dans votre message et nous vous proposerons un créneau horaire.",
    "purpose and legal basis": "Objectif et base légale",
    "read article": "Lire l'article",
    "ready to build": "Prêt à construire",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "Une QA rigoureuse, des audits de performance et un déploiement par étapes garantissent un lancement sans faille qui fait la bonne première impression.",
    "schedule a call": "Planifiez un appel",
    "send request": "Envoyer la demande",
    "services built": "Services construits",
    "step by step.": "étape par étape.",
    "thank you. a member of the studio will reply within one business day.": "Merci. Un membre du studio répondra dans un délai d'un jour ouvrable.",
    "the information published on this site is provided for general guidance and shall not engage the liability of the publisher.": "Les informations publiées sur ce site sont fournies à titre indicatif et n'engagent pas la responsabilité de l'éditeur.",
    "the minds": "Les esprits",
    "this site does not use advertising tracking cookies. only technical cookies strictly necessary for the site to function may be used.": "Ce site n'utilise pas de cookies de suivi publicitaire. Seuls les cookies techniques strictement nécessaires au fonctionnement du site peuvent être utilisés.",
    "we build empires.": "Nous bâtissons des maisons qui durent.",
    "we don't just": "Nous ne faisons pas que",
    "we don't just": "Nous ne faisons pas que",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Nous nous immergeons dans votre entreprise, vos utilisateurs et votre paysage concurrentiel. Une recherche approfondie guide chaque décision que nous prenons.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Nous ne prenons qu'un nombre restreint de clients par trimestre. Si vous avez un projet, parlons-en avant que les places soient prises.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Nous travaillons avec un nombre sélectionné de clients chaque trimestre. Si vous avez un projet en tête, parlons-en avant que les places ne se remplissent.",
    "web design": "Conception Web",
    "what": "Quoi",
    "written by the impact studio team. provided for informational purposes.": "Rédigé par l'équipe d'IMPACT Studio. Fournit à des fins d'information.",
    "year": "Année",
    "years of craft": "Années de savoir-faire",
    "your rights": "Vos droits",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Somos una agencia creativa que une el diseño excepcional a la ingeniería de alto nivel. Acompañamos a los visionarios en sus experiencias digitales.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Reflexiones, métodos y estrategias del equipo sobre diseño, ingeniería y crecimiento digital.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Más allá del SEO, la velocidad de carga moldea la percepción de su marca y la conversión de su sitio.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Un sistema de diseño bien construido no es un lujo de agencia: es la herramienta que alinea diseño y desarrollo y acorta sus plazos.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Cubrimos lo digital de principio a fin: consultoría estratégica, identidad de marca, desarrollo full-stack y motion design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Todas las fotografías de este sitio son propiedad exclusiva del estudio Elena Korr, salvo mención contraria. Unsplash aporta las imágenes de muestra.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Este portafolio fue diseñado y desarrollado con precisión, con Next.js, Tailwind CSS y Framer Motion, para una experiencia fluida y cinematográfica.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Usamos tipografías modernas y legibles, elegidas para equilibrar elegancia y legibilidad, a imagen de la estética del estudio.",
    "the weight of light at dusk": "El peso de la luz al atardecer",
    "behind the scenes": "Entre bastidores",
    "behind the lens: maison lumière": "Detrás del objetivo: Maison Lumière",
    "finding geometry in the sahara": "Encontrar la geometría en el Sáhara",
    "the philosophy of slow fashion": "La filosofía de la moda lenta",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Bogavante azul de Bretaña entero, salsa thermidor al coral, gratén delfinés, brotes de temporada",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Costillar de cordero en costra de hierbas, jugo a la provenzal, cassoulet de judías, mollejas de cordero",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Suflé clásico de chocolate negro Valrhona 70 %, crema inglesa de vainilla, ralladura de naranja confitada",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Borgoña, Francia · 2022 — Mineral, sílex, fruta blanca de hueso",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Burdeos, Francia · 2015 — Trufa, ciruela negra, hierro — la cumbre",
    "let's start a": "Empecemos un",
    "project.": "proyecto.",
    "ready to elevate your digital presence? we're currently accepting new projects for q3. fill out the form below and we'll get back to you within 24 hours.": "¿Listo para elevar su presencia digital? Aceptamos nuevos proyectos para el tercer trimestre. Rellene el formulario y le responderemos en 24 horas.",
    "name": "Nombre",
    "project details": "Su proyecto",
    "contact information": "Nuestros datos",
    "visit us": "Visítenos",
    "a curated selection of our recent projects. we partner with ambitious brands to create digital experiences that stand out and deliver results.": "Una selección de nuestros proyectos recientes. Acompañamos a marcas ambiciosas para crear experiencias digitales que destacan y dan resultados.",
    "everything you need to know about novaplatform's pricing. built for speed, security, and developer experience.": "Todo lo que hay que saber sobre las tarifas de NovaPlatform. Pensadas para la velocidad, la seguridad y la experiencia de desarrollo.",
    "founded in": "Fundada en",
    "in 2021, atelier noir is an independent fashion house dedicated to the art of quiet luxury. we reject the rapid cycles of fast fashion in favor of a slower, more deliberate method of creation.": "en 2021, Atelier NOIR es una casa de moda independiente dedicada al arte del lujo discreto. Rechazamos los ciclos rápidos de la fast fashion en favor de una creación más lenta y deliberada.",
    "our garments are defined by architectural simplicity, meticulous tailoring, and exceptional materials. we work exclusively with certified natural fibers—organic cashmere, french flax linen, and japanese silk—sourced from mills that guarantee raw material traceability and ecological responsibility.": "Nuestras prendas se definen por una simplicidad arquitectónica, un corte meticuloso y materiales excepcionales. Solo trabajamos fibras naturales certificadas — cachemir ecológico, lino de Francia, seda de Japón — de hilanderías que garantizan la trazabilidad y la responsabilidad ecológica.",
    "every piece is handcrafted to order in our parisian atelier by master artisans who bring decades of high-fashion experience. by making only what is ordered, we eliminate excess production and waste, creating garments that are as responsible as they are beautiful.": "Cada pieza se confecciona por encargo en nuestro taller parisino por maestros artesanos con décadas de alta costura. Al producir solo lo encargado, eliminamos la sobreproducción y el desperdicio: prendas tan responsables como bellas.",
    "founded in 2018, impact studio is a collective of designers, engineers, and strategists obsessed with excellence. we partner with ambitious brands — from seed-stage startups to fortune 500 companies — delivering work that consistently outperforms.": "Fundado en 2018, el estudio IMPACT reúne a diseñadores, desarrolladores y estrategas obsesionados con la excelencia. Acompañamos a marcas ambiciosas — de la startup a la gran empresa — con un trabajo que supera sistemáticamente los objetivos.",
    "strategic thinking": "Pensamiento estratégico",
    "pixel perfection": "Precisión al píxel",
    "clean code": "Código limpio",
    "fast delivery": "Entrega rápida",
    "engineering": "Desarrollo",
    "development": "Desarrollo",
    "identity": "Identidad",
    "branding": "Identidad de marca",
    "strategy": "Estrategia",
    "design motion": "Motion design",
    "speed": "Velocidad",
    "performance": "Rendimiento",
    "launch": "Puesta en línea",
    "load testing, lighthouse audits, staging environments, go-live support.": "Pruebas de carga, auditorías Lighthouse, entornos de preproducción, acompañamiento el día del lanzamiento.",
    "stakeholder interviews, user research, competitor analysis, technical audit.": "Entrevistas con las partes interesadas, estudio de usuarios, análisis de la competencia, auditoría técnica.",
    "projects delivered": "Proyectos entregados",
    "web ecosystem": "Ecosistema web",
    "brand identity": "Identidad de marca",
    "fintech app": "Aplicación fintech",
    "healthcare portal": "Portal de salud",
    "saas platform": "Plataforma SaaS",
    "something great?": "algo grande?",
    "resources": "Recursos",
    "connect": "Síguenos",
    "all articles": "Todos los artículos",
    "all work": "Todo el trabajo",
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Un trabajo hermoso que no convierte es solo decoración. Medimos nuestro éxito por los resultados de nuestros clientes.",
    "behind it.": "detrás de ello.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Interfaces personalizadas elaboradas con precisión perfecta de píxeles y un pensamiento estratégico de UX que convierte a los visitantes en clientes.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Interfaces personalizadas elaboradas con precisión perfecta en píxeles y un pensamiento estratégico de UX que convierte visitantes en clientes.",
    "build": "Construir",
    "build websites.": "hacemos sitios web.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Animaciones cinematográficas e microinteracciones que elevan la percepción y hacen que cada punto de contacto sea memorable.",
    "client satisfaction": "Satisfacción del cliente",
    "clients worldwide": "Clientes en todo el mundo",
    "conversion funnels: five frictions that cost you customers": "Embudos de conversión: cinco fricciones que te cuestan clientes",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Optimización de Core Web Vitals, arquitectura CDN y ajuste de infraestructura para tiempos de carga de menos de un segundo a nivel mundial.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Optimización de Core Web Vitals, arquitectura CDN y ajuste de infraestructura para tiempos de carga de menos de un segundo.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Estrategias de crecimiento basadas en datos que se acumulan con el tiempo y construyen lealtad duradera con su audiencia.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Estrategias de crecimiento basadas en datos que se acumulan con el tiempo, convirtiendo a los visitantes en defensores leales de la marca.",
    "design": "Diseño",
    "design system, development": "Sistema de diseño, Desarrollo",
    "design systems: the investment that speeds up every release": "Sistemas de diseño: la inversión que acelera cada lanzamiento",
    "design, development, branding": "Diseño, Desarrollo, Branding",
    "design, development, motion": "Diseño, Desarrollo, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Identidades visuales distintivas que resuenan profundamente con su audiencia y lo diferencian de los competidores.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Identidades visuales distintivas que resuenan profundamente con su público objetivo y se destacan de los competidores.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Cada píxel es intencionado. Cada interacción está pensada. Cada línea de código se escribe para durar. Unimos la exigencia estética a un efecto medible, porque un trabajo bonito que no convierte es solo decoración.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Cada píxel es intencional. Creemos que la excelencia vive en los detalles que nadie nota conscientemente.",
    "for impact.": "para el impacto.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "Desde el diseño hasta el código, anticipamos casos extremos y construimos para durar. Un sitio hermoso que se rompe es solo una promesa rota.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Desde wireframes hasta prototipos de alta fidelidad, creamos interfaces que son tanto bellas como funcionalmente precisas.",
    "full-service creative studio crafting immersive digital experiences, brand identities, and high-performance products for ambitious brands.": "Estudio creativo de servicio completo que crea experiencias digitales inmersivas, identidades de marca y productos de alto rendimiento para marcas ambiciosas.",
    "growth": "Crecimiento",
    "guides us.": "nos guía.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Aplicaciones de alto rendimiento construidas sobre pilas modernas con integraciones sin problemas y fiabilidad a prueba de balas.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Aplicaciones de alto rendimiento construidas sobre pilas modernas, con integraciones sin problemas y fiabilidad a prueba de balas.",
    "internet's best.": "lo mejor de internet.",
    "let's talk": "Hablemos",
    "motion design": "Diseño de Movimiento",
    "motion design: when animation serves the experience (and when it hurts it)": "Diseño de movimiento: cuando la animación sirve a la experiencia (y cuando la perjudica)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Nuestros ingenieros traducen diseños en código de calidad de producción. Limpio, eficiente y construido para escalar bajo carga del mundo real.",
    "our process,": "Nuestro proceso,",
    "our role": "Nuestro papel",
    "prefer a call? mention it in your message and we'll suggest a time slot.": "¿Prefieres una llamada? Menciónalo en tu mensaje y te sugeriremos un horario.",
    "purpose and legal basis": "Propósito y base legal",
    "read article": "Leer artículo",
    "ready to build": "Listo para construir",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "QA rigurosa, auditorías de rendimiento y un lanzamiento por etapas aseguran un lanzamiento impecable que causa la impresión correcta.",
    "schedule a call": "Programa una llamada",
    "send request": "Enviar solicitud",
    "services built": "Servicios construidos",
    "step by step.": "paso a paso.",
    "thank you. a member of the studio will reply within one business day.": "Gracias. Un miembro del estudio responderá dentro de un día hábil.",
    "the information published on this site is provided for general guidance and shall not engage the liability of the publisher.": "La información publicada en este sitio se proporciona como guía general y no compromete la responsabilidad del editor.",
    "the minds": "Las mentes",
    "this site does not use advertising tracking cookies. only technical cookies strictly necessary for the site to function may be used.": "Este sitio no utiliza cookies de seguimiento publicitario. Solo se pueden utilizar cookies técnicas estrictamente necesarias para el funcionamiento del sitio.",
    "we build empires.": "Construimos casas que perduran.",
    "we don't just": "No solo",
    "we don't just": "No solo",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Nos sumergimos en su negocio, sus usuarios y su panorama competitivo. La investigación profunda impulsa cada decisión que tomamos.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Solo aceptamos un número limitado de clientes por trimestre. Si tiene un proyecto, hablemos antes de que se agoten las plazas.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Trabajamos con un número selecto de clientes cada trimestre. Si tienes un proyecto en mente, hablemos antes de que se llenen los espacios.",
    "web design": "Diseño Web",
    "what": "Qué",
    "written by the impact studio team. provided for informational purposes.": "Escrito por el equipo de IMPACT Studio. Proporcionado con fines informativos.",
    "year": "Año",
    "years of craft": "Años de artesanía",
    "your rights": "Tus derechos",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Wir sind eine Kreativagentur, die außergewöhnliches Design mit erstklassiger Technik verbindet. Wir begleiten Visionäre bei digitalen Erlebnissen.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Gedanken, Methoden und Strategien des Teams zu Design, Technik und digitalem Wachstum.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Jenseits von SEO prägt die Ladegeschwindigkeit, wie Ihre Marke wahrgenommen wird und wie gut Ihre Seite konvertiert.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Ein gut gebautes Designsystem ist kein Agenturluxus: Es ist das Werkzeug, das Design und Entwicklung ausrichtet und Ihre Fristen verkürzt.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Wir decken Digitales von A bis Z ab: strategische Beratung, Markenidentität, Full-Stack-Entwicklung und Motion Design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Alle Fotografien dieser Website sind exklusives Eigentum des Studios Elena Korr, sofern nicht anders angegeben. Unsplash liefert die Platzhalterbilder.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Dieses Portfolio wurde mit Präzision gestaltet und entwickelt — mit Next.js, Tailwind CSS und Framer Motion für ein flüssiges, filmisches Erlebnis.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Wir verwenden moderne, gut lesbare Schriften, gewählt für die Balance aus Eleganz und Lesbarkeit, im Geist der Studioästhetik.",
    "the weight of light at dusk": "Das Gewicht des Lichts in der Dämmerung",
    "behind the scenes": "Hinter den Kulissen",
    "behind the lens: maison lumière": "Hinter der Linse: Maison Lumière",
    "finding geometry in the sahara": "Geometrie in der Sahara finden",
    "the philosophy of slow fashion": "Die Philosophie der Slow Fashion",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Ganzer bretonischer Hummer, Thermidor-Sauce mit Corail, Gratin dauphinois, Saisonkeimlinge",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Lammkarree in Kräuterkruste, provenzalischer Jus, Flageolet-Cassoulet, Lammbries",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Klassisches Soufflé mit Valrhona-Bitterschokolade 70 %, Vanille-Crème-anglaise, kandierte Orangenzesten",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Burgund, Frankreich · 2022 — Mineralisch, Feuerstein, weißes Steinobst",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Bordeaux, Frankreich · 2015 — Trüffel, dunkle Pflaume, Eisen — der Gipfel",
    "let's start a": "Starten wir ein",
    "project.": "Projekt.",
    "ready to elevate your digital presence? we're currently accepting new projects for q3. fill out the form below and we'll get back to you within 24 hours.": "Bereit, Ihre digitale Präsenz zu heben? Wir nehmen neue Projekte für das dritte Quartal an. Füllen Sie das Formular aus, wir melden uns binnen 24 Stunden.",
    "name": "Name",
    "project details": "Ihr Projekt",
    "contact information": "Unsere Kontaktdaten",
    "visit us": "Besuchen Sie uns",
    "a curated selection of our recent projects. we partner with ambitious brands to create digital experiences that stand out and deliver results.": "Eine Auswahl unserer jüngsten Projekte. Wir begleiten ehrgeizige Marken bei digitalen Erlebnissen, die herausstechen und Ergebnisse liefern.",
    "everything you need to know about novaplatform's pricing. built for speed, security, and developer experience.": "Alles Wissenswerte zu den Preisen von NovaPlatform. Gebaut für Geschwindigkeit, Sicherheit und Entwicklerkomfort.",
    "founded in": "Gegründet in",
    "in 2021, atelier noir is an independent fashion house dedicated to the art of quiet luxury. we reject the rapid cycles of fast fashion in favor of a slower, more deliberate method of creation.": "2021 gegründet, ist Atelier NOIR ein unabhängiges Modehaus, das sich der Kunst des leisen Luxus verschrieben hat. Wir lehnen die schnellen Zyklen der Fast Fashion zugunsten eines langsameren, bewussteren Schaffens ab.",
    "our garments are defined by architectural simplicity, meticulous tailoring, and exceptional materials. we work exclusively with certified natural fibers—organic cashmere, french flax linen, and japanese silk—sourced from mills that guarantee raw material traceability and ecological responsibility.": "Unsere Kleidung definiert sich durch architektonische Schlichtheit, sorgfältigen Schnitt und außergewöhnliche Materialien. Wir verarbeiten nur zertifizierte Naturfasern — Bio-Kaschmir, Leinen aus Frankreich, Seide aus Japan — aus Spinnereien mit garantierter Rückverfolgbarkeit und ökologischer Verantwortung.",
    "every piece is handcrafted to order in our parisian atelier by master artisans who bring decades of high-fashion experience. by making only what is ordered, we eliminate excess production and waste, creating garments that are as responsible as they are beautiful.": "Jedes Stück wird auf Bestellung in unserem Pariser Atelier von Meisterhandwerkern mit jahrzehntelanger Haute-Couture-Erfahrung gefertigt. Indem wir nur das Bestellte fertigen, vermeiden wir Überproduktion und Abfall: Kleidung, so verantwortungsvoll wie schön.",
    "founded in 2018, impact studio is a collective of designers, engineers, and strategists obsessed with excellence. we partner with ambitious brands — from seed-stage startups to fortune 500 companies — delivering work that consistently outperforms.": "Das 2018 gegründete Studio IMPACT vereint Designer, Entwickler und Strategen, die auf Exzellenz aus sind. Wir begleiten ehrgeizige Marken — vom jungen Start-up bis zum Konzern — mit Arbeit, die die gesetzten Ziele regelmäßig übertrifft.",
    "strategic thinking": "Strategisches Denken",
    "pixel perfection": "Pixelgenauigkeit",
    "clean code": "Sauberer Code",
    "fast delivery": "Schnelle Lieferung",
    "engineering": "Entwicklung",
    "development": "Entwicklung",
    "identity": "Identität",
    "branding": "Markenidentität",
    "strategy": "Strategie",
    "design motion": "Motion Design",
    "speed": "Geschwindigkeit",
    "performance": "Performance",
    "launch": "Livegang",
    "load testing, lighthouse audits, staging environments, go-live support.": "Lasttests, Lighthouse-Audits, Staging-Umgebungen, Begleitung am Tag des Livegangs.",
    "stakeholder interviews, user research, competitor analysis, technical audit.": "Gespräche mit den Beteiligten, Nutzerforschung, Wettbewerbsanalyse, technisches Audit.",
    "projects delivered": "Gelieferte Projekte",
    "web ecosystem": "Web-Ökosystem",
    "brand identity": "Markenidentität",
    "fintech app": "Fintech-App",
    "healthcare portal": "Gesundheitsportal",
    "saas platform": "SaaS-Plattform",
    "something great?": "etwas Großes?",
    "resources": "Ressourcen",
    "connect": "Folgen",
    "all articles": "Alle Artikel",
    "all work": "Alle Arbeiten",
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Schöne Arbeit, die nicht konvertiert, ist nur Dekoration. Wir messen unseren Erfolg an den Ergebnissen unserer Kunden.",
    "behind it.": "dahinter.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Maßgeschneiderte Schnittstellen, die mit pixelgenauer Präzision und strategischem UX-Denken entwickelt wurden, um Besucher in Kunden zu verwandeln.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Maßgeschneiderte Schnittstellen, die mit pixelgenauer Präzision und strategischem UX-Denken gestaltet sind, um Besucher in Kunden zu verwandeln.",
    "build": "Bauen",
    "build websites.": "Websites.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Kinematische Animationen und Mikrointeraktionen, die die Wahrnehmung erhöhen und jeden Berührungspunkt unvergesslich machen.",
    "client satisfaction": "Kundenzufriedenheit",
    "clients worldwide": "Kunden weltweit",
    "conversion funnels: five frictions that cost you customers": "Conversionstrichter: fünf Reibungen, die Sie Kunden kosten",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Optimierung der Core Web Vitals, CDN-Architektur und Infrastrukturabstimmung für Ladezeiten von unter einer Sekunde weltweit.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Optimierung der Core Web Vitals, CDN-Architektur und Infrastrukturabstimmung für Ladezeiten von unter einer Sekunde.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Datengetriebene Wachstumsstrategien, die sich im Laufe der Zeit summieren und eine dauerhafte Loyalität zu Ihrem Publikum aufbauen.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Datengetriebene Wachstumsstrategien, die sich im Laufe der Zeit summieren und Besucher in treue Markenbotschafter verwandeln.",
    "design": "Design",
    "design system, development": "Designsystem, Entwicklung",
    "design systems: the investment that speeds up every release": "Designsysteme: die Investition, die jede Veröffentlichung beschleunigt",
    "design, development, branding": "Design, Entwicklung, Branding",
    "design, development, motion": "Design, Entwicklung, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Unverwechselbare visuelle Identitäten, die tief mit Ihrem Publikum resonieren und Sie von Ihren Mitbewerbern abheben.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Unverwechselbare visuelle Identitäten, die tief mit Ihrer Zielgruppe resonieren und sich von Wettbewerbern abheben.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Jedes Pixel ist gewollt. Jede Interaktion ist durchdacht. Jede Codezeile ist auf Dauer geschrieben. Wir verbinden ästhetischen Anspruch mit messbarer Wirkung, denn schöne Arbeit, die nicht konvertiert, ist bloß Dekoration.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Jeder Pixel ist absichtlich. Wir glauben, dass Exzellenz in den Details lebt, die niemand bewusst bemerkt.",
    "for impact.": "für Wirkung.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "Von Design zu Code antizipieren wir Randfälle und bauen für die Ewigkeit. Eine schöne Seite, die abstürzt, ist nur ein gebrochenes Versprechen.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Von Wireframes bis hin zu hochauflösenden Prototypen gestalten wir Schnittstellen, die sowohl schön als auch funktional präzise sind.",
    "full-service creative studio crafting immersive digital experiences, brand identities, and high-performance products for ambitious brands.": "Vollständiges kreatives Studio, das immersive digitale Erlebnisse, Markenidentitäten und leistungsstarke Produkte für ehrgeizige Marken entwickelt.",
    "growth": "Wachstum",
    "guides us.": "führt uns.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Hochleistungsanwendungen, die auf modernen Stacks mit nahtlosen Integrationen und absoluter Zuverlässigkeit basieren.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Hochleistungsanwendungen, die auf modernen Stacks basieren, mit nahtlosen Integrationen und absoluter Zuverlässigkeit.",
    "internet's best.": "das Beste des Internets.",
    "let's talk": "Lass uns reden",
    "motion design": "Bewegungsdesign",
    "motion design: when animation serves the experience (and when it hurts it)": "Motion Design: wenn Animation das Erlebnis dient (und wenn es schadet)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Unsere Ingenieure übersetzen Designs in produktionsreifes Code. Sauber, leistungsfähig und für die Skalierung unter realen Lasten gebaut.",
    "our process,": "Unser Prozess,",
    "our role": "Unsere Rolle",
    "prefer a call? mention it in your message and we'll suggest a time slot.": "Bevorzugen Sie einen Anruf? Erwähnen Sie es in Ihrer Nachricht, und wir schlagen Ihnen einen Zeitrahmen vor.",
    "purpose and legal basis": "Zweck und rechtliche Grundlage",
    "read article": "Artikel lesen",
    "ready to build": "Bereit zu bauen",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "Strenge QA, Leistungsprüfungen und ein gestaffelter Rollout sorgen für einen fehlerfreien Start, der den richtigen ersten Eindruck hinterlässt.",
    "schedule a call": "Vereinbaren Sie einen Anruf",
    "send request": "Anfrage senden",
    "services built": "Dienste erstellt",
    "step by step.": "Schritt für Schritt.",
    "thank you. a member of the studio will reply within one business day.": "Danke. Ein Mitglied des Studios wird innerhalb eines Werktages antworten.",
    "the information published on this site is provided for general guidance and shall not engage the liability of the publisher.": "Die auf dieser Seite veröffentlichten Informationen dienen der allgemeinen Orientierung und begründen keine Haftung des Herausgebers.",
    "the minds": "Die Köpfe",
    "this site does not use advertising tracking cookies. only technical cookies strictly necessary for the site to function may be used.": "Diese Seite verwendet keine Werbe-Tracking-Cookies. Es dürfen nur technisch notwendige Cookies verwendet werden, die für die Funktion der Seite unbedingt erforderlich sind.",
    "we build empires.": "Wir bauen, was Bestand hat.",
    "we don't just": "Wir bauen nicht nur",
    "we don't just": "Wir machen nicht nur",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Wir tauchen in Ihr Geschäft, Ihre Nutzer und Ihr Wettbewerbsumfeld ein. Tiefgehende Forschung treibt jede Entscheidung, die wir treffen.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Wir nehmen pro Quartal nur wenige Kunden an. Wenn Sie ein Vorhaben haben, sprechen wir, bevor die Plätze vergeben sind.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Wir arbeiten jedes Quartal mit einer ausgewählten Anzahl von Kunden. Wenn Sie ein Projekt im Kopf haben, lassen Sie uns sprechen, bevor die Plätze vergeben sind.",
    "web design": "Webdesign",
    "what": "Was",
    "written by the impact studio team. provided for informational purposes.": "Geschrieben vom Team des IMPACT Studios. Bereitgestellt zu Informationszwecken.",
    "year": "Jahr",
    "years of craft": "Jahre des Handwerks",
    "your rights": "Ihre Rechte",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "we are a creative agency bridging the gap between exceptional design and world-class engineering. we partner with visionaries to craft digital experiences.": "Somos uma agência criativa que liga o design de exceção à engenharia de alto nível. Acompanhamos visionários nas suas experiências digitais.",
    "thoughts, frameworks, and strategies from our team on design, engineering, and digital growth.": "Reflexões, métodos e estratégias da equipa sobre design, engenharia e crescimento digital.",
    "beyond seo, load speed directly shapes how your brand is perceived and how well your site converts.": "Para além do SEO, a velocidade de carregamento molda a perceção da sua marca e a conversão do seu site.",
    "a well-built design system isn't an agency luxury: it's the tool that aligns design and development and cuts your timelines.": "Um sistema de design bem construído não é um luxo de agência: é a ferramenta que alinha design e desenvolvimento e encurta os seus prazos.",
    "we provide end-to-end digital solutions, from strategic consulting and brand identity to full-stack engineering and motion design.": "Cobrimos o digital de ponta a ponta: consultoria estratégica, identidade de marca, desenvolvimento full-stack e motion design.",
    "all photography featured on this website is the exclusive property of elena korr studio, unless otherwise noted. unsplash is used for placeholder imagery.": "Todas as fotografias deste site são propriedade exclusiva do estúdio Elena Korr, salvo indicação em contrário. O Unsplash fornece as imagens de demonstração.",
    "this portfolio was designed and developed with precision, utilizing next.js, tailwind css, and framer motion to create a fluid, cinematic experience.": "Este portefólio foi concebido e desenvolvido com precisão, com Next.js, Tailwind CSS e Framer Motion, para uma experiência fluida e cinematográfica.",
    "we use modern, legible fonts carefully selected to balance elegance and readability, reflecting the studio's contemporary aesthetic.": "Usamos tipos de letra modernos e legíveis, escolhidos para equilibrar elegância e legibilidade, à imagem da estética do estúdio.",
    "the weight of light at dusk": "O peso da luz ao crepúsculo",
    "behind the scenes": "Nos bastidores",
    "behind the lens: maison lumière": "Por trás da objetiva: Maison Lumière",
    "finding geometry in the sahara": "Encontrar a geometria no Saara",
    "the philosophy of slow fashion": "A filosofia da moda lenta",
    "whole blue lobster from brittany, coral thermidor sauce, gratin dauphinois, seasonal micro greens": "Lavagante azul da Bretanha inteiro, molho thermidor ao coral, gratinado dauphinois, rebentos da época",
    "rack of lamb, herb crust, provençal jus, flageolet bean cassoulet, lamb sweetbread": "Costeleta de borrego em crosta de ervas, molho à provençal, cassoulet de feijão, moleja de borrego",
    "classic soufflé with valrhona 70% dark chocolate, vanilla bean crème anglaise, candied orange zest": "Soufflé clássico de chocolate negro Valrhona 70 %, creme inglês de baunilha, raspas de laranja cristalizadas",
    "domaine william fèvre · burgundy, france · 2022 — mineral, flint, and white stone fruit": "Domaine William Fèvre · Borgonha, França · 2022 — Mineral, sílex, fruta branca de caroço",
    "pomerol aoc · bordeaux, france · 2015 — truffles, dark plum, iron — the pinnacle": "Pomerol AOC · Bordéus, França · 2015 — Trufa, ameixa preta, ferro — o cume",
    "let's start a": "Vamos lançar um",
    "project.": "projeto.",
    "ready to elevate your digital presence? we're currently accepting new projects for q3. fill out the form below and we'll get back to you within 24 hours.": "Pronto para elevar a sua presença digital? Aceitamos novos projetos para o terceiro trimestre. Preencha o formulário e responderemos em 24 horas.",
    "name": "Nome",
    "project details": "O seu projeto",
    "contact information": "Os nossos contactos",
    "visit us": "Visite-nos",
    "a curated selection of our recent projects. we partner with ambitious brands to create digital experiences that stand out and deliver results.": "Uma seleção dos nossos projetos recentes. Acompanhamos marcas ambiciosas para criar experiências digitais que se destacam e dão resultados.",
    "everything you need to know about novaplatform's pricing. built for speed, security, and developer experience.": "Tudo o que há para saber sobre os preços da NovaPlatform. Pensados para a velocidade, a segurança e o conforto de programação.",
    "founded in": "Fundada em",
    "in 2021, atelier noir is an independent fashion house dedicated to the art of quiet luxury. we reject the rapid cycles of fast fashion in favor of a slower, more deliberate method of creation.": "em 2021, o Atelier NOIR é uma casa de moda independente dedicada à arte do luxo discreto. Recusamos os ciclos rápidos da fast fashion em favor de uma criação mais lenta e deliberada.",
    "our garments are defined by architectural simplicity, meticulous tailoring, and exceptional materials. we work exclusively with certified natural fibers—organic cashmere, french flax linen, and japanese silk—sourced from mills that guarantee raw material traceability and ecological responsibility.": "As nossas peças definem-se por uma simplicidade arquitetónica, um corte meticuloso e matérias de exceção. Só trabalhamos fibras naturais certificadas — caxemira biológica, linho de França, seda do Japão — de fiações que garantem a rastreabilidade e a responsabilidade ecológica.",
    "every piece is handcrafted to order in our parisian atelier by master artisans who bring decades of high-fashion experience. by making only what is ordered, we eliminate excess production and waste, creating garments that are as responsible as they are beautiful.": "Cada peça é confecionada por encomenda no nosso atelier parisiense por mestres artesãos com décadas de alta-costura. Ao produzir apenas o encomendado, eliminamos a sobreprodução e o desperdício: peças tão responsáveis quanto belas.",
    "founded in 2018, impact studio is a collective of designers, engineers, and strategists obsessed with excellence. we partner with ambitious brands — from seed-stage startups to fortune 500 companies — delivering work that consistently outperforms.": "Fundado em 2018, o estúdio IMPACT reúne designers, programadores e estrategas obcecados pela excelência. Acompanhamos marcas ambiciosas — da jovem empresa ao grande grupo — com um trabalho que supera regularmente os objetivos.",
    "strategic thinking": "Pensamento estratégico",
    "pixel perfection": "Precisão ao pixel",
    "clean code": "Código limpo",
    "fast delivery": "Entrega rápida",
    "engineering": "Desenvolvimento",
    "development": "Desenvolvimento",
    "identity": "Identidade",
    "branding": "Identidade de marca",
    "strategy": "Estratégia",
    "design motion": "Motion design",
    "speed": "Velocidade",
    "performance": "Desempenho",
    "launch": "Colocação em linha",
    "load testing, lighthouse audits, staging environments, go-live support.": "Testes de carga, auditorias Lighthouse, ambientes de pré-produção, acompanhamento no dia do lançamento.",
    "stakeholder interviews, user research, competitor analysis, technical audit.": "Entrevistas com as partes interessadas, estudo dos utilizadores, análise da concorrência, auditoria técnica.",
    "projects delivered": "Projetos entregues",
    "web ecosystem": "Ecossistema web",
    "brand identity": "Identidade de marca",
    "fintech app": "Aplicação fintech",
    "healthcare portal": "Portal de saúde",
    "saas platform": "Plataforma SaaS",
    "something great?": "algo grande?",
    "resources": "Recursos",
    "connect": "Siga-nos",
    "all articles": "Todos os artigos",
    "all work": "Todo o trabalho",
    "beautiful work that doesn't convert is just decoration. we measure our success by our clients' results.": "Um trabalho bonito que não converte é apenas decoração. Medimos nosso sucesso pelos resultados de nossos clientes.",
    "behind it.": "por trás disso.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that converts visitors into customers.": "Interfaces personalizadas criadas com precisão perfeita de pixels e pensamento estratégico de UX que converte visitantes em clientes.",
    "bespoke interfaces crafted with pixel-perfect precision and strategic ux thinking that turns visitors into customers.": "Interfaces personalizadas criadas com precisão perfeita em pixels e um pensamento estratégico de UX que transforma visitantes em clientes.",
    "build": "Construir",
    "build websites.": "sites.",
    "cinematic animations and micro-interactions that elevate perception and make every touchpoint memorable.": "Animações cinematográficas e microinterações que elevam a percepção e tornam cada ponto de contato memorável.",
    "client satisfaction": "Satisfação do cliente",
    "clients worldwide": "Clientes em todo o mundo",
    "conversion funnels: five frictions that cost you customers": "Funis de conversão: cinco fricções que lhe custam clientes",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times globally.": "Otimização dos Core Web Vitals, arquitetura CDN e ajuste de infraestrutura para tempos de carregamento abaixo de um segundo globalmente.",
    "core web vitals optimization, cdn architecture, and infrastructure tuning for sub-second load times.": "Otimização dos Core Web Vitals, arquitetura CDN e ajuste de infraestrutura para tempos de carregamento abaixo de um segundo.",
    "data-driven growth strategies that compound over time and build lasting loyalty with your audience.": "Estratégias de crescimento orientadas por dados que se acumulam ao longo do tempo e constroem lealdade duradoura com o seu público.",
    "data-driven growth strategies that compound over time, converting visitors into loyal brand advocates.": "Estratégias de crescimento orientadas por dados que se acumulam ao longo do tempo, convertendo visitantes em defensores leais da marca.",
    "design": "Design",
    "design system, development": "Sistema de design, Desenvolvimento",
    "design systems: the investment that speeds up every release": "Sistemas de design: o investimento que acelera cada lançamento",
    "design, development, branding": "Design, Desenvolvimento, Branding",
    "design, development, motion": "Design, Desenvolvimento, Motion",
    "distinctive visual identities that resonate deeply with your audience and set you apart from competitors.": "Identidades visuais distintas que ressoam profundamente com o seu público e o diferenciam dos concorrentes.",
    "distinctive visual identities that resonate deeply with your target audience and stand apart from competitors.": "Identidades visuais distintas que ressoam profundamente com o seu público-alvo e se destacam dos concorrentes.",
    "every pixel is intentional. every interaction is engineered. every line of code is written to last. we combine aesthetic excellence with measurable business impact because beautiful work that doesn't convert is just decoration.": "Cada píxel é intencional. Cada interação é pensada. Cada linha de código é escrita para durar. Juntamos a exigência estética a um efeito mensurável, porque um belo trabalho que não converte é apenas decoração.",
    "every pixel is intentional. we believe excellence lives in the details no one consciously notices.": "Cada pixel é intencional. Acreditamos que a excelência vive nos detalhes que ninguém nota conscientemente.",
    "for impact.": "para impacto.",
    "from design to code, we anticipate edge cases and build to last. a beautiful site that breaks is just a broken promise.": "Do design ao código, antecipamos casos extremos e construímos para durar. Um site bonito que quebra é apenas uma promessa quebrada.",
    "from wireframes to high-fidelity prototypes, we craft interfaces that are both beautiful and functionally precise.": "Desde wireframes até protótipos de alta fidelidade, criamos interfaces que são tanto bonitas quanto funcionalmente precisas.",
    "full-service creative studio crafting immersive digital experiences, brand identities, and high-performance products for ambitious brands.": "Estúdio criativo de serviço completo que cria experiências digitais imersivas, identidades de marca e produtos de alto desempenho para marcas ambiciosas.",
    "growth": "Crescimento",
    "guides us.": "nos guia.",
    "high-performance applications built on modern stacks with seamless integrations and bulletproof reliability.": "Aplicações de alto desempenho construídas em pilhas modernas com integrações perfeitas e fiabilidade à prova de falhas.",
    "high-performance applications built on modern stacks, with seamless integrations and bulletproof reliability.": "Aplicações de alto desempenho construídas em pilhas modernas, com integrações perfeitas e fiabilidade à prova de falhas.",
    "internet's best.": "o melhor da internet.",
    "let's talk": "Vamos falar",
    "motion design": "Design de Movimento",
    "motion design: when animation serves the experience (and when it hurts it)": "Design de movimento: quando a animação serve a experiência (e quando a prejudica)",
    "our engineers translate designs into production-grade code. clean, performant, and built to scale under real-world load.": "Os nossos engenheiros traduzem designs em código de qualidade de produção. Limpo, eficiente e construído para escalar sob carga do mundo real.",
    "our process,": "O nosso processo,",
    "our role": "O nosso papel",
    "prefer a call? mention it in your message and we'll suggest a time slot.": "Prefere uma chamada? Mencione isso na sua mensagem e sugeriremos um horário.",
    "purpose and legal basis": "Propósito e base legal",
    "read article": "Ler artigo",
    "ready to build": "Pronto para construir",
    "rigorous qa, performance audits, and a staged rollout ensure a flawless launch that makes the right first impression.": "QA rigorosa, auditorias de desempenho e um lançamento em etapas garantem um lançamento impecável que causa a impressão certa.",
    "schedule a call": "Agende uma chamada",
    "send request": "Enviar pedido",
    "services built": "Serviços construídos",
    "step by step.": "passo a passo.",
    "thank you. a member of the studio will reply within one business day.": "Obrigado. Um membro do estúdio responderá dentro de um dia útil.",
    "the information published on this site is provided for general guidance and shall not engage the liability of the publisher.": "As informações publicadas neste site são fornecidas para orientação geral e não comprometem a responsabilidade do editor.",
    "the minds": "As mentes",
    "this site does not use advertising tracking cookies. only technical cookies strictly necessary for the site to function may be used.": "Este site não utiliza cookies de rastreamento publicitário. Apenas cookies técnicos estritamente necessários para o funcionamento do site podem ser utilizados.",
    "we build empires.": "Construímos casas que perduram.",
    "we don't just": "Não fazemos apenas",
    "we don't just": "Não fazemos apenas",
    "we immerse ourselves in your business, your users, and your competitive landscape. deep research drives every decision we make.": "Mergulhamos no seu negócio, nos seus usuários e no seu panorama competitivo. Uma pesquisa aprofundada orienta cada decisão que tomamos.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Só aceitamos um número limitado de clientes por trimestre. Se tem um projeto, falemos antes de as vagas se esgotarem.",
    "we work with a select number of clients each quarter. if you have a project in mind, let's talk before spots fill.": "Trabalhamos com um número selecionado de clientes a cada trimestre. Se você tiver um projeto em mente, vamos conversar antes que os lugares se preencham.",
    "web design": "Design de Websites",
    "what": "O que",
    "written by the impact studio team. provided for informational purposes.": "Escrito pela equipe do IMPACT Studio. Fornecido para fins informativos.",
    "year": "Ano",
    "years of craft": "Anos de artesanato",
    "your rights": "Seus direitos",
  },
};
