/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "pure": "La pure",
    "ethics": "Éthique",
    "biology.": "biologie.",
    "research data": "Données de recherche",
    "latency threshold": "Seuil de latence",
    "sync latency": "Latence de synchronisation",
    "biocompatibility": "Biocompatibilité",
    "active users": "Porteurs actifs",
    "r&d patents": "Brevets déposés",
    "hardware": "Matériel",
    "optics": "Optique",
    "molecular sovereignty": "Souveraineté moléculaire",
    "synthesis.": "synthèse.",
    "molecular synthesis": "Synthèse moléculaire",
    "sourcing integrity": "Intégrité des matières",
    "neural bridging": "Pont neuronal",
    "eco-biological cycle": "Cycle éco-biologique",
    "architecture.": "architecture.",
    "sync.": "synchronisation.",
    "1:1 synapse match": "Correspondance synaptique 1:1",
    "zero systemic residue": "Aucun résidu systémique",
    "sub-ms bridging": "Pont sous la milliseconde",
    "augmented": "Augmenté",
    "empirical evidence": "Preuves cliniques",
    "validation.": "validation.",
    "neural plasticity": "Plasticité neuronale",
    "94.2% success": "94,2 % de réussite",
    "long-term study on synaptic bridge stability across 10 000 subjects over a 24-month period.": "Étude au long cours sur la stabilité du pont synaptique, menée sur 10 000 sujets pendant vingt-quatre mois.",
    "0.02% rejection": "0,02 % de rejet",
    "cognitive load": "Charge cognitive",
    "3.2x bandwidth": "3,2× de bande passante",
    "fortress protocol": "Protocole forteresse",
    "trust.": "confiance.",
    "encryption": "Chiffrement",
    "fail-safe": "Sécurité passive",
    "hardware kill": "Coupure matérielle",
    "audits": "Audits",
    "operational grid": "Réseau opérationnel",
    "nodes.": "nœuds.",
    "latency": "Latence",
    "peak load": "Charge maximale",
    "optimizing": "Optimisation",
    "rights.": "droits.",
    "data sovereignty": "Souveraineté des données",
    "biological integrity": "Intégrité biologique",
    "cognitive liberty": "Liberté cognitive",
    "compliance.": "conformité.",
    "audit status": "État de l'audit",
    "hardware schematics": "Schémas techniques",
    "manifesto.": "manifeste.",
    "parameter": "Paramètre",
    "processing power": "Puissance de calcul",
    "n/a (chemical)": "Sans objet (chimique)",
    "bio-latency": "Bio-latence",
    "instant": "Instantané",
    "battery life": "Autonomie",
    "indefinite (kinetic)": "Illimitée (cinétique)",
    "material": "Matériau",
    "liquid graphene": "Graphène liquide",
    "synthetic serum": "Sérum synthétique",
    "refractive glass": "Verre réfractif",
    "clearance": "Habilitation",
    "user experiences": "Témoignages",
    "quantum architect": "Architecte quantique",
    "synthetic biologist": "Biologiste de synthèse",
    "common": "Questions",
    "queries.": "fréquentes.",
    "provenance": "Provenance",
    "tame your": "Domptez votre",
    "your brain is the final frontier of privacy. our neural security layer implements hardware-level encryption that physically disconnects the bridge if any external intrusion is detected. no cloud, no backdoors, no exceptions.": "Votre cerveau est la dernière frontière de la vie privée. Notre couche de sécurité neurale chiffre au niveau du matériel et coupe physiquement le pont dès qu'une intrusion est détectée. Pas de nuage, pas de porte dérobée, pas d'exception.",
    "at neuralis, we believe augmentation is a fundamental right. our governance board ensures every neural bridge is encrypted locally, giving you absolute sovereignty over your own biological data.": "Pour nous, l'augmentation est un droit fondamental. Notre comité de gouvernance garantit que chaque pont neural est chiffré localement : vous restez souverain de vos propres données biologiques.",
    "a sub-dermal haptic relay providing 1:1 sensory mapping between physical and digital environments.": "Un relais haptique sous-cutané fournissant une cartographie sensorielle 1:1 entre les environnements physiques et numériques.",
    "achieve sub-millisecond latency in thought-to-command execution with our proprietary bridge protocols.": "Atteignez une latence inférieure à la milliseconde dans l'exécution de la pensée à la commande avec nos protocoles de pont propriétaires.",
    "are there any side effects?": "Y a-t-il des effets secondaires ?",
    "beyond the interface. we design biological extensions that merge the raw power of synthetic processing with the elegant complexity of human neurology.": "Au-delà de l'interface. Nous concevons des extensions biologiques qui fusionnent la puissance brute du traitement synthétique avec la complexité élégante de la neurologie humaine.",
    "biocompatibility testing for synthetic serum integration within pulmonary and cardiovascular systems.": "Tests de biocompatibilité pour l'intégration de sérum synthétique dans les systèmes pulmonaire et cardiovasculaire.",
    "can i disable the augmentation at any time?": "Puis-je désactiver l'augmentation à tout moment ?",
    "client portal": "Portail Client",
    "enter the atelier": "Entrer dans l'atelier",
    "every augmentation is 100% recyclable within the human biological loop, ensuring zero systemic residue.": "Chaque augmentation est 100 % recyclable dans le cycle biologique humain, garantissant zéro résidu systémique.",
    "every neuralis bridge is certified by the global augmentation council (gac) for safety class-s integration.": "Chaque pont Neuralis est certifié par le Global Augmentation Council (GAC) pour une intégration de classe de sécurité S.",
    "how do you handle firmware updates?": "Comment gérez-vous les mises à jour ?",
    "is the installation process invasive?": "La pose est-elle invasive ?",
    "long-term study on synaptic bridge stability across 10,000 subjects over a 24-month period.": "Étude à long terme sur la stabilité des ponts synaptiques chez 10 000 sujets sur une période de 24 mois.",
    "new york": "New York",
    "no external overrides. our firmware is open-source and audited by third-party ethics councils.": "Pas de contournements externes. Notre firmware est open-source et audité par des conseils d'éthique tiers.",
    "our lab utilizes 4d molecular printing to create biocompatible materials that evolve with your cellular structure.": "Notre laboratoire emploie l'impression moléculaire en quatre dimensions pour créer des matières biocompatibles qui évoluent avec vos cellules.",
    "our liquid-graphene bridges are designed to last a lifetime. they evolve with your cellular structure and are powered by your body's own kinetic energy.": "Nos ponts en graphène liquide sont conçus pour durer toute une vie. Ils évoluent avec votre structure cellulaire et sont alimentés par l'énergie cinétique de votre corps.",
    "oxy-flow is the first augmentation that feels truly native. the focus is sustained, clinical, and entirely without the jitters of chemical stimulants.": "Oxy-Flow est la première augmentation qui se sent vraiment native. La concentration est soutenue, clinique et totalement sans les tremblements des stimulants chimiques.",
    "real time": "Temps Réel",
    "real-world testing of prism ar data visualization during high-stress operational environments.": "Tests en conditions réelles de la visualisation de données Prism AR dans des environnements opérationnels à forte pression.",
    "request diagnostic scan": "Demander un scan diagnostique",
    "retinal projection system with 32k resolution and integrated neural eye-tracking.": "Système de projection rétinienne avec une résolution de 32k et un suivi oculaire neural intégré.",
    "synthetic blood enhancement that increases oxygen transport to the prefrontal cortex by 40%.": "Amélioration du sang synthétique qui augmente le transport d'oxygène vers le cortex préfrontal de 40%.",
    "the absolute mastery of bio-synthetic integration. engineered for the evolutionary elite in our tokyo sanctuary.": "La maîtrise absolue de l'intégration biosynthétique. Conçue dans notre atelier de Tokyo.",
    "the apex of neuro-synthetic integration. engineered for the evolutionary elite.": "Le sommet de l'intégration neuro-synthétique. Conçu pour l'élite évolutive.",
    "the maison": "La Maison",
    "the moral compass": "La boussole morale",
    "the neural link didn't just improve my workflow; it changed my perception of mathematical structures. i'm no longer visualizing data—i'm inhabiting it.": "Le Neural Link n'a pas seulement amélioré mon flux de travail ; il a changé ma perception des structures mathématiques. Je ne visualise plus les données, je les habite.",
    "updates are pushed via encrypted neural-burst protocols. you will be notified in your hud, and updates are only applied with explicit neural authorization.": "Les mises à jour sont envoyées via des protocoles de burst neural cryptés. Vous serez notifié dans votre HUD, et les mises à jour ne sont appliquées qu'avec une autorisation neuronale explicite.",
    "view all research logs": "Voir tous les carnets de recherche",
    "what is the lifespan of the hardware?": "Quelle est la durée de vie du matériel ?",
    "yes. every neuralis device includes a physical 'kill-switch' and a software-based 'dormant mode' which can be toggled via your encrypted client portal.": "Oui. Chaque appareil Neuralis comprend un 'Kill-Switch' physique et un 'Mode Dormant' basé sur logiciel qui peut être activé via votre portail client crypté.",
    "your neural patterns never leave your local bridge. we provide the hardware, you own the thoughts.": "Vos schémas neuronaux ne quittent jamais votre passerelle. Nous fournissons le matériel, les pensées vous appartiennent.",
    "zero-residue materials that can be fully integrated or removed without cellular trauma.": "Matériaux sans résidu qui peuvent être entièrement intégrés ou retirés sans traumatisme cellulaire.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "pure": "La pura",
    "ethics": "Ética",
    "biology.": "biología.",
    "research data": "Datos de investigación",
    "latency threshold": "Umbral de latencia",
    "sync latency": "Latencia de sincronización",
    "biocompatibility": "Biocompatibilidad",
    "active users": "Usuarios activos",
    "r&d patents": "Patentes registradas",
    "hardware": "Hardware",
    "optics": "Óptica",
    "molecular sovereignty": "Soberanía molecular",
    "synthesis.": "síntesis.",
    "molecular synthesis": "Síntesis molecular",
    "sourcing integrity": "Integridad de los materiales",
    "neural bridging": "Puente neuronal",
    "eco-biological cycle": "Ciclo ecobiológico",
    "architecture.": "arquitectura.",
    "sync.": "sincronización.",
    "1:1 synapse match": "Correspondencia sináptica 1:1",
    "zero systemic residue": "Sin residuo sistémico",
    "sub-ms bridging": "Puente por debajo del milisegundo",
    "augmented": "Aumentado",
    "empirical evidence": "Pruebas clínicas",
    "validation.": "validación.",
    "neural plasticity": "Plasticidad neuronal",
    "94.2% success": "94,2 % de éxito",
    "long-term study on synaptic bridge stability across 10 000 subjects over a 24-month period.": "Estudio a largo plazo sobre la estabilidad del puente sináptico, realizado en 10 000 sujetos durante veinticuatro meses.",
    "0.02% rejection": "0,02 % de rechazo",
    "cognitive load": "Carga cognitiva",
    "3.2x bandwidth": "3,2× de ancho de banda",
    "fortress protocol": "Protocolo fortaleza",
    "trust.": "confianza.",
    "encryption": "Cifrado",
    "fail-safe": "Seguridad pasiva",
    "hardware kill": "Corte por hardware",
    "audits": "Auditorías",
    "operational grid": "Red operativa",
    "nodes.": "nodos.",
    "latency": "Latencia",
    "peak load": "Carga máxima",
    "optimizing": "Optimizando",
    "rights.": "derechos.",
    "data sovereignty": "Soberanía de los datos",
    "biological integrity": "Integridad biológica",
    "cognitive liberty": "Libertad cognitiva",
    "compliance.": "conformidad.",
    "audit status": "Estado de la auditoría",
    "hardware schematics": "Esquemas técnicos",
    "manifesto.": "manifiesto.",
    "parameter": "Parámetro",
    "processing power": "Potencia de cálculo",
    "n/a (chemical)": "No aplica (químico)",
    "bio-latency": "Biolatencia",
    "instant": "Instantáneo",
    "battery life": "Autonomía",
    "indefinite (kinetic)": "Ilimitada (cinética)",
    "material": "Material",
    "liquid graphene": "Grafeno líquido",
    "synthetic serum": "Suero sintético",
    "refractive glass": "Vidrio refractivo",
    "clearance": "Habilitación",
    "user experiences": "Testimonios",
    "quantum architect": "Arquitecto cuántico",
    "synthetic biologist": "Bióloga sintética",
    "common": "Preguntas",
    "queries.": "frecuentes.",
    "provenance": "Procedencia",
    "tame your": "Dome su",
    "your brain is the final frontier of privacy. our neural security layer implements hardware-level encryption that physically disconnects the bridge if any external intrusion is detected. no cloud, no backdoors, no exceptions.": "Su cerebro es la última frontera de la privacidad. Nuestra capa de seguridad neuronal cifra a nivel de hardware y corta físicamente el puente en cuanto detecta una intrusión. Sin nube, sin puertas traseras, sin excepciones.",
    "at neuralis, we believe augmentation is a fundamental right. our governance board ensures every neural bridge is encrypted locally, giving you absolute sovereignty over your own biological data.": "Para nosotros, la aumentación es un derecho fundamental. Nuestro comité de gobernanza garantiza que cada puente neuronal se cifra localmente: usted sigue siendo soberano de sus propios datos biológicos.",
    "a sub-dermal haptic relay providing 1:1 sensory mapping between physical and digital environments.": "Un relé háptico subdérmico que proporciona un mapeo sensorial 1:1 entre entornos físicos y digitales.",
    "achieve sub-millisecond latency in thought-to-command execution with our proprietary bridge protocols.": "Logra una latencia de menos de un milisegundo en la ejecución de pensamiento a comando con nuestros protocolos de puente patentados.",
    "are there any side effects?": "¿Hay efectos secundarios?",
    "beyond the interface. we design biological extensions that merge the raw power of synthetic processing with the elegant complexity of human neurology.": "Más allá de la interfaz. Diseñamos extensiones biológicas que fusionan el poder bruto del procesamiento sintético con la complejidad elegante de la neurología humana.",
    "biocompatibility testing for synthetic serum integration within pulmonary and cardiovascular systems.": "Pruebas de biocompatibilidad para la integración de suero sintético en los sistemas pulmonar y cardiovascular.",
    "can i disable the augmentation at any time?": "¿Puedo desactivar la mejora en cualquier momento?",
    "client portal": "Portal del Cliente",
    "enter the atelier": "Entrar en el taller",
    "every augmentation is 100% recyclable within the human biological loop, ensuring zero systemic residue.": "Cada augmentación es 100% reciclable dentro del ciclo biológico humano, asegurando cero residuos sistémicos.",
    "every neuralis bridge is certified by the global augmentation council (gac) for safety class-s integration.": "Cada puente Neuralis está certificado por el Global Augmentation Council (GAC) para la integración de Clase de Seguridad S.",
    "how do you handle firmware updates?": "¿Cómo gestionan las actualizaciones?",
    "is the installation process invasive?": "¿La colocación es invasiva?",
    "long-term study on synaptic bridge stability across 10,000 subjects over a 24-month period.": "Estudio a largo plazo sobre la estabilidad del puente sináptico en 10,000 sujetos durante un período de 24 meses.",
    "new york": "Nueva York",
    "no external overrides. our firmware is open-source and audited by third-party ethics councils.": "Sin anulación externa. Nuestro firmware es de código abierto y auditado por consejos de ética de terceros.",
    "our lab utilizes 4d molecular printing to create biocompatible materials that evolve with your cellular structure.": "Nuestro laboratorio emplea la impresión molecular en cuatro dimensiones para crear materias biocompatibles que evolucionan con sus células.",
    "our liquid-graphene bridges are designed to last a lifetime. they evolve with your cellular structure and are powered by your body's own kinetic energy.": "Nuestros puentes de grafeno líquido están diseñados para durar toda la vida. Evolucionan con tu estructura celular y son alimentados por la energía cinética de tu cuerpo.",
    "oxy-flow is the first augmentation that feels truly native. the focus is sustained, clinical, and entirely without the jitters of chemical stimulants.": "Oxy-Flow es la primera augmentación que se siente verdaderamente nativa. El enfoque es sostenido, clínico y completamente libre de los nervios de los estimulantes químicos.",
    "real time": "Tiempo Real",
    "real-world testing of prism ar data visualization during high-stress operational environments.": "Pruebas en el mundo real de la visualización de datos Prism AR durante entornos operativos de alta presión.",
    "request diagnostic scan": "Solicitar escaneo diagnóstico",
    "retinal projection system with 32k resolution and integrated neural eye-tracking.": "Sistema de proyección retinal con resolución de 32k y seguimiento ocular neural integrado.",
    "synthetic blood enhancement that increases oxygen transport to the prefrontal cortex by 40%.": "Mejora de sangre sintética que aumenta el transporte de oxígeno al córtex prefrontal en un 40%.",
    "the absolute mastery of bio-synthetic integration. engineered for the evolutionary elite in our tokyo sanctuary.": "El dominio absoluto de la integración biosintética. Concebido en nuestro taller de Tokio.",
    "the apex of neuro-synthetic integration. engineered for the evolutionary elite.": "El apogeo de la integración neuro-sintética. Diseñado para la élite evolutiva.",
    "the maison": "La Maison",
    "the moral compass": "La brújula moral",
    "the neural link didn't just improve my workflow; it changed my perception of mathematical structures. i'm no longer visualizing data—i'm inhabiting it.": "El Neural Link no solo mejoró mi flujo de trabajo; cambió mi percepción de las estructuras matemáticas. Ya no visualizo datos, los habito.",
    "updates are pushed via encrypted neural-burst protocols. you will be notified in your hud, and updates are only applied with explicit neural authorization.": "Las actualizaciones se envían a través de protocolos de ráfaga neural encriptados. Se le notificará en su HUD, y las actualizaciones solo se aplican con autorización neural explícita.",
    "view all research logs": "Ver todos los cuadernos de investigación",
    "what is the lifespan of the hardware?": "¿Cuál es la vida útil del equipo?",
    "yes. every neuralis device includes a physical 'kill-switch' and a software-based 'dormant mode' which can be toggled via your encrypted client portal.": "Sí. Cada dispositivo Neuralis incluye un 'Kill-Switch' físico y un 'Modo Dormido' basado en software que se puede activar a través de su portal de cliente encriptado.",
    "your neural patterns never leave your local bridge. we provide the hardware, you own the thoughts.": "Sus patrones neuronales nunca salen de su pasarela. Nosotros damos el equipo, los pensamientos son suyos.",
    "zero-residue materials that can be fully integrated or removed without cellular trauma.": "Materiales sin residuos que pueden integrarse o eliminarse completamente sin trauma celular.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "pure": "Die reine",
    "ethics": "Ethik",
    "biology.": "Biologie.",
    "research data": "Forschungsdaten",
    "latency threshold": "Latenzschwelle",
    "sync latency": "Sync-Latenz",
    "biocompatibility": "Biokompatibilität",
    "active users": "Aktive Träger",
    "r&d patents": "Angemeldete Patente",
    "hardware": "Hardware",
    "optics": "Optik",
    "molecular sovereignty": "Molekulare Souveränität",
    "synthesis.": "Synthese.",
    "molecular synthesis": "Molekulare Synthese",
    "sourcing integrity": "Integrität der Materialien",
    "neural bridging": "Neuronale Brücke",
    "eco-biological cycle": "Öko-biologischer Kreislauf",
    "architecture.": "Architektur.",
    "sync.": "Synchronisation.",
    "1:1 synapse match": "1:1-Synapsenabgleich",
    "zero systemic residue": "Kein systemischer Rückstand",
    "sub-ms bridging": "Brücke unter einer Millisekunde",
    "augmented": "Erweitert",
    "empirical evidence": "Klinische Belege",
    "validation.": "Validierung.",
    "neural plasticity": "Neuronale Plastizität",
    "94.2% success": "94,2 % Erfolg",
    "long-term study on synaptic bridge stability across 10 000 subjects over a 24-month period.": "Langzeitstudie zur Stabilität der synaptischen Brücke an 10 000 Probanden über vierundzwanzig Monate.",
    "0.02% rejection": "0,02 % Abstoßung",
    "cognitive load": "Kognitive Last",
    "3.2x bandwidth": "3,2× Bandbreite",
    "fortress protocol": "Festungsprotokoll",
    "trust.": "Vertrauen.",
    "encryption": "Verschlüsselung",
    "fail-safe": "Ausfallsicherung",
    "hardware kill": "Hardware-Abschaltung",
    "audits": "Audits",
    "operational grid": "Betriebsnetz",
    "nodes.": "Knoten.",
    "latency": "Latenz",
    "peak load": "Spitzenlast",
    "optimizing": "Optimierung",
    "rights.": "Rechte.",
    "data sovereignty": "Datensouveränität",
    "biological integrity": "Biologische Integrität",
    "cognitive liberty": "Kognitive Freiheit",
    "compliance.": "Konformität.",
    "audit status": "Audit-Status",
    "hardware schematics": "Technische Schaltpläne",
    "manifesto.": "Manifest.",
    "parameter": "Parameter",
    "processing power": "Rechenleistung",
    "n/a (chemical)": "Entfällt (chemisch)",
    "bio-latency": "Bio-Latenz",
    "instant": "Sofort",
    "battery life": "Laufzeit",
    "indefinite (kinetic)": "Unbegrenzt (kinetisch)",
    "material": "Material",
    "liquid graphene": "Flüssiges Graphen",
    "synthetic serum": "Synthetisches Serum",
    "refractive glass": "Refraktives Glas",
    "clearance": "Freigabestufe",
    "user experiences": "Erfahrungsberichte",
    "quantum architect": "Quantenarchitekt",
    "synthetic biologist": "Synthetische Biologin",
    "common": "Häufige",
    "queries.": "Fragen.",
    "provenance": "Herkunft",
    "tame your": "Zähmen Sie Ihr",
    "your brain is the final frontier of privacy. our neural security layer implements hardware-level encryption that physically disconnects the bridge if any external intrusion is detected. no cloud, no backdoors, no exceptions.": "Ihr Gehirn ist die letzte Grenze der Privatsphäre. Unsere neuronale Sicherheitsschicht verschlüsselt auf Hardware-Ebene und trennt die Brücke physisch, sobald ein Eindringen erkannt wird. Keine Cloud, keine Hintertüren, keine Ausnahmen.",
    "at neuralis, we believe augmentation is a fundamental right. our governance board ensures every neural bridge is encrypted locally, giving you absolute sovereignty over your own biological data.": "Für uns ist Augmentierung ein Grundrecht. Unser Governance-Gremium stellt sicher, dass jede neuronale Brücke lokal verschlüsselt wird: Sie bleiben souverän über Ihre eigenen biologischen Daten.",
    "a sub-dermal haptic relay providing 1:1 sensory mapping between physical and digital environments.": "Ein subdermales haptisches Relais, das eine 1:1 sensorische Abbildung zwischen physischen und digitalen Umgebungen bietet.",
    "achieve sub-millisecond latency in thought-to-command execution with our proprietary bridge protocols.": "Erreichen Sie eine Latenz von unter einer Millisekunde bei der Ausführung von Gedanken zu Befehlen mit unseren proprietären Brückenprotokollen.",
    "are there any side effects?": "Gibt es Nebenwirkungen?",
    "beyond the interface. we design biological extensions that merge the raw power of synthetic processing with the elegant complexity of human neurology.": "Jenseits der Schnittstelle. Wir entwerfen biologische Erweiterungen, die die rohe Kraft der synthetischen Verarbeitung mit der eleganten Komplexität der menschlichen Neurologie verbinden.",
    "biocompatibility testing for synthetic serum integration within pulmonary and cardiovascular systems.": "Biokompatibilitätstests für die Integration von synthetischem Serum in die pulmonalen und kardiovaskulären Systeme.",
    "can i disable the augmentation at any time?": "Kann ich die Erweiterung jederzeit abschalten?",
    "client portal": "Kundenportal",
    "enter the atelier": "Zum Atelier",
    "every augmentation is 100% recyclable within the human biological loop, ensuring zero systemic residue.": "Jede Augmentation ist zu 100 % im menschlichen biologischen Kreislauf recycelbar, was null systemische Rückstände gewährleistet.",
    "every neuralis bridge is certified by the global augmentation council (gac) for safety class-s integration.": "Jede Neuralis-Brücke ist vom Global Augmentation Council (GAC) für die Sicherheitsklasse-S-Integration zertifiziert.",
    "how do you handle firmware updates?": "Wie handhaben Sie Aktualisierungen?",
    "is the installation process invasive?": "Ist der Einbau invasiv?",
    "long-term study on synaptic bridge stability across 10,000 subjects over a 24-month period.": "Langzeitstudie zur Stabilität synaptischer Brücken bei 10.000 Probanden über einen Zeitraum von 24 Monaten.",
    "new york": "New York",
    "no external overrides. our firmware is open-source and audited by third-party ethics councils.": "Keine externen Überschreibungen. Unsere Firmware ist Open Source und wird von Dritten Ethikräten geprüft.",
    "our lab utilizes 4d molecular printing to create biocompatible materials that evolve with your cellular structure.": "Unser Labor nutzt 4D-Molekulardruck, um biokompatible Materialien zu schaffen, die sich mit Ihren Zellen entwickeln.",
    "our liquid-graphene bridges are designed to last a lifetime. they evolve with your cellular structure and are powered by your body's own kinetic energy.": "Unsere flüssigen Graphenbrücken sind so konzipiert, dass sie ein Leben lang halten. Sie entwickeln sich mit Ihrer Zellstruktur und werden von der kinetischen Energie Ihres Körpers betrieben.",
    "oxy-flow is the first augmentation that feels truly native. the focus is sustained, clinical, and entirely without the jitters of chemical stimulants.": "Oxy-Flow ist die erste Augmentation, die sich wirklich einheimisch anfühlt. Der Fokus ist nachhaltig, klinisch und völlig ohne die Nervosität chemischer Stimulanzien.",
    "real time": "Echtzeit",
    "real-world testing of prism ar data visualization during high-stress operational environments.": "Echtzeit-Tests der Prism AR-Datenvisualisierung in hochstressigen Betriebsumgebungen.",
    "request diagnostic scan": "Diagnosescanner anfordern",
    "retinal projection system with 32k resolution and integrated neural eye-tracking.": "Retinalprojektionssystem mit 32k Auflösung und integriertem neuronalen Eye-Tracking.",
    "synthetic blood enhancement that increases oxygen transport to the prefrontal cortex by 40%.": "Synthetische Blutverbesserung, die den Sauerstofftransport zum präfrontalen Kortex um 40 % erhöht.",
    "the absolute mastery of bio-synthetic integration. engineered for the evolutionary elite in our tokyo sanctuary.": "Die absolute Beherrschung biosynthetischer Integration. Entwickelt in unserer Werkstatt in Tokio.",
    "the apex of neuro-synthetic integration. engineered for the evolutionary elite.": "Der Höhepunkt der neuro-synthetischen Integration. Entwickelt für die evolutionäre Elite.",
    "the maison": "Die Maison",
    "the moral compass": "Der moralische Kompass",
    "the neural link didn't just improve my workflow; it changed my perception of mathematical structures. i'm no longer visualizing data—i'm inhabiting it.": "Der Neural Link hat nicht nur meinen Arbeitsablauf verbessert; er hat meine Wahrnehmung mathematischer Strukturen verändert. Ich visualisiere Daten nicht mehr, ich bewohne sie.",
    "updates are pushed via encrypted neural-burst protocols. you will be notified in your hud, and updates are only applied with explicit neural authorization.": "Updates werden über verschlüsselte neuronale Burst-Protokolle bereitgestellt. Sie werden in Ihrem HUD benachrichtigt, und Updates werden nur mit ausdrücklicher neuronaler Genehmigung angewendet.",
    "view all research logs": "Alle Forschungsprotokolle ansehen",
    "what is the lifespan of the hardware?": "Wie lange hält die Hardware?",
    "yes. every neuralis device includes a physical 'kill-switch' and a software-based 'dormant mode' which can be toggled via your encrypted client portal.": "Ja. Jedes Neuralis-Gerät enthält einen physischen 'Kill-Switch' und einen softwarebasierten 'Schlafmodus', der über Ihr verschlüsseltes Kundenportal umgeschaltet werden kann.",
    "your neural patterns never leave your local bridge. we provide the hardware, you own the thoughts.": "Ihre neuronalen Muster verlassen nie Ihre lokale Brücke. Wir liefern die Hardware, die Gedanken gehören Ihnen.",
    "zero-residue materials that can be fully integrated or removed without cellular trauma.": "Null-Rückstands-Materialien, die vollständig integriert oder entfernt werden können, ohne zelluläres Trauma zu verursachen.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "pure": "A pura",
    "ethics": "Ética",
    "biology.": "biologia.",
    "research data": "Dados de investigação",
    "latency threshold": "Limiar de latência",
    "sync latency": "Latência de sincronização",
    "biocompatibility": "Biocompatibilidade",
    "active users": "Portadores ativos",
    "r&d patents": "Patentes registadas",
    "hardware": "Equipamento",
    "optics": "Ótica",
    "molecular sovereignty": "Soberania molecular",
    "synthesis.": "síntese.",
    "molecular synthesis": "Síntese molecular",
    "sourcing integrity": "Integridade dos materiais",
    "neural bridging": "Ponte neuronal",
    "eco-biological cycle": "Ciclo ecobiológico",
    "architecture.": "arquitetura.",
    "sync.": "sincronização.",
    "1:1 synapse match": "Correspondência sináptica 1:1",
    "zero systemic residue": "Sem resíduo sistémico",
    "sub-ms bridging": "Ponte abaixo do milissegundo",
    "augmented": "Aumentado",
    "empirical evidence": "Provas clínicas",
    "validation.": "validação.",
    "neural plasticity": "Plasticidade neuronal",
    "94.2% success": "94,2 % de sucesso",
    "long-term study on synaptic bridge stability across 10 000 subjects over a 24-month period.": "Estudo de longa duração sobre a estabilidade da ponte sináptica, realizado em 10 000 sujeitos durante vinte e quatro meses.",
    "0.02% rejection": "0,02 % de rejeição",
    "cognitive load": "Carga cognitiva",
    "3.2x bandwidth": "3,2× de largura de banda",
    "fortress protocol": "Protocolo fortaleza",
    "trust.": "confiança.",
    "encryption": "Cifragem",
    "fail-safe": "Segurança passiva",
    "hardware kill": "Corte por hardware",
    "audits": "Auditorias",
    "operational grid": "Rede operacional",
    "nodes.": "nós.",
    "latency": "Latência",
    "peak load": "Carga máxima",
    "optimizing": "Otimização",
    "rights.": "direitos.",
    "data sovereignty": "Soberania dos dados",
    "biological integrity": "Integridade biológica",
    "cognitive liberty": "Liberdade cognitiva",
    "compliance.": "conformidade.",
    "audit status": "Estado da auditoria",
    "hardware schematics": "Esquemas técnicos",
    "manifesto.": "manifesto.",
    "parameter": "Parâmetro",
    "processing power": "Potência de cálculo",
    "n/a (chemical)": "Não aplicável (químico)",
    "bio-latency": "Biolatência",
    "instant": "Instantâneo",
    "battery life": "Autonomia",
    "indefinite (kinetic)": "Ilimitada (cinética)",
    "material": "Material",
    "liquid graphene": "Grafeno líquido",
    "synthetic serum": "Soro sintético",
    "refractive glass": "Vidro refrativo",
    "clearance": "Habilitação",
    "user experiences": "Testemunhos",
    "quantum architect": "Arquiteto quântico",
    "synthetic biologist": "Bióloga sintética",
    "common": "Perguntas",
    "queries.": "frequentes.",
    "provenance": "Proveniência",
    "tame your": "Dome o seu",
    "your brain is the final frontier of privacy. our neural security layer implements hardware-level encryption that physically disconnects the bridge if any external intrusion is detected. no cloud, no backdoors, no exceptions.": "O seu cérebro é a última fronteira da privacidade. A nossa camada de segurança neural cifra ao nível do hardware e corta fisicamente a ponte assim que deteta uma intrusão. Sem nuvem, sem portas traseiras, sem exceções.",
    "at neuralis, we believe augmentation is a fundamental right. our governance board ensures every neural bridge is encrypted locally, giving you absolute sovereignty over your own biological data.": "Para nós, a aumentação é um direito fundamental. O nosso comité de governação garante que cada ponte neural é cifrada localmente: continua soberano dos seus próprios dados biológicos.",
    "a sub-dermal haptic relay providing 1:1 sensory mapping between physical and digital environments.": "Um relé háptico subdérmico que fornece mapeamento sensorial 1:1 entre ambientes físicos e digitais.",
    "achieve sub-millisecond latency in thought-to-command execution with our proprietary bridge protocols.": "Alcance uma latência inferior a um milissegundo na execução de pensamento para comando com nossos protocolos de ponte proprietários.",
    "are there any side effects?": "Há efeitos secundários?",
    "beyond the interface. we design biological extensions that merge the raw power of synthetic processing with the elegant complexity of human neurology.": "Além da interface. Projetamos extensões biológicas que fundem o poder bruto do processamento sintético com a complexidade elegante da neurologia humana.",
    "biocompatibility testing for synthetic serum integration within pulmonary and cardiovascular systems.": "Testes de biocompatibilidade para a integração de soro sintético nos sistemas pulmonar e cardiovascular.",
    "can i disable the augmentation at any time?": "Posso desativar a melhoria a qualquer momento?",
    "client portal": "Portal do Cliente",
    "enter the atelier": "Entrar no atelier",
    "every augmentation is 100% recyclable within the human biological loop, ensuring zero systemic residue.": "Cada augmentação é 100% reciclável dentro do ciclo biológico humano, garantindo zero resíduos sistêmicos.",
    "every neuralis bridge is certified by the global augmentation council (gac) for safety class-s integration.": "Cada ponte Neuralis é certificado pelo Global Augmentation Council (GAC) para integração de Classe de Segurança S.",
    "how do you handle firmware updates?": "Como gerem as atualizações?",
    "is the installation process invasive?": "A colocação é invasiva?",
    "long-term study on synaptic bridge stability across 10,000 subjects over a 24-month period.": "Estudo a longo prazo sobre a estabilidade da ponte sináptica em 10.000 sujeitos ao longo de um período de 24 meses.",
    "new york": "Nova Iorque",
    "no external overrides. our firmware is open-source and audited by third-party ethics councils.": "Sem sobreposições externas. O nosso firmware é de código aberto e auditado por conselhos de ética de terceiros.",
    "our lab utilizes 4d molecular printing to create biocompatible materials that evolve with your cellular structure.": "O nosso laboratório emprega a impressão molecular em quatro dimensões para criar matérias biocompatíveis que evoluem com as suas células.",
    "our liquid-graphene bridges are designed to last a lifetime. they evolve with your cellular structure and are powered by your body's own kinetic energy.": "As nossas pontes de grafeno líquido são projetadas para durar uma vida inteira. Elas evoluem com a sua estrutura celular e são alimentadas pela energia cinética do seu corpo.",
    "oxy-flow is the first augmentation that feels truly native. the focus is sustained, clinical, and entirely without the jitters of chemical stimulants.": "O Oxy-Flow é a primeira augmentação que se sente verdadeiramente nativa. O foco é sustentado, clínico e totalmente livre dos nervos dos estimulantes químicos.",
    "real time": "Tempo Real",
    "real-world testing of prism ar data visualization during high-stress operational environments.": "Testes no mundo real da visualização de dados Prism AR durante ambientes operacionais de alta pressão.",
    "request diagnostic scan": "Solicitar varredura de diagnóstico",
    "retinal projection system with 32k resolution and integrated neural eye-tracking.": "Sistema de projeção retinal com resolução de 32k e rastreamento ocular neural integrado.",
    "synthetic blood enhancement that increases oxygen transport to the prefrontal cortex by 40%.": "A melhoria do sangue sintético que aumenta o transporte de oxigênio para o córtex pré-frontal em 40%.",
    "the absolute mastery of bio-synthetic integration. engineered for the evolutionary elite in our tokyo sanctuary.": "O domínio absoluto da integração biossintética. Concebido no nosso atelier de Tóquio.",
    "the apex of neuro-synthetic integration. engineered for the evolutionary elite.": "O ápice da integração neuro-sintética. Projetado para a elite evolutiva.",
    "the maison": "A Maison",
    "the moral compass": "A bússola moral",
    "the neural link didn't just improve my workflow; it changed my perception of mathematical structures. i'm no longer visualizing data—i'm inhabiting it.": "O Neural Link não apenas melhorou meu fluxo de trabalho; mudou minha percepção das estruturas matemáticas. Não estou mais visualizando dados, estou habitando-os.",
    "updates are pushed via encrypted neural-burst protocols. you will be notified in your hud, and updates are only applied with explicit neural authorization.": "As atualizações são enviadas através de protocolos de explosão neural criptografados. Você será notificado em seu HUD, e as atualizações só são aplicadas com autorização neural explícita.",
    "view all research logs": "Ver todos os cadernos de investigação",
    "what is the lifespan of the hardware?": "Qual é a vida útil do equipamento?",
    "yes. every neuralis device includes a physical 'kill-switch' and a software-based 'dormant mode' which can be toggled via your encrypted client portal.": "Sim. Cada dispositivo Neuralis inclui um 'Kill-Switch' físico e um 'Modo Dormant' baseado em software que pode ser alternado através do seu portal de cliente criptografado.",
    "your neural patterns never leave your local bridge. we provide the hardware, you own the thoughts.": "Os seus padrões neuronais nunca saem da sua ponte local. Nós fornecemos o equipamento, os pensamentos são seus.",
    "zero-residue materials that can be fully integrated or removed without cellular trauma.": "Materiais sem resíduos que podem ser totalmente integrados ou removidos sem trauma celular.",
  },
};
