/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "manifesto": "Manifeste",
    "commission": "Nous confier un projet",
    "markets": "Marchés",
    "strategies": "Stratégies",
    "traders": "Opérateurs",
    "archive": "Archives",
    "e-commerce": "Commerce en ligne",
    "origins": "Origines",
    "source": "Origine",
    "roast": "Torréfaction",
    "cup": "Tasse",
    "programs": "Programmes",
    "members": "Membres",
    "destinations": "Destinations",
    "years experience": "Ans d'expérience",
    "releases": "Sorties",
    "tour": "Tournée",
    "store": "Boutique",
    "waste diverted": "Déchets détournés",
    "residential": "Résidentiel",
    "penthouse": "Attique",
    "concierge": "Conciergerie",
    "locations": "Nos adresses",
    "seller portal": "Espace vendeurs",
    "legacy": "Héritage",
    "select seat": "Choisir sa place",
    "offense": "Attaque",
    "intelligence": "Renseignement",
    "global nodes": "Nœuds mondiaux",
    "enlist": "Nous rejoindre",
    "market": "Marché",
    "curators": "Curateurs",
    "stats": "Chiffres",
    "connect wallet": "Connecter le portefeuille",
    "sanctuary": "Le sanctuaire",
    "retreats": "Retraites",
    "essence": "Essence",
    "landmark cases": "Affaires marquantes",
    "authority": "Autorité",
    "vegan & cruelty-free": "Végane et sans cruauté",
    "design": "DESIGN",
    "content": "CONTENU",
    "we design digital experiences that": "Nous concevons des expériences numériques qui",
    "\"presence is the ultimate luxury. we provide the architecture to achieve it.\"": "« La présence est le luxe absolu. Nous en bâtissons l'architecture. »",
    "14 days · from €11,200": "14 jours · à partir de 11 200 €",
    "2-month follow-up": "suivi de 2 mois",
    "3 days · from €2,400": "3 jours · à partir de 2 400 €",
    "7 days · from €5,800": "7 jours · à partir de 5 800 €",
    "choose your": "Choisissez votre",
    "designed by award-winning architects, our sanctuary uses local stone and recycled timber to create a seamless transition between the self and nature.": "Conçu par des architectes primés, notre sanctuaire utilise de la pierre locale et du bois recyclé pour créer une transition harmonieuse entre soi et la nature.",
    "enquire": "Renseignez-vous",
    "full sensory withdrawal programme for executives and high-performance athletes.": "Programme de retrait sensoriel complet pour les cadres et les athlètes de haut niveau.",
    "hold the": "Tenez le",
    "i arrived carrying three years of accumulated burnout. after seven days at aether, i remembered what it felt like to be in my body.": "Je suis arrivé en portant trois ans de burnout accumulé. Après sept jours à Aether, je me suis souvenu de ce que c'était que d'être dans mon corps.",
    "journey.": "Voyage.",
    "limited memberships available for our 2026 season. begin your journey into the aether today.": "Adhésions en nombre limité pour la saison 2026. Commencez votre parcours dès aujourd'hui.",
    "nothing digital, nothing performative. just the sound of water and the smell of cedar. it changed my entire relationship with stillness.": "Rien de numérique, rien de performatif. Juste le son de l'eau et l'odeur du cèdre. Cela a changé toute ma relation avec le silence.",
    "our ethos": "Notre éthique",
    "request membership audit": "Demander un audit de membre",
    "the complete aether experience. curated for transformational depth.": "L'expérience Aether complète. Curatée pour une profondeur transformationnelle.",
    "the deep stillness retreat recalibrated my nervous system in ways i didn't know were possible. i sleep differently now.": "Le retrait Deep Stillness a recalibré mon système nerveux de manières que je ne savais pas possibles. Je dors différemment maintenant.",
    "the sanctuary": "Le sanctuaire",
    "view retreat schedule": "Voir le calendrier des retraites",
    "view retreats": "Voir les retraites",
    "voices of": "Voix de",
  },
  es: {
    "manifesto": "Manifiesto",
    "commission": "Encargar un proyecto",
    "markets": "Mercados",
    "strategies": "Estrategias",
    "traders": "Operadores",
    "archive": "Archivo",
    "e-commerce": "Comercio electrónico",
    "origins": "Orígenes",
    "source": "Origen",
    "roast": "Tueste",
    "cup": "Taza",
    "programs": "Programas",
    "members": "Miembros",
    "destinations": "Destinos",
    "years experience": "Años de experiencia",
    "releases": "Lanzamientos",
    "tour": "Gira",
    "store": "Tienda",
    "waste diverted": "Residuos desviados",
    "residential": "Residencial",
    "penthouse": "Ático",
    "concierge": "Conserjería",
    "locations": "Nuestras direcciones",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Elegir asiento",
    "offense": "Ataque",
    "intelligence": "Inteligencia",
    "global nodes": "Nodos mundiales",
    "enlist": "Únase a nosotros",
    "market": "Mercado",
    "curators": "Comisarios",
    "stats": "Cifras",
    "connect wallet": "Conectar la cartera",
    "sanctuary": "El santuario",
    "retreats": "Retiros",
    "essence": "Esencia",
    "landmark cases": "Casos emblemáticos",
    "authority": "Autoridad",
    "vegan & cruelty-free": "Vegano y sin crueldad",
    "design": "DISEÑO",
    "content": "CONTENIDO",
    "we design digital experiences that": "Diseñamos experiencias digitales que",
    "\"presence is the ultimate luxury. we provide the architecture to achieve it.\"": "«La presencia es el lujo absoluto. Nosotros construimos su arquitectura.»",
    "14 days · from €11,200": "14 días · desde 11.200 €",
    "2-month follow-up": "seguimiento de 2 meses",
    "3 days · from €2,400": "3 días · desde 2.400 €",
    "7 days · from €5,800": "7 días · desde 5.800 €",
    "choose your": "Elija su",
    "designed by award-winning architects, our sanctuary uses local stone and recycled timber to create a seamless transition between the self and nature.": "Diseñado por arquitectos galardonados, nuestro santuario utiliza piedra local y madera reciclada para crear una transición fluida entre el yo y la naturaleza.",
    "enquire": "Consulta",
    "full sensory withdrawal programme for executives and high-performance athletes.": "Programa de retiro sensorial completo para ejecutivos y atletas de alto rendimiento.",
    "hold the": "Mantenga el",
    "i arrived carrying three years of accumulated burnout. after seven days at aether, i remembered what it felt like to be in my body.": "Llegué cargando tres años de agotamiento acumulado. Después de siete días en Aether, recordé lo que se sentía estar en mi cuerpo.",
    "journey.": "Viaje.",
    "limited memberships available for our 2026 season. begin your journey into the aether today.": "Membresías limitadas para la temporada 2026. Empiece hoy mismo su recorrido.",
    "nothing digital, nothing performative. just the sound of water and the smell of cedar. it changed my entire relationship with stillness.": "Nada digital, nada performativo. Solo el sonido del agua y el olor de la madera de cedro. Cambió toda mi relación con la quietud.",
    "our ethos": "Nuestra ética",
    "request membership audit": "Solicitar auditoría de membresía",
    "the complete aether experience. curated for transformational depth.": "La experiencia completa de Aether. Curada para una profundidad transformacional.",
    "the deep stillness retreat recalibrated my nervous system in ways i didn't know were possible. i sleep differently now.": "El retiro Deep Stillness recalibró mi sistema nervioso de maneras que no sabía que eran posibles. Ahora duermo de manera diferente.",
    "the sanctuary": "El santuario",
    "view retreat schedule": "Ver horario de retiros",
    "view retreats": "Ver retiros",
    "voices of": "Voces de",
  },
  de: {
    "manifesto": "Manifest",
    "commission": "Projekt anfragen",
    "markets": "Märkte",
    "strategies": "Strategien",
    "traders": "Händler",
    "archive": "Archiv",
    "e-commerce": "E-Commerce",
    "origins": "Herkünfte",
    "source": "Ursprung",
    "roast": "Röstung",
    "cup": "Tasse",
    "programs": "Programme",
    "members": "Mitglieder",
    "destinations": "Reiseziele",
    "years experience": "Jahre Erfahrung",
    "releases": "Veröffentlichungen",
    "tour": "Tour",
    "store": "Shop",
    "waste diverted": "Umgeleitete Abfälle",
    "residential": "Wohnbau",
    "penthouse": "Penthouse",
    "concierge": "Concierge-Service",
    "locations": "Unsere Standorte",
    "seller portal": "Verkäuferbereich",
    "legacy": "Erbe",
    "select seat": "Platz wählen",
    "offense": "Angriff",
    "intelligence": "Aufklärung",
    "global nodes": "Weltweite Knoten",
    "enlist": "Mitmachen",
    "market": "Markt",
    "curators": "Kuratoren",
    "stats": "Zahlen",
    "connect wallet": "Wallet verbinden",
    "sanctuary": "Das Refugium",
    "retreats": "Retreats",
    "essence": "Essenz",
    "landmark cases": "Wegweisende Fälle",
    "authority": "Autorität",
    "vegan & cruelty-free": "Vegan und tierversuchsfrei",
    "design": "DESIGN",
    "content": "INHALT",
    "we design digital experiences that": "Wir gestalten digitale Erlebnisse, die",
    "\"presence is the ultimate luxury. we provide the architecture to achieve it.\"": "„Präsenz ist der höchste Luxus. Wir bauen die Architektur dafür.“",
    "14 days · from €11,200": "14 Tage · ab 11.200 €",
    "2-month follow-up": "2-monatige Nachverfolgung",
    "3 days · from €2,400": "3 Tage · ab 2.400 €",
    "7 days · from €5,800": "7 Tage · ab 5.800 €",
    "choose your": "Wählen Sie Ihren",
    "designed by award-winning architects, our sanctuary uses local stone and recycled timber to create a seamless transition between the self and nature.": "Entworfen von preisgekrönten Architekten, nutzt unser Heiligtum lokalen Stein und recyceltes Holz, um einen nahtlosen Übergang zwischen dem Selbst und der Natur zu schaffen.",
    "enquire": "Anfragen",
    "full sensory withdrawal programme for executives and high-performance athletes.": "Vollständiges sensorisches Rückzugsprogramm für Führungskräfte und Hochleistungssportler.",
    "hold the": "Halten Sie den",
    "i arrived carrying three years of accumulated burnout. after seven days at aether, i remembered what it felt like to be in my body.": "Ich kam mit drei Jahren angesammeltem Burnout an. Nach sieben Tagen bei Aether erinnerte ich mich, wie es sich anfühlte, in meinem Körper zu sein.",
    "journey.": "Reise.",
    "limited memberships available for our 2026 season. begin your journey into the aether today.": "Begrenzte Mitgliedschaften für die Saison 2026. Beginnen Sie Ihren Weg noch heute.",
    "nothing digital, nothing performative. just the sound of water and the smell of cedar. it changed my entire relationship with stillness.": "Nichts Digitales, nichts Performatives. Nur das Geräusch von Wasser und der Geruch von Zeder. Es hat meine gesamte Beziehung zur Stille verändert.",
    "our ethos": "Unser Ethos",
    "request membership audit": "Mitgliedschaftsprüfung anfordern",
    "the complete aether experience. curated for transformational depth.": "Das vollständige Aether-Erlebnis. Kuratiert für transformative Tiefe.",
    "the deep stillness retreat recalibrated my nervous system in ways i didn't know were possible. i sleep differently now.": "Der Deep Stillness-Retreat hat mein Nervensystem auf Weisen neu kalibriert, von denen ich nicht wusste, dass sie möglich sind. Ich schlafe jetzt anders.",
    "the sanctuary": "Das Refugium",
    "view retreat schedule": "Rückzugszeitplan anzeigen",
    "view retreats": "Rückzüge anzeigen",
    "voices of": "Stimmen von",
  },
  pt: {
    "manifesto": "Manifesto",
    "commission": "Confiar-nos um projeto",
    "markets": "Mercados",
    "strategies": "Estratégias",
    "traders": "Operadores",
    "archive": "Arquivo",
    "e-commerce": "Comércio eletrónico",
    "origins": "Origens",
    "source": "Origem",
    "roast": "Torra",
    "cup": "Chávena",
    "programs": "Programas",
    "members": "Membros",
    "destinations": "Destinos",
    "years experience": "Anos de experiência",
    "releases": "Lançamentos",
    "tour": "Digressão",
    "store": "Loja",
    "waste diverted": "Resíduos desviados",
    "residential": "Residencial",
    "penthouse": "Cobertura",
    "concierge": "Concierge",
    "locations": "As nossas moradas",
    "seller portal": "Área de vendedores",
    "legacy": "Legado",
    "select seat": "Escolher lugar",
    "offense": "Ataque",
    "intelligence": "Informações",
    "global nodes": "Nós mundiais",
    "enlist": "Junte-se a nós",
    "market": "Mercado",
    "curators": "Curadores",
    "stats": "Números",
    "connect wallet": "Ligar a carteira",
    "sanctuary": "O santuário",
    "retreats": "Retiros",
    "essence": "Essência",
    "landmark cases": "Casos marcantes",
    "authority": "Autoridade",
    "vegan & cruelty-free": "Vegano e sem crueldade",
    "design": "DESIGN",
    "content": "CONTEÚDO",
    "we design digital experiences that": "Concebemos experiências digitais que",
    "\"presence is the ultimate luxury. we provide the architecture to achieve it.\"": "«A presença é o luxo absoluto. Nós construímos a sua arquitetura.»",
    "14 days · from €11,200": "14 dias · a partir de 11.200 €",
    "2-month follow-up": "seguimento de 2 meses",
    "3 days · from €2,400": "3 dias · a partir de 2.400 €",
    "7 days · from €5,800": "7 dias · a partir de 5.800 €",
    "choose your": "Escolha o seu",
    "designed by award-winning architects, our sanctuary uses local stone and recycled timber to create a seamless transition between the self and nature.": "Projetado por arquitetos premiados, o nosso santuário utiliza pedra local e madeira reciclada para criar uma transição perfeita entre o eu e a natureza.",
    "enquire": "Perguntar",
    "full sensory withdrawal programme for executives and high-performance athletes.": "Programa de retirada sensorial completo para executivos e atletas de alto desempenho.",
    "hold the": "Segure o",
    "i arrived carrying three years of accumulated burnout. after seven days at aether, i remembered what it felt like to be in my body.": "Cheguei carregando três anos de burnout acumulado. Depois de sete dias na Aether, lembrei-me de como era estar no meu corpo.",
    "journey.": "Jornada.",
    "limited memberships available for our 2026 season. begin your journey into the aether today.": "Adesões limitadas para a temporada 2026. Comece hoje o seu percurso.",
    "nothing digital, nothing performative. just the sound of water and the smell of cedar. it changed my entire relationship with stillness.": "Nada digital, nada performativo. Apenas o som da água e o cheiro de cedro. Mudou toda a minha relação com a quietude.",
    "our ethos": "A nossa ética",
    "request membership audit": "Solicitar auditoria de adesão",
    "the complete aether experience. curated for transformational depth.": "A experiência completa de Aether. Curada para profundidade transformacional.",
    "the deep stillness retreat recalibrated my nervous system in ways i didn't know were possible. i sleep differently now.": "O retiro Deep Stillness recalibró o meu sistema nervoso de maneiras que não sabia serem possíveis. Agora durmo de forma diferente.",
    "the sanctuary": "O santuário",
    "view retreat schedule": "Ver calendário de retiros",
    "view retreats": "Ver retiros",
    "voices of": "Vozes de",
  },
};
