/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "equipment": "Équipement",
    "enquiry": "Nous écrire",
    "highest": "Les plus hauts",
    "summits": "sommets",
    "elite art conservation & private registry": "Conservation d'œuvres et registre privé",
    "collector vault": "Coffre du collectionneur",
    "materials": "Matériaux",
    "specs": "Caractéristiques",
    "applications": "Applications",
    "research": "Recherche",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Soie au graphène. Maille bioluminescente CRISPR. Laine à mémoire de forme en nitinol. Nous concevons des textiles au croisement de la science des matériaux, de la biotechnologie et de la haute couture.",
    "core directive": "Directive fondamentale",
    "uptime protocol": "Protocole de disponibilité",
    "expandable storage": "Stockage extensible",
    "provision node": "Provisionner un nœud",
    "product": "Produit",
    "marketing": "Marketing",
    "properties": "Nos biens",
    "market": "Le marché",
    "neighborhoods": "Les quartiers",
    "establishment": "Fondation",
    "gold": "Or",
    "time": "Le temps",
    "newsletter": "Lettre d'information",
    "planning": "Le planning",
    "heritage": "Héritage",
    "by submitting you accept our material nda terms. samples shipped from": "En envoyant, vous acceptez notre accord de confidentialité. Échantillons expédiés depuis",
    "each material undergoes 24 months of laboratory validation before entering our production registry. click any color swatch to shift the accent tone.": "Chaque matière passe vingt-quatre mois de validation en laboratoire avant d'entrer au registre de production. Cliquez sur un échantillon pour changer la teinte d'accent.",
    "engineered for": "Conçu pour",
    "engineering the textile future through graphene, biotech, and shape-memory materials science.": "Concevoir l'avenir du textile par le graphène, les biotechnologies et les matériaux à mémoire de forme.",
    "explore materials": "Explorer les Matériaux",
    "of tomorrow.": "de Demain.",
    "physical sample kits are available to qualified research institutions, luxury brands, and defense contractors. nda required for r&d materials.": "Des kits d'échantillons physiques sont disponibles pour les institutions de recherche qualifiées, les marques de luxe et les entrepreneurs de défense. NDA requis pour les matériaux de R&D.",
    "request logged. our lab team will reach out within 48h.": "Demande enregistrée. Notre équipe de laboratoire vous contactera dans les 48h.",
    "request sample": "Demander un échantillon",
    "request your": "Demandez votre",
    "terminal read.": "Lecture terminale.",
    "the fabric": "Le Tissu",
  },
  es: {
    "equipment": "Equipamiento",
    "enquiry": "Escríbanos",
    "highest": "Las más altas",
    "summits": "cumbres",
    "elite art conservation & private registry": "Conservación de obras y registro privado",
    "collector vault": "Cámara del coleccionista",
    "materials": "Materiales",
    "specs": "Características",
    "applications": "Aplicaciones",
    "research": "Investigación",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda con grafeno. Malla bioluminiscente CRISPR. Lana con memoria de forma de nitinol. Diseñamos textiles en el cruce de la ciencia de materiales, la biotecnología y la alta costura.",
    "core directive": "Directiva fundamental",
    "uptime protocol": "Protocolo de disponibilidad",
    "expandable storage": "Almacenamiento ampliable",
    "provision node": "Aprovisionar un nodo",
    "product": "Producto",
    "marketing": "Marketing",
    "properties": "Nuestros inmuebles",
    "market": "El mercado",
    "neighborhoods": "Los barrios",
    "establishment": "Fundación",
    "gold": "Oro",
    "time": "El tiempo",
    "newsletter": "Boletín",
    "planning": "El horario",
    "heritage": "Herencia",
    "by submitting you accept our material nda terms. samples shipped from": "Al enviar, acepta nuestro acuerdo de confidencialidad. Muestras enviadas desde",
    "each material undergoes 24 months of laboratory validation before entering our production registry. click any color swatch to shift the accent tone.": "Cada material pasa veinticuatro meses de validación en laboratorio antes de entrar en el registro de producción. Pulse una muestra para cambiar el tono de acento.",
    "engineered for": "Concebido para",
    "engineering the textile future through graphene, biotech, and shape-memory materials science.": "Concebir el futuro del textil mediante el grafeno, las biotecnologías y los materiales con memoria de forma.",
    "explore materials": "Explorar Materiales",
    "of tomorrow.": "del Mañana.",
    "physical sample kits are available to qualified research institutions, luxury brands, and defense contractors. nda required for r&d materials.": "Los kits de muestras físicas están disponibles para instituciones de investigación calificadas, marcas de lujo y contratistas de defensa. Se requiere NDA para materiales de I+D.",
    "request logged. our lab team will reach out within 48h.": "Solicitud registrada. Nuestro equipo de laboratorio se pondrá en contacto en un plazo de 48 horas.",
    "request sample": "Solicitar muestra",
    "request your": "Solicite su",
    "terminal read.": "Lectura terminal.",
    "the fabric": "La Tela",
  },
  de: {
    "equipment": "Ausrüstung",
    "enquiry": "Anfrage",
    "highest": "Die höchsten",
    "summits": "Gipfel",
    "elite art conservation & private registry": "Kunstkonservierung und privates Register",
    "collector vault": "Sammlertresor",
    "materials": "Werkstoffe",
    "specs": "Kenndaten",
    "applications": "Anwendungen",
    "research": "Forschung",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seide mit Graphen. Biolumineszentes CRISPR-Gewebe. Formgedächtniswolle aus Nitinol. Wir entwickeln Textilien an der Schnittstelle von Materialwissenschaft, Biotechnologie und Haute Couture.",
    "core directive": "Grundsatzdirektive",
    "uptime protocol": "Verfügbarkeitsprotokoll",
    "expandable storage": "Erweiterbarer Speicher",
    "provision node": "Knoten bereitstellen",
    "product": "Produkt",
    "marketing": "Marketing",
    "properties": "Unsere Objekte",
    "market": "Der Markt",
    "neighborhoods": "Die Viertel",
    "establishment": "Gründung",
    "gold": "Gold",
    "time": "Die Zeit",
    "newsletter": "Newsletter",
    "planning": "Der Stundenplan",
    "heritage": "Erbe",
    "by submitting you accept our material nda terms. samples shipped from": "Mit dem Absenden akzeptieren Sie unsere Vertraulichkeitsvereinbarung. Muster versandt ab",
    "each material undergoes 24 months of laboratory validation before entering our production registry. click any color swatch to shift the accent tone.": "Jedes Material durchläuft vierundzwanzig Monate Laborprüfung, bevor es ins Produktionsregister aufgenommen wird. Klicken Sie auf ein Farbmuster, um den Akzentton zu wechseln.",
    "engineered for": "Entwickelt für",
    "engineering the textile future through graphene, biotech, and shape-memory materials science.": "Die Zukunft des Textils gestalten — mit Graphen, Biotechnologie und Formgedächtnismaterialien.",
    "explore materials": "Materialien erkunden",
    "of tomorrow.": "von Morgen.",
    "physical sample kits are available to qualified research institutions, luxury brands, and defense contractors. nda required for r&d materials.": "Physische Musterkits sind für qualifizierte Forschungseinrichtungen, Luxusmarken und Verteidigungsauftragnehmer erhältlich. NDA für F&E-Materialien erforderlich.",
    "request logged. our lab team will reach out within 48h.": "Anfrage protokolliert. Unser Laborteam wird sich innerhalb von 48 Stunden bei Ihnen melden.",
    "request sample": "Muster anfordern",
    "request your": "Fordern Sie Ihr",
    "terminal read.": "Terminal-Lesung.",
    "the fabric": "Der Stoff",
  },
  pt: {
    "equipment": "Equipamento",
    "enquiry": "Escreva-nos",
    "highest": "Os mais altos",
    "summits": "cumes",
    "elite art conservation & private registry": "Conservação de obras e registo privado",
    "collector vault": "Cofre do colecionador",
    "materials": "Materiais",
    "specs": "Características",
    "applications": "Aplicações",
    "research": "Investigação",
    "graphene-infused silk. crispr bioluminescent mesh. nitinol shape-memory wool. we engineer textiles at the intersection of materials science, biotechnology, and haute couture.": "Seda com grafeno. Malha bioluminescente CRISPR. Lã com memória de forma em nitinol. Concebemos têxteis no cruzamento da ciência dos materiais, da biotecnologia e da alta-costura.",
    "core directive": "Diretiva fundamental",
    "uptime protocol": "Protocolo de disponibilidade",
    "expandable storage": "Armazenamento expansível",
    "provision node": "Aprovisionar um nó",
    "product": "Produto",
    "marketing": "Marketing",
    "properties": "Os nossos imóveis",
    "market": "O mercado",
    "neighborhoods": "Os bairros",
    "establishment": "Fundação",
    "gold": "Ouro",
    "time": "O tempo",
    "newsletter": "Boletim",
    "planning": "O horário",
    "heritage": "Herança",
    "by submitting you accept our material nda terms. samples shipped from": "Ao enviar, aceita o nosso acordo de confidencialidade. Amostras enviadas de",
    "each material undergoes 24 months of laboratory validation before entering our production registry. click any color swatch to shift the accent tone.": "Cada material passa vinte e quatro meses de validação em laboratório antes de entrar no registo de produção. Clique numa amostra para mudar o tom de destaque.",
    "engineered for": "Concebido para",
    "engineering the textile future through graphene, biotech, and shape-memory materials science.": "Conceber o futuro do têxtil através do grafeno, das biotecnologias e dos materiais com memória de forma.",
    "explore materials": "Explorar Materiais",
    "of tomorrow.": "do Amanhã.",
    "physical sample kits are available to qualified research institutions, luxury brands, and defense contractors. nda required for r&d materials.": "Kits de amostras físicas estão disponíveis para instituições de pesquisa qualificadas, marcas de luxo e contratantes de defesa. NDA necessário para materiais de P&D.",
    "request logged. our lab team will reach out within 48h.": "Pedido registado. Nossa equipe de laboratório entrará em contato dentro de 48 horas.",
    "request sample": "Solicitar amostra",
    "request your": "Solicite o seu",
    "terminal read.": "Leitura terminal.",
    "the fabric": "O Tecido",
  },
};
