/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "technology stack": "Technologies employées",
    "establish connection": "Établir la connexion",
    "projects completed": "Projets livrés",
    "countries": "Pays",
    "carbon-negative projects": "Projets à bilan carbone négatif",
    "motion graphics": "Motion design",
    "brand films": "Films de marque",
    "interactive": "Interactif",
    "brand exploration": "Exploration de marque",
    "fleet": "La flotte",
    "network": "Réseau",
    "company": "L'entreprise",
    "craftsmanship": "Savoir-faire",
    "heritage": "Héritage",
    "innovation": "Innovation",
    "infrastructure": "Infrastructure",
    "deploy": "Déployer",
    "fragrances": "Parfums",
    "digital craft": "Artisanat numérique",
    "e-commerce": "Commerce en ligne",
    "art direction, webgl": "Direction artistique, WebGL",
    "global edition": "Édition internationale",
    "reserve": "Réserver",
    "owner portal": "Espace propriétaires",
    "stack": "Technologies",
    "access": "Accès",
    "initialize": "Démarrer",
    "system architecture": "Architecture du système",
    "command login": "Accès contrôle",
    "missions": "Missions",
    "events": "Événements",
    "artists": "Artistes",
    "venues": "Salles",
    "upcoming": "À venir",
    "properties": "Nos biens",
    "private inquiry": "Demande confidentielle",
    "exceptional": "Exceptionnel",
    "examples": "Exemples",
    "plugins": "Extensions",
    "digital experience": "Expérience numérique",
    "brand identity": "Identité de marque",
    "ai revolution": "Révolution de l'IA",
    "a standard interactive 3d landing page takes 6-8 weeks from concept to deployment. complex data visualizations or configurators may take 12-16 weeks.": "Une page d'atterrissage interactive 3D standard prend 6 à 8 semaines, de la conception au déploiement. Des visualisations de données complexes ou des configurateurs peuvent prendre 12 à 16 semaines.",
    "algorithmic design architectures that react in real-time to user input and audio.": "Architectures de design algorithmique qui réagissent en temps réel aux entrées utilisateur et à l'audio.",
    "all systems nominal": "TOUS SYSTÈMES NORMAUX",
    "dedicated spatial computing team.": "Une équipe dédiée à l'informatique spatiale.",
    "deployment plans": "Plans de déploiement",
    "do you create the 3d assets in-house?": "Créez-vous les actifs 3D en interne ?",
    "global clients": "Clients globaux",
    "how does 3d affect website performance?": "Comment la 3D affecte-t-elle les performances des sites web ?",
    "initiate a secure connection with our lead engineers to discuss your spatial computing requirements.": "Initier une connexion sécurisée avec nos ingénieurs principaux pour discuter de vos besoins en informatique spatiale.",
    "pioneering the spatial web. we combine aesthetic discipline with extreme technical capabilities to build the digital future.": "Défricher le web spatial. Nous joignons une exigence esthétique à des moyens techniques extrêmes pour bâtir l'avenir numérique.",
    "proof of concept and visual direction.": "Preuve de concept et direction visuelle.",
    "ready to": "Prêt à",
    "real-time particle system for tracking server loads.": "Système de particules en temps réel pour suivre les charges serveur.",
    "transforming flat pages into interactive 3d environments using three.js and webgl.": "Transformer des pages plates en environnements 3D interactifs en utilisant Three.js et WebGL.",
    "view demo reel": "Voir la démo",
    "view repository": "Voir le dépôt",
    "we engineer immersive 3d interfaces, webgl experiences, and spatial computing environments for the next era of the web.": "Nous concevons des interfaces 3D immersives, des expériences WebGL et des environnements de calcul spatial pour la prochaine ère du web.",
    "what is your typical project timeline?": "Quel est votre calendrier de projet typique ?",
    "yes, our team includes technical artists who build, rig, and optimize assets specifically for real-time web rendering in blender and maya.": "Oui, notre équipe comprend des artistes techniques qui construisent, équipent et optimisent des actifs spécifiquement pour le rendu web en temps réel dans Blender et Maya.",
  },
  es: {
    "technology stack": "Tecnologías empleadas",
    "establish connection": "Establecer conexión",
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "projects completed": "Proyectos entregados",
    "countries": "Países",
    "carbon-negative projects": "Proyectos de balance de carbono negativo",
    "motion graphics": "Motion graphics",
    "brand films": "Films de marca",
    "interactive": "Interactivo",
    "brand exploration": "Exploración de marca",
    "fleet": "La flota",
    "network": "Red",
    "company": "La empresa",
    "craftsmanship": "Saber hacer",
    "heritage": "Herencia",
    "innovation": "Innovación",
    "infrastructure": "Infraestructura",
    "deploy": "Desplegar",
    "fragrances": "Perfumes",
    "digital craft": "Artesanía digital",
    "e-commerce": "Comercio electrónico",
    "art direction, webgl": "Dirección de arte, WebGL",
    "global edition": "Edición internacional",
    "reserve": "Reservar",
    "owner portal": "Área de propietarios",
    "stack": "Tecnologías",
    "access": "Acceso",
    "initialize": "Iniciar",
    "system architecture": "Arquitectura del sistema",
    "command login": "Acceso de control",
    "missions": "Misiones",
    "events": "Eventos",
    "artists": "Artistas",
    "venues": "Salas",
    "upcoming": "Próximamente",
    "properties": "Nuestros inmuebles",
    "private inquiry": "Solicitud confidencial",
    "exceptional": "Excepcional",
    "examples": "Ejemplos",
    "plugins": "Extensiones",
    "digital experience": "Experiencia digital",
    "brand identity": "Identidad de marca",
    "ai revolution": "Revolución de la IA",
    "a standard interactive 3d landing page takes 6-8 weeks from concept to deployment. complex data visualizations or configurators may take 12-16 weeks.": "Una página de aterrizaje interactiva 3D estándar toma de 6 a 8 semanas desde el concepto hasta el despliegue. Las visualizaciones de datos complejas o los configuradores pueden tardar de 12 a 16 semanas.",
    "algorithmic design architectures that react in real-time to user input and audio.": "Arquitecturas de diseño algorítmico que reaccionan en tiempo real a la entrada del usuario y al audio.",
    "all systems nominal": "TODOS LOS SISTEMAS NORMALES",
    "dedicated spatial computing team.": "Un equipo dedicado a la computación espacial.",
    "deployment plans": "Planes de despliegue",
    "do you create the 3d assets in-house?": "¿Crean los activos 3D internamente?",
    "global clients": "Clientes globales",
    "how does 3d affect website performance?": "¿Cómo afecta la 3D al rendimiento del sitio web?",
    "initiate a secure connection with our lead engineers to discuss your spatial computing requirements.": "Iniciar una conexión segura con nuestros ingenieros principales para discutir sus requisitos de computación espacial.",
    "pioneering the spatial web. we combine aesthetic discipline with extreme technical capabilities to build the digital future.": "Abrir camino en la web espacial. Unimos una exigencia estética a medios técnicos extremos para construir el futuro digital.",
    "proof of concept and visual direction.": "Prueba de concepto y dirección visual.",
    "ready to": "Listo para",
    "real-time particle system for tracking server loads.": "Sistema de partículas en tiempo real para rastrear las cargas del servidor.",
    "transforming flat pages into interactive 3d environments using three.js and webgl.": "Transformando páginas planas en entornos 3D interactivos utilizando Three.js y WebGL.",
    "view demo reel": "Ver demostración",
    "view repository": "Ver repositorio",
    "we engineer immersive 3d interfaces, webgl experiences, and spatial computing environments for the next era of the web.": "Ingeniamos interfaces 3D inmersivas, experiencias WebGL y entornos de computación espacial para la próxima era de la web.",
    "what is your typical project timeline?": "¿Cuál es su cronograma típico de proyecto?",
    "yes, our team includes technical artists who build, rig, and optimize assets specifically for real-time web rendering in blender and maya.": "Sí, nuestro equipo incluye artistas técnicos que construyen, configuran y optimizan activos específicamente para el renderizado web en tiempo real en Blender y Maya.",
  },
  de: {
    "technology stack": "Technologie-Stack",
    "establish connection": "Verbindung herstellen",
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "projects completed": "Fertiggestellte Projekte",
    "countries": "Länder",
    "carbon-negative projects": "Projekte mit negativer CO₂-Bilanz",
    "motion graphics": "Motion Graphics",
    "brand films": "Markenfilme",
    "interactive": "Interaktiv",
    "brand exploration": "Markenerkundung",
    "fleet": "Die Flotte",
    "network": "Netz",
    "company": "Unternehmen",
    "craftsmanship": "Handwerkskunst",
    "heritage": "Erbe",
    "innovation": "Innovation",
    "infrastructure": "Infrastruktur",
    "deploy": "Deployen",
    "fragrances": "Düfte",
    "digital craft": "Digitales Handwerk",
    "e-commerce": "E-Commerce",
    "art direction, webgl": "Art Direction, WebGL",
    "global edition": "Internationale Ausgabe",
    "reserve": "Reservieren",
    "owner portal": "Eigentümerbereich",
    "stack": "Technologien",
    "access": "Zugang",
    "initialize": "Starten",
    "system architecture": "Systemarchitektur",
    "command login": "Zugang zur Leitstelle",
    "missions": "Missionen",
    "events": "Veranstaltungen",
    "artists": "Künstler",
    "venues": "Spielstätten",
    "upcoming": "Demnächst",
    "properties": "Unsere Objekte",
    "private inquiry": "Vertrauliche Anfrage",
    "exceptional": "Außergewöhnlich",
    "examples": "Beispiele",
    "plugins": "Erweiterungen",
    "digital experience": "Digitales Erlebnis",
    "brand identity": "Markenidentität",
    "ai revolution": "KI-Revolution",
    "a standard interactive 3d landing page takes 6-8 weeks from concept to deployment. complex data visualizations or configurators may take 12-16 weeks.": "Eine standardmäßige interaktive 3D-Startseite benötigt 6-8 Wochen von der Konzeption bis zur Bereitstellung. Komplexe Datenvisualisierungen oder Konfiguratoren können 12-16 Wochen in Anspruch nehmen.",
    "algorithmic design architectures that react in real-time to user input and audio.": "Algorithmische Entwurfsarchitekturen, die in Echtzeit auf Benutzereingaben und Audio reagieren.",
    "all systems nominal": "ALLE SYSTEME NORMAL",
    "dedicated spatial computing team.": "Ein eigenes Team für räumliches Rechnen.",
    "deployment plans": "Bereitstellungspläne",
    "do you create the 3d assets in-house?": "Erstellen Sie die 3D-Assets intern?",
    "global clients": "Globale Kunden",
    "how does 3d affect website performance?": "Wie beeinflusst 3D die Website-Leistung?",
    "initiate a secure connection with our lead engineers to discuss your spatial computing requirements.": "Eine sichere Verbindung mit unseren leitenden Ingenieuren herstellen, um Ihre Anforderungen an die räumliche Datenverarbeitung zu besprechen.",
    "pioneering the spatial web. we combine aesthetic discipline with extreme technical capabilities to build the digital future.": "Wegbereiter des räumlichen Webs. Wir verbinden ästhetische Strenge mit äußerster technischer Leistungsfähigkeit, um die digitale Zukunft zu bauen.",
    "proof of concept and visual direction.": "Machbarkeitsnachweis und visuelle Richtung.",
    "ready to": "Bereit zu",
    "real-time particle system for tracking server loads.": "Echtzeit-Partikelsystem zur Verfolgung von Serverlasten.",
    "transforming flat pages into interactive 3d environments using three.js and webgl.": "Flache Seiten in interaktive 3D-Umgebungen mit Three.js und WebGL umwandeln.",
    "view demo reel": "Demo ansehen",
    "view repository": "Repository ansehen",
    "we engineer immersive 3d interfaces, webgl experiences, and spatial computing environments for the next era of the web.": "Wir entwickeln immersive 3D-Schnittstellen, WebGL-Erlebnisse und räumliche Computerumgebungen für die nächste Ära des Webs.",
    "what is your typical project timeline?": "Wie sieht Ihr typischer Projektzeitplan aus?",
    "yes, our team includes technical artists who build, rig, and optimize assets specifically for real-time web rendering in blender and maya.": "Ja, unser Team umfasst technische Künstler, die Assets speziell für das Echtzeit-Web-Rendering in Blender und Maya erstellen, riggen und optimieren.",
  },
  pt: {
    "technology stack": "Tecnologias utilizadas",
    "establish connection": "Estabelecer conexão",
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "projects completed": "Projetos entregues",
    "countries": "Países",
    "carbon-negative projects": "Projetos de balanço de carbono negativo",
    "motion graphics": "Motion design",
    "brand films": "Filmes de marca",
    "interactive": "Interativo",
    "brand exploration": "Exploração de marca",
    "fleet": "A frota",
    "network": "Rede",
    "company": "A empresa",
    "craftsmanship": "Saber-fazer",
    "heritage": "Herança",
    "innovation": "Inovação",
    "infrastructure": "Infraestrutura",
    "deploy": "Implementar",
    "fragrances": "Perfumes",
    "digital craft": "Artesanato digital",
    "e-commerce": "Comércio eletrónico",
    "art direction, webgl": "Direção de arte, WebGL",
    "global edition": "Edição internacional",
    "reserve": "Reservar",
    "owner portal": "Área de proprietários",
    "stack": "Tecnologias",
    "access": "Acesso",
    "initialize": "Iniciar",
    "system architecture": "Arquitetura do sistema",
    "command login": "Acesso de controlo",
    "missions": "Missões",
    "events": "Eventos",
    "artists": "Artistas",
    "venues": "Salas",
    "upcoming": "Em breve",
    "properties": "Os nossos imóveis",
    "private inquiry": "Pedido confidencial",
    "exceptional": "Excecional",
    "examples": "Exemplos",
    "plugins": "Extensões",
    "digital experience": "Experiência digital",
    "brand identity": "Identidade de marca",
    "ai revolution": "Revolução da IA",
    "a standard interactive 3d landing page takes 6-8 weeks from concept to deployment. complex data visualizations or configurators may take 12-16 weeks.": "Uma página de aterragem interativa 3D padrão leva de 6 a 8 semanas desde o conceito até à implementação. Visualizações de dados complexas ou configuradores podem levar de 12 a 16 semanas.",
    "algorithmic design architectures that react in real-time to user input and audio.": "Arquiteturas de design algorítmico que reagem em tempo real à entrada do usuário e ao áudio.",
    "all systems nominal": "TODOS OS SISTEMAS NORMAIS",
    "dedicated spatial computing team.": "Uma equipa dedicada à computação espacial.",
    "deployment plans": "Planos de implementação",
    "do you create the 3d assets in-house?": "Criam os ativos 3D internamente?",
    "global clients": "Clientes globais",
    "how does 3d affect website performance?": "Como é que a 3D afeta o desempenho do site?",
    "initiate a secure connection with our lead engineers to discuss your spatial computing requirements.": "Iniciar uma conexão segura com os nossos engenheiros principais para discutir os seus requisitos de computação espacial.",
    "pioneering the spatial web. we combine aesthetic discipline with extreme technical capabilities to build the digital future.": "Desbravar a web espacial. Juntamos uma exigência estética a meios técnicos extremos para construir o futuro digital.",
    "proof of concept and visual direction.": "Prova de conceito e direção visual.",
    "ready to": "Pronto para",
    "real-time particle system for tracking server loads.": "Sistema de partículas em tempo real para rastrear as cargas do servidor.",
    "transforming flat pages into interactive 3d environments using three.js and webgl.": "Transformando páginas planas em ambientes 3D interativos usando Three.js e WebGL.",
    "view demo reel": "Ver demonstração",
    "view repository": "Ver repositório",
    "we engineer immersive 3d interfaces, webgl experiences, and spatial computing environments for the next era of the web.": "Desenvolvemos interfaces 3D imersivas, experiências WebGL e ambientes de computação espacial para a próxima era da web.",
    "what is your typical project timeline?": "Qual é o seu cronograma típico de projeto?",
    "yes, our team includes technical artists who build, rig, and optimize assets specifically for real-time web rendering in blender and maya.": "Sim, a nossa equipa inclui artistas técnicos que constroem, equipam e otimizam ativos especificamente para renderização web em tempo real no Blender e no Maya.",
  },
};
