/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"materials define the limit. we push the limit. engineering the foundation of future performance.\"": "« La matière fixe la limite. Nous la repoussons. Bâtir le socle de la performance à venir. »",
    "0→$2b transactions routed in 90 days": "0→2 milliards de dollars de transactions routées en 90 jours",
    "build.": "CONSTRUIRE.",
    "computational ply-stack optimization driven by finite element analysis. each component has a unique lay-up sequence — no two programs are identical.": "Optimisation de la pile de couches par calcul, basée sur l'analyse par éléments finis. Chaque composant a une séquence de stratification unique — aucun programme n'est identique.",
    "custom epoxy-bismaleimide hybrid matrix engineered in-house for thermal resistance to 320°c while maintaining 4.2 gpa interlaminar shear strength.": "Matrice hybride époxy-bismaleimide sur mesure conçue en interne pour une résistance thermique jusqu'à 320°C tout en maintenant une résistance au cisaillement interlaminaire de 4,2 GPa.",
    "get quote": "Demander un devis",
    "high-rigidity monocoques and aerodynamic components for top-tier racing and hypercars.": "Monocoques à haute rigidité et pièces aérodynamiques pour la compétition de pointe et les hypercars.",
    "i've been in edge computing for a decade. carbon's routing intelligence is the first thing i've seen that actually works at 6ms global p99.": "Je travaille dans le edge computing depuis une décennie. L'intelligence de routage de Carbon est la première chose que j'ai vue qui fonctionne réellement à 6 ms P99 global.",
    "in the": "DANS LE",
    "lay-up architecture": "Architecture de stratification",
    "real-time stress audit": "Audit de stress en temps réel",
    "the dx is phenomenal. i shipped a distributed service in go in under 2 hours. zero config, zero yak shaving. just works.": "L'expérience développeur est phénoménale. J'ai expédié un service distribué en Go en moins de 2 heures. Aucune configuration, aucun tracas. Ça fonctionne.",
    "thermal-resistant composite structures for next-gen orbital flight and satellite chassis.": "Structures composites résistantes à la chaleur, pour le vol orbital et les châssis de satellites.",
    "transform your structural requirements into high-performance assets. we are currently accepting r&d partnerships for q3 2026.": "Faites de vos contraintes structurelles un atout de performance. Nous acceptons des partenariats de recherche pour le 3e trimestre 2026.",
    "trusted by builders": "Approuvé par les constructeurs",
    "we replaced our entire observability stack with carbon in a weekend. the performance gain was immediate — and our infra bill dropped 40%.": "Nous avons remplacé notre pile d'observabilité entière par Carbon en un week-end. Le gain de performance a été immédiat — et notre facture d'infrastructure a chuté de 40%.",
    "what they": "CE QU'ILS",
  },
  es: {
    "\"materials define the limit. we push the limit. engineering the foundation of future performance.\"": "«La materia fija el límite. Nosotros lo empujamos. Construir la base del rendimiento futuro.»",
    "0→$2b transactions routed in 90 days": "0→$2B transacciones enrutadas en 90 días",
    "build.": "CONSTRUIR.",
    "computational ply-stack optimization driven by finite element analysis. each component has a unique lay-up sequence — no two programs are identical.": "Optimización computacional de la pila de capas impulsada por análisis de elementos finitos. Cada componente tiene una secuencia de apilamiento única: ningún programa es idéntico.",
    "custom epoxy-bismaleimide hybrid matrix engineered in-house for thermal resistance to 320°c while maintaining 4.2 gpa interlaminar shear strength.": "Matriz híbrida de epóxido-bismaleimida personalizada diseñada internamente para resistencia térmica hasta 320°C manteniendo una resistencia al corte interlaminar de 4.2 GPa.",
    "get quote": "Pedir presupuesto",
    "high-rigidity monocoques and aerodynamic components for top-tier racing and hypercars.": "Monocascos de alta rigidez y piezas aerodinámicas para la competición de élite y los hiperdeportivos.",
    "i've been in edge computing for a decade. carbon's routing intelligence is the first thing i've seen that actually works at 6ms global p99.": "He estado en la computación en la periferia durante una década. La inteligencia de enrutamiento de Carbon es lo primero que he visto que realmente funciona a 6 ms P99 global.",
    "in the": "EN EL",
    "lay-up architecture": "Arquitectura de apilamiento",
    "real-time stress audit": "Auditoría de estrés en tiempo real",
    "the dx is phenomenal. i shipped a distributed service in go in under 2 hours. zero config, zero yak shaving. just works.": "La experiencia de desarrollador es fenomenal. Envié un servicio distribuido en Go en menos de 2 horas. Sin configuración, sin complicaciones. Simplemente funciona.",
    "thermal-resistant composite structures for next-gen orbital flight and satellite chassis.": "Estructuras compuestas resistentes al calor, para el vuelo orbital y los chasis de satélites.",
    "transform your structural requirements into high-performance assets. we are currently accepting r&d partnerships for q3 2026.": "Convierta sus exigencias estructurales en un activo de rendimiento. Aceptamos alianzas de investigación para el 3.er trimestre de 2026.",
    "trusted by builders": "Confiable para los constructores",
    "we replaced our entire observability stack with carbon in a weekend. the performance gain was immediate — and our infra bill dropped 40%.": "Reemplazamos toda nuestra pila de observabilidad con Carbon en un fin de semana. La ganancia de rendimiento fue inmediata — y nuestra factura de infraestructura bajó un 40%.",
    "what they": "LO QUE",
  },
  de: {
    "\"materials define the limit. we push the limit. engineering the foundation of future performance.\"": "„Das Material setzt die Grenze. Wir verschieben sie. Das Fundament künftiger Leistung bauen.“",
    "0→$2b transactions routed in 90 days": "0→2 Mrd. $ Transaktionen in 90 Tagen",
    "build.": "BAUEN.",
    "computational ply-stack optimization driven by finite element analysis. each component has a unique lay-up sequence — no two programs are identical.": "Computergestützte Optimierung des Schichtstapels, die auf der Finite-Elemente-Analyse basiert. Jedes Bauteil hat eine einzigartige Laminiersequenz – kein Programm ist identisch.",
    "custom epoxy-bismaleimide hybrid matrix engineered in-house for thermal resistance to 320°c while maintaining 4.2 gpa interlaminar shear strength.": "Maßgeschneiderte Epoxid-Bismaleimid-Hybridmatrix, die intern für eine thermische Beständigkeit von bis zu 320 °C entwickelt wurde und eine interlaminare Scherfestigkeit von 4,2 GPa aufweist.",
    "get quote": "Angebot anfordern",
    "high-rigidity monocoques and aerodynamic components for top-tier racing and hypercars.": "Hochsteife Monocoques und aerodynamische Bauteile für Spitzenrennsport und Hypercars.",
    "i've been in edge computing for a decade. carbon's routing intelligence is the first thing i've seen that actually works at 6ms global p99.": "Ich bin seit einem Jahrzehnt im Edge-Computing tätig. Die Routing-Intelligenz von Carbon ist das erste, was ich gesehen habe, das tatsächlich bei 6 ms globalem P99 funktioniert.",
    "in the": "IM",
    "lay-up architecture": "Laminierarchitektur",
    "real-time stress audit": "Echtzeit-Stress-Audit",
    "the dx is phenomenal. i shipped a distributed service in go in under 2 hours. zero config, zero yak shaving. just works.": "Die Entwicklererfahrung ist phänomenal. Ich habe einen verteilten Dienst in Go in weniger als 2 Stunden bereitgestellt. Keine Konfiguration, kein Aufwand. Es funktioniert einfach.",
    "thermal-resistant composite structures for next-gen orbital flight and satellite chassis.": "Hitzebeständige Verbundstrukturen für Orbitalflug und Satellitenrahmen.",
    "transform your structural requirements into high-performance assets. we are currently accepting r&d partnerships for q3 2026.": "Machen Sie aus Ihren strukturellen Anforderungen einen Leistungsvorteil. Wir nehmen Forschungspartnerschaften für das 3. Quartal 2026 an.",
    "trusted by builders": "Vertraut von Bauherren",
    "we replaced our entire observability stack with carbon in a weekend. the performance gain was immediate — and our infra bill dropped 40%.": "Wir haben unseren gesamten Observability-Stack am Wochenende durch Carbon ersetzt. Der Leistungsgewinn war sofort spürbar – und unsere Infrastrukturkosten sanken um 40%.",
    "what they": "WAS SIE",
  },
  pt: {
    "\"materials define the limit. we push the limit. engineering the foundation of future performance.\"": "«A matéria fixa o limite. Nós empurramo-lo. Construir a base do desempenho futuro.»",
    "0→$2b transactions routed in 90 days": "0→2 mil milhões de dólares em transações roteadas em 90 dias",
    "build.": "CONSTRUIR.",
    "computational ply-stack optimization driven by finite element analysis. each component has a unique lay-up sequence — no two programs are identical.": "Otimização computacional da pilha de camadas impulsionada por análise de elementos finitos. Cada componente tem uma sequência de empilhamento única — nenhum programa é idêntico.",
    "custom epoxy-bismaleimide hybrid matrix engineered in-house for thermal resistance to 320°c while maintaining 4.2 gpa interlaminar shear strength.": "Matriz híbrida de epóxi-bismaleimida personalizada projetada internamente para resistência térmica até 320°C, mantendo uma resistência ao cisalhamento interlaminar de 4,2 GPa.",
    "get quote": "Pedir orçamento",
    "high-rigidity monocoques and aerodynamic components for top-tier racing and hypercars.": "Monocoques de alta rigidez e peças aerodinâmicas para a competição de topo e os hipercarros.",
    "i've been in edge computing for a decade. carbon's routing intelligence is the first thing i've seen that actually works at 6ms global p99.": "Estou no edge computing há uma década. A inteligência de roteamento do Carbon é a primeira coisa que vi que realmente funciona a 6 ms P99 global.",
    "in the": "NO",
    "lay-up architecture": "Arquitetura de empilhamento",
    "real-time stress audit": "Auditoria de stress em tempo real",
    "the dx is phenomenal. i shipped a distributed service in go in under 2 hours. zero config, zero yak shaving. just works.": "A experiência do desenvolvedor é fenomenal. Enviei um serviço distribuído em Go em menos de 2 horas. Sem configuração, sem complicações. Funciona.",
    "thermal-resistant composite structures for next-gen orbital flight and satellite chassis.": "Estruturas compósitas resistentes ao calor, para o voo orbital e os chassis de satélites.",
    "transform your structural requirements into high-performance assets. we are currently accepting r&d partnerships for q3 2026.": "Transforme as suas exigências estruturais num ativo de desempenho. Aceitamos parcerias de investigação para o 3.º trimestre de 2026.",
    "trusted by builders": "Confiável pelos construtores",
    "we replaced our entire observability stack with carbon in a weekend. the performance gain was immediate — and our infra bill dropped 40%.": "Substituímos toda a nossa pilha de observabilidade pelo Carbon em um fim de semana. O ganho de desempenho foi imediato — e a nossa fatura de infraestrutura caiu 40%.",
    "what they": "O QUE",
  },
};
