/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "Les auditions sont disponibles uniquement sur rendez-vous dans notre Atelier de Berlin ou par l'intermédiaire de nos partenaires privés sélectionnés à Londres, Tokyo et New York.",
    "can i audition the systems in person?": "Puis-je écouter les systèmes sur place ?",
    "client lounge": "Salon Client",
    "do you offer on-site acoustic calibration?": "Proposez-vous un calage acoustique sur place ?",
    "download technical archive": "Télécharger l'archive technique",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "En raison de la nature artisanale de nos haut-parleurs électrostatiques et de nos boîtiers usinés CNC, le délai actuel est de 12 à 16 semaines à partir de la confirmation de commande.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Des haut-parleurs électrostatiques associés à un filtre à tubes à vide pour une réponse transitoire inégalée.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Chaque boîtier est usiné CNC à partir de blocs solides d'aluminium aéronautique pour éliminer les résonances internes.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Chaque système de référence comprend une visite de calibration sur site de 3 jours par un ingénieur senior d'Aether pour optimiser l'acoustique de la pièce et l'alignement du système.",
    "is the system compatible with digital streamers?": "Le système est-il compatible avec les lecteurs réseau ?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Câblage point à point à la main avec des conducteurs en argent 6N garantissant aucune distorsion de phase sur l'ensemble du spectre.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Algorithmes DSP propriétaires qui préservent le 'souffle' des enregistrements en direct tout en gérant l'acoustique de la pièce.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Amplification Pure Classe A sans rétroaction négative, logée dans un châssis monolithique en cuivre.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "DAC échelle R2R avec horloge en femtosecondes pour la conversion numérique-analogique la plus naturelle.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Redéfinir le seuil de l'audition. Instruments sonores de précision pour les oreilles les plus exigeantes du monde.",
    "request audition": "Demander une audition",
    "schedule listening session": "Planifier une session d'écoute",
    "signal to noise ratio": "Rapport Signal sur Bruit",
    "signal-to-noise": "Signal sur Bruit",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "La maîtrise absolue de l'ingénierie acoustique. Conçue pour l'audiophile exigeant, dans notre atelier berlinois.",
    "the chronology": "La chronologie",
    "the craftsmen": "Les artisans",
    "the maison": "La Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Nous offrons une garantie complète de 5 ans sur tous les châssis et circuits, et une garantie de performance de 1 an sur tous les tubes à vide premium sélectionnés.",
    "what is the lead time for aether one monitors?": "Quel est le délai de fabrication ?",
    "what is the warranty on vacuum-tube components?": "Quelle est la garantie sur les composants à tubes ?",
  },
  es: {
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "Las audiciones están disponibles estrictamente con cita previa en nuestro Atelier de Berlín o a través de nuestros selectos socios privados en Londres, Tokio y Nueva York.",
    "can i audition the systems in person?": "¿Puedo escuchar los equipos en persona?",
    "client lounge": "Salón del Cliente",
    "do you offer on-site acoustic calibration?": "¿Ofrecen calibración acústica in situ?",
    "download technical archive": "Descargar el archivo técnico",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "Debido a la naturaleza artesanal de nuestros controladores electrostáticos y carcasas fresadas en CNC, el tiempo de entrega actual es de 12 a 16 semanas a partir de la confirmación del pedido.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Controladores electrostáticos emparejados con un cruce de tubos de vacío para una respuesta transitoria inigualable.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Cada carcasa está fresada en CNC a partir de bloques sólidos de aluminio aeronáutico para eliminar resonancias internas.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Cada sistema de referencia incluye una visita de calibración in situ de 3 días por un ingeniero senior de Aether para optimizar la acústica de la sala y la alineación del sistema.",
    "is the system compatible with digital streamers?": "¿El sistema es compatible con los reproductores en red?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Cableado punto a punto hecho a mano con conductores de plata 6N que garantizan cero distorsión de fase en todo el espectro.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Algoritmos DSP propietarios que preservan el 'aliento' de las grabaciones en vivo mientras gestionan la acústica de la sala.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Amplificación de Clase A pura sin retroalimentación negativa, alojada en un chasis monolítico de cobre.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "DAC de escalera R2R con temporización en femtosegundos para la conversión digital a analógica más natural.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Redefiniendo el umbral de la audición. Instrumentos sonoros de precisión para los oídos más exigentes del mundo.",
    "request audition": "Solicitar audición",
    "schedule listening session": "Programar sesión de escucha",
    "signal to noise ratio": "Relación Señal a Ruido",
    "signal-to-noise": "Señal a Ruido",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "El dominio absoluto de la ingeniería acústica. Concebido para el audiófilo exigente, en nuestro taller berlinés.",
    "the chronology": "La cronología",
    "the craftsmen": "Los artesanos",
    "the maison": "La Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Ofrecemos una garantía integral de 5 años en todos los chasis y circuitos, y una garantía de rendimiento de 1 año en todos los tubos de vacío premium seleccionados.",
    "what is the lead time for aether one monitors?": "¿Cuál es el plazo de fabricación?",
    "what is the warranty on vacuum-tube components?": "¿Cuál es la garantía de los componentes de válvulas?",
  },
  de: {
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "Vorführungen sind ausschließlich nach Vereinbarung in unserem Atelier in Berlin oder über unsere ausgewählten privaten Partner in London, Tokio und New York verfügbar.",
    "can i audition the systems in person?": "Kann ich die Systeme vor Ort hören?",
    "client lounge": "Kundenlounge",
    "do you offer on-site acoustic calibration?": "Bieten Sie eine akustische Einmessung vor Ort an?",
    "download technical archive": "Technisches Archiv herunterladen",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "Aufgrund der handgefertigten Natur unserer elektrostatischen Treiber und CNC-gefrästen Gehäuse beträgt die aktuelle Lieferzeit 12 bis 16 Wochen nach Auftragsbestätigung.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Elektrostatische Treiber kombiniert mit einem Vakuumröhren-Crossover für unvergleichliche Transientenreaktion.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Jedes Gehäuse wird CNC-gefräst aus massiven Blöcken aus Luftfahrtaluminium, um interne Resonanzen zu eliminieren.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Jedes Referenzsystem umfasst einen 3-tägigen Vor-Ort-Kalibrierungsbesuch durch einen Senior Engineer von Aether, um die Raumakustik und die Systemausrichtung zu optimieren.",
    "is the system compatible with digital streamers?": "Ist das System mit Netzwerk-Streamern kompatibel?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Punkt-zu-Punkt-Handverdrahtung mit 6N-Silberleitern, die eine Null-Phasendistortion über das gesamte Spektrum gewährleisten.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Proprietäre DSP-Algorithmen, die den 'Atem' von Live-Aufnahmen bewahren und gleichzeitig die Raumakustik steuern.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Reine Class-A-Verstärkung ohne negative Rückkopplung, untergebracht in einem monolithischen Kupfergehäuse.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "R2R-Leiter-DAC mit Femtosekunden-Taktung für die natürlichste digitale-zu-analoge Umwandlung.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Die Schwelle des Hörens neu definieren. Präzise Klanginstrumente für die anspruchsvollsten Ohren der Welt.",
    "request audition": "Audition anfordern",
    "schedule listening session": "Hörsitzung planen",
    "signal to noise ratio": "Signal-Rausch-Verhältnis",
    "signal-to-noise": "Signal-Rausch",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "Die absolute Beherrschung der Akustiktechnik. Für den anspruchsvollen Audiophilen, in unserer Berliner Werkstatt.",
    "the chronology": "Die Chronologie",
    "the craftsmen": "Die Handwerker",
    "the maison": "Das Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Wir bieten eine umfassende 5-Jahres-Garantie auf alle Gehäuse und Schaltungen sowie eine 1-Jahres-Leistungsgarantie auf alle ausgewählten Premium-Vakuumröhren.",
    "what is the lead time for aether one monitors?": "Wie lang ist die Lieferzeit?",
    "what is the warranty on vacuum-tube components?": "Wie lange ist die Garantie auf Röhrenbauteile?",
  },
  pt: {
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "As audições estão disponíveis estritamente por marcação no nosso Atelier em Berlim ou através dos nossos parceiros privados selecionados em Londres, Tóquio e Nova Iorque.",
    "can i audition the systems in person?": "Posso ouvir os sistemas no local?",
    "client lounge": "Sala de Clientes",
    "do you offer on-site acoustic calibration?": "Oferecem calibração acústica no local?",
    "download technical archive": "Transferir o arquivo técnico",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "Devido à natureza artesanal dos nossos drivers eletrostáticos e das caixas fresadas em CNC, o prazo de entrega atual é de 12 a 16 semanas a partir da confirmação do pedido.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Drivers eletrostáticos emparelhados com um crossover de tubo a vácuo para uma resposta transitória inigualável.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Cada caixa é fresada em CNC a partir de blocos sólidos de alumínio aeronáutico para eliminar ressonâncias internas.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Cada sistema de referência inclui uma visita de calibração no local de 3 dias por um Engenheiro Sênior da Aether para otimizar a acústica do ambiente e o alinhamento do sistema.",
    "is the system compatible with digital streamers?": "O sistema é compatível com os leitores em rede?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Fiação ponto a ponto feita à mão com condutores de prata 6N garantindo zero distorção de fase em todo o espectro.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Algoritmos DSP proprietários que preservam o 'sopro' de gravações ao vivo enquanto gerenciam a acústica do ambiente.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Amplificação Classe A pura sem retroalimentação negativa, alojada em um chassi monolítico de cobre.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "DAC de escada R2R com temporização em femtosegundos para a conversão digital-analógica mais natural.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Redefinindo o limiar da audição. Instrumentos sonoros de precisão para os ouvidos mais exigentes do mundo.",
    "request audition": "Solicitar audição",
    "schedule listening session": "Agendar sessão de escuta",
    "signal to noise ratio": "Relação Sinal-Ruído",
    "signal-to-noise": "Sinal-Ruído",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "O domínio absoluto da engenharia acústica. Concebido para o audiófilo exigente, na nossa oficina berlinense.",
    "the chronology": "A cronologia",
    "the craftsmen": "Os artesãos",
    "the maison": "A Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Oferecemos uma garantia abrangente de 5 anos em todos os chassi e circuitos, e uma garantia de desempenho de 1 ano em todos os tubos a vácuo premium selecionados.",
    "what is the lead time for aether one monitors?": "Qual é o prazo de fabrico?",
    "what is the warranty on vacuum-tube components?": "Qual é a garantia dos componentes de válvulas?",
  },
};
