/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "pure": "La pure",
    "reference": "Référence",
    "amplification": "Amplification",
    "source": "Sources",
    "current collection": "Collection en cours",
    "frequency range": "Bande passante",
    "master craftsmen": "Maîtres artisans",
    "countries served": "Pays livrés",
    "reference monitors": "Enceintes de référence",
    "digital source": "Source numérique",
    "sonic integrity": "Intégrité sonore",
    "physical": "Acoustique",
    "acoustics.": "physique.",
    "acoustic geometry": "Géométrie acoustique",
    "signal purity": "Pureté du signal",
    "harmonic integrity": "Intégrité harmonique",
    "vacuum tube": "Architecture",
    "1:1 accuracy": "Fidélité 1:1",
    "zero phase drift": "Aucune dérive de phase",
    "r2r ladder dac": "Convertisseur R2R en échelle",
    "0.2ms transient": "Transitoire à 0,2 ms",
    "three": "Trois",
    "decades.": "décennies.",
    "acoustic manifest": "Manifeste acoustique",
    "full": "Le spectre",
    "spectrum.": "entier.",
    "specification": "Caractéristique",
    "frequency response": "Réponse en fréquence",
    "total harmonic dist.": "Distorsion harmonique totale",
    "output impedance": "Impédance de sortie",
    "chassis material": "Matériau du châssis",
    "t6 aluminum": "Aluminium T6",
    "c110 copper": "Cuivre C110",
    "aircraft grade ti": "Titane qualité aéronautique",
    "weight (kg)": "Poids (kg)",
    "85kg / unit": "85 kg par enceinte",
    "human": "L'élément",
    "element.": "humain.",
    "master luthier & cabinetist": "Maître luthier et ébéniste",
    "senior analog engineer": "Ingénieure analogique senior",
    "sonic": "Dialogues",
    "dialogues.": "sonores.",
    "instruments": "Instruments",
    "beyond the measurement. we design sonic instruments that merge the mathematical precision of modern electronics with the emotional warmth of vintage analog philosophy.": "Au-delà de la mesure. Nous dessinons des instruments sonores qui allient la précision mathématique de l'électronique moderne à la chaleur des philosophies analogiques d'autrefois.",
    "since 1994, aether has operated at the intersection of material science and auditory emotion. our journey began in a small workshop in kreuzberg and has evolved into a global benchmark for reference sound.": "Depuis 1994, la maison travaille au croisement de la science des matériaux et de l'émotion sonore. L'aventure a commencé dans un petit atelier de Kreuzberg ; elle fait aujourd'hui référence.",
    "the aether lab is founded. initial research into electrostatic driver stability begins.": "Fondation du laboratoire. Premiers travaux sur la stabilité des transducteurs électrostatiques.",
    "launch of the vortex series. first implementation of pure class-a copper chassis amplification.": "Lancement de la série Vortex. Première amplification en classe A pure sur châssis cuivre.",
    "aether one is released. redefining the frequency response limit for commercial monitors.": "Sortie de l'Aether One, qui redéfinit la limite de réponse en fréquence des moniteurs du marché.",
    "integration of femto-clocking across the entire digital source lineup.": "Intégration de l'horloge femtoseconde sur toute la gamme de sources numériques.",
    "wood is a living resonator. we treat our speaker enclosures like cellos—carefully aged, meticulously tensioned, and finished with organic oils to preserve the wood's natural breath.": "Le bois est un résonateur vivant. Nous traitons nos ébénisteries comme des violoncelles : séchage lent, tension réglée au dixième, finition à l'huile pour laisser le bois respirer.",
    "silicon has its place, but for pure emotional transmission, vacuum tubes remain the gold standard. we design circuits that respect the soul of the signal while pushing the limits of modern stability.": "Le silicium a sa place, mais pour transmettre l'émotion, la lampe reste la référence. Nous dessinons des circuits qui respectent l'âme du signal tout en poussant la stabilité au maximum.",
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "Les auditions sont disponibles uniquement sur rendez-vous dans notre Atelier de Berlin ou par l'intermédiaire de nos partenaires privés sélectionnés à Londres, Tokyo et New York.",
    "can i audition the systems in person?": "Puis-je écouter les systèmes sur place ?",
    "client lounge": "Salon Client",
    "do you offer on-site acoustic calibration?": "Proposez-vous un calage acoustique sur place ?",
    "download technical archive": "Télécharger l'archive technique",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "En raison de la nature artisanale de nos haut-parleurs électrostatiques et de nos boîtiers usinés CNC, le délai actuel est de 12 à 16 semaines à partir de la confirmation de commande.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Des haut-parleurs électrostatiques associés à un filtre à tubes à vide pour une réponse transitoire inégalée.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Chaque boîtier est usiné CNC à partir de blocs solides d'aluminium aéronautique pour éliminer les résonances internes.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Chaque système de référence comprend une visite de calibration sur site de 3 jours par un ingénieur senior d'Aether pour optimiser l'acoustique de la pièce et l'alignement du système.",
    "is the system compatible with digital streamers?": "Le système est-il compatible avec les lecteurs réseau ?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Câblage point à point à la main avec des conducteurs en argent 6N garantissant aucune distorsion de phase sur l'ensemble du spectre.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Algorithmes DSP propriétaires qui préservent le 'souffle' des enregistrements en direct tout en gérant l'acoustique de la pièce.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Amplification Pure Classe A sans rétroaction négative, logée dans un châssis monolithique en cuivre.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "DAC échelle R2R avec horloge en femtosecondes pour la conversion numérique-analogique la plus naturelle.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Redéfinir le seuil de l'audition. Instruments sonores de précision pour les oreilles les plus exigeantes du monde.",
    "request audition": "Demander une audition",
    "schedule listening session": "Planifier une session d'écoute",
    "signal to noise ratio": "Rapport Signal sur Bruit",
    "signal-to-noise": "Signal sur Bruit",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "La maîtrise absolue de l'ingénierie acoustique. Conçue pour l'audiophile exigeant, dans notre atelier berlinois.",
    "the chronology": "La chronologie",
    "the craftsmen": "Les artisans",
    "the maison": "La Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Nous offrons une garantie complète de 5 ans sur tous les châssis et circuits, et une garantie de performance de 1 an sur tous les tubes à vide premium sélectionnés.",
    "what is the lead time for aether one monitors?": "Quel est le délai de fabrication ?",
    "what is the warranty on vacuum-tube components?": "Quelle est la garantie sur les composants à tubes ?",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "pure": "La pura",
    "reference": "Referencia",
    "amplification": "Amplificación",
    "source": "Fuentes",
    "current collection": "Colección actual",
    "frequency range": "Rango de frecuencia",
    "master craftsmen": "Maestros artesanos",
    "countries served": "Países atendidos",
    "reference monitors": "Monitores de referencia",
    "digital source": "Fuente digital",
    "sonic integrity": "Integridad sonora",
    "physical": "Acústica",
    "acoustics.": "física.",
    "acoustic geometry": "Geometría acústica",
    "signal purity": "Pureza de la señal",
    "harmonic integrity": "Integridad armónica",
    "vacuum tube": "Arquitectura",
    "1:1 accuracy": "Fidelidad 1:1",
    "zero phase drift": "Sin deriva de fase",
    "r2r ladder dac": "Conversor R2R en escalera",
    "0.2ms transient": "Transitorio a 0,2 ms",
    "three": "Tres",
    "decades.": "décadas.",
    "acoustic manifest": "Manifiesto acústico",
    "full": "El espectro",
    "spectrum.": "completo.",
    "specification": "Característica",
    "frequency response": "Respuesta en frecuencia",
    "total harmonic dist.": "Distorsión armónica total",
    "output impedance": "Impedancia de salida",
    "chassis material": "Material del chasis",
    "t6 aluminum": "Aluminio T6",
    "c110 copper": "Cobre C110",
    "aircraft grade ti": "Titanio de calidad aeronáutica",
    "weight (kg)": "Peso (kg)",
    "85kg / unit": "85 kg por unidad",
    "human": "El elemento",
    "element.": "humano.",
    "master luthier & cabinetist": "Maestro luthier y ebanista",
    "senior analog engineer": "Ingeniera analógica sénior",
    "sonic": "Diálogos",
    "dialogues.": "sonoros.",
    "instruments": "Instrumentos",
    "beyond the measurement. we design sonic instruments that merge the mathematical precision of modern electronics with the emotional warmth of vintage analog philosophy.": "Más allá de la medida. Diseñamos instrumentos sonoros que unen la precisión matemática de la electrónica moderna con la calidez de las filosofías analógicas de antaño.",
    "since 1994, aether has operated at the intersection of material science and auditory emotion. our journey began in a small workshop in kreuzberg and has evolved into a global benchmark for reference sound.": "Desde 1994, la casa trabaja en el cruce entre la ciencia de materiales y la emoción sonora. La aventura empezó en un pequeño taller de Kreuzberg; hoy es una referencia.",
    "the aether lab is founded. initial research into electrostatic driver stability begins.": "Fundación del laboratorio. Primeros trabajos sobre la estabilidad de los transductores electrostáticos.",
    "launch of the vortex series. first implementation of pure class-a copper chassis amplification.": "Lanzamiento de la serie Vortex. Primera amplificación en clase A pura sobre chasis de cobre.",
    "aether one is released. redefining the frequency response limit for commercial monitors.": "Salida del Aether One, que redefine el límite de respuesta en frecuencia de los monitores del mercado.",
    "integration of femto-clocking across the entire digital source lineup.": "Integración del reloj de femtosegundo en toda la gama de fuentes digitales.",
    "wood is a living resonator. we treat our speaker enclosures like cellos—carefully aged, meticulously tensioned, and finished with organic oils to preserve the wood's natural breath.": "La madera es un resonador vivo. Tratamos nuestras cajas como violonchelos: secado lento, tensión ajustada al décimo, acabado al aceite para dejar respirar la madera.",
    "silicon has its place, but for pure emotional transmission, vacuum tubes remain the gold standard. we design circuits that respect the soul of the signal while pushing the limits of modern stability.": "El silicio tiene su lugar, pero para transmitir emoción la válvula sigue siendo la referencia. Diseñamos circuitos que respetan el alma de la señal llevando la estabilidad al máximo.",
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "Las audiciones están disponibles estrictamente con cita previa en nuestro Atelier de Berlín o a través de nuestros selectos socios privados en Londres, Tokio y Nueva York.",
    "can i audition the systems in person?": "¿Puedo escuchar los equipos en persona?",
    "client lounge": "Salón del Cliente",
    "do you offer on-site acoustic calibration?": "¿Ofrecen calibración acústica in situ?",
    "download technical archive": "Descargar el archivo técnico",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "Debido a la naturaleza artesanal de nuestros controladores electrostáticos y carcasas fresadas en CNC, el tiempo de entrega actual es de 12 a 16 semanas a partir de la confirmación del pedido.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Controladores electrostáticos emparejados con un cruce de tubos de vacío para una respuesta transitoria inigualable.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Cada carcasa está fresada en CNC a partir de bloques sólidos de aluminio aeronáutico para eliminar resonancias internas.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Cada sistema de referencia incluye una visita de calibración in situ de 3 días por un ingeniero senior de Aether para optimizar la acústica de la sala y la alineación del sistema.",
    "is the system compatible with digital streamers?": "¿El sistema es compatible con los reproductores en red?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Cableado punto a punto hecho a mano con conductores de plata 6N que garantizan cero distorsión de fase en todo el espectro.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Algoritmos DSP propietarios que preservan el 'aliento' de las grabaciones en vivo mientras gestionan la acústica de la sala.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Amplificación de Clase A pura sin retroalimentación negativa, alojada en un chasis monolítico de cobre.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "DAC de escalera R2R con temporización en femtosegundos para la conversión digital a analógica más natural.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Redefiniendo el umbral de la audición. Instrumentos sonoros de precisión para los oídos más exigentes del mundo.",
    "request audition": "Solicitar audición",
    "schedule listening session": "Programar sesión de escucha",
    "signal to noise ratio": "Relación Señal a Ruido",
    "signal-to-noise": "Señal a Ruido",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "El dominio absoluto de la ingeniería acústica. Concebido para el audiófilo exigente, en nuestro taller berlinés.",
    "the chronology": "La cronología",
    "the craftsmen": "Los artesanos",
    "the maison": "La Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Ofrecemos una garantía integral de 5 años en todos los chasis y circuitos, y una garantía de rendimiento de 1 año en todos los tubos de vacío premium seleccionados.",
    "what is the lead time for aether one monitors?": "¿Cuál es el plazo de fabricación?",
    "what is the warranty on vacuum-tube components?": "¿Cuál es la garantía de los componentes de válvulas?",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "pure": "Die reine",
    "reference": "Referenz",
    "amplification": "Verstärkung",
    "source": "Quellen",
    "current collection": "Aktuelle Kollektion",
    "frequency range": "Frequenzbereich",
    "master craftsmen": "Meisterhandwerker",
    "countries served": "Belieferte Länder",
    "reference monitors": "Referenzmonitore",
    "digital source": "Digitale Quelle",
    "sonic integrity": "Klangliche Integrität",
    "physical": "Akustik",
    "acoustics.": "der Physik.",
    "acoustic geometry": "Akustische Geometrie",
    "signal purity": "Signalreinheit",
    "harmonic integrity": "Harmonische Integrität",
    "vacuum tube": "Architektur",
    "1:1 accuracy": "1:1-Genauigkeit",
    "zero phase drift": "Keine Phasendrift",
    "r2r ladder dac": "R2R-Leiter-DAC",
    "0.2ms transient": "Transiente bei 0,2 ms",
    "three": "Drei",
    "decades.": "Jahrzehnte.",
    "acoustic manifest": "Akustisches Manifest",
    "full": "Das ganze",
    "spectrum.": "Spektrum.",
    "specification": "Kenngröße",
    "frequency response": "Frequenzgang",
    "total harmonic dist.": "Gesamtklirrfaktor",
    "output impedance": "Ausgangsimpedanz",
    "chassis material": "Gehäusematerial",
    "t6 aluminum": "Aluminium T6",
    "c110 copper": "Kupfer C110",
    "aircraft grade ti": "Titan in Luftfahrtqualität",
    "weight (kg)": "Gewicht (kg)",
    "85kg / unit": "85 kg pro Einheit",
    "human": "Der Mensch",
    "element.": "im Mittelpunkt.",
    "master luthier & cabinetist": "Meisterlutier und Kunsttischler",
    "senior analog engineer": "Leitende Analogingenieurin",
    "sonic": "Klangliche",
    "dialogues.": "Dialoge.",
    "instruments": "Instrumente",
    "beyond the measurement. we design sonic instruments that merge the mathematical precision of modern electronics with the emotional warmth of vintage analog philosophy.": "Jenseits der Messung. Wir entwerfen Klanginstrumente, die die mathematische Präzision moderner Elektronik mit der Wärme alter analoger Philosophien verbinden.",
    "since 1994, aether has operated at the intersection of material science and auditory emotion. our journey began in a small workshop in kreuzberg and has evolved into a global benchmark for reference sound.": "Seit 1994 arbeitet das Haus an der Schnittstelle von Materialwissenschaft und klanglicher Emotion. Angefangen hat es in einer kleinen Werkstatt in Kreuzberg; heute ist es eine Referenz.",
    "the aether lab is founded. initial research into electrostatic driver stability begins.": "Gründung des Labors. Erste Arbeiten zur Stabilität elektrostatischer Wandler.",
    "launch of the vortex series. first implementation of pure class-a copper chassis amplification.": "Start der Vortex-Serie. Erste reine Class-A-Verstärkung auf Kupferchassis.",
    "aether one is released. redefining the frequency response limit for commercial monitors.": "Erscheinen des Aether One, das die Grenze des Frequenzgangs marktüblicher Monitore neu definiert.",
    "integration of femto-clocking across the entire digital source lineup.": "Integration des Femtosekunden-Taktgebers in die gesamte Reihe digitaler Quellen.",
    "wood is a living resonator. we treat our speaker enclosures like cellos—carefully aged, meticulously tensioned, and finished with organic oils to preserve the wood's natural breath.": "Holz ist ein lebendiger Resonator. Wir behandeln unsere Gehäuse wie Celli: langsame Trocknung, auf den Zehntel eingestellte Spannung, Ölfinish, damit das Holz atmet.",
    "silicon has its place, but for pure emotional transmission, vacuum tubes remain the gold standard. we design circuits that respect the soul of the signal while pushing the limits of modern stability.": "Silizium hat seinen Platz, doch für die Übertragung von Emotion bleibt die Röhre die Referenz. Wir entwerfen Schaltungen, die die Seele des Signals achten und die Stabilität ausreizen.",
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "Vorführungen sind ausschließlich nach Vereinbarung in unserem Atelier in Berlin oder über unsere ausgewählten privaten Partner in London, Tokio und New York verfügbar.",
    "can i audition the systems in person?": "Kann ich die Systeme vor Ort hören?",
    "client lounge": "Kundenlounge",
    "do you offer on-site acoustic calibration?": "Bieten Sie eine akustische Einmessung vor Ort an?",
    "download technical archive": "Technisches Archiv herunterladen",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "Aufgrund der handgefertigten Natur unserer elektrostatischen Treiber und CNC-gefrästen Gehäuse beträgt die aktuelle Lieferzeit 12 bis 16 Wochen nach Auftragsbestätigung.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Elektrostatische Treiber kombiniert mit einem Vakuumröhren-Crossover für unvergleichliche Transientenreaktion.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Jedes Gehäuse wird CNC-gefräst aus massiven Blöcken aus Luftfahrtaluminium, um interne Resonanzen zu eliminieren.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Jedes Referenzsystem umfasst einen 3-tägigen Vor-Ort-Kalibrierungsbesuch durch einen Senior Engineer von Aether, um die Raumakustik und die Systemausrichtung zu optimieren.",
    "is the system compatible with digital streamers?": "Ist das System mit Netzwerk-Streamern kompatibel?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Punkt-zu-Punkt-Handverdrahtung mit 6N-Silberleitern, die eine Null-Phasendistortion über das gesamte Spektrum gewährleisten.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Proprietäre DSP-Algorithmen, die den 'Atem' von Live-Aufnahmen bewahren und gleichzeitig die Raumakustik steuern.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Reine Class-A-Verstärkung ohne negative Rückkopplung, untergebracht in einem monolithischen Kupfergehäuse.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "R2R-Leiter-DAC mit Femtosekunden-Taktung für die natürlichste digitale-zu-analoge Umwandlung.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Die Schwelle des Hörens neu definieren. Präzise Klanginstrumente für die anspruchsvollsten Ohren der Welt.",
    "request audition": "Audition anfordern",
    "schedule listening session": "Hörsitzung planen",
    "signal to noise ratio": "Signal-Rausch-Verhältnis",
    "signal-to-noise": "Signal-Rausch",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "Die absolute Beherrschung der Akustiktechnik. Für den anspruchsvollen Audiophilen, in unserer Berliner Werkstatt.",
    "the chronology": "Die Chronologie",
    "the craftsmen": "Die Handwerker",
    "the maison": "Das Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Wir bieten eine umfassende 5-Jahres-Garantie auf alle Gehäuse und Schaltungen sowie eine 1-Jahres-Leistungsgarantie auf alle ausgewählten Premium-Vakuumröhren.",
    "what is the lead time for aether one monitors?": "Wie lang ist die Lieferzeit?",
    "what is the warranty on vacuum-tube components?": "Wie lange ist die Garantie auf Röhrenbauteile?",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "pure": "A pura",
    "reference": "Referência",
    "amplification": "Amplificação",
    "source": "Fontes",
    "current collection": "Coleção atual",
    "frequency range": "Gama de frequências",
    "master craftsmen": "Mestres artesãos",
    "countries served": "Países servidos",
    "reference monitors": "Monitores de referência",
    "digital source": "Fonte digital",
    "sonic integrity": "Integridade sonora",
    "physical": "Acústica",
    "acoustics.": "física.",
    "acoustic geometry": "Geometria acústica",
    "signal purity": "Pureza do sinal",
    "harmonic integrity": "Integridade harmónica",
    "vacuum tube": "Arquitetura",
    "1:1 accuracy": "Fidelidade 1:1",
    "zero phase drift": "Sem deriva de fase",
    "r2r ladder dac": "Conversor R2R em escada",
    "0.2ms transient": "Transitório a 0,2 ms",
    "three": "Três",
    "decades.": "décadas.",
    "acoustic manifest": "Manifesto acústico",
    "full": "O espetro",
    "spectrum.": "inteiro.",
    "specification": "Característica",
    "frequency response": "Resposta em frequência",
    "total harmonic dist.": "Distorção harmónica total",
    "output impedance": "Impedância de saída",
    "chassis material": "Material do chassis",
    "t6 aluminum": "Alumínio T6",
    "c110 copper": "Cobre C110",
    "aircraft grade ti": "Titânio de qualidade aeronáutica",
    "weight (kg)": "Peso (kg)",
    "85kg / unit": "85 kg por unidade",
    "human": "O elemento",
    "element.": "humano.",
    "master luthier & cabinetist": "Mestre luthier e ebanista",
    "senior analog engineer": "Engenheira analógica sénior",
    "sonic": "Diálogos",
    "dialogues.": "sonoros.",
    "instruments": "Instrumentos",
    "beyond the measurement. we design sonic instruments that merge the mathematical precision of modern electronics with the emotional warmth of vintage analog philosophy.": "Para lá da medida. Desenhamos instrumentos sonoros que aliam a precisão matemática da eletrónica moderna ao calor das filosofias analógicas de outrora.",
    "since 1994, aether has operated at the intersection of material science and auditory emotion. our journey began in a small workshop in kreuzberg and has evolved into a global benchmark for reference sound.": "Desde 1994, a casa trabalha no cruzamento entre a ciência dos materiais e a emoção sonora. A aventura começou numa pequena oficina em Kreuzberg; hoje é uma referência.",
    "the aether lab is founded. initial research into electrostatic driver stability begins.": "Fundação do laboratório. Primeiros trabalhos sobre a estabilidade dos transdutores eletrostáticos.",
    "launch of the vortex series. first implementation of pure class-a copper chassis amplification.": "Lançamento da série Vortex. Primeira amplificação em classe A pura sobre chassi de cobre.",
    "aether one is released. redefining the frequency response limit for commercial monitors.": "Saída do Aether One, que redefine o limite de resposta em frequência dos monitores do mercado.",
    "integration of femto-clocking across the entire digital source lineup.": "Integração do relógio de fentossegundo em toda a gama de fontes digitais.",
    "wood is a living resonator. we treat our speaker enclosures like cellos—carefully aged, meticulously tensioned, and finished with organic oils to preserve the wood's natural breath.": "A madeira é um ressoador vivo. Tratamos as nossas caixas como violoncelos: secagem lenta, tensão afinada ao décimo, acabamento a óleo para deixar a madeira respirar.",
    "silicon has its place, but for pure emotional transmission, vacuum tubes remain the gold standard. we design circuits that respect the soul of the signal while pushing the limits of modern stability.": "O silício tem o seu lugar, mas para transmitir emoção a válvula continua a ser a referência. Desenhamos circuitos que respeitam a alma do sinal levando a estabilidade ao máximo.",
    "auditions are available strictly by appointment at our berlin atelier or through our select private partners in london, tokyo, and new york.": "As audições estão disponíveis estritamente por marcação no nosso Atelier em Berlim ou através dos nossos parceiros privados selecionados em Londres, Tóquio e Nova Iorque.",
    "can i audition the systems in person?": "Posso ouvir os sistemas no local?",
    "client lounge": "Sala de Clientes",
    "do you offer on-site acoustic calibration?": "Oferecem calibração acústica no local?",
    "download technical archive": "Transferir o arquivo técnico",
    "due to the hand-crafted nature of our electrostatic drivers and cnc-milled enclosures, current lead time is 12 to 16 weeks from order confirmation.": "Devido à natureza artesanal dos nossos drivers eletrostáticos e das caixas fresadas em CNC, o prazo de entrega atual é de 12 a 16 semanas a partir da confirmação do pedido.",
    "electrostatic drivers paired with a vacuum-tube crossover for unparalleled transient response.": "Drivers eletrostáticos emparelhados com um crossover de tubo a vácuo para uma resposta transitória inigualável.",
    "every enclosure is cnc-milled from solid blocks of aeronautical aluminum to eliminate internal resonances.": "Cada caixa é fresada em CNC a partir de blocos sólidos de alumínio aeronáutico para eliminar ressonâncias internas.",
    "every reference system includes a 3-day on-site calibration visit by an aether senior engineer to optimize room acoustics and system alignment.": "Cada sistema de referência inclui uma visita de calibração no local de 3 dias por um Engenheiro Sênior da Aether para otimizar a acústica do ambiente e o alinhamento do sistema.",
    "is the system compatible with digital streamers?": "O sistema é compatível com os leitores em rede?",
    "point-to-point hand-wiring with 6n silver conductors ensuring zero phase distortion across the spectrum.": "Fiação ponto a ponto feita à mão com condutores de prata 6N garantindo zero distorção de fase em todo o espectro.",
    "proprietary dsp algorithms that preserve the 'breath' of live recordings while managing room acoustics.": "Algoritmos DSP proprietários que preservam o 'sopro' de gravações ao vivo enquanto gerenciam a acústica do ambiente.",
    "pure class-a amplification with zero negative feedback, housed in a monolithic copper chassis.": "Amplificação Classe A pura sem retroalimentação negativa, alojada em um chassi monolítico de cobre.",
    "r2r ladder dac with femto-second clocking for the most natural digital-to-analog conversion.": "DAC de escada R2R com temporização em femtosegundos para a conversão digital-analógica mais natural.",
    "redefining the threshold of hearing. precision sonic instruments for the world's most discerning ears.": "Redefinindo o limiar da audição. Instrumentos sonoros de precisão para os ouvidos mais exigentes do mundo.",
    "request audition": "Solicitar audição",
    "schedule listening session": "Agendar sessão de escuta",
    "signal to noise ratio": "Relação Sinal-Ruído",
    "signal-to-noise": "Sinal-Ruído",
    "the absolute mastery of acoustic engineering. engineered for the evolutionary audiophile in our berlin sanctuary.": "O domínio absoluto da engenharia acústica. Concebido para o audiófilo exigente, na nossa oficina berlinense.",
    "the chronology": "A cronologia",
    "the craftsmen": "Os artesãos",
    "the maison": "A Maison",
    "we provide a 5-year comprehensive warranty on all chassis and circuitry, and a 1-year performance guarantee on all selected premium vacuum tubes.": "Oferecemos uma garantia abrangente de 5 anos em todos os chassi e circuitos, e uma garantia de desempenho de 1 ano em todos os tubos a vácuo premium selecionados.",
    "what is the lead time for aether one monitors?": "Qual é o prazo de fabrico?",
    "what is the warranty on vacuum-tube components?": "Qual é a garantia dos componentes de válvulas?",
  },
};
