/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "force of": "La force de la",
    "nature.": "nature.",
    "aero efficiency": "Efficacité aérodynamique",
    "thermal stability": "Stabilité thermique",
    "grand tourer": "Grand tourisme",
    "track focused": "Orientée circuit",
    "electric hypercar": "Hypercar électrique",
    "advanced": "Dynamique",
    "dynamics.": "avancée.",
    "optimal": "Optimal",
    "stable": "Stable",
    "torque vectoring": "Vectorisation du couple",
    "active": "Actif",
    "precise": "Précis",
    "g-force max": "Accélération latérale max.",
    "extreme": "Extrême",
    "carbon structure": "Structure carbone",
    "tailored": "Vitesse",
    "velocity.": "sur mesure.",
    "options": "Options",
    "artisans": "Artisans",
    "configure your unit": "Configurer votre appareil",
    "do you offer international delivery?": "Offrez-vous une livraison internationale ?",
    "is the stratos e road-legal?": "Le Stratos E est-il homologué pour la route ?",
    "the flying technician program": "Le programme des Techniciens Volants",
    "the stratos e is homologated for road use in the eu, uk, and usa. track-only variants are also available.": "Le Stratos E est homologué pour une utilisation sur route dans l'UE, au Royaume-Uni et aux États-Unis. Des variantes réservées à la piste sont également disponibles.",
    "top speed": "Vitesse maximale",
    "view registry": "Voir le registre",
    "what is the typical wait time for a bespoke unit?": "Quel est le délai d'attente typique pour une unité sur mesure ?",
    "yes. every owner is assigned a dedicated flying technician and global concierge who manages white-glove transport.": "Oui. Chaque propriétaire se voit attribuer un Technicien Volant dédié et un concierge mondial qui gère le transport avec service haut de gamme.",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "force of": "La fuerza de la",
    "nature.": "naturaleza.",
    "aero efficiency": "Eficiencia aerodinámica",
    "thermal stability": "Estabilidad térmica",
    "grand tourer": "Gran turismo",
    "track focused": "Orientada a circuito",
    "electric hypercar": "Hiperdeportivo eléctrico",
    "advanced": "Dinámica",
    "dynamics.": "avanzada.",
    "optimal": "Óptimo",
    "stable": "Estable",
    "torque vectoring": "Vectorización del par",
    "active": "Activo",
    "precise": "Preciso",
    "g-force max": "Aceleración lateral máx.",
    "extreme": "Extremo",
    "carbon structure": "Estructura de carbono",
    "tailored": "Velocidad",
    "velocity.": "a medida.",
    "options": "Opciones",
    "artisans": "Artesanos",
    "configure your unit": "Configure su equipo",
    "do you offer international delivery?": "¿Ofrecen entrega internacional?",
    "is the stratos e road-legal?": "¿Es legal en carretera el Stratos E?",
    "the flying technician program": "El Programa de Técnicos Voladores",
    "the stratos e is homologated for road use in the eu, uk, and usa. track-only variants are also available.": "El Stratos E está homologado para uso en carretera en la UE, el Reino Unido y los EE. UU. También hay variantes solo para pista disponibles.",
    "top speed": "Velocidad máxima",
    "view registry": "Ver registro",
    "what is the typical wait time for a bespoke unit?": "¿Cuál es el tiempo de espera típico para una unidad a medida?",
    "yes. every owner is assigned a dedicated flying technician and global concierge who manages white-glove transport.": "Sí. A cada propietario se le asigna un Técnico Volador dedicado y un conserje global que gestiona el transporte de lujo.",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "force of": "Die Kraft der",
    "nature.": "Natur.",
    "aero efficiency": "Aerodynamische Effizienz",
    "thermal stability": "Thermische Stabilität",
    "grand tourer": "Gran Turismo",
    "track focused": "Auf die Rennstrecke ausgelegt",
    "electric hypercar": "Elektro-Hypercar",
    "advanced": "Fortschrittliche",
    "dynamics.": "Dynamik.",
    "optimal": "Optimal",
    "stable": "Stabil",
    "torque vectoring": "Torque Vectoring",
    "active": "Aktiv",
    "precise": "Präzise",
    "g-force max": "Maximale Querbeschleunigung",
    "extreme": "Extrem",
    "carbon structure": "Karbonstruktur",
    "tailored": "Geschwindigkeit",
    "velocity.": "nach Maß.",
    "options": "Optionen",
    "artisans": "Handwerker",
    "configure your unit": "Gerät konfigurieren",
    "do you offer international delivery?": "Bieten Sie internationalen Versand an?",
    "is the stratos e road-legal?": "Ist der Stratos E straßenzulässig?",
    "the flying technician program": "Das Programm der fliegenden Techniker",
    "the stratos e is homologated for road use in the eu, uk, and usa. track-only variants are also available.": "Der Stratos E ist für den Straßenverkehr in der EU, im Vereinigten Königreich und in den USA homologiert. Es sind auch Varianten nur für die Rennstrecke erhältlich.",
    "top speed": "Höchstgeschwindigkeit",
    "view registry": "Registrierung anzeigen",
    "what is the typical wait time for a bespoke unit?": "Wie lange ist die typische Wartezeit für eine maßgeschneiderte Einheit?",
    "yes. every owner is assigned a dedicated flying technician and global concierge who manages white-glove transport.": "Ja. Jeder Eigentümer erhält einen dedizierten fliegenden Techniker und einen globalen Concierge, der den Transport mit weißem Handschuh verwaltet.",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "force of": "A força da",
    "nature.": "natureza.",
    "aero efficiency": "Eficiência aerodinâmica",
    "thermal stability": "Estabilidade térmica",
    "grand tourer": "Grande turismo",
    "track focused": "Orientada para circuito",
    "electric hypercar": "Hipercarro elétrico",
    "advanced": "Dinâmica",
    "dynamics.": "avançada.",
    "optimal": "Ótimo",
    "stable": "Estável",
    "torque vectoring": "Vetorização do binário",
    "active": "Ativo",
    "precise": "Preciso",
    "g-force max": "Aceleração lateral máx.",
    "extreme": "Extremo",
    "carbon structure": "Estrutura em carbono",
    "tailored": "Velocidade",
    "velocity.": "à medida.",
    "options": "Opções",
    "artisans": "Artesãos",
    "configure your unit": "Configurar o seu equipamento",
    "do you offer international delivery?": "Oferecem entrega internacional?",
    "is the stratos e road-legal?": "O Stratos E é legal na estrada?",
    "the flying technician program": "O Programa de Técnicos Voadores",
    "the stratos e is homologated for road use in the eu, uk, and usa. track-only variants are also available.": "O Stratos E está homologado para uso em estrada na UE, no Reino Unido e nos EUA. Também estão disponíveis variantes apenas para pista.",
    "top speed": "Velocidade máxima",
    "view registry": "Ver registo",
    "what is the typical wait time for a bespoke unit?": "Qual é o tempo de espera típico para uma unidade personalizada?",
    "yes. every owner is assigned a dedicated flying technician and global concierge who manages white-glove transport.": "Sim. A cada proprietário é atribuído um Técnico Voador dedicado e um concierge global que gere o transporte de luxo.",
  },
};
