/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "native typescript framework for zero-knowledge application development.": "Un cadre TypeScript natif pour développer des applications à divulgation nulle.",
    "high-performance validator infrastructure with automated failover.": "Une infrastructure de validateurs performante, avec bascule automatique en cas de panne.",
    "seamless indexed data across 40+ l1 and l2 networks via a single unified api.": "Des données indexées sur plus de 40 réseaux L1 et L2, à travers une seule API.",
    "join 42 000+ developers building the future of decentralized computation.": "Rejoignez plus de 42 000 développeurs qui construisent le calcul décentralisé de demain.",
    "architected for scale. every component of the blockbase stack is built to handle millions of transactions with sub-second latency.": "Conçu pour l'échelle. Chaque composant de la pile Blockbase est construit pour gérer des millions de transactions avec une latence inférieure à une seconde.",
    "data indexed and available via api in less than 200ms from block finality.": "Données indexées et disponibles via API en moins de 200 ms après la finalité du bloc.",
    "engineering the foundation of high-performance decentralized systems. built for the next billion users.": "Bâtir le socle des systèmes décentralisés à haute performance. Conçu pour le prochain milliard d'utilisateurs.",
    "explore the sdk": "Explorer le SDK",
    "get api key": "Obtenir la clé API",
    "integrated circuits for ultra-fast zero-knowledge proof generation and validation.": "Circuits intégrés pour la génération et la validation de preuves à connaissance nulle ultra-rapides.",
    "join 42,000+ developers building the future of decentralized computation.": "Rejoignez plus de 42 000 développeurs qui construisent l'avenir de la computation décentralisée.",
    "our infrastructure is audited by leading security firms and stress-tested under production loads exceeding 500k tps.": "Notre infrastructure est auditée par les meilleurs cabinets de sécurité et éprouvée sous des charges de production dépassant 500 000 transactions par seconde.",
    "ready to": "Prêt à",
    "real-time": "Temps Réel",
    "trail of bits": "TRAIL OF BITS",
    "tx processed: 4.2b": "TX TRAITÉ : 4,2B",
    "ultra-low latency indexing engine for real-time blockchain telemetry.": "Moteur d'indexation à latence minimale pour la télémétrie en temps réel.",
    "view documentation": "Voir la documentation",
  },
  es: {
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "native typescript framework for zero-knowledge application development.": "Un marco TypeScript nativo para desarrollar aplicaciones de conocimiento cero.",
    "high-performance validator infrastructure with automated failover.": "Una infraestructura de validadores de alto rendimiento, con conmutación automática ante fallos.",
    "seamless indexed data across 40+ l1 and l2 networks via a single unified api.": "Datos indexados en más de 40 redes L1 y L2, a través de una sola API.",
    "join 42 000+ developers building the future of decentralized computation.": "Únase a más de 42 000 desarrolladores que construyen la computación descentralizada del mañana.",
    "architected for scale. every component of the blockbase stack is built to handle millions of transactions with sub-second latency.": "Arquitectado para escalar. Cada componente de la pila Blockbase está diseñado para manejar millones de transacciones con una latencia de menos de un segundo.",
    "data indexed and available via api in less than 200ms from block finality.": "Datos indexados y disponibles a través de API en menos de 200 ms desde la finalización del bloque.",
    "engineering the foundation of high-performance decentralized systems. built for the next billion users.": "Construir la base de los sistemas descentralizados de alto rendimiento. Pensado para los próximos mil millones de usuarios.",
    "explore the sdk": "Explorar el SDK",
    "get api key": "Obtener la clave API",
    "integrated circuits for ultra-fast zero-knowledge proof generation and validation.": "Circuitos integrados para la generación y validación de pruebas de conocimiento cero ultrarrápidas.",
    "join 42,000+ developers building the future of decentralized computation.": "Únete a más de 42,000 desarrolladores que están construyendo el futuro de la computación descentralizada.",
    "our infrastructure is audited by leading security firms and stress-tested under production loads exceeding 500k tps.": "Nuestra infraestructura la auditan las mejores firmas de seguridad y se somete a cargas de producción superiores a 500 000 transacciones por segundo.",
    "ready to": "Listo para",
    "real-time": "Tiempo Real",
    "trail of bits": "TRAIL OF BITS",
    "tx processed: 4.2b": "TX PROCESADO: 4,2B",
    "ultra-low latency indexing engine for real-time blockchain telemetry.": "Motor de indexación de latencia mínima para la telemetría en tiempo real.",
    "view documentation": "Ver documentación",
  },
  de: {
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "native typescript framework for zero-knowledge application development.": "Ein natives TypeScript-Framework für Zero-Knowledge-Anwendungen.",
    "high-performance validator infrastructure with automated failover.": "Eine leistungsstarke Validator-Infrastruktur mit automatischem Failover.",
    "seamless indexed data across 40+ l1 and l2 networks via a single unified api.": "Indizierte Daten über mehr als 40 L1- und L2-Netze, über eine einzige API.",
    "join 42 000+ developers building the future of decentralized computation.": "Schließen Sie sich über 42 000 Entwicklern an, die das dezentrale Rechnen von morgen bauen.",
    "architected for scale. every component of the blockbase stack is built to handle millions of transactions with sub-second latency.": "Für Skalierung entworfen. Jedes Element des Blockbase-Stacks ist so konzipiert, dass es Millionen von Transaktionen mit einer Latenz von weniger als einer Sekunde verarbeiten kann.",
    "data indexed and available via api in less than 200ms from block finality.": "Daten indexiert und über API in weniger als 200 ms nach Blockfinalität verfügbar.",
    "engineering the foundation of high-performance decentralized systems. built for the next billion users.": "Das Fundament leistungsstarker dezentraler Systeme bauen. Gemacht für die nächste Milliarde Nutzer.",
    "explore the sdk": "SDK erkunden",
    "get api key": "API-Schlüssel erhalten",
    "integrated circuits for ultra-fast zero-knowledge proof generation and validation.": "Integrierte Schaltungen zur ultra-schnellen Generierung und Validierung von Zero-Knowledge-Beweisen.",
    "join 42,000+ developers building the future of decentralized computation.": "Schließen Sie sich über 42.000 Entwicklern an, die die Zukunft der dezentralen Berechnung gestalten.",
    "our infrastructure is audited by leading security firms and stress-tested under production loads exceeding 500k tps.": "Unsere Infrastruktur wird von führenden Sicherheitsfirmen geprüft und unter Produktionslasten von über 500 000 Transaktionen pro Sekunde getestet.",
    "ready to": "Bereit zu",
    "real-time": "Echtzeit",
    "trail of bits": "TRAIL OF BITS",
    "tx processed: 4.2b": "TX VERARBEITET: 4,2B",
    "ultra-low latency indexing engine for real-time blockchain telemetry.": "Indexierungsmaschine mit minimaler Latenz für Telemetrie in Echtzeit.",
    "view documentation": "Dokumentation anzeigen",
  },
  pt: {
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "native typescript framework for zero-knowledge application development.": "Uma estrutura TypeScript nativa para desenvolver aplicações de conhecimento zero.",
    "high-performance validator infrastructure with automated failover.": "Uma infraestrutura de validadores de alto desempenho, com comutação automática em caso de falha.",
    "seamless indexed data across 40+ l1 and l2 networks via a single unified api.": "Dados indexados em mais de 40 redes L1 e L2, através de uma só API.",
    "join 42 000+ developers building the future of decentralized computation.": "Junte-se a mais de 42 000 programadores que constroem a computação descentralizada de amanhã.",
    "architected for scale. every component of the blockbase stack is built to handle millions of transactions with sub-second latency.": "Arquitetado para escalar. Cada componente da pilha Blockbase é construído para lidar com milhões de transações com latência de menos de um segundo.",
    "data indexed and available via api in less than 200ms from block finality.": "Dados indexados e disponíveis via API em menos de 200 ms após a finalização do bloco.",
    "engineering the foundation of high-performance decentralized systems. built for the next billion users.": "Construir a base dos sistemas descentralizados de alto desempenho. Pensado para os próximos mil milhões de utilizadores.",
    "explore the sdk": "Explorar o SDK",
    "get api key": "Obter a chave API",
    "integrated circuits for ultra-fast zero-knowledge proof generation and validation.": "Circuitos integrados para geração e validação de provas de conhecimento zero ultra-rápidas.",
    "join 42,000+ developers building the future of decentralized computation.": "Junte-se a mais de 42.000 desenvolvedores que estão construindo o futuro da computação descentralizada.",
    "our infrastructure is audited by leading security firms and stress-tested under production loads exceeding 500k tps.": "A nossa infraestrutura é auditada pelas melhores firmas de segurança e testada sob cargas de produção superiores a 500 000 transações por segundo.",
    "ready to": "Pronto para",
    "real-time": "Tempo Real",
    "trail of bits": "TRAIL OF BITS",
    "tx processed: 4.2b": "TX PROCESSADO: 4,2B",
    "ultra-low latency indexing engine for real-time blockchain telemetry.": "Motor de indexação de latência mínima para a telemetria em tempo real.",
    "view documentation": "Ver documentação",
  },
};
