/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"conflict is inevitable. neutralization is an choice. we are the choice of the prepared.\"": "« Le conflit est inévitable. La neutralisation est un choix. Nous sommes le choix de ceux qui se préparent. »",
    "// core team": "// équipe de base",
    "38 gb staged over nine weeks through a sanctioned file-sharing tool. behavioural baseline caught the schedule, not the volume.": "Trente-huit gigaoctets préparés sur neuf semaines, par un outil de partage autorisé. C'est la régularité, non le volume, que la référence comportementale a repérée.",
    "combolists, stealer logs and paste sites, matched against your domains. median time from appearance to your inbox: four hours.": "Listes de comptes, journaux de voleurs de données et sites de collage, recoupés avec vos domaines. Délai médian entre l'apparition et votre boîte : quatre heures.",
    "engagements are summarised with the client's written consent. sectors, figures and dates are generalised wherever disclosure would identify the party.": "Les missions sont résumées avec l'accord écrit du client. Secteurs, chiffres et dates sont généralisés partout où la précision identifierait la partie.",
    "every asset you own, and the ones you forgot: expired subdomains, orphaned s3 buckets, staging hosts still answering on port 443.": "Tout ce que vous possédez, et ce que vous avez oublié : sous-domaines expirés, espaces de stockage orphelins, serveurs de recette qui répondent encore sur le port 443.",
    "lateral path missed for two years": "Un chemin latéral resté invisible deux ans",
    "our proprietary monitoring grid ensures that no movement goes unnoticed. we operate 24/7/365 across all time zones to ensure perpetual readiness.": "Notre grille de surveillance propriétaire garantit qu'aucun mouvement ne passe inaperçu. Nous opérons 24/7/365 dans tous les fuseaux horaires pour assurer une préparation perpétuelle.",
    "our red team couldn't find a single gap after deployment. the threat graph identified a lateral movement path we had missed for two years. mission critical.": "Notre équipe rouge n'a trouvé aucune faille après le déploiement. Le graphique des menaces a identifié un chemin de mouvement latéral que nous avions manqué pendant deux ans. Critique pour la mission.",
    "recovery from immutable backups in 61 hours. the full timeline, published with the client's consent.": "Restauration depuis des sauvegardes immuables en soixante et une heures. La chronologie complète, publiée avec l'accord du client.",
    "request private audit": "Demander un audit privé",
    "request strategy brief": "Demander un bref stratégique",
    "secure": "Sécurisé",
    "secure portal": "Portail Sécurisé",
    "six ransomware attempts blocked in 90 days. zero successful intrusions. the ai intercepts attacks before our soc analysts even see the alert.": "Six tentatives de ransomware bloquées en 90 jours. Zéro intrusion réussie. L'IA intercepte les attaques avant même que nos analystes SOC ne voient l'alerte.",
    "the risk.": "Le risque.",
    "watch.": "Regarder.",
    "we follow twenty-two groups by tooling and tradecraft, not by press release. when one changes loader, our clients hear about it that week.": "Nous suivons vingt-deux groupes à leurs outils et à leurs méthodes, pas aux communiqués. Quand l'un change de chargeur, nos clients l'apprennent dans la semaine.",
    "your legacy.": "Votre héritage.",
    "your vendors' breaches become yours. we monitor the ones that hold your data, and we tell you before their disclosure does.": "Les fuites de vos prestataires deviennent les vôtres. Nous surveillons ceux qui détiennent vos données, et nous vous prévenons avant leur communiqué.",
  },
  es: {
    "\"conflict is inevitable. neutralization is an choice. we are the choice of the prepared.\"": "«El conflicto es inevitable. La neutralización es una elección. Somos la elección de quienes se preparan.»",
    "// core team": "// equipo central",
    "38 gb staged over nine weeks through a sanctioned file-sharing tool. behavioural baseline caught the schedule, not the volume.": "Treinta y ocho gigabytes preparados en nueve semanas, mediante una herramienta de compartición autorizada. Fue la regularidad, no el volumen, lo que detectó la línea base de comportamiento.",
    "combolists, stealer logs and paste sites, matched against your domains. median time from appearance to your inbox: four hours.": "Listas de credenciales, registros de ladrones de datos y sitios de pegado, cotejados con sus dominios. Tiempo mediano entre la aparición y su bandeja: cuatro horas.",
    "engagements are summarised with the client's written consent. sectors, figures and dates are generalised wherever disclosure would identify the party.": "Las misiones se resumen con el consentimiento escrito del cliente. Sectores, cifras y fechas se generalizan allí donde la precisión identificaría a la parte.",
    "every asset you own, and the ones you forgot: expired subdomains, orphaned s3 buckets, staging hosts still answering on port 443.": "Todo lo que posee, y lo que ha olvidado: subdominios caducados, cubos de almacenamiento huérfanos, servidores de pruebas que aún responden en el puerto 443.",
    "lateral path missed for two years": "Un camino lateral invisible durante dos años",
    "our proprietary monitoring grid ensures that no movement goes unnoticed. we operate 24/7/365 across all time zones to ensure perpetual readiness.": "Nuestra cuadrícula de monitoreo patentada asegura que ningún movimiento pase desapercibido. Operamos 24/7/365 en todos los husos horarios para garantizar una preparación perpetua.",
    "our red team couldn't find a single gap after deployment. the threat graph identified a lateral movement path we had missed for two years. mission critical.": "Nuestro equipo rojo no pudo encontrar una sola brecha después del despliegue. El gráfico de amenazas identificó un camino de movimiento lateral que habíamos pasado por alto durante dos años. Crítico para la misión.",
    "recovery from immutable backups in 61 hours. the full timeline, published with the client's consent.": "Restauración desde copias inmutables en sesenta y una horas. La cronología completa, publicada con el consentimiento del cliente.",
    "request private audit": "Solicitar una auditoría privada",
    "request strategy brief": "Solicitar un informe estratégico",
    "secure": "Seguro",
    "secure portal": "Portal Seguro",
    "six ransomware attempts blocked in 90 days. zero successful intrusions. the ai intercepts attacks before our soc analysts even see the alert.": "Seis intentos de ransomware bloqueados en 90 días. Cero intrusiones exitosas. La IA intercepta ataques antes de que nuestros analistas de SOC vean la alerta.",
    "the risk.": "El riesgo.",
    "watch.": "Ver.",
    "we follow twenty-two groups by tooling and tradecraft, not by press release. when one changes loader, our clients hear about it that week.": "Seguimos a veintidós grupos por sus herramientas y métodos, no por los comunicados. Cuando uno cambia de cargador, nuestros clientes lo saben esa semana.",
    "your legacy.": "Su legado.",
    "your vendors' breaches become yours. we monitor the ones that hold your data, and we tell you before their disclosure does.": "Las filtraciones de sus proveedores se vuelven suyas. Vigilamos a los que guardan sus datos y le avisamos antes que su comunicado.",
  },
  de: {
    "\"conflict is inevitable. neutralization is an choice. we are the choice of the prepared.\"": "„Konflikt ist unvermeidlich. Neutralisierung ist eine Wahl. Wir sind die Wahl der Vorbereiteten.“",
    "// core team": "// Kernteam",
    "38 gb staged over nine weeks through a sanctioned file-sharing tool. behavioural baseline caught the schedule, not the volume.": "Achtunddreißig Gigabyte über neun Wochen vorbereitet, über ein freigegebenes Freigabewerkzeug. Erkannt wurde der Rhythmus, nicht das Volumen.",
    "combolists, stealer logs and paste sites, matched against your domains. median time from appearance to your inbox: four hours.": "Zugangslisten, Stealer-Logs und Paste-Seiten, abgeglichen mit Ihren Domains. Mittlere Zeit vom Auftauchen bis in Ihr Postfach: vier Stunden.",
    "engagements are summarised with the client's written consent. sectors, figures and dates are generalised wherever disclosure would identify the party.": "Mandate werden mit schriftlicher Zustimmung des Kunden zusammengefasst. Branchen, Zahlen und Daten werden verallgemeinert, wo die Angabe die Partei erkennbar machen würde.",
    "every asset you own, and the ones you forgot: expired subdomains, orphaned s3 buckets, staging hosts still answering on port 443.": "Alles, was Ihnen gehört, und was Sie vergessen haben: abgelaufene Subdomains, verwaiste Speicher-Buckets, Staging-Server, die noch auf Port 443 antworten.",
    "lateral path missed for two years": "Ein seitlicher Pfad, zwei Jahre lang übersehen",
    "our proprietary monitoring grid ensures that no movement goes unnoticed. we operate 24/7/365 across all time zones to ensure perpetual readiness.": "Unser proprietäres Überwachungsnetz sorgt dafür, dass keine Bewegung unbemerkt bleibt. Wir sind 24/7/365 in allen Zeitzonen im Einsatz, um ständige Bereitschaft zu gewährleisten.",
    "our red team couldn't find a single gap after deployment. the threat graph identified a lateral movement path we had missed for two years. mission critical.": "Unser rotes Team konnte nach dem Einsatz keine einzige Lücke finden. Das Bedrohungsdiagramm identifizierte einen lateralen Bewegungsweg, den wir zwei Jahre lang übersehen hatten. Kritisch für die Mission.",
    "recovery from immutable backups in 61 hours. the full timeline, published with the client's consent.": "Wiederherstellung aus unveränderlichen Sicherungen in einundsechzig Stunden. Der vollständige Ablauf, veröffentlicht mit Zustimmung des Kunden.",
    "request private audit": "Private Prüfung anfordern",
    "request strategy brief": "Strategie-Brief anfordern",
    "secure": "Sicher",
    "secure portal": "Sicheres Portal",
    "six ransomware attempts blocked in 90 days. zero successful intrusions. the ai intercepts attacks before our soc analysts even see the alert.": "Sechs Ransomware-Versuche in 90 Tagen blockiert. Null erfolgreiche Eindringlinge. Die KI unterbricht Angriffe, bevor unsere SOC-Analysten die Warnung überhaupt sehen.",
    "the risk.": "Das Risiko.",
    "watch.": "Beobachten.",
    "we follow twenty-two groups by tooling and tradecraft, not by press release. when one changes loader, our clients hear about it that week.": "Wir verfolgen zweiundzwanzig Gruppen anhand ihrer Werkzeuge und Vorgehensweisen, nicht anhand von Pressemitteilungen. Wechselt eine den Loader, erfahren es unsere Kunden noch in derselben Woche.",
    "your legacy.": "Ihr Erbe.",
    "your vendors' breaches become yours. we monitor the ones that hold your data, and we tell you before their disclosure does.": "Die Lecks Ihrer Dienstleister werden zu Ihren. Wir überwachen jene, die Ihre Daten halten, und melden es Ihnen vor deren Mitteilung.",
  },
  pt: {
    "\"conflict is inevitable. neutralization is an choice. we are the choice of the prepared.\"": "«O conflito é inevitável. A neutralização é uma escolha. Somos a escolha de quem se prepara.»",
    "// core team": "// equipa central",
    "38 gb staged over nine weeks through a sanctioned file-sharing tool. behavioural baseline caught the schedule, not the volume.": "Trinta e oito gigabytes preparados ao longo de nove semanas, através de uma ferramenta de partilha autorizada. Foi a regularidade, não o volume, que a linha de base comportamental detetou.",
    "combolists, stealer logs and paste sites, matched against your domains. median time from appearance to your inbox: four hours.": "Listas de credenciais, registos de ladrões de dados e sites de colagem, cruzados com os seus domínios. Tempo mediano entre o aparecimento e a sua caixa: quatro horas.",
    "engagements are summarised with the client's written consent. sectors, figures and dates are generalised wherever disclosure would identify the party.": "As missões são resumidas com o consentimento escrito do cliente. Setores, números e datas são generalizados sempre que a precisão identificaria a parte.",
    "every asset you own, and the ones you forgot: expired subdomains, orphaned s3 buckets, staging hosts still answering on port 443.": "Tudo o que possui, e o que esqueceu: subdomínios expirados, espaços de armazenamento órfãos, servidores de testes que ainda respondem na porta 443.",
    "lateral path missed for two years": "Um caminho lateral invisível durante dois anos",
    "our proprietary monitoring grid ensures that no movement goes unnoticed. we operate 24/7/365 across all time zones to ensure perpetual readiness.": "A nossa grade de monitorização proprietária garante que nenhum movimento passe despercebido. Operamos 24/7/365 em todos os fusos horários para garantir uma prontidão perpétua.",
    "our red team couldn't find a single gap after deployment. the threat graph identified a lateral movement path we had missed for two years. mission critical.": "A nossa equipa vermelha não conseguiu encontrar uma única falha após a implementação. O gráfico de ameaças identificou um caminho de movimento lateral que tínhamos perdido durante dois anos. Crítico para a missão.",
    "recovery from immutable backups in 61 hours. the full timeline, published with the client's consent.": "Restauro a partir de cópias imutáveis em sessenta e uma horas. A cronologia completa, publicada com o consentimento do cliente.",
    "request private audit": "Solicitar uma auditoria privada",
    "request strategy brief": "Solicitar um resumo estratégico",
    "secure": "Seguro",
    "secure portal": "Portal Seguro",
    "six ransomware attempts blocked in 90 days. zero successful intrusions. the ai intercepts attacks before our soc analysts even see the alert.": "Seis tentativas de ransomware bloqueadas em 90 dias. Zero intrusões bem-sucedidas. A IA intercepta ataques antes que os nossos analistas de SOC vejam o alerta.",
    "the risk.": "O risco.",
    "watch.": "Assistir.",
    "we follow twenty-two groups by tooling and tradecraft, not by press release. when one changes loader, our clients hear about it that week.": "Seguimos vinte e dois grupos pelas suas ferramentas e métodos, não pelos comunicados. Quando um muda de carregador, os nossos clientes sabem-no nessa semana.",
    "your legacy.": "O seu legado.",
    "your vendors' breaches become yours. we monitor the ones that hold your data, and we tell you before their disclosure does.": "As fugas dos seus fornecedores tornam-se suas. Vigiamos os que guardam os seus dados e avisamo-lo antes do comunicado deles.",
  },
};
