/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "14 days free →": "14 jours gratuits →",
    "14 days free on all plans. no credit card required.": "14 jours gratuits sur tous les plans. Aucune carte de crédit requise.",
    "14 days free on the growth plan, no credit card required. data is deleted at the end if you don't convert.": "14 jours gratuits sur le plan Croissance, aucune carte de crédit requise. Les données sont supprimées à la fin si vous ne convertissez pas.",
    "14 days free. no credit card. results from day one.": "14 jours gratuits. Pas de carte de crédit. Résultats dès le premier jour.",
    "200+ native integrations. rest sdk for the rest.": "Plus de deux cents intégrations natives. Une trousse REST pour le reste.",
    "a 15-minute connection wizard for standard integrations. for complex setups, a solutions engineer accompanies you (included in enterprise).": "Un assistant de connexion de 15 minutes pour les intégrations standard. Pour les configurations complexes, un ingénieur solutions vous accompagne (inclus dans l'Enterprise).",
    "analytics, alerts, reports. all-in-one. no compromises.": "Analytique, alertes, rapports. Tout-en-un. Pas de compromis.",
    "b2b scale-up, 110 people": "Entreprise en croissance, 110 personnes",
    "cohorts, funnels, retention analysis, heatmaps. deep behavioral analytics without writing a single line of code.": "Cohortes, entonnoirs, analyse de la rétention, cartes de chaleur. Analyse comportementale approfondie sans écrire une seule ligne de code.",
    "configurable threshold alerts with anomaly detection. slack, email, and webhook delivery. get warned before the incident.": "Des alertes à seuil réglable, avec détection d'anomalie. Par messagerie, courriel ou webhook. Être prévenu avant l'incident.",
    "connect everything you use.": "Reliez tout ce que vous utilisez.",
    "data refreshed every 5 seconds. 40+ visualization types. drag-and-drop widget builder — no sql required.": "Données actualisées toutes les 5 secondes. Plus de 40 types de visualisation. Constructeur de widgets par glisser-déposer — aucune SQL requise.",
    "do you offer a free trial?": "Offrez-vous un essai gratuit ?",
    "everything your team needs.": "Tout ce dont votre équipe a besoin.",
    "free trial": "Essai gratuit",
    "growth": "Croissance",
    "head of growth": "Responsable de la croissance",
    "how does onboarding work?": "Comment fonctionne l'intégration ?",
    "identify where users drop off and fix the leaks.": "Repérez où les visiteurs décrochent, et colmatez.",
    "is there a public api?": "Y a-t-il une API publique ?",
    "is your data stored in europe?": "Vos données sont-elles stockées en Europe ?",
    "know exactly which channels drive real revenue.": "Sachez précisément quels canaux rapportent vraiment.",
    "metric turns raw data into actionable insights. dashboards, alerts, and automated reports — all in one platform built for serious teams.": "Metric transforme les données brutes en informations exploitables. Tableaux de bord, alertes et rapports automatisés — le tout sur une seule plateforme conçue pour des équipes sérieuses.",
    "metric's ai alerts detected a tracking bug 48 hours before we noticed it. that alone saved us 2 weeks of clean data we would have lost forever.": "Les alertes IA de Metric ont détecté un bug de suivi 48 heures avant que nous ne le remarquions. Cela nous a permis d'économiser 2 semaines de données propres que nous aurions perdues pour toujours.",
    "native connectors for ga4, stripe, hubspot, salesforce, postgres, bigquery. rest sdk for everything else.": "Connecteurs natifs pour GA4, Stripe, HubSpot, Salesforce, Postgres, BigQuery. SDK REST pour tout le reste.",
    "new users": "Nouveaux utilisateurs",
    "real-time analytics for data-driven teams. make better decisions, faster.": "L'analyse en temps réel pour les équipes qui décident sur des données. Mieux décider, plus vite.",
    "real-time dashboards": "Tableaux de bord en temps réel",
    "revenue attribution": "Attribution des revenus",
    "simple, predictable pricing.": "Tarification simple et prévisible.",
    "start for free →": "Commencer gratuitement →",
    "team access & roles": "Accès et rôles d'équipe",
    "teams who chose metric.": "Équipes qui ont choisi Metric.",
    "the stripe → metric integration gave me real-time mrr and churn visibility i'd been trying to build for 6 months. setup took 12 minutes.": "L'intégration Stripe → Metric m'a donné une visibilité en temps réel sur le MRR et le churn que j'essayais de construire depuis 6 mois. La configuration a pris 12 minutes.",
    "track how different segments perform over time.": "Suivez le comportement de chaque segment dans le temps.",
    "view demo": "Voir la démo",
    "vs last 30 days": "vs les 30 derniers jours",
    "we replaced 4 tools with metric. fewer reporting meetings, more decisions based on real data. our whole ops team lives in this dashboard now.": "Nous avons remplacé 4 outils par Metric. Moins de réunions de reporting, plus de décisions basées sur des données réelles. Toute notre équipe opérationnelle vit maintenant dans ce tableau de bord.",
    "weekly and monthly delivery in pdf or html. white-label ready. multi-recipient without requiring accounts.": "Livraison hebdomadaire et mensuelle en PDF ou HTML. Prêt à être en marque blanche. Multi-destinataire sans nécessiter de comptes.",
    "yes — csv import, direct bigquery/redshift connection, or via our rest api. configurable retention up to 2 years.": "Oui — importation CSV, connexion directe BigQuery/Redshift, ou via notre API REST. Rétention configurable jusqu'à 2 ans.",
    "yes — full rest api documented at docs.metric.io. webhooks, javascript and python sdks available.": "Oui — API REST complète documentée sur docs.metric.io. Webhooks, SDKs JavaScript et Python disponibles.",
    "your data is waiting for you.": "Vos données vous attendent.",
  },
  es: {
    "14 days free →": "14 días gratis →",
    "14 days free on all plans. no credit card required.": "14 días gratis en todos los planes. No se requiere tarjeta de crédito.",
    "14 days free on the growth plan, no credit card required. data is deleted at the end if you don't convert.": "14 días gratis en el plan de Crecimiento, no se requiere tarjeta de crédito. Los datos se eliminan al final si no conviertes.",
    "14 days free. no credit card. results from day one.": "14 días gratis. Sin tarjeta de crédito. Resultados desde el primer día.",
    "200+ native integrations. rest sdk for the rest.": "Más de doscientas integraciones nativas. Un kit REST para lo demás.",
    "a 15-minute connection wizard for standard integrations. for complex setups, a solutions engineer accompanies you (included in enterprise).": "Un asistente de conexión de 15 minutos para integraciones estándar. Para configuraciones complejas, un ingeniero de soluciones te acompaña (incluido en Enterprise).",
    "analytics, alerts, reports. all-in-one. no compromises.": "Analítica, alertas, informes. Todo en uno. Sin compromisos.",
    "b2b scale-up, 110 people": "Empresa en crecimiento, 110 personas",
    "cohorts, funnels, retention analysis, heatmaps. deep behavioral analytics without writing a single line of code.": "Cohortes, embudos, análisis de retención, mapas de calor. Análisis de comportamiento profundo sin escribir una sola línea de código.",
    "configurable threshold alerts with anomaly detection. slack, email, and webhook delivery. get warned before the incident.": "Alertas de umbral configurable, con detección de anomalías. Por mensajería, correo o webhook. Avisado antes del incidente.",
    "connect everything you use.": "Conecte todo lo que usa.",
    "data refreshed every 5 seconds. 40+ visualization types. drag-and-drop widget builder — no sql required.": "Datos actualizados cada 5 segundos. Más de 40 tipos de visualización. Constructor de widgets por arrastrar y soltar — sin necesidad de SQL.",
    "do you offer a free trial?": "¿Ofrecen una prueba gratuita?",
    "everything your team needs.": "Todo lo que su equipo necesita.",
    "free trial": "Prueba gratuita",
    "growth": "Crecimiento",
    "head of growth": "Jefe de Crecimiento",
    "how does onboarding work?": "¿Cómo funciona la incorporación?",
    "identify where users drop off and fix the leaks.": "Detecte dónde abandonan los visitantes y tape las fugas.",
    "is there a public api?": "¿Hay una API pública?",
    "is your data stored in europe?": "¿Está almacenada su data en Europa?",
    "know exactly which channels drive real revenue.": "Sepa con precisión qué canales generan ingresos de verdad.",
    "metric turns raw data into actionable insights. dashboards, alerts, and automated reports — all in one platform built for serious teams.": "Metric convierte los datos en bruto en información procesable. Tableros, alertas e informes automatizados: todo en una sola plataforma diseñada para equipos serios.",
    "metric's ai alerts detected a tracking bug 48 hours before we noticed it. that alone saved us 2 weeks of clean data we would have lost forever.": "Las alertas de IA de Metric detectaron un error de seguimiento 48 horas antes de que lo notáramos. Eso solo nos ahorró 2 semanas de datos limpios que habríamos perdido para siempre.",
    "native connectors for ga4, stripe, hubspot, salesforce, postgres, bigquery. rest sdk for everything else.": "Conectores nativos para GA4, Stripe, HubSpot, Salesforce, Postgres, BigQuery. SDK REST para todo lo demás.",
    "new users": "Nuevos usuarios",
    "real-time analytics for data-driven teams. make better decisions, faster.": "El análisis en tiempo real para equipos que deciden con datos. Decidir mejor, más rápido.",
    "real-time dashboards": "Paneles en tiempo real",
    "revenue attribution": "Atribución de ingresos",
    "simple, predictable pricing.": "Precios simples y predecibles.",
    "start for free →": "Empezar gratis →",
    "team access & roles": "Acceso y roles del equipo",
    "teams who chose metric.": "Equipos que eligieron Metric.",
    "the stripe → metric integration gave me real-time mrr and churn visibility i'd been trying to build for 6 months. setup took 12 minutes.": "La integración de Stripe → Metric me dio visibilidad en tiempo real del MRR y la tasa de cancelación que había estado tratando de construir durante 6 meses. La configuración tomó 12 minutos.",
    "track how different segments perform over time.": "Siga el comportamiento de cada segmento en el tiempo.",
    "view demo": "Ver demo",
    "vs last 30 days": "vs los últimos 30 días",
    "we replaced 4 tools with metric. fewer reporting meetings, more decisions based on real data. our whole ops team lives in this dashboard now.": "Reemplazamos 4 herramientas por Metric. Menos reuniones de informes, más decisiones basadas en datos reales. Todo nuestro equipo de operaciones vive ahora en este panel.",
    "weekly and monthly delivery in pdf or html. white-label ready. multi-recipient without requiring accounts.": "Entrega semanal y mensual en PDF o HTML. Listo para marca blanca. Múltiples destinatarios sin necesidad de cuentas.",
    "yes — csv import, direct bigquery/redshift connection, or via our rest api. configurable retention up to 2 years.": "Sí — importación CSV, conexión directa a BigQuery/Redshift, o a través de nuestra API REST. Retención configurable de hasta 2 años.",
    "yes — full rest api documented at docs.metric.io. webhooks, javascript and python sdks available.": "Sí — API REST completa documentada en docs.metric.io. Webhooks, SDKs de JavaScript y Python disponibles.",
    "your data is waiting for you.": "Sus datos le esperan.",
  },
  de: {
    "14 days free →": "14 Tage kostenlos →",
    "14 days free on all plans. no credit card required.": "14 Tage kostenlos in allen Tarifen. Keine Kreditkarte erforderlich.",
    "14 days free on the growth plan, no credit card required. data is deleted at the end if you don't convert.": "14 Tage kostenlos im Wachstumsplan, keine Kreditkarte erforderlich. Daten werden am Ende gelöscht, wenn Sie nicht konvertieren.",
    "14 days free. no credit card. results from day one.": "14 Tage kostenlos. Keine Kreditkarte. Ergebnisse ab dem ersten Tag.",
    "200+ native integrations. rest sdk for the rest.": "Über zweihundert native Integrationen. Ein REST-SDK für den Rest.",
    "a 15-minute connection wizard for standard integrations. for complex setups, a solutions engineer accompanies you (included in enterprise).": "Ein 15-minütiger Verbindungsassistent für Standardintegrationen. Bei komplexen Setups begleitet Sie ein Solutions Engineer (in Enterprise enthalten).",
    "analytics, alerts, reports. all-in-one. no compromises.": "Analytik, Warnungen, Berichte. Alles in einem. Keine Kompromisse.",
    "b2b scale-up, 110 people": "Wachstumsunternehmen, 110 Personen",
    "cohorts, funnels, retention analysis, heatmaps. deep behavioral analytics without writing a single line of code.": "Kohorten, Trichter, Retentionsanalyse, Heatmaps. Tiefe Verhaltensanalysen ohne eine einzige Zeile Code zu schreiben.",
    "configurable threshold alerts with anomaly detection. slack, email, and webhook delivery. get warned before the incident.": "Konfigurierbare Schwellenwertalarme mit Anomalieerkennung. Per Chat, E-Mail oder Webhook. Gewarnt, bevor es passiert.",
    "connect everything you use.": "Verbinden Sie alles, was Sie nutzen.",
    "data refreshed every 5 seconds. 40+ visualization types. drag-and-drop widget builder — no sql required.": "Daten alle 5 Sekunden aktualisiert. Über 40 Visualisierungstypen. Drag-and-Drop-Widget-Builder — keine SQL erforderlich.",
    "do you offer a free trial?": "Bieten Sie eine kostenlose Testversion an?",
    "everything your team needs.": "Alles, was Ihr Team braucht.",
    "free trial": "Kostenlose Testversion",
    "growth": "Wachstum",
    "head of growth": "Leiter des Wachstums",
    "how does onboarding work?": "Wie funktioniert das Onboarding?",
    "identify where users drop off and fix the leaks.": "Erkennen Sie, wo Nutzer abspringen, und schließen Sie die Lücken.",
    "is there a public api?": "Gibt es eine öffentliche API?",
    "is your data stored in europe?": "Sind Ihre Daten in Europa gespeichert?",
    "know exactly which channels drive real revenue.": "Wissen Sie genau, welche Kanäle wirklich Umsatz bringen.",
    "metric turns raw data into actionable insights. dashboards, alerts, and automated reports — all in one platform built for serious teams.": "Metric verwandelt Rohdaten in umsetzbare Erkenntnisse. Dashboards, Warnmeldungen und automatisierte Berichte – alles auf einer Plattform, die für ernsthafte Teams entwickelt wurde.",
    "metric's ai alerts detected a tracking bug 48 hours before we noticed it. that alone saved us 2 weeks of clean data we would have lost forever.": "Die KI-Alerts von Metric haben einen Tracking-Fehler 48 Stunden erkannt, bevor wir ihn bemerkt haben. Das allein hat uns 2 Wochen saubere Daten gespart, die wir für immer verloren hätten.",
    "native connectors for ga4, stripe, hubspot, salesforce, postgres, bigquery. rest sdk for everything else.": "Native Connector für GA4, Stripe, HubSpot, Salesforce, Postgres, BigQuery. REST SDK für alles andere.",
    "new users": "Neue Benutzer",
    "real-time analytics for data-driven teams. make better decisions, faster.": "Echtzeit-Analyse für datengetriebene Teams. Besser entscheiden, schneller.",
    "real-time dashboards": "Echtzeit-Dashboards",
    "revenue attribution": "Umsatzzuordnung",
    "simple, predictable pricing.": "Einfache, vorhersehbare Preise.",
    "start for free →": "Kostenlos starten →",
    "team access & roles": "Teamzugang & Rollen",
    "teams who chose metric.": "Teams, die sich für Metric entschieden haben.",
    "the stripe → metric integration gave me real-time mrr and churn visibility i'd been trying to build for 6 months. setup took 12 minutes.": "Die Stripe → Metric-Integration gab mir Echtzeit-Transparenz über MRR und Churn, die ich seit 6 Monaten zu erstellen versuchte. Die Einrichtung dauerte 12 Minuten.",
    "track how different segments perform over time.": "Verfolgen Sie, wie sich einzelne Segmente über die Zeit entwickeln.",
    "view demo": "Demo ansehen",
    "vs last 30 days": "vs den letzten 30 Tagen",
    "we replaced 4 tools with metric. fewer reporting meetings, more decisions based on real data. our whole ops team lives in this dashboard now.": "Wir haben 4 Tools durch Metric ersetzt. Weniger Reporting-Meetings, mehr Entscheidungen basierend auf echten Daten. Unser gesamtes Ops-Team lebt jetzt in diesem Dashboard.",
    "weekly and monthly delivery in pdf or html. white-label ready. multi-recipient without requiring accounts.": "Wöchentliche und monatliche Lieferung im PDF- oder HTML-Format. Weißes Etikett bereit. Mehrere Empfänger ohne Konten erforderlich.",
    "yes — csv import, direct bigquery/redshift connection, or via our rest api. configurable retention up to 2 years.": "Ja — CSV-Import, direkte BigQuery/Redshift-Verbindung oder über unsere REST-API. Konfigurierbare Aufbewahrung von bis zu 2 Jahren.",
    "yes — full rest api documented at docs.metric.io. webhooks, javascript and python sdks available.": "Ja — vollständige REST-API dokumentiert unter docs.metric.io. Webhooks, JavaScript- und Python-SDKs verfügbar.",
    "your data is waiting for you.": "Ihre Daten warten auf Sie.",
  },
  pt: {
    "14 days free →": "14 dias grátis →",
    "14 days free on all plans. no credit card required.": "14 dias grátis em todos os planos. Não é necessário cartão de crédito.",
    "14 days free on the growth plan, no credit card required. data is deleted at the end if you don't convert.": "14 dias grátis no plano de Crescimento, não é necessário cartão de crédito. Os dados são eliminados no final se não converter.",
    "14 days free. no credit card. results from day one.": "14 dias grátis. Sem cartão de crédito. Resultados desde o primeiro dia.",
    "200+ native integrations. rest sdk for the rest.": "Mais de duzentas integrações nativas. Um kit REST para o resto.",
    "a 15-minute connection wizard for standard integrations. for complex setups, a solutions engineer accompanies you (included in enterprise).": "Um assistente de conexão de 15 minutos para integrações padrão. Para configurações complexas, um engenheiro de soluções acompanha você (incluído no Enterprise).",
    "analytics, alerts, reports. all-in-one. no compromises.": "Análise, alertas, relatórios. Tudo em um. Sem compromissos.",
    "b2b scale-up, 110 people": "Empresa em crescimento, 110 pessoas",
    "cohorts, funnels, retention analysis, heatmaps. deep behavioral analytics without writing a single line of code.": "Cohortes, funis, análise de retenção, mapas de calor. Análise comportamental profunda sem escrever uma única linha de código.",
    "configurable threshold alerts with anomaly detection. slack, email, and webhook delivery. get warned before the incident.": "Alertas de limiar configurável, com deteção de anomalias. Por mensagem, correio ou webhook. Avisado antes do incidente.",
    "connect everything you use.": "Ligue tudo o que utiliza.",
    "data refreshed every 5 seconds. 40+ visualization types. drag-and-drop widget builder — no sql required.": "Dados atualizados a cada 5 segundos. Mais de 40 tipos de visualização. Construtor de widgets arrastar e soltar — sem necessidade de SQL.",
    "do you offer a free trial?": "Oferece um teste gratuito?",
    "everything your team needs.": "Tudo o que a sua equipa precisa.",
    "free trial": "Teste gratuito",
    "growth": "Crescimento",
    "head of growth": "Chefe de Crescimento",
    "how does onboarding work?": "Como funciona a integração?",
    "identify where users drop off and fix the leaks.": "Detete onde os visitantes desistem e tape as fugas.",
    "is there a public api?": "Há uma API pública?",
    "is your data stored in europe?": "Os seus dados estão armazenados na Europa?",
    "know exactly which channels drive real revenue.": "Saiba com precisão que canais geram receita a sério.",
    "metric turns raw data into actionable insights. dashboards, alerts, and automated reports — all in one platform built for serious teams.": "Metric transforma dados brutos em insights acionáveis. Painéis, alertas e relatórios automatizados - tudo em uma única plataforma construída para equipes sérias.",
    "metric's ai alerts detected a tracking bug 48 hours before we noticed it. that alone saved us 2 weeks of clean data we would have lost forever.": "Os alertas de IA do Metric detectaram um erro de rastreamento 48 horas antes de o notarmos. Isso sozinho nos salvou 2 semanas de dados limpos que teríamos perdido para sempre.",
    "native connectors for ga4, stripe, hubspot, salesforce, postgres, bigquery. rest sdk for everything else.": "Conectores nativos para GA4, Stripe, HubSpot, Salesforce, Postgres, BigQuery. SDK REST para tudo o resto.",
    "new users": "Novos utilizadores",
    "real-time analytics for data-driven teams. make better decisions, faster.": "A análise em tempo real para equipas que decidem com dados. Decidir melhor, mais depressa.",
    "real-time dashboards": "Painéis em tempo real",
    "revenue attribution": "Atribuição de receita",
    "simple, predictable pricing.": "Preços simples e previsíveis.",
    "start for free →": "Começar gratuitamente →",
    "team access & roles": "Acesso e funções da equipe",
    "teams who chose metric.": "Equipes que escolheram a Metric.",
    "the stripe → metric integration gave me real-time mrr and churn visibility i'd been trying to build for 6 months. setup took 12 minutes.": "A integração Stripe → Metric deu-me visibilidade em tempo real do MRR e da taxa de cancelamento que eu tentava construir há 6 meses. A configuração levou 12 minutos.",
    "track how different segments perform over time.": "Siga o comportamento de cada segmento ao longo do tempo.",
    "view demo": "Ver demonstração",
    "vs last 30 days": "vs os últimos 30 dias",
    "we replaced 4 tools with metric. fewer reporting meetings, more decisions based on real data. our whole ops team lives in this dashboard now.": "Substituímos 4 ferramentas pelo Metric. Menos reuniões de relatórios, mais decisões baseadas em dados reais. Toda a nossa equipe de operações vive agora neste painel.",
    "weekly and monthly delivery in pdf or html. white-label ready. multi-recipient without requiring accounts.": "Entrega semanal e mensal em PDF ou HTML. Pronto para marca branca. Múltiplos destinatários sem necessidade de contas.",
    "yes — csv import, direct bigquery/redshift connection, or via our rest api. configurable retention up to 2 years.": "Sim — importação CSV, conexão direta BigQuery/Redshift, ou através da nossa API REST. Retenção configurável até 2 anos.",
    "yes — full rest api documented at docs.metric.io. webhooks, javascript and python sdks available.": "Sim — API REST completa documentada em docs.metric.io. Webhooks, SDKs de JavaScript e Python disponíveis.",
    "your data is waiting for you.": "Os seus dados esperam por si.",
  },
};
