/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in the light.\"": "« L'architecture est le jeu savant, correct et magnifique, des volumes assemblés sous la lumière. »",
    "\"we believe in architecture that breathes with the world, using the elements of earth to build the dreams of man.\"": "« Nous croyons à une architecture qui respire avec le monde, et qui bâtit les rêves des hommes avec les éléments de la terre. »",
    "based in copenhagen": "BASÉ À COPENHAGUE",
    "dissolving the boundaries between indoor living and the natural ecosystem.": "Effacer la frontière entre l'habitat et le vivant qui l'entoure.",
    "join our atelier": "Rejoindre l'atelier",
    "leveraging solar pathing and cross-ventilation to eliminate mechanical cooling.": "Exploiter le cheminement solaire et la ventilation croisée pour éliminer le refroidissement mécanique.",
    "prioritizing raw timber, rammed earth, and local stone with zero toxic finishes.": "Priorisant le bois brut, la terre compactée et la pierre locale sans finitions toxiques.",
    "recognised by": "Reconnu par",
    "request consultation": "Demander une consultation",
    "start your": "Commencez votre",
    "team.": "Équipe.",
    "the terra manifesto": "Notre manifeste",
    "the terra way": "Notre façon de faire",
    "we design structures that don't just sit on the earth, but emerge from it. minimalist, sustainable, and timeless architecture.": "Nous concevons des structures qui ne se contentent pas de reposer sur la terre, mais qui en émergent. Architecture minimaliste, durable et intemporelle.",
    "whether it's a private retreat or a sustainable commercial hub, let's create a space that respects the past and preserves the future.": "Que ce soit un refuge privé ou un pôle commercial durable, créons un espace qui respecte le passé et préserve l'avenir.",
    "with earth.": "AVEC LA TERRE.",
    "works.": "Travaux.",
  },
  es: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in the light.\"": "«La arquitectura es el juego sabio, correcto y magnífico, de los volúmenes reunidos bajo la luz.»",
    "\"we believe in architecture that breathes with the world, using the elements of earth to build the dreams of man.\"": "«Creemos en una arquitectura que respira con el mundo y que construye los sueños de los hombres con los elementos de la tierra.»",
    "based in copenhagen": "CON SEDE EN COPENHAGUE",
    "dissolving the boundaries between indoor living and the natural ecosystem.": "Borrar la frontera entre la vivienda y el entorno vivo.",
    "join our atelier": "Unirse al taller",
    "leveraging solar pathing and cross-ventilation to eliminate mechanical cooling.": "Aprovechando la orientación solar y la ventilación cruzada para eliminar el enfriamiento mecánico.",
    "prioritizing raw timber, rammed earth, and local stone with zero toxic finishes.": "Priorizando la madera sin tratar, la tierra apisonada y la piedra local sin acabados tóxicos.",
    "recognised by": "Reconocido por",
    "request consultation": "Solicitar consulta",
    "start your": "Comienza tu",
    "team.": "Equipo.",
    "the terra manifesto": "Nuestro manifiesto",
    "the terra way": "Nuestra manera de hacer",
    "we design structures that don't just sit on the earth, but emerge from it. minimalist, sustainable, and timeless architecture.": "Diseñamos estructuras que no solo se asientan en la tierra, sino que emergen de ella. Arquitectura minimalista, sostenible y atemporal.",
    "whether it's a private retreat or a sustainable commercial hub, let's create a space that respects the past and preserves the future.": "Ya sea un refugio privado o un centro comercial sostenible, creemos un espacio que respete el pasado y preserve el futuro.",
    "with earth.": "CON LA TIERRA.",
    "works.": "Obras.",
  },
  de: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in the light.\"": "„Architektur ist das kunstvolle, korrekte und großartige Spiel der unter dem Licht versammelten Baukörper.“",
    "\"we believe in architecture that breathes with the world, using the elements of earth to build the dreams of man.\"": "„Wir glauben an eine Architektur, die mit der Welt atmet und die Träume der Menschen aus den Elementen der Erde baut.“",
    "based in copenhagen": "ANSÄSSIG IN KOPENHAGEN",
    "dissolving the boundaries between indoor living and the natural ecosystem.": "Die Grenze zwischen Wohnen und der lebendigen Umgebung auflösen.",
    "join our atelier": "Dem Atelier beitreten",
    "leveraging solar pathing and cross-ventilation to eliminate mechanical cooling.": "Nutzung von solarer Ausrichtung und Querlüftung zur Eliminierung der mechanischen Kühlung.",
    "prioritizing raw timber, rammed earth, and local stone with zero toxic finishes.": "Priorisierung von rohem Holz, gestampfter Erde und lokalem Stein ohne toxische Oberflächen.",
    "recognised by": "Anerkannt von",
    "request consultation": "Beratung anfordern",
    "start your": "Starten Sie Ihr",
    "team.": "Team.",
    "the terra manifesto": "Unser Manifest",
    "the terra way": "Unsere Art zu bauen",
    "we design structures that don't just sit on the earth, but emerge from it. minimalist, sustainable, and timeless architecture.": "Wir entwerfen Strukturen, die nicht nur auf der Erde sitzen, sondern aus ihr hervorgehen. Minimalistische, nachhaltige und zeitlose Architektur.",
    "whether it's a private retreat or a sustainable commercial hub, let's create a space that respects the past and preserves the future.": "Ob es ein privater Rückzugsort oder ein nachhaltiges Handelszentrum ist, lassen Sie uns einen Raum schaffen, der die Vergangenheit respektiert und die Zukunft bewahrt.",
    "with earth.": "MIT DER ERDE.",
    "works.": "Arbeiten.",
  },
  pt: {
    "\"architecture is the learned game, correct and magnificent, of forms assembled in the light.\"": "«A arquitetura é o jogo sábio, correto e magnífico, dos volumes reunidos sob a luz.»",
    "\"we believe in architecture that breathes with the world, using the elements of earth to build the dreams of man.\"": "«Acreditamos numa arquitetura que respira com o mundo e que constrói os sonhos dos homens com os elementos da terra.»",
    "based in copenhagen": "SITUADO EM COPENHAGA",
    "dissolving the boundaries between indoor living and the natural ecosystem.": "Apagar a fronteira entre a habitação e o meio vivo que a rodeia.",
    "join our atelier": "Juntar-se ao atelier",
    "leveraging solar pathing and cross-ventilation to eliminate mechanical cooling.": "Aproveitando a orientação solar e a ventilação cruzada para eliminar o arrefecimento mecânico.",
    "prioritizing raw timber, rammed earth, and local stone with zero toxic finishes.": "Priorizando madeira bruta, terra batida e pedra local sem acabamentos tóxicos.",
    "recognised by": "Reconhecido por",
    "request consultation": "Solicitar consulta",
    "start your": "Comece o seu",
    "team.": "Equipe.",
    "the terra manifesto": "O nosso manifesto",
    "the terra way": "A nossa maneira de fazer",
    "we design structures that don't just sit on the earth, but emerge from it. minimalist, sustainable, and timeless architecture.": "Projetamos estruturas que não apenas repousam sobre a terra, mas emergem dela. Arquitetura minimalista, sustentável e atemporal.",
    "whether it's a private retreat or a sustainable commercial hub, let's create a space that respects the past and preserves the future.": "Seja um retiro privado ou um centro comercial sustentável, vamos criar um espaço que respeite o passado e preserve o futuro.",
    "with earth.": "COM A TERRA.",
    "works.": "Trabalhos.",
  },
};
