// Ce que chaque thème sait afficher, et donc ce que le wizard doit demander.
//
// Généré par analyse statique des 373 thèmes le 2026-08-03 : constantes nommées
// (SERVICES_DEMO, AVIS_DEMO, TARIFS…) et sections écrites directement dans le
// JSX. Les thèmes déclarent 432 noms de constantes différents pour les mêmes
// concepts, d'où cette table : elle donne un vocabulaire unique par-dessus.
//
// Le principe : un client choisit un thème parce qu'il montre ce qu'il veut
// montrer. S'il prend un thème avec une section « zones d'intervention », le
// wizard doit lui demander ses zones — sinon la section restera celle de la
// démonstration, quel que soit le câblage.
//
// Régénérer après ajout de thèmes : voir docs/PLAN_CONTRAT_CONTENU.md.

export type ContentBlock =
  | "prestations"
  | "avis"
  | "engagements"
  | "chiffres"
  | "methode"
  | "tarifs"
  | "realisations"
  | "faq"
  | "equipe"
  | "horaires"
  | "menu"
  | "produits"
  | "zones";

/** Demandé à tous, quel que soit le thème. */
export const SOCLE: ContentBlock[] = ["prestations"];

export const THEME_BLOCKS: Record<string, ContentBlock[]> = {
  "impact-01": ["avis", "chiffres", "engagements", "equipe", "methode", "prestations", "realisations"],
  "impact-02": ["avis", "faq", "methode", "prestations", "realisations"],
  "impact-03": ["engagements", "methode", "produits", "realisations"],
  "impact-04": ["avis", "chiffres", "engagements", "faq", "menu", "tarifs"],
  "impact-05": ["avis", "chiffres", "engagements", "equipe", "faq", "prestations", "realisations", "tarifs"],
  "impact-06": ["avis", "chiffres", "engagements", "prestations", "produits", "realisations"],
  "impact-07": ["avis", "chiffres", "engagements", "prestations", "realisations"],
  "impact-08": ["avis", "engagements", "prestations"],
  "impact-09": ["avis", "engagements", "methode", "prestations"],
  "impact-10": ["avis", "chiffres", "prestations"],
  "impact-11": ["avis", "faq", "prestations", "tarifs"],
  "impact-12": ["engagements", "horaires", "methode", "realisations"],
  "impact-13": ["methode", "realisations"],
  "impact-14": ["avis", "chiffres", "methode", "prestations"],
  "impact-15": ["avis", "chiffres", "prestations", "realisations", "tarifs"],
  "impact-16": ["prestations", "realisations"],
  "impact-17": ["equipe", "horaires", "methode", "prestations", "realisations", "tarifs"],
  "impact-18": ["avis", "chiffres", "faq", "prestations", "tarifs"],
  "impact-19": ["avis", "equipe", "prestations", "realisations"],
  "impact-20": ["avis", "engagements", "produits"],
  "impact-21": ["avis", "methode", "prestations", "realisations", "tarifs"],
  "impact-22": ["avis", "faq", "prestations", "tarifs"],
  "impact-23": ["equipe", "prestations", "realisations", "tarifs"],
  "impact-24": ["avis", "faq", "prestations", "realisations"],
  "impact-25": ["avis", "chiffres", "faq", "prestations", "realisations", "tarifs"],
  "impact-26": ["avis", "engagements", "methode", "prestations", "produits"],
  "impact-27": ["avis", "chiffres", "engagements", "faq", "methode", "prestations", "realisations", "tarifs"],
  "impact-28": ["avis", "engagements", "equipe", "methode", "prestations", "realisations", "zones"],
  "impact-29": ["avis", "chiffres", "engagements", "faq", "methode", "prestations", "realisations"],
  "impact-30": ["avis", "chiffres", "engagements", "equipe", "faq", "prestations", "tarifs"],
  "impact-31": ["avis", "chiffres", "engagements", "faq", "horaires", "prestations", "tarifs"],
  "impact-32": ["avis", "chiffres", "engagements", "equipe", "faq", "horaires", "methode", "prestations", "tarifs"],
  "impact-33": ["avis", "chiffres", "engagements", "faq", "horaires", "produits"],
  "impact-34": ["avis", "engagements", "prestations", "tarifs", "zones"],
  "impact-35": ["avis", "chiffres", "engagements", "equipe", "faq", "prestations", "tarifs", "zones"],
  "impact-36": ["avis", "chiffres", "engagements", "faq", "prestations", "realisations"],
  "impact-37": ["avis", "engagements", "equipe", "faq", "horaires", "menu"],
  "impact-38": ["avis", "chiffres", "engagements", "faq", "horaires", "menu", "methode", "produits", "tarifs"],
  "impact-39": ["avis", "chiffres", "engagements", "faq", "methode", "prestations", "tarifs"],
  "impact-40": ["avis", "engagements", "faq", "horaires", "menu", "prestations", "tarifs"],
  "impact-41": ["avis", "prestations"],
  "impact-42": ["avis", "engagements", "faq", "prestations", "tarifs"],
  "impact-43": ["avis", "equipe", "methode"],
  "impact-44": ["engagements", "equipe", "methode"],
  "impact-45": ["avis", "chiffres", "engagements", "faq", "prestations", "realisations", "tarifs"],
  "impact-46": ["avis", "faq", "prestations", "realisations", "zones"],
  "impact-47": ["avis", "engagements", "faq", "produits"],
  "impact-48": ["engagements", "equipe", "methode", "prestations", "realisations"],
  "impact-49": ["avis", "engagements", "methode", "prestations", "tarifs"],
  "impact-50": ["avis", "chiffres", "prestations", "tarifs"],
  "impact-51": ["avis", "chiffres", "engagements", "prestations", "tarifs"],
  "impact-52": ["avis", "chiffres", "equipe", "prestations", "realisations"],
  "impact-53": ["avis", "chiffres", "prestations", "realisations"],
  "impact-54": ["avis", "chiffres", "engagements", "prestations", "tarifs"],
  "impact-55": ["avis", "chiffres", "engagements", "equipe", "prestations"],
  "impact-56": ["avis", "chiffres", "engagements", "faq", "methode", "prestations"],
  "impact-57": ["avis", "chiffres", "engagements", "equipe", "methode", "prestations", "realisations"],
  "impact-58": ["avis", "chiffres", "engagements", "equipe", "prestations", "realisations"],
  "impact-59": ["avis", "chiffres", "engagements", "faq", "methode", "prestations"],
  "impact-60": ["avis", "engagements"],
  "impact-61": ["avis", "engagements", "equipe", "prestations", "realisations"],
  "impact-62": ["avis", "engagements", "menu", "methode", "prestations"],
  "impact-63": ["avis", "engagements", "prestations"],
  "impact-64": ["avis", "chiffres", "engagements", "equipe", "faq", "methode", "prestations", "tarifs"],
  "impact-65": ["avis", "engagements", "prestations"],
  "impact-66": ["avis", "chiffres", "engagements", "methode", "prestations"],
  "impact-67": ["engagements", "methode", "prestations"],
  "impact-68": ["avis", "chiffres", "engagements", "equipe", "faq", "methode", "prestations", "realisations"],
  "impact-69": ["chiffres", "engagements"],
  "impact-70": ["avis", "engagements", "prestations"],
  "impact-71": ["avis", "engagements", "methode"],
  "impact-72": ["avis", "methode", "prestations"],
  "impact-73": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-74": ["avis", "engagements", "menu", "methode", "realisations"],
  "impact-75": ["avis", "engagements", "faq", "methode", "prestations", "produits"],
  "impact-76": ["avis", "chiffres", "engagements", "equipe", "methode", "prestations", "realisations"],
  "impact-77": ["avis", "engagements", "methode", "prestations", "tarifs"],
  "impact-78": ["avis", "chiffres", "engagements", "methode", "prestations"],
  "impact-79": ["avis", "engagements", "methode", "prestations", "produits"],
  "impact-80": ["avis", "chiffres", "equipe", "faq", "methode", "prestations", "realisations"],
  "impact-81": ["avis", "prestations"],
  "impact-82": ["avis", "engagements", "equipe", "realisations"],
  "impact-83": ["avis", "chiffres", "engagements", "equipe", "faq", "methode"],
  "impact-84": ["avis", "engagements"],
  "impact-85": ["avis", "faq", "methode", "produits"],
  "impact-86": ["avis", "engagements", "equipe", "faq", "horaires", "prestations"],
  "impact-87": ["avis", "chiffres", "horaires", "prestations"],
  "impact-88": ["avis", "engagements", "faq", "horaires", "methode", "prestations", "realisations", "tarifs"],
  "impact-89": ["avis", "chiffres", "faq", "methode", "prestations", "realisations"],
  "impact-90": ["avis", "engagements", "faq", "horaires", "methode", "prestations"],
  "impact-91": ["avis", "chiffres", "engagements", "faq"],
  "impact-92": ["avis", "chiffres", "engagements", "faq", "prestations"],
  "impact-93": ["avis", "engagements", "faq", "prestations", "realisations"],
  "impact-94": ["avis", "chiffres", "engagements", "faq", "horaires", "methode", "realisations"],
  "impact-95": ["engagements", "equipe", "faq", "horaires", "tarifs"],
  "impact-96": ["avis", "chiffres", "faq", "prestations", "realisations", "tarifs"],
  "impact-97": ["chiffres", "prestations", "tarifs"],
  "impact-98": ["chiffres", "realisations"],
  "impact-99": ["chiffres", "engagements", "horaires", "menu"],
  "impact-100": ["chiffres", "realisations"],
  "impact-101": ["avis", "chiffres", "prestations", "realisations"],
  "impact-102": ["avis", "chiffres", "engagements", "equipe", "prestations"],
  "impact-103": ["avis", "equipe", "prestations", "realisations"],
  "impact-104": ["avis", "chiffres", "prestations", "realisations"],
  "impact-105": ["avis", "chiffres", "prestations"],
  "impact-106": ["equipe", "realisations"],
  "impact-107": ["avis", "prestations"],
  "impact-108": ["avis", "chiffres", "engagements", "horaires", "prestations"],
  "impact-109": ["avis", "equipe", "prestations", "produits"],
  "impact-110": ["avis", "prestations"],
  "impact-111": ["avis", "equipe", "prestations", "realisations", "tarifs"],
  "impact-112": ["avis", "engagements", "faq", "methode", "prestations", "produits", "tarifs"],
  "impact-113": ["avis", "faq", "prestations", "realisations", "tarifs"],
  "impact-114": ["avis", "chiffres", "engagements", "methode", "prestations", "realisations"],
  "impact-115": ["avis", "chiffres", "engagements", "equipe", "prestations", "realisations"],
  "impact-116": ["avis", "chiffres", "engagements", "equipe", "faq", "methode", "prestations", "realisations", "tarifs"],
  "impact-117": ["avis", "prestations"],
  "impact-118": ["engagements", "prestations", "realisations"],
  "impact-119": ["avis", "chiffres", "prestations", "tarifs"],
  "impact-120": ["avis", "chiffres", "engagements", "prestations", "realisations", "tarifs"],
  "impact-121": ["avis", "engagements", "prestations", "tarifs"],
  "impact-122": ["avis", "engagements", "prestations"],
  "impact-123": ["engagements", "realisations"],
  "impact-124": ["engagements", "faq", "prestations", "realisations", "tarifs"],
  "impact-125": ["avis", "equipe", "prestations"],
  "impact-126": ["horaires", "menu"],
  "impact-127": ["avis", "chiffres", "faq", "prestations"],
  "impact-128": ["avis", "prestations", "realisations"],
  "impact-129": ["avis", "chiffres", "equipe", "prestations"],
  "impact-130": ["avis", "chiffres", "equipe", "faq", "methode", "prestations", "realisations"],
  "impact-131": ["chiffres", "engagements"],
  "impact-132": ["avis", "engagements", "prestations"],
  "impact-133": ["avis", "prestations", "realisations"],
  "impact-134": ["avis", "engagements", "methode", "prestations", "produits"],
  "impact-135": ["avis", "chiffres", "prestations", "realisations", "tarifs"],
  "impact-136": ["avis", "methode", "prestations", "realisations"],
  "impact-137": ["methode", "tarifs"],
  "impact-138": ["avis", "chiffres", "engagements", "prestations"],
  "impact-139": ["equipe", "prestations", "tarifs"],
  "impact-140": ["avis", "chiffres"],
  "impact-141": ["avis", "chiffres", "prestations"],
  "impact-142": ["avis", "prestations", "tarifs"],
  "impact-143": ["avis", "prestations", "realisations"],
  "impact-144": ["avis", "prestations"],
  "impact-145": ["avis", "prestations", "realisations"],
  "impact-146": ["avis", "engagements", "prestations"],
  "impact-147": ["equipe"],
  "impact-148": ["engagements", "realisations"],
  "impact-149": ["avis", "equipe"],
  "impact-150": ["engagements", "methode", "realisations"],
  "impact-151": [],
  "impact-152": ["avis", "chiffres", "prestations", "realisations"],
  "impact-153": ["avis", "engagements", "equipe", "prestations"],
  "impact-154": ["avis", "engagements", "prestations", "realisations"],
  "impact-155": ["avis", "chiffres", "prestations"],
  "impact-156": ["avis", "chiffres", "engagements", "tarifs"],
  "impact-157": ["avis", "chiffres", "engagements", "faq", "prestations", "realisations"],
  "impact-158": ["avis", "engagements", "prestations"],
  "impact-159": ["avis", "chiffres", "engagements", "prestations"],
  "impact-160": ["avis", "prestations"],
  "impact-161": ["avis", "faq", "prestations", "tarifs"],
  "impact-162": ["avis", "horaires", "menu", "realisations"],
  "impact-163": ["avis", "chiffres", "faq", "methode", "prestations", "tarifs"],
  "impact-164": ["avis", "chiffres", "equipe", "faq", "prestations", "realisations", "tarifs"],
  "impact-165": ["avis", "prestations", "tarifs"],
  "impact-166": ["avis", "engagements", "prestations"],
  "impact-167": ["avis", "chiffres", "methode"],
  "impact-168": ["avis", "chiffres", "engagements", "faq", "produits", "realisations"],
  "impact-169": ["avis", "chiffres", "engagements", "faq", "prestations", "tarifs"],
  "impact-170": ["avis", "engagements", "methode", "prestations", "realisations"],
  "impact-171": ["avis", "engagements", "equipe", "horaires", "methode", "prestations", "tarifs"],
  "impact-172": [],
  "impact-173": ["avis", "chiffres", "engagements", "equipe", "faq", "methode", "realisations"],
  "impact-174": ["equipe"],
  "impact-175": ["avis", "methode", "prestations"],
  "impact-176": ["avis", "chiffres", "faq", "methode", "prestations", "tarifs"],
  "impact-177": ["avis", "prestations", "realisations"],
  "impact-178": ["avis", "engagements", "prestations", "tarifs"],
  "impact-179": ["avis", "prestations", "realisations", "tarifs", "zones"],
  "impact-180": ["avis", "prestations", "realisations", "zones"],
  "impact-181": ["avis", "prestations", "realisations", "zones"],
  "impact-182": ["avis", "prestations", "realisations", "zones"],
  "impact-183": ["avis", "prestations", "realisations", "zones"],
  "impact-184": ["avis", "methode", "prestations", "tarifs", "zones"],
  "impact-185": ["avis", "engagements", "prestations", "tarifs"],
  "impact-186": ["avis", "engagements", "equipe", "prestations", "tarifs"],
  "impact-187": ["avis", "methode", "prestations", "tarifs"],
  "impact-188": ["avis", "equipe", "horaires", "prestations", "tarifs"],
  "impact-189": ["avis", "engagements", "equipe", "prestations", "realisations", "tarifs"],
  "impact-190": ["avis", "equipe", "prestations"],
  "impact-191": ["avis", "prestations", "realisations", "zones"],
  "impact-192": ["avis", "prestations", "tarifs", "zones"],
  "impact-193": ["avis", "horaires", "tarifs"],
  "impact-194": ["avis", "menu", "prestations", "realisations"],
  "impact-195": ["avis", "equipe", "prestations", "realisations"],
  "impact-196": ["avis", "chiffres", "prestations"],
  "impact-197": ["avis", "chiffres", "engagements", "faq", "methode", "prestations", "realisations", "tarifs"],
  "impact-198": ["avis", "engagements", "equipe", "prestations"],
  "impact-199": ["avis", "engagements", "faq", "methode", "realisations", "tarifs"],
  "impact-200": ["avis", "engagements", "methode", "prestations", "realisations"],
  "impact-201": ["avis", "engagements"],
  "impact-207": ["avis", "engagements", "prestations"],
  "impact-208": ["chiffres", "engagements", "equipe", "prestations", "realisations"],
  "impact-209": ["avis", "engagements", "equipe", "methode", "prestations", "realisations"],
  "impact-210": ["avis", "engagements", "prestations", "realisations", "tarifs"],
  "impact-211": ["engagements", "horaires"],
  "impact-212": ["avis", "engagements", "equipe", "faq", "methode", "prestations", "realisations"],
  "impact-213": ["avis", "chiffres", "engagements", "equipe", "faq", "methode", "prestations", "realisations", "tarifs"],
  "impact-214": ["avis", "chiffres", "engagements", "equipe", "faq", "methode", "prestations", "realisations", "zones"],
  "impact-215": ["avis", "engagements", "faq", "methode", "prestations", "produits", "tarifs"],
  "impact-216": ["avis", "chiffres", "engagements", "faq", "prestations", "tarifs"],
  "impact-217": ["engagements", "methode", "produits"],
  "impact-218": ["avis", "engagements"],
  "impact-219": ["avis", "engagements", "faq", "prestations", "realisations", "tarifs"],
  "impact-220": ["avis", "engagements", "methode", "realisations"],
  "impact-221": ["avis", "engagements", "realisations"],
  "impact-222": ["avis", "chiffres", "engagements", "prestations"],
  "impact-223": ["avis", "methode", "prestations", "realisations"],
  "impact-226": ["avis", "chiffres", "engagements", "methode", "realisations", "tarifs"],
  "impact-227": ["avis", "chiffres", "engagements", "equipe", "prestations", "tarifs"],
  "impact-228": ["avis", "chiffres", "engagements", "prestations"],
  "impact-229": ["avis", "chiffres", "engagements", "prestations", "tarifs"],
  "impact-230": ["avis", "chiffres", "engagements", "realisations"],
  "impact-231": ["avis", "chiffres", "engagements", "methode"],
  "impact-232": ["avis", "chiffres", "engagements", "prestations"],
  "impact-233": ["avis", "chiffres", "engagements"],
  "impact-235": ["engagements", "realisations"],
  "impact-236": ["avis", "engagements", "prestations", "realisations"],
  "impact-237": ["avis", "engagements", "equipe", "prestations"],
  "impact-238": ["avis", "engagements", "equipe", "methode"],
  "impact-239": ["avis", "engagements", "realisations"],
  "impact-240": ["engagements", "methode", "prestations"],
  "impact-241": ["engagements", "prestations"],
  "impact-242": ["avis", "engagements", "prestations"],
  "impact-243": ["avis", "engagements"],
  "impact-244": ["avis", "engagements", "prestations"],
  "impact-245": ["avis", "engagements"],
  "impact-246": ["avis", "engagements", "prestations"],
  "impact-247": ["avis", "engagements", "prestations"],
  "impact-248": ["avis", "engagements"],
  "impact-249": ["avis", "engagements"],
  "impact-250": ["avis", "engagements", "prestations", "realisations"],
  "impact-251": ["avis", "engagements", "prestations"],
  "impact-252": ["avis", "engagements"],
  "impact-253": ["avis", "engagements", "methode"],
  "impact-254": ["avis", "engagements", "prestations"],
  "impact-255": ["avis", "engagements", "prestations"],
  "impact-256": ["avis", "engagements", "methode", "prestations", "tarifs"],
  "impact-257": ["avis", "engagements"],
  "impact-258": ["avis", "engagements"],
  "impact-259": ["avis", "engagements", "menu"],
  "impact-260": ["avis", "engagements", "prestations"],
  "impact-261": ["avis", "engagements", "prestations"],
  "impact-262": ["avis", "engagements"],
  "impact-263": ["avis", "engagements", "prestations", "realisations"],
  "impact-264": ["avis", "engagements"],
  "impact-265": ["avis", "engagements"],
  "impact-266": ["avis", "engagements", "prestations"],
  "impact-267": ["avis", "engagements"],
  "impact-268": ["engagements", "methode", "prestations"],
  "impact-269": ["avis", "engagements"],
  "impact-270": ["avis", "engagements"],
  "impact-271": ["avis", "engagements", "prestations"],
  "impact-272": ["avis", "engagements", "methode"],
  "impact-273": ["avis", "engagements"],
  "impact-274": ["avis", "engagements", "equipe", "horaires"],
  "impact-275": ["avis", "chiffres", "engagements", "methode"],
  "impact-276": ["avis", "chiffres", "engagements", "methode"],
  "impact-277": ["avis", "engagements", "methode", "prestations", "realisations", "zones"],
  "impact-278": ["avis", "engagements", "methode", "prestations", "realisations", "zones"],
  "impact-279": ["avis", "engagements"],
  "impact-280": ["avis", "engagements", "methode", "prestations", "realisations", "tarifs", "zones"],
  "impact-281": ["avis", "engagements", "methode", "prestations"],
  "impact-282": ["avis", "engagements", "menu", "methode", "tarifs"],
  "impact-283": ["avis", "engagements", "equipe", "horaires", "tarifs"],
  "impact-284": ["avis", "engagements", "equipe", "prestations"],
  "impact-285": ["avis", "engagements", "equipe", "horaires"],
  "impact-286": ["avis", "chiffres", "engagements", "methode"],
  "impact-287": ["avis", "engagements", "methode", "prestations", "tarifs"],
  "impact-288": ["avis", "chiffres", "engagements", "methode", "prestations", "zones"],
  "impact-289": ["avis", "chiffres", "engagements", "methode", "prestations"],
  "impact-290": ["avis", "engagements", "methode", "prestations", "zones"],
  "impact-291": ["avis", "engagements"],
  "impact-292": ["avis", "engagements", "faq", "horaires", "menu"],
  "impact-293": ["avis", "engagements", "faq", "horaires", "menu"],
  "impact-294": ["avis", "engagements", "faq", "horaires", "menu"],
  "impact-295": ["avis", "engagements", "faq", "horaires", "menu"],
  "impact-296": ["avis", "engagements", "faq", "horaires", "menu"],
  "impact-297": ["avis", "engagements", "faq", "horaires", "menu", "prestations", "tarifs"],
  "impact-298": ["avis", "engagements", "faq", "horaires", "menu", "prestations", "tarifs"],
  "impact-299": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-300": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-301": ["avis", "engagements", "faq", "horaires", "menu", "prestations", "tarifs"],
  "impact-302": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-303": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-304": ["avis", "engagements", "faq", "horaires", "menu", "prestations", "tarifs"],
  "impact-305": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-306": ["avis", "engagements", "faq", "horaires", "menu"],
  "impact-307": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-308": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-309": ["avis", "engagements", "faq", "horaires", "menu", "tarifs"],
  "impact-310": ["avis", "engagements", "faq", "horaires", "menu", "prestations", "realisations", "tarifs"],
  "impact-311": ["avis", "faq", "horaires", "prestations"],
  "impact-312": ["avis", "chiffres", "engagements", "faq", "horaires", "prestations"],
  "impact-313": ["avis", "engagements", "faq", "prestations", "realisations"],
  "impact-314": ["avis", "faq", "prestations", "realisations"],
  "impact-315": ["avis", "engagements", "faq", "horaires", "prestations", "tarifs"],
  "impact-316": ["avis", "engagements", "faq", "horaires", "prestations"],
  "impact-317": ["avis", "engagements", "faq", "horaires", "methode", "prestations", "tarifs"],
  "impact-318": ["avis", "engagements", "faq", "methode", "prestations"],
  "impact-319": ["faq", "prestations"],
  "impact-321": ["chiffres", "engagements", "faq"],
  "impact-322": ["avis", "prestations", "realisations"],
  "impact-324": ["engagements", "faq"],
  "impact-325": ["engagements"],
  "impact-326": ["avis", "chiffres", "engagements", "tarifs"],
  "impact-327": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-328": ["avis", "engagements", "prestations", "tarifs"],
  "impact-329": ["avis", "chiffres", "engagements", "methode", "prestations"],
  "impact-330": ["avis", "engagements", "prestations"],
  "impact-331": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-332": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-333": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-334": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-335": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-336": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-337": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-338": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-339": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-340": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-341": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-342": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-343": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-344": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-345": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-346": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-347": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-348": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-349": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-350": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-351": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-352": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-353": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-354": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-355": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-356": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-357": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-358": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-359": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-360": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-361": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-362": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-363": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-364": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-365": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-366": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-367": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-368": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-369": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-370": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-371": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-372": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-373": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-374": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-375": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-376": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-377": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-378": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-379": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-380": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-381": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-382": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
  "impact-383": ["avis", "chiffres", "engagements", "methode", "prestations", "tarifs"],
};

/**
 * Les blocs à demander pour un thème : son propre jeu, plus le socle.
 * Un thème inconnu retombe sur le socle seul — on préfère demander trop peu
 * que d'inventer une section que le thème ne sait pas afficher.
 */
export function blocksForTheme(templateId: string | undefined): ContentBlock[] {
  const own = (templateId && THEME_BLOCKS[templateId]) || [];
  return Array.from(new Set([...SOCLE, ...own]));
}
