// AUTO-GÉNÉRÉ — ne pas modifier à la main.
// Régénérer : GEMINI_API_KEY=… node scripts/traduire-descriptions.mjs
//
// Les `description` de lib/templates/registry.ts sont rédigées en anglais alors
// que ce fichier est censé être la source française du catalogue. Les fiches
// modèles (/themes/modele/[id]) s'adressent au marché français : leur poser un
// paragraphe anglais serait pire que de n'en poser aucun. Cette table porte donc
// la version française, traduite depuis l'anglais SANS rien y ajouter.
//
// 373 entrées sur 373.

export const DESCRIPTION_FR: Record<string, string> = {
  "impact-01": "Vitrine d'agence multi-sections complète avec animations au défilement, boutons magnétiques, carrousel de portfolio et formulaire de contact.",
  "impact-02": "Photographe de mode et de reportage : séries, méthode en quatre étapes, tarifs et prise de contact.",
  "impact-03": "Maison de mode en fabrication à la commande : collections, matières, atelier et engagement durable.",
  "impact-04": "Restaurant gastronomique étoilé : carte de saison, menu dégustation, privatisation et réservation.",
  "impact-05": "Plateforme technique pour équipes produit : hébergement en périphérie, tableaux de bord, tarifs et essai gratuit.",
  "impact-06": "Neurotechnologie grand public : interface neuronale, sécurité du signal, gouvernance et souveraineté des données.",
  "impact-07": "Fabricant d'enceintes et d'électronique audio haut de gamme : gamme, matières, jalons de la maison.",
  "impact-08": "Atelier automobile de performance : préparation, aérodynamique, châssis et prise de rendez-vous.",
  "impact-09": "Manifeste premium de logistique orbitale et tourisme spatial avec schémas d'ingénierie aérospatiale, dossiers de commandement de mission et protocoles de sécurité.",
  "impact-10": "Palace et hôtel de luxe : chambres et suites, restaurant, spa, bar et réservation.",
  "impact-11": "Plateforme EdTech moderne avec bandeau de cartes de cours flottantes, tarification en dégradé violet, suivi de progression et typographie system-ui.",
  "impact-12": "Marque de mode éditoriale avec bandeau partagé noir et blanc, empilements typographiques, navigation au défilement transparent-vers-blanc et collections en grille éditoriale.",
  "impact-13": "Boutique horlogère de luxe avec palette charbon foncé et laiton, typographie Cormorant Garamond et effets de profondeur parallaxe par carte.",
  "impact-14": "Affrètement de yachts en Méditerranée : flotte, itinéraires, équipage et devis sur mesure.",
  "impact-15": "Entreprise de cybersécurité avec esthétique terminal sombre, accents vert néon, police JetBrains Mono et widget de journal de sécurité cyclique en direct.",
  "impact-16": "Studio photo avec fond sombre, accents dorés, texture de grain superposée et cartes photo pivotées qui se redressent au survol.",
  "impact-17": "Cabinet d'architecture : réalisations, méthode, équipe et contact — palette terre cuite, plans en fond et photographies plein cadre.",
  "impact-18": "Plateforme SaaS avec palette bleu marine foncé et bleu électrique, maquette de bandeau tableau Kanban et vitrine animée des fonctionnalités.",
  "impact-19": "Société de capital-risque avec palette sombre et or, typographie Cormorant Garamond, esthétique VC minimaliste et liste des sociétés du portefeuille.",
  "impact-20": "Maison de joaillerie fine avec palette sombre et or chaud, bandeau à bande défilante, cartes de collection avec animation de bordure dorée au survol.",
  "impact-21": "Studio de design produit avec palette blanc et orange, bandeau à panneau diagonal orange, indicateur d'onglet coulissant et études de cas.",
  "impact-22": "Plateforme cloud d'IA aux tons bleu marine foncé et cyan, diagramme animé du pipeline IA avec points pulsés et tableau comparatif des fonctionnalités.",
  "impact-23": "Studio de production cinématographique avec palette sombre et ambre, police Cormorant Garamond, bandeau de bande film horizontale avec parallaxe de défilement.",
  "impact-24": "Accélérateur de startups : programme de douze semaines, investissement d'amorçage, réseau et candidature.",
  "impact-25": "Agence web et design : sites, applications et identités visuelles — stratégie, design, développement, une seule équipe.",
  "impact-26": "Maison de parfum de luxe aux teintes prune profonde et or rose, bandeau cercle SVG rotatif et animation d'échelle déclenchée au défilement.",
  "impact-27": "Studio 3D et AR avec palette violet foncé, bandeau vue en fil de fer transformée en perspective et vitrines de projets immersives.",
  "impact-28": "Cabinet d'architecture brutaliste : réalisations, méthode, équipe et contact — noir et blanc, sans photographie de complaisance.",
  "impact-29": "Portfolio développeur au style terminal sombre, cyan néon, police JetBrains Mono uniquement, et bandeau texte tapé avec titres préfixés par //.",
  "impact-30": "Clinique dentaire moderne aux teintes blanc et menthe, bandeau SVG de dent animé, cartes de traitements, profils d'équipe et mise en page axée sur la confiance.",
  "impact-31": "Studio de yoga et méditation aux tons terre chauds, polices Lora et Raleway, bandeau cercle de respiration animé et grille du planning des cours.",
  "impact-32": "Clinique vétérinaire conviviale avec palette vert forêt, bandeau empreinte de patte animé, onglets espèces d'animaux et tarification à trois plans.",
  "impact-33": "Boulangerie artisanale aux teintes ivoire chaud et brun, titres Playfair Display, bandeau défilant de pâtisseries et menu organisé par catégorie.",
  "impact-34": "Plateforme d'hébergement de balados : diffusion, statistiques, monétisation et formules.",
  "impact-35": "Espace de coworking premium aux tons ambre, police Space Grotesk, plan d'étage interactif et niveaux d'adhésion jour/mois/année.",
  "impact-36": "Cabinet de recrutement exécutif aux couleurs bleu marine profond et bleu électrique, police Plus Jakarta Sans, compteurs de placements animés et grille des secteurs d'activité.",
  "impact-37": "Bar à vin et cave : sélections par région, dégustations, adhésion et réservation.",
  "impact-38": "Torréfacteur de café de spécialité : origines, abonnements, boutique et atelier.",
  "impact-39": "Entreprise de déménagement et logistique aux couleurs orange et marine, bandeau SVG de camion animé, frise chronologique du processus en 4 étapes et bouton d'action devis instantané.",
  "impact-40": "Ferme biologique et abonnement CSA aux teintes vert forêt et jaune doré, bandeau SVG de plante en croissance animé, onglets saisonniers et histoire de la ferme.",
  "impact-41": "Organisation humanitaire à but non lucratif avec une palette bleu compassion et jaune ensoleillé, compteurs d'impact animés, niveaux de dons et programmes de mission.",
  "impact-42": "Studio d'enregistrement professionnel avec une palette noir pur et rouge néon, titres Bebas Neue, barres d'égalisation animées et bandeau d'artistes remarquables.",
  "impact-43": "Spa et retraite de bien-être : rituels de soin, bassins, équipe de praticiens et formules.",
  "impact-44": "Studio de design d'intérieur avec blanc chaud et terre cuite, police DM Serif Display, bandeau éditorial partagé, portfolio de projets filtrable et étapes du processus.",
  "impact-45": "Studio de tatouage ligne fine et blackwork : artistes, galerie, tarifs et demande de rendez-vous.",
  "impact-46": "Cabinet d'avocats d'affaires : domaines, équipe associée, honoraires et premier rendez-vous.",
  "impact-47": "Fleuriste et atelier floral : compositions de saison, abonnements, mariages et ateliers.",
  "impact-48": "Cabinet de gestion de patrimoine avec charbon foncé et or chaud, police Cormorant Garamond, SVG de graphique de portefeuille animé et profils de conseillers.",
  "impact-49": "Place de cours en ligne avec dégradé violet profond et sarcelle, police Plus Jakarta Sans, bandeau de recherche, barres de progression des compétences et tarification à trois plans.",
  "impact-50": "Interface fluide visqueuse présentant des manifestes liquides et des coques d'interface fluides, pour une navigation immersive et organique.",
  "impact-51": "Plateforme de développement : environnements, déploiement, sécurité et tarifs.",
  "impact-52": "Interface de champ de particules dynamique avec manifestes de particules et coques d'interface de champ, offrant une visualisation interactive.",
  "impact-53": "Studio de direction artistique : identité de marque, sites, direction créative externalisée et campagnes.",
  "impact-54": "Interface de typographie cinétique intégrant des manifestes d’écho et des coques d’interface au défilement.",
  "impact-55": "Interface HUD de style sci-fi avec des manifestes néon et des coques d’interface HUD.",
  "impact-56": "Domaine et château pour réceptions : salles, hébergement, mariages et visite.",
  "impact-57": "Typographie à grande échelle associée à des effets vidéo de fond masqués, offrant une présence visuelle marquée.",
  "impact-58": "Carrousel au défilement animé, présentant une distorsion dynamique en biais qui crée un effet de mouvement fluide.",
  "impact-59": "Vitrine e-commerce technique, offrant une mise en avant interactive des spécifications produit pour faciliter la compréhension des caractéristiques.",
  "impact-60": "Pile photographique au style brutaliste, intégrant des transitions épinglées qui dévoilent progressivement les images au défilement.",
  "impact-61": "Navigation verticale à points sur une page unique, avec des sections qui s’enclenchent en douceur.",
  "impact-62": "Transitions SVG « Gooey » viscerales appliquées à une typographie audacieuse, créant un effet fluide et organique.",
  "impact-63": "Manufacture horlogère : collections, mouvements, savoir-faire et prise de rendez-vous.",
  "impact-64": "Pluie de données inspirée de Matrix, moderne, affichant des fragments de code technique.",
  "impact-65": "Fabricant de composites carbone : procédés, contrôle qualité, applications et devis.",
  "impact-66": "Protocole gastronomique interactif présentant l’anatomie des ingrédients, pour explorer chaque composant.",
  "impact-67": "Sélecteur de pièces inspiré d’un HUD, dédié à l’immobilier haut de gamme.",
  "impact-68": "Studio de branding : identité, direction artistique, réalisations et démarrage de projet.",
  "impact-69": "Photographe d'art et tirages en édition limitée : séries, papiers, format et commande.",
  "impact-70": "Club et salle de concert : programmation, salons privés, réservation de table.",
  "impact-71": "Studio de yoga et de respiration : cours, retraites, séances en entreprise et abonnement.",
  "impact-72": "Pile de projets en éventail 3D animée par une physique à ressort, offrant un effet de dispersion fluide.",
  "impact-73": "École de musique et conservatoire : cours de piano, guitare, chant et batterie, individuels ou en groupe, enfants et adultes.",
  "impact-74": "Menu liquide pour la haute cuisine, avec transitions circulaires via clip-path.",
  "impact-75": "Rotation interactive 3D d’un produit pour le commerce électronique haut de gamme.",
  "impact-76": "Panneaux en verre flottants d’interface sur des arrière-plans cinématographiques de nature.",
  "impact-77": "Photographe au moyen format : séries, tirages, publications et prise de contact.",
  "impact-78": "Typographie constituée de particules virtuelles, accompagnée d’animations de fragmentation.",
  "impact-79": "Révélations de sections horizontales épinglées, soutenues par d’énormes ancres topographiques.",
  "impact-80": "Portfolio de studio d’architecture incluant une archive de projets résidentiels et commerciaux, une grille de récompenses, les profils des associés fondateurs, et un processus de conception en six étapes.",
  "impact-81": "Magazine de mode haut de gamme avec grilles en mosaïque asymétriques, données d'entropie culturelle et vitrines modulaires de boutique.",
  "impact-82": "Promoteur immobilier : programmes résidentiels haut de gamme, bureaux et opérations mixtes, avec chiffres-clés et équipe.",
  "impact-83": "Maison de joaillerie et horlogerie ultra-luxe avec révélations interactives de pierres précieuses et frises chronologiques d'artisans historiques.",
  "impact-84": "Clinique de médecine esthétique d'élite avec audits interactifs des traitements, dossiers de spécialistes et protocoles de sécurité médicale.",
  "impact-85": "Laboratoire de soins de la peau haut de gamme avec révélation de formulations moléculaires, données de résultats cliniques et service de conciergerie cutanée sur mesure.",
  "impact-86": "Spa et institut de beauté : rituels de soin, équipements thermaux, botaniques et réservation.",
  "impact-87": "Vitrine de salle de CrossFit et fitness à Lyon avec emplois du temps des cours, profils d'entraîneurs certifiés, témoignages de la communauté et proposition d'adhésion en salle ouverte.",
  "impact-88": "Salon d'art des ongles premium avec portfolio filtrable, fenêtre de réservation, menu des soins, profils d'artistes et pied de page méga rose doré.",
  "impact-89": "Studio de tatouage et piercing de luxe au style brutaliste sombre, portfolio filtrable, audit de stérilisation et profils d'artistes.",
  "impact-90": "Boulangerie artisanale : pains au levain, viennoiseries, fournées du jour et click and collect.",
  "impact-91": "Atelier de joaillerie haute fidélité avec archives saisonnières, plans de services sur mesure, statistiques d'artisanat et design luxe à empattement doré.",
  "impact-92": "Groupe immobilier et conciergerie ultra-luxe avec annonces privées interactives, grilles de capacités d'écosystème et esthétique en marbre noir.",
  "impact-93": "Affrètement de jets privés : flotte, terminaux privés, délais de mise à disposition et devis.",
  "impact-94": "Atelier floral haut de gamme : compositions, abonnements, événements et boutique en ligne.",
  "impact-95": "Clinique de médecine esthétique premium avec protocoles de traitement, analyses diagnostiques approfondies, grilles de fondations scientifiques et design clinique minimaliste.",
  "impact-96": "Maison de production cinématographique parisienne de prestige, réalisant fictions, documentaires et publicités pour des clients de luxe (Cartier, Hermès, Arte, Canal+), avec studio de post-production intégré 4K/Atmos.",
  "impact-97": "Affrètement de yachts de luxe : flotte, destinations, équipage et service sur mesure.",
  "impact-98": "Atelier horloger suisse premium avec archives de spécifications de calibres, modules de services d'artisanat et analyses approfondies de philosophie patrimoniale.",
  "impact-99": "Steakhouse haut de gamme au feu de bois avec archives de menus saisonniers, grilles de philosophie du laboratoire du feu et analyses détaillées de l'expérience de cave.",
  "impact-100": "Studio de design d'intérieur minimaliste haut de gamme avec grilles d'archives de projets, modules de services de psychologie spatiale et analyses approfondies de l'atelier.",
  "impact-101": "Ce site propose une interface SPA pour une plateforme développeur, affichant une esthétique de terminal high-tech et des manifestes de télémétrie détaillés.",
  "impact-102": "Institut de recherche en informatique quantique : processeurs tolérants aux fautes, algorithmes, accès chercheurs.",
  "impact-103": "Cabinet d'avocats d'affaires international : fusions-acquisitions, contentieux, notes de doctrine et dossiers de référence.",
  "impact-104": "Studio de photographie de mariage et portrait, proposant une vitrine de galerie, des sections dédiées mariages et portraits, ainsi qu'un formulaire de demande de devis pour réservation.",
  "impact-105": "Fleuriste artisanal à Strasbourg, offrant des créations de bouquets saisonniers, des designs floraux pour mariages et des services floraux pour entreprises et commerces.",
  "impact-106": "SPA d'un studio créatif multidisciplinaire, présentant des effets au survol de la liste de projets, une grille de compétences, une section récompenses et une esthétique chaleureuse orange sur fond crème.",
  "impact-107": "Voyagiste d'expédition : itinéraires polaires et australs, guides, témoignages et réservation.",
  "impact-108": "Vitrine d'un cabinet d'expertise comptable à Bordeaux, fort de 25 ans d'activité, proposant des conseils fiscaux proactifs et un positionnement centré sur la relation client.",
  "impact-109": "SPA d'infrastructure de réseau maillé IoT, avec animations de pulsation des nœuds, affichage tête-up de télémétrie et une esthétique industrielle violette.",
  "impact-110": "SPA de défense contre les incendies de forêt, intégrant des effets de scintillement thermique, la télémétrie d'une flotte de drones et une esthétique industrielle orange de surveillance incendie.",
  "impact-111": "Application monopage de communication interstellaire avec animations d'anneaux orbitaux, télémétrie de flotte de sondes et esthétique cyan-industrielle.",
  "impact-112": "Grille e-commerce artisanale minimaliste aux tons chauds et boutons de panier au survol.",
  "impact-113": "Plateforme d'infrastructure logicielle : exécution en périphérie, sécurité, conformité et tarifs.",
  "impact-114": "Curseur plein écran a revelation en rideau presentant photographies de nature et titres en empattement.",
  "impact-115": "Architecture bio-inspirée : projets, philosophie du vivant, matériaux biosourcés et équipe.",
  "impact-116": "Studio de motion design : réalisations, prestations, équipe et devis.",
  "impact-117": "Application monopage de decouverte de medicaments par IA avec visualisation de cibles moleculaires, telemetrie du pipeline clinique et esthétique emeraude-biotech.",
  "impact-118": "Maison horlogere suisse de luxe (Geneve) presentant une vitrine de collections, le récit du montage manuel et une frise chronologique du patrimoine.",
  "impact-119": "Fournisseur cloud pour entreprises : conformité, régions, crédits d'essai et tarifs.",
  "impact-120": "SPA de maison de parfum de luxe avec visualisation des molécules, anneaux de parfum en expansion, plantes rares et esthétique prune-violet profonde.",
  "impact-121": "SPA de portfolio créatif avec liste de projets révélée au survol, grille de services, section récompenses et esthétique épurée monochrome à thème clair.",
  "impact-122": "SPA de magazine éditorial avec barre de progression de lecture, cartes d'articles longs en vedette, typographie à empattement et esthétique ambre éditoriale.",
  "impact-123": "SPA d'atelier hypercar avec gamme de modèles, télémétrie de performance (0-100 km/h, force d'appui), programme de journées sur circuit pour propriétaires et histoire d'ingénierie ex-F1.",
  "impact-124": "SPA de studio de motion design avec bandeau blob morphologique, mise à l'échelle liée au défilement, effets au survol de la liste de projets et esthétique fuchsia créative.",
  "impact-125": "SPA de laboratoire de design interactif avec aura de curseur personnalisée, balayage radar, grille de recherche haptique et esthétique cyan interactive.",
  "impact-126": "Trattoria romaine : pâtes fraîches du jour, carte des vins, histoire de la maison et réservation.",
  "impact-127": "Producteur de concerts : programmation, salles, billetterie et partenariats.",
  "impact-128": "Agence immobilière de prestige : biens hors marché, discrétion, réseau international et estimation.",
  "impact-129": "Outil de données open source : installation, exemples de code, documentation et communauté.",
  "impact-130": "Diaporama à écran partagé présentant une image à gauche, du contenu à droite et des accents émeraude.",
  "impact-131": "Bandeau vitrine de vins aux tons bordeaux profonds, décor de vignoble et présentation de bouteilles.",
  "impact-132": "Revue de fond : articles longs, infolettre hebdomadaire, abonnement et rédaction.",
  "impact-133": "Studio d'architecture paramétrique : projets, méthode de calcul, outils et contact.",
  "impact-134": "Grille e-commerce beauté et soins de la peau aux tons pêche et étiquettes d'accent rose.",
  "impact-135": "Plateforme de trading : données de marché, tests rétrospectifs, exécution et gestion du risque.",
  "impact-136": "Studio digital : sites et applications sur mesure — conversion, performance et parti pris esthétique.",
  "impact-137": "Torréfacteur de café de spécialité, 2e variante : origines, abonnements, avis et boutique.",
  "impact-138": "Tableau de bord analytique en glassmorphism, avec fond en dégradé, diagramme à barres et cartes de métriques.",
  "impact-139": "Studio de fitness boutique SPA proposant des programmes d'entraînement signature (force, HIIT, récupération), suivi en temps réel du rythme cardiaque et offres d'adhésion à plusieurs niveaux.",
  "impact-140": "Bandeau d'agence de voyage avec cartes de destinations, accents ambrés et paysage en plein écran.",
  "impact-141": "Site d'un label indépendant et collectif d'artistes, incluant lecteur musical complet, catalogue de sorties, roster d'artistes, dates de tournée et boutique.",
  "impact-142": "Compensation carbone : programmes de reboisement et dépollution des océans, formules particuliers et entreprises.",
  "impact-143": "Architecte d'intérieur : projets, prestations, matières et prise de rendez-vous.",
  "impact-144": "Studio de motion design, 2e variante : réalisations, prestations, méthode et démarrage de projet.",
  "impact-145": "SPA immobilier ultra-luxe proposant des annonces mondiales (NYC, Santorin, Kyoto), avec des galeries vitrine en parallaxe et un positionnement destiné à une clientèle fortunée.",
  "impact-146": "Restaurant omakase Edomae ultra-exclusif de 8 places, avec biographie du chef, menus dégustation changeant chaque soir et positionnement uniquement sur réservation.",
  "impact-147": "Récupération d'actifs et défense juridique face au cyber : traçage, gel des avoirs, protection et alertes.",
  "impact-148": "Narration pour soins de la peau bio, aux tons crème doux, typographie serif délicate et ambiance botanique.",
  "impact-149": "Vitrine de mobilier haut de gamme avec transitions en perspective 3D et typographie gras italique.",
  "impact-150": "Cabinet d'avocats international : quatre pôles, dossiers de référence, implantations et contact.",
  "impact-151": "Boutique winery & distillery estate SPA avec vitrine vintage, données de terroir (altitude, sol, température) et catalogue de vins et whiskys en édition limitée.",
  "impact-152": "Architecte d'intérieur : projets, prestations, atelier et devis — grille de réalisations, témoignages et esthétique chaude ambre.",
  "impact-153": "Page unique d'agence d'ingénierie avec grille de fonctionnalités, compteurs de statistiques, témoignages, niveaux tarifaires et esthétique sombre violet-tech.",
  "impact-154": "Site vitrine d'agence créative avec page à propos, grille de services, portfolio, témoignages, tarification et esthétique sombre rose-crimson.",
  "impact-155": "Page unique de galerie d'art numérique avec collections, grille de fonctionnalités, témoignages, tarification d'abonnement et esthétique sombre violet-créatif.",
  "impact-156": "Site vitrine d'architecture durable avec page à propos, portfolio de projets, grille de services, témoignages et esthétique claire vert-sauge.",
  "impact-157": "Page détaillée e-commerce de bijoux ultra-premium aux tons obsidienne profonds, accents dorés et mise en avant de photographies sculpturales haut de gamme.",
  "impact-158": "Magazine de voyage : récits, destinations, galerie et infolettre.",
  "impact-159": "Page unique d'événement technologique à haute énergie avec compte à rebours dynamique, accents dégradé néon et effets de fond immersifs de style particules.",
  "impact-160": "Lookbook de mode minimaliste en cascade avec design monochrome à fort contraste, effets au survol et titres héroïques en gras.",
  "impact-161": "Page unique SaaS épurée avec une structure de blocs HTML sémantique prête pour WordPress/Elementor.",
  "impact-162": "Café de spécialité et torréfaction : carte, histoire de la maison, galerie et adresse.",
  "impact-163": "Blog au style éditorial de journal — grille newspaper asymétrique, articles bandeau avec date en marge, filtrage par catégories, typographie vieille presse et parallaxe de fond.",
  "impact-164": "Agence créative brutaliste — typographie monospace, grille à deux colonnes asymétrique, bandeau défilant horizontal, liste de services qui s’étend au survol et sélecteur d’études de cas.",
  "impact-165": "Page unique SaaS pour application mobile — maquette de téléphone avec parallaxe de mise à l’échelle au défilement, onglets des fonctionnalités animés, section témoignages sombre et tarifs à trois niveaux sous forme de pilules.",
  "impact-166": "Studio photo : séries, prestations, témoignages et réservation.",
  "impact-167": "Chasseur immobilier : entretien préalable, marché hors annonces, négociation et accompagnement jusqu'à l'acte.",
  "impact-168": "Bandeau d'annonce, bandeau plein écran sombre, grille de produits avec liste d'envies cœur et compteur d'ajout au panier, zoom au survol de l'image et newsletter en bas de section.",
  "impact-169": "Mise en page type journal avec colonne latérale catégories verticale, logo en rotation au défilement, archive des numéros cliquables en liste et inscription scindée jaune/sombre.",
  "impact-170": "Animations de frappe séquencées, barres de compétences activées en visibilité, frise chronologique de carrière verticale et cartes de projets avec révélation ciblée au survol.",
  "impact-171": "Clinique médicale moderne — bandeau partagé avec cartes spécialistes flottantes en décalé, onglets spécialités AnimatePresence, statistiques teal sur fond plein et tarification avec mise en évidence par mise à l'échelle.",
  "impact-172": "Bandeau au format 3:2 avec titre italique surdimensionné, barre latérale « domaines » contenant un panneau AnimatePresence, et associés présentés en grille avec une ligne dorée absolue en haut.",
  "impact-173": "Site BTP industriel avec titre en pleine largeur (clamp64px-11vw-160px) en capitales, panneau diagonal orange via clipPath, barres de progression de projets animées et services affichés sous icônes carrées.",
  "impact-174": "Bandeau partagé 50% noir / 50% néon lime, barres d'intensité à quatre dimensions déclenchées en useInView, programmes actifs avec bordure accentuée et bouton d'action lime en pleine largeur.",
  "impact-175": "Bandeau centré avec cercles décoratifs absolus, sélecteur de types d'événements à multiples accents, frise chronologique à quatre étapes verticale et statistiques en prune avec chiffres en police serif.",
  "impact-176": "Plateforme d'analytique produit : détection d'anomalies, prévision de tendance, cohortes et tarifs.",
  "impact-177": "Studio de conception et construction de piscines sur mesure (Lyon) présenté en vitrine, avec design conceptuel 3D, réalisations personnalisées, rénovations et aménagements de pool-house.",
  "impact-178": "Agence immobilière premium à Paris présentée en vitrine, proposant des annonces de biens de luxe, estimation gratuite, marketing haut de gamme et services de gestion locative.",
  "impact-179": "Page unique d'association caritative avec photographies émotionnelles, titres en police serif et bouton d'action de don.",
  "impact-180": "Mise en page split-screen pour barbershop/salon premium, esthétique sombre et liste de prix.",
  "impact-181": "Pisciniste : construction béton ou coque, rénovation de bassin, entretien et sécurité — devis gratuit, garantie décennale.",
  "impact-182": "Page unique premium d'hôtel de luxe avec polices serif élégantes, effet parallaxe et grandes photographies immersives.",
  "impact-183": "Plateforme SaaS IA premium avec effets de verre néumorphique, lueurs en mode sombre et indices d'interface générative.",
  "impact-184": "Musée moderne premium avec mise en page à barre latérale brutaliste, typographie extrême et bordures solides.",
  "impact-185": "Mise en page premium de marque de mode avec texte de bandeau massif intégré à la photographie de fond.",
  "impact-186": "Grille structurelle premium d'agence d'architecture avec révélations au survol brutalistes en niveaux de gris.",
  "impact-187": "Interface premium FinTech avec graphiques lumineux, dégradés bleu profond/émeraude et glassmorphism.",
  "impact-188": "Production cinématographique premium — esthétique à défilement horizontal, typographie cinématographique et grandes tuiles cinématographiques.",
  "impact-189": "Disposition premium pour restaurant/dîner — thèmes sombres romantiques, sérifs fins élégants et masques d'image hauts.",
  "impact-190": "Page unique premium pour studio cyberpunk/jeu — effets de grille néon, texte inspiré du glitch et lignes nettes.",
  "impact-191": "Clinique haut de gamme en santé et esthétique, avec une mise en page épurée qui inspire confiance et met l’accent sur la réservation de rendez-vous.",
  "impact-192": "Modèle e-commerce de cosmétiques haut de gamme, proposant des grilles de produits dynamiques, des révélations de textures et un panier latéral.",
  "impact-193": "Mise en page premium pour cabinet d’avocats d’entreprise et cabinet de conseil, avec typographie à empattement et design autoritaire.",
  "impact-194": "Interface avancée d’ingénierie de gravité artificielle et de singularité, affichant en temps réel des mesures de courbure et des moniteurs de forces de marée.",
  "impact-195": "Interface d'ingénierie climatique et de capture atmosphérique à l'échelle planétaire, intégrant la titration du carbone et les systèmes de contrôle de l'albédo.",
  "impact-196": "Cabinet de kinésithérapie : rééducation orthopédique, neurologique, sportive et respiratoire.",
  "impact-197": "Page unique d'agence de voyages de luxe présentant des itinéraires sur mesure, un bandeau parallaxe, des cartes de destination, des services de conciergerie et une tarification à 3 niveaux.",
  "impact-198": "Vitrine de salon de beauté haut de gamme mettant en avant des produits bio et naturels, une grille de soins, des onglets d'équipe, un carrousel de témoignages et des offres saisonnières.",
  "impact-199": "Studio de tatouage artistique proposant une vitrine de six styles, trois profils d'artistes, une tarification flash et personnalisée, ainsi qu'une esthétique éditoriale sombre.",
  "impact-200": "Page unique de planificateur de mariages affichant une galerie d'événements passés, des services de coordination complète, des offres à 3 niveaux et une esthétique romantique.",
  "impact-201": "Vitrine de chef privé : restauration gastronomique à domicile, menus saisonniers, chef formé aux standards Michelin, service de traiteur événementiel et témoignages.",
  "impact-207": "Freight & logistics B2B premium : carte SVG animée des itinéraires, bandeau parallaxe de la flotte, frise chronologique de livraison en temps réel, statistiques de couverture mondiale et bouton d'action entreprise.",
  "impact-208": "Entreprise de construction premium : révélation animée d’un plan SVG, compteur de bâtiments piloté par le défilement, vitrine en grille de matériaux, portefeuille de projets et formulaire de devis.",
  "impact-209": "Salon de coiffure de luxe : bandeau animé avec ciseaux, curseur avant/après, menu de services premium, profils de l’équipe et étapes de réservation en ligne.",
  "impact-210": "Salon d'onglerie : prestations, palette de teintes, galerie et réservation en ligne.",
  "impact-211": "Restaurant gastronomique : bandeau cinématographique de photographies de plats, carte interactive du terroir français, menu animé au défilement, section sommelier et formulaire de réservation.",
  "impact-212": "Entreprise premium de chauffage et climatisation : pompes à chaleur, chaudières, climatisation, plancher chauffant. Bandeau parallaxe feu, compteurs animés, certifications RGE et bouton d'action urgence 24 h/24.",
  "impact-213": "Entreprise premium de maçonnerie et construction : maçonnerie générale, ravalement ITE, carrelage. Bandeau animé de plan, plan d’étage SVG animé, portefeuille complet de projets BTP.",
  "impact-214": "Entreprise premium de plomberie et sanitaires : dépannage fuite 24 h/24, rénovation de salle de bains, débouchage, chauffe-eau. Bandeau animé goutte d’eau, bannière de ligne d’urgence et portefeuille de salles de bains.",
  "impact-215": "E-commerce premium de chauffage : poêles à bois, granulés, inserts et cheminées. Bandeau animé de particules d’étincelles, configurateur produit interactif en 3 étapes, panier latéral et catalogue certifié Flamme Verte.",
  "impact-216": "Entreprise premium B2B de logistique et fret : transport express, messagerie, logistique e-commerce, entreposage. Carte SVG animée de couverture France, suivi de livraison en temps réel et tarification à 3 niveaux.",
  "impact-217": "Boutique de baskets en séries limitées : collections, matières et panier.",
  "impact-218": "E-commerce de domaine viticole français : animation SVG du cep à la bouteille au verre pilotée par le défilement, catalogue de cartes de millésimes, narration du terroir et commande basée sur allocation.",
  "impact-219": "Page unique SaaS full-stack : bandeau animé de tableau de bord, logos clients, grille de 6 avantages, processus en 3 étapes, tarification à 3 niveaux, témoignages, accordéon FAQ et bouton d'action final.",
  "impact-220": "Marque suisse de montres ultra-luxe présentant un mécanisme de montre Canvas 2D piloté par le défilement (ouverture du boîtier, trains d'engrenages, révélation du tourbillon), des chapitres éditoriaux, une grille de collection et un formulaire de devis sur mesure.",
  "impact-221": "Marque de mobilité urbaine électrique proposant des sections plein écran à défilement à enclenchement, un scooter Canvas 2D à lueur néon, une vue éclatée du véhicule, des spécifications en incrémentation et un formulaire de réservation avec compte à rebours.",
  "impact-222": "Agence immobilière haut de gamme offrant une façade de bâtiment Canvas 2D avec fenêtres éclairées, une carte SVG de la France avec points de ville animés, des cartes de biens avec superpositions au survol, des statistiques en incrémentation et un formulaire de contact.",
  "impact-223": "Vitrine de services d’électricien – installation électrique, tableaux de distribution, câblage neuf, mise aux normes NF C 15-100, habitat individuel et collectif.",
  "impact-226": "Vitrine de studio de tatouage (Paris 11e) – trois artistes spécialistes (blackwork, réalisme, japonais, aquarelle), pièces sur mesure, portfolio Instagram.",
  "impact-227": "Vitrine de barbershop et salon de grooming masculin (Lyon) – coupes classiques, rasages à la lame droite traditionnels, sculpture de barbe et soins du cuir chevelu.",
  "impact-228": "Services d'électricien premium — urgence 1 h, 16 ans d'expérience, plus de 5 000 interventions, 24 h/7 j, avec une typographie Bebas Neue en gras.",
  "impact-229": "Institut de beauté vitrine — 14 ans d'expertise, plus de 3 200 soins, note Google 4,9★, soins signature de 90 min, réservation et témoignages.",
  "impact-230": "Atelier d'ébéniste artisan — 20 ans d'ébénisterie, plus de 600 pièces créées, 100 % du bois provenant de France, garantie de 3 ans sur les pièces.",
  "impact-231": "Cabinet de diététicien-nutritionniste — 8 ans d'expérience, plus de 1 200 patients, 92 % des objectifs atteints, rendez-vous sous 48 h.",
  "impact-232": "Vitrine de jardinier paysagiste — 15 ans d'expertise, plus de 350 jardins réalisés, zéro pesticide, 94 % de clients satisfaits.",
  "impact-233": "Cabinet d'ostéopathie : motifs de consultation, approche, avis et prise de rendez-vous.",
  "impact-235": "Modèle éditorial de type magazine avec numéros d'édition, chapitres éditoriaux et mises en page typographiques riches.",
  "impact-236": "Services d'électricien modernes — mise aux normes, installation électrique, avec une typographie Inter épurée et pied de page SIRET.",
  "impact-237": "Cabinet dentaire vitrine — soins conservateurs, prévention, esthétique dentaire, typographie DM Serif Display.",
  "impact-238": "Centre de physiothérapie vitrine — rééducation, bilan fonctionnel, sportifs et séniors, situé à Rennes.",
  "impact-239": "Cabinet d'avocats vitrine — droit des affaires, contentieux, expertise de 1998 à 2026, typographie serif classique.",
  "impact-240": "Studio de coaching athlétique — coaching privé, programmes sur mesure, typographie Barlow condensée.",
  "impact-241": "Agence immobilière premium à Bordeaux — investissement locatif, expertise depuis 2003, identité serif classique.",
  "impact-242": "Cabinet d'expertise comptable vitrine — conseil en gestion, expertise comptable, membre OEC, typographie Plus Jakarta Sans.",
  "impact-243": "Médecin généraliste : médecine générale, préventive et du sport, avec prise de rendez-vous.",
  "impact-244": "Maison de décoration et d'aménagement intérieur : collections, projets et conseil.",
  "impact-245": "Rôtisserie artisanale de café — torréfaction, origines, de 2011 à 2026, typographie Libre Baskerville chaleureuse.",
  "impact-246": "Spécialiste CVC à Marseille — chauffage, climatisation, typographie DM Serif Display élégante.",
  "impact-247": "Vitrine d'électricien premium — éclairage, installation électrique, style éditorial Playfair Display.",
  "impact-248": "Cabinet d'ostéopathe à Paris 11e — structure, fonctionnement, typographie Cormorant Garamond de luxe.",
  "impact-249": "Studio de tatouage à Montpellier – blackwork, illustration, identité en gras DM Serif Display.",
  "impact-250": "Vitrine de studio de céramique – conception, création artisanale, 2010–2026, typographie Cardo serif.",
  "impact-251": "Planificateur de mariages de luxe – robe sur mesure, organisation, typographie serif Italiana ultra-luxueuse.",
  "impact-252": "Cabinet dentaire : soins conservateurs, esthétique dentaire, implantologie et technologie.",
  "impact-253": "Physiothérapie sportive à Paris 15e – blessures sportives, rééducation, performance, typographie Playfair Display.",
  "impact-254": "Cabinet d'avocats vitrine — conseil en gestion, droit des affaires, 1990–2026, police EB Garamond classique.",
  "impact-255": "Avocat à Toulouse — contentieux commercial, 87 % de dossiers résolus, police Spectral serif autorité.",
  "impact-256": "Coach sportif personnel à Marseille — coaching sur mesure, typographie athlétique Lora + Oswald.",
  "impact-257": "Médecin conventionné secteur 2 vitrine — consultations, téléconsultation, RPPS, police Merriweather serif.",
  "impact-258": "Marque d'hôtellerie de luxe — 2012–2026, typographie éditoriale serif Cormorant ultra-luxe.",
  "impact-259": "Boulangerie artisanale à Strasbourg — pains, viennoiseries, service traiteur, 2009–2026, police Fraunces serif éditoriale.",
  "impact-260": "Spécialiste en plomberie à Lyon — plomberie, chauffage, certification RGE, identité chaleureuse Playfair Display.",
  "impact-261": "Cabinet de conseil en management — conseil en gestion, stratégie, 2015–2026, identité épurée DM Serif.",
  "impact-262": "Studio de tatouage premium dans le Marais à Paris — illustration, blackwork, typographie Bodoni Moda, style éditorial de luxe en empattement.",
  "impact-263": "Designer paysagiste à Bordeaux — jardins privatifs, 2006–2026, typographie Cormorant Garamond, élégance naturelle.",
  "impact-264": "Cabinet d'ostéopathie à Nantes — cabinet ostéopathique, approche chaleureuse, typographie Lora en empattement.",
  "impact-265": "Atelier de broderie de soie de luxe à Lyon — broderie à la main pour mariages, typographie Cormorant ultra-délicate.",
  "impact-266": "Lieu d'événement premium — privatisation et réceptions, identité élégante avec les polices Marcellus et Raleway.",
  "impact-267": "Studio d'artiste tatoueur — illustration, style géométrique, portraits, typographie Abril Fatface en gras, éditorial.",
  "impact-268": "Jardinier paysagiste en Île-de-France — jardins contemporains, typographies Crimson Pro et Tenor Sans, style naturel.",
  "impact-269": "Boulangerie artisanale à Bordeaux — pains et viennoiseries, 2007–2026, typographie Zilla Slab, ton éditorial chaleureux.",
  "impact-270": "Studio de tatouage Nature and feather à Lille — tatouage nature, identité délicate en Playfair Display.",
  "impact-271": "Paysagiste alsacien — jardins alsaciens et contemporains, 2003–2026, SARL Reinhardt, typographie Vollkorn.",
  "impact-272": "Physiothérapie pédiatrique à Bordeaux — kinésithérapie pédiatrique, typographie Merriweather bienveillante.",
  "impact-273": "Cabinet dentaire à Strasbourg — soins dentaires, chirurgie, autorité professionnelle avec Libre Baskerville.",
  "impact-274": "Médecin généraliste à Lyon 3e — suivi personnalisé, téléconsultation, secteur 1, typographies Lora et Nunito Sans, vert sauge et prune.",
  "impact-275": "Avocate en droit de la famille à Marseille — divorce, succession, héritage, typographies Playfair Display et Raleway, marine et or.",
  "impact-276": "Coach sportif et nutrition à Bordeaux — perte de poids, prise de masse, performance, typographie Barlow Condensed, noir et orange.",
  "impact-277": "Électricien certifié : installation, rénovation, mise aux normes NFC 15-100, domotique et urgences.",
  "impact-278": "Site d'un plombier-chauffagiste à Toulouse, présentant les services de rénovation de salle de bain, d'installation de chaudières et d'interventions d'urgence 24 h/7 j. Typographie Montserrat, palette rouge brique et beige.",
  "impact-279": "Site d'un ostéopathe D.O. à Lyon 6e, quartier Brotteaux, proposant des soins pour les douleurs, les nourrissons et les sportifs. Typographies Cormorant Garamond, palette vert forêt et terracotta.",
  "impact-280": "Site d'une wedding planner à Strasbourg, présentant une organisation complète d'événements et une décoration florale sur mesure. Typographies Cormorant Garamond, palette rose poudré et vert sauge.",
  "impact-281": "Maison de réception et de mariage : salles, prestations et visite.",
  "impact-282": "Boulangerie artisanale à Lille Vieux-Bourg — pain au levain, viennoiseries. Libre Baskerville, brun / blé doré.",
  "impact-283": "Cabinet de kinésithérapie à Montpellier Antigone — rééducation, balnéo, neurologie. Merriweather + Inter, bleu méditerranéen.",
  "impact-284": "Chirurgien-dentiste : implantologie, alignement invisible et esthétique du sourire.",
  "impact-285": "Médecin généraliste & médecine du voyage Nantes — vaccination, pathologies chroniques. Spectral, vert émeraude / saumon.",
  "impact-286": "Avocate en droit du travail : licenciement, harcèlement, rupture conventionnelle — consultation urgente.",
  "impact-287": "Coach bien-être et remise en forme à Nice Promenade, proposant yoga, course en plein air et nutrition méditerranéenne. Police : Nunito, couleurs bleu azur et corail.",
  "impact-288": "Électricien artisan à Nantes, spécialisé dans les bornes de recharge IRVE, le solaire photovoltaïque et certifié RGE. Police : Poppins, couleurs bleu nuit et vert électrique.",
  "impact-289": "Expert-comptable à Strasbourg Neudorf, spécialiste du droit local Alsace-Moselle pour les TPE et PME. Police : Libre Baskerville, couleurs bleu Rhin et rouge.",
  "impact-290": "Plombier-chauffagiste RGE : plomberie, sanitaires, pompes à chaleur et chauffe-eau solaires.",
  "impact-291": "Ostéopathe D.O. à Strasbourg Orangerie, pratiquant les approches structurelles, viscérales, crâniennes et pédiatriques. Police : Playfair Display, couleurs terracotta et gris bleu.",
  "impact-292": "Burger artisanal à Paris 9e, proposant des steaks faits maison, des frites fraîches et la livraison. Police : Bebas Neue, couleurs noir et jaune moutarde.",
  "impact-293": "Pizzeria napolitaine à Lyon Presqu'île, cuisinée au four à bois avec une pâte fermentée 72 h et livraison en 30 minutes. Police : Cormorant Garamond, couleurs rouge et ivoire.",
  "impact-294": "Kebab et grill méditerranéen : carte, viande halal certifiée, click and collect.",
  "impact-295": "Restauration rapide asiatique dans le 13e arrondissement de Paris – wok, sushi, ramen. Police Noto Serif JP, couleur rouge laque / or.",
  "impact-296": "Tacos et burritos mexicains à Bordeaux, quartier Victoire – recettes d’Oaxaca, sauces maison. Police Oswald, couleur orange / vert avocat.",
  "impact-297": "Médecin généraliste à Toulouse, quartier Capitole – médecine sportive, prévention, téléconsultation. Police Spectral, couleur violet / or.",
  "impact-298": "Chirurgien-dentiste à Montpellier, quartier Antigone – implantologie, orthodontie invisible. Police EB Garamond, couleur turquoise / blanc.",
  "impact-299": "Kinésithérapeute du sport Lyon Confluence — athlètes, rééducation post-op, dry needling. Barlow Condensed, bleu / orange.",
  "impact-300": "Ostéopathie périnatale et pédiatrique : nourrissons, femmes enceintes, post-partum.",
  "impact-301": "Avocat droit des affaires Bordeaux — M&A, startups, RGPD. Cormorant Garamond, ardoise / or.",
  "impact-302": "Expert-comptable pour indépendants et e-commerce : tarifs, dématérialisation et reporting mensuel.",
  "impact-303": "Coach sportif à Paris Est - transformation physique, nutrition, suivi d’application. Poppins, noir / vert néon.",
  "impact-304": "Plombier-chauffagiste à Paris - urgences 24 h/7 j, pompes à chaleur, rénovation. Montserrat, rouge / blanc.",
  "impact-305": "Électricien tertiaire à Bordeaux - domotique, smart home et alarmes. Exo 2, bleu nuit / lime.",
  "impact-306": "Boulangerie-pâtisserie à Montpellier - pains spéciaux, brunch, commandes pour événements. Libre Baskerville, ocre / vert.",
  "impact-307": "Organisation de mariages intimistes : cérémonies laïques, décoration florale et formules.",
  "impact-308": "Marque de mode upcycling à Bordeaux, proposant des collections éco-responsables, des ateliers DIY et des pièces uniques. Typographie Josefin Sans, couleurs noir et terre cuite.",
  "impact-309": "Studio de tatouage fineline et aquarelle : réalisations, artistes et prise de rendez-vous.",
  "impact-310": "Paysagiste méditerranéen à Montpellier, mise en avant d'espèces locales, systèmes d'irrigation et terrasses. Typographie Fraunces, couleurs olive et sable.",
  "impact-311": "Garage indépendant premium proposant révision, freinage, diagnostic et prise de rendez-vous. Bandeau atelier sombre avec animations au défilement.",
  "impact-312": "Garage automobile au design clair et minimaliste, présentant services, tarifs transparents et prise de rendez-vous. Interface épurée.",
  "impact-313": "Plombier-chauffagiste disponible 24 h/24 et 7 j/7 pour dépannages, fuites et pompes à chaleur. Accent rouge d'urgence, bandeau sombre.",
  "impact-314": "Plombier moderne au design clair, offrant installation, rénovation de salle de bain, chauffage et devis gratuit.",
  "impact-315": "Service de ménage à domicile : prestations, formules, avis et réservation en ligne.",
  "impact-316": "Nettoyage de bureaux et locaux B2B avec identité corporate bleu marine et or, contrats, entretien régulier et références clients.",
  "impact-317": "Société de ménage vibrante et moderne, proposant prestations à domicile, réservation en ligne et garanties.",
  "impact-318": "Nettoyage spécialisé après sinistre, fin de chantier ou désinfection, avec un ton technique et rassurant.",
  "impact-319": "Nettoyage écologique à domicile utilisant des produits naturels, avec un design minimaliste et un engagement environnemental.",
  "impact-321": "Page unique d'événement corporate/tech avec grand bandeau, compte à rebours, programme, line-up et bouton d'action d'inscription.",
  "impact-322": "Vitrine d'agence événementielle premium présentant un portfolio d'événements, services corporate et musical, ainsi que des références.",
  "impact-324": "Billetterie e-commerce d'événement musical avec catalogue de billets, catégories VIP et early-bird, panier et processus de paiement.",
  "impact-325": "Billetterie e-commerce pour séminaires et conférences B2B, proposant inscriptions, forfaits, panier et un style clair corporate.",
  "impact-326": "Étude notariale premium détaillant ses domaines d'intervention en balancier ArcSwap, émoluments réglementés, avec une esthétique ivoire et laiton.",
  "impact-327": "Cuisiniste et agence d'agencement sur mesure, chaque projet se déploie du plan à la pièce grâce à ExpandFrame, devis ferme et méthode en quatre étapes.",
  "impact-328": "Pompes funèbres et prévoyance avec HeldSwap au rythme le plus lent du kit, habilitation préfectorale, devis-type réglementé et ton sobre.",
  "impact-329": "Déménageur professionnel proposant des formules coupées net et remontées en HardCutRebuild, bandeau typographique sans photo et registre des transporteurs.",
  "impact-330": "Pharmacie et parapharmacie avec rayonnage déployé rayon par rayon en MosaicPush, click & collect d'ordonnances, vaccination et couleur vert officinal.",
  "impact-331": "Opticien 2e variante — les montures se balancent en ArcSwap devant le visage, 100 % Santé, examen de vue, tiers payant.",
  "impact-332": "Serrurier 2e variante, sécurité à froid — le blindage se matérialise en GhostSolid, certifications A2P, devis ferme, sans photo.",
  "impact-333": "Notaire 2e variante, urbaine et sombre — les clauses s'assemblent en WordFlight, émoluments réglementés, projet d'acte commenté.",
  "impact-334": "Cuisiniste 2e variante, studio-showroom — les façades descendent en PanelDrop, atelier conception 2 h, devis ferme, pose décennale.",
  "impact-335": "Pompes funèbres 2e variante, côtière et lumineuse — les bandeaux s'élèvent en PanelRise, habilitation préfectorale, devis-type.",
  "impact-336": "Pharmacie 2e variante — le parcours de l'ordonnance en StickyProgress épinglé, préparatoire, vaccination, tiers payant.",
  "impact-337": "Courtier en assurances — les garanties s'assemblent en ComposeIn, ORIAS/ACPR, étude comparative 48 h, gestion de sinistre.",
  "impact-338": "Courtier risques d'entreprise — la grille de risques en BentoCascade, cartographie, place de marché, cellule sinistres.",
  "impact-339": "Audioprothésiste — le son en halo ParticleOrb, bilan offert, essai 30 jours, 100 % Santé classe I d'abord.",
  "impact-340": "Centre auditif 2e variante, technologique — les mots reviennent en WordFlight, mesure in-vivo, cabine d'environnements, essai 30 j.",
  "impact-341": "Auto-école — la trajectoire se resserre en TrackingCollapse, agrément préfectoral, taux affichés, CPF et permis à 1 €.",
  "impact-342": "Auto-école : code intensif, permis B, conduite accompagnée et inscription en ligne.",
  "impact-343": "Pressing — le propre révélé en WipeReveal, aquanettoyage zéro perchlo, fiche de soin par pièce, 24 h chrono.",
  "impact-344": "Pressing 2e variante, écologique — l'avant/après en InvertSweep au défilement, aquanettoyage Écolabel, collecte à vélo.",
  "impact-345": "Boucherie-charcuterie des halles — la pièce posée en HeldSwap, élevages nommés, maturation visible, charcuterie maison.",
  "impact-346": "Fromager-affineur — l'étal arrive en MosaicPush, cave d'affinage sur place, AOP en direct des fermes, plateaux composés.",
  "impact-347": "Centre de formation Qualiopi — le programme se déroule en LineScroll, TOSA/LILATE, CPF et OPCO, taux publiés.",
  "impact-348": "Centre de reconversion Qualiopi — les modules tombent en BentoCascade, titres RNCP, ateliers réels, insertion publiée.",
  "impact-349": "Contrôle technique automobile : prestations, déroulé, engagements et rendez-vous.",
  "impact-350": "Contrôle technique automobile, 2e variante : créneaux du soir, rapport expliqué et espace enfants.",
  "impact-351": "La toiture est déposée puis remontée avec HardCutRebuild, en ardoise d'Anjou, garantie décennale Qualibat et bâchage en 24 h.",
  "impact-352": "Le toit s'approche en ScrollGrow, sur un bâti ancien normand, avec dossiers ABF et carnet de toiture.",
  "impact-353": "Les blocs s'assemblent en ComposeIn, avec agrément PMI, pédagogie du dehors, repas bio sur place et CMG simulé.",
  "impact-354": "La carte grandit en ScrollGrow, avec PSU CAF, gestion parentale, équipe stable et inclusion.",
  "impact-355": "Les bandeaux s'élèvent en PanelRise, conventionnés CPAM, tournées 7 j/7 et dossier de soins partagé.",
  "impact-356": "La tournée se compose en ComposeIn, avec secrétariat humain, application pour les familles et DU plaies.",
  "impact-357": "Le résultat se précise en TrackingCollapse, certifié COFRAC ISO 15189, avec résultats le jour même et biologistes joignables.",
  "impact-358": "Laboratoire de biologie médicale : sites de prélèvement, navette réfrigérée et résultats commentés.",
  "impact-359": "Location de matériel de chantier : engins, outillage, livraison et devis.",
  "impact-360": "La carte file en PushBlur, tentes montées J-2, vaisselle rendue sale et hotline le soir J.",
  "impact-361": "Peintre décorateur : peintures dépolluantes, enduits à la chaux et papiers peints panoramiques.",
  "impact-362": "L'avant/après bascule en InvertSweep, avec carnet de chantier, forfaits locatifs et délais tenus.",
  "impact-363": "La semelle en MosaicPush, couche par couche, avec plateforme de pression, fabrication au cabinet et conformité Ordre/ADELI.",
  "impact-364": "La foulée en LineMask, pédicurie sans douleur, semelles fines et service à domicile le jeudi.",
  "impact-365": "Le panier posé en HeldSwap, certification AB, vente directe et paniers hebdomadaires sans engagement.",
  "impact-366": "Maraîchage biologique en AMAP : paniers, saisons, contrats et marché.",
  "impact-367": "Le halo ParticleOrb respire, suivi complet conventionné, PRADO à domicile et gynécologue de prévention.",
  "impact-368": "Bandeaux en PanelRise, créneaux du soir, urgences allaitement J+0 et dossier partagé.",
  "impact-369": "Le portail s'ouvre en PortalZoom, 220 couverts, 12 chambres, ERP contrôlé et un seul événement à la fois.",
  "impact-370": "Le plan devient la salle en ExpandFrame, 600 m² sous verrière, technique intégrée et régie incluse.",
  "impact-371": "Sécurité privée : gardiennage, rondes, événementiel et télésurveillance — société agréée CNAPS.",
  "impact-372": "Sécurité privée 2e variante, commerces et résidentiel — la vigilance se resserre en TrackingCollapse, CNAPS, agents salariés.",
  "impact-373": "VTC premium — la course coupée nette en HardCutRebuild, REVTC, prix fermes, suivi des vols, mise à disposition.",
  "impact-374": "VTC du quotidien et transport médical assis conventionné : trajets, abonnements et réservation.",
  "impact-375": "Vitrier-miroitier — le filé net/flou en PushBlur, urgence 7j/7 au barème normal, atelier de façonnage sur place.",
  "impact-376": "Miroiterie d'agencement 2e variante — la lumière ligne à ligne en LineScroll, verrières, garde-corps calculés, 3D avant signature.",
  "impact-377": "École de musiques actuelles : guitare, batterie, chant, MAO — cours individuels et ateliers.",
  "impact-378": "Gestion de patrimoine 2e variante — le parcours patrimonial en StickyProgress épinglé, CIF/AMF, architecture ouverte, honoraires écrits.",
  "impact-379": "Ébéniste d'art 2e variante — la pièce bascule en ArcSwap, assemblages traditionnels, restauration à la colle d'os, MOF régional.",
  "impact-380": "Brasserie artisanale — la mousse monte en PanelRise, quatre permanentes, non filtrée, taproom et fûts CHR.",
  "impact-381": "Caviste indépendant — la bouteille posée en HeldSwap, 400 références goûtées, achats en direct au domaine, dégustations mensuelles.",
  "impact-382": "Cabinet de recrutement et chasse de têtes : prestations, méthode et garantie d'un an.",
  "impact-383": "Toiletteur & pension familiale — la carte file en PushBlur, un animal à la fois, sans contention, pension déclarée DDPP.",
};
