/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "estates": "Les biens",
    "concierge": "Conciergerie",
    "client_login": "Espace_client",
    "request_membership": "Demander_une_adhésion",
    "assets managed": "Actifs sous gestion",
    "global offices": "Bureaux dans le monde",
    "comprehensive": "Maîtrise",
    "asset control.": "complète du patrimoine.",
    "asset acquisition": "Acquisition d'actifs",
    "lifestyle management": "Gestion du quotidien",
    "family office support": "Accompagnement de family office",
    "absolute discretion.": "la discrétion absolue.",
    "confidential": "CONFIDENTIEL",
    "operational rule": "RÈGLE DE FONCTIONNEMENT",
    "information security": "SÉCURITÉ DE L'INFORMATION",
    "salon privé // london": "SALON PRIVÉ // LONDRES",
    "private": "Portefeuille",
    "inventory.": "confidentiel.",
    "restricted access listings // required nda": "Biens à accès restreint // accord de confidentialité requis",
    "request_nda": "Demander_l_accord",
    "inquire_now": "Nous_écrire",
    "billionaire's row, nyc": "Billionaire's Row, New York",
    "bel air, ca": "Bel Air, Californie",
    "trusted by": "La confiance de",
    "discerning leaders.": "dirigeants exigeants.",
    "family office principal": "Dirigeant de family office",
    "24/7 dedicated concierge for travel, security, and global event access.": "Concierge dédié 24/7 pour les voyages, la sécurité et l'accès aux événements mondiaux.",
    "are your lifestyle concierge services globally active?": "Vos services de conciergerie de style de vie sont-ils actifs à l'échelle mondiale ?",
    "asked questions.": "Questions posées.",
    "at skyline concierge group, we operate at the unique intersection of wealth infrastructure, private security, and lifestyle orchestration.": "Chez Skyline Concierge Group, nous opérons à l'intersection unique de l'infrastructure de richesse, de la sécurité privée et de l'orchestration de style de vie.",
    "client endorsements": "Témoignages de clients",
    "client login": "Connexion Client",
    "client satisfaction": "Satisfaction client",
    "confidential brokerage and lifestyle management for the world's most discerning families. from off-market penthouses to global asset security.": "Courtage confidentiel et gestion de style de vie pour les familles les plus exigeantes au monde. Des penthouses hors marché à la sécurité des actifs mondiaux.",
    "confidential wealth transition and lifestyle infrastructure for high-net-worth families.": "Transmission de patrimoine et intendance de vie, en toute confidentialité, pour les grandes fortunes familiales.",
    "contact our private desk for membership inquiries or asset advisory. all transmissions are encrypted and treated with absolute confidentiality.": "Contactez notre bureau privé pour toute demande d'adhésion ou de conseil patrimonial. Tous les échanges sont chiffrés et traités en confidentialité absolue.",
    "discretion is their currency. skyline has become our trusted advisor for all non-financial infrastructure and global assets.": "La discrétion est leur monnaie. Skyline est devenu notre conseiller de confiance pour toute infrastructure non financière et les actifs mondiaux.",
    "explore capability": "Explorer les capacités",
    "how do i obtain membership?": "Comment puis-je obtenir un abonnement ?",
    "inquire now": "Renseignez-vous maintenant",
    "is an nda required for private listings?": "Un NDA est-il requis pour les annonces privées ?",
    "new york": "New York",
    "off-market access to the world's most exclusive real estate, yachts, and private aviation.": "Un accès hors marché à l'immobilier, aux yachts et à l'aviation privée les plus rares.",
    "off-market deals": "Off-Market Deals",
    "our creed": "Notre credo",
    "our mission is to create a seamless operational environment for the world's most discerning individuals. by managing the complexities of luxury asset coordination, physical security detail, and private travel logistics, we restore the ultimate luxury: absolute freedom.": "Notre mission : offrir un environnement sans friction aux personnes les plus exigeantes. En prenant en charge la coordination des actifs, la sécurité rapprochée et la logistique des voyages privés, nous rendons le luxe absolu — la liberté.",
    "our network spans across 12 strategic global hubs, providing seamless lifestyle continuity and asset security for clients in transit.": "Notre réseau s'étend sur 12 hubs stratégiques mondiaux, offrant une continuité de style de vie sans faille et une sécurité des actifs pour les clients en transit.",
    "request membership": "Demander une adhésion",
    "request nda": "Demander un NDA",
    "request private membership": "Demander l'adhésion privée",
    "secure": "Sécurisé",
    "secure email": "EMAIL SÉCURISÉ",
    "secure encryption v4.2": "CRYPTAGE SÉCURISÉ V4.2",
    "secure node active": "Nœud sécurisé actif",
    "secure transmission": "TRANSMISSION SÉCURISÉE",
    "secure transmission received": "TRANSMISSION SÉCURISÉE REÇUE",
    "secure voice": "VOIX SÉCURISÉE",
    "skyline managed the off-market acquisition of our alpine estate and the security logistics for our family office within 48 hours. absolute excellence.": "Skyline a géré l'acquisition hors marché de notre domaine alpin et la logistique de sécurité pour notre bureau familial en 48 heures. Excellence absolue.",
    "the ecosystem": "L'écosystème",
    "the glass pavilion": "Le Pavillon de Verre",
    "the intersection of high-net-worth wealth transition and absolute lifestyle sovereignty. confidential by design.": "Au croisement de la transmission des grands patrimoines et de la souveraineté du mode de vie. Confidentiel par construction.",
    "the lifestyle desk is truly outstanding. from securing last-minute yacht charters to private aviation coordination, their response time is unparalleled.": "Le bureau de style de vie est vraiment exceptionnel. De la sécurisation de charters de yacht de dernière minute à la coordination de l'aviation privée, leur temps de réponse est inégalé.",
    "the obsidian penthouse": "Le Penthouse Obsidienne",
    "the philosophy of": "La philosophie de",
    "the vault": "Le Coffre",
    "view private listings": "Voir les annonces privées",
    "what private assets do you handle?": "Quels actifs privés gérez-vous ?",
    "without borders.": "Sans frontières.",
  },
  es: {
    "estates": "Los inmuebles",
    "concierge": "Conserjería",
    "client_login": "Área_de_cliente",
    "request_membership": "Solicitar_adhesión",
    "assets managed": "Activos gestionados",
    "global offices": "Oficinas en el mundo",
    "comprehensive": "Control",
    "asset control.": "completo del patrimonio.",
    "asset acquisition": "Adquisición de activos",
    "lifestyle management": "Gestión del día a día",
    "family office support": "Acompañamiento de family office",
    "absolute discretion.": "la discreción absoluta.",
    "confidential": "CONFIDENCIAL",
    "operational rule": "REGLA DE FUNCIONAMIENTO",
    "information security": "SEGURIDAD DE LA INFORMACIÓN",
    "salon privé // london": "SALÓN PRIVADO // LONDRES",
    "private": "Cartera",
    "inventory.": "confidencial.",
    "restricted access listings // required nda": "Inmuebles de acceso restringido // acuerdo de confidencialidad obligatorio",
    "request_nda": "Solicitar_acuerdo",
    "inquire_now": "Escríbanos",
    "billionaire's row, nyc": "Billionaire's Row, Nueva York",
    "bel air, ca": "Bel Air, California",
    "trusted by": "La confianza de",
    "discerning leaders.": "líderes exigentes.",
    "family office principal": "Director de family office",
    "24/7 dedicated concierge for travel, security, and global event access.": "Conserje dedicado 24/7 para viajes, seguridad y acceso a eventos globales.",
    "are your lifestyle concierge services globally active?": "¿Sus servicios de conserjería de estilo de vida están activos a nivel mundial?",
    "asked questions.": "Preguntas frecuentes.",
    "at skyline concierge group, we operate at the unique intersection of wealth infrastructure, private security, and lifestyle orchestration.": "En Skyline Concierge Group, operamos en la intersección única de la infraestructura de riqueza, la seguridad privada y la orquestación del estilo de vida.",
    "client endorsements": "Recomendaciones de clientes",
    "client login": "Inicio de sesión del cliente",
    "client satisfaction": "Satisfacción del cliente",
    "confidential brokerage and lifestyle management for the world's most discerning families. from off-market penthouses to global asset security.": "Corretaje confidencial y gestión del estilo de vida para las familias más exigentes del mundo. Desde áticos fuera del mercado hasta seguridad de activos globales.",
    "confidential wealth transition and lifestyle infrastructure for high-net-worth families.": "Transmisión de patrimonio e intendencia de vida, con total confidencialidad, para grandes fortunas familiares.",
    "contact our private desk for membership inquiries or asset advisory. all transmissions are encrypted and treated with absolute confidentiality.": "Contacte con nuestra mesa privada para solicitudes de membresía o asesoramiento patrimonial. Todos los intercambios están cifrados y se tratan con confidencialidad absoluta.",
    "discretion is their currency. skyline has become our trusted advisor for all non-financial infrastructure and global assets.": "La discreción es su moneda. Skyline se ha convertido en nuestro asesor de confianza para toda infraestructura no financiera y activos globales.",
    "explore capability": "Explorar capacidades",
    "how do i obtain membership?": "¿Cómo obtengo la membresía?",
    "inquire now": "Consulta ahora",
    "is an nda required for private listings?": "¿Se requiere un NDA para listados privados?",
    "new york": "Nueva York",
    "off-market access to the world's most exclusive real estate, yachts, and private aviation.": "Acceso fuera de mercado al inmobiliario, los yates y la aviación privada más exclusivos.",
    "off-market deals": "Ofertas fuera del mercado",
    "our creed": "Nuestro credo",
    "our mission is to create a seamless operational environment for the world's most discerning individuals. by managing the complexities of luxury asset coordination, physical security detail, and private travel logistics, we restore the ultimate luxury: absolute freedom.": "Nuestra misión: ofrecer un entorno sin fricciones a las personas más exigentes. Al asumir la coordinación de activos, la seguridad personal y la logística de los viajes privados, devolvemos el lujo absoluto: la libertad.",
    "our network spans across 12 strategic global hubs, providing seamless lifestyle continuity and asset security for clients in transit.": "Nuestra red abarca 12 centros estratégicos globales, proporcionando continuidad de estilo de vida sin interrupciones y seguridad de activos para los clientes en tránsito.",
    "request membership": "Solicitar membresía",
    "request nda": "Solicitar NDA",
    "request private membership": "Solicitar la membresía privada",
    "secure": "Seguro",
    "secure email": "EMAIL SEGURO",
    "secure encryption v4.2": "ENCRIPTACIÓN SEGURA V4.2",
    "secure node active": "Nodo seguro activo",
    "secure transmission": "TRANSMISIÓN SEGURA",
    "secure transmission received": "TRANSMISIÓN SEGURA RECIBIDA",
    "secure voice": "VOZ SEGURA",
    "skyline managed the off-market acquisition of our alpine estate and the security logistics for our family office within 48 hours. absolute excellence.": "Skyline gestionó la adquisición fuera del mercado de nuestra propiedad alpina y la logística de seguridad para nuestra oficina familiar en 48 horas. Excelencia absoluta.",
    "the ecosystem": "El ecosistema",
    "the glass pavilion": "El Pabellón de Cristal",
    "the intersection of high-net-worth wealth transition and absolute lifestyle sovereignty. confidential by design.": "En el cruce de la transmisión de grandes patrimonios y la soberanía del modo de vida. Confidencial por construcción.",
    "the lifestyle desk is truly outstanding. from securing last-minute yacht charters to private aviation coordination, their response time is unparalleled.": "El servicio de estilo de vida es verdaderamente excepcional. Desde asegurar chárteres de yates de última hora hasta la coordinación de aviación privada, su tiempo de respuesta es inigualable.",
    "the obsidian penthouse": "El Ático Obsidiana",
    "the philosophy of": "La filosofía de",
    "the vault": "La Bóveda",
    "view private listings": "Ver listados privados",
    "what private assets do you handle?": "¿Qué activos privados manejan?",
    "without borders.": "Sin fronteras.",
  },
  de: {
    "estates": "Die Objekte",
    "concierge": "Concierge-Service",
    "client_login": "Kundenbereich",
    "request_membership": "Mitgliedschaft_anfragen",
    "assets managed": "Verwaltete Vermögenswerte",
    "global offices": "Büros weltweit",
    "comprehensive": "Umfassende",
    "asset control.": "Vermögenssteuerung.",
    "asset acquisition": "Vermögenserwerb",
    "lifestyle management": "Lifestyle-Management",
    "family office support": "Family-Office-Begleitung",
    "absolute discretion.": "der absoluten Diskretion.",
    "confidential": "VERTRAULICH",
    "operational rule": "BETRIEBSREGEL",
    "information security": "INFORMATIONSSICHERHEIT",
    "salon privé // london": "SALON PRIVÉ // LONDON",
    "private": "Privates",
    "inventory.": "Portfolio.",
    "restricted access listings // required nda": "Objekte mit beschränktem Zugang // Vertraulichkeitsvereinbarung erforderlich",
    "request_nda": "Vereinbarung_anfragen",
    "inquire_now": "Anfrage_senden",
    "billionaire's row, nyc": "Billionaire's Row, New York",
    "bel air, ca": "Bel Air, Kalifornien",
    "trusted by": "Vertraut von",
    "discerning leaders.": "anspruchsvollen Führungskräften.",
    "family office principal": "Leiter eines Family Office",
    "24/7 dedicated concierge for travel, security, and global event access.": "24/7 dedizierter Concierge für Reisen, Sicherheit und Zugang zu globalen Veranstaltungen.",
    "are your lifestyle concierge services globally active?": "Sind Ihre Lifestyle-Concierge-Services weltweit aktiv?",
    "asked questions.": "Häufig gestellte Fragen.",
    "at skyline concierge group, we operate at the unique intersection of wealth infrastructure, private security, and lifestyle orchestration.": "Bei Skyline Concierge Group arbeiten wir an der einzigartigen Schnittstelle von Vermögensinfrastruktur, privater Sicherheit und Lifestyle-Orchestrierung.",
    "client endorsements": "Kundenempfehlungen",
    "client login": "Kundenanmeldung",
    "client satisfaction": "Kundenzufriedenheit",
    "confidential brokerage and lifestyle management for the world's most discerning families. from off-market penthouses to global asset security.": "Vertrauliche Vermittlung und Lifestyle-Management für die anspruchsvollsten Familien der Welt. Von Off-Market-Penthäusern bis hin zur globalen Vermögenssicherung.",
    "confidential wealth transition and lifestyle infrastructure for high-net-worth families.": "Vermögensübergang und Lebensinfrastruktur, streng vertraulich, für vermögende Familien.",
    "contact our private desk for membership inquiries or asset advisory. all transmissions are encrypted and treated with absolute confidentiality.": "Wenden Sie sich an unser privates Büro für Mitgliedschaft oder Vermögensberatung. Alle Übermittlungen sind verschlüsselt und werden absolut vertraulich behandelt.",
    "discretion is their currency. skyline has become our trusted advisor for all non-financial infrastructure and global assets.": "Diskretion ist ihre Währung. Skyline ist unser vertrauenswürdiger Berater für alle nicht-finanziellen Infrastrukturen und globalen Vermögenswerte geworden.",
    "explore capability": "Fähigkeiten erkunden",
    "how do i obtain membership?": "Wie erhalte ich eine Mitgliedschaft?",
    "inquire now": "Jetzt anfragen",
    "is an nda required for private listings?": "Ist eine NDA für private Angebote erforderlich?",
    "new york": "New York",
    "off-market access to the world's most exclusive real estate, yachts, and private aviation.": "Off-Market-Zugang zu den exklusivsten Immobilien, Yachten und Privatflugzeugen.",
    "off-market deals": "Off-Market-Deals",
    "our creed": "Unser Credo",
    "our mission is to create a seamless operational environment for the world's most discerning individuals. by managing the complexities of luxury asset coordination, physical security detail, and private travel logistics, we restore the ultimate luxury: absolute freedom.": "Unser Auftrag: ein reibungsloses Umfeld für die anspruchsvollsten Menschen. Indem wir Vermögenskoordination, Personenschutz und private Reiselogistik übernehmen, geben wir den größten Luxus zurück — die Freiheit.",
    "our network spans across 12 strategic global hubs, providing seamless lifestyle continuity and asset security for clients in transit.": "Unser Netzwerk erstreckt sich über 12 strategische globale Knotenpunkte und bietet nahtlose Lebensstilkontinuität und Vermögenssicherheit für Kunden in Transit.",
    "request membership": "Mitgliedschaft anfordern",
    "request nda": "NDA anfordern",
    "request private membership": "Private Mitgliedschaft anfragen",
    "secure": "Sicher",
    "secure email": "SICHERE E-MAIL",
    "secure encryption v4.2": "SICHERE VERSCHLÜSSELUNG V4.2",
    "secure node active": "Sicherer Knoten aktiv",
    "secure transmission": "SICHERE ÜBERTRAGUNG",
    "secure transmission received": "SICHERE ÜBERTRAGUNG EMPFANGEN",
    "secure voice": "SICHERE STIMME",
    "skyline managed the off-market acquisition of our alpine estate and the security logistics for our family office within 48 hours. absolute excellence.": "Skyline verwaltete den Off-Market-Erwerb unseres Alpenanwesens und die Sicherheitslogistik für unser Family Office innerhalb von 48 Stunden. Absolute Exzellenz.",
    "the ecosystem": "Das Ökosystem",
    "the glass pavilion": "Der Glaspavillon",
    "the intersection of high-net-worth wealth transition and absolute lifestyle sovereignty. confidential by design.": "An der Schnittstelle von Vermögensübergang und souveräner Lebensführung. Vertraulich von Grund auf.",
    "the lifestyle desk is truly outstanding. from securing last-minute yacht charters to private aviation coordination, their response time is unparalleled.": "Der Lifestyle-Desk ist wirklich herausragend. Von der Sicherstellung von Last-Minute-Yachtchartern bis zur Koordination der privaten Luftfahrt ist ihre Reaktionszeit unübertroffen.",
    "the obsidian penthouse": "Die Obsidian-Penthouse",
    "the philosophy of": "Die Philosophie von",
    "the vault": "Der Tresor",
    "view private listings": "Private Angebote ansehen",
    "what private assets do you handle?": "Welche privaten Vermögenswerte verwalten Sie?",
    "without borders.": "Ohne Grenzen.",
  },
  pt: {
    "estates": "Os imóveis",
    "concierge": "Concierge",
    "client_login": "Área_de_cliente",
    "request_membership": "Pedir_adesão",
    "assets managed": "Ativos sob gestão",
    "global offices": "Escritórios no mundo",
    "comprehensive": "Controlo",
    "asset control.": "completo do património.",
    "asset acquisition": "Aquisição de ativos",
    "lifestyle management": "Gestão do quotidiano",
    "family office support": "Acompanhamento de family office",
    "absolute discretion.": "da discrição absoluta.",
    "confidential": "CONFIDENCIAL",
    "operational rule": "REGRA DE FUNCIONAMENTO",
    "information security": "SEGURANÇA DA INFORMAÇÃO",
    "salon privé // london": "SALÃO PRIVADO // LONDRES",
    "private": "Carteira",
    "inventory.": "confidencial.",
    "restricted access listings // required nda": "Imóveis de acesso restrito // acordo de confidencialidade obrigatório",
    "request_nda": "Pedir_acordo",
    "inquire_now": "Escreva-nos",
    "billionaire's row, nyc": "Billionaire's Row, Nova Iorque",
    "bel air, ca": "Bel Air, Califórnia",
    "trusted by": "A confiança de",
    "discerning leaders.": "líderes exigentes.",
    "family office principal": "Diretor de family office",
    "24/7 dedicated concierge for travel, security, and global event access.": "Concierge dedicado 24/7 para viagens, segurança e acesso a eventos globais.",
    "are your lifestyle concierge services globally active?": "Os seus serviços de concierge de estilo de vida estão ativos globalmente?",
    "asked questions.": "Perguntas Frequentes.",
    "at skyline concierge group, we operate at the unique intersection of wealth infrastructure, private security, and lifestyle orchestration.": "No Skyline Concierge Group, operamos na interseção única da infraestrutura de riqueza, segurança privada e orquestração de estilo de vida.",
    "client endorsements": "Endossos de clientes",
    "client login": "Login do Cliente",
    "client satisfaction": "Satisfação do Cliente",
    "confidential brokerage and lifestyle management for the world's most discerning families. from off-market penthouses to global asset security.": "Corretagem confidencial e gestão de estilo de vida para as famílias mais exigentes do mundo. Desde penthouses fora do mercado até segurança de ativos globais.",
    "confidential wealth transition and lifestyle infrastructure for high-net-worth families.": "Transmissão de património e intendência de vida, com total confidencialidade, para grandes fortunas familiares.",
    "contact our private desk for membership inquiries or asset advisory. all transmissions are encrypted and treated with absolute confidentiality.": "Contacte a nossa mesa privada para pedidos de adesão ou aconselhamento patrimonial. Todas as trocas são cifradas e tratadas com confidencialidade absoluta.",
    "discretion is their currency. skyline has become our trusted advisor for all non-financial infrastructure and global assets.": "A discrição é a sua moeda. A Skyline tornou-se o nosso consultor de confiança para toda a infraestrutura não financeira e ativos globais.",
    "explore capability": "Explorar capacidades",
    "how do i obtain membership?": "Como posso obter a adesão?",
    "inquire now": "Pergunte agora",
    "is an nda required for private listings?": "É necessário um NDA para listagens privadas?",
    "new york": "Nova Iorque",
    "off-market access to the world's most exclusive real estate, yachts, and private aviation.": "Acesso fora de mercado ao imobiliário, aos iates e à aviação privada mais exclusivos.",
    "off-market deals": "Ofertas Fora do Mercado",
    "our creed": "O nosso credo",
    "our mission is to create a seamless operational environment for the world's most discerning individuals. by managing the complexities of luxury asset coordination, physical security detail, and private travel logistics, we restore the ultimate luxury: absolute freedom.": "A nossa missão: oferecer um ambiente sem atritos às pessoas mais exigentes. Ao assumir a coordenação de ativos, a segurança pessoal e a logística das viagens privadas, devolvemos o luxo absoluto: a liberdade.",
    "our network spans across 12 strategic global hubs, providing seamless lifestyle continuity and asset security for clients in transit.": "A nossa rede abrange 12 centros globais estratégicos, proporcionando continuidade de estilo de vida sem interrupções e segurança de ativos para clientes em trânsito.",
    "request membership": "Solicitar adesão",
    "request nda": "Solicitar NDA",
    "request private membership": "Pedir a adesão privada",
    "secure": "Seguro",
    "secure email": "EMAIL SEGURO",
    "secure encryption v4.2": "CRIPTOGRAFIA SEGURA V4.2",
    "secure node active": "Nó seguro ativo",
    "secure transmission": "TRANSMISSÃO SEGURA",
    "secure transmission received": "TRANSMISSÃO SEGURA RECEBIDA",
    "secure voice": "VOZ SEGURA",
    "skyline managed the off-market acquisition of our alpine estate and the security logistics for our family office within 48 hours. absolute excellence.": "A Skyline geriu a aquisição fora do mercado da nossa propriedade alpina e a logística de segurança para o nosso escritório familiar em 48 horas. Excelência absoluta.",
    "the ecosystem": "O ecossistema",
    "the glass pavilion": "O Pavilhão de Vidro",
    "the intersection of high-net-worth wealth transition and absolute lifestyle sovereignty. confidential by design.": "No cruzamento da transmissão de grandes patrimónios e da soberania do modo de vida. Confidencial por construção.",
    "the lifestyle desk is truly outstanding. from securing last-minute yacht charters to private aviation coordination, their response time is unparalleled.": "O serviço de estilo de vida é verdadeiramente excepcional. Desde garantir charters de iates de última hora até a coordenação de aviação privada, o tempo de resposta deles é incomparável.",
    "the obsidian penthouse": "O Penthouse Obsidiana",
    "the philosophy of": "A filosofia de",
    "the vault": "O Cofre",
    "view private listings": "Ver listas privadas",
    "what private assets do you handle?": "Quais ativos privados você gerencia?",
    "without borders.": "Sem Fronteiras.",
  },
};
