/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "soc2 type ii, iso 27001, and hipaa compliant environments.": "Environnements conformes SOC 2 Type II, ISO 27001 et HIPAA.",
    "start today with 200  €in free credits. no credit card required to explore our ecosystem.": "Commencez aujourd'hui avec 200 € de crédits offerts. Aucune carte bancaire n'est demandée pour explorer.",
    "120+ global regions with <5ms latency to end-users.": "120+ régions mondiales avec une latence <5ms pour les utilisateurs finaux.",
    "24/7 dedicated team": "Équipe dédiée 24/7",
    "aes-256 at rest and tls 1.3 in transit with mtls between services.": "AES-256 au repos, TLS 1.3 en transit, mTLS entre les services.",
    "auto-scaling clusters with built-in service mesh and observability.": "Clusters à mise à l'échelle automatique avec maillage de services intégré et observabilité.",
    "cold start: 0.8ms": "Démarrage à froid : 0,8 ms",
    "create free account": "Créer un compte gratuit",
    "dedicated sre on-call": "SRE dédié en astreinte",
    "deploy your first node": "Déployer votre premier nœud",
    "firecracker microvm isolation for every function and node.": "Isolation par micro-machine virtuelle Firecracker, pour chaque fonction et chaque nœud.",
    "hardened by": "Renforcé par",
    "high-performance cloud infrastructure designed for modern engineering teams. bare metal performance with serverless ease.": "Infrastructure cloud haute performance conçue pour les équipes d'ingénierie modernes. Performance bare metal avec la facilité du sans serveur.",
    "no egress fees. no hidden charges. pay for what you use.": "Aucun frais de sortie. Aucun coût caché. Vous payez ce que vous consommez.",
    "our p99 latency dropped from 380ms to 22ms after onboarding. the edge routing intelligence is genuinely next-level.": "Notre latence p99 est passée de 380ms à 22ms après l'intégration. L'intelligence de routage en périphérie est vraiment de niveau supérieur.",
    "ready to scale": "Prêt à évoluer",
    "s3-compatible, multi-region replication with 11 nines of durability.": "Réplications multi-régions compatibles S3 avec 11 nines de durabilité.",
    "start today with $200 in free credits. no credit card required to explore our ecosystem.": "Commencez aujourd'hui avec 200 $ de crédits gratuits. Aucune carte de crédit requise pour explorer notre écosystème.",
    "the compliance dashboard alone was worth the migration. soc 2 audit prep that used to take weeks now takes hours.": "Le tableau de bord de conformité à lui seul valait la migration. La préparation de l'audit SOC 2 qui prenait des semaines ne prend maintenant que des heures.",
    "the world's fastest cloud platform for building and scaling high-performance applications at the edge.": "La plateforme cloud la plus rapide au monde pour créer et mettre à l'échelle des applications haute performance à la périphérie.",
    "trusted by engineering teams": "Les équipes techniques nous font confiance",
    "up to 10 services": "Jusqu'à 10 services",
    "view cli docs": "Voir la documentation CLI",
    "we migrated 140 microservices in a single weekend with zero downtime. their orchestration layer handled the complexity we were dreading. remarkable.": "Nous avons migré 140 microservices en un seul week-end sans aucun temps d'arrêt. Leur couche d'orchestration a géré la complexité que nous redoutions. Remarquable.",
    "what teams": "Ce que les équipes",
  },
  es: {
    "soc2 type ii, iso 27001, and hipaa compliant environments.": "Entornos conformes a SOC 2 Tipo II, ISO 27001 e HIPAA.",
    "start today with 200  €in free credits. no credit card required to explore our ecosystem.": "Empiece hoy con 200 € de crédito gratis. No se pide tarjeta para explorar.",
    "120+ global regions with <5ms latency to end-users.": "Más de 120 regiones globales con <5ms de latencia para los usuarios finales.",
    "24/7 dedicated team": "Equipo dedicado 24/7",
    "aes-256 at rest and tls 1.3 in transit with mtls between services.": "AES-256 en reposo, TLS 1.3 en tránsito, mTLS entre servicios.",
    "auto-scaling clusters with built-in service mesh and observability.": "Clústeres de escalado automático con malla de servicios integrada y observabilidad.",
    "cold start: 0.8ms": "Arranque en frío: 0,8 ms",
    "create free account": "Crear una cuenta gratuita",
    "dedicated sre on-call": "SRE dedicado de guardia",
    "deploy your first node": "Desplegar su primer nodo",
    "firecracker microvm isolation for every function and node.": "Aislamiento por micromáquina virtual Firecracker, para cada función y cada nodo.",
    "hardened by": "Endurecido por",
    "high-performance cloud infrastructure designed for modern engineering teams. bare metal performance with serverless ease.": "Infraestructura en la nube de alto rendimiento diseñada para equipos de ingeniería modernos. Rendimiento bare metal con la facilidad de lo sin servidor.",
    "no egress fees. no hidden charges. pay for what you use.": "Sin costes de salida. Sin cargos ocultos. Paga lo que usa.",
    "our p99 latency dropped from 380ms to 22ms after onboarding. the edge routing intelligence is genuinely next-level.": "Nuestra latencia p99 bajó de 380ms a 22ms después de la incorporación. La inteligencia de enrutamiento en la frontera es realmente de otro nivel.",
    "ready to scale": "Listo para escalar",
    "s3-compatible, multi-region replication with 11 nines of durability.": "Replicación multirregional compatible con S3 con 11 nueves de durabilidad.",
    "start today with $200 in free credits. no credit card required to explore our ecosystem.": "Comienza hoy con $200 en créditos gratuitos. No se requiere tarjeta de crédito para explorar nuestro ecosistema.",
    "the compliance dashboard alone was worth the migration. soc 2 audit prep that used to take weeks now takes hours.": "El panel de cumplimiento por sí solo valía la migración. La preparación de la auditoría SOC 2 que solía tardar semanas ahora toma horas.",
    "the world's fastest cloud platform for building and scaling high-performance applications at the edge.": "La plataforma en la nube más rápida del mundo para construir y escalar aplicaciones de alto rendimiento en el borde.",
    "trusted by engineering teams": "Los equipos técnicos confían en nosotros",
    "up to 10 services": "Hasta 10 servicios",
    "view cli docs": "Ver documentación de CLI",
    "we migrated 140 microservices in a single weekend with zero downtime. their orchestration layer handled the complexity we were dreading. remarkable.": "Migramos 140 microservicios en un solo fin de semana sin tiempo de inactividad. Su capa de orquestación manejó la complejidad que temíamos. Notable.",
    "what teams": "Lo que los equipos",
  },
  de: {
    "soc2 type ii, iso 27001, and hipaa compliant environments.": "Umgebungen konform zu SOC 2 Typ II, ISO 27001 und HIPAA.",
    "start today with 200  €in free credits. no credit card required to explore our ecosystem.": "Starten Sie heute mit 200 € Startguthaben. Zum Erkunden ist keine Kreditkarte nötig.",
    "120+ global regions with <5ms latency to end-users.": "Über 120 globale Regionen mit <5ms Latenz zu Endbenutzern.",
    "24/7 dedicated team": "24/7 engagiertes Team",
    "aes-256 at rest and tls 1.3 in transit with mtls between services.": "AES-256 im Ruhezustand, TLS 1.3 bei der Übertragung, mTLS zwischen den Diensten.",
    "auto-scaling clusters with built-in service mesh and observability.": "Automatisch skalierbare Cluster mit integriertem Service Mesh und Observierbarkeit.",
    "cold start: 0.8ms": "Kaltstart: 0,8 ms",
    "create free account": "Kostenloses Konto erstellen",
    "dedicated sre on-call": "Dedizierter SRE im Bereitschaftsdienst",
    "deploy your first node": "Ihren ersten Knoten bereitstellen",
    "firecracker microvm isolation for every function and node.": "Isolation per Firecracker-MicroVM für jede Funktion und jeden Knoten.",
    "hardened by": "Gestärkt durch",
    "high-performance cloud infrastructure designed for modern engineering teams. bare metal performance with serverless ease.": "Hochleistungs-Cloud-Infrastruktur, die für moderne Ingenieurteams entwickelt wurde. Bare-Metal-Leistung mit serverloser Einfachheit.",
    "no egress fees. no hidden charges. pay for what you use.": "Keine Egress-Gebühren. Keine versteckten Kosten. Sie zahlen, was Sie nutzen.",
    "our p99 latency dropped from 380ms to 22ms after onboarding. the edge routing intelligence is genuinely next-level.": "Unsere p99-Latenz fiel von 380ms auf 22ms nach der Onboarding. Die Edge-Routing-Intelligenz ist wirklich auf einem nächsten Level.",
    "ready to scale": "Bereit zum Skalieren",
    "s3-compatible, multi-region replication with 11 nines of durability.": "S3-kompatible, Multi-Region-Replikation mit 11 Neunen Haltbarkeit.",
    "start today with $200 in free credits. no credit card required to explore our ecosystem.": "Starten Sie noch heute mit 200 $ in kostenlosen Credits. Keine Kreditkarte erforderlich, um unser Ökosystem zu erkunden.",
    "the compliance dashboard alone was worth the migration. soc 2 audit prep that used to take weeks now takes hours.": "Das Compliance-Dashboard allein war die Migration wert. Die SOC 2-Auditvorbereitung, die früher Wochen dauerte, dauert jetzt Stunden.",
    "the world's fastest cloud platform for building and scaling high-performance applications at the edge.": "Die schnellste Cloud-Plattform der Welt zum Erstellen und Skalieren von Hochleistungsanwendungen am Edge.",
    "trusted by engineering teams": "Entwicklerteams vertrauen uns",
    "up to 10 services": "Bis zu 10 Dienstleistungen",
    "view cli docs": "CLI-Dokumentation anzeigen",
    "we migrated 140 microservices in a single weekend with zero downtime. their orchestration layer handled the complexity we were dreading. remarkable.": "Wir haben 140 Mikrodienste an einem einzigen Wochenende ohne Ausfallzeiten migriert. Ihre Orchestrierungsschicht hat die Komplexität bewältigt, vor der wir uns gefürchtet haben. Bemerkenswert.",
    "what teams": "Was Teams",
  },
  pt: {
    "soc2 type ii, iso 27001, and hipaa compliant environments.": "Ambientes conformes a SOC 2 Tipo II, ISO 27001 e HIPAA.",
    "start today with 200  €in free credits. no credit card required to explore our ecosystem.": "Comece hoje com 200 € de créditos oferecidos. Não é pedido cartão para explorar.",
    "120+ global regions with <5ms latency to end-users.": "Mais de 120 regiões globais com <5ms de latência para os utilizadores finais.",
    "24/7 dedicated team": "Equipe dedicada 24/7",
    "aes-256 at rest and tls 1.3 in transit with mtls between services.": "AES-256 em repouso, TLS 1.3 em trânsito, mTLS entre os serviços.",
    "auto-scaling clusters with built-in service mesh and observability.": "Clusters de escalabilidade automática com malha de serviços integrada e observabilidade.",
    "cold start: 0.8ms": "Arranque a frio: 0,8 ms",
    "create free account": "Criar uma conta gratuita",
    "dedicated sre on-call": "SRE dedicado de plantão",
    "deploy your first node": "Implantar o seu primeiro nó",
    "firecracker microvm isolation for every function and node.": "Isolamento por micromáquina virtual Firecracker, para cada função e cada nó.",
    "hardened by": "Aprimorado por",
    "high-performance cloud infrastructure designed for modern engineering teams. bare metal performance with serverless ease.": "Infraestrutura em nuvem de alto desempenho projetada para equipes de engenharia modernas. Desempenho bare metal com a facilidade do sem servidor.",
    "no egress fees. no hidden charges. pay for what you use.": "Sem custos de saída. Sem encargos ocultos. Paga o que usa.",
    "our p99 latency dropped from 380ms to 22ms after onboarding. the edge routing intelligence is genuinely next-level.": "A nossa latência p99 caiu de 380ms para 22ms após a integração. A inteligência de roteamento de borda é realmente de nível superior.",
    "ready to scale": "Pronto para escalar",
    "s3-compatible, multi-region replication with 11 nines of durability.": "Replicação multi-região compatível com S3 com 11 noves de durabilidade.",
    "start today with $200 in free credits. no credit card required to explore our ecosystem.": "Comece hoje com 200 € em créditos gratuitos. Não é necessário cartão de crédito para explorar o nosso ecossistema.",
    "the compliance dashboard alone was worth the migration. soc 2 audit prep that used to take weeks now takes hours.": "O painel de conformidade por si só valeu a migração. A preparação da auditoria SOC 2 que costumava levar semanas agora leva horas.",
    "the world's fastest cloud platform for building and scaling high-performance applications at the edge.": "A plataforma de nuvem mais rápida do mundo para construir e escalar aplicações de alto desempenho na borda.",
    "trusted by engineering teams": "As equipas técnicas confiam em nós",
    "up to 10 services": "Até 10 serviços",
    "view cli docs": "Ver documentação de CLI",
    "we migrated 140 microservices in a single weekend with zero downtime. their orchestration layer handled the complexity we were dreading. remarkable.": "Migrámos 140 microserviços em um único fim de semana sem tempo de inatividade. A camada de orquestração lidou com a complexidade que temíamos. Notável.",
    "what teams": "O que as equipas",
  },
};
