/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "a rare promoter that programmes for the room rather than the spreadsheet.": "Un organisateur rare, qui programme pour la salle et non pour le tableur.",
    "about pulse": "À propos",
    "all events": "Tous les événements",
    "are the venues accessible?": "Les lieux sont-ils accessibles ?",
    "artist-first booking process with full creative control": "Une programmation qui met l'artiste d'abord, avec pleine liberté créative",
    "balcony horseshoe, velvet and gilt. indie bills that deserve the room.": "Balcon en fer à cheval, velours et dorures. Des affiches indépendantes à la hauteur de la salle.",
    "before": "Avant",
    "browse all events": "Voir tous les événements",
    "build moments.": "créer des moments.",
    "by city": "Par Ville",
    "by genre": "Par Genre",
    "can i transfer my ticket?": "Puis-je transférer mon billet ?",
    "carbon-offset events since 2023": "Événements à empreinte carbone compensée depuis 2023",
    "curated live music experiences in iconic venues worldwide.": "Expériences musicales en direct sélectionnées dans des lieux emblématiques du monde entier.",
    "curated live music experiences in the world's most iconic venues. electronic, orchestral, indie — all unforgettable.": "Expériences musicales en direct soigneusement sélectionnées dans les lieux les plus emblématiques du monde. Électronique, orchestral, indie — toutes inoubliables.",
    "events per year": "Événements par an",
    "events this season": "événements cette saison",
    "every room we programme has step-free access to the floor, accessible toilets and a dedicated viewing area. companion tickets are free — book the standard ticket and email us, we will add the second at no cost.": "Chaque salle que nous programmons offre un accès de plain-pied, des toilettes accessibles et un espace réservé. Le billet accompagnateur est gratuit : réservez le billet normal et écrivez-nous, nous ajoutons le second sans frais.",
    "every venue we programme has step-free access to the floor and accessible toilets. see the accessibility note below for the detail per room.": "Chaque lieu que nous programmons a un accès sans marche au sol et des toilettes accessibles. Voir la note d'accessibilité ci-dessous pour les détails par salle.",
    "feel the frequency.": "SENTEZ LA FRÉQUENCE.",
    "full refund if an event is cancelled or rescheduled to a date you cannot make. otherwise tickets are transferable rather than refundable.": "Remboursement intégral si un événement est annulé ou reporté à une date à laquelle vous ne pouvez pas assister. Sinon, les billets sont transférables plutôt que remboursables.",
    "join waitlist": "Rejoindre la liste d'attente",
    "members get a 48-hour window before general release. sign up and you will get the code by email the morning it opens.": "Les membres bénéficient d'une fenêtre de 48 heures avant la mise en vente générale. Inscrivez-vous et vous recevrez le code par e-mail le matin de l'ouverture.",
    "the archivists": "Les archivistes",
    "the low end": "Les basses",
    "the most consistently interesting bookings in europe right now.": "La programmation la plus régulièrement intéressante d'Europe en ce moment.",
    "they treat a 1,600-capacity club with the care most promoters reserve for arenas.": "Ils traitent une salle de mille six cents places avec le soin que la plupart réservent aux stades.",
    "tickets sold in 2025": "Billets vendus en 2025",
    "warehouse ix and sublevel are standing rooms with limited seating on request. hall meridian and le ratio are fully seated. tell us what you need when you book and we will confirm the specifics for that room.": "Warehouse IX et Sublevel se tiennent debout, avec quelques places assises sur demande. Hall Meridian et Le Ratio sont entièrement assis. Dites-nous ce qu'il vous faut à la réservation, nous confirmons pour cette salle.",
    "we don't book venues.": "Nous ne réservons pas de lieux.",
    "what is your refund policy?": "Quelle est votre politique de remboursement ?",
    "when do tickets go on sale?": "Quand les billets seront-ils en vente ?",
    "yes, up to 24 hours before doors, from your account. transfers are free — we would rather you pass it on than leave a seat empty.": "Oui, jusqu'à 24 heures avant l'ouverture des portes, depuis votre compte. Les transferts sont gratuits — nous préférons que vous le passiez plutôt que de laisser un siège vide.",
    "you go": "de partir",
  },
  es: {
    "a rare promoter that programmes for the room rather than the spreadsheet.": "Un promotor raro, que programa para la sala y no para la hoja de cálculo.",
    "about pulse": "Sobre nosotros",
    "all events": "Todos los eventos",
    "are the venues accessible?": "¿Son accesibles los lugares?",
    "artist-first booking process with full creative control": "Una programación que pone al artista primero, con plena libertad creativa",
    "balcony horseshoe, velvet and gilt. indie bills that deserve the room.": "Balcón en herradura, terciopelo y dorados. Carteles independientes a la altura de la sala.",
    "before": "Antes",
    "browse all events": "Ver todos los eventos",
    "build moments.": "crear momentos.",
    "by city": "Por Ciudad",
    "by genre": "Por Género",
    "can i transfer my ticket?": "¿Puedo transferir mi entrada?",
    "carbon-offset events since 2023": "Eventos con huella de carbono compensada desde 2023",
    "curated live music experiences in iconic venues worldwide.": "Experiencias de música en vivo seleccionadas en lugares icónicos de todo el mundo.",
    "curated live music experiences in the world's most iconic venues. electronic, orchestral, indie — all unforgettable.": "Experiencias de música en vivo seleccionadas en los lugares más icónicos del mundo. Electrónica, orquestal, indie — todas inolvidables.",
    "events per year": "Eventos por año",
    "events this season": "eventos esta temporada",
    "every room we programme has step-free access to the floor, accessible toilets and a dedicated viewing area. companion tickets are free — book the standard ticket and email us, we will add the second at no cost.": "Cada sala que programamos tiene acceso sin escalones, aseos accesibles y una zona reservada. La entrada de acompañante es gratuita: reserve la entrada normal y escríbanos, añadimos la segunda sin coste.",
    "every venue we programme has step-free access to the floor and accessible toilets. see the accessibility note below for the detail per room.": "Cada lugar que programamos tiene acceso sin escalones al piso y baños accesibles. Consulte la nota de accesibilidad a continuación para obtener detalles por sala.",
    "feel the frequency.": "SIENTA LA FRECUENCIA.",
    "full refund if an event is cancelled or rescheduled to a date you cannot make. otherwise tickets are transferable rather than refundable.": "Reembolso completo si un evento es cancelado o reprogramado a una fecha que no puedes asistir. De lo contrario, las entradas son transferibles en lugar de reembolsables.",
    "join waitlist": "Unirse a la lista de espera",
    "members get a 48-hour window before general release. sign up and you will get the code by email the morning it opens.": "Los miembros tienen una ventana de 48 horas antes de la venta general. Regístrate y recibirás el código por correo electrónico la mañana de la apertura.",
    "the archivists": "Los archiveros",
    "the low end": "Los graves",
    "the most consistently interesting bookings in europe right now.": "La programación más constantemente interesante de Europa ahora mismo.",
    "they treat a 1,600-capacity club with the care most promoters reserve for arenas.": "Tratan una sala de mil seiscientas plazas con el cuidado que la mayoría reserva a los estadios.",
    "tickets sold in 2025": "Entradas vendidas en 2025",
    "warehouse ix and sublevel are standing rooms with limited seating on request. hall meridian and le ratio are fully seated. tell us what you need when you book and we will confirm the specifics for that room.": "Warehouse IX y Sublevel son de pie, con algunas plazas sentadas a petición. Hall Meridian y Le Ratio son enteramente sentados. Díganos qué necesita al reservar y lo confirmamos para esa sala.",
    "we don't book venues.": "No reservamos lugares.",
    "what is your refund policy?": "¿Cuál es su política de reembolso?",
    "when do tickets go on sale?": "¿Cuándo salen a la venta las entradas?",
    "yes, up to 24 hours before doors, from your account. transfers are free — we would rather you pass it on than leave a seat empty.": "Sí, hasta 24 horas antes de la apertura de puertas, desde tu cuenta. Las transferencias son gratuitas; preferimos que lo pases en lugar de dejar un asiento vacío.",
    "you go": "de irse",
  },
  de: {
    "a rare promoter that programmes for the room rather than the spreadsheet.": "Ein seltener Veranstalter, der für den Saal programmiert und nicht für die Tabelle.",
    "about pulse": "Über uns",
    "all events": "Alle Veranstaltungen",
    "are the venues accessible?": "Sind die Veranstaltungsorte barrierefrei?",
    "artist-first booking process with full creative control": "Eine Programmierung, die den Künstler zuerst stellt, mit voller künstlerischer Freiheit",
    "balcony horseshoe, velvet and gilt. indie bills that deserve the room.": "Hufeisenbalkon, Samt und Gold. Independent-Programme, die dem Saal gerecht werden.",
    "before": "Vor",
    "browse all events": "Alle Veranstaltungen ansehen",
    "build moments.": "Momente schaffen.",
    "by city": "Nach Stadt",
    "by genre": "Nach Genre",
    "can i transfer my ticket?": "Kann ich mein Ticket übertragen?",
    "carbon-offset events since 2023": "Veranstaltungen mit CO₂-Ausgleich seit 2023",
    "curated live music experiences in iconic venues worldwide.": "Kuratierten Live-Musik-Erlebnisse in ikonischen Veranstaltungsorten weltweit.",
    "curated live music experiences in the world's most iconic venues. electronic, orchestral, indie — all unforgettable.": "Kuratiertes Live-Musik-Erlebnis in den ikonischsten Veranstaltungsorten der Welt. Elektronisch, orchestral, indie — alles unvergesslich.",
    "events per year": "Veranstaltungen pro Jahr",
    "events this season": "Veranstaltungen in dieser Saison",
    "every room we programme has step-free access to the floor, accessible toilets and a dedicated viewing area. companion tickets are free — book the standard ticket and email us, we will add the second at no cost.": "Jeder Saal, den wir bespielen, hat stufenlosen Zugang, barrierefreie Toiletten und einen eigenen Bereich. Die Begleitkarte ist kostenlos: Buchen Sie das normale Ticket und schreiben Sie uns, wir fügen die zweite gratis hinzu.",
    "every venue we programme has step-free access to the floor and accessible toilets. see the accessibility note below for the detail per room.": "Jeder Veranstaltungsort, den wir programmieren, hat einen stufenlosen Zugang zum Boden und barrierefreie Toiletten. Siehe die Zugänglichkeitsnotiz unten für die Details pro Raum.",
    "feel the frequency.": "SPÜREN SIE DIE FREQUENZ.",
    "full refund if an event is cancelled or rescheduled to a date you cannot make. otherwise tickets are transferable rather than refundable.": "Vollständige Rückerstattung, wenn eine Veranstaltung abgesagt oder auf ein Datum verschoben wird, an dem Sie nicht teilnehmen können. Andernfalls sind Tickets übertragbar, aber nicht erstattungsfähig.",
    "join waitlist": "Wartenliste beitreten",
    "members get a 48-hour window before general release. sign up and you will get the code by email the morning it opens.": "Mitglieder erhalten ein 48-Stunden-Fenster vor dem allgemeinen Verkauf. Melden Sie sich an und Sie erhalten den Code per E-Mail am Morgen der Eröffnung.",
    "the archivists": "Die Archivare",
    "the low end": "Die Tiefen",
    "the most consistently interesting bookings in europe right now.": "Derzeit das durchweg interessanteste Programm Europas.",
    "they treat a 1,600-capacity club with the care most promoters reserve for arenas.": "Sie behandeln einen Club für tausendsechshundert Menschen mit der Sorgfalt, die andere Arenen vorbehalten.",
    "tickets sold in 2025": "Tickets verkauft im Jahr 2025",
    "warehouse ix and sublevel are standing rooms with limited seating on request. hall meridian and le ratio are fully seated. tell us what you need when you book and we will confirm the specifics for that room.": "Warehouse IX und Sublevel sind Stehplätze, Sitzplätze auf Anfrage. Hall Meridian und Le Ratio sind vollständig bestuhlt. Sagen Sie uns bei der Buchung, was Sie brauchen — wir bestätigen es für den Saal.",
    "we don't book venues.": "Wir buchen keine Veranstaltungsorte.",
    "what is your refund policy?": "Was ist Ihre Rückerstattungsrichtlinie?",
    "when do tickets go on sale?": "Wann gehen die Tickets in den Verkauf?",
    "yes, up to 24 hours before doors, from your account. transfers are free — we would rather you pass it on than leave a seat empty.": "Ja, bis zu 24 Stunden vor Einlass, von Ihrem Konto aus. Übertragungen sind kostenlos – wir ziehen es vor, dass Sie es weitergeben, als einen Platz leer zu lassen.",
    "you go": "Sie gehen",
  },
  pt: {
    "a rare promoter that programmes for the room rather than the spreadsheet.": "Um promotor raro, que programa para a sala e não para a folha de cálculo.",
    "about pulse": "Sobre nós",
    "all events": "Todos os eventos",
    "are the venues accessible?": "Os locais são acessíveis?",
    "artist-first booking process with full creative control": "Uma programação que põe o artista primeiro, com plena liberdade criativa",
    "balcony horseshoe, velvet and gilt. indie bills that deserve the room.": "Balcão em ferradura, veludo e dourados. Cartazes independentes à altura da sala.",
    "before": "Antes",
    "browse all events": "Ver todos os eventos",
    "build moments.": "criar momentos.",
    "by city": "Por Cidade",
    "by genre": "Por Género",
    "can i transfer my ticket?": "Posso transferir o meu bilhete?",
    "carbon-offset events since 2023": "Eventos com pegada de carbono compensada desde 2023",
    "curated live music experiences in iconic venues worldwide.": "Experiências de música ao vivo selecionadas em locais icónicos em todo o mundo.",
    "curated live music experiences in the world's most iconic venues. electronic, orchestral, indie — all unforgettable.": "Experiências de música ao vivo selecionadas nos locais mais icônicos do mundo. Eletrônico, orquestral, indie — todas inesquecíveis.",
    "events per year": "Eventos por ano",
    "events this season": "eventos esta temporada",
    "every room we programme has step-free access to the floor, accessible toilets and a dedicated viewing area. companion tickets are free — book the standard ticket and email us, we will add the second at no cost.": "Cada sala que programamos tem acesso sem degraus, casas de banho acessíveis e uma zona reservada. O bilhete de acompanhante é gratuito: reserve o bilhete normal e escreva-nos, acrescentamos o segundo sem custo.",
    "every venue we programme has step-free access to the floor and accessible toilets. see the accessibility note below for the detail per room.": "Cada local que programamos tem acesso sem degraus ao piso e casas de banho acessíveis. Veja a nota de acessibilidade abaixo para os detalhes por sala.",
    "feel the frequency.": "SINTA A FREQUÊNCIA.",
    "full refund if an event is cancelled or rescheduled to a date you cannot make. otherwise tickets are transferable rather than refundable.": "Reembolso total se um evento for cancelado ou reagendado para uma data que você não pode comparecer. Caso contrário, os bilhetes são transferíveis em vez de reembolsáveis.",
    "join waitlist": "Juntar-se à lista de espera",
    "members get a 48-hour window before general release. sign up and you will get the code by email the morning it opens.": "Os membros têm uma janela de 48 horas antes da venda geral. Inscreva-se e receberá o código por e-mail na manhã da abertura.",
    "the archivists": "Os arquivistas",
    "the low end": "Os graves",
    "the most consistently interesting bookings in europe right now.": "A programação mais consistentemente interessante da Europa neste momento.",
    "they treat a 1,600-capacity club with the care most promoters reserve for arenas.": "Tratam uma sala de mil e seiscentos lugares com o cuidado que a maioria reserva aos estádios.",
    "tickets sold in 2025": "Bilhetes vendidos em 2025",
    "warehouse ix and sublevel are standing rooms with limited seating on request. hall meridian and le ratio are fully seated. tell us what you need when you book and we will confirm the specifics for that room.": "Warehouse IX e Sublevel são de pé, com alguns lugares sentados a pedido. Hall Meridian e Le Ratio são totalmente sentados. Diga-nos do que precisa ao reservar e confirmamos para essa sala.",
    "we don't book venues.": "Não reservamos locais.",
    "what is your refund policy?": "Qual é a sua política de reembolso?",
    "when do tickets go on sale?": "Quando é que os bilhetes vão estar à venda?",
    "yes, up to 24 hours before doors, from your account. transfers are free — we would rather you pass it on than leave a seat empty.": "Sim, até 24 horas antes da abertura das portas, a partir da sua conta. As transferências são gratuitas — preferimos que o passe do que deixar um lugar vazio.",
    "you go": "de partir",
  },
};
