/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "trusted by": "Adopté par les",
    "builders.": "bâtisseurs.",
    "projects completed": "Projets livrés",
    "countries": "Pays",
    "carbon-negative projects": "Projets à bilan carbone négatif",
    "motion graphics": "Motion design",
    "brand films": "Films de marque",
    "interactive": "Interactif",
    "brand exploration": "Exploration de marque",
    "fleet": "La flotte",
    "network": "Réseau",
    "company": "L'entreprise",
    "craftsmanship": "Savoir-faire",
    "heritage": "Héritage",
    "innovation": "Innovation",
    "infrastructure": "Infrastructure",
    "deploy": "Déployer",
    "fragrances": "Parfums",
    "digital craft": "Artisanat numérique",
    "e-commerce": "Commerce en ligne",
    "art direction, webgl": "Direction artistique, WebGL",
    "global edition": "Édition internationale",
    "reserve": "Réserver",
    "owner portal": "Espace propriétaires",
    "stack": "Technologies",
    "access": "Accès",
    "initialize": "Démarrer",
    "system architecture": "Architecture du système",
    "command login": "Accès contrôle",
    "missions": "Missions",
    "events": "Événements",
    "artists": "Artistes",
    "venues": "Salles",
    "upcoming": "À venir",
    "properties": "Nos biens",
    "private inquiry": "Demande confidentielle",
    "exceptional": "Exceptionnel",
    "examples": "Exemples",
    "plugins": "Extensions",
    "digital experience": "Expérience numérique",
    "brand identity": "Identité de marque",
    "ai revolution": "Révolution de l'IA",
    "without the pain.": "Sans la douleur.",
    "build pipelines": "Construire des pipelines",
    "built by": "Construit par",
    "built-in versioning": "Versioning intégré",
    "declarative pipeline definitions with full typescript support. connect any source to any sink with composable transforms.": "Définitions de pipeline déclaratives avec un support complet de TypeScript. Connectez n'importe quelle source à n'importe quel puits avec des transformations composables.",
    "extend the core with typed plugins. community-maintained registry with 200+ packages.": "Étendez le cœur par des greffons typés. Un registre tenu par la communauté, plus de deux cents paquets.",
    "full control from your terminal. scriptable, composable, and ci/cd-friendly.": "Tout se pilote depuis le terminal. Scriptable, composable, et fait pour l'intégration continue.",
    "open core team": "L'équipe du cœur ouvert",
    "open-source data pipeline framework.": "Cadriciel libre de traitement de données.",
    "our onboarding dropped from 3 days to 4 hours. every new dev just runs one command and they're in the right environment immediately.": "Notre intégration est passée de 3 jours à 4 heures. Chaque nouveau développeur exécute simplement une commande et il est immédiatement dans le bon environnement.",
    "process data streams without memory allocation overhead. 10x faster than alternatives.": "Traitez des flux de données sans surcharge d'allocation mémoire. 10x plus rapide que les alternatives.",
    "read the docs": "Lire la documentation",
    "replaced our entire internal cli tooling in a weekend. the dx is absurd — we shipped a production feature in the time our old flow took to configure.": "Remplacé tous nos outils internes CLI en un week-end. L'expérience développeur est absurde — nous avons expédié une fonctionnalité en production dans le temps que notre ancien flux prenait pour se configurer.",
    "star on github": "Étoile sur GitHub",
    "start building": "Commencer à construire",
    "the gitbranch integration is effortless. i've been a cli nerd for 12 years — this is the first time i've felt genuinely excited about tooling.": "L'intégration GitBranch est sans effort. Je suis passionné de CLI depuis 12 ans — c'est la première fois que je me sens vraiment excité par des outils.",
    "the open-source framework for building real-time data pipelines. type-safe, zero-copy, and absurdly fast.": "Le cadre open-source pour construire des pipelines de données en temps réel. Sûr pour les types, sans copie, et incroyablement rapide.",
    "today.": "Aujourd'hui.",
    "track every schema change with automatic migration generation and rollback.": "Suivez chaque changement de schéma : migrations générées automatiquement, retour arrière possible.",
    "wavefx is free, open-source, and backed by a community of 450+ contributors.": "WaveFX est gratuit, open-source, et soutenu par une communauté de plus de 450 contributeurs.",
  },
  es: {
    "trusted by": "Adoptado por",
    "builders.": "constructores.",
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "projects completed": "Proyectos entregados",
    "countries": "Países",
    "carbon-negative projects": "Proyectos de balance de carbono negativo",
    "motion graphics": "Motion graphics",
    "brand films": "Films de marca",
    "interactive": "Interactivo",
    "brand exploration": "Exploración de marca",
    "fleet": "La flota",
    "network": "Red",
    "company": "La empresa",
    "craftsmanship": "Saber hacer",
    "heritage": "Herencia",
    "innovation": "Innovación",
    "infrastructure": "Infraestructura",
    "deploy": "Desplegar",
    "fragrances": "Perfumes",
    "digital craft": "Artesanía digital",
    "e-commerce": "Comercio electrónico",
    "art direction, webgl": "Dirección de arte, WebGL",
    "global edition": "Edición internacional",
    "reserve": "Reservar",
    "owner portal": "Área de propietarios",
    "stack": "Tecnologías",
    "access": "Acceso",
    "initialize": "Iniciar",
    "system architecture": "Arquitectura del sistema",
    "command login": "Acceso de control",
    "missions": "Misiones",
    "events": "Eventos",
    "artists": "Artistas",
    "venues": "Salas",
    "upcoming": "Próximamente",
    "properties": "Nuestros inmuebles",
    "private inquiry": "Solicitud confidencial",
    "exceptional": "Excepcional",
    "examples": "Ejemplos",
    "plugins": "Extensiones",
    "digital experience": "Experiencia digital",
    "brand identity": "Identidad de marca",
    "ai revolution": "Revolución de la IA",
    "without the pain.": "Sin el dolor.",
    "build pipelines": "Construir tuberías",
    "built by": "Construido por",
    "built-in versioning": "Versionado integrado",
    "declarative pipeline definitions with full typescript support. connect any source to any sink with composable transforms.": "Definiciones de tuberías declarativas con soporte completo de TypeScript. Conecte cualquier fuente a cualquier sumidero con transformaciones componibles.",
    "extend the core with typed plugins. community-maintained registry with 200+ packages.": "Amplíe el núcleo con complementos tipados. Un registro mantenido por la comunidad, más de doscientos paquetes.",
    "full control from your terminal. scriptable, composable, and ci/cd-friendly.": "Todo se maneja desde la terminal. Programable, componible y pensado para la integración continua.",
    "open core team": "El equipo del núcleo abierto",
    "open-source data pipeline framework.": "Marco de trabajo libre para el tratamiento de datos.",
    "our onboarding dropped from 3 days to 4 hours. every new dev just runs one command and they're in the right environment immediately.": "Nuestra incorporación pasó de 3 días a 4 horas. Cada nuevo desarrollador solo ejecuta un comando y está en el entorno correcto de inmediato.",
    "process data streams without memory allocation overhead. 10x faster than alternatives.": "Procesa flujos de datos sin sobrecarga de asignación de memoria. 10x más rápido que las alternativas.",
    "read the docs": "Leer la documentación",
    "replaced our entire internal cli tooling in a weekend. the dx is absurd — we shipped a production feature in the time our old flow took to configure.": "Reemplazamos todas nuestras herramientas internas de CLI en un fin de semana. La experiencia del desarrollador es absurda — lanzamos una función de producción en el tiempo que nuestro antiguo flujo tardaba en configurarse.",
    "star on github": "Estrella en GitHub",
    "start building": "Empezar a construir",
    "the gitbranch integration is effortless. i've been a cli nerd for 12 years — this is the first time i've felt genuinely excited about tooling.": "La integración de GitBranch es sin esfuerzo. He sido un nerd de CLI durante 12 años — esta es la primera vez que me siento genuinamente emocionado por las herramientas.",
    "the open-source framework for building real-time data pipelines. type-safe, zero-copy, and absurdly fast.": "El marco de código abierto para construir tuberías de datos en tiempo real. Seguro para tipos, sin copias y absurdamente rápido.",
    "today.": "Hoy.",
    "track every schema change with automatic migration generation and rollback.": "Siga cada cambio de esquema: migraciones generadas automáticamente y vuelta atrás posible.",
    "wavefx is free, open-source, and backed by a community of 450+ contributors.": "WaveFX es gratuito, de código abierto y respaldado por una comunidad de más de 450 colaboradores.",
  },
  de: {
    "trusted by": "Vertraut von",
    "builders.": "Machern.",
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "projects completed": "Fertiggestellte Projekte",
    "countries": "Länder",
    "carbon-negative projects": "Projekte mit negativer CO₂-Bilanz",
    "motion graphics": "Motion Graphics",
    "brand films": "Markenfilme",
    "interactive": "Interaktiv",
    "brand exploration": "Markenerkundung",
    "fleet": "Die Flotte",
    "network": "Netz",
    "company": "Unternehmen",
    "craftsmanship": "Handwerkskunst",
    "heritage": "Erbe",
    "innovation": "Innovation",
    "infrastructure": "Infrastruktur",
    "deploy": "Deployen",
    "fragrances": "Düfte",
    "digital craft": "Digitales Handwerk",
    "e-commerce": "E-Commerce",
    "art direction, webgl": "Art Direction, WebGL",
    "global edition": "Internationale Ausgabe",
    "reserve": "Reservieren",
    "owner portal": "Eigentümerbereich",
    "stack": "Technologien",
    "access": "Zugang",
    "initialize": "Starten",
    "system architecture": "Systemarchitektur",
    "command login": "Zugang zur Leitstelle",
    "missions": "Missionen",
    "events": "Veranstaltungen",
    "artists": "Künstler",
    "venues": "Spielstätten",
    "upcoming": "Demnächst",
    "properties": "Unsere Objekte",
    "private inquiry": "Vertrauliche Anfrage",
    "exceptional": "Außergewöhnlich",
    "examples": "Beispiele",
    "plugins": "Erweiterungen",
    "digital experience": "Digitales Erlebnis",
    "brand identity": "Markenidentität",
    "ai revolution": "KI-Revolution",
    "without the pain.": "Ohne den Schmerz.",
    "build pipelines": "Pipelines erstellen",
    "built by": "Gebaut von",
    "built-in versioning": "Integrierte Versionierung",
    "declarative pipeline definitions with full typescript support. connect any source to any sink with composable transforms.": "Deklarative Pipeline-Definitionen mit vollständiger TypeScript-Unterstützung. Verbinden Sie jede Quelle mit jedem Ziel mit komposierbaren Transformationen.",
    "extend the core with typed plugins. community-maintained registry with 200+ packages.": "Erweitern Sie den Kern mit typisierten Plugins. Ein von der Gemeinschaft gepflegtes Register mit über zweihundert Paketen.",
    "full control from your terminal. scriptable, composable, and ci/cd-friendly.": "Alles über das Terminal steuerbar. Skriptfähig, kombinierbar und auf CI/CD ausgelegt.",
    "open core team": "Das Open-Core-Team",
    "open-source data pipeline framework.": "Quelloffenes Framework für Datenpipelines.",
    "our onboarding dropped from 3 days to 4 hours. every new dev just runs one command and they're in the right environment immediately.": "Unser Onboarding ist von 3 Tagen auf 4 Stunden gesunken. Jeder neue Entwickler führt einfach einen Befehl aus und ist sofort in der richtigen Umgebung.",
    "process data streams without memory allocation overhead. 10x faster than alternatives.": "Verarbeiten Sie Datenströme ohne Speicherzuweisungsüberhead. 10x schneller als Alternativen.",
    "read the docs": "Dokumentation lesen",
    "replaced our entire internal cli tooling in a weekend. the dx is absurd — we shipped a production feature in the time our old flow took to configure.": "Haben unser gesamtes internes CLI-Tooling an einem Wochenende ersetzt. Die Entwicklererfahrung ist absurd — wir haben ein Produktionsfeature in der Zeit ausgeliefert, die unser alter Workflow zur Konfiguration benötigte.",
    "star on github": "Stern auf GitHub",
    "start building": "Jetzt loslegen",
    "the gitbranch integration is effortless. i've been a cli nerd for 12 years — this is the first time i've felt genuinely excited about tooling.": "Die GitBranch-Integration ist mühelos. Ich bin seit 12 Jahren ein CLI-Nerd — das ist das erste Mal, dass ich mich wirklich über Tools freue.",
    "the open-source framework for building real-time data pipelines. type-safe, zero-copy, and absurdly fast.": "Das Open-Source-Framework zum Erstellen von Echtzeit-Datenpipelines. Typsicher, null Kopien und absurd schnell.",
    "today.": "Heute.",
    "track every schema change with automatic migration generation and rollback.": "Verfolgen Sie jede Schemaänderung: automatisch erzeugte Migrationen und Rückabwicklung.",
    "wavefx is free, open-source, and backed by a community of 450+ contributors.": "WaveFX ist kostenlos, Open Source und wird von einer Gemeinschaft von über 450 Mitwirkenden unterstützt.",
  },
  pt: {
    "trusted by": "Adotado por",
    "builders.": "construtores.",
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "projects completed": "Projetos entregues",
    "countries": "Países",
    "carbon-negative projects": "Projetos de balanço de carbono negativo",
    "motion graphics": "Motion design",
    "brand films": "Filmes de marca",
    "interactive": "Interativo",
    "brand exploration": "Exploração de marca",
    "fleet": "A frota",
    "network": "Rede",
    "company": "A empresa",
    "craftsmanship": "Saber-fazer",
    "heritage": "Herança",
    "innovation": "Inovação",
    "infrastructure": "Infraestrutura",
    "deploy": "Implementar",
    "fragrances": "Perfumes",
    "digital craft": "Artesanato digital",
    "e-commerce": "Comércio eletrónico",
    "art direction, webgl": "Direção de arte, WebGL",
    "global edition": "Edição internacional",
    "reserve": "Reservar",
    "owner portal": "Área de proprietários",
    "stack": "Tecnologias",
    "access": "Acesso",
    "initialize": "Iniciar",
    "system architecture": "Arquitetura do sistema",
    "command login": "Acesso de controlo",
    "missions": "Missões",
    "events": "Eventos",
    "artists": "Artistas",
    "venues": "Salas",
    "upcoming": "Em breve",
    "properties": "Os nossos imóveis",
    "private inquiry": "Pedido confidencial",
    "exceptional": "Excecional",
    "examples": "Exemplos",
    "plugins": "Extensões",
    "digital experience": "Experiência digital",
    "brand identity": "Identidade de marca",
    "ai revolution": "Revolução da IA",
    "without the pain.": "Sem a dor.",
    "build pipelines": "Construir pipelines",
    "built by": "Construído por",
    "built-in versioning": "Versionamento integrado",
    "declarative pipeline definitions with full typescript support. connect any source to any sink with composable transforms.": "Definições de pipeline declarativas com suporte total para TypeScript. Conecte qualquer fonte a qualquer destino com transformações compostas.",
    "extend the core with typed plugins. community-maintained registry with 200+ packages.": "Amplie o núcleo com extensões tipadas. Um registo mantido pela comunidade, mais de duzentos pacotes.",
    "full control from your terminal. scriptable, composable, and ci/cd-friendly.": "Tudo se controla a partir do terminal. Programável, componível e feito para a integração contínua.",
    "open core team": "A equipa do núcleo aberto",
    "open-source data pipeline framework.": "Framework livre para o tratamento de dados.",
    "our onboarding dropped from 3 days to 4 hours. every new dev just runs one command and they're in the right environment immediately.": "A nossa integração passou de 3 dias para 4 horas. Cada novo desenvolvedor apenas executa um comando e está imediatamente no ambiente correto.",
    "process data streams without memory allocation overhead. 10x faster than alternatives.": "Processa fluxos de dados sem sobrecarga de alocação de memória. 10x mais rápido do que as alternativas.",
    "read the docs": "Ler a documentação",
    "replaced our entire internal cli tooling in a weekend. the dx is absurd — we shipped a production feature in the time our old flow took to configure.": "Substituímos todas as nossas ferramentas internas de CLI em um fim de semana. A experiência do desenvolvedor é absurda — lançamos uma funcionalidade em produção no tempo que o nosso antigo fluxo levava para se configurar.",
    "star on github": "Estrela no GitHub",
    "start building": "Começar a construir",
    "the gitbranch integration is effortless. i've been a cli nerd for 12 years — this is the first time i've felt genuinely excited about tooling.": "A integração GitBranch é sem esforço. Sou um fã de CLI há 12 anos — esta é a primeira vez que me sinto genuinamente entusiasmado com ferramentas.",
    "the open-source framework for building real-time data pipelines. type-safe, zero-copy, and absurdly fast.": "A estrutura de código aberto para construir pipelines de dados em tempo real. Seguro para tipos, sem cópias e absurdamente rápido.",
    "today.": "Hoje.",
    "track every schema change with automatic migration generation and rollback.": "Siga cada alteração de esquema: migrações geradas automaticamente e reversão possível.",
    "wavefx is free, open-source, and backed by a community of 450+ contributors.": "WaveFX é gratuito, de código aberto e apoiado por uma comunidade de mais de 450 colaboradores.",
  },
};
