"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Frame, Eye, Calendar, Menu, X, Star, CheckCircle2, Ticket, BookOpen, Users } from "lucide-react";
import "../premium.css";
const EXHI=[{t:"Structures of Silence",a:"Yoko Abe",c:"INSTALLATION",y:"2026"},{t:"Digital Brutalism",a:"Max Werner",c:"DIGITAL",y:"2025"},{t:"The Weight of Light",a:"Ana Morales",c:"SCULPTURE",y:"2026"},{t:"Grid Theory",a:"Collective Void",c:"MIXED MEDIA",y:"2025"}];
const SVC=[{icon:<Frame className="w-6 h-6"/>,t:"Permanent Collection",d:"3,000+ works spanning modern and contemporary art."},{icon:<Eye className="w-6 h-6"/>,t:"Rotating Exhibitions",d:"Six major exhibitions annually from global artists."},{icon:<Calendar className="w-6 h-6"/>,t:"Events & Talks",d:"Artist talks, workshops, and opening night receptions."},{icon:<BookOpen className="w-6 h-6"/>,t:"Research Library",d:"50,000 volumes of art history and criticism."},{icon:<Users className="w-6 h-6"/>,t:"Education Programs",d:"K-12, university, and adult learning workshops."},{icon:<Ticket className="w-6 h-6"/>,t:"Membership",d:"Unlimited access, previews, and exclusive events."}];
const TM=[{n:"Dr. Elena Voss",r:"Art Critic",q:"MoMA Structure is the most important new museum of the decade. The architecture alone is worth the visit."},{n:"Kenji Nakamura",r:"Collector",q:"Their curation is extraordinary. Every visit reveals something new."},{n:"Sophie Müller",r:"Artist",q:"Being exhibited here was a career-defining moment. Their support for artists is genuine."}];
const PR=[{n:"DAY PASS",p:"$25",pd:"/visit",f:["All galleries","Current exhibitions","Audio guide","Gift shop discount"],c:"Buy_Ticket"},{n:"ANNUAL",p:"$120",pd:"/year",f:["Unlimited visits","Member previews","Guest passes","Event invites","10% shop discount"],c:"Join_Now",ft:true},{n:"PATRON",p:"$500",pd:"/year",f:["All Annual benefits","Private tours","Curator dinners","Name recognition","Tax deduction"],c:"Become_Patron"}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function MoMAStructurePage(){
  const[s,setS]=useState(false);const[m,setM]=useState(false);
  useEffect(()=>{const h=()=>setS(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  return(<div className="premium-theme min-h-screen bg-[#fafafa] text-[#0a0a0a] font-mono selection:bg-[#0a0a0a] selection:text-white overflow-x-hidden">
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${s?"bg-[#fafafa]/90 backdrop-blur-xl py-4 border-b border-[#0a0a0a]/10":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-[#0a0a0a] rounded-none flex items-center justify-center text-white"><Frame className="w-4 h-4"/></div><span className="group-hover:text-[#0a0a0a]/60 transition-colors">MOMA // <span className="text-[#0a0a0a]/30">STRUCTURE</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-[#0a0a0a]/30">{["Exhibitions","Collection","Visit","Join"].map(l=><Link key={l} href="#" className="hover:text-[#0a0a0a] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-[#0a0a0a] text-white text-[10px] font-black uppercase tracking-widest hover:bg-[#0a0a0a]/80 transition-all hidden md:block">Tickets</button><button onClick={()=>setM(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{m&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#fafafa] p-8 flex flex-col pt-32"><button onClick={()=>setM(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Exhibitions","Collection","Visit","Join"].map(l=><Link key={l} href="#" onClick={()=>setM(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>

    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#0a0a0a]/5 border border-[#0a0a0a]/10 text-[#0a0a0a]/60 text-[9px] font-bold uppercase tracking-widest inline-block mb-8">NOW_EXHIBITING</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">Art.<br/>Architecture.<br/><span className="text-[#0a0a0a]/30">Structure.</span></h1><p className="max-w-xl text-lg text-[#0a0a0a]/40 leading-relaxed font-light uppercase tracking-widest italic mb-12">Museum of modern art & architecture. Where form meets meaning.</p><div className="flex flex-col sm:flex-row gap-6"><button className="px-12 py-5 bg-[#0a0a0a] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#0a0a0a]/80 transition-all">Buy_Tickets</button><button className="px-12 py-5 border-2 border-[#0a0a0a] text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#0a0a0a] hover:text-white transition-all">Plan_Visit</button></div></Reveal></div></section>

    <section className="py-40 bg-white border-y-4 border-[#0a0a0a]"><div className="max-w-[1500px] mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-2 gap-24 items-center"><Reveal><span className="text-[10px] text-[#0a0a0a]/60 font-bold uppercase tracking-[0.4em] mb-6 block">About</span><h2 className="text-5xl md:text-7xl font-black tracking-tighter leading-[0.85] mb-8 uppercase">Since <span className="text-[#0a0a0a]/30">1929.</span></h2><p className="text-base text-[#0a0a0a]/40 leading-relaxed mb-12">MoMA Structure redefines the museum as a living, breathing architectural experience. Our brutalist campus houses 3,000+ works across 12 galleries.</p><div className="flex gap-16">{[{v:"3K+",l:"WORKS"},{v:"12",l:"GALLERIES"},{v:"1.2M",l:"VISITORS/YR"}].map((s,i)=><div key={i}><div className="text-3xl font-black">{s.v}</div><div className="text-[9px] font-bold text-[#0a0a0a]/20 uppercase tracking-widest">{s.l}</div></div>)}</div></Reveal><Reveal delay={0.15}><div className="w-full aspect-square bg-[#0a0a0a] rounded-none flex items-center justify-center"><Frame className="w-20 h-20 text-white/10"/></div></Reveal></div></section>

    <section className="py-40 bg-[#fafafa]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Current <span className="text-[#0a0a0a]/30">Shows.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{EXHI.map((e,i)=><Reveal key={i} delay={i*0.05}><div className="group cursor-pointer"><div className="w-full aspect-[16/10] bg-[#0a0a0a]/5 border-2 border-[#0a0a0a]/10 rounded-none flex items-center justify-center mb-6 group-hover:bg-[#0a0a0a] group-hover:border-[#0a0a0a] transition-all"><Eye className="w-12 h-12 text-[#0a0a0a]/15 group-hover:text-white/20 transition-colors"/></div><div className="flex items-center gap-4 mb-2"><span className="text-[9px] font-bold text-[#0a0a0a]/60 uppercase tracking-widest">{e.c}</span><span className="text-[9px] text-[#0a0a0a]/20 uppercase tracking-widest">{e.y}</span></div><h3 className="text-2xl font-black uppercase tracking-tighter group-hover:text-[#0a0a0a]/60 transition-colors mb-1">{e.t}</h3><p className="text-sm text-[#0a0a0a]/30">{e.a}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-white border-y-4 border-[#0a0a0a]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Museum <span className="text-[#0a0a0a]/30">Programs.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{SVC.map((f,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-[#fafafa] border-2 border-[#0a0a0a]/10 hover:border-[#0a0a0a] rounded-none transition-all"><div className="w-14 h-14 bg-[#0a0a0a]/5 rounded-none flex items-center justify-center text-[#0a0a0a] mb-8 group-hover:bg-[#0a0a0a] group-hover:text-white transition-all">{f.icon}</div><h3 className="text-xl font-black uppercase tracking-tighter mb-4">{f.t}</h3><p className="text-sm text-[#0a0a0a]/40">{f.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#fafafa]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Visitor <span className="text-[#0a0a0a]/30">Reviews.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-white border-2 border-[#0a0a0a]/10 rounded-none h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#0a0a0a] fill-[#0a0a0a]"/>)}</div><p className="text-base text-[#0a0a0a]/50 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t-2 border-[#0a0a0a]/10"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-[#0a0a0a]/30 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#fafafa]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter leading-[0.85] mb-24 uppercase text-center">Membership.</h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">{PR.map((p,i)=><Reveal key={i} delay={i*0.1}><div className={`group p-10 border-2 rounded-none transition-all ${p.ft?"bg-[#0a0a0a] text-white border-[#0a0a0a]":"bg-white border-[#0a0a0a]/10"}`}><div className={`text-[9px] font-bold uppercase tracking-widest mb-2 ${p.ft?"text-white/60":"text-[#0a0a0a]/60"}`}>{p.n}</div><div className="text-4xl font-black mb-1">{p.p}<span className={`text-lg ${p.ft?"text-white/30":"text-[#0a0a0a]/30"}`}>{p.pd}</span></div><div className={`space-y-4 mt-8 pt-8 border-t ${p.ft?"border-white/10":"border-[#0a0a0a]/10"}`}>{p.f.map((f,j)=><div key={j} className={`flex items-center gap-3 text-[10px] ${p.ft?"text-white/40":"text-[#0a0a0a]/50"}`}><CheckCircle2 className={`w-3.5 h-3.5 ${p.ft?"text-white":"text-[#0a0a0a]"}`}/>{f}</div>)}</div><button className={`mt-8 w-full py-3 text-[10px] font-black uppercase tracking-widest transition-all ${p.ft?"bg-white text-[#0a0a0a]":"border-2 border-[#0a0a0a]/10 hover:bg-[#0a0a0a] hover:text-white"}`}>{p.c}</button></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0a0a0a] text-white text-center"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Visit <span className="text-white/30">Today.</span></h2><button className="px-16 py-6 bg-white text-[#0a0a0a] text-[12px] font-black uppercase tracking-[0.4em] hover:bg-white/80 transition-all">Get_Tickets</button></Reveal></div></section>

    <footer className="bg-[#0a0a0a] border-t-4 border-white/10 py-32 px-6 md:px-12 text-white"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-white text-[#0a0a0a] rounded-none flex items-center justify-center"><Frame className="w-4 h-4"/></div><span>MOMA // STRUCTURE</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">Museum of modern art. Since 1929.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-white/60">Visit</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Hours","Directions","Accessibility"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-white/60">Connect</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Instagram","Newsletter","Press"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 MOMA STRUCTURE</div></footer>
  </div>);
}
