/*
  La prose de démonstration de ce thème, dans les langues que nous proposons.

  Ces phrases sont écrites en dur dans le thème : elles ne viennent d'aucun
  champ du formulaire, et disparaissent dès que le client remplit le bloc
  correspondant. Les traduire est ce qui tient la page tant qu'il ne l'a pas
  fait — un site français ne montre pas de paragraphe anglais.

  Chargé par BrandColorVar avec ce thème et avec lui seul.
*/
export const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    "the": "LA",
    "speed": "VITESSE",
    "of": "DE LA",
    "light.": "LUMIÈRE.",
    "the speed of light.": "La vitesse de la lumière.",
    "en transit : nyc_442": "EN TRANSIT : NYC_442",
    "projects completed": "Projets livrés",
    "countries": "Pays",
    "carbon-negative projects": "Projets à bilan carbone négatif",
    "motion graphics": "Motion design",
    "brand films": "Films de marque",
    "interactive": "Interactif",
    "brand exploration": "Exploration de marque",
    "fleet": "La flotte",
    "network": "Réseau",
    "company": "L'entreprise",
    "craftsmanship": "Savoir-faire",
    "heritage": "Héritage",
    "innovation": "Innovation",
    "infrastructure": "Infrastructure",
    "deploy": "Déployer",
    "fragrances": "Parfums",
    "digital craft": "Artisanat numérique",
    "e-commerce": "Commerce en ligne",
    "art direction, webgl": "Direction artistique, WebGL",
    "global edition": "Édition internationale",
    "reserve": "Réserver",
    "owner portal": "Espace propriétaires",
    "stack": "Technologies",
    "access": "Accès",
    "initialize": "Démarrer",
    "system architecture": "Architecture du système",
    "command login": "Accès contrôle",
    "missions": "Missions",
    "events": "Événements",
    "artists": "Artistes",
    "venues": "Salles",
    "upcoming": "À venir",
    "properties": "Nos biens",
    "private inquiry": "Demande confidentielle",
    "exceptional": "Exceptionnel",
    "examples": "Exemples",
    "plugins": "Extensions",
    "digital experience": "Expérience numérique",
    "brand identity": "Identité de marque",
    "ai revolution": "Révolution de l'IA",
    "ai-optimized routing that reduces energy consumption by 24% per mile.": "Routage optimisé par l'IA qui réduit la consommation d'énergie de 24 % par mile.",
    "autonomous, all-electric, and ai-driven logistics. we don't just deliver packages; we engineer time and efficiency.": "Logistique autonome, entièrement électrique et pilotée par l'IA. Nous ne livrons pas seulement des colis ; nous concevons le temps et l'efficacité.",
    "blockchain-verified delivery milestones with real-time biometric scanning.": "Étapes de livraison certifiées, avec lecture biométrique en temps réel.",
    "client portal": "Portail Client",
    "engineering the next generation of autonomous, zero-emission logistics for a world that never stops moving.": "Ingénierie de la prochaine génération de logistique autonome et zéro émission pour un monde qui ne cesse de bouger.",
    "in-transit: nyc 442": "En transit : NYC 442",
    "in-transit: nyc_442": "En Transit : NYC_442",
    "our fleet": "Notre flotte",
    "powered by": "Alimenté par",
    "proof of transit": "Preuve de Transit",
    "see pricing": "Voir les tarifs",
    "shift your": "Faites bouger votre",
    "start shipping": "Commencer à expédier",
    "view specifications": "Voir les spécifications",
    "watch logistics flow": "Regardez la logistique s'écouler",
  },
  es: {
    "the": "LA",
    "speed": "VELOCIDAD",
    "of": "DE LA",
    "light.": "LUZ.",
    "the speed of light.": "La velocidad de la luz.",
    "en transit : nyc_442": "EN TRÁNSITO: NYC_442",
    "réserver une table": "Reservar una mesa",
    "réserver votre table": "Reservar su mesa",
    "réserver": "Reservar",
    "commander": "Pedir",
    "commander en ligne": "Pedir en línea",
    "devis gratuit": "Presupuesto gratuito",
    "prendre rendez-vous": "Pedir cita",
    "nous contacter": "Contáctenos",
    "nous écrire": "Escríbanos",
    "appeler": "Llamar",
    "appeler maintenant": "Llamar ahora",
    "voir le menu": "Ver la carta",
    "voir la carte": "Ver la carta",
    "haute gastronomie": "Alta gastronomía",
    "l'alchimie": "La alquimia",
    "de l'extraction.": "de la extracción.",
    "collection": "Colección",
    "projects completed": "Proyectos entregados",
    "countries": "Países",
    "carbon-negative projects": "Proyectos de balance de carbono negativo",
    "motion graphics": "Motion graphics",
    "brand films": "Films de marca",
    "interactive": "Interactivo",
    "brand exploration": "Exploración de marca",
    "fleet": "La flota",
    "network": "Red",
    "company": "La empresa",
    "craftsmanship": "Saber hacer",
    "heritage": "Herencia",
    "innovation": "Innovación",
    "infrastructure": "Infraestructura",
    "deploy": "Desplegar",
    "fragrances": "Perfumes",
    "digital craft": "Artesanía digital",
    "e-commerce": "Comercio electrónico",
    "art direction, webgl": "Dirección de arte, WebGL",
    "global edition": "Edición internacional",
    "reserve": "Reservar",
    "owner portal": "Área de propietarios",
    "stack": "Tecnologías",
    "access": "Acceso",
    "initialize": "Iniciar",
    "system architecture": "Arquitectura del sistema",
    "command login": "Acceso de control",
    "missions": "Misiones",
    "events": "Eventos",
    "artists": "Artistas",
    "venues": "Salas",
    "upcoming": "Próximamente",
    "properties": "Nuestros inmuebles",
    "private inquiry": "Solicitud confidencial",
    "exceptional": "Excepcional",
    "examples": "Ejemplos",
    "plugins": "Extensiones",
    "digital experience": "Experiencia digital",
    "brand identity": "Identidad de marca",
    "ai revolution": "Revolución de la IA",
    "ai-optimized routing that reduces energy consumption by 24% per mile.": "Enrutamiento optimizado por IA que reduce el consumo de energía en un 24 % por milla.",
    "autonomous, all-electric, and ai-driven logistics. we don't just deliver packages; we engineer time and efficiency.": "Logística autónoma, totalmente eléctrica y impulsada por IA. No solo entregamos paquetes; diseñamos el tiempo y la eficiencia.",
    "blockchain-verified delivery milestones with real-time biometric scanning.": "Hitos de entrega certificados, con lectura biométrica en tiempo real.",
    "client portal": "Portal del Cliente",
    "engineering the next generation of autonomous, zero-emission logistics for a world that never stops moving.": "Ingeniería de la próxima generación de logística autónoma y cero emisiones para un mundo que nunca deja de moverse.",
    "in-transit: nyc 442": "En tránsito: NYC 442",
    "in-transit: nyc_442": "En Tránsito: NYC_442",
    "our fleet": "Nuestra flota",
    "powered by": "Impulsado por",
    "proof of transit": "Prueba de Tránsito",
    "see pricing": "Ver las tarifas",
    "shift your": "Mueva su",
    "start shipping": "Empezar a enviar",
    "view specifications": "Ver especificaciones",
    "watch logistics flow": "Mira fluir la logística",
  },
  de: {
    "the": "DIE",
    "speed": "GESCHWINDIGKEIT",
    "of": "DES",
    "light.": "LICHTS.",
    "the speed of light.": "Lichtgeschwindigkeit.",
    "en transit : nyc_442": "IN TRANSIT: NYC_442",
    "réserver une table": "Einen Tisch reservieren",
    "réserver votre table": "Ihren Tisch reservieren",
    "réserver": "Reservieren",
    "commander": "Bestellen",
    "commander en ligne": "Online bestellen",
    "devis gratuit": "Kostenloses Angebot",
    "prendre rendez-vous": "Termin vereinbaren",
    "nous contacter": "Kontaktieren Sie uns",
    "nous écrire": "Schreiben Sie uns",
    "appeler": "Anrufen",
    "appeler maintenant": "Jetzt anrufen",
    "voir le menu": "Karte ansehen",
    "voir la carte": "Karte ansehen",
    "haute gastronomie": "Haute Cuisine",
    "l'alchimie": "Die Alchemie",
    "de l'extraction.": "der Extraktion.",
    "collection": "Kollektion",
    "projects completed": "Fertiggestellte Projekte",
    "countries": "Länder",
    "carbon-negative projects": "Projekte mit negativer CO₂-Bilanz",
    "motion graphics": "Motion Graphics",
    "brand films": "Markenfilme",
    "interactive": "Interaktiv",
    "brand exploration": "Markenerkundung",
    "fleet": "Die Flotte",
    "network": "Netz",
    "company": "Unternehmen",
    "craftsmanship": "Handwerkskunst",
    "heritage": "Erbe",
    "innovation": "Innovation",
    "infrastructure": "Infrastruktur",
    "deploy": "Deployen",
    "fragrances": "Düfte",
    "digital craft": "Digitales Handwerk",
    "e-commerce": "E-Commerce",
    "art direction, webgl": "Art Direction, WebGL",
    "global edition": "Internationale Ausgabe",
    "reserve": "Reservieren",
    "owner portal": "Eigentümerbereich",
    "stack": "Technologien",
    "access": "Zugang",
    "initialize": "Starten",
    "system architecture": "Systemarchitektur",
    "command login": "Zugang zur Leitstelle",
    "missions": "Missionen",
    "events": "Veranstaltungen",
    "artists": "Künstler",
    "venues": "Spielstätten",
    "upcoming": "Demnächst",
    "properties": "Unsere Objekte",
    "private inquiry": "Vertrauliche Anfrage",
    "exceptional": "Außergewöhnlich",
    "examples": "Beispiele",
    "plugins": "Erweiterungen",
    "digital experience": "Digitales Erlebnis",
    "brand identity": "Markenidentität",
    "ai revolution": "KI-Revolution",
    "ai-optimized routing that reduces energy consumption by 24% per mile.": "KI-optimierte Routenführung, die den Energieverbrauch um 24 % pro Meile senkt.",
    "autonomous, all-electric, and ai-driven logistics. we don't just deliver packages; we engineer time and efficiency.": "Autonome, vollelektrische und KI-gesteuerte Logistik. Wir liefern nicht nur Pakete; wir entwickeln Zeit und Effizienz.",
    "blockchain-verified delivery milestones with real-time biometric scanning.": "Zertifizierte Lieferschritte mit biometrischer Erfassung in Echtzeit.",
    "client portal": "Kundenportal",
    "engineering the next generation of autonomous, zero-emission logistics for a world that never stops moving.": "Ingenieure die nächste Generation autonomer, emissionsfreier Logistik für eine Welt, die sich niemals stillsteht.",
    "in-transit: nyc 442": "In-Transit: NYC 442",
    "in-transit: nyc_442": "Unterwegs: NYC_442",
    "our fleet": "Unsere Flotte",
    "powered by": "Angetrieben von",
    "proof of transit": "Nachweis des Transits",
    "see pricing": "Preise ansehen",
    "shift your": "Bewegen Sie Ihre",
    "start shipping": "Versand starten",
    "view specifications": "Spezifikationen anzeigen",
    "watch logistics flow": "Sieh zu, wie die Logistik fließt",
  },
  pt: {
    "the": "A",
    "speed": "VELOCIDADE",
    "of": "DA",
    "light.": "LUZ.",
    "the speed of light.": "A velocidade da luz.",
    "en transit : nyc_442": "EM TRÂNSITO: NYC_442",
    "réserver une table": "Reservar uma mesa",
    "réserver votre table": "Reservar a sua mesa",
    "réserver": "Reservar",
    "commander": "Encomendar",
    "commander en ligne": "Encomendar em linha",
    "devis gratuit": "Orçamento gratuito",
    "prendre rendez-vous": "Marcar consulta",
    "nous contacter": "Contacte-nos",
    "nous écrire": "Escreva-nos",
    "appeler": "Ligar",
    "appeler maintenant": "Ligar agora",
    "voir le menu": "Ver o menu",
    "voir la carte": "Ver a carta",
    "haute gastronomie": "Alta gastronomia",
    "l'alchimie": "A alquimia",
    "de l'extraction.": "da extração.",
    "collection": "Coleção",
    "projects completed": "Projetos entregues",
    "countries": "Países",
    "carbon-negative projects": "Projetos de balanço de carbono negativo",
    "motion graphics": "Motion design",
    "brand films": "Filmes de marca",
    "interactive": "Interativo",
    "brand exploration": "Exploração de marca",
    "fleet": "A frota",
    "network": "Rede",
    "company": "A empresa",
    "craftsmanship": "Saber-fazer",
    "heritage": "Herança",
    "innovation": "Inovação",
    "infrastructure": "Infraestrutura",
    "deploy": "Implementar",
    "fragrances": "Perfumes",
    "digital craft": "Artesanato digital",
    "e-commerce": "Comércio eletrónico",
    "art direction, webgl": "Direção de arte, WebGL",
    "global edition": "Edição internacional",
    "reserve": "Reservar",
    "owner portal": "Área de proprietários",
    "stack": "Tecnologias",
    "access": "Acesso",
    "initialize": "Iniciar",
    "system architecture": "Arquitetura do sistema",
    "command login": "Acesso de controlo",
    "missions": "Missões",
    "events": "Eventos",
    "artists": "Artistas",
    "venues": "Salas",
    "upcoming": "Em breve",
    "properties": "Os nossos imóveis",
    "private inquiry": "Pedido confidencial",
    "exceptional": "Excecional",
    "examples": "Exemplos",
    "plugins": "Extensões",
    "digital experience": "Experiência digital",
    "brand identity": "Identidade de marca",
    "ai revolution": "Revolução da IA",
    "ai-optimized routing that reduces energy consumption by 24% per mile.": "Roteamento otimizado por IA que reduz o consumo de energia em 24 % por milha.",
    "autonomous, all-electric, and ai-driven logistics. we don't just deliver packages; we engineer time and efficiency.": "Logística autónoma, totalmente elétrica e impulsionada por IA. Não apenas entregamos pacotes; engenheiramos tempo e eficiência.",
    "blockchain-verified delivery milestones with real-time biometric scanning.": "Etapas de entrega certificadas, com leitura biométrica em tempo real.",
    "client portal": "Portal do Cliente",
    "engineering the next generation of autonomous, zero-emission logistics for a world that never stops moving.": "Engenharia da próxima geração de logística autónoma e zero emissões para um mundo que nunca para de se mover.",
    "in-transit: nyc 442": "Em trânsito: NYC 442",
    "in-transit: nyc_442": "Em Trânsito: NYC_442",
    "our fleet": "A Nossa Frota",
    "powered by": "Alimentado por",
    "proof of transit": "Prova de Trânsito",
    "see pricing": "Ver os preços",
    "shift your": "Mova a sua",
    "start shipping": "Começar a expedir",
    "view specifications": "Ver especificações",
    "watch logistics flow": "Veja a logística fluir",
  },
};
